### ISSUE TITLE
Mozilla Social API integration

### ISSUE THREAD

**Issue by qwertygc** [shaarli/Shaarli#101]
Mozilla à sorti Social API (https://developer.mozilla.org/fr/docs/Social_API). Pourquoi pas faire un plugin pour shaarli ?

**Comment by nodiscc** [comment]
Avec quelles fonctionalités? Un bouton share? (shaarli a déjà un bookmarklet) Une sidebar shaarli? J'ai un peu testé les démos et je vois mal ce que ça apporte pour l'instant. Si quelqu'un peut m'éclairer...

**Comment by qwertygc** [comment]
En gros, c'est comme le bouton share, mais tout est regroupé au sein d'un seul bouton, on gagne de la place ^^

**Comment by nodiscc** [comment]
I have read a bit about Firefox's Social API. Existing services are listed here: https://activations.cdn.mozilla.net/en-US/
I has the benefit of grouping all social media accounts under one toolbar button and/or sidebar.
However, the implementation seems complex (https://developer.mozilla.org/en-US/docs/tag/Social; https://github.com/mixedpuppy/socialapi-demo -what?) and it's not cross-browser. So this should be added as a plugin if someone wants to work on it.

**Comment by e2jk** [comment]
I have created a [page to list all plugin ideas](https://github.com/shaarli/Shaarli/wiki/Ideas-for-plugins), and listed this plugin suggestion there.
I'm closing this issue, please reopen if anyone wants to work on it (or just create a Pull Request and we're done with it ;) )

**Comment by nodiscc** [comment]
@e2jk Thanks, I think it makes sense to close plugin requests that we are no one is willing to work on right now.

**Comment by nodiscc** [comment]
Reopening to make issue visible in issues list (cleaning up the Ideas for plugins wiki page)

**Comment by Marsup** [comment]
@nodiscc I just did it, it was quite simple honestly, about 20 lines of code, I'm not sure it's worth a plugin. Should I proceed with a PR ?

**Comment by nodiscc** [comment]
> about 20 lines of code
> Should I proceed with a PR

Please yes. If it doesn't add much complexity and works as expected, it can be merged.

**Comment by Marsup** [comment]
How do I run the tests if any ? Just making sure I didn't break anything.

**Comment by nodiscc** [comment]
You can send your pull request and it will be manually reviewed and tested for some time before the merge.

We don't have a clear test procedure currently, we just make sure all Shaarli features are working correctly (yes a list would be nice) and wait for https://github.com/shaarli/Shaarli/issues/71 and https://github.com/shaarli/Shaarli/issues/130
