### ISSUE TITLE
0.9.0 to 0.9.2 produces empty page

### ISSUE THREAD

**Issue by gerroon** [shaarli/Shaarli#1011]
Hi

I just upgraded from 0.9.0 to 0.9.2 using the tar release (shaarli-v0.9.2-full.tar.gz)  and I copied the data folder. I made sure apache has the write permissions but all I get is a blank page

Debian Wheezy 32bit
Server version: Apache/2.2.22 (Debian)

Please bear in mind that 0.9.0 is a working version on my server.

thanks

**Comment by virtualtam** [comment]
Hi @gerroon,

Do you have access to the web server's logs? Usually `/var/log/apache2/error.log`, unless overridden in the virtualhost configuration.

What is the PHP version running on the server?

Please note that PHP < 5.5 is not supported since Shaarli 0.9.x - https://shaarli.readthedocs.io/en/master/Server-requirements/

**Comment by gerroon** [comment]
PHP 5.6.31-1~dotdeb+7.1 (cli) (built: Jul 11 2017 06:53:16) 
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2016, by Zend Technologies



Maybe this ?

[Thu Nov 02 18:04:16 2017] [error] [client 192.168.2.106] PHP Fatal error:  Uncaught exception 'RainTpl_NotFoundException' with message 'Template linklist not found!' in /var/www/ShaarlI/inc/rain.tpl.class.php:268\nStack trace:\n#0 /var/www/ShaarlI/inc/rain.tpl.class.php(164): RainTPL->check_template('linklist')\n#1 /var/www/ShaarlI/application/PageBuilder.php(153): RainTPL->draw('linklist')\n#2 /var/www/ShaarlI/index.php(680): PageBuilder->renderPage('linklist')\n#3 /var/www/ShaarlI/index.php(1071): showLinkList(Object(PageBuilder), Object(LinkDB), Object(Shaarli\\Config\\ConfigManager), Object(PluginManager))\n#4 /var/www/ShaarlI/index.php(2306): renderPage(Object(Shaarli\\Config\\ConfigManager), Object(PluginManager), Object(LinkDB), Object(History))\n#5 {main}\n  thrown in /var/www/ShaarlI/inc/rain.tpl.class.php on line 26
8

**Comment by virtualtam** [comment]
This could be related to:
- the location and/or availability (permissions) for the RainTPL templates:
    - `tpl/default` when using the latest theme
    - `tpl/vintage` when using the legacy theme
    - `tpl/<custom>` when using a custom theme
- the configuration of the Shaarli instance, `data/config.json.php`:

```json
<?php /*
{
  "resource": {
    "raintpl_tpl": "tpl\/",
    "theme": "default"
  }
}
*/ ?>
```

**Comment by gerroon** [comment]
I am not sure really. I just copied the new stuff from the tar and copied my data back in to the proper place like it said in the update section of the docs and made sure the permissions are ownbed by the server

```
 "resource": {
        "data_dir": "data",
        "config": "data\/config.php",
        "datastore": "data\/datastore.php",
        "ban_file": "data\/ipbans.php",
        "updates": "data\/updates.txt",
        "log": "data\/log.txt",
        "update_check": "data\/lastupdatecheck.txt",
        "raintpl_tpl": ".",
        "raintpl_tmp": "tmp\/",
        "thumbnails_cache": "cache",
        "page_cache": "pagecache",
        "history": "data\/history.php",
        "theme": "tpl"
    },

```

**Comment by virtualtam** [comment]
Looks like erroneous values, resulting in the HTML templates not being found:

`"raintpl_tpl": ".",`
`"theme": "tpl"`

Did you use a custom theme on your previous installation?

In any case,
- `raintpl_tpl` should point to the parent theme directory (`tpl`)
- `theme` should contain the name of the active theme (`default`, `vintage`)

**Comment by gerroon** [comment]
@virtualtam 

Thanks for your input. I have no idea how those values got in there, I also do not know anything about all this stuff, just a user. It works in 0.9.0 so I was expecting it would work in 0.9.2 as well.

Anyway after using your recommended line there, the upgrade seems to work now.

**Comment by virtualtam** [comment]
Glad to know it's working, I'm closing this issue as solved :)
