### ISSUE TITLE
Where do I find my secret token?

### ISSUE THREAD

**Issue by PrimordialHelios** [shaarli/Shaarli#1018]
I'm tryign to connect my Miniflux instance with my Shaarli instance, which requires giving my "Shaarli secret" to Miniflux, but I can't find that anywhere in Shaarli. I've checked the documentation, looked all through Shaarli, and looked through the github repo, but I can't find it. Am I missing something?

**Comment by ArthurHoaro** [comment]
Hi. You can find your API secret token in the configure page. However, you need Shaarli v0.9.0+ to have the REST API.

**Comment by PrimordialHelios** [comment]
I guess I somehow got an older version of Shaarli when I was installing it. 

The bookmarks aren't syncing, though. Are there any other steps I would need to take for the REST API to work? I'm not sure if this issue is on Shaarli's end or Miniflux's.

**Comment by ArthurHoaro** [comment]
Having the REST API enabled and a secret key configured should be enough.

![](https://i.imgur.com/WqTV14V.png)

I'm not sure how Miniflux is supposed to use Shaarli's API, so I suggest that you open a support issue there.

**Comment by PrimordialHelios** [comment]
Alright, thanks. Looks like an issue with Miniflux not sending API requests. I appreciate the help!
