### ISSUE TITLE
Bookmark files with newline in description tag are not properly imported

### ISSUE THREAD

**Issue by tschlotfeldt** [shaarli/Shaarli#1021]
Importing a bookmark file from SemanticScuttle results in not properly imported bookmarks if the description tag contains a line break.

**Comment by ArthurHoaro** [comment]
Hi, would you be able to provide a sample?

**Comment by tschlotfeldt** [comment]
Sure ;-) I had round about 1,000 bookmarks to import when I rercognized this behaviour. After  a little bit of trial and error I found the reason. I removed all occurrence of newlines in the description tag in my bookmark file with sed and the problem was gone.

Here is an example:

https://gist.github.com/tschlotfeldt/39a91af8d3bf3776d767b583d644c9f9
