### ISSUE TITLE
Notes links use 443 port

### ISSUE THREAD

**Issue by husimo** [shaarli/Shaarli#1022]
Hello,
I have a trouble in my Shaarli as you can see it here : https://husimo.fr/shaarli/?ireqPQ
The note link is http and then you have the 443 port displayed in the URL. But my browser doesn't like it so these links are not working.
I think it may be related to the fact I'm using OVH provided for hosting (free offer with domain name with 10MB space, just what I need for Shaarli !), with SSL Let's encrypt certificate.
I have the last version of Shaarli.
Thank you

**Comment by husimo** [comment]
Actually, $_SERVER['SCRIPT_URI'] gives me [SCRIPT_URI] => https://husimo.fr:443/shaarli/test.php so I pretty sure that's not shaarli related. OVH is doing something weird...Is there any way to force URL base in Shaarli ?

**Comment by virtualtam** [comment]
Hi @husimo !

The server configuration is worth checking, as when selecting a permalink, the link to the Shaarli index is wrong:

- expected: https://husimo.fr/shaarli/index.php or https://husimo.fr/shaarli/
- actual: https://husimo.fr/shaarli/index.php?permalink

What is the setup for this webserver? E.g. web server (Apache HTTPD, Nginx, etc.) version, PHP version, VirtualHost configuration...

**Comment by ArthurHoaro** [comment]
Your issue doesn't come from `SCRIPT_URI`, but is caused by the reverse proxy settings:

```
    [HTTP_X_FORWARDED_PROTO] => http
    [HTTP_X_FORWARDED_PORT] => 443
```

The protocol should be `https` instead of `http`. We could add a check in `serveur_url()`, just as we do for non proxied HTTPS vs. port 443 [here](https://github.com/shaarli/Shaarli/blob/master/application/HttpUtils.php#L330).

**Comment by husimo** [comment]
Yeah, I think it would be useful because I don't think why OVH did it that way but I don't think I will be able to make them change their configuration :-1: 
Thank you :-)

**Comment by ArthurHoaro** [comment]
I've submitted a PR, but you should open an issue to OVH since it really looks like bad configuration.
