### ISSUE TITLE
Firefox Share API and Shaarli Firefox addon deprecated in Firefox 57

### ISSUE THREAD

**Issue by techexo** [shaarli/Shaarli#1023]
Hello everyone,

I was wondering how to share on Shaarli with the latest update of Firefox (57, Quantum). Indeed, the [add-on shaarli](https://addons.mozilla.org/fr/firefox/addon/shaarli/) is now deprecated ; and I cannot see in this version the "Share this page" button using Firefox Social API.

Is there something in the development pipeline to allow Firefox users to easily use Shaarli? Or am I just plain stupid and did not find the Share button in Firefox Quantum?

Edit: I confirm that Social API has been disabled with Firefox 57: https://developer.mozilla.org/en-US/Firefox/Releases/57#APIs_2

Thanks!

**Comment by nodiscc** [comment]
HI @techexo , I was not aware that Social API was going to be deprecated in Firefox 57. At the moment there is no plan to replace Shaarli's `Add to Firefox Share`, so the possibilities are:

 * Stay on [Firefox 52 ESR](https://www.mozilla.org/en-US/firefox/organizations/) which still supports Social API (it is what I personally use). It will still be supported by mozilla [until Firefox 61 comes out](https://www.mozilla.org/en-US/firefox/organizations/faq/), at which point Firefox 59 will become the new ESR (June 26 2018)
 * Ask on https://bitbucket.org/aeris/shaarli-extension if the addon maintainer is planning to port it to WebExtensions. The first comment on https://bugzilla.mozilla.org/show_bug.cgi?id=1388902 seems to indicate this should be doable.
 * Use the bookmarklet from the tools page (with the usual [limitations](https://shaarli.readthedocs.io/en/master/Bookmarklet/#troubleshooting-the-bookmarklet-doesnt-work-with-a-few-websites-eg-githubcom))
 * Write a Firefox WebExtension from scratch.

Thanks for reporting this, hopefully someone can come up with a solution.

This also means we should remove Firefox Share features from Shaarli when it reaches its real EOL, June 26 2018.

**Comment by techexo** [comment]
Thanks for your (really) quick answer. For mental health reasons, I won't stay on Firefox ESR, the leap in speed is just to big with Firefox Quantum. :)

I doubt that aeris will port his extension to WebExtensions as the repository seems quite dead.
However, it seems that there is a compatibility between WebExtensions and Chrome extensions, so I asked if Simpleshare would consider a port for Firefox Quantum: https://github.com/Devenet/SimpleShare/issues/3

I will keep searching for solutions and update this post.

**Comment by virtualtam** [comment]
Hi @techexo & @nodiscc!

There is an existing discussion on (re)writing a Shaarli extension using modern standards at #825

**Comment by ikipatang** [comment]
@virtualtam #825 ask for too much sophisticated features
We just need a `share link` and a `go to shaarli`

**Comment by ikipatang** [comment]
@techexo Nearly a good news, i made something that should have worked today
https://github.com/ikipatang/shaarli-web-extension
Unfortunatly, i have a bug of encoding on linux but it works on windows
You can try it if you wish: https://github.com/ikipatang/shaarli-web-extension/tree/master/xpi-release

**Comment by techexo** [comment]
@ikipatang Great work, it worked perfectly on Windows!

**Comment by xrat** [comment]
Currently, I use [AddToAny: Share Anywhere](https://addons.mozilla.org/firefox/addon/addtoany-share/) which allows to add custom services/links, and [Bookmarklets context menu](https://addons.mozilla.org/firefox/addon/bookmarklets-context-menu/) which makes the bookmarklets work again (this one I'll probably keep in any case).

**Comment by techexo** [comment]
To summarize, there is two alternatives very close to what we used before Firefox Quantum:
1. https://github.com/ikipatang/shaarli-web-extension
2. https://github.com/Mte90/Share-Backported (https://github.com/Mte90/Share-Backported/issues/27)

@Mte90 said that he fixed the issue of the pop-up windows not being the right size, but the release has not rolled-out yet (I point it out because I saw that it was in the TODO list of @ikipatang).

**Comment by ikipatang** [comment]
@techexo i have released the popup dimension settings (version 0.2.6)

**Comment by husimo** [comment]
Currently I still use "AddToAny" because I use two Shaarlis, as the new shaarli addon doesn't provide (yet ?) the functionality to use multiple shaarlis.
Yesterday I discovered "Url forwarder" on Android. It creates a Share item on Android and it forwards the current URL to Shaarli.

**Comment by xrat** [comment]
Me too. I have currently 3 Shaarli instances. Generally, I use the Bookmarklet context menu addon.

**Comment by nodiscc** [comment]
Firefox Share integration has been removed in https://github.com/shaarli/Shaarli/pull/1026, https://github.com/shaarli/Shaarli/pull/1232. Currently working addons can be found at https://shaarli.readthedocs.io/en/master/Community-&-Related-software/. Ideas for an advanced browser addon can be found at https://github.com/shaarli/Shaarli/issues/825.

Please file enhancement requests/bug reports on the relevant issue trackers, or in the linked issue.
