### ISSUE TITLE
Ability to filter out/hide private links 

### ISSUE THREAD

**Issue by averymd** [shaarli/Shaarli#1030]
I use Shaarli with `hide_public_links` and `force_login` both set to true, so my entire set of links requires authentication. I mark personal links as "private" and leave professional stuff unmarked. It would be excellent if I could choose to have private links filtered _out_ by default in listings and searches (even when searching myself) and use something like the current "filter private links" button to choose to show them.

I think this would be a new feature, unless I'm missing some existing way to do this with hidden tags.

**Comment by virtualtam** [comment]
Hi @averymd!

It is currently possible to show only private links; so we would need to add the possibility to show only public links to a logged in user, as well as provide the corresponding configuration option.
