### ISSUE TITLE
Error 500 after logging in: End of script output before headers

### ISSUE THREAD

**Issue by Andrewskiz** [shaarli/Shaarli#1035]
I haven't changed anything, though I am on shared hosting and they may have upgraded some software or changed some variable. Apache 2.4, PHP 7.1, Shaarli 0.9.2

When logged out shaarli displays fine, but I receive an error 500 when trying to log in. Error log shows:
End of script output before headers: index.php
End of script output before headers: index.php, referer: shaarli/?do=login

**Comment by Andrewskiz** [comment]
Interestingly enough, I can still access the share page and see my tags when I start typing, but the index page when logged in is still giving me an error 500.

**Comment by nodiscc** [comment]
* Does clearing the caches and tmp directories solve the problem?
* Could this be a damaged file? I'd check that your index.php (maybe other files?) matches the one in the [original download](https://github.com/shaarli/Shaarli/releases/download/v0.9.2/shaarli-v0.9.2-full.tar.gz) (using diff, sha256sum...)
* (Backup your Shaarli installation!!) Does reinstalling Shaarli (or installing it in another directory) solve the problem?

**Comment by Andrewskiz** [comment]
Cleared the cache and tmp folders, verified the checksum, and did a clean install of Shaarli. Install worked, but upon logging in I get the same error.

**Comment by ArthurHoaro** [comment]
Can you check all your file permissions? Which shared hosting are you using?

**Comment by Andrewskiz** [comment]
`drwxrwxr-x   5 217355  217355     27 Dec 12 17:13 application
drwxrwxrwx   2 217355  217355      3 Dec 12 17:13 cache
-rw-rw-r--   1 217355  217355   1338 Oct  7 10:23 composer.json
-rw-rw-r--   1 217355  217355  86295 Oct  7 10:23 composer.lock
drwxrwxrwx   2 217355  217355     10 Dec 12 18:07 data
drwxrwxr-x   4 217355  217355      4 Dec 12 17:15 doc
drwxrwxr-x   2 217355  217355      9 Dec 12 17:15 images
drwxrwxr-x   2 217355  217355     10 Dec 12 17:15 inc
-rw-rw-r--   1 217355  217355  93035 Oct  7 10:23 index.php
drwxrwxrwx   2 217355  217355      3 Dec 12 17:15 pagecache
drwxrwxr-x  12 217355  217355     13 Dec 12 17:15 plugins
-rw-rw-r--   1 217355  217355     21 Oct  7 10:23 shaarli_version.php
drwxrwxrwx   2 217355  217355     12 Dec 12 18:08 tmp
drwxrwxr-x   4 217355  217355      4 Dec 12 17:15 tpl
drwxrwxr-x  13 217355  217355     14 Dec 12 17:17 vendor`

I am using nearlyfreespeech.net hosting

**Comment by ArthurHoaro** [comment]
After a fun session of hide n seek, I've found your issue. Your host has a misconfigured/compiled `php-intl` extension. The module is loaded, but generates a silent segmentation fault on `IntlDateFormatter` instantiation.

Reproduction, create a `tmp.php` file:
```php
<?php

echo 'pass1'. PHP_EOL;
new   IntlDateFormatter('en_US', IntlDateFormatter::SHORT, IntlDateFormatter::SHORT);
echo 'pass2'. PHP_EOL;
```
Run:
```bash
$ php tmp.php
pass1
Segmentation fault
```

I'll let you report the issue to your host provider, and I'll close this issue as is not directly related to Shaarli.
