### ISSUE TITLE
Inconsistencies in COPYING

### ISSUE THREAD

**Issue by nodiscc** [shaarli/Shaarli#104]
https://github.com/shaarli/Shaarli/blob/master/COPYING

We still have a GPLv3 header at the end of the file. AFAIK there's no GPL code in Shaarli anymore (qr.js is now licensed under MIT). Right? If so, we should remove it.

There's no copy of the Creative Commonts Attribution (CC-BY) license in COPYING.

**Comment by pikzen** [comment]
Actually, according to https://github.com/neocotic/qr.js/blob/master/LICENSE.md, qr.js is under the GPLv3, which is confirmed by http://neocotic.com/qr.js/changes.

Pushed a PR to fix it.

**Comment by e2jk** [comment]
Correct, qr.js was incorrectly relicensed to MIT, it got fixed last summer:
https://github.com/neocotic/qr.js/issues/23
