### ISSUE TITLE
Problems while upgrading from sebsauvage's Shaarli 0.0.41 beta to 0.8.4

### ISSUE THREAD

**Issue by MutoKenji** [shaarli/Shaarli#1040]
Hey there,
I encountered exactly a similar issue than this one here https://github.com/shaarli/Shaarli/issues/847
I upgraded from the lastest sebsauvage version (years old!) to the newest stable one : 0.8.4
I did that by extracting the content of the new folder on my server, and replacing my old data folder in it.

I had the following notices : 

> Notice: Undefined index: titleLink in /public_html/fosteb_new_084/application/config/ConfigPhp.php on line 84
> 
> Notice: Undefined index: privateLinkByDefault in /public_html/fosteb_new_084/application/config/ConfigPhp.php on line 84
> 
> Notice: Undefined index: config in /public_html/fosteb_new_084/application/config/ConfigPhp.php on line 86

I read a couple of posts here and tried various things. Then, I copied only the datastore.php in data, and did a config from scratch.
But I still encoutered the issue when I tried to login

> You must specify an integer as a key.

Therefore, I had to use the workaround given here https://github.com/shaarli/Shaarli/issues/775

> 
    Create a file called data/updates.txt.
    Paste this string in the new file updateMethodRenameDashTags
    Login to Shaarli.
    Delete the update file.

And in the end it works.

But it was quite frustrating! :-)

I hope it's clear.

**Comment by ArthurHoaro** [comment]
Thanks for the feedback. I'll take a look at these warnings. Did you get them while being logged out?

> But I still encoutered the issue when I tried to login

This has been fixed by #776 but was only released in `v0.9.0`.

**Comment by MutoKenji** [comment]
Yes I had them while being logged out. I think one of them remained when
logged in.

2017-12-18 13:51 GMT+01:00 ArthurHoaro <notifications@github.com>:
