### ISSUE TITLE
Allow anonymous posting

### ISSUE THREAD

**Issue by jvoisin** [shaarli/Shaarli#1045]
I'm running a private Shaarli instance behind http authentication (mainly because I don't trust PHP at all.), so I don't need a *second* authentication layer. It would be nice to have a tickbox to allow anonymous submissions.

**Comment by virtualtam** [comment]
Hi @jvoisin,

There is an `open_shaarli` configuration setting to allow everyone to post on a Shaarli instance, see https://shaarli.readthedocs.io/en/master/Shaarli-configuration/#security

Given this is a sensitive setting that is scarcely used, it is not configurable via the Web UI; you need to edit `data/config.json.php` to allow public write access.

**Comment by jvoisin** [comment]
Wonderful, thank you ♥

**Comment by virtualtam** [comment]
You're welcome :)
