### ISSUE TITLE
Facebook integration into bookmarklet code

### ISSUE THREAD

**Issue by bzupp** [shaarli/Shaarli#1051]
In the bookmark interface, I'd love to be able to send the link and textbox (and tags?) content to Facebook (or twitter) account...I wonder if this can be done with a tweak to the bookmarklet javascript. 

LOVE Shaarli! Thanks for all you work on the app. I use it daily.

**Comment by virtualtam** [comment]
Hi @bzupp!

There is an existing [shaarli2twitter](https://github.com/ArthurHoaro/shaarli2twitter) plugin, that allows posting _new_ entries as tweets.

You might also be interested in the [Social](https://github.com/alexisju/social) plugin that adds buttons to share an _existing_ Shaarli entry to social platforms.

There is no Facebook integration (that I know of) for now, though.

**Comment by bzupp** [comment]
Thank you!
