### ISSUE TITLE
Call to undefined function mb_convert_case()

### ISSUE THREAD

**Issue by smth** [shaarli/Shaarli#1053]
When I try to use the text search I get the following error:

`Fatal error: Call to undefined function mb_convert_case() in /path/to/public_html/application/LinkFilter.php on line 183`

v0.9.2

**Comment by virtualtam** [comment]
Hi @smth,

The PHP `mbstring` extension must be installed and enabled, and is part of Shaarli requirements, see https://shaarli.readthedocs.io/en/master/Server-requirements/

It should be present and enabled by default on most Debian- and Ubuntu-based systems, but you need to install and enable it on CentOS/RHEL/Fedora and Windows.

Let us know if you're running another system so we can update the docs accordingly :)

**Comment by smth** [comment]
Hi @virtualtam 
`mbstring` was not enabled by default on my (Linux / cPanel) host, and this was indeed the problem. Thanks
