### ISSUE TITLE
Original Ideas/Fixme page

### ISSUE THREAD

**Issue by nodiscc** [shaarli/Shaarli#106]
I found this list at http://sebsauvage.net/wiki/doku.php?id=php:shaarli:ideas

It's a collection of the ideas proposed by sebsauvage and contributors back when the project was hosted on sebsauvage.net. Some are interesting, some are fixed already, and some are probably `wontfix` :) I'm pasting it here as a reference; feel free to comment/propose decisions for each item. If a particular item needs discussion, please open an issue specifically for it.

[EDIT 2015-09-15] Sort issues by resolution, add formatting (@virtualtam)
[EDIT 2016-02-15] Cleanup old entries, update https://lite6.framapad.org/p/3I7CN1Drms (@nodiscc]
## Status: Done
- **Private Shaarli**> In config, add an option to make the Shaarli private: The Shaarli will not show any link, except if you are logged in. (This can also be used to temporarly “close” a shaarli). - #188 - Hide all links to non logged-in users - #197 - Allow disabling all public links
-  **W3C compliance** > Make Shaarli HTML/CSS code W3C compliant (apply idleman patch) > Correct tag encoding in tag cloud. > Include Timo's patch for proper charset/encoding detection in page title. - #64, #77, #103 - Make Shaarli W3C-compliant - #54 - Use `urlencode()` in tag cloud
- **Documentation** > Write proper user manual, in a separate wiki page (installation, bookmarklet usage, keyboard  speed-up tips, how to use Shaarli as a pastebin/online notepad, who to use Shaarli as twitter, how to customize Shaarli (colors, logo, templates…), backup/restore, how to filter picture wall or RSS/ATOM feed by tag or text search…) Take a look at the [README](https://github.com/shaarli/Shaarli/blob/master/README.md), [CONTRIBUTING](https://github.com/shaarli/Shaarli/blob/master/CONTRIBUTING.md) and [Wiki](https://github.com/shaarli/Shaarli/wiki) pages ;-)
- **Feeds:** permalink / actual link > In RSS/ATOM feed, add a parameter in URL in order to choose which URL to put in <link> tag: Permalink or final link. - #63 - enable/disable permalinks for RSS
- *_Anchor after link edition *_> After adding/editing a link, go back to the same page and scroll to the item which has been edited (using an anchor).
- **Default links**> In the default database (the 2 links created when you start a new Shaarli), use ZeroBin instead of Pastebin.
- **Deferred Javascript**> Defer javascript execution to speedup page display (as javascript is not used to build pages).> Add paging to picwall? - #132 - Lazy-load images with bLazy - #148, #165, #221 - Autocomplete with awesomeplete
### Batch operations

> Allow mass operations (on a group of bookmarks) (eg. add/remove a tag, delete, change private flag…)
- #137 - batch-add multiple links
### Internationalization (translation)

> Prepare source for translation.
> Sniff browser locale/language ($_SERVER['HTTP_ACCEPT_LANGUAGE']):
> - automatically choose corresponding translation if available.
> - automatically format date. done (Note: some servers do not have locales like “fr_FR” installed… this includes mine :-/ )
- #121 - Translate Shaarli
### Weekly, monthly pages

> - Add weekly and monthly pages like the daily page.
> - Filter links by date (between two dates ?) 
> - Add better navigation in the “Daily” page (calendar ?)
- #160 - Add weekly and monthly views
- #161 - Add a date picker
### Refactoring

> Re-write shaarli entirely (better object model, and use namespaces to avoid conflicts)
- #324 - Refactoring todolist
- #71 - Unitary tests
- #95 - Coding style compliance
### Admin tools

> Add statistics ? (database size, number of links (private/public), free space on webspace) (No access statistics)
- #247 - Statistics

> Allow 1-click Shaarli upgrade in admin interface.
- #248 - 1-click Shaarli upgrade
### Search

> When using fulltext search, highlight the words in results.
- #205 - Highlight search results
### QRCode

> Allow configuration of QRCode generation URL in config screens.
- #57, #285 - Move QRCode as a plugin
### Thumbnails

> Custom thumbnails
- #153 - Generic thumbnailer
### ~~Go multi-user~~

> - One data file (Not one data file per user)
> - Entries can be:
>   - Public : Anyone can see them.
>   - Shared : Only logged-in users can see them.
>   - Private : Only the user who created them can see them.
- ~~#15 - Multi-user Shaarli~~
- #204 -  Shaarli "farm"/multiple user accounts management tool
### ~~API~~

> Create Shaarli API:
> - Post links (using HMAC authentication)
> - Extract data (search by tag, full text), in json format.
> - Others ?
- #16, #113 - API
- #316 - Import / Export database
### ~~Disable thumbnails~~

> Allow the visitors to disable thumbnails.

See addons such as https://requestpolicycontinued.github.io/, in the future all thumbs will be cached
### Bookmarklet

> - When using the bookmarklet button on a blank page (eg. about:blank), create a self-pointing entry (like “Add link” > Enter).
> - When using the bookmarklet and the login fails in the popup window, properly redirect to the initial &post=… URL.
> - Find a way, when you find an interesting entry on another shaarli, to import easily the entry in your shaarli (adding a “via” in description pointing to the permalink of the original entry).
### Misc.

Copy of the DONE, REPORTED, and WONTFIX sections from https://lite6.framapad.org/p/3I7CN1Drms

```
DONE
/////// After adding/editing a link, go back to the same page and scroll to the item which has been edited (using an anchor). ////////// **DONE**
////// Write proper user manual, in a separate wiki page (installation, bookmarklet usage, keyboard  speed-up tips, how to use Shaarli as a pastebin/online notepad, who to use Shaarli as twitter, how to customize Shaarli (colors, logo, templates…), backup/restore, how to filter picture wall or RSS/ATOM feed by tag or text search…) ////// **DONE**
/////// Correct tag encoding in tag cloud. ////// **DONE**
////// Make Shaarli HTML/CSS code W3C compliant (apply idleman patch) ////// **DONE**, thanks @virtualtam @ArthurHoaro //////
///// In config, add an option to make the Shaarli private: The Shaarli will not show any link, except if you are logged in. (This can also be used to temporarly “close” a shaarli). ////// **DONE**
////// In RSS/ATOM feed, add a parameter in URL in order to choose which URL to put in <link> tag: Permalink or final link. done.
////// Sniff browser locale/language ($_SERVER['HTTP_ACCEPT_LANGUAGE']): => done (see autoLocale() )////// 


Reported
////// Add weekly and monthly pages like the daily page. ////// Accepted, see below //////
////// Add better navigation in the “Daily” page (calendar ?)////// Accepted, see https://github.com/shaarli/Shaarli/issues/161
////// Prepare source for translation. ////// Accepted, https://github.com/shaarli/Shaarli/issues/21
////// Filter links by date (between two dates ?) ////// Accepted, see https://github.com/shaarli/Shaarli/issues/160 and https://github.com/shaarli/Shaarli/issues/246 
////// When using fulltext search, highlight the words in results. //////  Accepted https://github.com/shaarli/Shaarli/issues/205
////// Show new links since last visit ? (maybe using a cookie which records the linkdate of the latest news ?) //////  => Accepted https://github.com/shaarli/Shaarli/issues/244
////// Images and video embedding: Show a collapsed space the user can open to see the links video or image.//////  => https://github.com/shaarli/Shaarli/issues/245
////// Add statistics ? (database size, number of links (private/public), free space on webspace) (No access statistics) //////  https://github.com/shaarli/Shaarli/issues/247
////// Allow 1-click Shaarli upgrade in admin interface. //////  https://github.com/shaarli/Shaarli/issues/248
/////// 24. Add better navigation in the “Daily” page (calendar ?) Discussed in #106. Is there an open issue? ACCEPTED- https://github.com/shaarli/Shaarli/issues/161 ////

Wontfix
////// Archive a copy of the link (page, image…) ? ////// Wontfix, see below, added to the doc, external tool //////
////// Allow spaces in tags. ////// Wontfix, see https://github.com/shaarli/Shaarli/issues/70 //////
////// Allow the visitors to disable thumbnails. ////// WONTFIX, you can use addons such as https://requestpolicycontinued.github.io/, in the future all thumbs will be cached //////
////// Automatic backups (every week ?) (how ? Copy file under a name with date ? email ?) ////// WONTFIX, see below, added to the doc, external tool //////
//////  Go multi-user: //////  WONTFIX, https://github.com/shaarli/Shaarli/issues/15
////// Add paging to picwall ////// ? => lazyloading
////// WONTFIX 40. Archive a copy of the link (page, image…), Won't fix.,  - Third party tool (nodiscc)////// 
/////// 33. Try to support description attribute in Scuttle exports. WONTFIX, scuttle userbase is very small. A thrid-party conversaion script can do the job (nodiscc) ///////
//////// 25. Allow spaces in tags. Won't fix for now.  - No. (nodiscc) ////////////// 
////// WONTFIX 1. multi-user: Won't fix for now as see in #15.  - possible way proposed in  https://github.com/shaarli/Shaarli/issues/204. Multi user related : One data file (Not one data file per user),  Entries can be: Public : Anyone can see them., Shared : Only logged-in users can see them.,   Private : Only the user who created them can see them.//////
////// WONTFIX ~~Backup, archive~~ > - Automatic backups (every week ?) (how ? Copy file under a name with date ? email ?) > - Archive a copy of the link (page, image…)? > - Other export/import options ? (CSV, RDF, single HTML file… ?) > - Support Firefox json export (because Firefox HTML export does not export tags (!)). See [nodiscc/shaarchiver](https://github.com/nodiscc/shaarchiver)//////
//// WONTFIX ~~Tags from outer space~~ > Allow spaces in tags.- ~~#70 - Comma-separated tags~~////
```

**Comment by virtualtam** [comment]
Thanks for starting this thread! ;-)
As some of these points have been regularly mentioned by / discussed with fellow Shaarli users & readers, here are some thoughts about them...

> Go multi-user

Shaarli being mono-user has both pros & cons:
* pros: personal, easy to setup, no bothering about user management / access rights;
* cons:
 * in case you want several persons to contribute to the same instance, the credentials have to be shared (argh!),
 * else, there has to be one Shaarli instance for each user; it could be more comfy to have a single instance, and provide each user/group its own sharing space.

Having the possibility to provide each user his/her own space on the same instance has some benefits:
* easier sharing,
* less administration workload: setup, updates, virtualhosts, DNS, etc.,
* better accessibility: easy creation of Shaarli spaces for non-computerscientist users ;-)

> Automatic backups

That would be great! We're currently running cron jobs that backup the `data` dir and tags it with a timestamp, which is OK... except if your server crashes and you lose your data.
Possible solutions could be:
* send the (encrypted?) data as a mail attachment; being mostly text, it's very lightweight (1000 links => 200 Ko);
* nerd-friendly: commit the changes on a (private) SCM repository ;-)

> Sniff browser locale/language

Does Shaarli even have translation support? Having GNU Gettext / Transifex / <your fav l10n/i18n module> implemented would be an awesome starting point.

> Filter links by date (between two dates ?)

Accurate dates may not be very convenient here, maybe providing user friendly date ranges would suffice? E.g. `last N weeks` or `last N months`.

> Add better navigation in the “Daily” page (calendar ?)
> Add weekly and monthly pages like the daily page.

I know of very few people who actually use the Daily page (despite its nice, vintage CSS); a better navigability could make it a bit more popular:
* several views: daily, weekly, monthly (organizer-like view);
* calendar view.

> Add statistics? (database size, number of links (private/public), free space on webspace)

A tools / admin page with stats would be nice; there isn't much data to be displayed, though...

> Archive a copy of the link (page, image…)?

+1 for an [Autoblog](https://github.com/mitsukarenai/Projet-Autoblog/wiki/Autoblog-Project)-like plugin ;-)
Most 404s we've seen come from multimedia content (YouTube, Dalilymotion, Soundcloud, etc.) that is deleted or made private for miscellaneous reasons. For those, it would be cool to be able to generate a list / command list to feed a media downloader (e.g. [youtube-dl](https://github.com/rg3/youtube-dl/), which features an impressive list of content extractors).

> Re-write shaarli entirely (better object model, and use namespaces to avoid conflicts)

<:trollface:>
Isn't complete code rewrite the Holy Grail of any developer?
 
Honestly, we'd love to, using a modern framework's buit-in features (e.g. Symfony/Zend for clean PHP, Django/Pylons for cool Python, <you fav framework> for <your fav web language>), responsive design (hello Bootstrap, Ink & co!), and so on...

But spare time has become scarce lately, and we feel no urge in fixing something that has been running smoothly for years :neckbeard:

Additionally, this mainly depends on the project's goals: should it stay KISS? should it become more feature-rich? Is the wheel tired of being invented a N<sup>th</sup> time?
</:trollface:>

**Comment by nodiscc** [comment]
Hi @virtualtam nice to have your insight! I have to think a bit more about some points you mentioned, but here are some ideas. **Incoming wall of text.**

> Automatic backups

We shouldn't let Shaarli handle these. A cron job on the server can handle sending mail attachments, committing and pushing to a VCS, rsyncing to remote machine ... whatever you can imagine. This can also be done from a client using software like https://github.com/nodiscc/shaarchiver (early draft, but you can already use https://github.com/nodiscc/shaarchiver/blob/master/export-shaarli.py to do periodic backups on your laptop; this is what I use). The data is already easily exportable (just copy the file tree, or export HTML/query RSS), I think we should let _backup_ software handle the backups.

> We're currently running cron jobs that backup the data dir and tags it with a timestamp, which is OK... except if your server crashes and you lose your data.

A backup with no offsite copy is not a backup :)

> Having GNU Gettext / Transifex / implemented would be an awesome starting point.

Yes! [i18n](https://en.wikipedia.org/wiki/Internationalization_and_localization) support would be great and is probably a major step once we're done with 0.9beta.

> Filter links by date (between two dates ?)

I think either that or your idea (user-friendly ranges) would be fine; how should it look like in the UI ?

> several views: daily, weekly, monthly (organizer-like view);

Yes definitely, and it's related to the previous point (if we can efficiently filter links by date this is doable)

> Archive a copy of the link (page, image…)? [...] generate a list / command list to feed a media downloader (e.g. youtube-dl

There is support for this in [shaarchiver](https://github.com/nodiscc/shaarchiver), basically just [run the `bookmarks-fetcher.py` on your HTML export](https://github.com/nodiscc/shaarchiver#usage) and it will `youtube-dl` your media. I still have to add proper support for downloading pages (see the issues). Contributions/ideas are welcome. <sub>I have it set up to only attempt `youtube-dl` on links that are [tagged with specifig tags](https://github.com/nodiscc/shaarchiver/blob/master/bookmarks-fetcher.py#L36), but it could be configured to force youtube-dl on all links.</sub>

Note that there is currently support in Shaarli for requesting previous versions of your links from [archive.org](https://archive.org/web/). This doesn't guarantee that your link will already be archived though, but merely doing a `curl https://web.archive.org/save/$url` allows you to save your page. <sub>I also have an [issue open about this](https://github.com/nodiscc/shaarchiver/issues/6) in the archival tool.</sub>

Maybe doing archive.org save requests could also be added as a Shaarli plugin? Need to check my `plugin-system` branch again. I _think_ AutoBlog and [respawn](https://github.com/broncowdd/respawn) also support archiving a link by only sending the a POST request, which can definitely  be done through a plugin. Idk if they allow saving media/videos.

> Add statistics? (database size, number of links (private/public), free space on webspace)

Number of links is already displayed at the top right, but we could differentiate between private and public links on the tools page, yes. db size may be interesting, you can also check it by looking at the filesize of your `datastore.php`. So there is that.

About free space, unless your `cache` and `pagecache` dirs grow huge, there is little interest in adding this (my cache dirs are very small, but it may be interesting to post sample sizes from different installs). I think it's the job of your host's admin panel to display this. A button to clear caches could be nice though.

> using a modern framework's buit-in features (e.g. Symfony/Zend for clean PHP, Django/Pylons for cool Python, for

![v08decj](https://cloud.githubusercontent.com/assets/3950390/6260804/73d0e68e-b7e4-11e4-96d5-4e089e72b864.gif)

Yes Shaarli is totally hackish :trollface: But as you said it's been running well and we actually have fixed some nastyness, so why not continue? ;) As I said in the general discussion thread, there's a nice bookmark sharing app written in python: https://github.com/bookieio/Bookie. Buuuut it's not the same complexity/maintenance/hosting/time cost to setup/maintain this and yep, we're short on time :)

**Comment by e2jk** [comment]
I agree with your comments. Just a quick note about i18n: I am more of a proponent of vanilla gettext support, but it was also proposed to use RainTPL's own array structure. Anyway, you can find some starting snippets for the translation at https://github.com/sebsauvage/Shaarli/issues/18#issuecomment-14168240

**Comment by nodiscc** [comment]
I agree about using GNU Gettext. The reference editor is [poedit](http://poedit.net/) but the [Transifex](https://www.transifex.com/) web platform also supports translating projects using gettext.

**Comment by virtualtam** [comment]
Yay for Gettext!
Transifex is great for community projects with a consequent UI, though I don't think it will be necessary for Shaarli (there aren't too many strings to get translated).

Thanks @nodiscc for pointing to Shaarchiver! :smile:
+1 for linking it in the Shaarli docs!

**Comment by nodiscc** [comment]
Summary (I'll update the list on top)

**Regarding backups:**

 * Example backup commands [added to the wiki](https://github.com/shaarli/Shaarli/wiki#backup) 
 * shaarchiver [added to the wiki](https://github.com/shaarli/Shaarli/wiki#related-software)

**Regarding links archiving/mirrorring:**

 *  Tools like [autoblog](https://github.com/shaarli/Shaarli/wiki#backup) are already able to follow RSS feeds and backup items (add it to the doc?).
 * I'll add a section to the wiki once shaarchiver is decent enough, and supports webpage archiving (currently only media exports work), and is able to generate HTML indexes.
 * For batch archiving by archive.org, I'll add this to shaarchiver (`curl https://web.archive.org/save/$url`, https://github.com/nodiscc/shaarchiver/issues/6). For now you can use Shaarli's archive.org functionality (needs to be moved to a plugin), clicking on archive.org links archives your link there.

**Regarding statistics:**

 * Add counters for number of public and private links to the tools page (please report a bug for this, low priority)
 * Add counters for datastore and cache directories to the tools page (please report a bug for this, low priority)

**Regarding translations:**

 * Feel free to propose i18n systems using gettext or RainTPL as pull requests. Low priority for now.

**Regarding a rewrite:**

 * A rewrite is possible as another project. Added [Bookie](https://github.com/bookieio/bookie) as an alternative to the wiki. We'll keep the current codebase and keep improving over it (code additions _and_ deletions)

**About weekly/monthly views:**

 * Please open a bug report about this (low priority, should be easy to add to the daily page)

**Comment by nodiscc** [comment]
About multi-user @virtualtam this was marked as wontfix: https://github.com/shaarli/Shaarli/issues/15. Just create multiple shaarlis. No need for multiple virtualhosts or DNS entries, just put them in separate directories, and enable dir indexes:

```
myserver.com/
    shaarlis/
        bob/         <-bob's shaarli instance
        virtualtam/  <-virtualtam's shaarli instance
        someoneelse/ <-someoneelse's shaarli instance
```

**Comment by virtualtam** [comment]
@nodiscc: agreed, though the use case I had in mind is a bit different (and goes beyond Shaarli'scope, IMHO); I was mostly reporting it 'cause multi-user Shaarlis were asked quite regularly by friends/users ;-)

**Comment by nodiscc** [comment]
@virtualtam I think a server-side (shell or python) script to maintain shaarli "farms" would be nice for those users, with the ability to create/delete shaarlis, reset passwords, ... Another worthwile side-project :)

**Comment by nodiscc** [comment]
@DMeloni @Oros42 ping since you are involved in maintaining these farms.

**Comment by Oros42** [comment]
Pong !
Interesting discussions but I'm realy busy this week :-/

**Comment by DMeloni** [comment]
Hi, 
some users run on the same instance of shaarli on shaarli.fr, this is just a fork available here : 
https://github.com/DMeloni/Shaarli

0/ the user connects on https://www.shaarli.fr/my/{pseudo}/
1/ a rewrite rule (apache2) create a 'pseudo' parameter
2/ forked shaarli creates a directory named 'data-pseudo' and specific cookie for avoiding connexion on the other accounts

The fork is probably unsecure, this is why it would be dangerous to merge it on the official project.
Plus there is no administrator interface (rm -r data-pseudo is actualy the only manner to delete an user).

I'm sure shaarli could be a software much more powerful if multiple instances could be linked together. 

all these web servers just waiting to love ;-)

**Comment by nodiscc** [comment]
@DMeloni ok so this fork enables creating Shaarlis on-the-fly through a web interface, using the same base directory, but a different datadir for each user (https://github.com/DMeloni/Shaarli/commit/2154b3e8ebfc1c6f2ee1ecd1cda58e15255ee9c4). This is different from a multi-user Shaarli in my view. While it's a nice hack I don't think we would merge this. 

You may want do to sanity checks because your code passes user-provided params (`?pseudo`) to PHP global vars (not saying this is unsafe, I din't have time to check)

Would you like to merge our code to provide the latest fixes to your users? As you edited index.php it won't merge properly though, but we could work together to separate your tool from Shaarli, this way we would have what I proposed: 

>script to maintain shaarli "farms" would be nice for those users, with the ability to create/delete shaarlis, reset passwords, ... Another worthwile side-project :)

while giving you the ability to stay up-to-date with the latest developments.

What do you think? We could discuss this on Gitter: https://gitter.im/shaarli/Shaarli (in english) or on this temporary IRC channel (english or french) if you like oldschool IRC: http://demo.relayjs.com/?server=irc.freenode.net#shaarli

This thread is beginning to grow :) We can always reopen another if it grows too large.

**Comment by e2jk** [comment]
>  or on this temporary IRC channel (english or french) if you like oldschool IRC

Note that the gitter chatroom is also reachable via IRC, if needed: https://irc.gitter.im/

**Comment by mrjovanovic** [comment]
> automatically choose corresponding translation if available.

This would be profoundly annoying, IMO. Plenty of users (me included) like to select different locales for different types of software. More often than not, their system locale is English, while the browser locale is different. What about using Shaarli on others'/public computers? It just seems like this choice would be better left to the user.

@virtualtam re: Daily page
>  several views: daily, weekly, monthly (organizer-like view);
>  calendar view.

This is a great idea.
 
@virtualtam @nodiscc 
>>    Filter links by date (between two dates ?)
>I think either that or your idea (user-friendly ranges) would be fine; how should it look like in the UI ?

How about this?
![date search suggestion](https://cloud.githubusercontent.com/assets/4664783/6588359/940eca72-c75e-11e4-843a-99f03cc937da.png)

**Comment by virtualtam** [comment]
@mrjovanovic this looks like a really convenient feature!

we could start with a simple date filtering in PHP, and move to a fancier Javascript UI when Shaarli's codebase has become a bit more mature :)

**Comment by nodiscc** [comment]
> automatically choose corresponding translation if available

Forwarded to https://github.com/shaarli/Shaarli/issues/121, let's discuss there.

> several views: daily, weekly, monthly (organizer-like view); calendar
> we could start with a simple date filtering in PHP

Yep, can you open another issue about this? The daily/weekly/monthly pages could be generated by date filtering system suggested by @virtualtam 

> Filter links by date (between two dates ?)

I like the idea of doing it via a GET parameter in the first time. @mrjovanovic I like the look of your date picker, but this should be done using the plugin system. It adds a field to the search bar which we can't clutter too much (you had to shrink the search field in your screenshot ...) @e2jk already suggested adding a "Add link" field there (https://github.com/shaarli/Shaarli/issues/147) and we can't have that much by default.

Can you open another issue about this too?

**Comment by nodiscc** [comment]
Let's triage the remaining list items before 0.9beta. Comments welcome

**Comment by ArthurHoaro** [comment]
Ok, I'll try to contribute on this. Handle 50+ ideas in a single issue isn't possible, so I've created a pad with my opinion on all of this.

I think our first objective is to create an issue for every item we want to discuss further.

https://lite6.framapad.org/p/3I7CN1Drms

It would be nice if you could review it.

**Comment by nodiscc** [comment]
Thank you, this is much better. I've added some points, will check back later.

**Comment by ArthurHoaro** [comment]
I answered some of your points. 

I will switch a few "UNDECIDED" to "Reporting" by opening related issues.

**Comment by nodiscc** [comment]
I have re-read this issue and the [pad](https://lite6.framapad.org/p/3I7CN1Drms), and I believe every point mentioned has been debated and either fixed, reported in another issue, or marked wontfix. So I think #106 can be closed :) Huge. thanks. everyone.

![](http://sebsauvage.net/links/images/logo.png) !
