### ISSUE TITLE
What should i do?

### ISSUE THREAD

**Issue by LaserKaspar** [shaarli/Shaarli#1064]
Sessions do not seem to work correctly on your server.
Make sure the variable session.save_path is set correctly in your php config, and that you have write access to it.
It currently points to /var/lib/php5/sessions
Check that the hostname used to access Shaarli contains a dot. On some browsers, accessing your server via a hostname like 'localhost' or any custom hostname without a dot causes cookie storage to fail. We recommend accessing your server via it's IP address or Fully Qualified Domain Name.

Click to try again.

**Comment by ArthurHoaro** [comment]
Hi,
Please provide more information about your setup: which kind of hosting are you using, which web server, etc. 
Also, make sure that `/var/lib/php5/sessions` is writable by your web server.

**Comment by LaserKaspar** [comment]
How im new on Linux (:
I have checked if the file exists but no there isnt a file called session.save_path.
How do I give permissions to my webserver to write/open this?

**Comment by ArthurHoaro** [comment]
`session.save_path` is a PHP config variable name. The actual folder is `/var/lib/php5/sessions`. Please provide the result of `ls -l /var/lib/php5/sessions`. You can change its permissions using `chmod`.

How do you access your Shaarli's instance? Do you use Apache/nginx/...? Did you install it locally on your computer, or on a shared hosting or on a dedicated server?

**Comment by virtualtam** [comment]
Hi @LaserKaspar!

The server setup and configuration is covered by the following documentation pages:
- https://shaarli.readthedocs.io/en/master/Server-requirements/
- https://shaarli.readthedocs.io/en/master/Server-configuration/#nginx
- https://shaarli.readthedocs.io/en/master/Shaarli-configuration/

You might also be interested in the following resources:
- https://nginx.org/en/docs/beginners_guide.html
- https://www.howtoforge.com/tutorial/installing-nginx-with-php-fpm-and-mariadb-lemp-on-debian-jessie/ (PHP and Nginx parts)

`session.save_path` can be set, along other options, by editing the `/etc/php5/fpm/php.ini` configuration file (don't forget to make a backup before editing)

More on this in the PHP documentation:
- https://secure.php.net/manual/en/session.configuration.php#ini.session.save-path

**Comment by LaserKaspar** [comment]
I don't have a Shaarli instance or what do you mean with a instance a SSH-user or a user in Shaarli? I have a vServer with nginx installed. 

ls -l /var/lib/php5/sessions
total 20
-rw------- 1 www-data www-data 94 Jan 25 14:48 sess_6h7972tc73da9i8kuqok0pgdj0
-rw------- 1 www-data www-data  0 Jan 25 14:55 sess_6ul3mttma9u496pfa1birv3dj7
-rw------- 1 www-data www-data 94 Jan 25 14:51 sess_7kb0fpulg1nisco9qh1rrbvvb6
-rw------- 1 www-data www-data  0 Jan 25 14:51 sess_ct0qa9hvq7gpe7anqbnhlqku55
-rw------- 1 www-data www-data  0 Jan 25 14:48 sess_dvslnaqilt1aok9rpjsodsj142
-rw------- 1 www-data www-data 94 Jan 25 14:55 sess_ec01be5a5r2l30np1o9lbkabm2
-rw------- 1 www-data www-data  0 Jan 25 14:51 sess_gagodun1bs17iidgkta153naf6
-rw------- 1 www-data www-data  0 Jan 25 15:19 sess_inhs2769o83qn0224nl80h0i72
-rw------- 1 www-data www-data 94 Jan 25 14:48 sess_pb7up0dah7a9tj50c9s3uufn53
-rw------- 1 www-data www-data  0 Jan 25 14:55 sess_pidi3891s8360smql0icq8bsc1
-rw------- 1 www-data www-data  0 Jan 25 14:55 sess_tofd46pb0e40lhvckek5b5po72
-rw------- 1 www-data www-data  0 Jan 25 14:55 sess_ttfqloac5m7os313a0r4b7g3h7
-rw------- 1 www-data www-data  0 Jan 25 14:50 sess_u4n1vtkd9ikokhl4nbbmq9d3m2
-rw------- 1 www-data www-data 94 Jan 25 14:55 sess_uv0lh4qurnrpbqt2i5l32ojvr4
-rw------- 1 www-data www-data  0 Jan 25 14:48 sess_v0ah6pp5c02qkgu7f7l71kjim3
Like said no session.save_path file

**Comment by LaserKaspar** [comment]
; where N is an integer.  Instead of storing all the session files in
; /path, what this will do is use subdirectories N-levels deep, and
; store the session data in those directories.  This is useful if
; your OS has problems with many files in one directory, and is
; a more efficient layout for servers that handle many sessions.
;
; NOTE 1: PHP will not create this directory structure automatically.
;         You can use the script in the ext/session dir for that purpose.
; NOTE 2: See the section on garbage collection below if you choose to
;         use subdirectories for session storage
;
; The file storage module creates files using mode 600 by default.
; You can change that by using
;
;     session.save_path = "N;MODE;/path"
;
; where MODE is the octal representation of the mode. Note that this
; does not overwrite the process's umask.
; http://php.net/session.save-path
session.save_path = "/var/lib/php5/sessions"

Is this right configured?

**Comment by virtualtam** [comment]
This sounds about right; it's important to ensure that:
- all Shaarli files are owned by the `www-data` group, see the `chown` and `chgrp` commands
- the `www-data` group has read, write and execution access to Shaarli data and cache directories
- PHP-FPM is run as the `www-data` user _and_ group; this ensures Nginx can communicate with the socket provided by PHP-FPM

You'll find more details regarding the appropriate file access and permissions in the docs I linked in my previous comment.

**Comment by nodiscc** [comment]
@LaserKaspar did this help?

> the www-data group has read, write and execution access to Shaarli data and cache directories

You can verify that the necessary permissions are set by issuing `sudo -u www-data touch /path/to/your/shaarli/{cache,tmp,data}/mytestfile` in your shell.

> PHP-FPM is run as the www-data user and group

`ps aux | grep php` should show a PHP-FPM process running as the `www-data` user.

If you are new to Linux I suggest giving a try to Debian 9 (the latest stable version - but 8 should be fine too)!

**Comment by ArthurHoaro** [comment]
Closing due to lack of feedback. Feel free to reopen this issue if you need more information.

**Comment by tricarte** [comment]
I faced this problem when I set php.ini's session and cookie related flags to more secure values. Try setting any or all of the below to false (0) in your php.ini depending on your configuration. This also causes the wrong login password error.
session.cookie_httponly = 0
session.cookie_secure = 0
session.use_only_cookies = 0
