### ISSUE TITLE
Error on Windows since v0.9.4 - Use of undefined constant LC_MESSAGES

### ISSUE THREAD

**Issue by kalvn** [shaarli/Shaarli#1067]
Since the v0.9.4, I have the following notices:

```
Notice: Use of undefined constant LC_MESSAGES - assumed 'LC_MESSAGES' in F:\Dev\PHP\shaarli\index.php on line 132

Deprecated: setlocale(): Passing locale category name as string is deprecated. Use the LC_* -constants instead in F:\Dev\PHP\shaarli\index.php on line 132
```

When I switch from Material theme to default theme, only the second message (Deprecated...) appears.

Nevertheless, translations work well so it may just be a matter of hiding these messages.

**Comment by ArthurHoaro** [comment]
According to [the doc](http://php.net/manual/en/function.setlocale.php), `LC_MESSAGES` constant is only available if PHP was compiled with `libintl`. I'll provide a PR to fix this warning.
