### ISSUE TITLE
Add comment icon / link on list view for Isso plugin

### ISSUE THREAD

**Issue by poVoq** [shaarli/Shaarli#1075]
Right now there is no way to actually see in the list view that there is the option to comment on the entries with Isso. Would be nice if the Isso plugin would add a small comment icon that would link to the "#comments" section on the permalinks page.
Maybe a bit similar to how the "related" plugin show a small link icon.

I actually tried to make something like this for my Hashover-Next plugin (https://github.com/poVoq/shaarli-plugin-hashover-comments - based on Isso plugin), but I failed due to being really bad at these things :( So if this was  implemented for the Isso plugin or someone would give me some hint how to do it, that would be great.

Thanks!

**Comment by poVoq** [comment]
The problem with my failed attempt is that I can't get the shortlink url in the html, like this:
`<a href="?{$value.shorturl}#comments">`

I guess `{$value.shorturl}` only works in .php right? So how can I get it to understand the unique shortcodes?

See my attempt based on the archive.org plugin here: https://github.com/poVoq/shaarli-plugin-hashover-comments/tree/master/commentlink

**Comment by ArthurHoaro** [comment]
It's a good idea.

In your plugin HTML file, instead of `{$value.shorturl}` (which is a RainTPL variable), use `%s`. Then in your PHP file, the function [`sprintf()`](https://secure.php.net/manual/en/function.sprintf.php) to replace the placeholder `%s` with a variable.

In this case, something like that (didn't test it):

```php
$commentlink = sprintf($commentlink_html, $value['shorturl']);
$value['link_plugin'][] = $commentlink;
```

**Comment by poVoq** [comment]
Works great, thanks a lot for the help!
