### ISSUE TITLE
Bookmarklet popup doesn't have scrollbar in Firefox

### ISSUE THREAD

**Issue by poVoq** [shaarli/Shaarli#1079]
If I use the Bookmarklet in Firefox, the small window that pops up doesn't have a scrollbar and is thus a bit difficult to use if you have additional plugins enabled that increase the size of it.

**Comment by ilpssun** [comment]
Yes, that's annoying.  I thought it was just due to my firefox configuration 😃
For me, the pop-up looks like that:
![grafik](https://user-images.githubusercontent.com/835280/35922346-a70d64d8-0c1d-11e8-8cad-07aa084919b4.png)

**Comment by poVoq** [comment]
https://developer.mozilla.org/en-US/docs/Web/API/Window/open

Seems to explain why that is happening.

**Comment by ArthurHoaro** [comment]
Please update your bookmarklet using the one in the Tools page in the default theme.
