### ISSUE TITLE
Bookmarklet does not work on github.com

### ISSUE THREAD

**Issue by ilpssun** [shaarli/Shaarli#1080]
When I try to use the “Shaare link” bookmarklet on github.com, it does not work.  In the Firefox web console I can see the following error message:

    Content Security Policy: Page settings have blocked loading a resource on self ("script-src https://assets-cdn.github.com").

*(I translated the error from German to English so the wording might not be 100% exact.)*

**Comment by Marsup** [comment]
Asked and answered in #196.

**Comment by virtualtam** [comment]
Thanks @Marsup!

The relevant documentation now lives at https://shaarli.readthedocs.io/en/master/Bookmarklet/

**Comment by ilpssun** [comment]
Thanks!  I wonder why I didn't find that when searching previously...
