### ISSUE TITLE
Can't find `data/config.php` file

### ISSUE THREAD

**Issue by tareefdev** [shaarli/Shaarli#1082]
I seem to have forgotten my password, but as I read the documentation I can't find the `data/config.php` file to delete it!

```
ls -la
total 88
drwxr-xr-x  2 nginx nginx  4096 Feb  9 08:40 .
drwxr-xr-x 13 nginx nginx  4096 Dec 23 17:24 ..
-rw-r--r--  1 nginx nginx  1904 Dec 23 17:49 config.json.php
-rw-r--r--  1 nginx nginx 29755 Jan 12 16:27 datastore.php
-rw-r--r--  1 nginx nginx  2523 Jan 12 16:27 history.php
-rw-r--r--  1 nginx nginx   236 Dec 23 17:24 .htaccess
-rw-r--r--  1 nginx nginx 17279 Dec 23 17:46 import.2017-12-23.log
-rw-r--r--  1 nginx nginx   218 Feb  5 10:55 ipbans.php
-rw-r--r--  1 nginx nginx     5 Jan 17 18:21 lastupdatecheck.txt
-rw-r--r--  1 nginx nginx   822 Feb  5 10:44 log.txt
-rw-r--r--  1 nginx nginx   358 Dec 23 17:37 updates.txt
```
I tried to rename `config.json.php` but this causes another problem so I return its name.

**Comment by virtualtam** [comment]
Hi @tareefdev,

The configuration is stored under `data/config.json.php`; which documentation are you referring to?

**Comment by tareefdev** [comment]
Hi @virtualtam 
I mean this:
https://shaarli.readthedocs.io/en/master/Troubleshooting/

but I tried to rename it as I mentioned above but it didn't help me.
thanks!

**Comment by virtualtam** [comment]
Thanks, this page is obsolete so we'll have to update its contents.

The file you need to remove is `config.json.php`. There should be no `config.php`, else Shaarli will try to load it and process it, which will fail.

After removing this file, you will need to reconfigure your Shaarli: password, plugins, settings, etc.
