### ISSUE TITLE
Allow turning off automatic linkification of URLs in description

### ISSUE THREAD

**Issue by cristoper** [shaarli/Shaarli#1094]
I would like to be able to add HTML anchor hyperlinks (`<a href='http://....'>link text</a>`) in the description field, but currently any such links are clobbered by `text2clickable()`. It would be nice if the automatic linkification of URLs could be disabled either by:

- A configuration option
- Moving `text2clickable()` to a (default) plugin
- Or at least modifying the regex so that it doesn't touch URLs between single or double quotation marks

I notice that the markdown plugin has to work around this default behavior by actually undoing the regex replacement with more regex replacements (in `reverse_text2clickable()`) which is not a very elegant thing to have to do. So allowing the automatic linking to be turned off could also simplify that (and other future) plugins.

**Comment by virtualtam** [comment]
Hi @cristoper!

This is a nice suggestion, as both features (clickable text, Markdown plugin) are mutually exclusive.

Impacted functions:

https://github.com/shaarli/Shaarli/blob/d449f79a0d7ca808b891baf73b9e25ce7f7e48fe/application/LinkUtils.php#L132

https://github.com/shaarli/Shaarli/blob/a381c373b30ed04001ea31ff5c38e077edacaf18/plugins/markdown/markdown.php#L180

To some extent, this improvement could also be applied for:

https://github.com/shaarli/Shaarli/blob/a381c373b30ed04001ea31ff5c38e077edacaf18/plugins/markdown/markdown.php#L230

https://github.com/shaarli/Shaarli/blob/a381c373b30ed04001ea31ff5c38e077edacaf18/plugins/markdown/markdown.php#L242

**Comment by ArthurHoaro** [comment]
I had started to work on something where markdown processing would be included in the core and links were processed through a formatter object. It would allow us to get rid of these reverse functions, but it's planned for `0.11` milestone. 

Related issue #445

**Comment by ArthurHoaro** [comment]
Markdown has now be integrated into Shaarli's core code. We can easily add a setting to disable autolinking in default bookmark formatter.
