### ISSUE TITLE
Redirect to previous search after deleting a link

### ISSUE THREAD

**Issue by nodiscc** [shaarli/Shaarli#110]
Followup to #87 

> @e2jk I frequently hit  this bug: 

> This would only be an issue when you want to delete multiple links from e.g. a search, but (1) how often does this use case happen and (2) you could click twice on the back button and you would be back to the page from which you clicked the delete button.

>It's very annoying when you are trying to cleanup links with a certain tag. I think if either `$searchtags` or `$searchterm` are defined, we should add these params to the next request (so you would be redirected to the previous serach. Hitting back twice is confusing and annoying.

>I'll aopen another issue for this.

Currently deleting a link takes you back to the home page (https://github.com/shaarli/Shaarli/commit/657837af111387c93b3a75149d93856df12c00d9). It should redirect you to your previous search if there was one set.

**Comment by e2jk** [comment]
For documentation purposes, this is handled in #112.
