### ISSUE TITLE
Content Security Policy:  ("script-src https://assets-cdn.github.com").

### ISSUE THREAD

**Issue by juh2** [shaarli/Shaarli#1101]
When I try to shaare a gihub page with the "Shaare link" bookmarklet I get this error message.

Content Security Policy: Die Einstellungen der Seite haben das Laden einer Ressource auf self blockiert ("script-src https://assets-cdn.github.com").

The German translates to "Configuration of the page blocked loading a ressource". I am not sure whether this is the original message.

Firefox 58.0.2
Shaarli 0.9.0

**Comment by ArthurHoaro** [comment]
Unfortunatly, there is nothing Shaarli can do about it. See [the documentation](troubleshooting-the-bookmarklet-doesnt-work-with-a-few-websites-eg-githubcom).

**Comment by fbartels** [comment]
@ArthurHoaro that link gives a 404. I guess you wanted to link https://shaarli.readthedocs.io/en/master/Bookmarklet/#troubleshooting-the-bookmarklet-doesnt-work-with-a-few-websites-eg-githubcom

**Comment by virtualtam** [comment]
Duplicate of #196

**Comment by ArthurHoaro** [comment]
@fbartels Thank you, I did't had my coffee back then. :)
