### ISSUE TITLE
Documentation: simplify the server configuration page

### ISSUE THREAD

**Issue by virtualtam** [shaarli/Shaarli#1105]
See http://shaarli.readthedocs.io/en/master/Server-configuration/

This page is a bit dated and features lots of information that may confuse new (and existing) users who are looking for a straightforward server setup example.

I'd be in favour of keeping only the most essential bits here to show a sane setup example for supported HTTP servers (currently, Apache & Nginx). Extra information could be moved to dedicated pages.

Also, the section about self-signed certificates should be removed and replaced with Let's Encrypt resources.

What do you think would be the best approach here?

**Comment by nodiscc** [comment]
Server Requirements, Configuration and Shaarli Download/Installation should probably be merged to a single, more concise page, giving an abstract of the most common setups. Extra config steps/other install methods/server tweaks/ssl config can be moved to subpages. If you can merge the 3 pages to a single one (in a temporary branch) we could start removing some of the fat.

**Comment by virtualtam** [comment]
Good idea, this could be an "Installation Guide" addressing most common setups, and platform-specific requirements and settings could be relocated to specific pages.

Now what should we consider to be a typical/common server setup?

With shared and VPS hosting in mind, I can think of:
- Debian 9, Apache 2.4, PHP 7.0
- Ubuntu 16.04, Apache 2.4, PHP 7.0
- (upcoming) Ubuntu 18.04, Apache 2.4, PHP 7.2

And maybe CentOS, but it rather seems to be used for enterprise servers where there is a prominent RHEL culture.

**Comment by nodiscc** [comment]
> Installation Guide
> Debian/Ubuntu/Apache/PHP7

:+1: A simple, common guide for these setups (install requirements, download and extract the prebuilt zip) should be doable without entering too much in distro specifics. Add to that:

 * a separate page on how to install through Docker
 * a separate page on how to install the development version through git/composer
 * an "Advanced server configuration" page where users could find advice on further configuring their servers. Most users should be able to skip this.

Speaking of the all-in-one zip, I'm thinking of setting up an automated build service. Apparently Travis makes this possible https://stackoverflow.com/questions/12343452/how-to-publish-artifacts-in-travis-ci#33109519. I am also setting up a GitLab/GitLab CI instance as a side project, I'll let you know how it goes.

**Comment by virtualtam** [comment]
> all-in-one zip

having this generated in an automated way would be super nice :)

> GitLab

GitLab goes nicer with each new release, the Kubernetes CI/CD pipeline being one of its super neat features :)

**Comment by nodiscc** [comment]
This was fixed in https://github.com/shaarli/Shaarli/pull/1389

I move the part related to automatic release zip builds to https://github.com/shaarli/Shaarli/issues/1555
