### ISSUE TITLE
Import config - Maximum size allowed: 2MiB

### ISSUE THREAD

**Issue by dhoko** [shaarli/Shaarli#1112]
Hey, 

I have an issue with my config, I can't import it.
The full export is huge, 3,3 MB (_3 317 182 bytes_), if I do 2 exports, one private and one public It won't work →public: 3,2 MB (_3 167 166 bytes_).
I have 11 376 links (_public_)

I exported my config from an old version of Shaarli (_Shaarli 0.0.41 beta_).

**Comment by ArthurHoaro** [comment]
Hi @dhoko. The maximum upload size depends on your server configuration. In your `php.ini` configuration file, check `post_max_size` and `upload_max_filesize` settings.

More resources: 

   * https://stackoverflow.com/questions/2184513/change-the-maximum-upload-file-size
   * http://php.net/manual/fr/ini.core.php#ini.upload-max-filesize

**Comment by dhoko** [comment]
lol thx it works, I didn't think to config php :)

**Comment by ArthurHoaro** [comment]
Glad I could help :)
