### ISSUE TITLE
Insufficient permissions in Docker

### ISSUE THREAD

**Issue by itskiru** [shaarli/Shaarli#1127]
Hi,

When I try to launch Shaarli under docker with the command `docker run -d -p 8000:80 -v /srv/shaarli:/var/www/shaarli/data shaarli/shaarli`, I make a reverse proxy with NGINX and I get that error: 

```
Insufficient permissions:

    "data" directory is not writable
```

And that's the docker logs: 
```
172.17.x - - [15/Apr/2018:13:03:47 +0000] "GET / HTTP/1.1" 200 93 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:60.0) Gecko/20100101 Firefox/60.0"
172.17.x - - [15/Apr/2018:13:03:48 +0000] "GET / HTTP/1.1" 200 93 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:60.0) Gecko/20100101 Firefox/60.0"
172.17.x - - [15/Apr/2018:13:03:48 +0000] "GET / HTTP/1.1" 200 93 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:60.0) Gecko/20100101 Firefox/60.0"
172.17.x - - [15/Apr/2018:13:03:48 +0000] "GET / HTTP/1.1" 200 93 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:60.0) Gecko/20100101 Firefox/60.0"
172.17.x - - [15/Apr/2018:13:03:48 +0000] "GET / HTTP/1.1" 200 93 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:60.0) Gecko/20100101 Firefox/60.0"
172.17.x - - [15/Apr/2018:13:03:49 +0000] "GET / HTTP/1.1" 200 93 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:60.0) Gecko/20100101 Firefox/60.0"
172.17.x - - [15/Apr/2018:13:03:49 +0000] "GET / HTTP/1.1" 200 93 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:60.0) Gecko/20100101 Firefox/60.0"
172.17.x - - [15/Apr/2018:13:03:49 +0000] "GET / HTTP/1.1" 200 93 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:60.0) Gecko/20100101 Firefox/60.0"
172.17.x - - [15/Apr/2018:13:05:20 +0000] "GET / HTTP/1.1" 200 93 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:60.0) Gecko/20100101 Firefox/60.0"
172.17.x - - [15/Apr/2018:13:05:20 +0000] "GET /favicon.ico HTTP/1.1" 200 76949 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:60.0) Gecko/20100101 Firefox/60.0"
```

I would to know why that error happen & how to fix it please...

Thanks !

**Comment by virtualtam** [comment]
Hey @itskiru,

This means that the processes running inside the Docker container are attempting to write data to a location that is not writeable.

See Docker's [Use volumes](https://docs.docker.com/storage/volumes/) documentation for more information regarding the available options for storing data in a persistent way.

A common issue when bind-mounting volumes is managing user permissions, as the numeric user and group IDs might differ between the host running Docker and the guest container appliances.

**Comment by itskiru** [comment]
Hi @virtualtam,

I gave the permission 777 by `chmod 777 /srv/shaarli` and I ran the container by the root user...

**Comment by virtualtam** [comment]
See my detailed answer on this previous issue: https://github.com/shaarli/Shaarli/issues/1031#issuecomment-348713433

> chmod `777`

Never ever do this...

> ran the container by the root user

This has no impact whatsoever, processes are run with user/group accounts that are local to the container, and usually have limited permissions.

**Comment by virtualtam** [comment]
Closing due to lack of feedback, feel free to reopen.

**Comment by danbo** [comment]
After making it 777, you can see the user and group the container is using internally - 100 and 101, so just chown the folder on your host to that.

```sudo chown 100:101 /srv/shaarli```

finally, reset perms to default

```sudo chmod 755 /srv/shaarli```
