### ISSUE TITLE
After first start => "Error: missing Composer configuration"

### ISSUE THREAD

**Issue by Pyradur** [shaarli/Shaarli#1128]
I copied shaarli as described using zip and unzipped it.
After starting shaarli I got the following error-message:

Error: missing Composer configuration

If you installed Shaarli through Git or using the development branch,
please refer to the installation documentation to install PHP dependencies using Composer:
- https://github.com/shaarli/Shaarli/wiki/Server-requirements
- https://github.com/shaarli/Shaarli/wiki/Download-and-Installation

How to use shaarly without composer?

**Comment by ArthurHoaro** [comment]
You need to use the `full` archive from the [release page](https://github.com/shaarli/Shaarli/releases/tag/v0.9.6).

**Comment by ArthurHoaro** [comment]
Closing due to lack of feedback. Feel free to reopen if my answer didn't solve your issue.

**Comment by zerosonesfun** [comment]
I'm having this issue as well. I've tried master, stable and 0.10.
