### ISSUE TITLE
REST api

### ISSUE THREAD

**Issue by dimtion** [shaarli/Shaarli#113]
I don't know if it is a planned feature (nor if it already exist but not documented) but would it be possible to implement an api to view, add, delete items in the list ?

Today it is quite painful to access to the data, and require to parse the html output from the server.

**Comment by e2jk** [comment]
Do you have any suggestion for a library written in PHP that would provide this with relatively small changes to the code? If this can be done while not increasing the complexity of the code too much, I'm not opposed to it (read: Pull Request welcome)

**Comment by nodiscc** [comment]
@dimtion For read access, you can also parse the RSS feed (which is just XML). Write access requires sending HTTP POST data. You can find a way to programatically log in to your shaarli and some basic operations at https://github.com/nodiscc/shaarchiver (work in progress)

**Comment by dimtion** [comment]
Thanks for the reply

@e2jk I don't know any today, however I will take a look...

@nodiscc Yeah, i was already looking in this direction (using the rss feed), but it was more about retrieving the token for posting (without any library) which was "painful".

**Comment by nodiscc** [comment]
@dimtion 

> retrieving the token for posting

https://github.com/nodiscc/shaarchiver/blob/master/export-shaarli.py#L74

**Comment by pikzen** [comment]
Implementing a REST API in Shaarli right now would basically mean rewriting already existing methods to output it in JSON/XML/whatever and duplicating code.

As of now, retrieving the token is your best bet. See @nodiscc's answer as a way to do it.
As far as posting goes, I'm afraid you're going to have to retrieve the token and POST it on ?do=editlink alongside with all the data, properly formatted.

**Comment by dimtion** [comment]
Ok thank you for all your answers. I'll do that for the moment.

**Comment by mro** [comment]
this issue is a duplicate of #16, right?

**Comment by nodiscc** [comment]
@mro; yes.
