### ISSUE TITLE
Unable to log into instance

### ISSUE THREAD

**Issue by cxWoNSUUt** [shaarli/Shaarli#1130]
Hi

Suddenly my shaarli won't let me log in. It keeps saying that my password is incorrect, when I know for a fact that it is correct (I use a password manager, and I haven't changed the password). Is there a way to reset the password?

**Comment by virtualtam** [comment]
Hi @cxWoNSUUt,

Authentication information can be reset by deleting the appropriate entries under `data/config.json.php`:

```json
    "credentials": {
        "login": "some_login",
        "hash": "<redacted>",
        "salt": "<redacted>"
    },
```

**Comment by cxWoNSUUt** [comment]
I'm not exactly sure what you mean @virtualtam. Do I delete the entire block? Or just the Hash/Salt parts? I tried that, and it wouldn't allow me in still. I also tried deleting the entire block, and I get this error:

```
An error occurred while parsing JSON configuration file (data/config.json.php): error code #4
➜ quoted object property name expected
Please check your JSON syntax (without PHP comment tags) using a JSON lint tool such as jsonlint.com.
```

**Comment by virtualtam** [comment]
You should delete the entire block, and ensure the file is JSON-valid so it is properly loaded by PHP code.
Alternatively, you can move the whole file elsewhere and let Shaarli create a new configuration file (you will then need to reconfigure your instance).

**Comment by cxWoNSUUt** [comment]
Hi

I deleted the entire block, as suggested, but it comes up with the error above. I have confirmed the JSON is correct. I tried removing the file completely, and the following error happens:

```
Sessions do not seem to work correctly on your server.
Make sure the variable session.save_path is set correctly in your php config, and that you have write access to it.
It currently points to /var/lib/php5/sessions
Check that the hostname used to access Shaarli contains a dot. On some browsers, accessing your server via a hostname like 'localhost' or any custom hostname without a dot causes cookie storage to fail. We recommend accessing your server via it's IP address or Fully Qualified Domain Name.

Click to try again.
```

I am thinking I am just going to reinstall shaarli. What should I back up to keep my saved links?

**Comment by cxWoNSUUt** [comment]
I have sorted it now, thanks. Don't know why, but 2 browsers had the same issue. I tried a third one (because why not), and it did the initial install as it should to create that file.

**Comment by virtualtam** [comment]
Good to know you got it working, though this is a bit surprising... feel free to reopen this issue if you have more info, so we can update the docs/FAQ :)

**Comment by mirabellette** [comment]
I am experiencing the same issue.

My configuration is the next one:
public url: example.com
reverse proxy apache 2.4
virtual machine ip: 192.168.1.1
virtual machine has shaarli which listen port 80

When I connect to shaarli throw.168.1.1:80, I am able to log in successfully.
When I connect to shaarli throw example.com, I got unsucessuf login even if it the same one.

Moreover, to do the installation, when I delete data/config.json.php and reload from example.com, I am redirected to 192.168.1.1 until I finish to configure it successfully. When it is finall configured, I can now access from example.com and 192.168.1.1 but login works only from 192.168.1.1
