### ISSUE TITLE
Image make shaare un-aesthetic

### ISSUE THREAD

**Issue by Draky50110** [shaarli/Shaarli#1131]
In french : si on shaare une image, le bas du shaare est mangé.

Pour expliquer mieux, un exemple : https://gilles.wittezaele.fr/liens/?0NQ4jg

Ça déborde en bas.
Solution ? Rajouter des lignes jusqu'à mettre un peu plus d'espace sous l'image ?

**Comment by ArthurHoaro** [comment]
Fixed by #687
