### ISSUE TITLE
RSS / link not rendered correctly

### ISSUE THREAD

**Issue by Nono-m0le** [shaarli/Shaarli#1134]
Bonjour L'équipe !

Since some times, I've noticed on some feed that the url of a "shaarlink" (the permalink of the shaarli) isn't rendered correctly into my feed. It seems that even the ?do=atom url can't rendered correctly the link : 
Example of not working feeds : 
http://orangina-rouge.org/shaarli/?do=atom
http://shaarli.sebw.info/?do=atom
https://www.lagilb.fr/Shaarli/?do=atom

Notice the "`<a href="http://orangina-rouge.org/shaarli/?axldog" title="Permalien">Permalien</a>`" for the permalink.

Example of working feed: https://shaarli.m0le.net/?do=rss where we can see directly the url under "Permalink".

Those feeds may have in common that they are on a mutualised environment.

**Comment by ArthurHoaro** [comment]
I'll try to look into it, however, it works fine [in the demo](https://demo.shaarli.org/?do=atom) which use the master branch. 

@OranginaRouge (if you receive notifications), which version are you using?

**Comment by OranginaRouge** [comment]
Salut!
I used v0.9.5 : https://github.com/shaarli/Shaarli/releases/tag/v0.9.5

**Comment by ArthurHoaro** [comment]
Thank you. This happens with `security.markdown_escape` setting set to `true`, because the whole shaare content including the permalink is passed to the plugin.

**Comment by ArthurHoaro** [comment]
You can edit this setting directly in `data/config.json.php`:
```json
"security": {
  "markdown_escape": false
}
```

Note that this may lead to XSS vulnerability in markdown processing, but it shouldn't really matter if you are not hosting a shared instance.

**Comment by OranginaRouge** [comment]
Ok but:
* is it a permanent correction ? i mean, will it be set like this in next version ?
* ` this may lead to XSS vulnerability`... it doesn't sound like a good thing to do...

**Comment by ArthurHoaro** [comment]
> is it a permanent correction ? i mean, will it be set like this in next version ?

We do not change user settings in the update process.

> this may lead to XSS vulnerability... it doesn't sound like a good thing to do...

I agree, but as I said if you're the only administrator, it doesn't really matter, and it's less extreme that disabling markdown entirely. 

Anyway, this issue will be fixed, probably within the next release.

**Comment by OranginaRouge** [comment]
I confirm that, while using markdown extension, setting `security.markdown_escape` to `true` fix (temporaly) the issue (and because i'm the only admin ;-) )
