### ISSUE TITLE
Datastore suddenly zeroed 

### ISSUE THREAD

**Issue by F5v7akm2x** [shaarli/Shaarli#1136]
Is it possible to recover something from history? Thank you.

**Comment by ArthurHoaro** [comment]
Hi, no unfortunately the only way to recover you data is a backup.
When you said it "suddenly zeroed", do you think this is an issue related to Shaarli?

**Comment by ArthurHoaro** [comment]
Closing due to lack of feedback. Feel free to reopen if you have more information regarding this issue.
