### ISSUE TITLE
[Q] Folder like structure?

### ISSUE THREAD

**Issue by Offerel** [shaarli/Shaarli#1139]
I haven’t installed Shaarli as of now, I was only in search for a bookmarking service and played a little bit with the demo.  Currently I use Firefox and Chrome and organize my bookmarks in folders. If I understand that correctly, there is no folder like concept in Shaarli? Is there something similar or mostly similar to folders?

**Comment by virtualtam** [comment]
Hi @Offerel!

Bookmarks are stored in a flat structure as of now, so there is no hierarchy. Allowing nested tags would be a nice improvement, there is an existing discussion on #412 :)

Closing as a duplicate.
