### ISSUE TITLE
wallabag urls are not parseable?

### ISSUE THREAD

**Issue by gerroon** [shaarli/Shaarli#1147]
Hi

The wallabag plugin seems to create urls like this below which causes issues with Wallabag like not recognizing the url. 

The actual url (also shown in Shaarli)
```https://linode.com/docs/security/ssl/install-lets-encrypt-to-create-ssl-certificates/```

The wallabag plugin result
```https://mydomain.com/?plainurl=https%3A%2F%2Flinode.com%2Fdocs%2Fsecurity%2Fssl%2Finstall-lets-encrypt-to-create-ssl-certificates%2F```

When you hover over the Wallabag icon in the Shaarli page  under an entry the url is shown properly, but when copied (via right click) to clipboard or clicked to send to Wallabag, the url is sent like above.

Using it on 
Wheezy
PHP 5.6.32-1
Apache/2.2.22
Shaarli 0.9.6

thanks

**Comment by ArthurHoaro** [comment]
Hi, sorry for the delay.

I don't use Wallabag, so I'm not sure what sure what your issue is. Do you mean that Wallabag expects a non encoded URL?

ie `https://mydomain.com/bookmarklet?url=https://shaarli.readthedocs.io` instead of `https://mydomain.com/bookmarklet?url=https%3A%2F%2Fshaarli.readthedocs.io`?

**Comment by gerroon** [comment]
@ArthurHoaro  I am not sure, I am not a dev but the urls submitted Shaarli are not parseable by wallabag since it cant grab the content from the urls, my assumption was that it is the result of those url format. It normally grabs the content if the url is submitted in its natural form.

**Comment by lgwapnitsky** [comment]
is it possible to configure the wallabag protocol to use the new api with client key and client secret? I think that may be part of the issue.

**Comment by ArthurHoaro** [comment]
Sorry for the delay. I have run a few tests, it works fine with `WALLABAG_URL` set to `2`.

I'll submit a PR setting a default value for this parameter. I have also fixed a minor encoding issue.
