### ISSUE TITLE
Provide a proper datastore for the demo

### ISSUE THREAD

**Issue by ArthurHoaro** [shaarli/Shaarli#1148]
Currently, the demo's datastore resets every night with the default post installation two links.

In order to show Shaarli's features regarding search, tag cloud, thumbnails, etc., it would be nice to have a test datastore with a bunch of example links.

**Comment by nodiscc** [comment]
Just exported this from the demo instance

```html
<!DOCTYPE NETSCAPE-Bookmark-file-1>
<META HTTP-EQUIV="Content-Type" CONTENT="text/html; charset=UTF-8">
<!-- This is an automatically generated file.
     It will be read and overwritten.
     Do Not Edit! -->
<TITLE>Shaarli demo (master)</TITLE>
<H1>Shaarli export of all bookmarks on Sat, 16 Jun 18 19:13:05 +0000</H1>
<DL><p>
<DT><A HREF="https://vimeo.com/153493904" ADD_DATE="1529174414" PRIVATE="1" TAGS="shaarli,help,video">quicksilver (loop) on Vimeo (Shaarli thumbnail demo)</A>
<DD>Shaarli will automatically pick up the thumbnail for links to a variety of websites.

Explore your new Shaarli instance by trying out controls and menus.
Visit the project on [Github](https://github.com/shaarli/Shaarli) or the [documentation](https://shaarli.readthedocs.io/en/master/) to learn more about Shaarli.

Now you can edit or delete the default shaares.
<DT><A HREF="?AJSD5Q" ADD_DATE="1529140026" PRIVATE="1" TAGS="shaarli,help">Note: Shaare descriptions</A>
<DD>Create a new shaare by clicking the [`+Shaare`](https://demo.shaarli.org/?do=addlink) button, or using any of the recommended [tools](?do=tools).
Shaarli allow you to bookmark your favorite pages, and share them with others.
Each share has a unique [permalink](https://demo.shaarli.org/?AJSD5Q).
Adding a shaare without entering an URL create a text-only &quot;note&quot; post such as this one.
You can use this to keep notes, post articles, code snippets, and much more.
A description can be added for any of your Shaares. The markdown [plugin](?do=pluginadmin) allows for more formatting options including:

### Title headings
#### Multiple headings levels

* bullet lists
* _italic_ text
* **bold** text
* ~~strike through~~ text
* `code` blocks
* images
* [links](https://en.wikipedia.org/wiki/Markdown)

You can attach **tags** to your shaares. For example, this one is tagged `shaarli` `help`.
You can browse tags by clicking them, typing multiple tags in the `Search tags` bar, or visiting the [tag cloud](?do=tagcloud) for more options. &quot;Hashtags&quot; such as #shaarli #help are also supported.
You can also filter the [RSS feed](https://demo.shaarli.org/?do=atom) and  [Picture wall](?do=picwall) by tag or plaintext search.
<DT><A HREF="https://github.com/shaarli/Shaarli" ADD_DATE="1529139971" PRIVATE="1" TAGS="shaarli,help">GitHub - shaarli/Shaarli: The personal, minimalist, super-fast, database free, bookmarking service - community repo</A>
<DD>Welcome to Shaarli!
The default shaares are private. You can only see them when logged in.

Use the filter buttons to display only public or private shaares.
</DL><p>

```

The order should be reversed though

**Comment by nodiscc** [comment]
Actually the above would be a good default shaare list for all new installs, don't you think?

We can add extra shaares to the demo instance to demo other functionality: Markdown tables example;

```html
<DT><A HREF="https://en.wikipedia.org/wiki/Classless_Inter-Domain_Routing" ADD_DATE="00000000" PRIVATE="0" TAGS="doc,admin,network">VLSM/Classless Inter-Domain Routing - Wikipedia</A>
<DD>* https://oav.net/mirrors/cidr.html

| Prefix | Mask | Subnets | Hosts |
| ----   | ---- | ------- | ----- |
| /25    | 128  | 2       | 126   |
| /26    | 192  | 4       | 62    |
| /27    | 224  | 8       | 30    |
| /28    | 240  | 16      | 14    |
| /29    | 248  | 32      | 6     |
| /30    | 252  | 64      | 2     |



```

**Comment by virtualtam** [comment]
It's nice for the demo to showcase a selection of key features, but we should avoid cluttering a default installation with bookmarks that are too "computer-science"-centric.

I had the opportunity to participate to a workshop organized by Framasoft last week ([event](https://www.agendadulibre.org/events/17064), [framapad](https://bimestriel.framapad.org/p/contribatelier-toulouse)) where we ran a couple UI/UX sessions with volunteer users, and there was some confusion regarding what Shaarli does, and how to get started with its usage. I'll post the minutes for these sessions in the upcoming days - still have to sort / sum up user feedback and check how it fits with existing issues :)

**Comment by nodiscc** [comment]
The 3 bookmarks from my first comment are not computer centric and give a quick gist of basic Shaarli usage.

The table demo was only meant for the demo instance, to show off markdown tables. But I agree it is not required.

> there was some confusion regarding what Shaarli does, and how to get started with its usage
> I'll post the minutes for these sessions in the upcoming days

It would be great! I think a cleanup of the documentation home page to summarize what Shaarli can do, plus a few screenshots would go a long way. I have started something in https://github.com/shaarli/Shaarli/pull/1155

**Comment by ArthurHoaro** [comment]
Unfortunately, `vimeo.com` seems to have banned my server's IP range. It means that the demo thumbnail is not working on the demo. We should probably use another default bookmark for thumbnail example.
