### ISSUE TITLE
qrcode plugin links to unsecured third-party site

### ISSUE THREAD

**Issue by rudeyak** [shaarli/Shaarli#1149]
The current qrcode.html plugin is super useful... but links to an unencrypted third-party site (http://qrfree.kaywa.com/?l=1&amp;s=8&amp;d=%s), which can cause some mixed-mode issues for those shaarli instances hosted under an https:// schema, or potentially privacy or availability issues with the third-party service.

A suggestion/fix that has worked for me: include a copy of https://github.com/edent/QR-Generator-PHP in the plugins/qrcode directory and change qrcode.html to reference that instead, e.g.

`... href="plugins/qrcode/QR-Generator-PHP/php/qr.php?d=%s" onclick="showQrCode(this); return false;" class="qrcode" data-permalink="%s" ...`

**Comment by virtualtam** [comment]
I'd suggest https://github.com/endroid/qr-code that is more actively tested and maintained.

**Comment by ArthurHoaro** [comment]
It looks good to me.

**Comment by ArthurHoaro** [comment]
Actually... the HTTP `qrfree` link isn't used at all. The plugin includes JS which generates the QRCode and there is no need for an external link. I'll just remove it.
