### ISSUE TITLE
Redirect to homepage after adding a link via "Add Link" dialog

### ISSUE THREAD

**Issue by e2jk** [shaarli/Shaarli#115]
When I add a page to Shaarli, I usually do it one at a time. I do not use the bookmarklet, so my process goes as such:
- I find an interesting page
- I open my Shaarli page
- I log in (sometimes I'm still logged in, but it is definitely not reliable...)
- I click on Add Link
- I paste the URL of the interesting page, and hit Save

Then I usually want to confirm that the addition worked, so I want to see the main page. But after having added a link, Shaarli brings me back again to the page to add a new link, so I need to click on the logo in the upper left part.

The question I want to ask the community is as follow: Do you see benefit/use the fact that after having added a new link, you are prompted to add a new one?

If it was just up to me, I'd have Shaarli redirect to the home page after adding a link, providing a visual confirmation that all worked fine.

What are your thoughts?

**Comment by nodiscc** [comment]
I agree, Shaarli should redirect to the home page after hitting `Save` when the previous page was `?do=addlink`. Maybe we can use the HTTP referrer or the `returnurl` variable for this.

**Comment by pikzen** [comment]
Yup, redirecting to a new addlink page makes little sense to me. Redirecting to / seems to be the most logical thing to do.

**Comment by virtualtam** [comment]
Could this be left for the user to choose? A simple `Add an other link` checkbox would do the trick :)

Let me explain:
* +1 for home usage: add a link, go back to the home page;
* -1 for work usage: I sometimes don't have access to Shaarli for a couple days (thanks to companies' overzealous proxy filtering policies); links then agglutinate in an e-mail draft before being all added at the same time... in which case cycling through `home > add link > home > add link >...` would just be a pain.

**Comment by nodiscc** [comment]
The checkbox idea is fine, valid usecase (batch adding links)

**Comment by e2jk** [comment]
Either the checkbox (which still has you perform a one-by-one copy/paste
action), or we could change the <input> where you type in the URL to be a
<textarea> that allows you to paste one url per line, so that you could add
X>1 links at once.

I think we have to protect ourselves against the checkbox-itis when there
might be other options available.

**Comment by nodiscc** [comment]
> allows you to paste one url per line, so that you could add X>1 links at once. 

So what happens when you click `Add link` and have multiple links in the area? Does it send you to a series of `editlink` dialogs?

**Comment by e2jk** [comment]
I would suggest the template that is used to edit the links is repeated for each link.
I'd like to split this issue into 2 discussions:
- One to redirect to the home page after adding a link (the original intent of this issue/question)
- One to better support batch-adding links (which was raised as a potential downside to redirecting to the home page, and for which I think we can do better than serial copy/pasting into this single form).

**Comment by nodiscc** [comment]
Thanks @e2jk Let's redirect to the previous search first, just like we do after deleting a link. @virtualtam Please report a new bug for batch-adding links if you want.
