### ISSUE TITLE
Bulk operation suggestions

### ISSUE THREAD

**Issue by helmut72** [shaarli/Shaarli#1160]
* select all / select all in this page / select all from search result
* add tag to selected
* remove/change tag from selected
* un/mark private from selected

There is only a delete button enabled on my installation. Do I need some further configuration? I'm using Shaarli 0.9.3. Thanks!

**Comment by virtadpt** [comment]
Those are essential things to do.  "Checkmark these entries to select them" doesn't exist in Shaarli yet, as far as I know.

**Comment by ArthurHoaro** [comment]
Thank you for your suggestions. The multi-select button is sort of new, so it doesn't have much features yet.

**Comment by ArthurHoaro** [comment]
Related to #572

**Comment by dajare** [comment]
+1 for @helmut72's suggestion of:

> - un/mark private from selected

(Along with some form of "multi-select".)

I've just imported an archive of 1,000+ bookmarks in a new instance of Shaarli. For some reason (not sure why, but there must be a reason!), 598 came in as "private links". I would like these to be "public", but I don't think I'll be doing this manually! 😬
