### ISSUE TITLE
i can't loggin, beeing banned

### ISSUE THREAD

**Issue by deneth** [shaarli/Shaarli#1161]
Yesterday i did a fresh install with version 0.9.7, and imported my datastore.php file. I also installed pluggins and theme, all was fine.
But today i can't login. I don't see login form, i have error message : "You have been banned after too many failed login attempts. Try again later.". I looked at ipbans.php file, but there is no ip in it.
I tried various things, like chown, chmod, i also deleted ipbans.php file, but i still have this error message.
May someone help me ?

**Comment by ArthurHoaro** [comment]
Can you give us more information about your setup? Are you behind a reverse proxy, etc.?

However, if you deleted the `ipbans.php`, you should be fine regarding to the code... Can you try to clear with browser cache after that? And eventually check that the file didn't magically reappeared?

**Comment by deneth** [comment]
I found what's wrong.
i backed up my data folder, my theme folder and all plugins folder i used.
I deleted shaarli folder, and did a fresh install. After i put my backed up folders, i got the same error !

So , i did another re-install, then restore only my theme folder, and i got the error. So it's my theme fault.
I modified the config file and put the default theme. 

My theme is only the default theme modified. I changed some colors, add a background pic, and use Font-Awesome 5 ( cause mastodon icon is only in FA 5 ).

So i did a copy of theme default, and did change step by step. Last step was adding FA 5, i was worried, but in the end it worked. So i have a new theme rebuild, and my old theme, they are the same, but one is ok, and one not :) it's weird !

Maybe i did some change in the old, that i didn't remember.

Sorry for beeing long, hope you understand.

**Comment by nodiscc** [comment]
> Maybe i did some change in the old, that i didn't remember.

Probably :) If you modified the default template it would be best to save your changes as a patch (using `diff`) or storing them in a git branch. This way you can

 * re-apply your changes when the default template receives changes here
 * attach your patch to issue reports (we had no way to know you were using a custom template:) )
