### ISSUE TITLE
Notice: Undefined index: redirector

### ISSUE THREAD

**Issue by eko133** [shaarli/Shaarli#1163]
After I installed Shaarli v0.9.7 on my linux server. I got an notice "Undefined index: redirector in /path/index.php on line 1155" everytime I save Shaarli configurations. Is that normal?

**Comment by nicolasdanelon** [comment]
@eko133 can you provide php + apache + nginx version? also shaarli version ;)

**Comment by ArthurHoaro** [comment]
This issue has been fixed with #1102 and will be released with `v0.10`. Note that you should never display PHP errors on a production instance.
