### ISSUE TITLE
Add markdown extra to markdown plugin

### ISSUE THREAD

**Issue by trailjeep** [shaarli/Shaarli#1169]
Shaarli is a great app.
I currently use [DokuWiki](https://www.dokuwiki.org/dokuwiki) for note taking and I've transitioned my bookmarks to Shaarli, but I've always wanted 1 app to unify notes and bookmarks and I think with the addition of parsedown extra to the already used parsedown I could achieve this (the addition of IDs and classes is part of what I'm really looking for.)
Combined with the related links plugin I would have everything I need.
I know this app is a bookmark manager, but it is so lightweight and fast it could be the perfect notes manager too.

**Comment by ArthurHoaro** [comment]
Thank you for the suggestion. 

https://github.com/erusev/parsedown-extra

**Comment by trailjeep** [comment]
If anyone else is interested I added it to my Shaarli and it works beautifully.

Prerequisite: `composer`

1. Add `"erusev/parsedown-extra": "0.7.1",` After `"erusev/parsedown": "1.7.1",` to `Shaarli/composer.json`
2. Run: `$ composer update --no-dev`
3. In `Shaarli/plugins/markdown/markdown.php` Change: `$parsedown = new Parsedown();` To: `$parsedown = new ParsedownExtra();`

Reference: [Markdown Extra](https://michelf.ca/projects/php-markdown/extra/)
