### ISSUE TITLE
Shaare link on Brave

### ISSUE THREAD

**Issue by cailab** [shaarli/Shaarli#1172]
I'm unable to drag the Shaare Link button to the toolbar on Brave (Linux Mint 18.3). Also cannot save link to toolbar using right click.

**Comment by ArthurHoaro** [comment]
Hi,

> [Currently bookmarklet does not work on Brave](https://community.brave.com/t/issues-with-bookmarklets/1999)

Also, from my understanding, Brave doesn't support Chrome's extension yet. I don't think there is an easy way to save links with this browser.
