### ISSUE TITLE
Shaarli API responses should include CORS headers

### ISSUE THREAD

**Issue by ArthurHoaro** [shaarli/Shaarli#1174]
Without them, any client side AJAX request to Shaarli API will probably end up with a browser error.

See https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS

**Comment by virtualtam** [comment]
Looking at the Mozilla docs, this applies when a service (e.g. frontend) sends requests to a service (e.g. backend/API) that is served under a different (sub-)domain. As of now, all Shaarli services (UI, backend, API) are available through a single domain, so it should not be necessary to send CORS headers - unless I'm missing a use case?

**Comment by ArthurHoaro** [comment]
The use case would be if I wanted to use Shaarli's REST API using a frontend app, such as a WebExtension, or any kind of frontend UI.
