### ISSUE TITLE
Stored XSS in Shaare

### ISSUE THREAD

**Issue by DrStacheWH** [shaarli/Shaarli#1183]
**Description**:
Cross-site scripting (XSS) vulnerability in Shaarli allow remote attackers (users) to inject arbitrary web script or HTML via the Shaare editor.

**Vulnerability Type**: Stored XSS

**Attack Vector**:

1. Login
2. Create a new *Shaare* [https://demo.shaarli.org/?post=test](https://demo.shaarli.org/?post=test)
3. Set ```<a href=javascript:alert(document.cookie)>Click Here</a>``` as description

Now when someone will click on the *Click Here* link in the newly created *Shaare*, ```alert(document.cookie)``` will be executed.

**Comment by ArthurHoaro** [comment]
Hi, this issue has already been reported and fixed with the `security.markdown_escape` setting set to true (default value). See #785 

For some reason I forgot to apply it to the demo instance...

**Comment by DrStacheWH** [comment]
Oops, I hadn't seen it...

**Comment by virtualtam** [comment]
Hi @DrStacheWH,

For future security reports, please consider contacting project maintainers directly (e.g. using email); this avoids publicly disclosing vulnerabilities and gives people time to fix the vulnerability before a patch is released, and the vulnerability is documented as a CVE/CVS.

**Comment by virtualtam** [comment]
Closing as the issue has been fixed and applied to the demo instance.
