### ISSUE TITLE
Upgrade / Install to 0.10

### ISSUE THREAD

**Issue by schklerg** [shaarli/Shaarli#1187]
Trying fresh install & upgrade, both get

yarn install
ERROR: [Errno 2] No such file or directory: 'install'
Makefile:162: recipe for target 'frontend_dependencies' failed
make: *** [frontend_dependencies] Error 1

If I try to get beyond it the best I can do is a page loading with no css or anything which throws an error related to a missing js file.  

Was doing an upgrade from .97 to .10, but I also tried fresh.  Debian 9.5

**Comment by virtualtam** [comment]
Hi @schklerg,

How did you install Shaarli? From the Git sources, a Git tarball or a release archive?

We provide full release archives that contain all dependencies needed to run Shaarli:
- https://shaarli.readthedocs.io/en/master/Download-and-Installation/#download-as-an-archive
- https://shaarli.readthedocs.io/en/master/Upgrade-and-migration/

**Comment by NachoParra** [comment]
Hi,

I have just upgraded from 0.9.6 to 0.10 via download of new zip file and moving the data folder from the old version and I'm having the same error

`Loading failed for the <script> with source “https://aupacommon.noip.me/shaarli/tpl/default/js/shaarli.min.js?v=41c5dba1b0295e8c31cf9d87d1f31d04ca85f1fb363c69f47a016eedecd896de”.`
`Loading failed for the <script> with source “https://aupacommon.noip.me/shaarli/tpl/default/js/thumbnails.min.js?v=41c5dba1b0295e8c31cf9d87d1f31d04ca85f1fb363c69f47a016eedecd896de”.`

I'm going to check the code vs the old version.

**Comment by virtualtam** [comment]
With Git, the whole update process looks like this:

```shell
$ cd /path/to/shaarli
$ git checkout master
$ git pull --prune
$ composer install --no-dev --prefer-dist
$ yarn install
$ yarn run build
```

**Comment by NachoParra** [comment]
@virtualtam It's working for you without any loading failed error?

I have found that the code is called on "./tpl/default/page.footer.html", 

`<script src="js/shaarli.min.js?v={$version_hash}"></script>`

But there is no js subfolder there

**Comment by NachoParra** [comment]
Hi,

I have just upgraded from 0.9.6 to 0.10 via download of new zip file and moving the data folder from the old version and I'm having the same error

Loading failed for the <script> with source “https://mysite/shaarli/tpl/default/js/shaarli.min.js?v=41c5dba1b0295e8c31cf9d87d1f31d04ca85f1fb363c69f47a016eedecd896de”.
Loading failed for the <script> with source “https://mysite/shaarli/tpl/default/js/thumbnails.min.js?v=41c5dba1b0295e8c31cf9d87d1f31d04ca85f1fb363c69f47a016eedecd896de”.

Checking the code I can see that these files are missing inside the `/shaarli/tpl/default/js` folder. The whole js folder is missing from the default one. Also, css, fonts, & img folders are missing.

**Comment by ArthurHoaro** [comment]
Crap. Assets file are now git-ignored in the `tpl` folder and built with webpack. Except the archives are build with `git archive` which excludes ignored files. I've rebuilt them, please redownload the `full` tarball from the [release page](https://github.com/shaarli/Shaarli/releases/tag/v0.10.0), it should be fixed.

**Comment by NachoParra** [comment]
Hi @ArthurHoaro ,
Yes, now it's working. Thanks a lot for the quick fix.
Kind regards

**Comment by schklerg** [comment]
You rock.  Fixed perfectly.  I love the new thumbnail feature too.
