### ISSUE TITLE
Daily Shaarli

### ISSUE THREAD

**Issue by Arrappathor** [shaarli/Shaarli#1190]
Hi!
Daily Shaarli shows blank page in v0.10.0.
Thanks again!

**Comment by agentcobra** [comment]
erreur 500 pour moi

**Comment by agentcobra** [comment]
is it linked with ?
https://github.com/shaarli/Shaarli/blob/ad5f47adbaee1eef85e90950ab8a45fe82959924/application/Thumbnailer.php#L53-L70

**Comment by ArthurHoaro** [comment]
Thank you for the report, I forgot the daily page when I was working on the new thumbnails system. #1191 should fix your issue.

**Comment by agentcobra** [comment]
fixed for me with #1191
