### ISSUE TITLE
`demo_plugin` plugin makes Shaarli Version `0.10.0` display a blank screen when enabled

### ISSUE THREAD

**Issue by VLNTNO** [shaarli/Shaarli#1192]
Hi,

I tried to hack the `demo_plugin` plugin. When I activate it (unchanged) on shaarli version `0.10.0`, I get a blank screen.

However, I could revert the previous configuration and neutralize the bug by removing the mention to the `demo_plugin` plugin in the `/data/config.json.php` file, section `general`>`enabled_plugins`.

**Comment by ArthurHoaro** [comment]
A blank screen usually means a PHP fatal error. Can you check you logs to report the logged error?

**Comment by VLNTNO** [comment]
I don't know how to get the correct log.

I run my instance on an OVH "hébergement mutualisé" pack.

**Comment by ArthurHoaro** [comment]
I don't know OVH's shared hosting but maybe [this](https://docs.ovh.com/fr/hosting/mutualise-consulter-les-statistiques-et-les-logs-de-mon-site/) can help you. Otherwise you can very temporarily uncomment the line in `index.php` ligne 41, which should display PHP errors in your browser.

**Comment by Draky50110** [comment]
0.10 introduces a new .htaccess if I'm not wrong.
That causes error 500 for me so I deleted it.

**Comment by ArthurHoaro** [comment]
Closing due to lack of feedback. Feel free to reopen with more information.
