### ISSUE TITLE
0.10.0 : no thumbnails

### ISSUE THREAD

**Issue by Draky50110** [shaarli/Shaarli#1197]
Hello.
Updated from 0.9.6 and synced thumbnails as asked by Shaarli.
None displayed : https://gilles.wittezaele.fr/pro/liens/
Linked to #1196 ?

**Comment by ArthurHoaro** [comment]
This is probably related to the other issue because trying to access a thumbnail issues an error 500, e.g. https://gilles.wittezaele.fr/pro/liens/cache/thumb/d79e51d08a4e207721887893015dcd7c/f8c9d1dc36d7b3ab9a8db34d7cb022fdfca755c41259010.jpg

**Comment by ArthurHoaro** [comment]
Duplicate of #1196
