### ISSUE TITLE
"You are not authorized to add a link." after 0.10 upgrade

### ISSUE THREAD

**Issue by Marsup** [shaarli/Shaarli#1198]
Hi!

I just upgrade from 0.9.7 to 0.10 via tarball. Retried this several times and it's always the same.

On 1st access it goes well, my list of links is shown, on any browser, then I proceed to login, which is quite long, I guess due to a migration. And from this moment, all browsers that are not logged in return a `You are not authorized to add a link.` error, of course once the cookie expires the one that was logged in does the same.

Just to be clear, it happens on the root url, I'm not trying to add anything, just to access the main page.

Any clue as to what might be happening during that migration ?

**Comment by ArthurHoaro** [comment]
Hi. I'm not really able to reproduce your issue.

> Any clue as to what might be happening during that migration ?

The only thing that can take long, is retrieving the thumbnails for your first links. To be clear, on the first login, you should have been asked to synchronize your thumbnails. If you don't, they'll be retrieved the first time they're displayed.

Looking back at the code, I think I understand what's going on. Shaarli's tries to update your thumbnails, meaning altering the datastore, whether you're logged in or not. For some reasons your update has failed (maybe you can check your logs for that), so the new thumbnails system is enabled, but visitors can't update them.

I'll work on a patch, but I'm a bit busy and it may not come until next week.

**Comment by Marsup** [comment]
To add some information, I was asked right after the upgrade to install php-gd btw, which I did before anything else. Could I be missing another lib or would it report it ?

Once I log in, I'm offered to do the migration in the top banner, nothing while visiting "anonymously". I once did the full generation of thumbnails, it displayed nothing but broken images during the process, not sure if it's normal, but it didn't work either even once finished, as there wasn't any thumbnail after that.

There are no errors logged in php-fpm logs nor nginx, but that wouldn't be the 1st time a php program fails silently for me.

**Comment by izumitelj** [comment]
I had similar problem (same error message) after trying to search for more than one tag (while not being logged in)... As suggested by @ArthurHoaro I didn't let the updater finish generating the thumbnails (I have many bookmarks), and after doing so, issue is now resolved.

**Comment by Cyrixo** [comment]
I have the same error message. If it helps, here is the log

`[php7:error] [pid 449] [client 66.XXXXXX:35658] PHP Fatal error:  Uncaught Error: Call to undefined function thumbnail() in /usr/share/webapps/shaarli/index.php:436\nStack trace:\n#0 /usr/share/webapps/shaarli/index.php(723): showDaily(Object(PageBuilder), Object(LinkDB), Object(Shaarli\\Config\\ConfigManager), Object(PluginManager), Object(Shaarli\\Security\\LoginManager))\n#1 /usr/share/webapps/shaarli/index.php(1863): renderPage(Object(Shaarli\\Config\\ConfigManager), Object(PluginManager), Object(LinkDB), Object(History), Object(Shaarli\\Security\\SessionManager), Object(Shaarli\\Security\\LoginManager))\n#2 {main}\n  thrown in /usr/share/webapps/shaarli/index.php on line 436`
And
`[php7:notice] [pid 354] [client 195.XXXXXX:35654] No thumbnail could be found using default finder`

**Comment by Marsup** [comment]
I retried today on a logged in session, shaarli is trying to access thumbnails on the wrong path, that is for example `GET /shaarli/-a59798f9c47f/shaarli/cache/thumb/a3e89d341a5214f2627d723cafdff433/8093d5b3d85ace10fc44efa77a1f2eddc34298801259010.jpg`.

The `-a59798f9c47f/shaarli` part shouldn't be there and then it would be a valid url, and it is actually an incomplete chunk of the physical path where shaarli is hosted, how could it leak to the frontend ?

I checked my nginx config in regards to shaarli's docs, couldn't spot any error.

**Comment by ArthurHoaro** [comment]
#1199 should fix the issue regarding the link edit while logged out. @Cyrixo can you test it if you still have the error?

@Cyrixo your first error is related to #1190 which have been fixed but not released yet. The second one is just a warning and should only appear if you have `dev.debug` set to true in your config file.

@Marsup can you open a separate issue regarding thumbnails path?

**Comment by Marsup** [comment]
Sorry, I thought it could be related, created #1201.
