### ISSUE TITLE
Thumbnails urls are wrong in 0.10

### ISSUE THREAD

**Issue by Marsup** [shaarli/Shaarli#1201]
Since 0.10, shaarli is trying to access thumbnails on the wrong path, that is for example `GET /shaarli/-a59798f9c47f/shaarli/cache/thumb/a3e89d341a5214f2627d723cafdff433/8093d5b3d85ace10fc44efa77a1f2eddc34298801259010.jpg`.

The `-a59798f9c47f/shaarli` part shouldn't be there and then it would be a valid url, and it is actually an incomplete chunk of the physical path where shaarli is hosted, how could it leak to the frontend ?

I checked my nginx config in regards to shaarli's docs, couldn't spot any error.

**Comment by ArthurHoaro** [comment]
Thank you. The thumbnailer try to create a relative path to the thumbnail. For that, it takes the PHP script's absolute path, and remove that part from the image absolute path.

Can you provide more information about your server setup: web server, is it a shared hosting, reverse proxy, etc. 

Also, can you create a temporary PHP file containing:

```
<?php var_dump($server['SCRIPT_FILENAME']);
```
And give us it's content by accessing it through you your browser?

**Comment by Marsup** [comment]
I use nginx + php-fpm, no reverse proxy, and it's my own server.

That php file gives `NULL`.

**Comment by ArthurHoaro** [comment]
Sorry, I copy pasted too quickly:

`<?php var_dump($_SERVER['SCRIPT_FILENAME']);`

**Comment by Marsup** [comment]
`string(35) "/usr/share/nginx/html/shaarli/t.php" `
It is to be noted that this folder is a symlink to somewhere else, hence the `-a59798f9c47f` in the original post.

**Comment by ArthurHoaro** [comment]
Thank you. I'll try to find a more universal way to retrieve the thumbnail path.

**Comment by nicolasdanelon** [comment]
can you use the `__DIR__` const ?

**Comment by ArthurHoaro** [comment]
@nicolasdanelon No because `__DIR__` will return the path of the PHP file, not the one of the cache folder which can be configured.

I've found the issue, I use `[realpath()](http://php.net/manual/en/function.realpath.php)` to get the absolute path, which resolves symlinks. I'm working on it.

**Comment by Marsup** [comment]
Fix confirmed, it's still scanning but so far so good, both thumbnails and anonymous access are working. Thanks a lot!
