### ISSUE TITLE
Hashtag and markdown

### ISSUE THREAD

**Issue by Knah-Tsaeb** [shaarli/Shaarli#1210]
Hi,
when plugin markdown is active, the hashtag system are broken. The workaround is set markdown_escape to true in config.json.php but is not a good solution.

You can reproduce this bug in the demo instance.

Have a nice day

**Comment by ArthurHoaro** [comment]
Thanks for the report. :+1: 

#1212 should fix the issue.

**Comment by Knah-Tsaeb** [comment]
Thanks.

**Comment by Draky50110** [comment]
I put hashtags with escape char : \#hashtag instead of #hashtag.

**Comment by ArthurHoaro** [comment]
It doesn't work as a hashtag if you do that.

**Comment by Draky50110** [comment]
It "displays" it as a hashtag, that's better than displaying it with "a href class hashtag" and so...
