### ISSUE TITLE
Delete tags

### ISSUE THREAD

**Issue by jeekajoo** [shaarli/Shaarli#1214]
Hi,

We cannot delete tags from "taglist" page. It does nothing and it doesn't throw error.
`"POST /links/?do=changetag HTTP/1.1" 200 43`
Shaarli version : 0.10.2

![](https://framapic.org/vKP7nm2v3mI1/GHwJvPxcSSii)

You can reproduce this bug in demo : https://demo.shaarli.org/?do=taglist&sort=usage

Thanks

**Comment by ArthurHoaro** [comment]
Thank you for the report. #1215 should fix it.
