### ISSUE TITLE
add lang attribute on html tag - accessibility issue

### ISSUE THREAD

**Issue by llune** [shaarli/Shaarli#1216]
Currently there is no lang attribute on the html tag thus preventing assistives technologies to determine the default language of the document.

For example a screenreader might not read the content with the proper pronunciation.

The lang attribute should change dynamically depending on the language set.

https://www.w3.org/TR/WCAG20-TECHS/H57.html

**Comment by ArthurHoaro** [comment]
We can add these. However note it will be ineffective if the instance owner has set the language to automatic, meaning that Shaarli's locale will depends on the browser locale.
