### ISSUE TITLE
Flickr thumbnails without "https://" and "www."

### ISSUE THREAD

**Issue by JerryCrazy** [shaarli/Shaarli#1224]
Hello

I have a problem with Flickr bookmarks, thumbnails are not generated for Flickr links without "https://" and "www.".

![screenshot](https://user-images.githubusercontent.com/13752194/45378647-5a884200-b5fe-11e8-8910-43c7e99fbc75.png)

I think the problem comes from Flickr, but it's a shame because I have to change all my URLs.

Is it possible to work around this problem and generate the thumbnails without modifying all the bookmarks?

Thank you

**Comment by ArthurHoaro** [comment]
Are you using the latest version (`v0.10.2`)? I just tried your example and I get a thumbnail.

![](https://i.imgur.com/sCHkRmY.png)

**Comment by ArthurHoaro** [comment]
Also, do you have `php-curl` extension installed and enabled?

**Comment by JerryCrazy** [comment]
Hello, sorry for the answer time

I did not change anything but my server is generating the thumbnails now ...
I did not understand why he did not generate thumbnails before!
Sorry for this bug report, this is probably a server configuration problem.

**Comment by nodiscc** [comment]
Feel free to reopen if the problem arises again
