### ISSUE TITLE
Can't keep Shaarli account stayed in

### ISSUE THREAD

**Issue by bisherbas** [shaarli/Shaarli#1228]
Below is relevant `php.ini` configuration. When I restart my browser (Chrome or Firefox) I have to log back in each time. All other websites (e.g. Google, Reddit etc.) work just fine. Including the Nextcloud installation on the same VPS server. (Ubuntu 18.04) Could you offer some help? Thanks.

```
Directive | Master Value
-- | --
session.auto_start | Off
session.cache_expire | 180
session.cache_limiter | nocache
session.cookie_domain | xxx.com
session.cookie_httponly | no value
session.cookie_lifetime | 1296000
session.cookie_path | /
session.cookie_secure | 0
session.gc_divisor | 1000
session.gc_maxlifetime | 1440
session.gc_probability | 1
session.lazy_write | On
session.name | PHPSESSID
session.referer_check | no value
session.save_handler | files
session.save_path | /tmp
session.serialize_handler | php
session.sid_bits_per_character | 5
session.sid_length | 26
session.upload_progress.cleanup | On
session.upload_progress.enabled | On
session.upload_progress.freq | 1%
session.upload_progress.min_freq | 1
session.upload_progress.name | PHP_SESSION_UPLOAD_PROGRESS
session.upload_progress.prefix | upload_progress_
session.use_cookies | 1
session.use_only_cookies | 1
session.use_strict_mode | 0
session.use_trans_sid
```

**Comment by virtualtam** [comment]
Hi @bisherbas,

Here are a couple things to check:
- ensure cookie hijacking protection is disabled, you can find this setting under `Tools > Configure your Shaarli > Disable session cookie hijacking protection`
- is your server using IPv6? this could be related to #1106 & #1182

**Comment by bisherbas** [comment]
@virtualtam That setting is unchecked. IPv6 is not enabled on my server.

**Comment by bisherbas** [comment]
I did check the box for the hijacking protection and have not had the same issue for the last few hours. I am not super familiar with this so called `hijacking protection`. Is now my server's security comprised since this protection is disabled?

**Comment by ArthurHoaro** [comment]
Shaarli's stay logged feature is based on the IP address. Meaning that if your IP changes, you'll have to log in again once your session is expired. With this setting enabled, you'll stay logged in even if your IP changes. It also means that if your computer or your browser is compromised, and someone is able to get access to your cookies, he'll be able to use to be logged in using your authentication cookie, even from another IP address.

So if you're using Shaarli behind a dynamic IP or a mobile connection, and it is unlikely that someone will stole your cookies, you may prefer to have this setting enabled.

**Comment by bisherbas** [comment]
@ArthurHoaro Thanks for the explanation. In that case I would expect Shaarli to keep me signed in all the time because my public ID is NOT dynamic. It is always static. And it is IPv4 (if that matters). So even when the hijacking protection option is unhecked, it is expected to stay signed in. Right? But that's not what I experience for some reason.

**Comment by bisherbas** [comment]
Even with disabling hijacking protection Shaarli signs me out every now and then within the same ip address. What can I do to fix it?

**Comment by ArthurHoaro** [comment]
Do you have any extension that would clear your cookies after some time?

**Comment by bisherbas** [comment]
@ArthurHoaro No I don't have any extensions. I have logged in on 4-5 different devices including an iPhone, Android, Desktop PC, and Macbook. I believe the problem is the Shaarli. Obviously I wouldn't know where to look for in the code so I'm asking for help here.

**Comment by bisherbas** [comment]
Still having this problem. Couldn't figure out how to resolve it.

**Comment by bisherbas** [comment]
As long as I do not sign in to my account via different computer and IP address, it stays signed in for prolonged period of time. I guess it's not a serious issue or perhaps it's a non-issue. I propose closing this issue. If you think oterwise feel free to reopen it.

**Comment by altayevrim** [comment]
It happens to me too, when I'm on my wifi and my computer is connected; I cannot login with my phone. There is no error or warning, It logs in and immediately logs out. 
After I checked _Disable session cookie hijacking protection
Check this if you get disconnected or if your IP address changes often_ now it logs in without a problem.
