### ISSUE TITLE
Open Graph meta tags not added on permalink

### ISSUE THREAD

**Issue by kalvn** [shaarli/Shaarli#1242]
I noticed something strange when trying to investigate this issue on Shaarli Material theme https://github.com/kalvn/Shaarli-Material/issues/88

With a fresh install, with default theme, when I open the permalink of a link, I cannot see og meta tags.
![image](https://user-images.githubusercontent.com/6149640/48058050-c7aaf480-e1b5-11e8-9e47-84f2c51594e9.png)

But when I switch to material theme, on the exact same URL I can see them:
![image](https://user-images.githubusercontent.com/6149640/48057820-45bacb80-e1b5-11e8-831e-ba0e2b9360f8.png)

What is weird is that I basically copied your implementation as-is, I cannot see any notable difference. And even weirded, if I check for example [this Shaarli](https://links.hoa.ro/?El5Epw) which uses default theme, og tags are present.

Any idea?

**Comment by nodiscc** [comment]
I cannot see opengraph meta tags on my sShaarli instance either. But they are present on the [demo instance](https://demo.shaarli.org/?)

**Comment by ArthurHoaro** [comment]
Looking at your thread it looks like you have solved your issue? 
To clarify, as you can see in #1205, I've added `description_src` in the markdown plugin which doesn't include any markdown tags.

@nodiscc This PR hasn't been released yet, are you using the `master` branch?

**Comment by kalvn** [comment]
As suggested by @immanuelfodor I just added `strip_tags` in front. It'll make sure we don't have the issue anymore in the future if a non-official plugin plays with the description for example.

**Comment by ArthurHoaro** [comment]
Closing because I think this has been fixed.
