### ISSUE TITLE
How can I reset my password?

### ISSUE THREAD

**Issue by anmol26s** [shaarli/Shaarli#1255]
Hi
I forgot my password and unable to login now. How to reset the password?

**Comment by virtualtam** [comment]
Hi @anmol26s,

You can reset your password by deleting (make sure you backup it first!) the configuration file:
- https://shaarli.readthedocs.io/en/master/Troubleshooting/#i-forgot-my-password

**Comment by anmol26s** [comment]
Thanks 
This has solved my problem.
