### ISSUE TITLE
Search should prioritize shaare titles over description.

### ISSUE THREAD

**Issue by trailjeep** [shaarli/Shaarli#1260]
Just an enhancement request.
When searching I often am looking for keyword in the title, but I have to scroll through many shaares with keyword in the description first.

**Comment by ArthurHoaro** [comment]
Currently the search engine does not prioritize result and just serves links in dates order. So this would mean to only search in the title, which I think is not a good idea in most cases.

`wontfix` for me.

**Comment by ArthurHoaro** [comment]
Closing regarding my previous comment. Feel free to add more information or use cases if you think this should be reopened.
