### ISSUE TITLE
Error installing new theme

### ISSUE THREAD

**Issue by effemmeffe** [shaarli/Shaarli#1263]
I tried a couple of themes and for both of them once I put the folder in tpl and enabled it in the shaarli configuration I get the following error:
`Fatal error: Uncaught RainTpl_NotFoundException: Template configure not found! in /var/www/html/shaarli/inc/rain.tpl.class.php:268 Stack trace: #0 /var/www/html/shaarli/inc/rain.tpl.class.php(164): RainTPL->check_template('configure') #1 /var/www/html/shaarli/application/PageBuilder.php(188): RainTPL->draw('configure') #2 /var/www/html/shaarli/index.php(1068): PageBuilder->renderPage('configure') #3 /var/www/html/shaarli/index.php(1866): renderPage(Object(Shaarli\Config\ConfigManager), Object(PluginManager), Object(LinkDB), Object(History), Object(Shaarli\Security\SessionManager), Object(Shaarli\Security\LoginManager)) #4 {main} thrown in /var/www/html/shaarli/inc/rain.tpl.class.php on line 268`

Any idea how to fix it?
Shaarli 0.10.2
The theme is [Shaarli-material](https://github.com/kalvn/Shaarli-Material)
Ubuntu 18.04
Apache2

**Comment by virtadpt** [comment]
Same thing here.

**Comment by effemmeffe** [comment]
I solved the problem by reinstalling shaarli from scratch, configure it, add the new theme, enable it and then restore the datastore.php

**Comment by nodiscc** [comment]
Looks like you've hit this issue https://github.com/kalvn/Shaarli-Material/issues/90 with Shaarli-Material.

The cause is not known yet but reinstalling the theme reportedly fixes the problem.

Does simply clearing cached files in `tmp/` `pagecache/` and `cache/` have any effect? I cannot reproduce this bug.

Please continue this discussion in https://github.com/kalvn/Shaarli-Material/issues/90 so that all information can be found there.

**Comment by virtadpt** [comment]
Clearing the contents of `tmp/` does not fix the problem.  I haven't tried clearing `pagecache/` or `cache/` yet.  Will try tonight after work.

**Comment by virtadpt** [comment]
I wiped and reinstalled, then restored my datastore and configs, and I get the same errors.

**Comment by nodiscc** [comment]
@virtadpt Do you use https://github.com/kalvn/Shaarli-Material? Can you reproduce with the default theme?

**Comment by virtadpt** [comment]
I tried using Shaarli-Material - it didn't work.  I've been tracking that repo, and every 'official' release breaks Shaarli in the same way.  Cloning the repo also results in Shaarli breaking.

I cannot reproduce with the default theme because it just works right out of the box.  It's only when trying to install other themes that Shaarli breaks.

**Comment by ArthurHoaro** [comment]
Can you make sure that:

  1. The template files are directly in the folder `tpl/material/`, i.e. a bunch of `*.html` files.
  2. In `data/config.json.php`, under `resources`, you have:
    * `raintpl_tpl: "tpl/"`
    * `raintpl_tmp: "tmp/"`
    * `theme: "material"`

**Comment by virtadpt** [comment]
I will give it a try when I get home from work tonight (I can't SSH into my web server from there).

**Comment by ArthurHoaro** [comment]
Closing due to lack of feedback. Feel free to reopen if there is any additional information to this issue.

**Comment by virtadpt** [comment]
I'll give it another go later today.

**Comment by virtadpt** [comment]
@ArthurHoaro 
1) Yup, they're a bunch of HTML files.
2a) `"raintpl_tpl": "tpl\/",` (I've never changed this)
2b) `"raintpl_tmp": "tmp\/",` (never changed this, either)

HOLY CRAP, that's it.

I downloaded the `shaarli-material.v0.10.4.tar.gz` tarball from the Releases tab of that theme.  This resulted in a directory `tpl/material/` this time.  Maybe the directory being called `Shaarli-Material` was the problem?

**Comment by raphaelbastide** [comment]
I had the same issue. I simply changed

**Comment by Labo9** [comment]
> I had the same issue. To solve it, I had to change in `data/config.json.php`:
> ` "theme": "variable"` to ` "theme": "default"`.

Best solution so far ! Solved, yet with another theme (albinomouse-template)
