### ISSUE TITLE
Plugins are not working (outdated?)

### ISSUE THREAD

**Issue by m-schmale** [shaarli/Shaarli#1266]
Hi,

I am wondering whether these plugins do work for someone:

- https://github.com/ArthurHoaro/code-coloration/
- https://framagit.org/Alda/shaarli-autoarchiveorg

Are they outdated, or have I done something wrong? 🤔 

Thanks,
Mark

**Comment by virtadpt** [comment]
I haven't gotten them to work, for what it's worth.

**Comment by ArthurHoaro** [comment]
All 3rd party plugins are broken on the master branch due to namespacing #1248 

@virtualtam Maybe we should release it under a new major version?

**Comment by virtualtam** [comment]
Yes, this makes sense. We could issue a last 0.10.x release featuring all recent commits but namespacing-related ones, and start working towards the next release :)

**Comment by virtualtam** [comment]
`v0.10.3` released!

**Comment by ArthurHoaro** [comment]
Thank you @virtualtam! Out of curiosity, how did you make the release? Did you just make a tag on the commit before #1248 merge?

**Comment by virtualtam** [comment]
Almost :)
`v0.10.3` is a merge of 1826e383ecf501302974132fd443cf1ca06e10f6 with 49106a5d8cf1153b5da23f889d15e46fa480e7cc cherry-picked as a freebie, then tagged and released.

**Comment by ArthurHoaro** [comment]
Namespacing changes have been released with `v0.11.0`. My 3rd party plugins and a few other I know have been updated. Please contact their authors if you still have issues.
