### ISSUE TITLE
Login Wrong Password

### ISSUE THREAD

**Issue by wcypierre** [shaarli/Shaarli#1277]
Today out of the blue Shaarli stopped working (couldn't login), did some troubleshooting according to this [page](https://shaarli.readthedocs.io/en/master/Troubleshooting/), [this](https://github.com/shaarli/Shaarli/blob/master/doc/md/Troubleshooting.md) and this #1064 

After some digging, apparently that after checking the nginx logs, the server is out of disk space and so it didn't worked :) 

Just a heads up in case whoever else is facing this in the future

**Comment by ArthurHoaro** [comment]
Thank you for the feedback. 

As it's neither a bug or a question, I'm closing it.
