### ISSUE TITLE
Thumbnails do not appear, "server" is empty

### ISSUE THREAD

**Issue by ehrlichja** [shaarli/Shaarli#1278]
Using the latest shaarli docker container running on localhost, I see that thumbnails do not get pulled when I press the thumbnail refresh button.

In the logs I see:

```
2019/02/21 19:21:21 [error] 10#10: *172 FastCGI sent in stderr: "PHP message: No thumbnail could be found using default finder: https://www.loc.gov/catdir/cpso/lcco/" while reading response header from upstream, client: 172.17.0.1, server: , request: "POST /?do=ajax_thumb_update HTTP/1.1", upstream: "fastcgi://unix:/var/run/php-fpm.sock:", host: "localhost:8080", referrer: "http://localhost:8080/?do=thumbs_update"
```

I see that "server" is empty; could this be related to the problem?

**Comment by ArthurHoaro** [comment]
There is no thumbnail to retrieve in the link in this log. The message displayed here is only an information and should only be logged while in debug mode, so I'll fix that part.

Do you have the same issue with a link with an image, such as [github.com/ehrlichja](https://github.com/ehrlichja)? If it does not work, you can try to open the permalink in your browser, delete `cache/finder` and `cache/thumb` folders, refresh the page, and check if the finder/thumb is cached properly.

**Comment by ArthurHoaro** [comment]
Closing due to lack of feedback. Please reopen if you have more information to provide.
