### ISSUE TITLE
update from v0.9.7 to v0.10.0 failed

### ISSUE THREAD

**Issue by Trufax** [shaarli/Shaarli#1280]
Hello,

just updated my old Shaarli from v0.9.0 to v0.9.7 without problems. (just replaced all files except the "data" folder". When i tried the update from v0.9.7 to v0.10.0 it failed. Page loads white with the following error:

```shell
Fatal error: Maximum execution time of 30 seconds exceeded in C:\UserData\XXXXXXXX\Shaarli\vendor\arthurhoaro\web-thumbnailer\src\WebThumbnailer\Application\WebAccess\WebAccessCUrl.php on line 99
```

Did i do something wrong in the update process?

Regards

**Comment by ArthurHoaro** [comment]
Hi, it looks like thumbs retrieval falls in timeout.
Can you try to visit `<your shaarli URL>/?do=thumbs_update`?

**Comment by ArthurHoaro** [comment]
Closing due to lack of feedback. Please reopen if you have more information to provide.

**Comment by Trufax** [comment]
Sorry for the late feedback. "/?do=thumbs_update" did the trick. I took quite some time to update but now it is working perfectly.
