### ISSUE TITLE
HTML entered in tags is not escaped

### ISSUE THREAD

**Issue by CrazyCode44** [shaarli/Shaarli#1287]
Hi, I noticed this on the Shaarli demo:
HTML entered in tags is not escaped in the autocompletion menu/popup.

How to reproduce:
- Add a new link, tag it `<h1>ooooooo</h1>`, save
- Add a new link, select the Tags field, type `o`

What happens:
the autocompletion popup shows `ooooooo` formatted as H1

I think tag text should not affect the page dom/styles?

**Comment by ArthurHoaro** [comment]
This is a behaviour related to awesomplete.

I have updated an existing issue, but it hasn't move for a few years now.
LeaVerou/awesomplete#16932

**Comment by CrazyCode44** [comment]
ok thanks you
