### ISSUE TITLE
MarkDown table on the description causes Shaarli to become unresponsive

### ISSUE THREAD

**Issue by aliron19** [shaarli/Shaarli#1290]
Hello,

If you add a link which contains the MarkDown table [pasted here](https://pastebin.com/raw/TdC1vyQ4) (I'm using pastebin.com to show the raw code since github will interpret the MarkDown by itself) in the description, then Shaarli hangs up.

It looks that the problem is related to the last three words `temporary filesystem (tmpfs).`, because if you delete them everything works as expected.

I'm using Shaarli v0.10.3 with the MarkDown plugin enabled.

Thanks,
Aliron

**Comment by ArthurHoaro** [comment]
Hi, I just tried your raw data on the [demo](https://demo.shaarli.org/) (Login: demo; Password: demo) and I didn't have any issue.

>It looks that the problem is related to the last three words temporary filesystem (tmpfs).

How is your Shaarli hosted?

**Comment by aliron19** [comment]
You're right, on the demo works perfectly fine.

I'm self-hosting it on a Windows 10 Pro machine under XAMPP for Windows v5.6.28, which includes PHP Version 5.6.28 and Apache/2.4.23.

May it be caused by some old version of a library of my XAMPP installation? Could some of the other plugins which the demo runs (qrcode and archive.org) helping to avoid this issue?

**Comment by ArthurHoaro** [comment]
> Could some of the other plugins which the demo runs (qrcode and archive.org) helping to avoid this issue?
It seems rather unlikely.

Can you reproduce the issue without the markdown plugin enabled? Do you have any error in your web server log files?

**Comment by aliron19** [comment]
After upgrading Shaarli to realease 0.10.4 the issue is still there.

If I disable the markdown plugin then I can add the problematic description perfectly. However, once added, if I try to enable the plugin again then Shaarli hangs once more (just after clicking "Save" on the Plugin administration page).

**Comment by ArthurHoaro** [comment]
I have no idea what could cause this issue. Please check you logs to see if there is any error present.

> It looks that the problem is related to the last three words `temporary filesystem (tmpfs).`, because if you delete them everything works as expected.

Does the problem occur if you replace this string by another with the same length?

**Comment by aliron19** [comment]
Hello,

Answering your question, yes, another sting of the same lenght will produce the same result.

I've tried several other variations on Shaarli 0.10.4. These ones will block Shaarli: https://pastebin.com/raw/LpVxDdrE

On the other hand, these will be added without any problem: https://pastebin.com/raw/fTXf4Lq3

So it seems to be related to how the markdown plugin processes the last row of that table, but I've looked at the Apache but they don't show any errors. 

I'd like to debug the markdown plugin once I've sent the problematic description, but I have no experience debugging PHP. Could you please give me some tips about how could I do that?

Thank you.

**Comment by virtualtam** [comment]
Hi @aliron19,

Could this be due to the type of newline / carriage return used in the pasted data? It is possible that the library we use for Markdown rendering expects Unix end-of lines. In that case, we could check this in Shaarli and sanitize submitted data before it is saved.

**Comment by aliron19** [comment]
Hello @virtualtam,

I've just tried to add some of the problematic descriptions changing their newlines to Unix style, but the results are still the same. :disappointed: 

Anyway, thank you very much for you suggestion.

**Comment by ArthurHoaro** [comment]
You can try to isolate the problem. To make sure it comes from the markdown parser, you can try this:

   * create a directory
   * create a file `paste.txt` containing the content of your previous pastebin links
   * run `composer require erusev/parsedown` in this directory
   * execute the following PHP script

```php
<?php

require 'vendor/autoload.php';

$raw = file_get_contents('paste.txt');
$parser = new Parsedown();

echo $parser->setMarkupEscaped(true)
        ->setBreaksEnabled(true)
        ->text($raw);
```

**Comment by ArthurHoaro** [comment]
Closing due to lack of feedback. Feel free to reopen if there is any additional information to this issue.
