### ISSUE TITLE
Header covers content in printed pages

### ISSUE THREAD

**Issue by heimpogo** [shaarli/Shaarli#1291]
## Reproduction steps
1. Create an entry with a long description. It has to be long enough to cover at least two pages when printing.
2. Click the permalink of this item.
3. Open the print preview.

## Expected
The menu header should only appear on the first page.

## Actual
The menu header appears on all pages and there it covers a part of the actual description.

**Comment by elwinschmitz** [comment]
@heimpogo If you're looking for a quick&dirty fix, this will help:

You could add this to your `data/user.css`-stylesheet:
```css
@media print {
  #shaarli-menu {
    position: absolute;
  }
}
```
Or; if you know how to open your browsers Dev-tools(`Cmd/Ctrl+Shift+J` or `F12`):
Run this in the console, just before printing:
```js
document.getElementById('shaarli-menu').style.position='absolute';
```

A more durable fix would be to include print-specific styles in the default theme CSS. But I think you can go a lot further then only this fix then. You could hide all kind of 'interactive' elements for print then.
