### ISSUE TITLE
Daily link opens on yesterday instead of today

### ISSUE THREAD

**Issue by kalvn** [shaarli/Shaarli#1299]
I noticed recently that when I open the Daily page on my Shaarli instance, it opens on the previous day and not the current one. Then I can of course click on *Next day* but that's weird.

I'm pretty sure it's related to timezone settings or something like that but I'd like your feedback on this. You can see the issue directly on [my instance](https://links.kalvn.net/?do=daily).

**Comment by virtualtam** [comment]
Looks like a bug, I can reproduce this on a vanilla instance as well.

**Comment by ArthurHoaro** [comment]
I think it was done [on purpose](https://github.com/shaarli/Shaarli/blob/master/index.php#L395).

The idea was probably to display all links from yesterday, kinda like a newspaper. While it makes sense for the daily RSS feed, we can probably change this for the actual page.

**Comment by kalvn** [comment]
Thanks for investigations. I guess the word "Daily" kind of misled me. My brain was expecting the current "day". I'm fine with keeping things as-is if you think it makes sense, I'm just trying to think about something that would make clearer the fact that it's the expected behavior.

**Comment by nodiscc** [comment]
Hi yes, I think it is on purpose. You will want to see the links of the last completed day by default. But I have no strong feelings about this so feel free to change it... I admit it can be rather confusing at first. For daily pages for today and yesterday, it might be nice to prepend _Today/Yesterday_ to the date for clarity.

**Today - May 3, 2019**
**Yesterday - May 2, 2019**

**Comment by ArthurHoaro** [comment]
Good idea @nodiscc.

I'm in favor of changing this, as it would make more sense to display the latest links available. Also, if there is no links shaared "yesterday", the default page is displaying "today", which isn't really a coherent behaviour.
