### ISSUE TITLE
Get the headers meta keywords and description of link

### ISSUE THREAD

**Issue by jadjay** [shaarli/Shaarli#1302]
Hello, 

Would be very usefull to get automagically keywords and description
This could be an optin/optout (get headers / do not get headers)

Or this could be on separate fields (activate/deactivate) 

I see that it's a features that lot of users/admin demands 

regards,

**Comment by lmjst** [comment]
Hi,
I have the option "Automatically retrieve description for new bookmarks" ticked in my shaarli config (Shaarli 0.12.1) but no description is retrieved from web pages which have the meta tag 
`<meta name="description" content="xxx" />`
I've tried with the firefox plugin and the firefox widget without success.

thanks !
