### ISSUE TITLE
Improve tags attribution

### ISSUE THREAD

**Issue by kalvn** [shaarli/Shaarli#1310]
When adding a new link and attributing tags to it, I'm often wondering if I do not have already another different tag conveying the same idea. And I'm always bothered by the fact that I could create several different tags for the same purpose.

Could we imagine a way to define kind of synonyms for tags so that when we type that synonym in the tag field of the *add link* or *edit link* page, the corresponding existing tag appears and I can choose it instead.

I'm not sure that what I mean is clear, feel free to let me know if it isn't.

Another way would be to have a mapping engine that uses external source to display those propositions automatically based on the meaning of words. But I guess we're talking about much bigger effort in that case.

**Comment by ArthurHoaro** [comment]
I don't know. I understand the use case, but maintaining a synonyms database within Shaarli might be a bit overkill.

This feature request is related to the discussion ongoing on #1024.

**Comment by nodiscc** [comment]
Let's merge this with https://github.com/shaarli/Shaarli/issues/1024
