### ISSUE TITLE
Changing Colour of Top menubar and Shaarli Entry Titlebar

### ISSUE THREAD

**Issue by monkymind** [shaarli/Shaarli#1312]
At the moment I'm using a several Shaarli instances for different projects/lists etc. 

To keep visual track of them I modify the css and replace the green (#1b926c) Top Menubar and Link Titlebar with another colour.

Am I the only one using Shaarli like this? If NO... then it's surprising there is not an easy config option for this kind of simple theme choice during setup. (Or would this require a radical rewrite of Shaarli's code?) 
 
![Blue](https://user-images.githubusercontent.com/51474710/59090666-c3fc6d80-8950-11e9-8cd5-c50e69ac4793.png)

![shaarli4](https://user-images.githubusercontent.com/51474710/59091469-bfd14f80-8952-11e9-9a5c-e30542d27b8a.png)

![shaarli-638261](https://user-images.githubusercontent.com/51474710/59091433-aa5c2580-8952-11e9-90ab-0521023b4ae1.png)

**Comment by virtadpt** [comment]
You are not the only person using Shaarli for this.  I use one for my bookmarks, and a second as a card catalogue for my book collection, and I'm considering setting up a third to catalogue my DVDs and Blu-Rays.  I've pretty much given up on developing themes for Shaarli because I can't figure it out.

So... yes.  An easy way to change the colors of the menu bars would be really helpful.

**Comment by ArthurHoaro** [comment]
It's not possible to change the color in the default template core CSS because it's generated with SASS compilation, which requires node and yarn/npm.

However, I think that we can easily generate a CSS file which overrides the default one regarding the colors. I also think that this should be done using a plugin.

**Comment by monkymind** [comment]
> You are not the only person using Shaarli for this. I use one for my bookmarks, and a second as a card catalogue for my book collection, and I'm considering setting up a third to catalogue my DVDs and Blu-Rays. I've pretty much given up on developing themes for Shaarli because I can't figure it out.
> 
> So... yes. An easy way to change the colors of the menu bars would be really helpful.

I'm finding the versatility of Shaarli for managing project info pretty spectacular :-) 

![oriole](https://user-images.githubusercontent.com/51474710/59139397-2c416280-89d6-11e9-8fad-6d6f7acd5969.png)

And the default layout is great too - so for my needs complex themes aren't necessary. That's why I just use "find and replace" in an editor to change title/menu bars colours.

Give it a try! Just backup your shaarli.min.css first :-)

**Comment by monkymind** [comment]
> It's not possible to change the color in the default template core CSS because it's generated with SASS compilation, which requires node and yarn/npm.
> 
> However, I think that we can easily generate a CSS file which overrides the default one regarding the colors. I also think that this should be done using a plugin.

Ahh! That explains why with all the many features of Shaarli.... simple colour changes were not included.

A plugin would be brilliant.

**Comment by agentcobra** [comment]
Hi,
I can try to do it
Agentcobra

>

**Comment by raphaelbastide** [comment]
I encounter the same issue: If I want to override 16 times the color `#1b926c`. Maybe the default theme could use a CSS variable for the main colors, so a `user.css` can look like that:

```
:root{
  --main-color: red;
  --neutral-color: lightgray;
}
```

However we need to make sure a CSS variable can be easily reallocated.

**Comment by ArthurHoaro** [comment]
We use SASS variables before building the final CSS, but I didn't know that CSS supports native variables. And the browser support [doesn't seem bad](https://i.imgur.com/UgABnV5.png). I can try to play with it seeing what can be done.

@agentcobra Did you start to work on this?
