### ISSUE TITLE
Links per page configuration ignored

### ISSUE THREAD

**Issue by techexo** [shaarli/Shaarli#1314]
Hi everyone,

I am trying to change the number of shaares showed per page on my instance, but it seems that the `links_per_page` option in `data/config.json.php` is completely ignored.
The documentation states nonetheless:
> links_per_page: Number of shaares displayed per page. 

 I tried deleting the cache on the server and reloading the page without cache on my browser with no effect. Whatever the value, only 20 shaares are displayed per page.

I am running v0.10.4 with Shaarli-Material template.

Is this a regression, an abandoned feature, or a bug? Please tell if I can further help you for solving this issue. Thanks

**Comment by techexo** [comment]
Note: I just saw that the links per page option was hidden on the shaarli instance in the filter popup... So my problem is solved, but maybe some indication should be made in the doc telling that this option is deprecated in the backend configuration?

**Comment by ArthurHoaro** [comment]
Hi,

You're right, it looks like this setting got lost at some point. It could be easily re-added to work along the front side setting.

**Comment by ArthurHoaro** [comment]
Oh no my bad. It's still working.

However, since the value is stored in the session, it's overridden by these until the the session is over. You can check with private browsing.

![](https://i.imgur.com/HVggP3r.png)

**Comment by techexo** [comment]
Oh OK, great that it was just that. I totally forgot about the session 🙏 Thanks!
