### ISSUE TITLE
Deleting an entry from a search result resets the search list

### ISSUE THREAD

**Issue by gerroon** [shaarli/Shaarli#1315]
- make a keyword search

- delete an entry from the search result

- the list view is back to non search state

I am using Shaarli 0.10.3 on Debian Buster under Apache

**Comment by ArthurHoaro** [comment]
I just tried on the demo instance and I could not reproduce your issue. Do you have the same issue on the demo?

**Comment by gerroon** [comment]
The demo page seems to be borked. Do you know a public one that I can try?

```
phpVirtualBox admin password recovery.

Rename recovery.php-disabled to recovery.php, navigate to it in your web
browser and follow the instructions presented.
```

**Comment by ArthurHoaro** [comment]
That just random content. You can try here : https://demo.shaarli.org/?searchterm=test

**Comment by gerroon** [comment]
Yeah I can repeat it with that demo too.

I made a search for "secret", deleted the resulting one using the "thrash" icon, it reset the page.

**Comment by ArthurHoaro** [comment]
Do you have any extension altering the referer? Can you try with another browser without custom settings, or with Firefox without addons using `about:profiles`?

**Comment by gerroon** [comment]
Interesting, I tried this with Chromium and it does not do that. I will see what is up with Firefox.

**Comment by ArthurHoaro** [comment]
Closing as it's not a bug in Shaarli.
