### ISSUE TITLE
Duplicate creation

### ISSUE THREAD

**Issue by mro** [shaarli/Shaarli#1316]
https://demo.shaarli.org/?do=login&post=https%3A%2F%2Fshaarli.readthedocs.io%2F once upon a time used to pick up the existing entry for editing rather than creating a duplicate as it does now.

Please repair, thx.

**Comment by mro** [comment]
maybe related to https://github.com/shaarli/Shaarli/issues/1303#issuecomment-493525745

**Comment by mro** [comment]
sorry, I mean https://demo.shaarli.org/?post=https%3A%2F%2Fshaarli.readthedocs.io%2F – not the above login link (which will yield the same result but isn't the relevant starting point as e.g. used from the bookmarklet).

**Comment by nodiscc** [comment]
@mro clicking many times on any of this links provides the expected result for me (first time a new link is created, following attempts show the edit dialog for the previously posted link).

Do you have different results?

**Comment by mro** [comment]
@nodiscc apologies for the confusion, it's the trailing slash added by firefox when right-clicking + copy to clipboard the target link listed in shaarli. It then isn't recognised as already existing and doesn't pre-fill the form.

Fair enough, with and without trailing slash is in fact different URLs. So no bug here, thx for bearing with me.
