### ISSUE TITLE
Editing links results in 403 error in certain situations

### ISSUE THREAD

**Issue by jmfcodes** [shaarli/Shaarli#1318]
I am running 0.10.4 on a domain with Namecheap hosting. Everything works great (I love it so much!), but there might be a bug with editing:

- When editing a link by clicking "edit" directly from the home page, "Apply Changes" returns a 403 error. 
- I do NOT get this error when I click the permalink for the entry, and then click edit from there.

I don't know if this is similar to #1300 (but the fix didn't work for me).

**Comment by ArthurHoaro** [comment]
Hum, besides the REST API, Shaarli isn't supposed to throw 403 errors. So my guess is that it comes from your web server for some reason. What does the error page look like?

Can you try in a browser without any extension or custom settings an check if you get the same result?

**Comment by nodiscc** [comment]
Webserver access/error logs at the time of the error would be helpful (apparently Namechap allows you to view the logs [this way](https://www.namecheap.com/support/knowledgebase/article.aspx/9563/29/how-can-i-check-my-website-access-logs))

**Comment by ArthurHoaro** [comment]
Closing due to lack of feedback. You can provide additional information if you still encounter your issue.
