### ISSUE TITLE
Responsive issue with Delete button in default template

### ISSUE THREAD

**Issue by ArthurHoaro** [shaarli/Shaarli#1329]
![](https://i.imgur.com/pdiThBD.png)

**Comment by rajathans** [comment]
How to set up locally? I want to fix this

**Comment by ArthurHoaro** [comment]
To install the project, refer to the documentation : https://shaarli.readthedocs.io/en/master/Download-and-Installation/#development-version-mainline

Then you can run a local PHP server : `php -S 0.0.0.0:8080`
