### ISSUE TITLE
Dead link on "Installation Guide" page on GitHub

### ISSUE THREAD

**Issue by arcanemachine** [shaarli/Shaarli#1330]
On the [Installation Guide](https://github.com/shaarli/Shaarli/blob/master/doc/md/Download-and-Installation.md), the second sentence says:

"Also, please make sure your server is properly [configured](https://github.com/shaarli/Shaarli/blob/master/doc/md/Server-configuration)."  (Links to https://github.com/shaarli/Shaarli/blob/master/doc/md/Server-configuration)

The link to the configuration guide is dead and (if I'm not mistaken) should link to this URL instead:

https://github.com/shaarli/Shaarli/blob/master/doc/md/Server-configuration.md

**Comment by nodiscc** [comment]
You are right.

It wasn't noticed because the recommended way to browse the docs is through https://shaarli.readthedocs.io/en/master/Download-and-Installation/ and it works there. I will fix it now.
