### ISSUE TITLE
Consider adding support of basic HTTP authentication scheme

### ISSUE THREAD

**Issue by tevino** [shaarli/Shaarli#1338]
## Use case

Access RSS feed by `https://user:password@shaarli.example.com/?do=atom` in feed reader.

Or is there another way to do that?

## Related

- https://github.com/shaarli/Shaarli/issues/569
- https://github.com/shaarli/Shaarli/issues/802
- https://github.com/shaarli/Shaarli/issues/1189

**Comment by nodiscc** [comment]
I don't think there is a way currently to:

 - Have Shaarli protected by it's authentication mechanism AND
 - Have the RSS feed _only_ protected by HTTP basic auth

**Comment by tevino** [comment]
@nodiscc Is it possible to make HTTP basic as a part of the current authentication mechanism?

Thus one may log in to Shaarli(including RSS feed) with either of those two mechanisms.

**Comment by nodiscc** [comment]
Moved to https://github.com/shaarli/Shaarli/issues/802
