### ISSUE TITLE
Add a manual configuration setting for base URL

### ISSUE THREAD

**Issue by foudfou** [shaarli/Shaarli#1339]
Dear all, URLs referring to my instance are partially broken. Ex:
- `<link rel="alternate" type="application/atom+xml" href="https://my.shaarli.me:8443/links/?do=atom" title="ATOM Feed" />` on the index
- all link in the `https://my.shaarli.me:8443/links/?do=atom` page

...as they're exposing the port of my internal server. I have the following setup:
```haproxy :443 <-https->  :8443 nginx <-> :9001 php-fpm```, haproxy on localhost facing the outside world, nginx on localhost, php-fpm in a container.

The issue is that the links rendered by shaarli/php from the env variables provided by nginx are wrong: I'd expect  `https://my.shaarli.me/links/?do=atom` rather than `https://my.shaarli.me:8443/links/?do=atom`.

I mitigated the issue by configuring nginx to override the `SERVER_PORT` variable passed to fastcgi scripts to 443.

Still I wonder if it's a good idea to rely on the PHP `$_SERVER` Array to build links, because they might hold valid values of the downstream server which wouldn't be helpful for clients. Wouldn't it be more straight-forward to either use relative links everywhere, as already done for links in the navbar (ex: `href="?do=tagcloud"`), or having a general config setting like `base_url` (`https://my.shaarli.me/links/` in my case) ?

Thank you anyway for the great work!

**Comment by ArthurHoaro** [comment]
Hi,

You can use `X-Forwarded-Port` header to specify the port in your reverse proxy. However looking at [the docs](https://shaarli.readthedocs.io/en/master/docker/reverse-proxy-configuration/) it looks like it's not documented.

> Wouldn't it be more straight-forward to either use relative links everywhere

Some links requires a full link, such as RSS feeds as in your example, because most RSS clients can't work with relatives links.

**Comment by foudfou** [comment]
Hey thx for the fast response !! I *think* I can't use `X-Forwarded-Port` in my setup because the TLS connection really happens between the client and the nginx server. Haproxy has no opportunity to set additional headers. Setting `X-Forwarded-Port` is usually the job of a proxy speaking plain http with the downstream server. In practice, haproxy uses the PROXY protocol in this case, which passes info in the beginning of the TCP connection in the form `PROXY TCP4 192.168.0.225 192.168.0.10 39070 443`. That info is then interpreted by nginx to some extend (I couldn't manage to retrieve the `443` value).

But if we take a step back, because there might be infinite possibilities of connections and layers between the client and shaarli, I wonder if shaarli should rely on info that is passed by the last HTTP server before php-fpm. Because, in practice, this is going to be quite some tricky work to pass the original port all along through all the proxy chain.

**Comment by ArthurHoaro** [comment]
Oh I missed in you first message that you found *a* solution by forcing the port from nginx. I don't know HAProxy but I'll take your word for it.

> But if we take a step back, because there might be infinite possibilities of connections and layers between the client and shaarli, I wonder if shaarli should rely on info that is passed by the last HTTP server before php-fpm. Because, in practice, this is going to be quite some tricky work to pass the original port all along through all the proxy chain.

I agree, Shaarli's automagic URL retrieval works in basic configurations, and `X-Forwarded-*` headers work for a basic single reverse proxy default config, but can become impossible with a complex infrastructure.

We have no choice but to rely on what info the web server is providing, or on user input. I like the fact that everything is working for most cases with minimal configuration. But I think that adding a manual configuration for base URL as you mentioned could be a good addition to avoid toying with reverse proxies configurations if needed.

I can work on this.
