### ISSUE TITLE
Suggestion: LDAP support

### ISSUE THREAD

**Issue by gem76** [shaarli/Shaarli#1343]
Is it possible to integrate LDAP-Support as UserAuthentification for Shaarli?

For the original shaarli there was a PR mentioned (https://github.com/sebsauvage/Shaarli/pull/212), but I guess it died in the process.

**Comment by pipoprods** [comment]
I needed this as well, so I've implemented it.

I'll clean my code, add the documentation & config parts and submit a PR.  Probaby today.

**Comment by helmut72** [comment]
Are there any further settings possible? My Samba LDAP need a bind user.

**Comment by ArthurHoaro** [comment]
I'm not super familiar with LDAP protocol but we can accept PR with improvements.

**Comment by helmut72** [comment]
Will use the local user. Had some wrong expectations. Shaarli is still single user, even with LDAP.

**Comment by Pyrosfr** [comment]
Any solution to connect to ldaps server ?

**Comment by ArthurHoaro** [comment]
Yes you can but for a single user as helmut mentionned: https://shaarli.readthedocs.io/en/master/Shaarli-configuration/#ldap

**Comment by helmut72** [comment]
First I wanted to add bind-auth. But Shaarli doesn't become a multi-user system with LDAP and it's not on the roadmap. Now I use with the local user.

**Comment by nodiscc** [comment]
> ldaps server

LDAPS as in LDAP-over-TLS? @Pyrosfr It should work (I have not checked). If it doesn't please open a separate issue
