### ISSUE TITLE
Bookmark import messes up sorting - possibly due to identical timestamps

### ISSUE THREAD

**Issue by Braintoe** [shaarli/Shaarli#1348]
First of all a big thank you to the maintainers of Shaarli! I searched for a replacement of my online bookmark service which recently had a downtime of more than two weeks - and solved this 
by installing Shaarli on the Raspi I use as adblocker with pi.hole.

Now to the issue: Shaarli 0.10.4 has a rather creative way of sorting imported (in my case about 1000) bookmarks, with the order changing randomly on every reload. My guess (please forgive me, apart from some rusty HTML/CSS knowledge I am not much of a programmer) is that this is caused by the time stamp of every imported bookmark being identical. My suggestion would be to change the import algorithm to either read existing timestamps from the import file and/or to add one second whenever the timestamp of an imported entry already exists in the database.

**Comment by ArthurHoaro** [comment]
Thanks for the kind words.

Shaares order is supposed be saved on write, so even if the timestamp is inconsistent, it shouldn't change on every reload. I'll run a few tests.

> read existing timestamps from the import file

It's supposed to be the case, so either the timestamps couldn't be read properly, or they're missing. Can you provide a sample with 2 links of your import file

> add one second whenever the timestamp of an imported entry

That's a good suggestion.

> already exists in the database

I'm not sure about that part. If your entry already exists in the database, it will either be skipped or overriden depending on  what you asked during the import.

**Comment by Braintoe** [comment]
> It's supposed to be the case, so either the timestamps couldn't be read properly, or they're missing. Can you provide a sample with 2 links of your import file

Here you are:

`<DT><A HREF="https://www.bid-o-matic.org/hp/plugin.php" ADD_DATE="1564867991" LAST_MODIFIED="1564867991" ICON_URI="https://www.bid-o-matic.org/favicon.ico">Biet-O-Matic - der Bietautomat</A>
<DT><A HREF="https://www.raspberrypi.org/learning/software-guide/update-sd-card/" ADD_DATE="1564867991" LAST_MODIFIED="1564867991" ICON_URI="https://www.raspberrypi.org/favicon.ico">Raspbian/Noobs Updating and upgrading</A>`
... aaand that solves this part of the question: the export file does not contain the creation time but the export time which is the same for every entry. Great -.-

> > add one second whenever the timestamp of an imported entry already exists in the database
> I'm not sure about that part. If your entry already exists in the database, it will either be skipped or overriden depending on what you asked during the import.

Sorry, it seems my intention was unclear (I am no native english speaker) - the idea was to check the database during import if _any_ other bookmark (not the same, identical ones are covered as you pointed out) with the same timestamp exists - and if it does, add one second to the imported one to make the timestamp different and keep sorting functional.

**Comment by ArthurHoaro** [comment]
I have submitted a solution in #1350 to fix the order inconsistency (sort by ID). 
Note that during the import, the bookmark are created from the beginning of your file to the end, meaning the first entries will appear as the last on your Shaarli. Depending on how the export was done, and what you need, you might need to alter your import file.

**Comment by ArthurHoaro** [comment]
Also regarding this:

> Shaares order is supposed be saved on write, so even if the timestamp is inconsistent, it shouldn't change on every reload. I'll run a few tests.

I did run a few tests, and since the order is inconsistent, Shaarli is always grabbing new thumbnails (at least for a while), thus writing the datastore and changing the order.

**Comment by Braintoe** [comment]
> I did run a few tests, and since the order is inconsistent, Shaarli is always grabbing new thumbnails (at least for a while), thus writing the datastore and changing the order.

Just for the sake of completeness: please note that the order of the affected bookmarks changes whenever you add, edit or delete a bookmark though (just tested this on my database, I am unsure if you can observe such behaviour if you only have a few of those bookmarks).

Anyway, I guess with request #1350 handling this issue I guess this one here can be closed. Thanks a lot for your help and the submit!

Now on to repairing the timestamps of that import file of mine...
