### ISSUE TITLE
Thumbnails are not loading in "Picture wall"

### ISSUE THREAD

**Issue by jeekajoo** [shaarli/Shaarli#1357]
Hi,

Using Shaarli 0.11.1, thumbnails are not loading in "Picture wall".

Demo : https://jeekajoo.eu/links/?do=picwall

![](https://i.imgur.com/M2ukONR.png)

However, pictures that are supposed to load are available :
* https://jeekajoo.eu/links/cache/thumb/14dd5266c70789bdc806364df4586335/02fdbb443e6129b4b4137de6e332693f1a530744125901.jpg
* https://jeekajoo.eu/links/cache/thumb/d03cf4680ca081157edb0d9c5f8b6f9f/c4f437a926f2a4369dfe88a2ee2a58b54a708567125901.jpg

It looks like "b-lazy" class is very lazy ;)

Thanks
J.

**Comment by ArthurHoaro** [comment]
Hi, yes it stopped working at some point I'm not sure why. There is a fix that has been merged but not released yet in #1354. 

You can work this around by adding in your `user.css`:

```css
.b-lazy {
  min-width: 1px;
  min-height: 1px;
}
```
