### ISSUE TITLE
Clean ?utm_content, ?xtor and ?fb parameters from URL

### ISSUE THREAD

**Issue by e2jk** [shaarli/Shaarli#136]
Split out from #133: When removing the tracking parameters (e.g. `?utm_source=[...]`), the code currently removes everything that comes after it. Theoretically there could be other parameters in the URL that are relevant.

Question: should we only remove that parameter and it's value, leaving what comes after it if anything?

It is most likely that tracking parameters are *appended* to the URL, so what is the likelihood that there are useful parameters after that? After all, maybe that removing all that comes after the first recognized tracking URL is a valid approach after all? Please discuss.

**Comment by nodiscc** [comment]
For what it's worth, I never had a problem with Shaarli removing _everything_ after the `?utm..` crap. But as we're adding new URL params soon, let's wait and see.

**Comment by alexisju** [comment]
I still have some dirty url with latest version of Shaarli. You can test these url :

http://example.com/titre-article/?fb=kr
http://example.com/titre-article_4544726_4222996.html#R4TsyA3xDemTTXI5.99
http://example.com/titre-article-62225?xtor=EPR-511537822
http://example.com/titre-article#utm_source=wri&utm_content=article
http://example.com/?utm_source=iceranking&amp%253butm_medium=link
http://example.com/titre-article_1115727?utm_source=Twitter&utm_campaign=Echobox&utm_medium=Social&link_time=14444459

**Comment by nodiscc** [comment]
>http://example.com/titre-article/?fb=kr

>http://example.com/titre-article_1115727?utm_source=Twitter&utm_campaign=Echobox&utm_medium=Social&link_time=14444459

@alexisju Where is this from? Can you send an actual URL with these params (`?fb,  &link_time`) We need to know what purpose these parameters serve, to know if we should consider them as "annoying"/useless. We don't want to break services that really depend on them to work properly. I think `?xtor

>http://example.com/titre-article#utm_source=wri&utm_content=article
>http://example.com/titre-article-62225?xtor=EPR-511537822

Yes. `?utm_content` and ?xtor` can be safely removed. If you can edit https://github.com/shaarli/Shaarli/blob/master/index.php#L1649 and send a Pull Request it will be done faster.

`#utm_source` should _not_ be removed, since it's an anchor, not an url parameter. We won't clean anchors, this could break pages. Same for `#R4TsyA3xDemTTXI5.99` in http://example.com/titre-article_4544726_4222996.html#R4TsyA3xDemTTXI5.99

>http://example.com/?utm_source=iceranking&amp%253butm_medium=link

is cleaned correctly IMHO? `?utm_source` is removed.

**Comment by alexisju** [comment]
"Real" situation I met :
http://www.dailydot.com/opinion/edward-snowden-mass-surveillance-nsa-america/?fb=kr
http://www.lemonde.fr/pixels/article/2015/03/18/disparition-mysterieuse-d-evolution-le-plus-grand-supermarche-de-la-drogue-en-ligne_4595726_4408996.html#R4TsyA3xDemTTXI5.99
http://www.liberation.fr/societe/2015/03/06/treize-raisons-de-lacher-le-steak-barbare_1215727?utm_source=Twitter&utm_campaign=Echobox&utm_medium=Social&link_time=1426868359 

I tried to find other similar situations with google and i found:
http://www.leroymerlin.fr/idees-conseils/des-garages-bien-optimises-1298476535?xtor=EPR-511537822
http://formation.ranking-metrics.fr/referencement-naturel#utm_source=wri&utm_content=dossier-parametres-url-gwt
http://www.votresite.ca/?utm_source=iceranking&amp%253butm_medium=link

**Comment by nodiscc** [comment]
Thanks for your research.

Just to be clear, we will clean `?utm_content`, `?xtor` and `?fb` parameters but _not_ `#utm_source` or `&amp%253butm_medium=link`. These are website-specific bugs:

 * The first link is supposed to have a `?utm_source` URL parameter, but it was inserted as an anchor. fail. Note that it's a SEO site...
 * The last one results from a double-triple-fail at URL-encoding (http://www.w3schools.com/tags/ref_urlencode.asp). Encoding the `&` param delimiter as `&amp`, fail. [Encoding `%3b` as `%253b`](https://stackoverflow.com/questions/4858108/url-to-uri-encoding-changes-a-3d-to-253d), fail.

Well I don't know what `#R4TsyA3xDemTTXI5.99` does, but it's an anchor, so we shouldn't remove it. Even if we decided to "clean" anchors, it has no easily recognizable pattern at the moment. I see 16 chars, a dot, 2 chars. It could help if we could find other sites that use this, or if we knew what it's used for. If you know the original page where you found that link, it could be interesting too (character substitution? modified ROT13?...)

**Comment by nodiscc** [comment]
I don't have much time these days, patches from the community welcome (it's easy, add these params to https://github.com/shaarli/Shaarli/blob/master/index.php#L1639 , `$annoyingpatterns` array)
