### ISSUE TITLE
API handling of newlines

### ISSUE THREAD

**Issue by toolleeo** [shaarli/Shaarli#1360]
How can post a link from the command line that has a description that should contain a newline when displayed in the shaarli online instance?

When trying something like (see the newlines in the description)

```
shaarli post-link --url 'http://test.url/' --title 'Test' --description 'One\nword\nper\nline.'
```

Using the `shaarli` script (v 0.3.0) returns

```
{
    "created": "2019-08-04T09:56:11+02:00",
    "description": "One\\nword\\nper\\nline.",
    "id": 2786,
    "private": false,
    "shorturl": "r-KS6g",
    "tags": [],
    "title": "Test",
    "updated": "",
    "url": "http://test.url/"
}
```

The newlines are escaped, and the text in the online shaarli instance contains the '\n' text verbatim instead of the actual newline.

Using '\r\n' instead of '\n' does not work either.

Not sure whether this is a API issue or a `shaarli` script issue...

**Comment by ArthurHoaro** [comment]
After a few tests, you can use actual line breaks, or this syntax: `--description $'One\nword\nper\nline.'`

See [this answer](https://stackoverflow.com/a/5295906/1484919) for reference.

**Comment by toolleeo** [comment]
Confirmed. It works. Thank you for the neat fix.

My 2 cents to improve the usability of shaarli client on this aspect:

- provide an example in the documentation with this "trick" for handling the newlines
- if something will be added to the docs, make it clear to use the single quotes; double quotes, i.e., `--description $"One\nword\nper\nline."`, do not work
