### ISSUE TITLE
Undefined thumbnail index when creating a note

### ISSUE THREAD

**Issue by ruaideh** [shaarli/Shaarli#1362]
On version 0.11.1, creating a note displays under the title bar a warning for undefined index :
Notice: Undefined index: thumbnail in /[shaarli directory]/index.php on line 468.

I replaced on line 468 <code>if ($link['thumbnail'])</code> by <code>if (isset($link['thumbnail']) && $link['thumbnail'] !== false)</code> and changed it too on /[shaarli directory]/temp/includes.[list of numbers].rtpl.php , line 32.
It is now working correctly but since the lattest file is generated, I do not know where to change the source file.

Hope it helps!

**Comment by ArthurHoaro** [comment]
This issue has been fixed by #1346 

However the one from `includes.html` template is not. Thanks for the report.

**Comment by ArthurHoaro** [comment]
Also note that you should not display PHP warnings/errors in production.

**Comment by ruaideh** [comment]
You welcome and thanks for the advice.
