### ISSUE TITLE
Thumbnails Do Not Show on Default Page (/?) Or Picture Wall

### ISSUE THREAD

**Issue by daprofessa19** [shaarli/Shaarli#1369]
Hi,

I'm using Chrome browser version 77, and I'm having a problem with thumbnails loading. I have synchronized thumbnails, but they do not display on the default page (/?) or on the picture wall.
They do, however, load on the "Daily" page when browsing dates.

This seems somewhat similar to #1357 , but I am already using the commit referenced there.

Thanks

**Comment by ArthurHoaro** [comment]
It looks like it's working fine for me with Chromium 78.

Can you check if you can reproduce your issue on the demo server: https://demo.shaarli.org

**Comment by daprofessa19** [comment]
Also, in the Firefox browser, thumbnails do show on default page (/?) and "Daily" page, but they do not display on the Picture Wall.

I also see a "Call Stack" table at the top of the page when loading Shaarli when not logged in. I'm not sure if this is normal.

**Comment by ArthurHoaro** [comment]
You did not answer my question.

> I also see a "Call Stack" table at the top of the page when loading Shaarli when not logged in. I'm not sure if this is normal.

It looks like you have a PHP error. Can you check your web server logs?

**Comment by mrb-x** [comment]
Hello,
I just update to 0.11.1 this morning and I can't see the "Picture Wall" anymore. Like @daprofessa19 the user.css (issue #1357) in data folder doesn't resolve my problem  .

I resolved my problem by adding the #1357 hack directly in the shaarli.min.css. For unkown reason,access to my user.css was denied by server (in Apache 2.4 log on synology DSM). Still digging...

My Shaarli is installed on Synology NAS, with PHP 7.2 and Apache 2.4

If you know how to properly resolve this issue, I be happy to kown.

Thanks.

**Comment by ArthurHoaro** [comment]
We use a `.htaccess` to restrict access to the `data` folder, but allow `user.css`: https://github.com/shaarli/Shaarli/tree/master/data

Maybe it's not working properly? Can you try to temporarily rename this file and see if it works?

**Comment by mrb-x** [comment]
Thanks for your response.
You're right, when I remove the .htaccess every things work fine.

**Comment by mrb-x** [comment]
If I remove the last three lines the thumbnail appear :

<IfModule !version_module>
    Require all denied
</IfModule>

**Comment by daprofessa19** [comment]
What exactly is user.css? My data folder does not have this file. Also I tried commenting out the last 3 lines, as mentioned above, but this had no effect.

I did some tests, and I was able to load the image, but I'm not sure what is the underlying issue here.
When I manually change the element from <img data-src="%thumbnail_path%"> TO <img src="%thumbnail_path%> AND I change class="b-lazy" TO class="b-lazy b-loaded" the thumbnail appears.

Otherwise, when the page loads, I get img src(unknown) and the image does not load, except for on the Daily page.

I was not able to replicate my issue on the demo server.

I also don't know why two different browsers give different results.

**Comment by mrb-x** [comment]
They was no user.css in my data folder, so I created it with the code from @ArthurHoaro on #1357 below :
`.b-lazy {
  min-width: 1px;
  min-height: 1px;
}`
With no success, until I suppress the last three line of my .htaccess in data folder (or rename .htaccess).

I suppose the Apache server can't find the version_module and folds back on the default behavior and deny the access to user.css

Be carreful, it's not the secure way to solve the problem, when removing the lines we probably allow too much right to visitors.

**Comment by ArthurHoaro** [comment]
> If I remove the last three lines the thumbnail appear

You're right, it looks like you don't have `version_module` in your Apache installation. However you should not remove those lines entirely because your allowing access to your datastore and configuration file.

You can try to add this section within the `<IfModule !version_module>` section

```
<Files "user.css">
  Require all granted
</Files>
```

Feel free to open a pull request if it works.

> What exactly is user.css?

It's a custom CSS file that you can create to override Shaarli's CSS. Take a look [at the documentation](https://shaarli.readthedocs.io/en/master/Theming/).

The work around from #1357 should work if your `user.css` is accessible (lazy loading doesn't seem to work properly anymore if the image block is 0*0px). Just to make sure that your issue is the same, you can also try to add these lines in Shaarli CSS file.

**Comment by mrb-x** [comment]
Hello,
I do exactly what you say by removing IfModule, and everything seems to work fine.

My first try with workaround # 1357 did not work because I changed shaarli.css and my browser uses shaarli.min.css. After editing the reduced version, the thumbnails appeared.

Thank you.

**Comment by daprofessa19** [comment]
This issue is resolved for me as well. I didn't think that I had to add that code to user.css since I was already using the latest sharli.css , which has those lines in it.
