### ISSUE TITLE
Metadata extraction

### ISSUE THREAD

**Issue by da2x** [shaarli/Shaarli#1375]
https://github.com/shaarli/Shaarli/blob/4b15c49198ef4be57b2ccb3d9033035a16d3b20c/application/bookmark/LinkUtils.php#L175-L179

This code incorrectly assumes that the itemprop and property attributes only contain one value. Their value is a whitespace-separated list of values (like the rel and class attributes).

The following example is valid HTML but unsupported:

    <meta property="some:thing og:description" content="Brief description.">

This is also valid and also unsupported:

    <meta property="og:description" name="description" content="Brief description.">

**Comment by nodiscc** [comment]
@da2x ping, can you report real-world examples of these `meta` tags?

**Comment by da2x** [comment]
163 examples:
https://publicwww.com/websites/%22dc%3Adescription+og%3Adescription%22/

Plus number 5 here:
https://publicwww.com/websites/%22og%3Adescription+twitter%3Adescription%22/
