### ISSUE TITLE
404 in Theming documentation

### ISSUE THREAD

**Issue by mehkera** [shaarli/Shaarli#1376]
Hello all,
In this page https://shaarli.readthedocs.io/en/master/Theming/ of the link : https://shaarli.readthedocs.io/en/master/Download%20CSS%20styles%20from%20an%20OPML%20list
go to 404 page.

**Comment by ArthurHoaro** [comment]
Hum, there is also a link in the footer of [this page](https://shaarli.readthedocs.io/en/master/guides/various-hacks/). Looking for a miror of the old wiki I found this : https://ziirish.info/bm/doc/Download-CSS-styles-from-an-OPML-list.html

Maybe we can remove this entirely? ping @nodiscc

**Comment by nodiscc** [comment]
Fixed in https://github.com/shaarli/Shaarli/commit/af8a03d1ab25e00354c40e4637366b954a2c480d and https://github.com/shaarli/Shaarli/commit/eb0a0f77cc42d5c1c4a331720dbe1710ef8eb565, thank you.
