### ISSUE TITLE
Inline HTML in description doesn't render anymore

### ISSUE THREAD

**Issue by pascollin** [shaarli/Shaarli#1377]
Switching to the last Shaarli's version, v0.11.1, I've got an issue with markdown plugin.

Markdown plugin should allow inline HTML, as described in the documentation : https://daringfireball.net/projects/markdown/syntax#html

But it doesn't work anymore. Demo on Shaarli demo website : https://demo.shaarli.org/?searchtags=issue
![shaarli markdown issue](https://user-images.githubusercontent.com/13776694/68390597-eac00980-0165-11ea-9983-5232ca86b73c.png)

**Comment by ArthurHoaro** [comment]
If you don't share your Shaarli instance, I suggest that you turn the setting `security.markdown_escape` to `false` in your `config.json.php` file. This should fix your issue.

**Comment by pascollin** [comment]
Hi,
Using version v0.12.1 - Markdown rendering is now integrated into Shaarli core (from v0.12). 
security-markdown_escape setting is missing into config.json.php.
I tried to add this setting manually, in the security section, but it seems to be ignored.
Inline HTML is no more rendered (but escaped).
Thanks for help

**Comment by ArthurHoaro** [comment]
Hi, it shouldn't be ignored ([L46](https://github.com/shaarli/Shaarli/blob/master/application/formatter/BookmarkMarkdownFormatter.php#L46) and [L67](https://github.com/shaarli/Shaarli/blob/master/application/formatter/BookmarkMarkdownFormatter.php#L67)). I'll take a look when I have some time.

**Comment by ArthurHoaro** [comment]
I just tried it, and with the following setting HTML is properly rendered and not escaped:

```
{
   ...,
   "security": {
      ...,
      "markdown_escape": false,
      ...
   }
   ...
}
```

Are you sure you didn't make a typo while manually adding the setting?

**Comment by pascollin** [comment]
Hi, 

Thanks for you help.

I don't think i missed the correct typo. Here is an extract from config.json.php in the data directory.

```
<?php /*{
    ... ,
    "security": {
        "markdown_escape": false,
        "ban_after": 4,
        "ban_duration": 1800,
        "session_protection_disabled": false,
        "open_shaarli": false,
        "allowed_protocols": [
            "ftp",
            "ftps",
            "magnet"
        ]
    },
    ...
}
```
It seems correct, but shaarli still escapes HTML content.

**Comment by ArthurHoaro** [comment]
It looks fine. I'm sorry but I can't reproduce your issue.
So just to sum it up and make sure that ẅe understand each other properly:

  - with Shaarli v0.12.1
  - with the setting `"markdown_escape": false,` 
  - in the configure page of Shaarli the formatter is set to `Markdown`
  - a shaare with the description `<strong>test</strong>`

Is displayed still `<strong>test</strong>` in the link list of your instance. That's correct?

**Comment by pascollin** [comment]
You're right ! Formatter was set to "Default" instead of "Markdown". 
Many thanks !

**Comment by pascollin** [comment]
Resolved
