### ISSUE TITLE
Login/session issues on Azure

### ISSUE THREAD

**Issue by Trufax** [shaarli/Shaarli#1378]
Hi all,

`shaarli version 0.11.1`
`PHP Version 7.2`

i setup shaarli on Microsoft Azure (App Service Plan an WebAPP) i did the initial setup on Chrome and it works like it should. However i can only login with chrome or firefox. Edge IE or Safari (iOS) fail with "wrong username and password". I deleted the config and tried a setup with Edge or Safari. But both send me the following error: session.save_path 

`Sessions do not seem to work correctly on your server.
Make sure the variable "session.save_path" is set correctly in your PHP config, and that you have write access to it.
It currently points to D:\local\Temp.`

This messages confuses me since if i open it with chrome or Firefox i can do the initial setup as expected. So is this really a session issue since its working in chrome in Firefox?

**Comment by ArthurHoaro** [comment]
It is a session issue, but probably not on server side (or not only), as it worked with other browser. Can you login with Edge on the demo instance?

**Comment by Trufax** [comment]
Yes the demo page works. I can login there.

**Comment by ArthurHoaro** [comment]
I don't have access to Edge or Safari, but you can try to inspect your browser cookies while browsing your Shaarli instance and check if your session cookie is working properly.

You can compare its behavior with Firefox. E.g.:

![](http://i.imgur.com/d8oH9TG.png)

**Comment by ArthurHoaro** [comment]
I'm closing old issues tagged `support` which are likely outdated. If you feel like this should stay open, please say so.
