### ISSUE TITLE
How safe is Shaarli dev in production server?

### ISSUE THREAD

**Issue by nicolasdanelon** [shaarli/Shaarli#138]
Hi, I just want to know if can I use the live version or I need to downgrade to 0.0.43beta

**Comment by nodiscc** [comment]
No security vulnerabilities or data corruption/loss issues are known in the current `master` (https://github.com/shaarli/Shaarli/tree/7572cfbe9620b13569ee47337f7015bcad119332). Though you should always do automated, periodic, encrypted, offline backups of your `data/` directory (like any other user-generated data/config).
