### ISSUE TITLE
CSS is rejected by browser

### ISSUE THREAD

**Issue by The-Inamati** [shaarli/Shaarli#1380]
I installed the app in my webserver and I get the error below in all browsers.

`Refused to apply style from 'https://shaarli.domain.tld/tpl/default/css/shaarli.min.css?v=3688d988ea87a141f16453bd3370ef6927c07d4822192a783d5bf8fa5f6f9b5b' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.`

I google and it appears to be some safety feature from the browsers. The app is behind a reverse proxy (haproxy) and is running in Ubuntu 18.04 LTS.

I have other apps that work normally. 

Can you help me?

**Comment by virtualtam** [comment]
> `'https://shaarli.domain.tld/...`

How is Shaarli deployed and configured? This is an example configuration setting, that should most likely be replaced to point to the domain your Shaarli instance is hosted.

**Comment by nodiscc** [comment]
@The-Inamati it appears that the  `Content-type` of your CSS gets changed to `text/html` somewhere along the way. Can you try to `culr --head https://shaarli.domain.tld/tpl/default/css/shaarli.min.css?v=3688d988ea87a141f16453bd3370ef6927c07d4822192a783d5bf8fa5f6f9b5b`

- Normally/in front of HAProxy
- Behind HAProxy and directly to the webserver serving Shaarli

and report the value of the `Content-Type:` header?

**Comment by The-Inamati** [comment]
Sorry. Fixed a long time ago. It was on my end.
