### ISSUE TITLE
[Question]: Is stable docker image still on debian and PHP5 ?

### ISSUE THREAD

**Issue by doc75** [shaarli/Shaarli#1382]
Hello,

Documentation is stating the `stable` docker image is based on `Debian 8 (Jessie)` and `PHP5`.
Looking at the repo, it seems that all images are now based on `alpine`.

Could you confirm if the doc is outdated ?
I yes, then I'll push a PR to update the doc.
If not, what is the process you are using to build the stable docker image ?

Thanks.

**Comment by virtualtam** [comment]
Hi @doc75 ,

Docker images are built from their respective Git branches:
- `master`
- `latest`
- `stable`

Additionally, images are built for each Git tag.

You can see available images and corresponding build logs on the Docker Hub: https://hub.docker.com/r/shaarli/shaarli/tags

This means that all images are built from an Alpine Linux base image, and that the docs are indeed out of date, PR welcome ;-)
