### ISSUE TITLE
the search bar disappears on my.frama

### ISSUE THREAD

**Issue by PatGendre** [shaarli/Shaarli#1384]
Thanks for this great software.
I use the my.frama service for a few month and today something strange happens, on the home page, the search bar is display for about 1 second and then disappears, and I've not found why or how to avoid this. The "add link" is on the bar so is not accessible anymore.

Sorry if the question is not appropriate and should be posted elsewhere.

**Comment by nodiscc** [comment]
Framasoft uses a heavily customized Shaarli (notably their template), so I think you would be better off asking/reporting this on https://framagit.org/framasoft/myframa

**Comment by PatGendre** [comment]
Thanks for the quick reply, I will post the issue on framagit.
