### ISSUE TITLE
[Install Issue] 403 Forbidden (Apache2.4+php-fpm7.3)

### ISSUE THREAD

**Issue by FinalTek** [shaarli/Shaarli#1385]
Hello,
I followed the Manual to install Shaarli, and configure the Apache, but when open the url (path to Shaali) in browser, I am seeing a "403 Forbidden" error message.

I have no idea how to fix it, please help me. Thanks!

```
apachectl -v
Server version: Apache/2.4.41 (Unix)
Server built:   Oct 11 2019 11:59:45
```

```
php -v
PHP 7.3.12 (cli) (built: Nov 22 2019 02:12:36) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.12, Copyright (c) 1998-2018 Zend Technologies
```

Apache debug log:
[shaarli_debuglog.txt](https://github.com/shaarli/Shaarli/files/3902073/shaarli_debuglog.txt)

virtual host configuration:
```
<VirtualHost $IP:80>
        H2Direct        on
        ServerName      $NAME
        Redirect 301 / https://$NAME
        LogLevel        warn
        ErrorLog        "logs/$NAME_error.log"
        CustomLog       "logs/$NAME_access.log" combined
</VirtualHost>
<VirtualHost $IP:443>
        H2Direct        on
        ServerName      $NAME
        ServerAdmin     $EMAIL
        DocumentRoot    "sites/$NAME"
        LogLevel        debug
        ErrorLog        "logs/$NAME_error.log"
        CustomLog       "logs/$NAME_access.log" combined
        SSLEngine on
        SSLCertificateFile "/etc/letsencrypt/live/$NAME/fullchain.pem"
        SSLCertificateKeyFile "/etc/letsencrypt/live/$NAME/privkey.pem"
        <Directory sites/$NAME/>
                DirectoryIndex index.php
                AllowOverride All
                Require all granted
                Options +Indexes +FollowSymLinks +MultiViews
        </Directory>
        <LocationMatch "^(.*\.php)$">
            ProxyPass fcgi://127.0.0.1:9000/sites/$NAME/$1
        </LocationMatch>
</VirtualHost>
```

**Comment by nodiscc** [comment]
```
[Thu Nov 28 15:09:58.678156 2019] [authz_core:debug] [pid 613:tid 13442488473664] mod_authz_core.c(817): [client $CLIENT:44692] AH01626: authorization result of Require all denied: denied
[Thu Nov 28 15:09:58.678163 2019] [authz_core:debug] [pid 613:tid 13442488473664] mod_authz_core.c(817): [client $CLIENT:44692] AH01626: authorization result of <RequireAny>: denied
[Thu Nov 28 15:09:58.678168 2019] [authz_core:error] [pid 613:tid 13442488473664] [client $CLIENT:44692] AH01630: client denied by server configuration: /var/www/sites/$WEBSITE/

```

It seems there is a `Require all denied` directive in your apache config somewhere preventing access to the ` /var/www/sites/$WEBSITE/` directory (I assume you redacted your real domain name, and it's not actually `$WEBSITE` in the log, else something is not corect).

Can you give the output of `grep -r --context=5 'Require all denied' /etc/apache2/`?

**Comment by FinalTek** [comment]
>  grep -r --context=5 'Require all denied' /etc/apache2/
/etc/apache2/httpd2.conf-# explicitly permit access to web content directories i                                                    n other
/etc/apache2/httpd2.conf-# <Directory> blocks below.
/etc/apache2/httpd2.conf-#
/etc/apache2/httpd2.conf-<Directory />
/etc/apache2/httpd2.conf-    AllowOverride none
/etc/apache2/httpd2.conf:    Require all denied
/etc/apache2/httpd2.conf-</Directory>
/etc/apache2/httpd2.conf-
/etc/apache2/httpd2.conf-#
/etc/apache2/httpd2.conf-# Note that from this point forward you must specifical                                                    ly allow
/etc/apache2/httpd2.conf-# particular features to be enabled - so if something's                                                     not working as
--
/etc/apache2/httpd2.conf-#
/etc/apache2/httpd2.conf-# The following lines prevent .htaccess and .htpasswd f                                                    iles from being
/etc/apache2/httpd2.conf-# viewed by Web clients.
/etc/apache2/httpd2.conf-#
/etc/apache2/httpd2.conf-<Files ".ht*">
/etc/apache2/httpd2.conf:    Require all denied
/etc/apache2/httpd2.conf-</Files>
/etc/apache2/httpd2.conf-
/etc/apache2/httpd2.conf-#
/etc/apache2/httpd2.conf-# ErrorLog: The location of the error log file.
/etc/apache2/httpd2.conf-# If you do not specify an ErrorLog directive within a                                                     <VirtualHost>
--
/etc/apache2/httpd2.conf.origbackup-# explicitly permit access to web content di                                                    rectories in other
/etc/apache2/httpd2.conf.origbackup-# <Directory> blocks below.
/etc/apache2/httpd2.conf.origbackup-#
/etc/apache2/httpd2.conf.origbackup-<Directory />
/etc/apache2/httpd2.conf.origbackup-    AllowOverride none
/etc/apache2/httpd2.conf.origbackup:    Require all denied
/etc/apache2/httpd2.conf.origbackup-</Directory>
/etc/apache2/httpd2.conf.origbackup-
/etc/apache2/httpd2.conf.origbackup-#
/etc/apache2/httpd2.conf.origbackup-# Note that from this point forward you must                                                     specifically allow
/etc/apache2/httpd2.conf.origbackup-# particular features to be enabled - so if                                                     something's not working as
--
/etc/apache2/httpd2.conf.origbackup-#
/etc/apache2/httpd2.conf.origbackup-# The following lines prevent .htaccess and                                                     .htpasswd files from being
/etc/apache2/httpd2.conf.origbackup-# viewed by Web clients.
/etc/apache2/httpd2.conf.origbackup-#
/etc/apache2/httpd2.conf.origbackup-<Files ".ht*">
/etc/apache2/httpd2.conf.origbackup:    Require all denied
/etc/apache2/httpd2.conf.origbackup-</Files>
/etc/apache2/httpd2.conf.origbackup-
/etc/apache2/httpd2.conf.origbackup-#
/etc/apache2/httpd2.conf.origbackup-# ErrorLog: The location of the error log fi                                                    le.
/etc/apache2/httpd2.conf.origbackup-# If you do not specify an ErrorLog directiv                                                    e within a <VirtualHost>

**Comment by nodiscc** [comment]
- What happens when you access `https://your.shaarli.domain/index.php`?
- Please set `LogLevel` to `debug` and reload apache, and try to access Shaarli. Can you see any relevant error message in your `logs/$NAME_error.log` log?

**Comment by nodiscc** [comment]
@FinalTek can you post your `/etc/apache2/httpd2.conf` file?

**Comment by KyleWJohnston** [comment]
Try moving your `Directory` section before the `VirtualHost` section rather than inside of it. I received this error and doing this fixed it for me.

**Comment by nodiscc** [comment]
@FinalTek do you still have this problem?

**Comment by ArthurHoaro** [comment]
I'm closing old issues tagged `support` which are likely outdated. If you feel like this should stay open, please say so.
