### ISSUE TITLE
Migration from 0.10.3 to 0.10.4 fails (internal server error)

### ISSUE THREAD

**Issue by guillaume-roche** [shaarli/Shaarli#1386]
Hi,

I'm trying to update from 0.10.3 to 0.10.4, but I encounter some "internal server error". If I switch back to 0.10.3, everything is fine.

I updated with the full zip file, and copied the content of my existing data folder.
I switched from PHP 7.2 to 7.3 without solving the issue.
I also tried to fix the updates.txt file according to the troubleshooting section of the documentation, I still get the error.

I'm using a managed hosting, and I couldn't manage to get the server logs yet.

**Comment by dajare** [comment]
I think I've had this kind of problem with Shaarli upgrades. Have you checked to see if there's an issue with your `.htaccess` file(s)? Take a [look at this fix][1] in issue #1196 and see if that helps.

I have needed to implement that to keep my Shaarli sites working on shared hosting. Maybe it will help for you?

[1]: https://github.com/shaarli/Shaarli/issues/1196#issuecomment-412271085

**Comment by virtadpt** [comment]
@dajare This.  I have to re-apply those patches to .htaccess every time.

**Comment by nodiscc** [comment]
I just added https://github.com/shaarli/Shaarli/blob/master/doc/md/Troubleshooting.md#old-apache-versions-internal-server-error to the docs. @guillaume-roche does this workaround fix your problem?

**Comment by ArthurHoaro** [comment]
I'm closing old issues tagged `support` which are likely outdated. If you feel like this should stay open, please say so.
