### ISSUE TITLE
Suggestions: Easy way to implement Google Analytics and other codes. WYSIWYG editor

### ISSUE THREAD

**Issue by pipetko** [shaarli/Shaarli#1387]
It will be perfect if there is an easy way to implement tracking codes like Google Analytics, verification codes for search engines. Also Adsense codes.

WYSIWYG editor will beh helpful in adding notes section

**Comment by ArthurHoaro** [comment]
Any custom JS injection can easily be through a custom plugin using the [plugin system](https://shaarli.readthedocs.io/en/master/Plugin-System/).

Note that a JS WYSIWYG Markdown editor could be interesting as a core supported plugin.

**Comment by nodiscc** [comment]
WYSIWYG part of this issue moved to https://github.com/shaarli/Shaarli/issues/1434
