### ISSUE TITLE
Cannot change `font-family` for `code` in user.css

### ISSUE THREAD

**Issue by dajare** [shaarli/Shaarli#1388]
This is a bit odd, and not a bug (I'm pretty sure!), but my ignorance regarding CSS. I want to change the font for the `code` style in my **user.css** file. When I include:

    code { color: red; }

that works just fine, but if i add:

    code { font-family: Consolas, monospace, monospace; color: red; }

Then the color still "works", but the change of font does not. Likewise, I cannot change the `font-size`.

I have two installations of Shaarli: one runs the default theme, the other one uses "Material" by kalvn. Both show the same behaviour. Using "View Source", I see that `/tpl/default/css/shaarli.min.css` includes:

    code,kbd,pre,samp{font-family:monospace,monospace;font-size:1em}

But I cannot work out how to over-ride it! Any help with this would be appreciated.

I'm on Shaarli 0.10.2, if that makes a difference. Thanks!

**Comment by ArthurHoaro** [comment]
Hi, sorry for the delay, your issue got buried.

I suggest that you take a look at CSS precedence rules. More precise rules will have a higher "priority".

In this case, there is a markdown specific rule which overrides your `font-family` and `font-size`.

![](https://i.imgur.com/jUt9Z5v.png)
