### ISSUE TITLE
Thumbnails missing in certain browsers

### ISSUE THREAD

**Issue by zerosonesfun** [shaarli/Shaarli#1390]
On my iPhone, in Safari and Chrome iOS, the thumbnails show up just fine. But, on my Chromebook, the thumbnails are missing. The thumbnail url is there in the HTML:

~~~
<img data-src="cache/thumb/bfab0dbc1288d325bd6fea7346e39fc5/5525646db4756f4f4725d5c9a604e613ff419348125901.jpg" class="b-lazy" src="" alt="" width="125" height="90">
~~~

No errors in the console. Very strange that the images load on my iPhone, and not on this laptop... Has anyone else experienced this?

**Comment by ArthurHoaro** [comment]
I think this is a duplicate of #1357, which has been fixed but not released yet. Please take a look at the workaround provided in the linked issue and let us know if it fixes your issue.

**Comment by zerosonesfun** [comment]
That fixes it. Thank you.
