### ISSUE TITLE
I made a Ulauncher extension for Shaarli

### ISSUE THREAD

**Issue by sebw** [shaarli/Shaarli#1397]
Hello community,

I made an [extension](https://ext.ulauncher.io/-/github-sebw-ulauncher-shaarli) for Ulauncher to find my bookmarks in Shaarli ([sources on Github](https://github.com/sebw/ulauncher-shaarli)).

I was trying to find a list of third party tools integrating with Shaarli in the documentation, but couldn't find.

Do we have such a list?

**Comment by ArthurHoaro** [comment]
Hi @sebw,

I don't personally use Ulauncher, but looking at the screencast it looks really good.

You can edit this documentation page which refers to all 3rd party software related to Shaarli : https://shaarli.readthedocs.io/en/master/Community-&-Related-software/

You can edit it in `doc/md/` and submit a PR.
