### ISSUE TITLE
Remove docker-shaarli repository

### ISSUE THREAD

**Issue by nodiscc** [shaarli/Shaarli#1405]
https://github.com/shaarli/docker-shaarli has been archived for +3 years, it may be ok to remove it now.

**Comment by nodiscc** [comment]
Same thing for https://github.com/shaarli/shaarli-themes, last update in 2015, only works (maybe?) with the legacy template.

**Comment by virtualtam** [comment]
Agreed :)

**Comment by nodiscc** [comment]
Goodbye old repos then. I am attaching a zip of the themes repository in case someone needs it.

[shaarli-themes-master.zip](https://github.com/shaarli/Shaarli/files/4099133/shaarli-themes-master.zip)
