### ISSUE TITLE
Readthedocs builds are failing

### ISSUE THREAD

**Issue by nodiscc** [shaarli/Shaarli#1412]
- `ImportError: cannot import name 'PackageFinder'`
- https://readthedocs.org/projects/shaarli/builds/10329496/
- https://readthedocs.org/projects/shaarli/builds/

**Comment by ArthurHoaro** [comment]
Do you have any idea what could cause this issue?

**Comment by nodiscc** [comment]
It was temporary, doc builds are now passing https://readthedocs.org/projects/shaarli/builds/
