### ISSUE TITLE
Feature wish: open links in new tab (target=_blank)

### ISSUE THREAD

**Issue by HonkXL** [shaarli/Shaarli#1414]
I think it would be very helpful to get an option in the settings "open links in new tab" that brings up links to target=_blank.
Problem is, that a lot of people work with browser tabs, but when new external links opens in the same tab, the standard workflow is broken.

I know that some people dislike tabs, so I think the best solution would be to make this configurable.

**Comment by ArthurHoaro** [comment]
Hi, there is a 3rd party plugin out there which does exactly that: https://github.com/trailjeep/shaarli-urlextern

Also see #422
