### ISSUE TITLE
ERROR: [Errno 2] No such file or directory: 'install'

### ISSUE THREAD

**Issue by bmsleight** [shaarli/Shaarli#1415]
Using https://shaarli.readthedocs.io/en/master/Download-and-Installation/#development-version-mainline

```
root@shaarli:~/Shaarli# make build_frontend
yarn install
00h00m00s 0/0: : ERROR: [Errno 2] No such file or directory: 'install'
Makefile:109: recipe for target 'frontend_dependencies' failed
make: *** [frontend_dependencies] Error 1
root@shaarli:~/Shaarli

```

I am trying to get the shaarli set-up with Thumbnail generation. Tried v0.10.4 and v0.11.1 (install ok but thumbnail synchronisation hangs) - can not find any logs. 

So tried installing the development version (within a lxc container).
```

$ lxc exec shaarli  -- /bin/bash 
root@shaarli:~# apt-get update
...
root@shaarli:~# apt-get install curl php-cli php-mbstring git unzip composer yarn python3-venv php-curl php-xml make
...
root@shaarli:~# git clone https://github.com/shaarli/Shaarli.git -b master
...
root@shaarli:~# cd Shaarli/
root@shaarli:~/Shaarli# composer install --no-dev --prefer-dist
Do not run Composer as root/super user! See https://getcomposer.org/root for details
Loading composer repositories with package information
Installing dependencies from lock file
Package operations: 14 installs, 0 updates, 0 removals
  - Installing phpunit/php-text-template (1.2.1): Downloading (100%)         
  - Installing arthurhoaro/web-thumbnailer (v2.0.1): Downloading (100%)         
  - Installing erusev/parsedown (1.7.4): Downloading (100%)         
  - Installing gettext/languages (2.6.0): Downloading (100%)         
  - Installing gettext/gettext (v4.8.2): Downloading (100%)         
  - Installing psr/log (1.1.2): Downloading (100%)         
  - Installing pubsubhubbub/publisher (dev-master 047b0fa): Downloading (100%)         
  - Installing katzgrau/klogger (1.2.1): Downloading (100%)         
  - Installing shaarli/netscape-bookmark-parser (v2.1.0): Downloading (100%)         
  - Installing psr/http-message (1.0.1): Downloading (100%)         
  - Installing psr/container (1.0.0): Downloading (100%)         
  - Installing pimple/pimple (v3.2.3): Downloading (100%)         
  - Installing nikic/fast-route (v1.3.0): Downloading (100%)         
  - Installing slim/slim (3.12.3): Downloading (100%)         
Generating autoload files
root@shaarli:~/Shaarli# make build_frontend
yarn install
00h00m00s 0/0: : ERROR: [Errno 2] No such file or directory: 'install'
Makefile:109: recipe for target 'frontend_dependencies' failed
make: *** [frontend_dependencies] Error 1
root@shaarli:~/Shaarli#

```

Look like it may be related to #1187 but the solution to this was to install one of the releases (which take me back to the same problem with thumbnails. 

Same error if I use https://shaarli.readthedocs.io/en/master/Download-and-Installation/#using-git 

Any hints on what I am doing wrong on:-
https://shaarli.readthedocs.io/en/master/Download-and-Installation/#development-version-mainline

**Comment by ArthurHoaro** [comment]
I'm not exactly sure what's going on, either with your thumbnails nor your install but one thing at a time. I don't have any issue running `yarn install` neither does our Docker build. So I suspect there is something else related to your environment.

Can this be related: https://stackoverflow.com/a/47680012/1484919 ?

**Comment by bmsleight** [comment]
Hi ArthurHoaro,

Thanks that alternative yarn solved that problem.  (Had to ammend Makefile for make htmldoc #1416 )

I placed the Shaarli files in the correct location, but it appears the css files are missing

```
# ls /var/www/html/Shaarli/tpl/default/ -R
/var/www/html/Shaarli/tpl/default/:
404.html             configure.html  error.html             feed.rss.html  linklist.html         page.footer.html   tag.cloud.html   tools.html
addlink.html         daily.html      export.bookmarks.html  import.html    linklist.paging.html  page.header.html   tag.list.html
changepassword.html  dailyrss.html   export.html            includes.html  loginform.html        picwall.html       tag.sort.html
changetag.html       editlink.html   feed.atom.html         install.html   opensearch.html       pluginsadmin.html  thumbnails.html
# ls /var/www/html/Shaarli/tpl/default/css
ls: cannot access '/var/www/html/Shaarli/tpl/default/css': No such file or directory

```

**Comment by nodiscc** [comment]
Can you post the full output of the process described at https://shaarli.readthedocs.io/en/master/Download-and-Installation/#development-version-mainline, until the error?

If the log is too big you can attach it as a `.log` file to your comment.

**Comment by bmsleight** [comment]
Poor bug reporting by myself.  (Two district bugs) 

Bug 1 
```
# make build_frontend
yarn install
00h00m00s 0/0: : ERROR: [Errno 2] No such file or directory: 'install'
Makefile:109: recipe for target 'frontend_dependencies' failed
make: *** [frontend_dependencies] Error 1

```

Resolved by https://stackoverflow.com/a/47680012/1484919  - using a later version of yarn

Bug 2
```
# ls /var/www/html/Shaarli/tpl/default/css
ls: cannot access '/var/www/html/Shaarli/tpl/default/css': No such file or directory

```

Install work without any error reporting, but not css files are present when following https://shaarli.readthedocs.io/en/master/Download-and-Installation/#development-version-mainline

When using the released bundle (zip/tar.gz) css files are present.

I will close this issue
Raise the other as missing css files. #1418
