### ISSUE TITLE
Missing css files when following instructions Development version (mainline)

### ISSUE THREAD

**Issue by bmsleight** [shaarli/Shaarli#1418]
After following https://shaarli.readthedocs.io/en/master/Download-and-Installation/#development-version-mainline

installs fine, working and able to access but no css.

```
# ls /var/www/html/Shaarli/tpl/default/ -R
/var/www/html/Shaarli/tpl/default/:
404.html             configure.html  error.html             feed.rss.html  linklist.html         page.footer.html   tag.cloud.html   tools.html
addlink.html         daily.html      export.bookmarks.html  import.html    linklist.paging.html  page.header.html   tag.list.html
changepassword.html  dailyrss.html   export.html            includes.html  loginform.html        picwall.html       tag.sort.html
changetag.html       editlink.html   feed.atom.html         install.html   opensearch.html       pluginsadmin.html  thumbnails.html
# ls /var/www/html/Shaarli/tpl/default/css
ls: cannot access '/var/www/html/Shaarli/tpl/default/css': No such file or directory

```

[shaarli.log](https://github.com/shaarli/Shaarli/files/4172366/shaarli.log)

**Comment by ArthurHoaro** [comment]
In your log, you're only cloning the repo, not following the documentation. You need to run the other commands to compile SASS files into CSS (and other stuff) if you want to use the development version.

**Comment by bmsleight** [comment]
How embarrassing - problem exists between chair and keyboard ?
Closed

Log file:-
Line 704 - Updated Makefile for ubuntu
Line 1144 - All css files present
Line 1194 - a2enmod rewrite

I honestly thought I run all the commands last time, I just copied and pasted them again. 

Sorry and thanks for shaarli
[shaarli-PEBCAK.log](https://github.com/shaarli/Shaarli/files/4172564/shaarli-PEBCAK.log)

**Comment by ArthurHoaro** [comment]
No worries, I'm glad we could help. :)
