### ISSUE TITLE
vimeo.com thumbnails are not generated

### ISSUE THREAD

**Issue by pmerletdevweb** [shaarli/Shaarli#1419]
#Bonjour,

Dans la version Shaarli 11.1 les vignettes pour le site Vimeo  ne sont plus générées.

système tournant sous PHP 5.6

**Comment by nodiscc** [comment]
Hi,

PHP 5.6 has reached its [end of life](https://www.php.net/supported-versions.php) and is [no longer supported](https://shaarli.readthedocs.io/en/master/Server-configuration/#prerequisistes). You are strongly encouraged to upgrade to one of the supported PHP versions. Some PHP 5.6 versions may also contain [security vulnerabilities](https://www.cvedetails.com/version-list/74/128/6/PHP-PHP.html?sha=78e084dbc6897971bd02e634619a193e623904d6&order=1&trc=1128)

>11.1

I assume you mean 0.11.1? Thumbnail generation on vimeo.com is working fine for me:

![Capture d’écran_2020-02-09_01-00-17](https://user-images.githubusercontent.com/3950390/74179049-8ca73480-4c34-11ea-8aff-7f6c2663f07a.png)

You can also [configure WebThumbnailer](https://github.com/ArthurHoaro/web-thumbnailer/blob/master/README.md#miscellaneous) to generate debug messages and check your webserver error logs, but there are no guarantees with such an old version of PHP.

**Comment by ArthurHoaro** [comment]
Closing after @nodiscc answer and lack of feedback. Please add more information if you feel like this issue should be reopened.
