### ISSUE TITLE
Hide mobile login link via CSS

### ISSUE THREAD

**Issue by tiborepcek** [shaarli/Shaarli#1422]
Hi and thank you for this great tool.

I yould like to ask, if it is possible to hide login link in mobile menu with CSS. I tried it in `data/user.css`, but it worked only for desktop version like this:

`#shaarli-menu-desktop-login {display: none;}`

This one did not work:

`#shaarli-menu-mobile-login {display: none;}`

Any help, please?

**Comment by ArthurHoaro** [comment]
Hi, I just tried, and adding your CSS rule dynamically on the default template with Firefox works:

```
#shaarli-menu-mobile-login {
  display: none;
}
```

![](https://i.imgur.com/C15JCnW.png)
