### ISSUE TITLE
Apache configuration in docs is out of date

### ISSUE THREAD

**Issue by KyleWJohnston** [shaarli/Shaarli#1423]
The [Apache configuration example](https://github.com/shaarli/Shaarli/blob/master/doc/md/Server-configuration.md#apache) is broken ([Read the Docs link](https://shaarli.readthedocs.io/en/master/Server-configuration/#apache)). I tested each of the changes made below and leaving out any one of them broke the server. Errors included "Can't reach server", "Object not found", "Access forbidden", or "Can't provide secure connection".

### Change 1
Update `Directory` options and remove comment.
```diff
<Directory /absolute/path/to/shaarli/>
     #Required for .htaccess support
-    AllowOverride All
-    Order allow,deny
-    Allow from all
+    Require all granted
 
-    Options Indexes FollowSymLinks MultiViews #TODO is Indexes/Multiviews required?
+    Options Indexes FollowSymLinks
 
     # Optional - required for playvideos plugin
     #Header set Content-Security-Policy "script-src 'self' 'unsafe-inline' https://www.youtube.com https://s.ytimg.com 'unsafe-eval'"
</Directory>
```

### Change 2
Add an alias, move the `Directory` section from the Change 1 to before `VirtualHost` section, change port 443 to port 80, and add comment that Let's Encrypt configuration is only needed if not already configured in `httpd-ssl.conf`.
```diff
+Alias /shaarli /absolute/path/to/shaarli/
+
+<Directory /absolute/path/to/shaarli/>
+    #Required for .htaccess support
+    Require all granted
+
+    Options Indexes FollowSymLinks MultiViews
+
+    # Optional - required for playvideos plugin
+    #Header set Content-Security-Policy "script-src 'self' 'unsafe-inline' https://www.youtube.com https://s.ytimg.com 'unsafe-eval'"
+</Directory>
+
-<VirtualHost *:443>
+<VirtualHost *:80>
     ServerName   shaarli.my-domain.org
     DocumentRoot /absolute/path/to/shaarli/
 
    # Logging
    # Possible values include: debug, info, notice, warn, error, crit, alert, emerg.
    LogLevel  warn
    ErrorLog  /var/log/apache2/shaarli-error.log
    CustomLog /var/log/apache2/shaarli-access.log combined

-   # Let's Encrypt SSL configuration (recommended)
+   # Let's Encrypt SSL configuration (recommended if not in httpd-ssl.conf)
    SSLEngine             on
    SSLCertificateFile    /etc/letsencrypt/live/yourdomain.example.com/fullchain.pem
    SSLCertificateKeyFile /etc/letsencrypt/live/yourdomain.example.com/privkey.pem
    Include /etc/letsencrypt/options-ssl-apache.conf

    # Self-signed SSL cert configuration
    #SSLEngine             on
    #SSLCertificateFile    /etc/ssl/certs/ssl-cert-snakeoil.pem
    #SSLCertificateKeyFile /etc/ssl/private/ssl-cert-snakeoil.key

    # Optional, log PHP errors, useful for debugging
     #php_flag  display_errors on
     #php_value error_reporting 2147483647
     #php_value error_log /var/log/apache2/shaarli-php-error.log
-
-    <Directory /absolute/path/to/shaarli/>
-        #Required for .htaccess support
-        Require all granted
-
-        Options Indexes FollowSymLinks
-
-        # Optional - required for playvideos plugin
-        #Header set Content-Security-Policy "script-src 'self' 'unsafe-inline' https://www.youtube.com https://s.ytimg.com 'unsafe-eval'"
-    </Directory>
-
 </VirtualHost>
```

I'd like to submit a PR unless anyone sees an issue with the suggested changes. I'm fairly new to Apache, so feedback is welcome! Thanks.

**Comment by nodiscc** [comment]
Well there is ongoing work on refactoring the installation/configuration guide and webserver config examples here: https://github.com/shaarli/Shaarli/pull/1389. The result can be seen at https://shaarli.readthedocs.io/en/doc-rework-setup/.

If you can submit a pull request against the `doc-rework-setup` branch I welcome your help on this task.

**Comment by KyleWJohnston** [comment]
Thanks, I'll submit the above changes against the `doc-rework-setup` branch then.

**Comment by nodiscc** [comment]
Work in progress to refactor the Server setup documentation in https://github.com/shaarli/Shaarli/pull/1389. Updated apache config at https://shaarli.readthedocs.io/en/doc-rework-setup/Server-configuration/#apache.

@KyleWJohnston please let me know in https://github.com/shaarli/Shaarli/pull/1389 comments if something is missing/incorrect.
