### ISSUE TITLE
Thumbnails error 400

### ISSUE THREAD

**Issue by kour1er** [shaarli/Shaarli#1425]
New to this project so please forgive if this isn't the preferred method for receiving this report. (and if I'm missing something obvious).

Environment: macOS 10.15.3
httpd: 2.4.41 (via brew)
php: 7.4 (via brew)

On a clean install of v0.11.1, when trying to synchronise thumbnails or add a new link and the subsequent generation of thumbnails if I set logging to debug I see this error:

---

[Sat Feb 29 16:32:11.956832 2020] [php7:info] [pid 54167] [client 10.0.0.4:49843] PHP Deprecated:  implode(): Passing glue string after array is deprecated. Swap the parameters in /usr/local/share/WebApps/shaarli/tmp/thumbnails.b91ef64efc3688266305ea9b42e5017e.rtpl.php on line 43, referer: https://shaarli.domain.com/?do=tools

---

If I alter the implode in files tpl/thumbnails.html:

`<?php echo implode(',',$ids); ?>`

The thumbnail issue seems to be resolved.

Cheers

**Comment by nodiscc** [comment]
@kour1er do you still have this problem?

**Comment by ArthurHoaro** [comment]
Thanks for the report. This has been fixed by https://github.com/shaarli/Shaarli/commit/fc6c7017746b81b267d8020968ab117e9383a23c released in `v0.12.0`.
