### ISSUE TITLE
blank image wall, no image displayed 

### ISSUE THREAD

**Issue by accnetdev** [shaarli/Shaarli#1429]
Hi,
I have installed the last stable version and noticed that the image wall is blank even if I refresh thumbnails.
Please help.

**Comment by nodiscc** [comment]
Do you have any errors when accessing the picture wall page in your browser console or webserver logs? If yes then please post your logs.

Also please post names and version for your web browser, web server, and the method you followed to install Shaarli.

**Comment by accnetdev** [comment]
Hi, thanks to reply.

No error.

Any browser / any OS.
Google Chrome Version 80.0.3987.132 (Build officiel) (64 bits)
Firefox Ubuntu 73.0.1 (64 bits)

Install : upload 0.11.1 to a new hosting and upload the /data of a previous version of Shaarli. 

Server (hosting LWS) : http://accserv.fr/phpinfolws.php

See what I see : http://accserv.fr/shaarli/?do=picwall

**Comment by nodiscc** [comment]
There **are** errors in the browser console for me, please recheck.

There is something wrong with your file https://accserv.fr/shaarli/tpl/default/js/thumbnails.min.js, it differs from the file `tpl/default/js/shaarli.min.js` provided in https://github.com/shaarli/Shaarli/releases/download/v0.11.1/shaarli-v0.11.1-full.tar.gz

```
Échec du chargement pour l’élément <script> dont la source est « https://accserv.fr/shaarli/tpl/default/js/shaarli.min.js?v=6…95d994de8477d8005f5bb9d5776b24fdf4ff020fbea0a2ccfb34536d84dc ».
```

Please check the contents of this file on your server, and make sure it is the same file as the one provided in the zip archive.

**Comment by accnetdev** [comment]
Hi,
You're right, I don't understand why, but it is a fact.

SHA-256
"bad thumbnail.min.js"
E5AF0C8A888C4572D2FCC3B003CD8A5FC61AF2A68F4D4292F44CFC4A14992F57
"current tar thumbnail.min.js (0.11.1)"
7FFB082CA31B10612D5B3D1D645BF6E2228EC2D3CDBCC614A01702AB661306FD

So I updated thumbnail.min.js with the one of the current tar.full, no change the issue is still here.
Then I updated the whole shaarli script with the current tar.full, no change the issue is still here.

I you recheck now thumbnail.min.js you'll see that it is the right one.

Another idea ?

**Comment by nodiscc** [comment]
Please post SHA256 sums of all files in your `tpl/default/js/` directory

**Comment by accnetdev** [comment]
Sorry I locked my github account, hope you'll receive that...

/js$ sha256sum *
67fceac71d9ba5fef1ce9497daae1d3d076ce11ffef2d117422e18b63f37eb67
 pluginsadmin.min.js
db56d31959cfd6ee76942f378d2b25bb8d882c1c09328a9901220f9f4a14b55d
 shaarli.min.js
e5af0c8a888c4572d2fcc3b003cd8a5fc61af2a68f4d4292f44cfc4a14992f57
 thumbnails.min.js
91390de3c435312a233632ebc4727b8b8505612c350a2cc510a34823987189d1
 thumbnails_update.min.js

**Comment by Cyrixo** [comment]
Hello, same issue here, php7 error ?
Error log : 
`[php7:notice] [pid 10767] [client 18X.X.2.148:5252] No thumbnail could be found using default finder: http://domaineA.net/wiki/doku.php?id=android, referer: https://domaineB.fr/?do=thumbs_update`

**Comment by ozgurcakmak** [comment]
I tracked this problem and found out that it is a view issue. Basically when it is iterating over the links, it doesn't fill the src tag and it results in unknown:
```
<div class="center">
        <div id="picwall_container">
            {loop="$linksToDisplay"}
            <div class="picwall_pictureframe">
                {ignore}RainTPL hack: put the 2 src on two different line to avoid path replace bug{/ignore}
                <img data-src="{$value.thumbnail}#" class="b-lazy"
                     src=""
                     alt="thumbnail" width="{$thumbnails_width}" height="{$thumbnails_height}" />
                <a href="{$value.real_url}"><span class="info">{$value.title}</span></a>
                {loop="$value.picwall_plugin"}
                    {$value}
                {/loop}
            </div>
            {/loop}
        </div>
</div>
```

When I replaced the `src` attribute with `"{$value.thumbnail}#"` I managed to get the thumbnails. I don't know whether this is a proper fix, but it acted as a bandaid.

**Comment by accnetdev** [comment]
OK. What can you advice?
What change(s) in which shaarli's file(s)?

**Comment by ArthurHoaro** [comment]
Hi, sorry for the delay.
Can you check if this workaround fixes your issue: https://github.com/shaarli/Shaarli/issues/1357#issuecomment-524535673

**Comment by ozgurcakmak** [comment]
I made this change in the `tpl/vintage/picwall.html` of the theme I was using. BUT I recommend @ArthurHoaro's solution if it works. Not to mention it is merged in the code, it is less invasive than my change.

**Comment by nodiscc** [comment]
It is proprely fixed in https://github.com/shaarli/Shaarli/pull/1354, see https://github.com/shaarli/Shaarli/issues/1357#issuecomment-524535673 for a workaround until the next release.
