### ISSUE TITLE
Running Shaarli on Docker on a VPS: Can't login using apps but browser login works fine

### ISSUE THREAD

**Issue by battlezone** [shaarli/Shaarli#1430]
As the title says I am running Shaarli on Docker on a VPS but I cannot login using Shaarlier or Stakali. Both say that there's a problem with authentication. When I navigate via my browser to the Shaarli instance I can login without any issue. The Shaarli logs also only show me loging in via the webpage. There are only "Login succesful" logs and nothing else.

Does anyone have an idea what I am doing wrong here? Does the communication between app and Shaarli run on a different port than 80 by any chance (Docker 8000->80)?

**Comment by immanuelfodor** [comment]
This is definitely not a Docker issue, I'm experiencing the same after updating to the latest master. But I get login page error as well with the Material theme: https://github.com/kalvn/Shaarli-Material/issues/95

**Comment by nodiscc** [comment]
Please post your full client error logs, and server access/error logs at the time of the error

**Comment by immanuelfodor** [comment]
I reverted back to my previous build of Shaarli, and as kalvn said at https://github.com/kalvn/Shaarli-Material/issues/95 he indeed let the theme diverge from Shaarli master, so I feel the problem in my case is with the theme, not Shaarli core. My error log can be found at the referenced issue's OP.

**Comment by nodiscc** [comment]
@battlezone can you still reproduce this bug?

**Comment by battlezone** [comment]
@nodiscc I cannot reproduce this bug. I don't know what I've done to fix it, but it works fine now.

**Comment by ArthurHoaro** [comment]
If you were talking about https://github.com/dimtion/Shaarlier, I think that @dimtion has published a new major version to use the REST API, which probably fixed your issue.

**Comment by dimtion** [comment]
@battlezone I can shed a bit of light on an issue I had with multiple users, that might help you find out the source of the issue.

Some web providers install in front of their instance anti-DDoS services that blocks the use of the Shaarli API. One example is to make the client solve a Javascript challenge before reaching the final page.

To find that out, you should try manually to do a request to your Shaarli instance (using Curl for example) and look if the received payload looks like a a valid JSON payload from the API.

@immanuelfodor For Shaarlier, if you are using version 1.7.2 and the token authentication there should be no issue using a personalized theme, if so, I encourage you to open an issue back in Shaarlier repo.
