### ISSUE TITLE
foo.com/bar and foo.com/bar/ are not being caught as duplicates

### ISSUE THREAD

**Issue by ChangePlaces** [shaarli/Shaarli#1431]
You may want to also check for things like empty query strings on the end of the url too e.g. foo.com/bar?

**Comment by virtadpt** [comment]
Agreed.  I'm working on some code to work on deduplicating URLs in my instance over here.  It'd be nice not to have to do that.

**Comment by nodiscc** [comment]
Duplicate of https://github.com/shaarli/Shaarli/issues/1444, let's track this there
