### ISSUE TITLE
Make tag cloud/list views buttons more obvious

### ISSUE THREAD

**Issue by nodiscc** [shaarli/Shaarli#1437]
From https://github.com/shaarli/Shaarli/issues/1432

> view tagged bookmarks as contents inside folders named after the tag, so tag cloud, because a list of tags with a folder icon and tag title underneath rather than a squished up bunch of words. Then, clicking on a 'folder' takes you to a filtered search for that tag.

This is what tags list views do, but the UI for switching list view mode is very terse/not immediately obvious that Cloud/Alphabetical/... items are actionable

![listview](https://user-images.githubusercontent.com/3950390/76577835-65a38300-64be-11ea-844c-a5f57034a3b5.png)

There should at least be a discrete border to indicate they are in fact buttons. Or an iconfont glyph on the left side of each button.

**Comment by philipp-r** [comment]
Maybe like this:

![Screenshot from 2020-07-16 15-20-10](https://user-images.githubusercontent.com/5230616/87676380-d7475280-c778-11ea-8f64-0fcb6b4ec9a5.png)

Same design as the filters on the main page.
