### ISSUE TITLE
Let RainTPL handle date formatting

### ISSUE THREAD

**Issue by alexisju** [shaarli/Shaarli#144]
As you know, date's formatting depends of the server's configuration.This causes some difficulties:

- Local problem (for example, if the server is configured in English, the date will not be displayed in your usual format, which can be uncomfortable for the user).
- The format is not necessarily the one I want to use my template (and having to hack index.php is not what there is of more convenient)

Specifically, in the case of AlbinoMouse on the shared hosting I use, I have to edit the index.php file to force the local French (setlocale (LC_TIME, 'en_US', 'eng')).

The result is "jeu. 05 March 2015 18:30:15 CET."

But if I want to display the date differently, for example in the format d / m / Y, it's impossible to do that by changing my template.

@ArthurHoaro for his personal shaarli uses a hack index.php to display the date it this way (d / m / Y): http://git.hoa.ro/arthur/links/blob/master/index.php#L1802

Another aspect is that of privacy (hiding timestamp) when sharing her with RSS Shaarlo: if totally mask the date and time, it does not work. But it's maybe possible to hide time into linklist/daily and preserve it into the rss...

**Comment by ArthurHoaro** [comment]
I did a ugly hack, but I think we can do better with RainTPL like [this](https://github.com/rainphp/raintpl3/issues/167). We just need to provide the timestamp instead of formatted date.

About RSS datetime, I wouldn't recommand it since RSS Reader (such as Shaarlo) might use it to retrieve or order their *shaare*.

**Comment by nodiscc** [comment]
I'd be ok with letting RainTPL parse and format dates (index.php would just pass a timestamp), **but** Shaarli currently formats the date/time depending on the browser locale (`Accept-Language` HTTP request header) and I don't know if RainTPL can do the same thing.

> But it's maybe possible to hide time into linklist/daily and preserve it into the rss...

No. `HIDE_TIMESTAMPS` should be respected everywhere.

**Comment by mro** [comment]
I once used a pure client-side human-friendly date formatting via http://momentjs.com/. Server deals with ISO8601 only. Target locale could maybe sit in a cookie.

see here: http://rec.mro.name/stations/b2/2015/03/10/0605%20radioWelt.xml#date

**Comment by nodiscc** [comment]
@ArthurHoaro @alexisju do you want to send a pull request to change date format handling (generate a timestamp in index.html, render it in template)? This should be done before work on https://github.com/shaarli/Shaarli/issues/163 is finished because it introduces changes to the templates (add date rendering code to them).

**Comment by alexisju** [comment]
(I don't know how to do that... but it will be nice indeed

**Comment by ArthurHoaro** [comment]
I'll try do something about it.

**Comment by ArthurHoaro** [comment]
I don't know for you guys, but `autoLocale()` doesn't work at all. My browser (firefox, Fedora) sends `fr,en-us` in header request and neither are valid parameter for [setlocale](http://php.net/setlocale). I'll work on that first.

**Comment by nodiscc** [comment]
Fixed in https://github.com/shaarli/Shaarli/commit/bec18701801cc140d760c261dd115fda1507a0dd (and 3 next commits...)
