### ISSUE TITLE
[bug] I've got a 500 when addind a link

### ISSUE THREAD

**Issue by aledeg** [shaarli/Shaarli#1440]
I've got a 500 error when adding the following link: https://i.redd.it/0xcb7qimhlt21.jpg
Probably because of `0x` in the name of the file.
I am using the 0.11.0 version of Shaarli

**Comment by nodiscc** [comment]
Hi @aledeg, what operating system and webserver are you using?

please post your  your webserver logs at the time of the error, and errors appearing in your web browser console, if any.

**Comment by aledeg** [comment]
I am not sure of the OS since it's a shared host. It's Linux but I don't know which flavor.
The web server is Apache but again I don't know which version.

There is no error in the browser console. But I've got the following error while trying to link the file.

```
ModSecurity: Access denied with code 418 (phase 1). Pattern match "(?i:(?:\\\\A|[^\\\\d])0x[a-f\\\\d]{3,}[a-f\\\\d]*)+" at ARGS:post. 
```

And now, I know that the error has nothing to do with shaarli.

**Comment by nodiscc** [comment]
Your web host has set up [modsecurity](https://en.wikipedia.org/wiki/ModSecurity) on their server, which flags this particular URL (`...0x...`) as malicious and blocks the request. You should get in touch with them to whitelist this URL, or change their modsecurity policy/rules, I don't know if this is possible.
