### ISSUE TITLE
Error 500 -> search: add page asking for php extensions

### ISSUE THREAD

**Issue by dhoko** [shaarli/Shaarli#1441]
:wave: 

I found a 500 when I tried to search something.

```shell
[Wed Apr  1 11:31:47 2020] 127.0.0.1:48890 [500]: /?searchterm=vim - Uncaught Error: Call to undefined function mb_convert_case() in /home/dhoko/dev/utils/shaarli/application/LinkFilter.php:183
Stack trace:
#0 /home/dhoko/dev/utils/shaarli/application/LinkFilter.php(85): LinkFilter->filterFulltext('vim', 'all')
#1 /home/dhoko/dev/utils/shaarli/application/LinkDB.php(444): LinkFilter->filter('vuo\x7Ftext', Array, false, 'all', false)
#2 /home/dhoko/dev/utils/shaarli/index.php(1638): LinkDB->filterSearch(Array, false, '', false)
#3 /home/dhoko/dev/utils/shaarli/index.php(500): buildLinkList(Object(PageBuilder), Object(LinkDB), Object(Shaarli\Config\ConfigManager), Object(PluginManager), Object(Shaarli\Security\LoginManager))
#4 /home/dhoko/dev/utils/shaarli/index.php(1594): showLinkList(Object(PageBuilder), Object(LinkDB), Object(Shaarli\Config\ConfigManager), Object(PluginManager), Object(Shaarli\Security\LoginManager))
#5 /home/dhoko/dev/utils/shaarli/index.php(1915): renderPage(Object(Shaarli\Config\ConfigManager), Object(PluginManager), Object(LinkDB), Object(History), Objec in /home/dhoko/dev/utils/shaarli/application/LinkFilter.php on line 183
```

I know why, because of this https://shaarli.readthedocs.io/en/master/Server-configuration/#shaarli

It would be a nice feature to see what's mandatory when we first load it or when we try to use a feature using an ext.

Ex: I don't have php-mbstring i try to search -> I see the page with an emphasis on mbstring.

What do you think?

**Comment by nodiscc** [comment]
Hi @dhoko,

what operating system and webserver (+ versions) are you using?

What's the output of `php -m`?

**Comment by dhoko** [comment]
@nodiscc it's not an issue anymore but more a feature we could have inside Shaarli.
I found how to fix the 500 itself it on my side via https://shaarli.readthedocs.io/en/master/Server-configuration/#shaarli 

A page missing dependencies.

**Comment by nodiscc** [comment]
I'm reworking/clarifying documentation as part of https://github.com/shaarli/Shaarli/pull/1389. Please let me know if you see anything missing from the docs after #1389 is merged. Thanks!
