### ISSUE TITLE
"Wrong Token" when using Pin feature

### ISSUE THREAD

**Issue by hobbesjaap** [shaarli/Shaarli#1443]
New user here. Recently set up Shaarli on my Synology using Docker (I'm on the latest Shaarli/shaarli docker running version 0.11.2). I'm running a Reverse Proxy for HTTPS access. Things are working absolutely fine. I've set custom headers for X-Forwarded-For, X-Forwarded-Proto & X-Real-IP. I've also added my Synology proxy (127.0.0.1) to the trusted_proxies setting in config.json.php

This means for example that the ShaarliOS app on iOS is now working splendidly, whereas before it was not.

The only, only feature currently not working smoothly is the Pin feature.

1. When I pin a link, Firefox gives me a "Corrupted Content Error".2. 
2. When I click "Try again" it gives me a white page with the text "Wrong token".4. 
3. When I then load into Shaarli again, the post is pinned.
4. If I unpin, the same error occurs. If I then load Shaarli again, it's unpinned.

Any help available for this rather particular error? Is this just my installation or a common situation with the current version?

**Comment by nodiscc** [comment]
Hi @hobbesjaap,

please post your webserver logs at the time of the error, and error messages appearing in the browser console, if any.

**Comment by hobbesjaap** [comment]
When I check the Docker log, this is sent back:
`"GET /?do=pin&id=126&token=b0c0da934813fda2f7707c15c003ba12b661173d HTTP/1.1" 302 5 "https://my.domain.me:1234/?" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/605.1.15 (KHTML, like Gecko) Version X`

This is when I click the pin action. I've tried Safari here because it show in more detail that, when I pin, it seems to pin successfully, then attempts to redirect me to https://localhost instead of the Shaarli URL. When I then go back to my Shaarli URL myself, the pin is there. So pinning seems to be work just fine, it's the URL referrer after that.

Is there a configuration file somewhere within the Docker I should modify to change "localhost" to my actual domain?

**Comment by nodiscc** [comment]
@hobbesjaap do you still have this problem?

**Comment by soundneedle** [comment]
> When I check the Docker log, this is sent back:
> `"GET /?do=pin&id=126&token=b0c0da934813fda2f7707c15c003ba12b661173d HTTP/1.1" 302 5 "https://my.domain.me:1234/?" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/605.1.15 (KHTML, like Gecko) Version X`
> 
> This is when I click the pin action. I've tried Safari here because it show in more detail that, when I pin, it seems to pin successfully, then attempts to redirect me to https://localhost instead of the Shaarli URL. When I then go back to my Shaarli URL myself, the pin is there. So pinning seems to be work just fine, it's the URL referrer after that.
> 
> Is there a configuration file somewhere within the Docker I should modify to change "localhost" to my actual domain?

I'm getting the same. Pin takes me to local host. Unable to find any config file to redirect.

**Comment by ArthurHoaro** [comment]
Shaarli relies on `SERVER_NAME` parameter which is defined by the web server to determine its URL, or `HTTP_X_FORWARDED_HOST` if available. If you are redirected to localhost, you are probably behind a reverse proxy which does not add the forwarded host header.

Please check https://shaarli.readthedocs.io/en/master/docker/reverse-proxy-configuration/

**Comment by hobbesjaap** [comment]
Dear Arthur, that worked a treat, thank you! I set up two more additional headers in my Synology reverse proxy:

X-Forwarded-Host & HTTP-X-FORWARDED-HOST both pointing to $http_host and now the pinning feature is working correctly. Thank you again!

**Comment by ArthurHoaro** [comment]
You're welcome!
