### ISSUE TITLE
Broken datastore decode command

### ISSUE THREAD

**Issue by immanuelfodor** [shaarli/Shaarli#1445]
I had a link export script that made use of the published datastore decode one-liner that is now broken after updating to the latest master from an old last October Shaarli version.

https://shaarli.readthedocs.io/en/master/guides/various-hacks/

```bash
/var/www/shaarli # php -r 'print(json_encode(unserialize(gzinflate(base64_decode(preg_replace("!.*/\* (.+) \*/.*!", "$1", file_get_contents("data/datastore.php")))))));' | jq .
{
  "__PHP_Incomplete_Class_Name": "Shaarli\\Bookmark\\BookmarkArray"
}
```

Could you please update it in a way that is compatible with the above example? I also fed the JSON output to jq to do various tasks with the links and their metadata, so it would be great to have the same JSON structure.

**Comment by nodiscc** [comment]
Well, I had no idea this was still working... we should update it or remove it.

In the mean time you could use the REST API (https://shaarli.github.io/api-documentation/) and output to json. Really easy to get started with https://github.com/shaarli/python-shaarli-client

**Comment by immanuelfodor** [comment]
Wow, I was not aware that the Python CLI existed, now it's just `shaarli get-links --limit all`, and I get back the same JSON data. Thanks!

**Comment by nodiscc** [comment]
I removed the obsolete datastore decode command in https://github.com/shaarli/Shaarli/pull/1389 (not merged yet). Please let us know you see something missing from the documentation after #1389 is merged. Thanks!
