### ISSUE TITLE
How to create tag from folder structure ?

### ISSUE THREAD

**Issue by Yannovitch** [shaarli/Shaarli#1449]
Hello everybody, bonjour tout le monde !

I've been collecting bookmarks for more than 10+ years, resulting in a very big collection of bookmarks (40.000+) (resulting too in very big bookmarks.html files lately, I don't know why suddenly my bookmarks.html weight now more than 100MB, but that's an other concern...)

My bookmarks are very well organized in a folder structure in Firefox, corresponding generally to the theme of the bookmark (For example, "Shaarli Documentation" in "Bookmark" folder which is in an other folder for all things related to homecomputing, ...)

If I understand correctly, if I want to migrate my bookmarks to Shaarli, instead of a folder structure, I need a tag structure.

**As such, what I would like to do is to add automatically a tag to a bookmark corresponding to the folder it is in, and if possible, in a nested way.
Example : If "Shaarli Documentation" bookmark is in "Bookmark" folder which is in "thinc.sh" folder, I would like to automatically add "Bookmark" and "thinc.sh" tags to "Shaarli Documentation" bookmark.**

I have wanted to migrate my bookmarks to Shaarli for a very long time, but due to the huge size of my bookmark collection, I can't possibly re-add manually tags for each bookmark, so I left the switch for an other time ... until now.

Has anybody done that or had this problem/usecase ?

All the best to you,

Yann

**Comment by nodiscc** [comment]
@Yannovitch Hi, have you tried? It should work as you described

**Comment by Yannovitch** [comment]
> 
> 
> @Yannovitch Hi, have you tried? It should work as you described

Hi @nodiscc , I don't understand what you mean by "it should work as you described" ? What should work as I described ?
I'm asking how I can automatically add a tag to a bookmark corresponding to the folder it is in ?
Do you know of any tool, script or software which can do that ?

**Comment by cy7yz2rj** [comment]
>  (resulting too in very big bookmarks.html files lately, I don't know why suddenly my bookmarks.html weight now more than 100MB, but that's an other concern...)

Close Firefox, open its profile directory in your file manager, delete `favicons.sqlite`, open Firefox and export your bookmarks. The bookmarks.html file should be significantly smaller.

If you want to preserve the favicons, instead of deleting the SQLite file permanently you should move it outside the Firefox profile folder, then after exporting your bookmarks and closing Firefox, copy it back in.

Now for your main question: Shaarli already does what you want, export your bookmarks from Firefox and import the bookmarks.html file into Shaarli, and each bookmark should be tagged by the combination of its Firefox tags and Firefox folder structure.

**Comment by nodiscc** [comment]
>> what you mean by "it should work as you described" ?

> Shaarli already does what you want, export your bookmarks from Firefox and import the bookmarks.html file into Shaarli, and each bookmark should be tagged by the combination of its Firefox tags and Firefox folder structure.

Thanks @cy7yz2rj that's what I meant. I added this feature to the docs [here](https://github.com/shaarli/Shaarli/commit/bf1f3cc07d372c9487e4f28a2383e788c49034df)

@Yannovitch does this answer your question?
