### ISSUE TITLE
Manage tags with space

### ISSUE THREAD

**Issue by alexisju** [shaarli/Shaarli#145]
Managing tags with spaces can be usefull :

1. more user friendly even if this imply to manage tags differently: with tabs, comma, or semicolon for example.

2. It could also resolve a little bug when you try to save a tag with a comma. (For now this shows empty tags associated with the link - but if you have js enabled maybe you have never seen that.)

3. Managing that could also permit to import corectly links+tags from delicious (as you can imagine, for now, tags with space from delicious are managed as severals tags)... 

http://sebsauvage.net/wiki/doku.php?id=php:shaarli:discussion#comment_1de251b8b80759ca538b48ba57fff4fa

**Comment by ArthurHoaro** [comment]
It might be solved soon since we're currently working on a new tag system. See #49 for more information.

**Comment by alexisju** [comment]
Great! :-)

**Comment by nodiscc** [comment]
Sorry to disappoint, we won't allow spaces in tags. This has been discussed here: https://github.com/shaarli/Shaarli/issues/70. Space will remain a tag separator.

Does anyone still use delicious? If yes, we could fix the import code.

**Comment by nodiscc** [comment]
@alexisju 

> For now this shows empty tags associated with the link - but if you have js enabled maybe you have never seen that

Jamais vu ce bug. C'est quoi?

**Comment by alexisju** [comment]
En enregistrant un lien avec un ou plusieurs tags avec une ou plusieurs virgules : le lien sera enregistré avec plusieurs tags vides. 

Je ne rencontre pas ce problème au quotidien, depuis le temps que j'utilise shaarli, mais au début, j'avais souvent le réflexe de séparer mes tags avec des virgules (habitudes prises sur d'autres sites comme delicious ou scoopit pendant des années).

L'autocompletion contourne ce problème, mais avec le javascript désactivé, les virgules peuvent être facilement enregistrées. Et sans le JS, contrairement à ce qui est dit ici https://github.com/shaarli/Shaarli/issues/70#issuecomment-66472611, les virgules ne fonctionnent pas comme des espaces.
On peut toujours reproduire ce bug avec l'index en 0.0.43

Alors pourquoi cette demande?

Désolé de rouvrir le sujet (et en français) qui, effectivement est le même que https://github.com/shaarli/Shaarli/issues/70 , mais pour moi, le principal argument en faveur des tags avec espace, c'est d'être pus proche du langage naturel. 

Un exemple? Quand je souhaite entrer une expression avec une apostrophe, un tag comme  "droit d'auteur", les alternatives sans espaces, soient-disant plus pratiques, ne me conviennent pas vraiment,  "droitDauteur"? "droitdAuteur"? "droit_d_auteur"? "droit_dauteur" 

Il y a beaucoup d'expressions toutes faites qui ont une valeur sémantique telles qu'elles.

Dans mon exemple, le tag "droit d'auteur" n'a pas la même signification que "droit+auteur" ou "droit_auteur" et quand bien même je me plie à cette logique depuis que j'utilise shaarli, cette logique des tagssansespaces, m'est toujours (un peu) désagréable.

**Comment by nodiscc** [comment]
> Et sans le JS, contrairement à ce qui est dit ici #70 (comment), les virgules ne fonctionnent pas comme des espaces.

Si c'est le cas c'est pas très bien. Je regarderai. Peut être faire le changement de lib d'autocompletion avant.

> les alternatives sans espaces, soient-disant plus pratiques, ne me conviennent pas vraiment
> cette logique des tagssansespaces, m'est toujours (un peu) désagréable.

Comme dit dans #70:

 * C'est simple. Pas besoin de se souvenir si le séparateur est espace virgule point virgule. C'est espace.
 * Faire ce changement casserait les habitudes de *tous* les utilisateurs de shaarli habitués à espace. Perso je me ferais avoir à chaque fois et j'entrerais des des tags comme ` dev games hardware history lecture wtf`
 * Oui ça oblige à se trouver une convention et à s'y tenir (mots attachés, `_`, `-`, `:`). Je vois que utilises déjà beaucoup le casing dans tes tags. Perso j'ai essayé, je devenais fou. Ca oblige à être très attentif tout le temps, à corriger, à se souvenir où est la deuXième majuscule, à jongler avec Maj. Lié à ahttps://github.com/shaarli/Shaarli/issues/146. Je mets toutattachéenminuscule. On s'habitue et ça simplifie la vie à la saisie et pendant la recherche.

C'est le genre de chose qu'on pourrait ajouter au wiki en une ligne.

**Comment by ArthurHoaro** [comment]
Désolé pour la réponse rapide, je ne connaissais pas l'existence de #70. :/
