### ISSUE TITLE
Error 500 on login

### ISSUE THREAD

**Issue by oktomus** [shaarli/Shaarli#1452]
Hi everyone. Every time, I go on Shaarli and login, I get a blank page on `/?do=login`. I need to manually go back to `/` to access the website.

Shaarli version: 0.11.1 https://shaarli.oktomus.com/

When logging in, I get an error 500:

![image](https://user-images.githubusercontent.com/4656466/81348040-9f0efe00-90bd-11ea-9385-5d7f5aa54de0.png)

![image](https://user-images.githubusercontent.com/4656466/81347894-535c5480-90bd-11ea-80de-eace86b3da9c.png)

Cookies:
```txt
shaarli | "xxxxxxxxxxxxx"
-- | --
shaarli_staySignedIn | "false"
```

![image](https://user-images.githubusercontent.com/4656466/81348026-99b1b380-90bd-11ea-9674-b25aede960c7.png)

Also, I checked `Remember me` but as you can see, `shaarli_staySignedIn` is `false`.

Any idea of what's happening and when I could try to do to fix this ?

Side question : when there will be a new release with last changes ?

**Comment by notarobot63** [comment]
Hello @oktomus 
I step upon your issue and it remind me of a problem I had: 
Check that your data directory is accessible and writable by your web server's user 
Also are you running Shaarli in Docker ?

**Comment by oktomus** [comment]
Thanks that helped ! Now it's easier to log in :) 
Although I didn't do it the safe way:

```sh
$ ls -la data
total 52
drwxr-xrwx  2 oktomus  oktomus   4096 May  8 11:52 .
drwxr-xr-x 13 oktomus  oktomus   4096 Aug  3  2019 ..
-rw-r--rw-  1 oktomus  oktomus    352 Aug  3  2019 .htaccess
-rw-r--rw-  1 www-data www-data  2122 Feb 17 13:55 config.json.php
-rw-r--rw-  1 www-data www-data 16171 May  7 23:42 datastore.php
-rw-r--rw-  1 www-data www-data   411 May  7 23:42 history.php
-rw-r--r--  1 www-data www-data    67 May  8 11:52 ipbans.php
-rw-r--rw-  1 www-data www-data     6 May  7 11:55 lastupdatecheck.txt
-rw-r--rw-  1 www-data www-data  3303 May  8 11:52 log.txt
-rw-r--rw-  1 www-data www-data   534 Feb 17 13:55 updates.txt
```

No I'm not using Docker.

**Comment by oktomus** [comment]
Is this better ?

```sh
$ sudo ls -la data
total 52
drwxr--r--  2 www-data www-data  4096 May  8 11:52 .
drwxr--r-- 13 www-data www-data  4096 Aug  3  2019 ..
-rwxr--r--  1 www-data www-data   352 Aug  3  2019 .htaccess
-rwxr--r--  1 www-data www-data  2122 Feb 17 13:55 config.json.php
-rwxr--r--  1 www-data www-data 16171 May  7 23:42 datastore.php
-rwxr--r--  1 www-data www-data   411 May  7 23:42 history.php
-rwxr--r--  1 www-data www-data    67 May  8 11:57 ipbans.php
-rwxr--r--  1 www-data www-data     6 May  8 11:57 lastupdatecheck.txt
-rwxr--r--  1 www-data www-data  3357 May  8 11:57 log.txt
-rwxr--r--  1 www-data www-data   534 Feb 17 13:55 updates.txt
```

**Comment by notarobot63** [comment]
Awesome glad I could help.! 
Your first example is what I have on my instance, but I'm no security expert.

**Comment by oktomus** [comment]
Thanks a lot :)

**Comment by nodiscc** [comment]
I am currently redoing the file permissions setup documentation (https://github.com/shaarli/Shaarli/pull/1389):
 - https://shaarli.readthedocs.io/en/doc-rework-setup/Installation/#set-file-permissions
 - https://shaarli.readthedocs.io/en/doc-rework-setup/dev/Development/#directory-structure

> Shaarli needs read/write access to the cache/, data/, pagecache/, and tmp/ directories

That was it! Thank you
