### ISSUE TITLE
[Question] Only show login form for anonymous users

### ISSUE THREAD

**Issue by lonix1** [shaarli/Shaarli#1457]
I want to run shaarli in private mode, not open to the public.

The docs said that I can show the login form to anonymous users by setting this config:
````json
"privacy": {
        "hide_public_links": true,
        "force_login": true,
    },
````

But lots of stuff is still visible, and unnecessary (vector for future bugs as well). For example: tags, daily, rss, search,etc.

How can I disable everything, except the login form?

**Comment by ArthurHoaro** [comment]
I don't think it's possible, as the login form anonymous users are redirected to is the same as the one they would see without this setting.

I don't really understand the issue here, as nothing is accessible, and every link redirects to the login form.

**Comment by lonix1** [comment]
Just a question, not really a problem.

In most apps if you are not logged in, all the other options are not available. Someone will make a PR one day and blow up the security, somehow. It's just asking for trouble... 😈

However thanks for confirming it's not possible. I thought there may be a setting or something.
