### ISSUE TITLE
Makefile: remove static_analysis_summary from all: target

### ISSUE THREAD

**Issue by nodiscc** [shaarli/Shaarli#1459]
`static_analysis_summary` was removed in https://github.com/shaarli/Shaarli/commit/37c9c6b4e62ba25f889ebb6486fe5c442acc9095#diff-b67911656ef5d18c4ae36cb6741b7965 but not from the `all:` target dependencies. Therefore running `make all` always fails.

**Comment by ArthurHoaro** [comment]
Are you working on this, or would you rather push the milestone or unassign this issue?

**Comment by nodiscc** [comment]
I will do it tomorrow, easy enough
