### ISSUE TITLE
Installing Shaarli on a Free server: error 500

### ISSUE THREAD

**Issue by YotaMoteuchi** [shaarli/Shaarli#1469]
Hello.

I'm trying to install shaarli on a personal page hosted by free.fr.
Nevertheless, when I reach the shaarli page, I have an error 500.
Despite the subjects found on the web, I couldn't resolve my issue ; by the way, I saw some Shaarli users hosted on free.fr, so I guess it's possible.
Could you please help me?
Which details can I provide to you for helping me?

Thanks in advance.
Yota

**Comment by agentcobra** [comment]
Hi @YotaMoteuchi,
You need to activate PHP5.
http://agentcobra.online.fr/blog/index.php/2015/10/php-5-6-arrive-chez-free.html
Best regard
agentcobra

**Comment by YotaMoteuchi** [comment]
Thanks for this first answer, @agentcobra.
My .htaccess is well configured with this command line. I also created the sessions and tmp directories to the root of my site.
Nevertheless, the same error 500 message appears.

Best regards,
Yota

**Comment by ArthurHoaro** [comment]
Hi, if you have 500 errors, you should have more details in your web server logs. Can you post them?

Note that the latest versions of Shaarli are no longer compatible with PHP5. Please check out the compatibility table here: https://shaarli.readthedocs.io/en/master/Server-configuration/

**Comment by YotaMoteuchi** [comment]
Hi Arthur.
You're right; so I installed the version 0.10.4 because Free accepts only PHP5.6.
Nevertheless, even with this installation i only have a "error 500" again.
And I don't know how to check the server logs with Free.

Best regards,
Yota

**Comment by agentcobra** [comment]
it's maybe a problem with your .htaccess file.

try just with :
```
<IfDefine Free>
php56 1
</IfDefine>
```

**Comment by YotaMoteuchi** [comment]
Hi Agentcobra.
I already followed your advice earlier, so the issue is not here.

**Comment by agentcobra** [comment]
I'm asking because Shaaeli provide this file : https://github.com/shaarli/Shaarli/blob/master/.htaccess

**Comment by YotaMoteuchi** [comment]
If I remove the .htaccess file in the Shaarli folder or if Replace it with the three lines above, I have another error message:
**Fatal error:** require(): Failed opening required '/var/www/sda/6/d/leyotademars/shaarli-leyotademars/vendor/composer/../nikic/fast-route/src/functions.php' (include_path='/var/www/sda/6/d/leyotademars/include:.:/usr/php5/lib/php') in **/var/www/sda/6/d/leyotademars/shaarli-leyotademars/vendor/composer/autoload_real.php** on line **66**

**Comment by YotaMoteuchi** [comment]
Here is the resolution of my issue.

Indeed, there were many issues:
- Free servers only use PHP 5.6, so the version 0.11 can't be installed.
- The .htaccess needed to be reconfigured;
- And, my PERSONAL issue was that Filezilla was wrongly configured: Free limits the number of connections to 2; I didn't configured Filezilla for that and many files were missing in the Shaarli directory.

How to resolve them:
- In Filezilla, in the tab "Transfert parameters", limit the connections to 2 ;
- Install the Shaarli v0.10.4 provided here : [https://github.com/shaarli/Shaarli/releases/tag/v0.10.4](https://github.com/shaarli/Shaarli/releases/tag/v0.10.4).
- Remove the .htaccess file in the Shaarli directory;
- Configure the ROOT .htaccess file of your site with the follwing:
```
<IfDefine Free>
php56 1
</IfDefine>
<Files ".ht*">
Order allow,deny
Deny from all
Satisfy all
</Files>
Options -Indexes
```

And voilà ! ^^

**Comment by nodiscc** [comment]
Well done! I updated PHP 5.6/free.fr compatibility docs: https://github.com/shaarli/Shaarli/commit/502b2851836afb957a6d4fafbdc81303623b50fb. It will be available when I finalize https://github.com/shaarli/Shaarli/pull/1389/

> Free limits the number of connections to 2; I didn't configured Filezilla for that

Well this was not obvious :) I think it might have something to do with incomplete/corrupted files reported in other issues.

Thank you all
