### ISSUE TITLE
Use awesomplete as autocompletion JS lib

### ISSUE THREAD

**Issue by ArthurHoaro** [shaarli/Shaarli#148]
The idea is to remove jQuery dependency in Shaarli. The last usage of jQuery we have is for tags autocompletion. We kinda agree to use [awesomplete](https://github.com/LeaVerou/awesomplete). It's light, has no dependency and seems to work pretty well. You can find [a demo here](https://leaverou.github.io/awesomplete/#advanced-examples).

Discussion about autocomplete has been running in other issues: #49 #92 #118 #146 #70 #145 

I suggest we centralize discussion in this issue.

**Comment by ArthurHoaro** [comment]
After a few tests based on LeaVerou/awesomplete#14184, it seems I can't use a space delimiter, since the lib uses `,` as default. I'll see if I can do something about it.

**Comment by nodiscc** [comment]
Forwarded from https://github.com/shaarli/Shaarli/pull/165

>Another possible improvement is to use Tab or Left Arrow keys to add the selected suggestion to the contents of the field.

>Currently it's only the Enter key and can cause mistakenly triggering "Save" when you're not finished editing tags and hit enter when the suggestion doesn't have focus.

**Comment by nodiscc** [comment]
One more thing to investigate: How are the suggestions sorted? Is this part of the awesomplete logic, or are they show in the order they are listed in the `datalist` ? Eg if I enter the characters `ss` in the tag entry field, I get these suggestions in this order:

```
css
rss
ssh
russia
classical
passwords
```

I'd expect to have words _starting_ with my input to show first in the list (in this case `ssh` and `ssl`)

**Comment by ArthurHoaro** [comment]
They're sorted by length. We can't add a function setting for sorting, but it only allows us to sort items between each other without getting the user input (as far as I can understand JavaScript). I believe we need to open an issue on awesomplete repo and/or work on it ourself.

**Comment by ArthurHoaro** [comment]
About using Tab and right arrow to select an item, it's also dependent to the lib but we can change that easily [here](https://github.com/LeaVerou/awesomplete/blob/gh-pages/awesomplete.js#L70) and send a PR to add it in awesomplete settings.

**Comment by nodiscc** [comment]
Issue fixed thanks to @ArthurHoaro. Remaining points (sorting, using another key such as Tab) can be discussed in new issues if it proves really annoying in the long term. Let's go with the defaults and see how it goes.
