### ISSUE TITLE
No thumbnail could be found using default finder:

### ISSUE THREAD

**Issue by quantitative-technologies** [shaarli/Shaarli#1482]
I get the message: 

There is no cached thumbnail. Try to synchronize them. 

in my Picture Wall. When I click synchronize, it gets stuck. I see the following messages for each bookmark in the shaarli-error.log:

[Fri Jun 05 00:11:13.101880 2020] [php7:notice] [pid 3839166] [client 127.0.0.1:54280] No thumbnail could be found using default finder: https://coinsquare.com, referer: https://127.0.0.1/?do=thumbs_update

Version: Shaarli 0.11.1

**Comment by ArthurHoaro** [comment]
I don't know what could cause your issue. If I try this link on the demo instance, the thumbnail is properly retrieved.

Do you have a specific server setup? Do you have `php-curl` extension installed?

**Comment by quantitative-technologies** [comment]
I tried to install apache2 according to the Shaarli instructions. I did not have `php-curl` because it was only suggested. However, after installing it I'm still having the issue. Here is a screenshot of where it gets stuck: [image](https://ibb.co/CmQZBzs)

**Comment by ArthurHoaro** [comment]
Actually, I don't think it gets stuck on your screenshot, it's just a counter  intuitive UI because there is no success message. We can improve that.

Can you confirm that you have no thumbnail retrieved at all?

**Comment by quantitative-technologies** [comment]
Before installing `php-curl` there were no thumbnails on my bookmark page. After installing it, newly added bookmarks have a thumbnail, but older bookmark have to be deleted and re-added to get a thumbnail. So I think `php-curl` should be considered a requirement.

However, my Picture Wall is still blank. I think I am now in the situation of issue #1357, but I haven't had a chance yet to look into the fixes there.

**Comment by nodiscc** [comment]
> I think php-curl should be considered a requirement.

php-curl is marked optional in https://shaarli.readthedocs.io/en/master/Server-configuration/, thumbnails should also work without it (https://github.com/ArthurHoaro/web-thumbnailer#requirements). Do they not?

Do you have related messages in your webserver logs?

> older bookmark have to be deleted and re-added to get a thumbnail

You can force a synchronization by going to _Tools > Synchronize thumbnails_ (/?do=thumbs_update)

> my Picture Wall is still blank / #1357 
>>You can work this around by adding in your user.css:

```css
.b-lazy {
  min-width: 1px;
  min-height: 1px;
}
```

**Comment by ArthurHoaro** [comment]
> Do they not?

It does work without php-curl, I tried it the other day. However PHP built-in `file_get_contents()` can be less reliable with external resources, so there might be an issue with your web server set up.

On Thu, Jun 11, 2020, at 19:28, nodiscc wrote:
> 

>> I think php-curl should be considered a requirement.

> php-curl is marked optional in https://shaarli.readthedocs.io/en/master/Server-configuration/, thumbnails should also work without it (https://github.com/ArthurHoaro/web-thumbnailer#requirements). Do they not?

> Do you have related messages in your webserver logs?

>> older bookmark have to be deleted and re-added to get a thumbnail

> You can force a synchronization by going to *Tools > Synchronize thumbnails* (/?do=thumbs_update)

>> my Picture Wall is still blank / #1357 <https://github.com/shaarli/Shaarli/issues/1357>

>>> You can work this around by adding in your user.css:

> .b-lazy {
  min-width: 1px;
  min-height: 1px;
}

**Comment by ArthurHoaro** [comment]
I'm closing old issues tagged support which are likely outdated. If you feel like this should stay open, please say so.

**Comment by quantitative-technologies** [comment]
Yes, everything was working perfectly, but I cannot recall what fixes I did.
