### ISSUE TITLE
Login page disappear

### ISSUE THREAD

**Issue by ChengxiX** [shaarli/Shaarli#1483]
Shaarli runs on my server, I just download it but there is not login page.
"
Not Found
The requested URL was not found on this server.
"

**Comment by nodiscc** [comment]
Hi @ChengxiX please add the following information:

 - operating system and version
 - web server/PHP version
 - which method did you use to install shaarli
 - webserver access and error logs

**Comment by ChengxiX** [comment]
I can't find my login page in the folder. I am trying to download shaarli on release page.

Windows10 x64 on Azure, Apache + PHP7.2.31  
I install it from release ZIP

**Comment by ChengxiX** [comment]
I have fixed this problem by getting shaarli from the release page. 
Thanks! : )
