### ISSUE TITLE
 traefik error in docker

### ISSUE THREAD

**Issue by AylaMeo** [shaarli/Shaarli#1493]
I'm not sure if this applies to Debian9 which the guide is for after all but on Debian10 traefik errors (the error being `command traefik error: failed to decode configuration from flags: field not found, node: acme`) due to changes in the newest version, however specifying `image: traefik:1.7-alpine` fixed it, should a note about this be added to the documentation?

**Comment by nodiscc** [comment]
I just reproduced the problem. The docker-compose/traefik-based install procedure had not been tested for a while, thanks for reporting. We need to pin the [traefik](https://hub.docker.com/_/traefik/) image to `1.7-alpine`.
