### ISSUE TITLE
Template file for individual permalink page

### ISSUE THREAD

**Issue by efeefe** [shaarli/Shaarli#1498]
Can someone please point me to the template file I should edit in order to change the individual permalink page?

**Comment by ArthurHoaro** [comment]
There is no dedicated template file for permalinks, it is `linklist.html` with a single entry.

**Comment by efeefe** [comment]
Ok, thank you.

**Comment by efeefe** [comment]
It seems it won't be so easy what I'm trying to do: [embed discourse discussions](https://meta.discourse.org/t/embedding-discourse-comments-via-javascript/31963) to individual entries. Have you seen that being done anywhere? 

BTW, congratulations for Shaarli, I'm happily hosting a links of bookmarks I've been maintaining for 15+ years since the age of delicious...

**Comment by lisandrodemarchi** [comment]
Maybe there is a more straightforward alternative, but you can add content only visible in individual entries/permalinks with a conditional like this in your linklist.html template:

```
{if="count($links) == 1 && empty($search_tags) && empty($search_term)"}
	<!-- Your discourse embed code here  -->
{/if}
```

**Comment by ArthurHoaro** [comment]
You should check out our [Isso plugin](https://github.com/shaarli/Shaarli/tree/master/plugins/isso) which does something similar (adding a comment section on permalinks).

**Comment by efeefe** [comment]
Thanks @lisandrodemarchi and @ArthurHoaro , that seemed to do the trick - but now I'm strugglin on the other end, trying to overcome Discourse's security measures.
