### ISSUE TITLE
Multi user shaarli

### ISSUE THREAD

**Issue by nodiscc** [shaarli/Shaarli#15]
- https://github.com/sebsauvage/Shaarli/issues/98: (Attempt at a multi-user setup)
- https://github.com/sebsauvage/Shaarli/issues/107: Shaarli Multi Utilisateurs

**Note:** work started in https://github.com/shaarli/Shaarli/pull/11 to have configurable `data/`, `tmp/`, `tpl/`.... paths. Going further, we could _(for shaarlis that have optional multiuser enabled)_, have https://my.shaarli.url/u/georges and https://my.shaarli.url/u/john be shorthands for https://my.shaarli.url/?user=georges, let shaarli detect the `user` param, and serve shaarli with different data paths (eg. `$SHAARLI_DATA_DIR/$user`, `$SHAARLI_TPL_DIR/$user`...)

**Comment by poVoq** [comment]
Not even a chance for very basic multi-user? I basically just want to allow other people (2-3) to post on my Shaarli for jointly curating links and notes, but I would prefer them not having full admin access.

**Comment by virtualtam** [comment]
Hi @poVoq,

Long story short, going multi-user requires too many changes to core features of Shaarli, especially how links/notes are handled (storage & code representation). Related work has been planned for (far-)future releases, notably #445 and #953.

In the meantime, the best way to use Shaarli in a social way is to rely on Atom/RSS feeds to aggregate data from several instances.

See also #907 for a related discussion and possible solutions.
