### ISSUE TITLE
[Feature Requests] Named walls | Open links in new tab | Grid layout

### ISSUE THREAD

**Issue by Ezyweb-uk** [shaarli/Shaarli#1501]
It would be great if the following features could be incorporated:
1) Walls that could be named in config to enable further categorization, maybe even a home wall with pinned links
2) A configurable option to open links in a new tab or window
3) A configurable option to display in a grid layout

**Comment by aledeg** [comment]
I think it's better you open one issue per request

**Comment by Ezyweb-uk** [comment]
Following your advice, and closing this one.
