### ISSUE TITLE
API calls returns HTTP 404 even if enabled

### ISSUE THREAD

**Issue by dimtion** [shaarli/Shaarli#1502]
Hi,

I'm going to need some help on this one, I am banging my head for a week trying to reproduce the issue, but with no luck so far.

Since I've upgraded Shaarlier to use Shaarli API I have received numerous reports from people saying that the API is not working for them. Some of those reports are listed in this issue: https://github.com/dimtion/Shaarlier/issues/42

Right now in order to check that the API is supported and enabled, Shaarlier will do a first unauthenticated call to `/api/v1/info` and check that the response is 401, which is the response I get when I test on my local instances (running latest version and master).

For some reason, even if those users swear that the API is activated on their instance, the route `/api/v1/info` always returns HTTP 404 for them, which is interpreted by the app as if the API is disabled. 

I could not reproduce this bug on my side, and reading the API source code I cannot find where this might be coming from. The only lead I have left is assuming that their Apache or Nginx is somewhat miss-configured.

I have seen this report on multiple versions ranging from v0.10.x to v0.11.x. The only correlation I could find is that it seems like many of these reports are running Shaarli on a Raspberry pi, but that might simply be a bias in the userbase.

If anybody have an idea or a procedure that I could send to those users to help them debug the problem that would be a blast.

**Comment by nodiscc** [comment]
Make sure the webserver is properly configured as per https://shaarli.readthedocs.io/en/doc-rework-setup/Server-configuration/#examples, notably `mod_rewrite` on Apache **must** be loaded for API routes to work.

**Comment by dimtion** [comment]
Thank you I got it now! It is indeed related to `mod_rewrite`:

If I disable support for `.htaccess`  (by forgetting to add `AllowOverride All`) the API routes won't be rewritten correctly. So many people are forgetting this piece of configuration, I think I'll add a helper in the app to troubleshoot the issue.

I'm not sure if we can do anything on Shaarli's side to improve on that issue, the documentation seemed clear enough for me, there could be more help in the API troubleshooting section, but I guess this is mainly for developers, not users.

**Comment by nodiscc** [comment]
Nice

> the documentation seemed clear enough for me

The docs I have linked are the cleaned up/refactored version found in https://github.com/shaarli/Shaarli/pull/1389 (branch  `doc-rework-setup`). The current/master version is a bit [overly complex](https://shaarli.readthedocs.io/en/master/Server-configuration/) so that should hlep when I finally get some time to finalize it :/

> there could be more help in the API troubleshooting section

Feel free to send a patch against the `doc-rework-setup` branch if you think something is missing (or wait for the merge and we can take another look at this)

**Comment by nodiscc** [comment]
The server configuration docs have been refactored, it is now clearly stated that `mod_rewrite` must be enabled https://shaarli.readthedocs.io/en/master/Server-configuration/
