### ISSUE TITLE
Open links in a new tab [Feature Request]

### ISSUE THREAD

**Issue by Ezyweb-uk** [shaarli/Shaarli#1504]
Unless I've missed something, links only load in the same browser tab. It would be nice if the system could be extended so that link behaviour was a configurable option to open either in the same tab or in a new tab.

**Comment by nodiscc** [comment]
> https://shaarli.readthedocs.io/en/master/Community-&-Related-software/#third-party-plugins
> https://github.com/trailjeep/shaarli-urlextern
> Shaarli plugin to open external links in a new tab/window.
