### ISSUE TITLE
[Feature Request] Shaarli provisioning with pre-defined API token

### ISSUE THREAD

**Issue by yuha0** [shaarli/Shaarli#1507]
Can shaarli load a pre-defined admin user definition and API token from a file or an environment variable instead of generating one by itself on initialization?

Background:

In my environment, I run Shaarli in a stateless fashion. I don't rely on the bookmark data on local filesystem, and instead, there's a process to run reconciliation loops periodically to sync bookmark data between shaarli and a "database" (if it sees differences between Shaarli and the database, it wipes out Shaarli local data and re-inserts all bookmarks in the database to Shaarli through Shaarli's API). This enables us to run Shaarli in HA mode -- multiple Shaarli instances can be setup behind a load balancer.

Now the problem is, when a Shaarli instance starts, if it does not see any data on the filesystem, it initializes as a brand new instance (which is what it should do), but I have to login onto that instance and manually create a user and get the API token. This prevent us from autoscaling number of Shaarli instances in the cluster.

**Comment by ArthurHoaro** [comment]
Thanks for your background use case, that's interesting. Shaarli relies entirely on local files, which does not necessarily make it multiple instances friendly.

Going back at your request, couldn't you just deploy your `config.json.php` with pre-configured credentials and API key through all of your instances?

**Comment by yuha0** [comment]
Thank you for the suggestion. However it is not an option for me. 

In my project, I don't consider a configuration file to be a "secret" because configuration should not contain sensitive information. 

A bit more about my background: Shaali is deployed in Kubernetes so I get load balancing and HA for free. In Kubernetes, there's a very clear concept distinction between configuration ([ConfigMap](https://kubernetes.io/docs/concepts/configuration/configmap/) object) and secret information ([Secret](https://kubernetes.io/docs/concepts/configuration/secret/) object).

If password and API token can be loaded from anywhere than the config file (be it a separate file, or environment variables...or anything), my setup will work reliably.

**Comment by nodiscc** [comment]
> In Kubernetes, there's a very clear concept distinction between configuration (ConfigMap object) and secret information (Secret object).

Are you sure there is no possibility to do any kind of templating in k8s? Like inserting a secret variable into a configuration?

That seems a very harsh limitation, as most software will embed sensitive/secret values or credentials in their config files. Docker Swarm has the same concept of `docker secrets` and `docker configs`, which have never worked for me as they should (when forced :gun: to use Docker I just use `secrets` for everything, or plain binds from the filesystem and appropriate permissions)... of course for this you need some kind of provisioning system like ansible and then we're back at square one (your infrastructure is not pure containers/clouds and unicorns, you need a template engine, a provisioning system, underlying file systems...).

I think orchestration systems are very detached from the reality of software as it exists, requiring you to rewrite your software specifically for them... man, managing tomcat in Docker and a bunch of stuff loaded from `.properties` files is not fun.

>  If password and API token can be loaded from anywhere than the config file

Yes just as I said :)

> be it a separate file

Then you have to take extra steps to deploy and secure this file...

> or environment variables

Well known security problems [[1](https://stackoverflow.com/questions/10090014/can-i-trust-my-environment-variables)] /accessible/modifiable everywhere inside your container...

Just my 2 cents rant :) I don't think we should add a separate file for "secrets" which increases indirections/complexity for regular users (that and, what values you consider sensitive will depend on your threat model). Instead can you just stash the whole config in a Secret object?

**Comment by yuha0** [comment]
This is understandable. I think I can mess with the entry point script to add a step to `sed` the secrets into the config file on container startup. Thanks!

> Are you sure there is no possibility to do any kind of templating in k8s?
It is possible, but I am doing infrastructure as data, so even if I do templating, I need to check in the templating engine's output files in git. Obviously I should not put password in git in plaintext.

> Then you have to take extra steps to deploy and secure this file...
There are mature solutions like HashiCorp Vault, Bitnami Sealed Secrets that tackle this area. My cluster has one, so `secret` protection comes for free.

**Comment by nodiscc** [comment]
If templating before starting your containers is not an option, then yes, your best bet is probably to replace secrets in the configuration file when the container starts (put a placeholder value in your configuration file/ConfigMap, `sed` it with the value from your Secret object in the entrypoint). This requires maintaining and regularly rebuilding a modified image though (?).

> Obviously I should not put password in git in plaintext.

Better not! I use plaintext templates for configuration files, then secret values/placeholders are replaced with a pre-generated or randomly-generated (at deployment time) secret, which is stored encrypted in the git repo (with a master password / ansible-vault). But then yes, something has to know the vault master password (be it your CI system/machine where the deployment tool runs, or a dedicated secret manager like HashiCorp Vault - which comes with an additional maintenance cost).

This is an interesting topic, feel free to share any details on how/if you got it to work, or other details about your implementation.

Cheers

**Comment by nodiscc** [comment]
@yuha0 are you exporting your API secret to the pod? Environment variable? Mounted in a text file at `/api-secret.txt`? [Other](https://kubernetes.io/docs/concepts/configuration/secret/#use-cases)?

If that's the case, we can modify the Dockerfile/entrypoint so that it replaces the `"api": { "secret":` value with the variable/file contents, if they exist. Then you would just have to mount your template `config.json.php` ConfigMap, declare your Secret file/variable, and let the entrypoint do the replacement.

This would also work for Docker (using `volumes/env/configs/secrets` instead of k8s configmap/secret).

I think we would also need to add replacement/calculation logic for `"credentials":` `login/salt/hash` then?

**Comment by nodiscc** [comment]
No reply, closing. Feel free to reopen, the use case was interesting.
