### ISSUE TITLE
Add github.com with "Shaare link" button doesn't work

### ISSUE THREAD

**Issue by anubister** [shaarli/Shaarli#1509]
Hello
using the javascript snippet button "Shaare link" from github.com projects does nothing (only experience with this website).
Shaarli 0.10.4; Firefox 68.7.0esr (64-Bit)

**Comment by ArthurHoaro** [comment]
> Websites which enforce Content Security Policy (CSP), such as github.com, disallow usage of bookmarklets. Unfortunately, there is nothing Shaarli can do about it.
> [Docs](https://shaarli.readthedocs.io/en/master/Sharing-content/#bookmarklet)

You can use browser extensions instead if you want to.
