### ISSUE TITLE
Nginx config

### ISSUE THREAD

**Issue by efeefe** [shaarli/Shaarli#1510]
Hi there... I'm migrating a Shaarli instance from a server running Apache2 to a new one on nginx and can't get it to work. The nginx section of the [docs](https://shaarli.readthedocs.io/en/master/Server-configuration/) is not that clear. Does anyone have a working, production ready nginx config sample to share?

**Comment by ArthurHoaro** [comment]
I'm using the [docker one](https://github.com/shaarli/Shaarli/blob/master/.docker/nginx.conf) but it's designed to work behind a reverse proxy. So you will need to add server name and SSL certificate if you're not.

**Comment by efeefe** [comment]
Thanks for that. I have other websites in the same VPN, so won't be changing nginx.conf itself but only the vhost in sites-enabled. I'll try to work my way from that one.

**Comment by efeefe** [comment]
Thanks @ArthurHoaro , that did work with minor adjustments.
