### ISSUE TITLE
Is there an open instance of Shaarli somewhere?

### ISSUE THREAD

**Issue by iootaa** [shaarli/Shaarli#1514]
Hi there,

I would love to use Shaarli, but https://my.framasoft.org/ is closed now.

Do you know of another place to get an access to Shaarli without self-hosting it?

Thank you, Cheers

**Comment by iootaa** [comment]
I found [this page on wiki.chatons](https://wiki.chatons.org/doku.php/la_gestion_de_ses_marque-pages_avec_shaarli#instances_publiques_deployees) but the only listed instance is down : (

**Comment by ArthurHoaro** [comment]
I am not aware of open multi-instance platform out there.
From the documentation you can easily deploy Shaarli with Cloudron or Yunohost: https://shaarli.readthedocs.io/en/master/Community-&-Related-software/#integration-with-other-platforms

Note that I have not tested these 3rd party integration myself.
