### ISSUE TITLE
file:// URLs get converted to http://

### ISSUE THREAD

**Issue by cy7yz2rj** [shaarli/Shaarli#1515]
Local URLs added with the "Shaare a new link" page or the Shaarli webextension have the `file://` string replaced by `http://`

Imported bookmarks are stored correctly but clicking the link doesn't do anything.

Editing an existing `file://` bookmark will turn it into `http://`

Tested with Shaarli 0.11.0 and Firefox.

**Comment by ArthurHoaro** [comment]
You can allow to add `file://` URL in your configuration file with the setting `security.allowed_protocols`. It takes a list of allowed protocols in shaare URLs or markdown-rendered descriptions (default: ["ftp", "ftps", "magnet"]).

https://shaarli.readthedocs.io/en/master/Shaarli-configuration/#security

**Comment by cy7yz2rj** [comment]
Thank you, that solves 1 and 3 but not 2: clicking or middle-clicking any `file://` bookmark won't open the page in Firefox like it does for http(s) URLs. Browser issue?

**Comment by nodiscc** [comment]
@cy7yz2rj this is a limitation/security feature of the browser. There seems to be several workaround, I don't know which ones actually work

 - http://kb.mozillazine.org/Firefox_:_Issues_:_Links_to_Local_Pages_Don't_Work
 - https://stackoverflow.com/questions/192080/firefox-links-to-local-or-network-pages-do-not-work
 - http://kb.mozillazine.org/Security.fileuri.strict_origin_policy
 - http://kb.mozillazine.org/Security.fileuri.origin_policy

I recommend caution before disabling this feature in your browser as it could lead to malicious javascript being able to access to your local files.
