### ISSUE TITLE
Test v0.12.0-beta

### ISSUE THREAD

**Issue by agentcobra** [shaarli/Shaarli#1522]
Bonjour,
j'ai cette erreur en voulant tester la béta : 
```
[Thu Aug 27 13:27:14.949380 2020] [proxy_fcgi:error] [pid 1656] [client 172.17.20.1:59232] AH01071: Got error 'PHP message: PHP Fatal error:  Uncaught Error: Class 'Shaarli\\Container\\ContainerBuilder' not found in /var/www/shaarli.agentcobra.net/index.php:71\nStack trace:\n#0 {main}\n  thrown in /var/www/shaarli.agentcobra.net/index.php on line 71\n'
```
https://github.com/shaarli/Shaarli/blob/bea062149ebcb4663861edb1cc0a32faf85b273f/index.php#L71

j'ai aussi un problème pour faire un composer update

```
± |tag:v0.12.0-beta ?:2 ✗| → composer update
Deprecation Notice: The behavior of unparenthesized expressions containing both '.' and '+'/'-' will change in PHP 8: '+'/'-' will take a higher precedence in /usr/share/php/Composer/Downloader/GitDownloader.php:253
Deprecation Notice: The behavior of unparenthesized expressions containing both '.' and '+'/'-' will change in PHP 8: '+'/'-' will take a higher precedence in /usr/share/php/Composer/Downloader/SvnDownloader.php:132
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file


  [ErrorException]
  "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"?


install [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-dev] [--no-custom-installers] [--no-autoloader] [--no-scripts] [--no-progress] [--no-suggest] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--ignore-platform-reqs] [--] [<packages>]...

```

ps : same for composer install

Je suis dispo pour faire d'autre tests

**Comment by ArthurHoaro** [comment]
How did you upgrade? Can you run `composer install`?

**Comment by agentcobra** [comment]
I'm on git
I've done a git fetch origin then git checkout v0.12.0-beta
composer install give the same error
I'v clear also the cache directory

**Comment by ArthurHoaro** [comment]
That's odd. You can still try `composer update` instead but that should not be an issue.

**Comment by ArthurHoaro** [comment]
Which version of PHP and Composer are you using?

**Comment by agentcobra** [comment]
I'm under debian :
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 9.13 (stretch)
Release:        9.13
Codename:       stretch

with php 7.4 : 
PHP 7.4.9 (cli) (built: Aug  7 2020 14:56:37) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.9, Copyright (c), by Zend Technologies

with composer : Composer version 1.10.10 2020-08-03 11:35:19

I'm have just (after opened this issue) upgrade all the system.
The error with composer is gone
Shaarli seem working but link are broken

**Comment by ArthurHoaro** [comment]
If you have some free time can you login to https://gitter.im/agentcobra, it'll be easier.

**Comment by agentcobra** [comment]
I'm on it :)

**Comment by ArthurHoaro** [comment]
Most issues were related to the usage of a custom theme (which requires a bunch of upgrade with v0.12). Thanks for your time!
