### ISSUE TITLE
Login loop, if "force_login": true

### ISSUE THREAD

**Issue by Meuschke23** [shaarli/Shaarli#1533]
Hi!
First of all many thanks for this great tool!

Ive got a problem with the [v0.12.0-beta](https://github.com/shaarli/Shaarli/releases/tag/v0.12.0-beta):
My Shaarli is available at 
```*ROOTURL*/*USERNAME*```. i like to use it as a private instance.

If i set ```"force_login": true,``` in the config, i cannot log in:

```https://*ROOTURL*/*USERNAME*/login?returnurl=%2F*USERNAME*%2F```
becomes
```https://*ROOTURL*/*USERNAME*/login?returnurl=%2F*USERNAME*%2Flogin%3Freturnurl%3D%252F*USERNAME*%252F```

The access data are correct, but no login takes place. If i set ```"force_login": false,```, then everything works.

What can be the cause? Can you help me?

Best regards
Meuschke

**Comment by ArthurHoaro** [comment]
Thanks for the report. `POST /login` now has a distinct route name, which wasn't included in the exceptions, so it was unreachable. #1536 should fix it.

**Comment by Meuschke23** [comment]
👍 Works for me. Thank You!
