### ISSUE TITLE
"Daily" view does not care for privacy

### ISSUE THREAD

**Issue by gruenheit** [shaarli/Shaarli#1543]
Affected Version: Shaarli 0.12.0-beta, Theme: Default

HTD: 
-  (preset) Import some bookmarks from another instance (here: Shaarli v0.11.1) with a couple of new created ones so that they will be displayed in the panel "Daily"

As long as you are logged in everything looks plausible when viewing the panel "Daily"

- Change the visibility of the new created bookmarks to "private"
- logout of shaarli
- click to the view "Daily"

All the above bookmarks are displayed in the "Daily" view, even the ones marked as "private"

**Comment by nodiscc** [comment]
Confirmed on 0.12-0-beta (https://shaarli-next.hoa.ro/daily), not reproducible on 0.11.1

**Comment by ArthurHoaro** [comment]
Good catch, thank you for the report. It should be fixed by #1547
