### ISSUE TITLE
Edit form returnurl parameter is not respected

### ISSUE THREAD

**Issue by immanuelfodor** [shaarli/Shaarli#1545]
Hi, I think I've found an annoying bug with editing shaares. The edit form has a hidden `returnurl` value that is set from the referrer page. It is really useful when you are editing a shaare from search or multiple pages back in history, or you have an open tab for a note and you want to make multiple edits over time. When you're done with the edit, you are usually redirected to the place where you came from. However, now the redirect is always made to https://shaarli.example.com/#RaNDomID which means the main page with a possibly non-existent shaare identifier, so you must find your way back where you were before manually. Please make this redirect work again, it was so useful. I'm using the Material theme with the 0.12.0 support branch if it helps in the debug.

![image](https://user-images.githubusercontent.com/21174107/92324352-30c55280-f041-11ea-8902-511ef703c41e.png)

**Comment by nodiscc** [comment]
> However, now the redirect is always made to https://shaarli.example.com/#RaNDomID which means the main page with a possibly non-existent shaare identifier, so you must find your way back where you were before manually.

It has always been this way for me (probably related to my browser settings?). Anyway this is annoying if confirmed for everyone

**Comment by immanuelfodor** [comment]
I used it a lot, for example, keeping a note open at https://shaarli.example.com/?RaNDomID then the save would redirect back to that note, so it'd let me edit the same note multiple times without navigating away. Now it loads the main page as `?RaNDomID` was replaced by `/shaare/RaNDomID`. If I come from a new `/shaare/...` URL, it should redirect back to it, this is why I think this functionality was lost in the 0.12.0 rewrite. (To be precise, originally, it directed back to https://shaarli.example.com/?RaNDomID#RaNDomID but that was the same thing when editing a single shaare multiple times.)

**Comment by immanuelfodor** [comment]
Browser settings or web server security headers can alter this as the returnurl is filled up with the http referer value. If you disable http referers, it can't determine where are you from, that's why it could work for you this way.

**Comment by ArthurHoaro** [comment]
There is a minor issue with the code preventing the redirection loop because of new route names `/shaare/RaNd0m` and `/admin/shaare`. I'll provide a PR for 0.12.0.

**Comment by immanuelfodor** [comment]
Thank you for the fix, it works fine, it's so useful for note taking!
