### ISSUE TITLE
"convert all tags to lowercase" button in tools dialog

### ISSUE THREAD

**Issue by nodiscc** [shaarli/Shaarli#155]
Followup to https://github.com/shaarli/Shaarli/issues/146

A growing list of tags can be painful to manage. Casing errors and variants introduce a lot of almost-duplicate tags so we could provide a button to convert all tags to all-lowercase. (next to the rename tags button)

**Comment by ArthurHoaro** [comment]
I think this issue is not relevant anymore due to #583
