### ISSUE TITLE
Additional variables are saved with plugins data

### ISSUE THREAD

**Issue by ArthurHoaro** [shaarli/Shaarli#1550]
Reported by @immanuelfodor 

> config.json.php:
> ```php
> "plugins": {
>        "_BASE_PATH_": "",
> ```
> The last variable seems extremely suspicious to me :)

I confirm that on my dev local environment I also have `_LOGGEDIN_` and `token` under the `plugins` section which are not supposed to be here. I suspect that additional data are saved in `PluginController`.

**Comment by immanuelfodor** [comment]
Hmm, so that one resulted in two issues at last 😃 (the other is #1548)
