### ISSUE TITLE
Feature request: Entry description field templates

### ISSUE THREAD

**Issue by virtadpt** [shaarli/Shaarli#1557]
Use case: I have a Shaarli instance that I use as a personal card catalog for my book collection.  All of my entries look like this:

```
Title field: title of book

Description field:
Author: ...
ISBN: ...
Publication: ...
Year: ...
Number of copies owned: ...
Pages: ...
```

Entering a new book requires a certain amount of copying and pasting to set up the Description field.  Would it be possible to configure Shaarli so that every new entry on that instance is pre-filled with some arbitrary text to facilitate this?  Or, would it be possible to add this feature as an option to a the new release (or a subsequent release)?

**Comment by kcaran** [comment]
Are you using the default template? You could add it to the textarea definition in editlink.html:

shaarli/tpl/default/editlink.html:

~~~
diff --git a/tpl/default/editlink.html b/tpl/default/editlink.html
index 568545b..43eb121 100644
--- a/tpl/default/editlink.html
+++ b/tpl/default/editlink.html
@@ -35,7 +35,15 @@ <h2 class="window-title">
         <label for="lf_description">{'Description'|t}</label>
       </div>
       <div>
-        <textarea name="lf_description" id="lf_description" class="autofocus">{$link.description}</textarea>
+        <textarea name="lf_description" id="lf_description" class="autofocus">{if="$link.description"}{$link.description}{else}
+Description field:
+Author:
+ISBN:
+Publication:
+Year:
+Number of copies owned:
+Pages:
+{/if}</textarea>
       </div>
       <div>
         <label for="lf_tags">{'Tags'|t}</label>
~~~

If there isn't already a link description, this will default it to the specified text. You could probably make it even smarter, like only defaulting it for notes and not remote URLs.

**Comment by virtadpt** [comment]
Yeah, I am using the default.

Thank you!  I didn't know I could do that.  I'll give it a try this afternoon.

**Comment by ArthurHoaro** [comment]
This is quite a specific request, so I don't think it should be added as a core feature in Shaarli.

However, as kcaran mentioned you can *hack* the template to add a default value. 
If you want to do that in a cleaner way, you can also write a simple plugin ([documentation](https://shaarli.readthedocs.io/en/master/dev/Plugin-system/)) using `render_editlink` hook.

**Comment by virtadpt** [comment]
That worked - thank you!
