### ISSUE TITLE
PHP warnings

### ISSUE THREAD

**Issue by robertharm** [shaarli/Shaarli#1578]
First thanks for your great tool - I have been using it for several years. Just one small issue: if PHP error log is enabled, my log is flooded with entries like those:

`mod_fcgid: stderr: PHP Notice:  Undefined index: thumbnail in /shaarli/tmp/includes.cedf684561d925457130839629000a81.rtpl.php on line 32`

Is there chance to get a fix for this?
thx,
Robert

**Comment by ArthurHoaro** [comment]
Hi @robertharm, which version of Shaarli are you using?

**Comment by robertharm** [comment]
v0.11.0 according to CHANGELOG.md

**Comment by ArthurHoaro** [comment]
This issue has been fixed by #1346 and will be released with v0.12.0. (yes, sorry, we had a long time without any release)

**Comment by robertharm** [comment]
thanks for the info - looking forward to the update!
