### ISSUE TITLE
Default theme cleanup

### ISSUE THREAD

**Issue by mrjovanovic** [shaarli/Shaarli#158]
I've been working on a cleanup of the default theme [here](https://github.com/mrjovanovic/Shaarli/tree/DefaultThemeRedesign). 

The clean-up does several things:
* Resolves the issue of menus being all wonky on window resize.
* Styles the tags and thumbnails to match the style of input boxes and buttons. This also makes tags easier to read.
* Improves padding on links, making private and public links visually consistent
* Improves spacing on search/tagfilter when on mobile, making them distinguishable.
* Fixes pixelated private links image and styles it to match other icons.
* Removes the box shadow around the "edit/delete links" sidebar and makes it more visually consistent.

I've tested it on Firefox and Chromium on GNU/Linux, but I don't have access to Windows/ OS X to test it there. Would like some help in testing this and figuring out bugs before submitting any pull request.

I hope this was appropriate to post as an issue. I wasn't really sure if I should put it here or on the wiki.I've been working on a cleanup of the default theme [here](https://github.com/mrjovanovic/Shaarli/tree/DefaultThemeRedesign). 

Screenshots below:
Front page showing padding, thumbnail cleanup, box shadow removal
![2015-03-10-143318_1366x768_scrot](https://cloud.githubusercontent.com/assets/4664783/6589266/502c1ad2-c76b-11e4-9e4b-e072d4f31652.png)

Resizing at work 
![2015-03-10-143346_1366x768_scrot](https://cloud.githubusercontent.com/assets/4664783/6589277/5a358360-c76b-11e4-9625-695cd2c93157.png)

**Comment by nodiscc** [comment]
@mrjovanovic congrats, this is better than what we currently have. I'll rebase/squash your commits and submit a Pull Request. After that you can checkout my Pull Request branch and start working on top of it.

**Comment by nodiscc** [comment]
Pull request at https://github.com/shaarli/Shaarli/pull/162
