### ISSUE TITLE
3rd party Chromium based extension is no longer working

### ISSUE THREAD

**Issue by toyqiu** [shaarli/Shaarli#1594]
![image](https://user-images.githubusercontent.com/479873/96250874-1f794980-0fe2-11eb-8c88-6826a40e7a3d.png)

new links ---- Wrong token
edit existed link ---- Wrong token
Chrome plugin login ---- Wrong token

delete all data and reinstall --- still ---- Wrong token

**Comment by ArthurHoaro** [comment]
Tokens are attached to your user session, and in your screenshot your are logged in, so your session seems to be working fine.

Can you try on the demo instance (https://demo.shaarli.org - login: demo/password: demo) just to rule out any browser plugin issue?

**Comment by toyqiu** [comment]
> Tokens are attached to your user session, and in your screenshot your are logged in, so your session seems to be working fine.
> 
> Can you try on the demo instance (https://demo.shaarli.org - login: demo/password: demo) just to rule out any browser plugin issue?

![image](https://user-images.githubusercontent.com/479873/96276067-1cdc1b80-1005-11eb-89c9-e4d46235a667.png)

![image](https://user-images.githubusercontent.com/479873/96276105-26658380-1005-11eb-8c97-04571ee044f9.png)
![image](https://user-images.githubusercontent.com/479873/96276177-3a10ea00-1005-11eb-8e39-8451aeecd34d.png)
![image](https://user-images.githubusercontent.com/479873/96276214-44cb7f00-1005-11eb-87e5-285170c446ac.png)

**Comment by ArthurHoaro** [comment]
Oh you are only talking about the Chrome extension. I can reproduce your issue, but this extension is a 3rd party software and not directly related to us.

You can try to report your issue here: https://github.com/octplane/Shiny-Shaarli

**Comment by nodiscc** [comment]
Please submit this issue to https://github.com/octplane/Shiny-Shaarli if it's still present, or try the other chromium/chrome extension listed [here](https://shaarli.readthedocs.io/en/master/Community-and-related-software/#browser-extensions)
