### ISSUE TITLE
Add the title of the link in the link element

### ISSUE THREAD

**Issue by aledeg** [shaarli/Shaarli#1599]
At the moment, we have something like:
```html
<h2>
    <a href="http://example.net">
	    <i class="fa fa-external-link" aria-hidden="true"></i>
    	<span class="linklist-link">Some title</span>
	</a>
</h2>
```

We could have something like:
```html
<h2>
    <a href="http://example.net" title="Some title">
	    <i class="fa fa-external-link" aria-hidden="true"></i>
    	<span class="linklist-link">Some title</span>
	</a>
</h2>
```

I am using Shaarli 0.12.0 with the default theme.

**Comment by ArthurHoaro** [comment]
What's the point if the title is the same as the one displayed?

**Comment by aledeg** [comment]
The point was to retrieve it in JS directly from the `a` tag. But I found that I can do that by other means. It can be closed if you think it is unnecessary.

**Comment by ArthurHoaro** [comment]
Yes I think that would be redundant, and the title can be retrieved using a `querySelector`.
