### ISSUE TITLE
API / programmable access

### ISSUE THREAD

**Issue by nodiscc** [shaarli/Shaarli#16]
- ~~https://github.com/sebsauvage/Shaarli/issues/58: Page storage~~ -> **external tool, https://github.com/nodiscc/shaarchiver is WIP**
- ~~https://github.com/sebsauvage/Shaarli/issues/57: Export features~~ **closed/ghost**
- ~~https://github.com/sebsauvage/Shaarli/issues/66: readityourself~~ **implemented in https://github.com/shaarli/Shaarli/pull/52**
- ~~https://github.com/sebsauvage/Shaarli/issues/69: Command-line authentication~~ **closed**
- https://github.com/sebsauvage/Shaarli/issues/74: Allow import from Firefox's JSON backup files **-> write a separate converter**
- https://github.com/sebsauvage/Shaarli/issues/92: Unable to login using links browser 
- ~~https://github.com/sebsauvage/Shaarli/issues/96: Functionnality to give crawlers possibility to know some options~~ **not a Shaarli bug, plugin if needed**
- ~~https://github.com/sebsauvage/Shaarli/issues/146: Mister Wong Import tweaks~~ **-> added to https://github.com/shaarli/Shaarli/wiki#importing-from-mister-wong**
- ~~https://github.com/sebsauvage/Shaarli/issues/167: Add sharing support for Wallabag~~ **-> implemented in https://github.com/shaarli/Shaarli/pull/52**

We already have RSS and ATOM available as a read-only API.  
This can be used for many things (I have a python script that fetches my RSS feed, locally saves pages tagged `readlater`, downloads media for `music` and `video` tags, images matching some URLs (`*.jpg`, `imgur.com`)...). The only missing features for my point of view are:
- ~~Authenticated access (access to private links, HTML export functionality)~~
- Write access (HTML import, add/edit/remove links, tags...)

**Comment by mro** [comment]
I consider the http get parameters, html form content and page flow the *API*.

How could we - as a part of the travis build - ensure a certain behaviour? Would `bash`+`curl` test scripts make sense?

**Comment by virtualtam** [comment]
#316 also related

PHPUnit itself is not designed to run functional tests, as you need to:
- run an HTTP server
- run an HTTP client to send, receive and verify requests

This is rather the domain of [SeleniumHQ](http://docs.seleniumhq.org/), which can be used both for verifying:
- HTTP headers
- generated pages

Some info:
- http://docs.travis-ci.com/user/gui-and-headless-browsers/
- https://www.browserstack.com/automate/continuous-integration

Any feedback/PR on using Selenium for PHP browser automation is more than welcome, this would be great to have for [v0.8.0](https://github.com/shaarli/Shaarli/milestones/0.8.0) to help with templating and W3C compliance checks

**Comment by mro** [comment]
Looks a bit hairy but may be worth while: http://docs.travis-ci.com/user/languages/php/#Apache-%2B-PHP

**Comment by mro** [comment]
test multiple shaarli versions at once: https://github.com/mro/phptestdemo

**Comment by mro** [comment]
The tests mentioned above show a strange pattern for 'wrong password' login failures with certain, mostly recent, releases: https://travis-ci.org/mro/phptestdemo/builds/78849088

I suspect php caching which I'm clueless about in travis environments.

Any ideas?

**Comment by virtualtam** [comment]
#342 opened to focus on functional testing :)
