### ISSUE TITLE
Add weekly, and monthly views to the Daily page

### ISSUE THREAD

**Issue by nodiscc** [shaarli/Shaarli#160]
We may want to add date filtering to the main code for this, and use user-provided params for the date range, eg

```
?do=daily&startdate=$currentyear-$currentmonth-01&enddate=$currentyear-$currentmonth-$daysinmonth` ?
```

**Comment by poVoq** [comment]
Any updates on this? A weekly newspaper would be good to have as a configuration.

**Comment by virtualtam** [comment]
@poVoq if there's no new comment nor open pull request, it's quite likely there's no work going on either :)
