### ISSUE TITLE
404 error page after login

### ISSUE THREAD

**Issue by 2Belette** [shaarli/Shaarli#1603]
Hi, 

Using Shaarli (0.12.0) with Nginx (using official nginx configuration from documentation) I got 404 when I am logging in. Clicking on any tab is working, and all the main functions are working great.

I notice the same problem if I click on Documentation (from the footer) : I can see the Homepage (doc/html/index.html) but if I click to anything else from the left menu I got the same 404 error.

The same error from my nginx log, I guess this is due to the rewrite rules, like some need to be tweaked from nginx configuration from the official website, anyone else got the same problem ?

nginx conf : 

```
  server {
        listen       80;
        server_tokens off;
        server_name  shaarli.mydomain;
        root   /srv/http/shaarli;
        access_log      /var/log/nginx/shaarli.access.log defaultformat;
        error_log       /var/log/nginx/shaarli.error.log;
	
	location ~ /\. {
            access_log off;
            log_not_found off;
            deny all;
        }
        location ~ ~$ {
            access_log off;
            log_not_found off;
            deny all;
        }
        location ~* \.(?:ico|css|js|gif|jpe?g|png)$ {
            expires    max;
            add_header Pragma public;
            add_header Cache-Control "public, must-revalidate, proxy-revalidate";
        }
        location = /favicon.ico {
            alias /var/www/shaarli/images/favicon.ico;
        }
        location / {
	    index index.php;
            try_files $uri /index.php$is_args$args;
        }
        location ~ (index)\.php$ {
            try_files $uri =404;
            fastcgi_split_path_info ^(.+\.php)(/.+)$;
            fastcgi_pass   unix:/run/php-fpm.sock;
            fastcgi_index  index.php;
            include        fastcgi.conf;
        }
        location ~ \.php$ {
            deny all;
	}
        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
            root   /usr/share/nginx/html;
        }
    }
```

**Comment by ArthurHoaro** [comment]
Hi,

What URL path are you redirected to after login to get a 404 error?

Regarding the documentation, I can reproduce your issue on the demo instance, so it broke at some point. I'll look into it.

**Comment by 2Belette** [comment]
Instead of redirecting to / it keeps me on /login so the 404, if I refresh after login in, then I got redirected to / and I don't have the 404 anymore !

For the documentation, it is sending me to /doc/html/index.html which is working well but if I tick on anything from the left menu I am sent to /doc/html/thepageIclick without index.html. If I add index.html it is working fine.

We should have a rule for index.html I guess on nginx, I tried to add it unsuccessfully for now

**Comment by ArthurHoaro** [comment]
If you inspect the login page, what do you have here?
![](https://i.imgur.com/31qpCvI.png)

**Comment by ArthurHoaro** [comment]
For the documentation, I tried to add this directive which seems to work. I'll run a few more tests to see if it can be improved:

```
location ~ /doc/ {
    default_type "text/html";
    try_files $uri $uri/ $uri.html =404;
}
```

**Comment by 2Belette** [comment]
Perfect for the doc it is fixing the issue :)

Regarding the login : exactly like you, redirecting to /

**Comment by 2Belette** [comment]
Sorry it seems I am not able to attach a screenshot, no idea why..

      <div>
        <input value="Login" class="bigbutton" type="submit">
      </div>
      <input name="token" value="xxxxxxxxxxxxxxxxxxxxxxxxxxxxx" type="hidden">
      <input name="returnurl" value="https://mydomain/login" type="hidden">
    </form>

After all, it is not the same like you, it is trying to redirect to /login so the issue...

**Comment by ArthurHoaro** [comment]
I can't reproduce your issue, and there are 2 things that I don't understand here:

  - the redirection code should prevent to redirect to any path containing `login` (to prevent redirection loop)
  - the `/login` page should return a 404 error as it is a valid route

Can you make sure that the URL are exactly the same between the one your reach to login, and the one you are redirected to?

**Comment by 2Belette** [comment]
I made another test, and indeed that weird... check below ! it is like there is no value ??

<form method="post" name="loginform">
      <div class="subheader-form header-login-form" id="header-login-form">
        <input name="login" aria-label="Username" placeholder="Username" type="text">
        <input name="password" aria-label="Password" placeholder="Password" type="password">
        <div class="remember-me">
          <input name="longlastingsession" id="longlastingsession" checked="" type="checkbox">
          <label for="longlastingsession">Remember me</label>
        </div>
        <input name="token" value="xxxxxxxxxxxxxxxxxxxxxx" type="hidden">
        <input name="returnurl" type="hidden">
        <input value="Login" type="submit">
      </div>
    </form>

**Comment by 2Belette** [comment]
Sorry again, I don't know why Github is not keeping my code...

<form method="post" name="loginform">
      <div class="subheader-form header-login-form" id="header-login-form">
        <input name="login" aria-label="Username" placeholder="Username" type="text">
        <input name="password" aria-label="Password" placeholder="Password" type="password">
        <div class="remember-me">
          <input name="longlastingsession" id="longlastingsession" checked="" type="checkbox">
          <label for="longlastingsession">Remember me</label>
        </div>
        <input name="token" value="xxxxxxxxxxxxxxxxx" type="hidden">
        <input name="returnurl" type="hidden">
        <input value="Login" type="submit">
      </div>
    </form>

**Comment by ArthurHoaro** [comment]
Add ``` one the line before and after your code.

**Comment by 2Belette** [comment]
:) just done that before your message, the button didn't work

**Comment by ArthurHoaro** [comment]
There can be no value, this relies on the HTTP Referer that your browser sends. Please check the question I asked in my previous message.

**Comment by 2Belette** [comment]
I hope this is giving you the answer (let me know if not), will try add the screenshots if Github gives me the permission to do so

**Comment by ArthurHoaro** [comment]
You have an « Unexpected error », which is an error 500 not 404. Unfortunately it's not logged anywhere yet (see #1606).

In your `data/config.json.php`, can you temporarily add:

```json
,
"dev": {
  "debug": true
}
```

It'll display the error stacktrace in the template that you can copy/paste here.

**Comment by 2Belette** [comment]
Yes you're right ! (The reason why I was confused is that /doc was 404 but login is /500)...

```2020/10/21 18:38:48 [error] 30029#30029: *96 FastCGI sent in stderr: "PHP message: PHP Notice:  Undefined index: LINKS_PER_PAGE in /shaarli/application/render/PageBuilder.php on line 152" while reading response header from upstream, client: x.x.x.x, server: shaarli.mydomain, request: "POST /login HTTP/1.0"```

**Comment by ArthurHoaro** [comment]
Are you 100% sure you're using Shaarli `v0.12.0` (check `shaarli_version.php`)?

**Comment by 2Belette** [comment]
```cat shaarli_version.php  
<?php /* 0.12.0 */ ?>
```

**Comment by 2Belette** [comment]
@ArthurHoaro , anything you want me to test or extra troubleshooting to help you figure out the problem ? I assume you don't have the same issue on your system right ?

**Comment by ArthurHoaro** [comment]
I will probably need some more info, but I need to take some time to analyze how the issue *could* append. I'm currently busy with a few other things but I will take a look asap.

And no, I couldn't reproduce your issue, that's what make it harder to debug. :)

**Comment by GaneshKandu** [comment]
I am getting same issue on PHP 7.1 working on PHP 7.2
when i print ``` $this->session ```  it print blank array on 7.1

**Comment by 2Belette** [comment]
@GaneshKandu, good hint ! I am actually on PHP 7.1.33 ... so perhaps you found the issue

**Comment by ArthurHoaro** [comment]
Thank you, I can reproduce your issue with PHP 7.1.

**Comment by ArthurHoaro** [comment]
OK I found the issue. [session_set_cookie_params](https://www.php.net/manual/en/function.session-set-cookie-params.php) returned void before PHP 7.2, [cookieParamters()](https://github.com/shaarli/Shaarli/blob/master/application/security/SessionManager.php#L296) must return void.

The displayed error about `LINKS_PER_PAGE` was actually raised in the error handler, because the session just got destroyed. I'll still add a default value.

**Comment by 2Belette** [comment]
Wonderful thanks, it solved the issue !! :)
