### ISSUE TITLE
blank page when searching for text

### ISSUE THREAD

**Issue by sjimwillis** [shaarli/Shaarli#1607]
Filtering by tags works as expected but when I try to search for a term that I know is in the Title of one of the webpages I've saved, the resulting page is blank. Searching for any text always results in a blank page:

https://links.jimwillis.org/?searchterm=practice&searchtags=

So whenever a parameter is passed to searchterm, I get a blank page back but if I pass a parameter to searchtags, it works fine. any ideas?

**Comment by ArthurHoaro** [comment]
* Which version of Shaarli are you using? 
  * Just to be sure, can you clear you `tmp/` folder? 
  * A blank page usually results with an error in your web server logs, can you check if there is anything?

**Comment by sjimwillis** [comment]
I cleared tmp. the log file seems to be pointing to a php issue around mb_convert_case()

[Wed Oct 21 11:53:28.241847 2020] [php7:error] [pid 20479] [client 100.35.134.139:58370] PHP Fatal error:  Uncaught Error: Call to undefined function Shaarli\\Bookmark\\mb_convert_case() in /home/sjwillis/public_html/links.jimwillis.org/public/application/bookmark/LinkFilter.php:188\nStack trace:\n#0 /home/sjwillis/public_html/links.jimwillis.org/public/application/bookmark/LinkFilter.php(90): Shaarli\\Bookmark\\LinkFilter->filterFulltext('practice', 'all')\n#1 /home/sjwillis/public_html/links.jimwillis.org/public/application/bookmark/LinkDB.php(428): Shaarli\\Bookmark\\LinkFilter->filter('vuo\\x7Ftext', Array, false, 'all', false)\n#2 /home/sjwillis/public_html/links.jimwillis.org/public/index.php(1683): Shaarli\\Bookmark\\LinkDB->filterSearch(Array, false, '', false)\n#3 /home/sjwillis/public_html/links.jimwillis.org/public/index.php(499): buildLinkList(Object(Shaarli\\Render\\PageBuilder), Object(Shaarli\\Bookmark\\LinkDB), Object(Shaarli\\Config\\ConfigManager), Object(Shaarli\\Plugin\\PluginManager), Object(Shaarli\\Security\\LoginManager))\n#4 /home/sjwillis/public_html/links.jimwillis.org/public/index.php(1639): showLinkList(Object in /home/sjwillis/public_html/links.jimwillis.org/public/application/bookmark/LinkFilter.php on line 188

**Comment by ArthurHoaro** [comment]
Shaarli [requires](https://shaarli.readthedocs.io/en/master/Server-configuration/) [php-mbstring](https://www.php.net/manual/en/book.mbstring.php) extension. You need to install it.

**Comment by sjimwillis** [comment]
Thanks!
apt-get install php7.3-mbstring
solved the problem, appreciate it.

**Comment by ArthurHoaro** [comment]
Glad I could help :+1:
