### ISSUE TITLE
Shaarli does not return to filtered view after editing a shaare

### ISSUE THREAD

**Issue by Braintoe** [shaarli/Shaarli#1611]
If you had your bookmarks filtered by a tag, let's say "zzzz" (tag was available on the demo site), and edited a bookmark, you returned to the filtered view when clicking "Apply Changes". 
On Shaarli 0.12 this feature is broken, the URL Shaarli returns to seems wrong, the "&" sign is converted to a "&amp%3B":

Original URL with "tag=zzzz" filter applied:
`https://demo.shaarli.org/?searchterm=&searchtags=zzzz+`

URL after editing a bookmark and clicking the "Apply Changes" button:
`https://demo.shaarli.org/?searchterm=&amp%3Bsearchtags=zzzz+#uZtqFQ`

Should be:
`https://demo.shaarli.org/?searchterm=&searchtags=zzzz+#uZtqFQ`

Tested on both the demo site and my own installation with MS edge (non-chromium) and Vivaldi, current stable versions.
(edit: browsers added)

**Comment by ArthurHoaro** [comment]
Thank you for the detailed report!
