### ISSUE TITLE
[Feature Request] Search API

### ISSUE THREAD

**Issue by yuha0** [shaarli/Shaarli#1617]
I'd like to programmatically access my bookmarks but couldn't find any way to perform a search through API.

At a glance, it doesn't seem to be possible by design since all API requests have to be authenticated.

Right now, looks like I can hit `/?searchterm=XXX&searchtags=XXX` and parse the response HTML myself. But I think providing native search functionality through API would be something very nice to have.

**Comment by ArthurHoaro** [comment]
Good news, it already exists!

  * https://shaarli.readthedocs.io/en/master/REST-API/
  * https://shaarli.github.io/api-documentation/

**Comment by yuha0** [comment]
@ArthurHoaro Sorry, I still couldn't find any API docs for **search**. Could you point me to the location if it is mentioned in the docs?

What I am looking for, is an API endpoint that I can do an HTTP GET against, with my search term and tags, and get a response from the server with structured data (probably JSON) that contains links matching my search term and tags. I'd like to do this without authentication to get public links.

**Comment by ArthurHoaro** [comment]
[GET /links](https://shaarli.github.io/api-documentation/#links-links-collection-get) accepts `searchterm` and `searchtags` query parameters to perform your search.

**Comment by yuha0** [comment]
@ArthurHoaro Thanks. But `GET /links` require authentication. Would it be possible to use this API without authentication? The shaarli instance is hosted in private network and only my family members can access. I am building some automation so they can search for public links without visiting shaarli website.

**Comment by virtadpt** [comment]
@yuha0 If by "authentication" you mean "username and password," the answer is yes, use an API key.  If by "authentication" you mean "API key," probably not.

If using an API key fits your use case, I have some code that does what you're asking about here: https://github.com/virtadpt/exocortex-halo/blob/master/shaarli_bot/shaarli_bot.py#L301
