### ISSUE TITLE
Allow using third-party templates without overwriting Shaarli's default

### ISSUE THREAD

**Issue by nodiscc** [shaarli/Shaarli#163]
Users should be able to clone/unzip other templates into their `tpl/your-template-here` directories, and tell Shaarli to use them by setting the `RAINTPL_TPL` config variable to this path. This prevents breaking Shaarli's upgrade path, and allows users to upgrade templates to their latest version easily.

@ArthurHoaro has started something tending to this in https://github.com/shaarli/Shaarli/pull/76.

 * The default template should probably be moved to `tpl/default`, all links to/from the template rewritten and checked.
 * The default shaarli.css is designd for the default template, so it should be moved inside the template directory.
 * The proposed plugin system (https://github.com/shaarli/Shaarli/pull/164) has to adapt to this. That's to say, are plugins specific to a template, or do tyhey apply to any template? The directory path for plugins depends on that.

That also means **each third-party template has to be in it's own archive/repository** to be able to clone/unpack it easily in it's own `tpl/your-template-here`.

The https://github.com/shaarli/templates repo doesn't follow this model currently (the hoa.ro template is in a subdirectory). I'd be ok to rename it to template-hoaro and move contents directly at the root of the repo. @ArthurHoaro already has write access to this repo so he can keep maintaining it in the future.

@alexisju you also have a nice template at https://github.com/alexisju/Shaarli-AlbinoMouse, would you like me to create a template-albinomouse repository in the shaarli organization and give you write access there? You could sync your template there when you think it's ready, and maintain it in the future.

There are more third-party Shaarli templates listed [in the wiki](https://github.com/shaarli/Shaarli/wiki#related-software) and it would be cool if the maintainers are willing to maintain their templates in the organization. So @kalvn @Vinm @dhoko @AkibaTech @misterair ping. Do you want to join your work to the community fork and maintain your template in the oragnization? I can create repos and give you write access there.

**We'll have to agree about a directory structure** in this issue, or on https://gitter.im/shaarli/Shaarli (english only here, english or French on Gitter if that's more comfortable for you)

**Comment by ArthurHoaro** [comment]
Then wouldn't it be simplier if we all keep our template set in our "Github space" and list them somewhere here?

**Comment by nodiscc** [comment]
Yep you can close the PR as this issue is now open :)

> wouldn't it be simplier if we all keep our template set in our "Github space" and list them somewhere here?

I don't know.

You can still maintain your theme in your own repos, but just `git remote add organization git@github.com:shaarli/template-hoaro; git push organization master` and your new version is also synced here.

Having all these templates in the org would ensure we have a list of known, maintained, compatible templates, and in the long run template maintainers can maintain each other's work (fixes, version bumps...) via the org. The templates would also be easily accessible/discoverable at https://github.com/shaarli/Shaarli. 

But yeah, even if we don't create these repos, I'm pinging everyone to see if the change is worth it (will we have a significant number of compatible templates? currently people's work is not compatible for easy install, the CSS is still old school, etc. Maybe we can help each other with this)

**Comment by AkibaTech** [comment]
Good Idea! I'm in! :)

**Comment by nodiscc** [comment]
@Vinm replied https://github.com/Vinm/Blue-theme-for-Shaarli/issues/2#issuecomment-78364265:

> 

>Hello !

>I answer to tell you that the theme for Shaarli I made few years ago is not very good, and is bad coded. If you want to use it, you can, but I advise you to don't use it because it is not responsive and not very user-friendly.

>Do what you want ;)
>Regards.

**Comment by nodiscc** [comment]
> But what about assets (js, css, fonts)? Should Shaarli not be updated accordingly?

@AkibaTech Well this is what we have to solve. The way I see it, the dir structure could be like
```
Shaarli/
├── cache
├── data
├── doc
├── images
├── inc
├── pagecache
├── tmp
└── tpl
    ├── albinomouse
    ├── default
    └── superhero <-------- clone or unzip your template here
        ├── daily.html
        ├── includes.html
        ├── linklist.html
        ├── page.footer.html
        ├── page.header.html
        ├── README.md
        └── inc
            ├── bootstrap.css
            ├── bootstrap.js
            ├── bootstrap.min.css
            ├── bootstrap.min.js
            ├── coolfont.eot
            └── superhero.css
```

And we should do the same for the default template (mov `inc/*` to the `tpl/default/inc`). Just a quick thought. I may have missed something, please let me know.

**Comment by AkibaTech** [comment]
Dooooooooone!!!!

https://github.com/AkibaTech/Shaarli---SuperHero-Theme/commit/abdbafb21d7f22594f498e1bf3528464cb9b3976

**Comment by ArthurHoaro** [comment]
@AkibaTech You should also include jQuery since we're trying to get rid of it. And it might be done soon if #165 is merged.

@nodiscc 
> Having all these templates in the org would ensure we have a list of known, maintained, compatible templates, and in the long run template maintainers can maintain each other's work (fixes, version bumps...)

Yep that's probably better.

> And we should do the same for the default template (mov inc/* to the tpl/default/inc).

I agree for client side dependency (eg. not raintpl) and CSS. Except maybe `reset.css`. Also, images folder probably belong in theme folder.

**Comment by AkibaTech** [comment]
All right.

Theme updated :)

**Comment by nodiscc** [comment]
> images folder probably belong in theme folder. 

You're right! I updated the dir structure above ^ @AkibaTech think you could do this? Thanks for your quick reply, I'll start working on a new branch soon and test your template there. And yep, include everything you would need client side, including jQuery.

**Comment by AkibaTech** [comment]
Know it :)

Branch "shaarli-template" is for this awesome upcoming feature.
Branch "master" is for current version as noticed in my readme :)

**Comment by nodiscc** [comment]
When this is merged, docs should also be updated (eg. config settings may not apply to all templates, for example `SHOW_ATOM`, or any othe)

**Comment by kalvn** [comment]
Interested as well, I will update my template tomorrow to fit this new structure.

**Comment by kalvn** [comment]
It's done and available here: https://github.com/kalvn/shaarli-blocks/tree/shaarli-template

By the way, if you want to make it easy for people to build custom templates, you should really define some path variables in index.php (like the absolute URL to templates, or at least the absolute URL of the installation) and make them available in the template because I noticed that some head files are automatically renamed and some aren't (for example CSS files) and it can quickly become a mess to understand why it doesn't work.

And for now, I indicated to update the variable `$GLOBALS['config']['RAINTPL_TPL']` but it would be interesting to have a parameter in the config file and the config page.

**Comment by dhoko** [comment]
I'm in too. :clap:

I will create a new version soon (with flexbox). Rewrite the default HTML \o/ 

@ArthurHoaro 
> Except maybe reset.css. 

Reset.css does not have to come with Shaarli. Ex: some dev don't use it (ex: me), there are normalize etc. Dev must choose their one reset.

**Comment by alexisju** [comment]
I'll do it soon also :)

**Comment by nodiscc** [comment]
@kalvn 

> I indicated to update the variable $GLOBALS['config']['RAINTPL_TPL'] but it would be interesting to have a parameter in the config file and the config page.

You should never edit index.php directly. You should define `GLOBALS['config']['RAINTPL_TPL'] = "tpl/shaarli-blocks";` in `data/options.php`! So this already supprted (I suggest you update your readme).

index. php. should. never. be. touched. Else we lose the benefit of having "modular" templates. `data/options.php` overrides existing options.

**Comment by kalvn** [comment]
Correct me if I'm wrong but the option file is required in the index.php *after* the initialization of raintpl. I didn't test but we define the directory to use during this init, it may be a problem no ?

**Comment by alexisju** [comment]
Albinomouse available as template : https://github.com/alexisju/albinomouse-template

**Comment by kalvn** [comment]
I finally moved mine on the the master branch as the last release of Shaarli handles the `options` file: https://github.com/kalvn/shaarli-blocks

I also created a new theme with Material Design guidelines and also offered an installation for Shaarli 0.0.44 and above: https://github.com/kalvn/Shaarli-Material

**Comment by nodiscc** [comment]
@kalvn great work! Thanks for your time, I'll look into this in the coming days (short on time right now).

Another thing to consider when we will push the changes for 3rd party templates support (mainly changing the dir structure) is to know whether your templates will support plugins (eg. I see you're using the QR code library, but it is planned to make it optional/pluggable) and where we will put them in the dir structure.

Please have a look at https://github.com/shaarli/Shaarli/pull/164, feedback welcome. The dir structure refactoring to support third party templates will probably be part of this Pull Request in the future.

**Comment by nodiscc** [comment]
misterair replied: https://github.com/misterair/limonade/issues/7#issuecomment-86743026

>hi,
>unfortunately I've no time to contribute :-/
>But, you can, if you want, copy/modify my template in your project. Be careful, I've modified the Shaarli's default template structure...

**Comment by nodiscc** [comment]
Attention, you can no longer use `$link.localdate` when I merge https://github.com/shaarli/Shaarli/pull/169 (this week :) ), you have to do date formatting inside your template. You can use `function="strftime('%c', $link.timestamp)"` instead

**Comment by alexisju** [comment]
ok

**Comment by ArthurHoaro** [comment]
Kinda duplicates #22. Also I think it's not a very good idea to have a main repo with all the themes. Everyone having its own repos and referencing in the docs is good enough. Closing.
