### ISSUE TITLE
Can I be added in the authors file?

### ISSUE THREAD

**Issue by killruana** [shaarli/Shaarli#1633]
Hi,

A very long time ago, I have sent two patches to sebsauvage for Shaarli (see changelogs for versions v0.0.17beta and v0.0.18beta). The code is now probably not used and deleted, but can I be added to the contributors list? 

author info: `Jonathan Tremesaygues <jonathan.tremesaygues+github@slaanesh.org>`

Best regards

**Comment by ArthurHoaro** [comment]
The `AUTHORS` file is auto-generated using the git commit log. I suppose sebsauvage wasn't using git back then.

I suggest that you send a pull request to have an entry in it.

**Comment by killruana** [comment]
Yup, at this time, seb used bazaar.

Thanks for your response.
