### ISSUE TITLE
hook_demo_plugin_render_editlink not working

### ISSUE THREAD

**Issue by Knah-Tsaeb** [shaarli/Shaarli#1646]
Hi, in the demo plugin, the function  _hook_demo_plugin_render_editlink_ not working in 0.12.1.
The extra field data is not save.

**Comment by nodiscc** [comment]
@Knah-Tsaeb do you still have this problem? Can you provide a way to reproduce the problem (example plugin?)

**Comment by Knah-Tsaeb** [comment]
@nodiscc of course.
  - install fresh Shaarli (docker or regular install)
  - enable plugin demo
  - add new link or note
  - fill the last input (Demo Stuff)
  - save
  - edit the previous link or note
  - the last input is blank

**Comment by nodiscc** [comment]
Thanks! I could reproduce with v0.12.1 installed from zip. The value of the last input does not seem to be saved. No relevant messages in logs even with `dev.debug = true`.

**Comment by ArthurHoaro** [comment]
This issue should be fixed by changes embedded in #1727. I'll see if I can get back into it and merge it.
