### ISSUE TITLE
Multiple tags are added as one huge tag

### ISSUE THREAD

**Issue by immanuelfodor** [shaarli/Shaarli#1651]
Moved here from: https://github.com/dimtion/Shaarlier/issues/55

> My Shaarli is at the latest upstream master and I have the default space as tag separator. When I add several tags to a link, it's being created as one huge tag. The only way to get the tags separated is to edit the link and just hit save, then the tags are broken up just as they should. There is no change in the use case of how I share a link, I've always used spaces to share both in the webapp and in Shaarlier. Please look into this issue, it's rather difficult for me to type commas instead of spaces on mobile with lots of tags (commas are the only way now to circumvent this issue meanwhile using the Shaarlier app share).

Huge tags also show up in the tag search after a share is created:

![image](https://user-images.githubusercontent.com/21174107/100091646-2dc64b00-2e55-11eb-9d9b-7b855684f64e.png)

The web is also displaying the one huge tag:

![image](https://user-images.githubusercontent.com/21174107/100091687-3cacfd80-2e55-11eb-9b5c-f5de91b7d818.png)

After hitting save, the tags are separated fine:

![image](https://user-images.githubusercontent.com/21174107/100091700-42a2de80-2e55-11eb-957c-d5ce3c90e3b3.png)

ArthurHoaro commented 42 minutes ago: 
> I can reproduce your issue using the Python client.

**Comment by dougbreaux** [comment]
Heh, as a new Shaarli user, I assumed this was working as designed and I just needed to delimit the tags differently 😄

**Comment by ArthurHoaro** [comment]
Actually I was misusing the python client.

It should be:

    shaarli post-link --description "python test"  --tags abc def

And not: 

   shaarli post-link --description "python test"  --tags "abc def"

Meaning that as specified in the [documentation](http://shaarli.github.io/api-documentation/#links-links-collection-post), an array of tags should be provided instead of a string. But it wouldn't harm to be more permissive.

So I suggest the following:

  - I'll provide a PR to parse strings properly
  - You can reopen your issue here dimtion/Shaarlier#55 to use an array instead of a string
  - I'll open an issue in the python client repo, because [the documentation](https://python-shaarli-client.readthedocs.io/en/latest/user/usage.html) doesn't provide any example of tags usage.

**Comment by immanuelfodor** [comment]
Thank you, I've reopened the Shaarlier issue as requested :)

**Comment by ArthurHoaro** [comment]
Thank you, I'm closing this as my first point has been done and merged, and other issue are not in this repo.

**Comment by immanuelfodor** [comment]
Thank you! Building on the latest Shaarli master image (https://hub.docker.com/layers/shaarli/shaarli/master/images/sha256-2acd7f5abf8b4166785bee43146331587d963bbb48b96224be74f32e880d861a?context=explore), I can't see any change, the space-separated Shaarlier tags are still created as one huge tag. Only after an edit or pin action they are separated. 

I assumed this PR would parse them correctly (addig backwards compatibility for string), although they still needed to be sent as an array from Shaarlier to comply with the API spec on the long run.

**Comment by ArthurHoaro** [comment]
:(

I will give it a try with Shaarlier to see what's going on.

**Comment by immanuelfodor** [comment]
I use the API key login if it helps.

**Comment by immanuelfodor** [comment]
I'm sorry, it works, closing the issue now 😃

Post mortem related to https://github.com/shaarli/Shaarli/issues/1673#issuecomment-753780154 : Keel force updated the deployment when the new image was built but the pull policy was `IfNotPresent`. Although Kubernetes restarted the deployment on the image update, it didn't pull the new version as the underlying node had the same tag (master). I checked the image SHA as well, the problem sufaced.
