### ISSUE TITLE
Synchronous metadata retrieval breaks the add link flow

### ISSUE THREAD

**Issue by immanuelfodor** [shaarli/Shaarli#1653]
Separated the web app issue into this ticket from the Shaarlier client one: https://github.com/dimtion/Shaarlier/issues/53

Maybe since the latest big updates, Shaarli is not loading the description field at all. It's not just not loading on a few sites, but honestly, I can't remember the last time it has loaded anything into the description field 😃 But it definitely worked earlier, and I loved it. 

Arthur suggested looking into `general.retrieve_description` and `general.enable_async_metadata`. I have both these configs turned on since forever (never touched them). 

Can somehting block the retrieval on the client side/browser, or this is a server-side curl? Somewhere I've seen a commit/PR/release note about improving regexes related to titles or descriptions, maybe this caused it to break?

**Comment by immanuelfodor** [comment]
And it's not just the description but the title as well. I use the Shaarlier app mainly to add links an it can load the title in some cases (see https://github.com/dimtion/Shaarlier/issues/54) but it seems the title is not loading on the web, too. 

![Screenshot_20201124-194407](https://user-images.githubusercontent.com/21174107/100137979-9e895980-2e8d-11eb-8192-8c71a53c678f.jpg)

**Comment by immanuelfodor** [comment]
Uh, oh, it seems to be a Material theme issue, working fine with the default theme :( 

It would mean it indeed got broken somewhere around the big changes, I can remember it was operating a few months or a year ago. 

cc @kalvn

![Screenshot_20201124-195035](https://user-images.githubusercontent.com/21174107/100138528-75b59400-2e8e-11eb-9d01-5547a87d9044.jpg)

**Comment by kalvn** [comment]
I'm pretty sure this is because metadata is now retrieved asynchronously, therefore using JavaScript which is part of the theme, not the core of Shaarli.

It means I have to handle that part on my own. I'll work on it soon.

**Comment by kalvn** [comment]
Can you please close the issue here and open a new one on Shaarli-Material repo?

**Comment by immanuelfodor** [comment]
Of course, thank you for your help: https://github.com/kalvn/Shaarli-Material/issues/120

**Comment by immanuelfodor** [comment]
Just for a quick test, I've set `general.enable_async_metadata` to `false` until kalvn fixes the Javascript part of the issue, and it completely broke the page (https://github.com/kalvn/Shaarli-Material/issues/120#issuecomment-735241953).

This is what I get after clicking the add link button:

```
strlen() expects parameter 1 to be string, boolean given
/var/www/shaarli/application/front/controller/admin/ShaarePublishController.php230
#0 /var/www/shaarli/application/front/controller/admin/ShaarePublishController.php(230): strlen(false)
#1 /var/www/shaarli/application/front/controller/admin/ShaarePublishController.php(165): Shaarli\Front\Controller\Admin\ShaarePublishController->buildFormData(Array, true, Object(Slim\Http\Request))
#2 /var/www/shaarli/application/front/controller/admin/ShaarePublishController.php(37): Shaarli\Front\Controller\Admin\ShaarePublishController->displayForm(Array, true, Object(Slim\Http\Request), Object(Slim\Http\Response))
#3 [internal function]: Shaarli\Front\Controller\Admin\ShaarePublishController->displayCreateForm(Object(Slim\Http\Request), Object(Slim\Http\Response), Array)
#4 /var/www/shaarli/vendor/slim/slim/Slim/Handlers/Strategies/RequestResponse.php(40): call_user_func(Array, Object(Slim\Http\Request), Object(Slim\Http\Response), Array)
#5 /var/www/shaarli/vendor/slim/slim/Slim/Route.php(281): Slim\Handlers\Strategies\RequestResponse->__invoke(Array, Object(Slim\Http\Request), Object(Slim\Http\Response), Array)
#6 /var/www/shaarli/application/front/ShaarliMiddleware.php(55): Slim\Route->__invoke(Object(Slim\Http\Request), Object(Slim\Http\Response))
#7 /var/www/shaarli/application/front/ShaarliAdminMiddleware.php(25): Shaarli\Front\ShaarliMiddleware->__invoke(Object(Slim\Http\Request), Object(Slim\Http\Response), Object(Slim\Route))
#8 [internal function]: Shaarli\Front\ShaarliAdminMiddleware->__invoke(Object(Slim\Http\Request), Object(Slim\Http\Response), Object(Slim\Route))
#9 /var/www/shaarli/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array(Array, Array)
#10 [internal function]: Slim\DeferredCallable->__invoke(Object(Slim\Http\Request), Object(Slim\Http\Response), Object(Slim\Route))
#11 /var/www/shaarli/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func(Object(Slim\DeferredCallable), Object(Slim\Http\Request), Object(Slim\Http\Response), Object(Slim\Route))
#12 /var/www/shaarli/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(117): Slim\Route->Slim\{closure}(Object(Slim\Http\Request), Object(Slim\Http\Response))
#13 /var/www/shaarli/vendor/slim/slim/Slim/Route.php(268): Slim\Route->callMiddlewareStack(Object(Slim\Http\Request), Object(Slim\Http\Response))
#14 /var/www/shaarli/vendor/slim/slim/Slim/App.php(503): Slim\Route->run(Object(Slim\Http\Request), Object(Slim\Http\Response))
#15 /var/www/shaarli/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(117): Slim\App->__invoke(Object(Slim\Http\Request), Object(Slim\Http\Response))
#16 /var/www/shaarli/vendor/slim/slim/Slim/App.php(392): Slim\App->callMiddlewareStack(Object(Slim\Http\Request), Object(Slim\Http\Response))
#17 /var/www/shaarli/vendor/slim/slim/Slim/App.php(297): Slim\App->process(Object(Slim\Http\Request), Object(Slim\Http\Response))
#18 /var/www/shaarli/index.php(176): Slim\App->run(true)
#19 {main}
```

**Comment by immanuelfodor** [comment]
Based on the stack trace, this seems to be a server-side bug, renamed the issue accordingly, cc @ArthurHoaro 

```
"retrieve_description": true,
"enable_async_metadata": false,
```

**Comment by ArthurHoaro** [comment]
Thanks for taking the time to investigate the issue @immanuelfodor .

**Comment by immanuelfodor** [comment]
Thanks for the fix! I would not test it right away, preferably just after the string parsing PR is merged for #1651. I'm a bit afraid that something else will break as the Material theme is a bit left behind the releases. However, two of these bugfixes are worth the risk :grinning:

**Comment by immanuelfodor** [comment]
I've tested the fix with my new build, the synchronous metadata retrieval on the backend-side now works in the latest Shaarli master image.

Thank you, and happy new year to you :tada:

**Comment by immanuelfodor** [comment]
I observe lots of hashed folder and file writes under `/cache/finder/` when the `enable_async_metadata` is `false`, just tiny hashed files with one image URL. Is something retrieved from each URL synchronously on every pagination? 

For every page going back in time p5, p6, ... p10, p11, etc, the first load is extremely slow, taking around 10-20s. Then all reloads on that same page is quick. This is when I did an `ls -latr` on the finder directory, and saw lots of batched time values on the hashed folders related to the pagination times. When I deleted all folders there, and did a new pagination, the page load for a previously quick page became slow again, and about 11-12 new folders appeared. Then another batch for another pagination. I turned off sync metadata retrieval, then deleted the hashed folders again, then reloaded the page, did some more pagination, and nothing was written into the finder folder. 

Doing a quick search in the repo, there is no match in the source for `finder`. What is the finder folder for, and what is happening here with the pagination when sync metadata retrieval is on?

**Comment by ArthurHoaro** [comment]
This is used for thumbnails by https://github.com/ArthurHoaro/web-thumbnailer. Finder is the piece of software locating the thumbnail URL on the remote page (and caching it), and `thumb` folder contains the thumbnail image cached. If you open a file in `cache/finder/` you should find either nothing or a URL.

Now, its integration with Shaarli processes thumbnail retrieval for a bookmark if the following parameters are matched:

  - user is logged in
  - bookmark is an external link with HTTP(S) scheme
  - the thumbnail has never been retrieved (`datastore.php`) or its associated image cache file does not exist (`cache/thumb/...`)

Retrieving a thumbnail can be a long process, that why if you change thumbnails settings, it is recommended to run a complete resync of them (`shaarli-url/admin/thumbnails`). Otherwise they will be retrieved one by one when displayed, either asynchronously using [AJAX requests](https://github.com/shaarli/Shaarli/blob/master/application/front/controller/admin/ThumbnailsController.php#L46) or [synchronously](https://github.com/shaarli/Shaarli/blob/master/application/front/controller/visitor/BookmarkListController.php#L178) (which makes the first load pretty slow) depending on `enable_async_metadata`.

> I turned off sync metadata retrieval, then deleted the hashed folders again, then reloaded the page, did some more pagination, and nothing was written into the finder folder.

That's not normal though.

**Comment by immanuelfodor** [comment]
Thanks for the explanation! Well, it could be normal with async enabled if the thumbnails existed in the other folder, I just removed the finder folder contents (which is a cache only for the thumbnail url location as I understand). With async as my main preference, there is no slowness issue for me, I was just curious why the sync mode is so slow on every first page load as I assumed it is only used for the page metadata retrieval (title+desc) upon adding a new link.
