### ISSUE TITLE
Update PHP version in Docker image?

### ISSUE THREAD

**Issue by dougbreaux** [shaarli/Shaarli#1655]
When we started a fresh instance from the Dockerhub image, it reports that the PHP it's running is EOL today, November 30, 2020.

![image](https://user-images.githubusercontent.com/25640850/100659179-de30c500-3315-11eb-9bea-c7bc042ddf33.png)

**Comment by nodiscc** [comment]
The [Dockerfile](https://github.com/shaarli/Shaarli/blob/master/Dockerfile) uses a hardcoded `alpine:3.8` base image. We should upgrade to a newer release (ideally 3.12) https://hub.docker.com/_/alpine/

**Comment by dougbreaux** [comment]
And do the Alpine package updating in the Dockerfile as well, for any packages that have been updated since the Alpine drop itself?

**Comment by nodiscc** [comment]
PR in https://github.com/shaarli/Shaarli/pull/1658

**Comment by nodiscc** [comment]
> Alpine package updating in the Dockerfile as well

see my reply at https://github.com/shaarli/Shaarli/pull/1658#discussion_r537049585

**Comment by ArthurHoaro** [comment]
The updated Alpine version repository serves PHP 7.3 which is 2 versions behind. That's not ideal. Maybe we should consider switching to [php:8.0-alpine](https://hub.docker.com/_/php) Docker base image.

**Comment by immanuelfodor** [comment]
Please notify if any plugin changes need to be made to comply with PHP 8. Though it would be great if it would just work :tm:

**Comment by ArthurHoaro** [comment]
Shaarli is compatible with PHP 8.0, so it is strongly recommended for 3rd party plugin to also be. Note that besides a few edge cases of PHP usage, PHP 8.0 does not include a lot of breaking changes.

**Comment by dougbreaux** [comment]
And now
> Running PHP 7.3.33
> End of life: December 6, 2021

**Comment by nodiscc** [comment]
`alpine:3:15` has php 7.4.27 https://pkgs.alpinelinux.org/packages?name=php7&branch=v3.15

-> update the base image to `alpine:3:15`

**Comment by nodiscc** [comment]
> running container is still Alpine 3.12.7

Are you sure you are running the updated image?

```bash
docker image ls | grep -i shaarli
docker ps
```

**Comment by dougbreaux** [comment]
I certainly built from the new Dockerfile as is reflected in the build messages above. This is running under Openshift (k8s), so it's a bit different to check, but some build excerpts (just ran it again):
```
...
[1/4] STEP 1/3: FROM python:3-alpine AS docs
[1/4] STEP 2/3: ADD . /usr/src/app/shaarli
--> 4c477ed3b88
[1/4] STEP 3/3: RUN cd /usr/src/app/shaarli     && apk add --no-cache gcc musl-dev     && pip install --no-cache-dir mkdocs     && mkdocs build --clean
fetch https://dl-cdn.alpinelinux.org/alpine/v3.15/main/x86_64/APKINDEX.tar.gz
fetch https://dl-cdn.alpinelinux.org/alpine/v3.15/community/x86_64/APKINDEX.tar.gz
...
[4/4] STEP 1/17: FROM alpine@sha256:a9c28c813336ece5bb98b36af5b66209ed777a394f4f856c6e62267790883820
[4/4] STEP 2/17: LABEL maintainer="Shaarli Community"
--> 643468eec01
[4/4] STEP 3/17: RUN apk --update --no-cache add         ca-certificates         nginx         php7         php7-ctype         php7-curl         php7-fpm         php7-gd         php7-iconv         php7-intl         php7-json         php7-mbstring         php7-openssl         php7-session         php7-xml         php7-simplexml         php7-zlib         s6
fetch http://dl-cdn.alpinelinux.org/alpine/v3.12/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.12/community/x86_64/APKINDEX.tar.gz
...
Successfully pushed image-registry.openshift-image-registry.svc:5000/shaarli/shaarli@sha256:44345f2bfa13d52b12e764348de32c35457425ea647ec91821ed134a9184a9ff
Push successful
```

Then 
```
$ oc get pods
NAME                       READY   STATUS      RESTARTS   AGE
shaarli-31-build           0/1     Completed   0          15m
shaarli-855c9fbf77-x4652   1/1     Running     0          12m
```

And
```
$ oc describe pod shaarli-855c9fbf77-x4652
Name:         shaarli-855c9fbf77-x4652
...
Containers:
  shaarli:
    Container ID:   cri-o://7c2bc64b900d6b54fc6bda14795daed6f11488c23a0583adb8e690b55e739b18
    Image:          image-registry.openshift-image-registry.svc:5000/shaarli/shaarli@sha256:44345f2bfa13d52b12e764348de32c35457425ea647ec91821ed134a9184a9ff
...
  Normal  Pulled          13m   kubelet            Successfully pulled image "image-registry.openshift-image-registry.svc:5000/shaarli/shaarli@sha256:44345f2bfa13d52b12e764348de32c35457425ea647ec91821ed134a9184a9ff" in 4.614147479s
  Normal  Created         13m   kubelet            Created container shaarli
  Normal  Started         13m   kubelet            Started container shaarli
```
Which is same SHA as was just built above, and which has that mix of Alpine 3.15 and 3.12 references in it.

**Comment by dougbreaux** [comment]
>Build cache configuration issues?

I sure wouldn't think so. especially not with the `--no-cache` ?

**Comment by nodiscc** [comment]
`--no-cache` is used by `apk` inside the build process, I was rather thinking about cached OCI image layers on your OpenShift node. Can you clear the node's image/layer cache somehow, and try again? That would help pinpoint the issue.

**Comment by dougbreaux** [comment]
I'll look into that and try if I find out how. But we've had another issue - not related to the Shaarli build specifically - that it seems the way the registry stores images by default, they don't persist at all across OCP version updates, which we just did today.

**Comment by dougbreaux** [comment]
Clearly some things we're learning about OpenShift. It was using a BuildConfig using an ImageStream pointing to Alpine 3.12. We manually added 3.15 and that seems to have done the trick.
