### ISSUE TITLE
Docker: default_color plugin unable to update settings

### ISSUE THREAD

**Issue by dougbreaux** [shaarli/Shaarli#1657]
I enabled the default_color plugin and was able to set the color once, but then I was never able to change it to anything else. Even when disabling & re-enabling it, it retains the initial color I set, even though the UI shows the new values I've tried to set.

When I shell into the container and look at `shaarli/plugins/default_colors/default_colors.css`, the initial color I set is still there. The file seems to have permissions where I ought to be able to change it from the UI:
```
/var/www # ls -al shaarli/plugins/default_colors/
total 16
drwxr-xr-x    1 nginx    nginx           32 Dec  4 21:18 .
drwxr-xr-x    1 nginx    nginx           28 Nov 12 12:20 ..
-rw-r--r--    1 nginx    nginx           35 Dec  4 21:18 default_colors.css
-rw-r--r--    1 nginx    nginx           13 Nov 12 12:20 default_colors.css.template
-rw-r--r--    1 nginx    nginx          354 Nov 12 12:20 default_colors.meta
-rw-r--r--    1 nginx    nginx         3268 Nov 12 12:20 default_colors.php
```

And, in fact, I'm able to edit it in place there in the container, and the change takes effect.

Also, though, I'd like to see these kinds of things externalized into a mounted volume as well. That may be a separate enhancement Issue: to get the plugins to store their settings in like the data volume?

**Comment by greinbold** [comment]
Same issue here, but I don't use Docker.

**Comment by ArthurHoaro** [comment]
I reproduced the issue on my own instance.
