### ISSUE TITLE
how to open bookmark in a new tab?

### ISSUE THREAD

**Issue by toyqiu** [shaarli/Shaarli#1663]
how to open bookmark in a new tab?

**Comment by aledeg** [comment]
This has nothing to do with Shaali. It depends on your browser and its configuration.
I am using Firefox and I can use either ''Ctrl + left click'' or ''middle click'' or the entry in the contextual menu.
You need to dig in your browser preferences or in its documentation to find out what works for you.

**Comment by toyqiu** [comment]
> This has nothing to do with Shaali. It depends on your browser and its configuration.
> I am using Firefox and I can use either `Ctrl + left click` or `middle click` or the entry in the contextual menu.
> You need to dig in your browser preferences or in its documentation to find out what works for you.

yeah,sure I know how to browse a URL in a new tab.
I mean if there could be a feature of choosing the way opening a new tab,like _blank or somethine.
It can be really more convenient.
THX

**Comment by ArthurHoaro** [comment]
See #1504
---
shaarli.readthedocs.io/en/master/Community-&-Related-software/#third-party-plugins
trailjeep/shaarli-urlextern
Shaarli plugin to open external links in a new tab/window.
