### ISSUE TITLE
Modification du header 'Last-Modified'

### ISSUE THREAD

**Issue by dukethis** [shaarli/Shaarli#1670]
Bonjour,
Je propose de modifier les lignes 82,83 de l'index.php par celles-ci :
```
// Load the last change time in 'Last-Modified' header
header("Last-Modified: " . date("D, d M Y H:i:s", filectime("data/datastore.php")) . " GMT");
```
Cela permet de donner la date de la dernière modification (post ou edit) comme prévu.

Modifié ici : https://github.com/dukethis/Shaarli

Merci,
duke

**Comment by ArthurHoaro** [comment]
I'll reopen your issue, if you don't mind. I have already seen this issue raised somewhere else, and in any case, disabling the cache by setting the case to the current timestamp is probably not the best idea.

**Comment by dukethis** [comment]
Yes sure. I have closed it because I was not sure at all about the case. I did the change but I noticed weird behaviors from my instance for a while (I don't think it was directly related to that change though..). 

Anyway you have the idea :) save some bandwith!

**Comment by ArthurHoaro** [comment]
Sorry I forgot that I already raised the issue in #1643, re-closing this one.
