### ISSUE TITLE
update all thumbnails with "error 405"

### ISSUE THREAD

**Issue by gwenlune** [shaarli/Shaarli#1674]
when i cleared the thumbnail cache, and I want to update thumbnails an error occur : An error occurred. Return code: 405

The log file says : 
`"POST /admin/thumbnails?do=ajax_thumb_update HTTP/1.1" 405 1006 "https://shaarli.home.monsiteinternet.org/admin/thumbnails" "Mozilla/5.0 (X11; Linux x86_64; rv:84.0) Gecko/20100101 Firefox/84.0"`

**Comment by ArthurHoaro** [comment]
Hi, can you provide more information about your Shaarli version, your web server configuration, etc.

**Comment by gwenlune** [comment]
This is the last git version (update yesterday). Apache 2.4, Php 7.3 on a debian Buster updated.

**Comment by ArthurHoaro** [comment]
Are you using the default theme? Can you try to clear your local cache and/or CTRL+F5?

I don't understand where `POST /admin/thumbnails?do=ajax_thumb_update` can come from. It looks like a mix between new and legacy routes.

You should have something like

  1. `GET /admin/thumbnails`
  1. `PATCH /admin/shaare/1814/update-thumbnail`

**Comment by gwenlune** [comment]
Yes I was surprise by the POST method...
I tried CTRL+F5 and on other browser (whch never launch my shaarli website) and I have the same error.

**Comment by ArthurHoaro** [comment]
> This is the last git version (update yesterday)

Did you rebuild the assets? `yarn run build`

**Comment by gwenlune** [comment]
No... I didn't know I have to do something after upgrade... I found https://shaarli.readthedocs.io/en/master/Upgrade-and-migration/#upgrading-from-git 
I did all it was necessary and it's ok now...
sorry for inconvenience
Thanks a lot

**Comment by ArthurHoaro** [comment]
No worries. I also suggest that you use a release instead of the master branch if you don't use it for development purposes.
