### ISSUE TITLE
Incorrect rendering of links in descriptions

### ISSUE THREAD

**Issue by nodiscc** [shaarli/Shaarli#1681]
How to reproduce:

- Submit this example shaare to https://demo.shaarli.org:

```
URL: https://docs.gitlab.com/ee/user/project/badges.html
Title:  Badges | GitLab
Tags:  doc admin gitlab cicd 
Description:
- https://docs.gitlab.com/ee/api/project_badges.html
- https://docs.gitlab.com/ee/ci/pipelines/settings.html
```

- Search for the term `ee/ci` + tag `cicd`: https://demo.shaarli.org/?searchterm=ee%2Fci&searchtags=cicd+#Z3nOfQ
- The search result displays withe one of the links in the description prefixed with `ee/ci/pipelines/settings.html">`

![image](https://user-images.githubusercontent.com/3950390/104133599-7c379680-537c-11eb-8a1e-cdab69f24fa3.png)

- The `href` of the generated link is incorrect `https://docs.gitlab.com/<span class=`
- Changing the `formatter` setting to either `default`, `markdown` or `markdownextra` does not solve the problem
- Reproducible at https://demo.shaarli.org/?searchterm=ee%2Fci&searchtags=cicd and on my v1.12.1 installation from release zip (Debian + Apache + php-fpm)
- Note that the problem does not happen when the current search term does not contain a slash

![image](https://user-images.githubusercontent.com/3950390/104133595-704bd480-537c-11eb-905f-96e501e37b92.png)

**Comment by nodiscc** [comment]
I get a different (incorrec)t rendering of the description with a different search term `gitlab.com`

![image](https://user-images.githubusercontent.com/3950390/104134174-f87fa900-537f-11eb-9a60-9f2aaa333a5b.png)

Removing the dot `.` and just searching for `gitlab` works

**Comment by virtadpt** [comment]
I've been seeing this, too.  It's been messing with my searches lately.

**Comment by nodiscc** [comment]
Also reproducible for some searches without any special characters in searchterms:

```
URL: https://tympanus.net/codrops/
Title: Codrops | Useful resources and inspiration for creative minds
Description:
- https://tympanus.net/Development/DialogEffects
- https://tympanus.net/Development/NotificationStyles
- https://tympanus.net/TipsTricks/CSS3MenuHoverEffect
Tags: graphisme webdev ui html5 index blog search dev 
```

https://demo.shaarli.org/?searchterm=tympanus&searchtags=#ReSApA

![image](https://user-images.githubusercontent.com/3950390/104136466-3aafe700-538e-11eb-9207-b7141c32fc47.png)
