### ISSUE TITLE
bookmarklet code fails when running without URL rewriting

### ISSUE THREAD

**Issue by andreworg** [shaarli/Shaarli#1682]
I just installed Shaarli 0.12.1 on lighttpd behind haproxy.

I still have not implemented URL rewriting, and I'm postponing "`/index.php/`" to my requests as described [here](https://shaarli.readthedocs.io/en/master/Server-configuration/#using-shaarli-without-url-rewriting).
Everything seems to work fine but the bookmarklets. The generated code does not take index.php into account, resulting in a Bad Request.

Please note that I have added `\/index,php\/` to `header_link` in the config, but I have not set `general.root_url` as _recommended_, because - again - everything else seems to work just fine without it.

The obvious workaround is to edit the bookmarket after creation, adding "`/index.php/`" to the URL in `window.open()`.

**Comment by ArthurHoaro** [comment]
It is working properly if `general.root_url` is set, otherwise `index.php` will be truncated any time Shaarli tries to generate an absolute URL of the instance. You probably have issues with your RSS feeds permalinks as well.
