### ISSUE TITLE
Delete a bookmark from bulk creation shows incorrect error

### ISSUE THREAD

**Issue by kalvn** [shaarli/Shaarli#1683]
_Tested with the latest Shaarli master branch._

When using the bulk creation page, if one of the added links already exists, there's the possibility to delete it. When clicking on delete, Shaarli makes a GET request to `/admin/shaare/delete?id=3&token=9d72184bceb63d929f4ef8ec9a69163cb747054b` (of course the id and token are variable).

The deletion works fine but after deleting, the following popup appears:

![image](https://user-images.githubusercontent.com/6149640/104925695-6e4acc80-599f-11eb-9e03-5bdf8b82530e.png)

The problem seems to be the fact that the response to the GET request contains the header `Location: /admin/shaare-batch` which the browser tries to follow, resulting to an AJAX GET request on `/admin/shaare-batch` which is not allowed (hence the message in the popup).

![image](https://user-images.githubusercontent.com/6149640/104926063-f630d680-599f-11eb-9f2e-716597a4c4cc.png)

A solution could be to change the initial AJAX request to use a DELETE instead of GET to an endpoint which would not send any `Location` header in the response.

**Comment by ArthurHoaro** [comment]
> A solution could be to change the initial AJAX request to use a DELETE instead of GET to an endpoint which would not send any Location header in the response.

Thanks for the suggestion, however I did try to add minimal controller and route changes when I added this feature, and that's why this button uses the default Shaarli `GET /delete` route (use everywhere else). I have removed the redirection from the response instead.

**Comment by ArthurHoaro** [comment]
Thanks @kalvn for taking the time to thoroughly test this feature and report these issues. I left quite of few of them obviously.

**Comment by kalvn** [comment]
Developing a theme is a good way to extensively test new features :) I'm glad it helps!
