### ISSUE TITLE
Undefined Variable Error When Adding Link

### ISSUE THREAD

**Issue by mdrockwell** [shaarli/Shaarli#1702]
I received the following error whenever I try to add a link to Shaarli (edited to remove my exact path):

`Notice: Undefined variable: index in /bookmark/tmp/editlink.025e4ef3c23e9ff6918934cf9db5d80e.rtpl.php on line 23`

The link still saves properly — I can see the saved link on other devices.

**Comment by ArthurHoaro** [comment]
Are you using the latest release?

**Comment by mdrockwell** [comment]
Yes, I’m using version 0.12.1. Here’s a screenshot (should have added that in the initial bug report):

![67C9AFC3-51AE-4177-A917-B1FBFD003B09](https://user-images.githubusercontent.com/42454301/106464535-c507da00-6466-11eb-97d5-66bba9f9be95.jpeg)

**Comment by ArthurHoaro** [comment]
I think this is because you are not using the latest beta release of Shaarli Material theme compatible with Shaarli v0.12.1: https://github.com/kalvn/Shaarli-Material/tags

**Comment by mdrockwell** [comment]
Sorry for the confusion. I did a bit more testing and this does appear to be from Material theme. Based on the error, I thought it was part of core Shaarli. Thanks!
