### ISSUE TITLE
Issue with URL building with the Docker image

### ISSUE THREAD

**Issue by kalvn** [shaarli/Shaarli#1705]
I'm running my Shaarli instance with the Docker image (tag v0.12.1) but I have issues with some URL resolutions.

For example, I noticed that the result of `index_url` function is `http://` in my case. It can be seen for example on the Server Config page:
![image](https://user-images.githubusercontent.com/6149640/107093806-2c76ae80-6806-11eb-9d48-7809b5730981.png)

I also noticed that the `{$feedurl}` variable from templates resolves to `http:///?do=rss` which is wrong. You can see it in the source code of https://links.kalvn.net

It seem to be because function `server_url` uses `$_SERVER['SERVER_NAME']` (https://github.com/shaarli/Shaarli/blob/master/application/http/HttpUtils.php#L347) which is empty in the case of the official Docker image. This is an extract of the phpinfo:

![image](https://user-images.githubusercontent.com/6149640/107096287-b32d8a80-680a-11eb-9957-315cfbf76c29.png)

**Comment by ArthurHoaro** [comment]
As you said `server_url` is based on `SERVER_NAME`, which is based on your web server configuration.

If you are using the Docker image, I assume you are using a reverse proxy. In that case, refer to [Reverse proxy docs](https://shaarli.readthedocs.io/en/master/Reverse-proxy/). Server name has to be specified.

**Comment by kalvn** [comment]
Very good point, I didn't think about the reverse proxy headers. I'll do that and close the ticket if it solves my issue.
