### ISSUE TITLE
Bulk creation: shaares are always created as private

### ISSUE THREAD

**Issue by nodiscc** [shaarli/Shaarli#1707]
Steps to reproduce:
 - click `+ Shaare` button
- Unfold the `+ Bulk creation` dialog
 - Paste a few links in the text area
```
https://mywiki.wooledge.org/BashProgramming
https://mywiki.wooledge.org/BashProgramming/02
https://mywiki.wooledge.org/BashProgramming/03
https://mywiki.wooledge.org/BashProgramming/04
https://mywiki.wooledge.org/BashProgramming/05
https://mywiki.wooledge.org/BashProgramming/Ex01
```
- Add some tags, make sure the `Private` checkbox is unchecked
- Click `Add links`
- Save all links, or save links one by one

Shaares are created as private even though none of the `Private` checkboxes are checked

**Comment by ArthurHoaro** [comment]
I can not reproduce your issue on `master` branch. Can you reproduce it, or was it fixed somehow?

**Comment by nodiscc** [comment]
I can reproduce it on 0.12.1 installed from zip, but not on https://demo.shaarli.org/, so I guess it's fixed on master. Thanks
