### ISSUE TITLE
Yarn/Nodejs in « The personal, minimalist … bookmarking service »

### ISSUE THREAD

**Issue by Sbgodin** [shaarli/Shaarli#1709]
Dear all,

It's been a while since I didn't updated my Shaarli instance. I couldn't proceed. It needs NodeJs that comes with Yarn. I downloaded the bunch of stuff required. Then it told me my version was outdated, on my Debian Buster.

At what moment did it appear to be a sweet idea to depend upon NodeJs to install Shaarli?

I took a look at the source code, I guess that NodeJs is no longer needed for Shaarli to work properly. Is it true?

The work made since I contributed long time ago seems great, but maybe the minimalist thingy got away.

**Comment by nodiscc** [comment]
You don't need `npm`/Nodejs if you install from release ZIP (https://shaarli.readthedocs.io/en/master/Installation/#from-release-zip), Shaarli's runtime requirements still are a simple web server and PHP interpreter.

yarn/webpack are only used as development/maintenance tools to manage frontend build dependencies and some tasks like minifying js. `composer` is used to manage PHP packages. None of these are needed if you install from the prebuilt zip.

This is what I do (I run the latest stable release zip on Debian 10). You will only need dev dependencies/package managers if you want to run your own builds (we let [CI](https://travis-ci.com/shaarli/Shaarli) tools handle this part)

**Comment by nodiscc** [comment]
If the question is whether the development toolchain could be simplified, yes, it could be improved. But dropping package managers while keeping required maintenance to a minimum, without losing functionality will be very hard. The fact that the reference package manager for JS libraries itselfs depends on Node is unfortunate, yes.

**Comment by Sbgodin** [comment]
@nodiscc I also noticed the CI tools, Docker stuff and it’s quite good because they could be removed. It’s, AFAIK, still possible to develop without the tools.

I guess that Node-things are required in order to develop seriously. For instance, I find something on the frontend ; or at least something related to. If I want to report anything, I must deal with Node. Just to be sure that it would be reproducible by the developers.

As for me, my production system is not _up to date_ enough. I can't (easily) touch anything as straightforward as before.

**Comment by nodiscc** [comment]
Reopening, installing Nodejs requirements should be documented somewhere at https://shaarli.readthedocs.io/en/master/ (again, [can be done on Debian stable](https://www.digitalocean.com/community/tutorials/how-to-install-node-js-on-debian-10) but you need the upstream version, not the version from Debian repositories)).

We could provide an alternative build mode that doesn't require npm (that probably means the [default](https://github.com/shaarli/Shaarli/tree/master/tpl/default) template will not be available, though the [vintage](https://github.com/shaarli/Shaarli/tree/master/tpl/vintage) template should work)

**Comment by nodiscc** [comment]
Building from source without `yarnpkg`/node is possible by removing `build_frontend` from the [`release_zip` target](https://github.com/shaarli/Shaarli/blob/master/Makefile#L131) dependencies, and running `make build_frontend` (though this will not build the `default` template - you have to use the `vintage` template or a third-party one).

Intalling nodejs from third-party repositories/struggling to find the correct version is no longer necessary on Debian, installing the official [yarnpkg](https://packages.debian.org/bullseye/yarnpkg) package should work out-of-the-box.

If this breaks again in the future, [nvm](https://github.com/nvm-sh/nvm) makes it easy to install the correct node version without touching system repositories/packages.

Using third-party frontend code makes it more complex, and `npm` packaging/dependency trees are absolutely insane (https://github.com/shaarli/Shaarli/blob/master/yarn.lock ...), but this is still a good tradeoff, as we do not have to maintain (and test!) low-level CSS/JS libs anymore.
