### ISSUE TITLE
encondig issues in 'search' & 'fiter by tag' buttons

### ISSUE THREAD

**Issue by nicolasdanelon** [shaarli/Shaarli#171]
Hi guys I think that [here](https://github.com/shaarli/Shaarli/blob/master/tpl/linklist.html#L8) we need to use HTML entities or something like that.. I just pull the current shaarli version and have this issue. See screenshot attached :

![screenshot from 2015-03-16 00 31 24](https://cloud.githubusercontent.com/assets/2846046/6660230/ce2c0634-cb73-11e4-8abc-a6b07b565918.png)

**Comment by nicolasdanelon** [comment]
the issue seems to be only in linux... font-family problem?

![windows](https://cloud.githubusercontent.com/assets/2846046/6660461/44b69676-cb78-11e4-8efb-a4de122025a2.png)

**Comment by pikzen** [comment]
Font family indeed. The glyph is hardcoded in https://github.com/shaarli/Shaarli/blob/master/tpl/linklist.html#L9 . Any font not having this glyph will not display it.

**Comment by nicolasdanelon** [comment]
confirming......
yup!
we need to roll back to text inputs

**Comment by nodiscc** [comment]
Sorry this is my whole fault :/ I changed the button title to an uncode character in https://github.com/shaarli/Shaarli/pull/167. I had tested availability of this glyph on some OSs, not enough, apparently. I'll roll back this change and do a bugfix release.

@mrjovanovic It might interest you. Here's the problem with unicode symbols instead of icons.

**Comment by nicolasdanelon** [comment]
Can I change it ? And add open sans fonts in my pull request?

**Comment by nodiscc** [comment]
@nicolasdanelon Let's revert it in the first time. I'll do that today. Another PR that changes icons to Unicode symbols + open sans can be opened.

**Comment by nodiscc** [comment]
Fixed in https://github.com/shaarli/Shaarli/commit/c981b4d19cea6ee8001ba80e1d7e47cd3d2f7ff6 and https://github.com/shaarli/Shaarli/commit/5b2a7cfe0f12b373fc0bf55c1e22413632f57b4d

**Comment by mrjovanovic** [comment]
Hm, that's interesting. @nicolasdanelon what distro/default fonts are that, if I may ask?

**Comment by fturco** [comment]
I have this problem with Shaarli 0.0.44beta. I haven't upgraded to latest version yet. As a workaround I installed the Symbola fonts (package "ttf-symbola" under Parabola/ArchLinux).
