### ISSUE TITLE
Upgrade from 0.11.1 to 0.12.1 fails

### ISSUE THREAD

**Issue by buzz** [shaarli/Shaarli#1710]
Trying to do a simple upgrade as described in [Upgrading from ZIP archives](https://shaarli.readthedocs.io/en/master/Upgrade-and-migration/#upgrading-from-zip-archives) from v0.11.1 to v0.12.1.

I set the theme back to `default` as it was mentioned it could cause issues. I'm using [this NGINX configuration](https://shaarli.readthedocs.io/en/master/Server-configuration/#nginx).

Opening the Shaarli page shows the following.

```
An unexpected error happened, and the error template could not be displayed.

Return value of Shaarli\Bookmark\Bookmark::getId() must be of the type int or null, string returned
/var/www/application/bookmark/Bookmark.php158
#0 /var/www/application/bookmark/BookmarkArray.php(77): Shaarli\Bookmark\Bookmark->getId()
#1 /var/www/application/legacy/LegacyUpdater.php(590): Shaarli\Bookmark\BookmarkArray->offsetSet('20170224_141935', Object(Shaarli\Bookmark\Bookmark))
#2 [internal function]: Shaarli\Legacy\LegacyUpdater->updateMethodMigrateDatabase()
#3 /var/www/application/legacy/LegacyUpdater.php(118): ReflectionMethod->invoke(Object(Shaarli\Legacy\LegacyUpdater))
#4 /var/www/application/bookmark/BookmarkFileService.php(417): Shaarli\Legacy\LegacyUpdater->update()
#5 /var/www/application/bookmark/BookmarkFileService.php(86): Shaarli\Bookmark\BookmarkFileService->migrate()
#6 /var/www/application/container/ContainerBuilder.php(97): Shaarli\Bookmark\BookmarkFileService->__construct(Object(Shaarli\Config\ConfigManager), Object(Shaarli\History), Object(malkusch\lock\mutex\FlockMutex), true)
#7 /var/www/vendor/pimple/pimple/src/Pimple/Container.php(118): Shaarli\Container\ContainerBuilder->Shaarli\Container\{closure}(Object(Shaarli\Container\ShaarliContainer))
#8 /var/www/vendor/slim/slim/Slim/Container.php(109): Pimple\Container->offsetGet('bookmarkService')
#9 /var/www/vendor/slim/slim/Slim/Container.php(164): Slim\Container->get('bookmarkService')
#10 /var/www/application/container/ContainerBuilder.php(110): Slim\Container->__get('bookmarkService')
#11 /var/www/vendor/pimple/pimple/src/Pimple/Container.php(118): Shaarli\Container\ContainerBuilder->Shaarli\Container\{closure}(Object(Shaarli\Container\ShaarliContainer))
#12 /var/www/vendor/slim/slim/Slim/Container.php(109): Pimple\Container->offsetGet('pageBuilder')
#13 /var/www/vendor/slim/slim/Slim/Container.php(164): Slim\Container->get('pageBuilder')
#14 /var/www/application/front/controller/visitor/ErrorController.php(20): Slim\Container->__get('pageBuilder')
#15 [internal function]: Shaarli\Front\Controller\Visitor\ErrorController->__invoke(Object(Slim\Http\Request), Object(Slim\Http\Response), Object(TypeError))
#16 /var/www/vendor/slim/slim/Slim/App.php(728): call_user_func_array(Object(Shaarli\Front\Controller\Visitor\ErrorController), Array)
#17 /var/www/vendor/slim/slim/Slim/App.php(396): Slim\App->handlePhpError(Object(TypeError), Object(Slim\Http\Request), Object(Slim\Http\Response))
#18 /var/www/vendor/slim/slim/Slim/App.php(297): Slim\App->process(Object(Slim\Http\Request), Object(Slim\Http\Response))
#19 /var/www/index.php(176): Slim\App->run(true)
#20 {main}
```

I then tried to use a fresh Shaarli install (deleting the contents of `data/`). I could then configure Shaarli successfully. All server requirements on the install page are met by the way. I tried then copying back the `datastore.php` (and later also `updates.txt`). The error then was simply: `You must specify an integer as a key`. Then I tried the suggestions in the [Troubleshooting section](https://shaarli.readthedocs.io/en/master/Troubleshooting/#you-must-specify-an-integer-as-a-key) to no avail. Same thing.

The only thing that kind of worked: I restored v0.11.1 and exported all my bookmarks to HTML, reinstalled a fresh v0.12.1 and restored them. All bookmarks were imported but I'm unsure if some metadata is lost in this process.

**Comment by ArthurHoaro** [comment]
Regarding your immediate issue, you should be fine with an export/import and you are not supposed to lose any data this way.

Now, you definitely have an issue with the automatic update process. My first suggestion would have been to delete the `updates.txt` file, but you already tried that apparently. 
If you are willing to spend some time on debugging this with me, without sharing your whole private data, I'd suggest that you add the following line in `Shaarli/application/legacy/LegacyLinkDB.php` line [137](https://github.com/shaarli/Shaarli/blob/820cae27cfcc94af552818f3f1e5342e00478f6c/application/legacy/LegacyLinkDB.php#L137) (just before the error message):

```
var_dump($offset);
var_dump($value);
```

and repeat the process that gave you `You must specify an integer as a key`.

**Comment by buzz** [comment]
```
string(15) "20170224_141935"
array(11) {
  ["title"]=>
  string(79) "An Epic Review of PyCharm 3 from a Vim User’s Perspective – Andrew Brookins"
  ["url"]=>
  string(106) "https://andrewbrookins.com/tech/one-year-later-an-epic-review-of-pycharm-2-7-from-a-vim-users-perspective/"
  ["description"]=>
  string(330) "Test output appears in a panel at the bottom of the window. If the test raises an exception, PyCharm converts each line of the stack trace into a hyperlink that opens the file in question at that line when I click on it.

Seems simple, right? After using these features for a year, I can’t live without them. Here’s why:

"
  ["private"]=>
  int(0)
  ["linkdate"]=>
  string(15) "20170224_141935"
  ["tags"]=>
  string(29) "pycharm emacs vim blog editor"
  ["real_url"]=>
  string(106) "https://andrewbrookins.com/tech/one-year-later-an-epic-review-of-pycharm-2-7-from-a-vim-users-perspective/"
  ["id"]=>
  string(15) "20170224_141935"
  ["created"]=>
  object(DateTime)#1294 (3) {
    ["date"]=>
    string(26) "2017-02-24 14:19:35.000000"
    ["timezone_type"]=>
    int(3)
    ["timezone"]=>
    string(13) "Europe/Berlin"
  }
  ["shorturl"]=>
  string(6) "2gY0SQ"
  ["sticky"]=>
  bool(false)
}
You must specify an integer as a key.
```

That `id` is indeed a string. I think I migrated some bookmarks a long time ago from the webiste del.icio.us. Could be one of them.

**Comment by ArthurHoaro** [comment]
Sorry the late answer. This is how ID were stored in an older version of Shaarli, which should be updated [here](https://github.com/shaarli/Shaarli/blob/820cae27cfcc94af552818f3f1e5342e00478f6c/application/legacy/LegacyUpdater.php#L246) during the migration process.

This change has been introduced in [v0.8.1](https://github.com/shaarli/Shaarli/releases/tag/v0.8.1) so you shouldn't have that even in v0.11.1. Maybe there was a bug at some point when you updated?

I just tried a simple v0.11 -> v0.12 upgrade and it seems to work properly. If that's ok with you, let's not waste time on this and close it.

**Comment by buzz** [comment]
> This change has been introduced in v0.8.1 so you shouldn't have that even in v0.11.1. Maybe there was a bug at some point when you updated?

Ah, I see. Thanks for clarification.

> If that's ok with you, let's not waste time on this and close it.

Sure
