### ISSUE TITLE
Turn off Daily

### ISSUE THREAD

**Issue by Maselia464** [shaarli/Shaarli#1712]
Is it possible to turn off the daily fonction ?

**Comment by yoanmalie** [comment]
I would love too! Same with "tag cloud",  "picture wall" as an options please 🙏.

**Comment by virtadpt** [comment]
You can edit the theme's template to comment out or delete those links.  That's what I did.

**Comment by aledeg** [comment]
Hiding it is not the same as turning it off! If you type the daily address, you can still access it. I guess that @Maselia464 was requesting was to not only remove the link but also remove the route itself.
My 2¢.

**Comment by yoanmalie** [comment]
Yep, + personally I don't want to edit the theme because I use the Material theme and if there an update this will erase my customization. I know I can fork it and track changes to apply them etc. But that totally different and not easy at all.

**Comment by nodiscc** [comment]
It is not required to edit the teplate. You can hide the daily button using [Custom CSS](https://shaarli.readthedocs.io/en/master/dev/Theming/#custom-css) in `data/user.css`, it will be preserved during upgrades. 

```css
#shaarli-menu-picwall{
  display: none
}
```

> If you type the daily address, you can still access it.

>Doctor, it hurts when I do this.
  >> Then don't do this...

**Comment by Maselia464** [comment]
> It is not required to edit the template. You can hide the daily button using [Custom CSS](https://shaarli.readthedocs.io/en/master/dev/Theming/#custom-css) in `data/user.css`, it will be preserved during upgrades.
> 
> ```css
> #shaarli-menu-picwall{
>   display: none
> }
> ```
> 
> > If you type the daily address, you can still access it.
> 
> > Doctor, it hurts when I do this.
> > > Then don't do this...

That should do the trick after all you can't click on what can't see

**Comment by Maselia464** [comment]
Hiding the css button is working for me.

Just if any other person want to do that you should copy the file just in case

Thank your time im closing this
