### ISSUE TITLE
Shaarli very slow after importing 1900 bookmarks from Firefox; how to improve performance?

### ISSUE THREAD

**Issue by sunrisepi** [shaarli/Shaarli#1715]
Hi.  I've been using Shaarli for a week (via Docker image) and like it a lot.  I backed up my Shaarli data/cache folders then decided to import my Firefox bookmarks and start using Shaarli on all my computers.  However, after importing my bookmarks (a total of 1900, which span 96 pages in Shaarli [for each page containing 20 entries]), it's very slow:

- Takes from 15-25 seconds to switch pages
- Takes 20 seconds to get "Tag cloud" link to load first time (sometimes it takes only about 5 seconds, so it must be caching something somewhere - but cache doesn't seem to persist as it can then take 20 seconds a few minutes later when I try again).
- From Tag cloud section, clicking on some tags takes 2 seconds to produce the list of bookmarks; others, 15-30 seconds.  

I'm using the latest version (v0.12.1) from https://github.com/shaarli/Shaarli.  I built my own Docker container from the source on my Raspberry Pi 4B (has 4GB of memory) and I am running in 32bit mode.  Thank you for providing the ARM dockerfile, very helpful!  :)  I have tried storing the data/cache files for the Shaarli Docker container on a USB hard drive as well as a microsd card, and the speed is about the same.

Other notes.. exported Firefox bookmarks file is 1.73MB in size.  I read this issue (#1449) about deleting the sqlite file in Firefox's user app directory to make the bookmarks smaller for the export.  I tried that, and the exported bookmark size was smaller (393KB).  I deleted the Shaarli data/cache folders, restored from backup I took initially, then ran another import.  It did import faster this time, but the performance of Shaarli is the same.  Very slow to switch pages, slow to get to Tag Cloud, slow most of the time to click on tags to load pages of links.  BTW I exported the bookmarks from Firefox 85.0.2 (64bit) on Windows 10.

While all this is happening, load on the Raspberry Pi is relatively low (doesn't get above 1.0).  The Pi isn't busy doing other things; it's reasonably idle, and Shaarli has the majority of the CPU available for use.  

For comparison:  Before importing bookmarks, Shaarli switches between pages in about 2 seconds, and Tag Cloud loads in only a couple of seconds.  But that's only with about 40 links added.

Additionally, I imported my Firefox bookmarks into [Shiori](https://github.com/go-shiori/shiori) and it was very fast.  I could switch pages instantly, and search was quick if I knew what I was looking for.  And while it seems to import tags (they show up in the UI), if I click the tags, sometimes it will load all the tagged links/bookmarks, and other times it will return nothing. So while Shiori is fast, the search functionality seems to have issues.  Plus, its UI is very plain.  I prefer Shaarli's, and wish to use it.  

I would appreciate some suggestions on how to get Shaarli to perform better.  I really like the interface and design, but if it is slow then I can't really use it.  :(  Thanks.

**Comment by sunrisepi** [comment]
No one else has had this issue?  OK.

FYI I have found something else; seems to work fast with all the links.  Perhaps Shaarli is not able to handle a large number of links?  Anyway, if others have an issue similiar to mine, try **linkding**: [https://github.com/sissbruecker/linkding](https://github.com/sissbruecker/linkding)

**Comment by nodiscc** [comment]
Hi,

This may be caused by thumbnail fetching (if thumbnails have never been retrieved yet, opening a page will try to fetch all thumbnails present on that page, the page will only displayed when all thumbnails retrievals are done). To confirm this, can you either:
 - Disable thumbnails (under `Tools > Configure your Shaarli > Enable Thumbnails: None`) and see if the problem persists?
 - Or force a full thumbnail synchronization (under `Tools > Server administration > Synchronize thumbnails`) and see if the problem persists?


Otherwise, can you enable `dev: true` in your [Shaarli Settings/config.json.php](https://shaarli.readthedocs.io/en/master/Shaarli-configuration/) and and check your server logs to see if there are relevant messages?

**Comment by sunrisepi** [comment]
Thanks @nodiscc, that fixed it!

- Disabled thumbnails, verified all the pages render quick and fast & Tag Cloud also quick to load
- Re-enabled thumbnails and ran a full thumbnail synch (took about 90 minutes to complete).  But when done, now all the pages load quickly and tag cloud also works fast when clicking Tag Cloud words, loading the results pages promptly.

Before it was taking 15-25 seconds to switch pages.  Now after the above was done, it only takes 1-3 seconds to switch pages and 1-2 seconds to load a selection of links by clicking on a Tag Cloud link. Searching for keywords in my bookmarks also takes only 1-2 seconds when using the search bar at the top of Shaarli.

Thanks very much for the suggestions.  Shaarli is now very fast again.  :)  Feel free to close my issue!

**Comment by nodiscc** [comment]
We could add a notice `If you imported a large number of bookmarks, please make sure thumbnails are [synchronized](admin/server) for better performance on first page loads.` to the [import completion message](https://github.com/shaarli/Shaarli/blob/master/application/netscape/NetscapeBookmarkUtils.php#L221).

First thumbnail loading/retrieval can also make Shaarli hang for a while if the thumbnailer has trouble accessing the target URL (eg. improper firewall configuration/outgoing HTTP requests not allowed).

Loading a page of 20 bookmarks takes ~400ms for me, setting links per page to 100 increases loading time up to ~800ms (not particularly fast server/VM - measured in firefox network tab). It's expected be to be a bit higher if you're running on SD card/USB2 disk. Feel free to update the issue with your own measures, always good to have.
