### ISSUE TITLE
Shaarli truncates my rel="me" link from Mastodon

### ISSUE THREAD

**Issue by mrtpcet** [shaarli/Shaarli#1720]
Hello,

If i put `<a rel="me" href="https://mamot.fr/@profile">Mastodon</a>` anywhere in the template, the result is : `<a rel="me" href="https://mamot.fr/"profile@>Mastodon</a>`

Thanks

**Comment by nicolasdanelon** [comment]
in order to help, this is not happening with the theme kalvn theme

**Comment by mrtpcet** [comment]
Thanks ! But same problem with kalvn theme and Shaarli 12.1

**Comment by ArthurHoaro** [comment]
Hi, it's an issue from the template engine. Unfortunately, it's not maintained anymore.

As a hackish workaround, you can use single quotes, it won't trigger its regexes:
```
<a rel="me" href='https://mamot.fr/@profile'>Mastodon</a>
```
