### ISSUE TITLE
SSO plugin with simpleSAMLphp

### ISSUE THREAD

**Issue by flashnet69** [shaarli/Shaarli#1721]
Hello,

I created a plugin allowing to make a connection to Shaarli via SSO, in particular simpleSAMLphp.

I get the project via a pull request that I added to my account but I don't know how to merge the plugin with your project. Would that interest you?

You can find the plugin via this link https://github.com/flashnet69/Shaarli

**Comment by nodiscc** [comment]
Hi @flashnet69 you could distribute your plugin as a standalone plugin (not a full Shaarli fork), and add it to the [list of third-party plugins](https://shaarli.readthedocs.io/en/master/Community-and-related-software/#related-software)

**Comment by ArthurHoaro** [comment]
You can open a pull request to update the documentation if you want to add it.

**Comment by flashnet69** [comment]
Thanks, i have send a update to the documentation
