### ISSUE TITLE
Links per page as a submenu (please test)

### ISSUE THREAD

**Issue by mrjovanovic** [shaarli/Shaarli#173]
So in an ongoing effort to remove clutter from the front page of shaarli, I implemented the links per page as a submenu here. Some advantages to this approach.

* Tries not to break existing themes, they all should theme and work fine with it.
* Has thumb-friendly buttons in mobile mode (see screenshot)
* Makes front page cleaner
* Gets rid of weird cutoff to the input field in Chrome (see screenshot).

Also, the search buttons are now properly centered in mobile mode in all browsers. 

Tested on Firefox/default Browser on Android Kit Kat, Firefox/Chromium on Debian and Firefox/Chrome/IE8 on Windows 7. It should all work fine. **Please help me test this** and give your opinions on the change before I submit a pull request.

Old (showing Chromium bug):
![2015-03-16-142634_1366x768_scrot](https://cloud.githubusercontent.com/assets/4664783/6674570/a4823fea-cbe8-11e4-86e3-7adbd678b939.png)

New with drop-down menu:
![2015-03-16-140334_1366x768_scrot](https://cloud.githubusercontent.com/assets/4664783/6674583/bc8207ce-cbe8-11e4-9175-91a71e39dd41.png)

New in mobile mode:
![2015-03-16-142949_1366x768_scrot](https://cloud.githubusercontent.com/assets/4664783/6674620/f027dbb2-cbe8-11e4-9e80-6338e0e84be5.png)

New using custom theme in mobile mode:
![2015-03-16-140235_1366x768_scrot](https://cloud.githubusercontent.com/assets/4664783/6674642/21d5a234-cbe9-11e4-980d-57a85a553781.png)

**Comment by mrjovanovic** [comment]
I forgot to add - the submenu could potentially have the option of filtering links from a specific date range, without cluttering the front page.

This was referenced in #106.

**Comment by nodiscc** [comment]
I did not have time to test this yet, just some impressions after looking at the screenshots:

 * I like it
 * Could the current setting be displayed next to "Links per page" (when the menu is folded)?
 * Padding in mobile mode is too damn huge
 * Befor you submit a PR, please base your changes on the current master (you can safely drop your `DefaultThemeRedesign` branch, previous commits were merged: `git checkout master; git pull shaarli master; git checkout -b linksperpage-submenu; git cherry-pick bb730fbabae33a59e69de31815f2a444753ae652; git push -u origin linksperpage-submenu; git branch -D DefaultThemeRedesign; git push origin :DefaultThemeRedesign`)

**Comment by mrjovanovic** [comment]
OK, cool, thanks for the lesson. :)

I tested the padding in mobile with my thumb, that's why it looks like that. I could easily reduce it a bit if you think that makes sense.

**Comment by nodiscc** [comment]
Well I didn't think about thumb-sized buttons, that makes sense, please keep it.
Congrats for doing it with only CSS. If you submit a patch with these changes I'd be ok with merging it (even though I'd like feedback from other contributors/users)

**Comment by nodiscc** [comment]
@mrjovanovic do you have a patch to propose for this? no hurry take your time

**Comment by mrjovanovic** [comment]
Well the branch is here ... https://github.com/mrjovanovic/Shaarli/tree/linksperpage-submenu

I don't have much time now, but I would like to figure out how to show the current settings next to the `Links per page ▼` text. This is also missing from the current version anyway. I am not sure where to start, I'd probably have to learn some things I don't know yet.. :)

**Comment by rubykat** [comment]
I definitely agree that showing the current setting of links-per-page is a wanted feature for this.

**Comment by mrjovanovic** [comment]
I understand, that makes sense, but I would like to note that the 
current implementation also doesn't show the current setting of 
links-per-page.

Any suggestions how I could go about doing this? I looked through the 
PHP stuff and there is a LINKS_PER_PAGE variable, but doing something 
like `<?php echo $LINKS_PER_PAGE; ?>` does nothing in the HTML.

I probably have no idea what I'm doing, so could use some help there, or 
I'll spend some more time learning and get back to it. 

Thanks for the input. :)

**Comment by rubykat** [comment]
>Any suggestions how I could go about doing this? I looked through the PHP stuff and there is a LINKS_PER_PAGE variable, but doing something like `<?php echo $LINKS_PER_PAGE; ?>` does nothing in the HTML.

That's probably because the variable in question is called $_SESSION['LINKS_PER_PAGE'] - try that and see what happens.

**Comment by mrjovanovic** [comment]
Hey, thanks so much in pointing me in the right direction. So, correct 
me if I'm wrong, if I want to do something like:

    <div class="paging_linksperpage">
        Links per page {$links_per_page}
    </div>

in `linklist.paging.html`, then I also need something like:

    $PAGE->assign('links_per_page',$_SESSION['LINKS_PER_PAGE']);

in `index.php`. Except that doesn't work! if you could maybe help me 
with this, or at least (kindly, again) point me in the right direction?  
You should be able to call PHP code from RainTPL templates with 
`{function=xxx}`, right?  except `{function=echo 
$_SESSION['LINKS_PER_PAGE']}` does nothing. as well...

I obviously don't know what I'm doing.. but I also don't know where to 
learn. I understand what some of the code is doing, but I also don't 
know the conventions of where things need to go.

Thanks for any advice you could give!

**Comment by nodiscc** [comment]
I've had some time to think about this.

 * Better with the old version: 1-click instead of 2.
 * Could be better with the new version: display the _current_ setting.

@mrjovanovic do you have a patch ready so we can test this? Or we might postpone this to later. I feel like the default template needs a proper rewrite from scratch...

**Comment by mrjovanovic** [comment]
Thanks for bumping this.

* The new version is also 1-click, it's on hover. The main points were to reduce clutter - in the old version, the option's function isn't self-evident *and* it takes up a lot of space. Likewise, the thumb-friendly buttons for mobile help.
* I would love to display the current setting, but I [haven't found how](https://github.com/shaarli/Shaarli/issues/173#issuecomment-95793540) to do it, sorry. Any other variable from `index.php`will show, except $_SESSION['LINKS_PER_PAGE']. 

A rewrite might be a good idea, I agree. :) It's just that I haven't had much free time to mess with this stuff.

**Comment by nodiscc** [comment]
Related https://github.com/shaarli/Shaarli/issues/266

**Comment by nodiscc** [comment]
Closing this in favor of https://github.com/shaarli/Shaarli/issues/266
