### ISSUE TITLE
3rd party plugin list : 404

### ISSUE THREAD

**Issue by timconsidine** [shaarli/Shaarli#1737]
Can't see list of other plugins :link gives 404 not found

https://shaarli.readthedocs.io/en/master/Community-and-Related-software/

**Comment by ArthurHoaro** [comment]
Seems to be a case issue: https://shaarli.readthedocs.io/en/master/Community-and-related-software/
Where did you find that URL?

**Comment by timconsidine** [comment]
Thank you

I saw it at bottom of documentation page for Plugins. - last section Third party plugins 
First saw it in my self-hosted but checked the main site also
<img width="1105" alt="Screenshot 2021-04-12 at 16 55 15" src="https://user-images.githubusercontent.com/28682881/114424392-f829c080-9baf-11eb-948e-3f6a8670fcc2.png">

**Comment by nodiscc** [comment]
thanks https://github.com/shaarli/Shaarli/pull/1738
