### ISSUE TITLE
Proposal to refactor Tools menu

### ISSUE THREAD

**Issue by mrjovanovic** [shaarli/Shaarli#174]
I feel that the current state of the tools menu is strange - it requires clicking and then opening up new pages for just one or two input fields.

I have made a mockup of the potential redesign of the tools section. What do you think?

Default appearance:
![g5076](https://cloud.githubusercontent.com/assets/4664783/6719685/59cb85b2-cd8a-11e4-851a-a32c82a3eb67.png)

Field changes on action/input:
![text5023](https://cloud.githubusercontent.com/assets/4664783/6719697/6b64d1d4-cd8a-11e4-91d5-5ba11b0d732e.png)

**Comment by nodiscc** [comment]
@mrjovanovic cool, I'd like having all the settings on a single page. Just note that it shouldn't depend on javascript to work properly. I suggest moving all config settings and tools directly on the `?do=tools` in the first time. A few notes about your mockups:

 * keep the original styles for now
 * separate import and export sections
 * keep 2 fields for the tag rename functionality (as it is now)
 * use square checkboxes

You can submit an incomplete Pull Request and we'll work on it.

**Comment by kalvn** [comment]
I like fact of having everything in one place but we need to ensure it doesn't become messy. 

For example I don't think that a 2-columns display is wise here.

And each section must be quickly indentifiable and clearly separated from the rest (with a visual separator or with enough margin/padding).

**Comment by nodiscc** [comment]
I agree about padding/separators.

About a 2-column layout, what do you suggest? We could keep a single column, but

 * you may would have to scroll (ie. you can't see all settings at once)
 * single column wastes screen space on desktop screens.

![wastedspace](https://cloud.githubusercontent.com/assets/3950390/6793155/0808017a-d1c1-11e4-8872-f98af9e1e43a.png)

A responsive 2 column layout may work, or may not. Thanks for your comment, other feedback welcome.

**Comment by mrjovanovic** [comment]
@kalvn 
Good point about lines as separators, I'll think that would help keep visual distinction. I can definitely include those.

As for the two-column layout - I do feel that a single-column is just incredibly wasteful on a desktop screen. My idea was to switch to single-column on mobile screens (currently set as screens below 480px). Could you maybe point out what you feel doesn't work in the two-column mockup? 

@nodiscc 
Is this a complete no-no on Javascript? If so, could you perhaps elucidate why? Some things I suggested can be done in pure CSS, so I would do that anyway.

Thanks for the useful feedback everyone! Really appreciate it.

**Comment by kalvn** [comment]
I agree for the waste of space but it's really easier to read a document which isn't too large. Take Github website for example, its width is limited and it improves readability. It's especially true for text content but I think it may apply also here.

But it's a personal feeling and I perfectly understand that other people may think differently. I just wanted to give my opinion on this point :)

**Comment by nodiscc** [comment]
> Is this a complete no-no on Javascript? 

Using javascript is ok, but ideally Shaarli should degrade gracefully when it's not enabled. What item  would you like to implement in JS on this page? Critical functions like password change or link export should work even without javascript. It also depends on whether or not it introduces dependencies on large JS libs (we just got rid of jQuery, yay).

>My idea was to switch to single-column on mobile screens (currently set as screens below 480px).

As long as there are separators this should be ok. Some padding on left/right would be cool though (width: 80% ?).

**Comment by nodiscc** [comment]
Closing as this hasn't been touched for a long time. Writing a new template from scratch and proposing it as default is ok, as discussed in other issues. Feel free to open a repo for this and a new issue.
