### ISSUE TITLE
Add new feature: small icon to open link on other browser

### ISSUE THREAD

**Issue by bcharest** [shaarli/Shaarli#1740]
That will be great to have a small icon for each link when you click on will open the link in a other browser. That will help to keep the shaarli web page always open.

What do you thing to add this feature ?

Tks for this project, this is a great tool 😀

**Comment by ArthurHoaro** [comment]
I don't think it's possible to have such a feature in web pages. One reason is that different browsers don't communicate with each other for obvious security reasons.

One solution would be to use a browser extension such as:

  * https://chrome.google.com/webstore/detail/open-in-firefox/lmeddoobegbaiopohmpmmobpnpjifpii
  * https://addons.mozilla.org/fr/firefox/addon/open-in-chrome-1/

Note that I didn't try those.
