### ISSUE TITLE
Update docker stable version to 0.11.x

### ISSUE THREAD

**Issue by hydrargyrum** [shaarli/Shaarli#1744]
The [README](https://github.com/shaarli/Shaarli/blob/master/README.md) states the stable version is 0.11.1.
However, the stable [version on dockerhub](https://hub.docker.com/r/shaarli/shaarli) uses shaarli 0.10.4 (that's what the footer says on every served shaarli page).

And see:

```
% docker run -it --entrypoint sh shaarli/shaarli:stable -c "grep v0 shaarli/README.md"
[![](https://img.shields.io/badge/stable-v0.9.7-blue.svg)](https://github.com/shaarli/Shaarli/releases/tag/v0.9.7)
[![](https://img.shields.io/badge/latest-v0.10.2-blue.svg)](https://github.com/shaarli/Shaarli/releases/tag/v0.10.2)
[![](https://img.shields.io/badge/master-v0.10.x-blue.svg)](https://github.com/shaarli/Shaarli)
```

**Comment by ArthurHoaro** [comment]
I will update it but note that the stable branch is deprecated. #1582

**Comment by hydrargyrum** [comment]
When it's done, what will be new tag on docker for the stable branch? `release`?

**Comment by ArthurHoaro** [comment]
There won't be any stable branch. It doesn't make sense regarding our release frequency (last v0.11 was release almost 2 years ago).

If you are afraid of breaking introduced bugs, you can still use deterministic version numbers.

BTW the Docker build is fixed: https://hub.docker.com/layers/shaarli/shaarli/stable/images/sha256-441d93a5c98169ce2973583712e1bee85790014452dcf252acf6bf85a9e6885a?context=repo

**Comment by hydrargyrum** [comment]
> If you are afraid of breaking introduced bugs, you can still use deterministic version numbers.

Pinning is always tricky as it prevents from benefiting of security fixes.
