### ISSUE TITLE
BUG: QR-Code generate works sometimes

### ISSUE THREAD

**Issue by Dtrieb** [shaarli/Shaarli#1745]
I didn't understand that:
Sometimes i can generate a QR-Code on my Desktop with the newest Chrome Browser, sometimes not.
With my Android Phone Chrome Browser it always works.

Any Ideas?

**Comment by ArthurHoaro** [comment]
Do you have any error in your browser console log when it doesn't work?

**Comment by ArthurHoaro** [comment]
I can't reproduce your issue and that error *should* not have any effect on the actual behavior of the script.

  * What's your Chrome version?
  * Do you reproduce that issue on demo.shaarli.org?

**Comment by nodiscc** [comment]
No reply for a year, closing.

**Comment by Dtrieb** [comment]
> * What's your Chrome version?
Version 112.0.5615.138 (Offizieller Build) (64-Bit)
> * Do you reproduce that issue on demo.shaarli.org?
No it work on the demo version
