### ISSUE TITLE
Missing permalink page title when logged in

### ISSUE THREAD

**Issue by kalvn** [shaarli/Shaarli#175]
As NerosTie noticed [here](https://github.com/kalvn/Shaarli-Material/issues/2), when displaying a permalink, the page title (title tag of the head of the html document) is correct when you are not logged in, but if you are, the title is not correct.

**Comment by alexisju** [comment]
:+1:

**Comment by nodiscc** [comment]
Fixed in https://github.com/shaarli/Shaarli/issues/190
