### ISSUE TITLE
"Database-free" is a hyphenated word, unlike the two words "super fast"

### ISSUE THREAD

**Issue by zylstra** [shaarli/Shaarli#1758]
The official description of Shaarli is currently "The personal, minimalist, super-fast, database free, bookmarking service by the Shaarli community".  To be more correct it should be "The personal, minimalist, super fast, database-free, bookmarking service by the Shaarli community".

**Comment by yfdyh000** [comment]
"The personal, lightweight, hold your data, bookmarking service by the Shaarli community".
Just an idea.

**Comment by zylstra** [comment]
hold-your-data would be hyphenated in this instance.

**Comment by nodiscc** [comment]
PR at https://github.com/shaarli/Shaarli/pull/2003
