### ISSUE TITLE
Add opensearch functionality

### ISSUE THREAD

**Issue by alexisju** [shaarli/Shaarli#176]
I just implemented opensearch plugins (by terms or by tags) into AlbinoMouse template but  it could be nice to add this functionnality by default.

It could also be better to generate xml file with index.php instead oh my hack (with shaarli's name instead url...). 

But the way i use for AlbinoMouse is pretty functionnal and don't need user customisation to work.

Look at https://github.com/alexisju/albinomouse-template/blob/master/inc/opensearch.searchtags.php or direcly at https://liens.effingo.be

PS: this current opensearch use https (because i use https on my domain and because its a good thing).
Credit : inspired by http://sourceforge.net/p/semanticscuttle/code/ci/master/tree/www/api/opensearch.php (another link manager)

**Comment by nodiscc** [comment]
Yes, let's do this, I see you use PHP to generate the `template` URL, so we may also use PHP to [generate the http/https protocol prefix](https://github.com/sebsauvage/MinigalNano/blob/master/rss.php#L6)

**Comment by alexisju** [comment]
https/http and path fixed in https://github.com/alexisju/albinomouse-template/commit/610bfc9d9b443637dbde98390b9b380d82ae586b

(but this code is a but uggly : it will be better to use shaarli's functions for that)

**Comment by nodiscc** [comment]
:+1:

If someone wants to make a Pull Request for that, I'm very ok (short on time these days)

**Comment by nodiscc** [comment]
@alexisju there are already https and path detection functions in SHaarli: `serverUrl()` and `indexUrl()`: https://github.com/shaarli/Shaarli/blob/master/index.php#L482

Can you use these functions in your script?

**Comment by ArthurHoaro** [comment]
That good and not invasive. We could implement it in the core instead of a plugin.

**Comment by nodiscc** [comment]
ok
