### ISSUE TITLE
Display Notes URLs as absolute in the linklist

### ISSUE THREAD

**Issue by nodiscc** [shaarli/Shaarli#177]
`<span class=linkurl` should show Notes permalinks as absolute URLs.

A marker like ![](https://camo.githubusercontent.com/499598b48f22fee0fafaebcac55bc4bda0611c9e/687474703a2f2f702e797573756b656b616d6979616d616e652e636f6d2f69636f6e732f7365617263682f66756775652f69636f6e732f737469636b792d6e6f74652e706e67) or ![](https://camo.githubusercontent.com/7ec532818d4bef0dfd4cef6c13ea86f8268d2433/687474703a2f2f702e797573756b656b616d6979616d616e652e636f6d2f69636f6e732f7365617263682f66756775652f69636f6e732f737469636b792d6e6f74652d70696e2e706e67) may be useful to distinguish notes from external links (now that the URL display is similar)

Requested at https://github.com/shaarli/Shaarli/issues/44#issuecomment-85668635

**Comment by ArthurHoaro** [comment]
Well, it's not that easy. Notes are currently saved as relative URLs (see line [1697](https://github.com/shaarli/Shaarli/blob/master/index.php#L1697)). We can change this behaviour but it won't change previous shaared notes.

In Projet-Autoblog we did this : https://github.com/mitsukarenai/Projet-Autoblog/blob/master/index.php#L100. I'm not sure it's 100% reliable (the return folder param doesn't matter here).

**Comment by nodiscc** [comment]
This is just about display, we can keep storing relative urls in the datastore. If an url is a permalink, display it like `indexUrl() . $url` (absolute url) in the linklist.

But it may mean running `if {preg_match()` on all links to determine if an url is a permalink before display. I'm not sure this is a good idea performance-wise.

**Comment by alexisju** [comment]
Maybe is it possible to do the same rss links works (and generate absolute url from a relative stored url?)

Actually is not just a design question, but also for future 3rd party plugins : for example in albinomouse my hack to share links on social media or by mail works fine.. except for notes (because relative link).

**Comment by pikzen** [comment]
>But it may mean running if {preg_match() on all links to determine if an url is a permalink before display. I'm not sure this is a good idea performance-wise.

We could run ten thousand preg_matches per page render and it would barely affect performance. Unless you're running Shaarli on a 8086.

Also, there's no need for preg_match(), just checking if the link starts with ? and is 7 chars long is more than enough. Just writing http:// is already 7 chars long so there's no way to go wrong. PR #180 fixes that.

**Comment by nodiscc** [comment]
https://github.com/shaarli/Shaarli/commit/a5752e776c9ee5ee5a711a76e8c8066ee88f7192 has mistakenly reverted this change...

**Comment by pikzen** [comment]
I'll pull the most recent changes and update the PR, hold on.

**Comment by nodiscc** [comment]
Fixed.
