### ISSUE TITLE
Bug: Shaarli returns 500 error on version 12.1 with a fresh install and backup data

### ISSUE THREAD

**Issue by Lyokolux** [shaarli/Shaarli#1770]
Hello (and great work by the way) !

I have already installed shaarli in the past and this time I am facing an error.
My data directory is currently a backup from my old shaarli instance.

The homepage returns a 500 error and the `errors.log` of nginx gives the following.
```
2021/06/25 16:31:13 [error] 17787#17787: *508 FastCGI sent in stderr: "PHP message: PHP Notice:  Undefined index: private in application/bookmark/LinkDB.php on line 295PHP message: PHP Notice:  Undefined index: url in application/Utils.php on line 127PHP message: PHP Notice:  Undefined index: title in application/Utils.php on line 128PHP message: PHP Notice:  Undefined index: description in application/Utils.php on line 129PHP message: PHP Notice:  Undefined index: tags in application/Utils.php on line 130PHP message: PHP Notice:  Undefined index: linkdate in application/bookmark/LinkDB.php on line 315PHP message: PHP Notice:  Undefined index: linkdate in application/bookmark/LinkDB.php on line 316PHP message: PHP Notice:  Undefined index: linkdate in application/bookmark/LinkDB.php on line 320PHP message: PHP Notice:  Undefined index: private in application/bookmark/LinkDB.php on line 295PHP message: PHP Notice:  Undefined index: url in application/Utils.php on line 127PHP message: PHP Notice:  Undefined index: title in application/Utils.php on line 128PHP message: PHP Notice:  Undefined index: description in application/Utils.php on line 129PHP message: PHP Notice:  Undefined index: tags in application/Utils.php on line 130PHP message: PHP Notice:  Undefined index: linkdate in application/bookmark/LinkDB.php on line 315PHP message: PHP Notice:  Undefined index: linkdate in application/bookmark/LinkDB.php on line 316PHP message: PHP Notice:  Undefined index: linkdate in application/bookmark/LinkDB.php on line 320PHP message: PHP Notice:  Undefined index: private in application/bookmark/LinkDB.php on line 295PHP message: PHP Notice:  Undefined index: url in application/Utils.php on line 127PHP message: PHP Notic
2021/06/25 16:31:13 [error] 17787#17787: *437 FastCGI sent in stderr: "Shaarli\Render\PageBuilder->assign('linkcount', 1)
#5 index.php(1953): renderPage(Object(Shaarli\Config\ConfigManager), Object(Shaarli\Plugin\PluginManager), Object(Shaarli\Bookmark\LinkDB), Object(Shaarli\History), Object(Shaarli\Security\SessionManager), Object(Shaarli\Security\LoginManager))
#6 {main}
  thrown in application/bookmark/LinkDB.php on line 182" while reading response header from upstream, client: 185.191.171.12, server: shaarli2.lyokolux.space, request: "GET /?addtag=tips HTTP/1.1", upstream: "fastcgi://unix:/var/run/php/php7.3-fpm.sock:", host: "shaarli2.lyokolux.space"
```

Current version:
* Shaarli 0.12.1 or 0.11.1
* php7.3

Any help is welcomed

**Comment by nodiscc** [comment]
Hi,

> application/bookmark/LinkDB.php

this file only exists in `v0.11`, in `v0.12` it was moved to `application/legacy/LegacyLinkDB.php`, so I assume your logs are from Shaarli v0.11 ?

Can you upgrade to v0.12.1? (https://shaarli.readthedocs.io/en/master/Upgrade-and-migration/ - I suggest using the release ZIP method, remember to keep backups before changing anything) and tell us if the problem persists? And describe the upgrade procedure/commands used/attach error logs if that is the case.

Performing a fresh v0.12.1 install and restoring `data/` from your backups should work without any special manipulation. Does it?

**Comment by Lyokolux** [comment]
Ok.
```bash
wget https://github.com/shaarli/Shaarli/releases/download/v0.12.1/shaarli-v0.12.1-full.zip
unzip shaarli-v0.12.1-full.zip 
sudo chown -R pi:www-data Shaarli
sudo chmod -R g+rX Shaarli
sudo chmod -R g+rwX Shaarli/{cache/,data/,pagecache/,tmp/}
```
I get the screen "Install Shaarli" (with https). Everything is normal, until I add my `data/` directory. So I suppose my data directory is currently corrupted.
I will try with an older backup on Sunday and I come back to this issue.

The installation with the zip file is definitely better :+1:

**Comment by Lyokolux** [comment]
Ok it was my bad.

My data directory has been corrupted. I changed my backup methods on March, and since then, the shaarli instance was not handled correctly. With the backups from the 6th March, I can make this works again.

Thanks for your time.

**Comment by nodiscc** [comment]
Good news. Yep, a reminder to test your backup restoration procedure on a regular basis. I use [`rsnapshot`](https://rsnapshot.org/) for automatic/daily/weekly/monthly backups, and do a manual restoration test every ~3-6 months in a development VM. I will also raise a monitoring alarm if there are no successful backups in the last 24h ![image](https://user-images.githubusercontent.com/3950390/123543429-eaf78900-d73d-11eb-936d-44c6b11a7680.png)
