### ISSUE TITLE
 markdown url rendering error when highlighting searched word in url

### ISSUE THREAD

**Issue by europrimus** [shaarli/Shaarli#1771]
I use the note function (no main url link) and the markdown syntax.
If I search for a word present in the the url, the highlighting process, highlight the word in the url.

This is an example to be more clear:
this note in markdown
```
[link text](https://github.com/sebsauvage/Shaarli)
```
normally rendered as
```
<div class="markdown"><p><a href="https://github.com/sebsauvage/Shaarli">link text</a></p></div>
```
if you search for **seb**, rendered as
```
<div class="markdown"><p><a href="https://github.com/<span class="search-highlight">seb</span>sauvage/Shaarli">link text</a></p></div>
```

**Comment by nodiscc** [comment]
hi @europrimus 

Is it the same problem as https://github.com/shaarli/Shaarli/issues/1681 and https://github.com/shaarli/Shaarli/issues/1735?

If it's the case, it is fixed on master but not released yet. Which shaarli version are you using/installation method (zip/source code+composer/docker/...) ?  Maybe we should do a bugfix release some time soon

**Comment by europrimus** [comment]
hi,
yes, it's a duplicate of #1735, sorry.

I'm using Shaarli 0.12.1 official release installed from zip file (or tar.gz).

It's a minor issue, but it's cool if it's fixed in next release.
