### ISSUE TITLE
JSON Parsing Error in config.json.php

### ISSUE THREAD

**Issue by bonfiredog** [shaarli/Shaarli#1776]
After changing the `links_per_page` option on `/data/config.json.php`, I keep getting this error:

```
An error occurred while parsing JSON configuration file (data/config.json.php): error code #4
➜ Syntax error
Please check your JSON syntax (without PHP comment tags) using a JSON lint tool such as jsonlint.com.
```

jsonlint does not return any JSON errors. I have `<?php /*` and `*/ ?>` around that JSON in the php file - is that correct? I didn't remember seeing the commenting-out before... however, removing it does not get rid of the error.

**Comment by ArthurHoaro** [comment]
Well, I guess you do have a JSON syntax error, at least for the PHP parser.

If you can't find it please share the entire file without the `credentials` section here.

The comment tag are correct, they are here to make sure that you config file will never be displayed, even your webserver is not configured properly.

**Comment by nodiscc** [comment]
@bonfiredog any news? Did you fix the problem/can you provide the requested file?

**Comment by nodiscc** [comment]
No reply for > a year, closing.
