### ISSUE TITLE
ParseDown Extra: Class 'DOMDocument' not found

### ISSUE THREAD

**Issue by ArthurHoaro** [shaarli/Shaarli#1777]
If I try to search (fulltext) for the keyword `array` I get this error:

> Error: Class 'DOMDocument' not found
> Class 'DOMDocument' not found
> /var/www/shaarli/vendor/erusev/parsedown-extra/ParsedownExtra.php477
> #0 /var/www/shaarli/vendor/erusev/parsedown-extra/ParsedownExtra.php(232): ParsedownExtra->processTag('

With rendering set to MarkdownExtra

**Comment by ArthurHoaro** [comment]
I can't reproduce it locally. It might be related to the PHP installation inside Docker. I will run a few more tests.

**Comment by yfdyh000** [comment]
> I can't reproduce it locally. It might be related to the PHP installation inside Docker. I will run a few more tests.

Me too, I can't reproduce it with `MarkdownExtra` & `master` inside Docker.

**Comment by nodiscc** [comment]
Can't reproduce it on 1.12.2 installed from release zip on apache/php-fpm

**Comment by nodiscc** [comment]
Still can't reproduce it on v0.12.2 installed from release zip, or on https://demo.shaarli.org. Cleaning up, closing, feel free to reopen if this bug manifests itself again.
