### ISSUE TITLE
Confused check box status for disable plugins

### ISSUE THREAD

**Issue by yfdyh000** [shaarli/Shaarli#1782]
In the /admin/plugins page, it provides a check box for each enabled plugin for disable the plugin, it show as like ☑ by default on Windows OS. There are two problems that should be unchecked by default, it should only generate reactions if the user mark it manually.

**Comment by ArthurHoaro** [comment]
I'm not sure to exactly understand what's the issue here.

Can you describe more precisely what is the behavior the you encounter and what should be the expected behavior. 
You can also add a screenshot or screencast if there is an issue with the checkbox rendering/behavior on Windows.

**Comment by yfdyh000** [comment]
![screenshot](https://user-images.githubusercontent.com/1769875/129464751-aa1b9c36-7b7b-4d25-930e-a5148a933aca.png)
This is my view on `/admin/plugins` page after initialization instance.

If the "Disable" checkbox is checked, the plugin should be disabled when saving config. But the checkbox show as an "Enabled" checkbox behaviors, it is checked by default and only changing the status of the plugin when the un-checked this box.
Also, I just noticed that the column heads is not aligned, although this is trivial.
