### ISSUE TITLE
Doc can't be entirely pulled on Windows.

### ISSUE THREAD

**Issue by pikzen** [shaarli/Shaarli#179]
NTFS (or Explorer depending on what Microsoft was thinking) does not support double quotes (") in filenames.

This conflicts with `doc\Mentions-of-Shaarli-in-"the-press".md`. Git then attempts to pull `"doc\Mentions-of-Shaarli-in-\"the-press\".md"`, and the file is nowhere to be found.

Fix: don't use quotes in slugs. Actually, don't use any special characters in slugs because they serve no purpose. If the current generator uses them to give a title to the document, solutions include using MultiMarkdown which allows metatags or using html tags in the document (which is explicitely allowed by Markdown)

**Comment by nodiscc** [comment]
Interesting. Anyway I deleted the mentioned page. There are too many mentions of le Shaarli on le Internet to count.
