### ISSUE TITLE
Empty datastore file raises an exception

### ISSUE THREAD

**Issue by Bravoboss** [shaarli/Shaarli#1796]
![del](https://user-images.githubusercontent.com/68810220/132104139-ac0a4537-1861-4ee5-b8b0-cca82197f611.png)

**Comment by nodiscc** [comment]
Please explain what actions led to this error, please describe your setup/versions/installation method, please describe what is expected instead of this message.

**Comment by Bravoboss** [comment]
-when i tried to open shaarli on browser this error showed.
-docker:arm-ugeek.
-i expect to see my bookmarks instead of this error .

**Comment by ArthurHoaro** [comment]
It looks like your are in an odd situation where the datastore file has been created but is empty?

Can you check the presence status and the content of the file `datastore.php` inside your Docker volume under `/var/www/shaarli/data`?

**Comment by Bravoboss** [comment]
What is inside datastore.php
![IMG_20210905_151849_392.jpg](https://user-images.githubusercontent.com/68810220/132126533-dc293fbd-6d70-4ab4-b0a0-6c4e8284abbd.jpg) 

What is inside data folder 

![IMG_20210905_151707_943.png](https://user-images.githubusercontent.com/68810220/132126554-1ad4f87d-664a-4417-b6d7-4976e033c519.png)

**Comment by Bravoboss** [comment]
Any updates ? 😅

**Comment by chhei** [comment]
I had exactly the same problem today, same error message when trying to access the Shaarli instance (v0.12.1). Running it using  `subdomain.example.com/shaarli`.  `datastore.php` has 0 bytes.

    -rw-r--r--. 1 user group  656 Sep  9 21:10 updates.txt
    -rw-r--r--. 1 user group  38K Sep  9 21:10 log.txt
    -rw-r--r--. 1 user group    0 Sep  9 21:10 lastupdatecheck.txt
    -rw-r--r--. 1 user group  271 Sep  9 21:10 ipbans.php
    -rw-r--r--. 1 user group    0 Sep  9 21:10 datastore.php
    -rw-r--r--. 1 user group 2.4K Sep  9 21:10 config.json.php
    -rw-r--r--. 1 user group    0 Sep  9 21:10 history.php
    -rw-r--r--. 1 user group 758K Sep  9 21:10 datastore.20210817221431_1.php
    -rw-rw-r--. 1 user group 292K Sep  9 21:10 import.2018-05-12.log

**Comment by ArthurHoaro** [comment]
You are talking about new installations, right?

Can you try to delete `datastore.php`? Do you have the same error?

@chhei How did you install your instance? On which OS?

**Comment by Bravoboss** [comment]
@ArthurHoaro 
If i delete datastore.php ,will i lose my data(saved bookmarks)?

**Comment by chhei** [comment]
@ArthurHoaro apologies for not putting this into the first message: 

- OS: CentOS 7 (running on [UberSpace](https://uberspace.de)
- Install: simple install using zip release of 0.12.1 and instructions [here](https://lab.uberspace.de/guide_shaarli.html)

**Comment by ArthurHoaro** [comment]
> If i delete datastore.php ,will i lose my data(saved bookmarks)?

So you are not talking about a new installation. I'm really sorry, but if your `datastore.php` file is empty, your data is already lost.
Which version of Shaarli are you using?

> Downgrading to v0.11.x seems to have worked for now, seems to be running w/o issues. Can the datastore.php file from v 0.12 used on a 0.11 version?

No, you can upgrade them without issues, but not downgrade. So it may be why your datastore file was corrupted?
Feel free to report any other issue you encounter, v0.12 has been around for a while and there shouldn't be any major issue.

**Comment by chhei** [comment]
@ArthurHoaro - thanks for the responses!

>> Downgrading to v0.11.x seems to have worked for now, seems to be running w/o issues. Can the datastore.php file from v 0.12 used on a 0.11 version?

> No, you can upgrade them without issues, but not downgrade. So it may be why your datastore file was corrupted?
Feel free to report any other issue you encounter, v0.12 has been around for a while and there shouldn't be any major issue.

Clear re down/upgrading, this is what I had assumed. 

The corruption happened before, running Shaarli v0.12.1 from a fresh install. Have followed the upgrade procedures from the manual (copy old `data` directory into fresh install). The corruption happened with a running 0.12.1 version - which had a number of issues - the baseURL was not set consistently, there were issues where I got a 'wrong' token message in the browser.

**Comment by Bravoboss** [comment]
@ArthurHoaro 
0.12.1

**Comment by nodiscc** [comment]
>  datastore.php has 0 bytes.

did you run out of disk space?
