### ISSUE TITLE
I write a bookmark toolbar plugin for fun

### ISSUE THREAD

**Issue by ghost** [shaarli/Shaarli#1802]
Based on v0.11.1, with a little change in the `index.php` file.

https://github.com/followgiant/Shaarli/commit/a0a0a9ce1c82944a685465a0298831053d500e02

![Snipaste_2021-09-25_01-17-50](https://user-images.githubusercontent.com/9292930/134717070-f993d7a2-a8be-4967-bbc0-fd62b1a427e3.png)

![Snipaste_2021-09-25_01-16-52](https://user-images.githubusercontent.com/9292930/134717093-d4f06ce3-30e2-4d8e-9739-c64b32fa1d80.png)

![Snipaste_2021-09-25_01-28-51](https://user-images.githubusercontent.com/9292930/134717110-2497728b-b75b-4a3c-ab54-2a664da80dcf.png)

**Comment by nodiscc** [comment]
Hi @followgiant what does this do? If I understand clearly:
- It shows a list of predefined tags in the toolbar
- It shows a list of all tags in the toolbar (?)

If you want to get this plugin in https://shaarli.readthedocs.io/en/master/Community-and-related-software/#third-party-plugins you should do the following:
- if it requires changes to `index.php` or other application files, please send a pull request with those changes _only_, explaining what your change does and why it is needed
- create a git repository containing only the plugin code, with a short README on how to install/configure it (you can look at other plugin examples in [third-party plugins](https://shaarli.readthedocs.io/en/master/Community-and-related-software/#third-party-plugins)
- add your plugin to [the list](https://github.com/shaarli/Shaarli/blob/master/doc/md/Community-and-related-software.md#third-party-plugins) and send a Pull Request

**Comment by nodiscc** [comment]
The code linked from the first comment in this issue seems to have disappeared (404).
Feel free to follow the steps above and submit your plugin to https://shaarli.readthedocs.io/en/master/Community-and-related-software.html
