### ISSUE TITLE
nginx: allow serving a static HTML page alongside Shaarli

### ISSUE THREAD

**Issue by wolfravenous** [shaarli/Shaarli#1803]
I am using Shaarli as a bookmarking site for my student IT workers.   It is hosted using nginx and accessed using the convention https://shaarli.domain.name/

 I have built a .htm page with the class schedules that I would like to link to in Shaarli.  I was hoping I could just put the .htm page in the root of the Shaarlie package and then link to it by using https://shaarli.domain.name/page_name.htm    However, when I try this the Shaarli package gives me a "Sorry, nothing to see here" page not found message.  

My question is:  Is there somewhere within the Shaarli package where I could place an .htm file that I can link to in Shaarli and then the page be displayed by nginx when someone clicks on the link in Shaarli???

**Comment by nodiscc** [comment]
Hi,
I assume you are using the nginx config detailed [here](https://shaarli.readthedocs.io/en/master/Reverse-proxy/#nginx). This config redirects **all** requests to `shaarli.mydomain.org` to php-fpm

```nginx
        location / {
            ...
            proxy_pass             http://localhost:10080/;
```

If you have a static HTML file  `/var/www/shaarli.mydomain.org/page.html`, you can try adding a more specific `location` block **before** the exsiting `location /` block (untested), to prevent passing this specific URL to php-fpm:

```nginx
        location /page.html {
            # just serve page.html, prevent passing requests to this URL to php-fpm
        }

        location / {
            proxy_set_header  X-Real-IP         $remote_addr;
            proxy_set_header  X-Forwarded-For   $proxy_add_x_forwarded_for;
            ...
            proxy_pass             http://localhost:10080/;
            ...
```

The `http` or `server` block must have the proper `root` location set, eg `root /var/www/shaarli.mydomain.org`

Check https://nginx.org/en/docs/http/ngx_http_core_module.html#location for details

**Comment by nodiscc** [comment]
@wolfravenous does this work for you?

**Comment by nodiscc** [comment]
No reply for > a year, closing.
