### ISSUE TITLE
Some features broken when using Tor or VPN to access Shaarli

### ISSUE THREAD

**Issue by 1xPdd** [shaarli/Shaarli#1809]
Hi. I'm running Shaarli 0.12.1 on Docker with Swag (which is just nginx) as a reverse proxy. I get the "Wrong Token" error if I access Shaarli from a VPN or Tor. Also descriptions are not automatically filled out. These work if I access the local IP without the reverse proxy and if access the reverse proxy but without Tor or VPN.

I have the "trusted_proxies" set to the reverse proxy IP and the Administration settings shows the Client IP as {reverse-proxy-IP}_{client-IP}. Is it possible to use the "trusted_proxies" to express that syntax (reverseproxy_a.b.c.d) where a.b.c.d change frequently, some kind of wildcard?

**Comment by nodiscc** [comment]
Hi,
please post your full configuration including webserver configuration and relevant logs.
