### ISSUE TITLE
Add Disqus or Isso comments box on a permalink page

### ISSUE THREAD

**Issue by NerosTie** [shaarli/Shaarli#181]
It could be very great to have a comments box on permalink pages.
Major improvment: you can chat! Instead of chatting via multiple "shaarli river" instances.

I'm trying to add this in shaarli for isso: 

```
<script data-isso="//sub.mydomain.tld/"
    src="//sub.mydomain.tld/js/embed.min.js"></script>
<div><section id="isso-thread"></section></div>
```

But I have no idea how "pages" work in shaarli.
Can you help me please?

http://posativ.org/isso/

(I think issue #175 must be fixed to work well, because Isso needs the title)

**Comment by nodiscc** [comment]
Hi, this is similar to previously requested "comment systems". It was decided that Shaarli could include external comments systems through plugins: have a look at the pull request https://github.com/shaarli/Shaarli/pull/164. It's not merged yet, but it provides a way to add custom elements to Shaarli's template.

Basically, using this branch, you can:

 * add `<script data-isso="//sub.mydomain.tld/" src="//sub.mydomain.tld/js/embed.min.js"></script>` to `tpl/plugins/isso/isso.includes.html` and it will be included in the page `<head>`
 * add `<div><section id="isso-thread"></section></div>` to `tpl/plugins/isso/isso.linklist.html` and it will be included for each link, in the link info bar.

I guess you need to specify different `id`s, else your isso comments thread will be the same for all displayed links. For example you could use somtehing like `id="isso-thread-$permalink"` and have each div render a different comments thread, I don't how isso handles that.

Anyway this is a very good use case for the planned plugin system, I can make changes to the pull request if you need more features/want to do things differently. Your ideas are welcome.

**Comment by NerosTie** [comment]
Thanks! I will wait the merge of #164 and I will try again.

**Comment by nodiscc** [comment]
@NerosTie I've read the isso doc and this should be doable, check https://github.com/nodiscc/Shaarli/blob/new-plugin-system/tpl/plugins/TODO.md. You would have to first click a permalink to see comments on this article. The linklist would only show a `0 comments`, `15 comments` counter for each shaarlink (no full comments threads in the linklist, only in permalink view)

**Comment by NerosTie** [comment]
I'm writing a plugin with Isso but I don't find how to activate it only on a permalink page.

I have this line: `if($data['_PAGE_'] == Router::$PAGE_LINKLIST){`

But it will activate the plugin on the homepage and this is not the expected behavior.

Thanks!

**Comment by ArthurHoaro** [comment]
We tried, but couldn't make it work because we weren't able to have a separate thread for different shaare. It looked like we could only have a thread based on the URL `index.php`/`?`.

https://github.com/ArthurHoaro/Shaarli/commit/5670545f709581e781fa11ecf7f91015e886c55e
(it's probably outdated because of search refactoring, but you want to enable it if you have 1 link in `$data`)

**Comment by NerosTie** [comment]
It seems to be more complicated than expected... (it was not that hard for Ghost).

Also, there is `Hashover`: https://github.com/jacobwb/hashover
In action: https://hal-9000.fr/?exgXpg

It could be an alternative.

**Comment by virtualtam** [comment]
Thanks @NerosTie for sharing :)

@ArthurHoaro looks like we're good to add a Hashover plugin ^^

**Comment by ArthurHoaro** [comment]
Yup, this looks good enough. @NerosTie, do you want to work on it?

**Comment by NerosTie** [comment]
@ArthurHoaro I can try, but I think I will have the same issue with the homepage.

**Comment by ArthurHoaro** [comment]
Ok, I'll look into it.

**Comment by ArthurHoaro** [comment]
Actually, I don't think we should make a Hashover plugin. Its code is rather low quality, and its configuration can't be externalized easily. But most importantly, home made encryption functions and storing clear passwords in the configuration file and cookies (!) make me worried about security.

**Comment by kalvn** [comment]
I made a quick Disqus plugin: https://github.com/kalvn/shaarli-plugin-disqus
Don't forget to set your Disqus shortname in the plugin administration page.

The tricky part was to ensure we are on the permalink page but it should work properly.
Let me know if you think it might be useful to add it as a default plugin and want to move it to the Shaarli repo.

**Comment by ArthurHoaro** [comment]
Other opinions are welcome, but I'd rather have a solution which doesn't rely on a commercial 3rd party in the main repo. Add it to the wiki though.

**Comment by kalvn** [comment]
I fully agree. I'll see what is doable with Isso.

**Comment by mro** [comment]
Maybe https://github.com/jacobwb/hashover-next is worth a look.

**Comment by NerosTie** [comment]
I have something for Isso but I need help:

https://github.com/NerosTie/isso/

It works, you can comment, but Isso can't find the title and the link is the same everywhere because permalinks begin with `?`

**Comment by ArthurHoaro** [comment]
That's what I said https://github.com/shaarli/Shaarli/issues/181#issuecomment-223409140

**Comment by NerosTie** [comment]
Exact, I forgot about this....

So, there is no possible solution?

**Comment by ArthurHoaro** [comment]
Except if we missed something, I'm afraid it can't work until they fix their `data-isso-id` tag, or add any way to specify the thread we're in.

**Comment by NerosTie** [comment]
There is a PR here: https://github.com/blatinier/isso/commit/f1325ccaca3cb73ec5916cd184cebb3e07f7e097

Maybe it helps

**Comment by ArthurHoaro** [comment]
> Maybe https://github.com/jacobwb/hashover-next is worth a look.

It looks way better! I'll try to end up with something.
Although, it's a lot of LOC, I think we should have a separate repo for this.

**Comment by kalvn** [comment]
Yes I think it would be better to keep things separated and only add this as a plugin for the client part.

**Comment by NerosTie** [comment]
Isso 0.10.5 has been released and there is this:

`clients can now use data-title to get the HTML title for a new page`

https://github.com/posativ/isso/pull/252
https://github.com/posativ/isso/releases/tag/0.10.5

Maybe it would help for the plugin in Shaarli?

**Comment by ArthurHoaro** [comment]
It's working! o/

**Comment by NerosTie** [comment]
Yeah! It's a good news! :tada:

**Comment by NerosTie** [comment]
So, it works? Can I close this issue? (I can't test it right now, unfortunately)

**Comment by ArthurHoaro** [comment]
Yup. I don't use it, but give us your feedback if you have the time to test it.

**Comment by poVoq** [comment]
Has there ever been any additional work on integrating Hashover-next or a similar php based comment application? Isso is cool, but needs Python which isn't available on many shared-hosts that Shaarli runs on.

**Comment by ArthurHoaro** [comment]
Not that I'm aware of. Feel free to provide PR or open another issue regarding a Hashover-next plugin though.

**Comment by poVoq** [comment]
Made a alpha version of a plugin that integrates Hashover-Next:
https://github.com/poVoq/shaarli-plugin-hashover-comments
