### ISSUE TITLE
Documentation leads to error 403

### ISSUE THREAD

**Issue by Iv4nd1** [shaarli/Shaarli#1819]
Hello,

I have installed Shaarli v0.12.1.

Issue : 
The Documentation link that is available at the bottom of the main page lead to an error 403 Access Denied.

Software stack :
Apache 2.4.51
PHP 7.4.25
Debian 11

vhost config using the best practices of the Shaarli official documentation :
https://hastebin.milkywan.fr/atipuyeyiy.apache

htaccess debug log :
https://hastebin.milkywan.fr/ijujugoxex.yaml

Thank you.

**Comment by nodiscc** [comment]
I can reproduce the problem on v0.12.1 installed from release ZIP, apache/php-fpm with the recommended config.
