### ISSUE TITLE
Date of daily/dailyrss still hard formatted

### ISSUE THREAD

**Issue by alexisju** [shaarli/Shaarli#182]
Even with https://github.com/shaarli/Shaarli/commit/bec18701801cc140d760c261dd115fda1507a0dd (Define date format in templates), date title of daily.html and dailyrss.html still hard formatted into the index.php 

    $daydate = utf8_encode(strftime('%A %d, %B %Y',linkdate2timestamp($day.'_000000'))); // Full text date
    $PAGE->assign('day',utf8_encode(strftime('%A %d, %B %Y',linkdate2timestamp($day.'_000000'))));

For example, with french locale detected, the date displayed is : "lundi 16, mars 2015"

**Comment by alexisju** [comment]
?do=dailyrss still display "hardcoded" date on the first rss entry (date next to the shaarli's name / FeedContent). (FeedEntryContent is ok)

 ```
<?xml version="1.0" encoding="UTF-8"?><rss version="2.0"><channel><title>Daily - demo</title><link>http://shaarlidemo.tuxfamily.org/Shaarli/</link><description>Daily shared links</description><language>en-en</language><copyright>http://shaarlidemo.tuxfamily.org/Shaarli/</copyright>
<item><title> ** demo - lundi 06, juillet 2015 ** </title><guid>http://shaarlidemo.tuxfamily.org/Shaarli/?do=daily&amp;day=20150706</guid><link>http://shaarlidemo.tuxfamily.org/Shaarli/?do=daily&amp;day=20150706</link><pubDate>Mon, 06 Jul 2015 00:00:00 +0200</pubDate>
<description><![CDATA[
	<h3><a href="https://github.com/shaarli/Shaarli/wiki"> Shaarli: the personal, minimalist, super-fast, no-database delicious clone</a></h3>
	<small>lun 06 jui 2015 21:20:40 CEST - opensource software<br>
	https://github.com/shaarli/Shaarli/wiki</small><br>
	<br>
	Welcome to Shaarli! This is your first public bookmark. To edit or delete me, you must first login.<br />
<br />
To learn how to use Shaarli, consult the link &quot;Help/documentation&quot; at the bottom of this page.<br />
<br />
You use the community supported version of the original Shaarli project, by Sebastien Sauvage.
	<br><br><hr>
]]></description>
</item>

</channel></rss><!-- Cached version of http://shaarlidemo.tuxfamily.org/Shaarli/?do=dailyrss -->
```

**Comment by ArthurHoaro** [comment]
As I said in my PR,

> daily RSS feed is not generated through templates. Date are still hard formatted in that case.

If you feel like that's really an issue, maybe we can think of a way to fix it.

**Comment by alexisju** [comment]
It is an issue as long is not possible to fix that in a template or without make modifications of index.php. But it is not critical (to be honest, i dont use this feed). On the other side, another way to consider this is thinking about how implement a multilanguage shaarli (cfr https://github.com/shaarli/Shaarli/issues/106).
