### ISSUE TITLE
need a startpage to pin favorite links

### ISSUE THREAD

**Issue by andrewchenshx** [shaarli/Shaarli#1822]
hope there would be a startpage to pin favorite links, just as [Flame](https://github.com/pawelmalak/flame) do,
i would be perfect if it could be archieved within Shaarli.
cheers,

**Comment by nodiscc** [comment]
You can already pin shaares to the first page.
A different layout can be achieved through a custom template.
All in all I don't think Shaarli and Flame serve the same purpose.
Shaarli is a bookmark manager and link sharing platform.
Flame is a personal start page.

> just as Flame do

The just use Flame for this? Or any other startpage?
