### ISSUE TITLE
Tags : @ non trouvé affiché si dans la description

### ISSUE THREAD

**Issue by bonnebulle** [shaarli/Shaarli#1830]
Bonjour
J'utilise `@` dans mes tags ( `#@auteur` ) qui ne sont pas toujours retrouvés ou filtrés quand je les cherche...

Ca marche, les liens/notes les contenant sont affichés :
- Quand j'ajoute ces tags dans le champ dédié (durant la publication de mon lien/note).., 
- Ils sont aussi transformés en tags clicables à l'intérieur du texte de description. 

Mais par contre
- les liens/notes qui les contiennent dans le corps du texte/description uniquement ne sont pas trouvés.cherchés.affichés quand je les demande depuis l'outil de recherche (ou addtag)

Je pense que c'est un bug mais je suis pas sûr.

( translate, short version
The tag starting with `@mytag` added as tag in the dedicated field are displayed when searching them.
But when I add `@mytag` directly in the body of the text-description, it is not display when I searching it.
So I need to add it in the body and the tag field (linklist-item-tags) if I want to find them with the search engine.. )

Merci par avance
Thanks all :)

**Comment by bonnebulle** [comment]
Test : 
Sur mon shaarli avec `@Philippe_Borrel` 
https://liens.vincent-bonnefille.fr/?searchtags=@Philippe_Borrel
devrait afficher
https://liens.vincent-bonnefille.fr/?F6Mt6Q ( qui contient `#@Philippe_Borrel` )

**Comment by nodiscc** [comment]
>  The tag starting with @mytag added as tag in the dedicated field are displayed when searching them.
> But when I add @mytag directly in the body of the text-description, it is not display when I searching it.

When you use `Filter by tag`, only the `tags` field is searched for matches, so this is normal.

If you want to search for `@something` in **descriptions**, you must use the `Search text` field.
