### ISSUE TITLE
I can't figure out the docker setup

### ISSUE THREAD

**Issue by TheOtterslider** [shaarli/Shaarli#1831]
So, I can't figure out how to get the docker image up and running partially because I can't figure out what I need to do.  I can't figure out what to do because I can't figure out the instructions on this page:  https://shaarli.readthedocs.io/en/master/Docker/#get-and-run-a-shaarli-image

My main question:  do I need a Dockerfile or not?  Are there build steps that are necessary?  The docker-compose at https://raw.githubusercontent.com/shaarli/Shaarli/latest/docker-compose.yml wants to run some build steps yet the docker run steps earlier on that page don't reference any build and are supposed to give a complete running version of Shaarli.

I know this is a real noob issue, but it feels like the image is out of date or sync with the instructions.

**Comment by TheOtterslider** [comment]
Well, scratch this.  It all builds ok now, but it's like nothing is served up.

**Comment by TheOtterslider** [comment]
Ok.  I'm back to not having a clue.  I've tried reading the documents and get conflicting information.  I'd volunteer to work on rewriting it if I knew some things.

1. I'm pretty sure I need to start things by git cloning into a directory even if I'm using docker, correct?
2. I don't want to use traefik as I've got an existing docker image I use to reverse proxy everything.  As such, it owns ports 80 and 443 already.  I edit the docker-compose.yml file (I'll put it at the end)
3. do I have to build anything?  I think so but the default docker run example doesn't appear to need it
3. I can't figure out what port I should have my reverse proxy connect to.  

- The instructions here make it look like the default shaarli image serves up on port 8000 (https://shaarli.readthedocs.io/en/master/Docker/#get-and-run-a-shaarli-image / the docker run command maps port 8000 on the image to local port 80).  So I send my reverse proxy to port 8000?
- The default docker-compose file doesn't look like traefik does anything special....  So I use port 80?
- The reverse proxy section says I need to use port 10080 (https://shaarli.readthedocs.io/en/master/Reverse-proxy/ )... So do I need to have my reverse proxy do that?

4. The reverse proxy section also talks about editing data/config.json.php . I guess I need to do that if I'm just using my reverse proxy??

Right now, I'm just all confused because what I read in the docs doesn't seem to line up with anything.  Because nothing agrees with itself, I can't figure out what I'm doing wrong.

The best I've got right now is my reverse proxy throwing 400 errors....  Here's what I do:

1. git clone https://github.com/shaarli/Shaarli.git [LOCALDIR]
2. edit docker-compose.yml to be what's at the end
3. run docker-compose build
4. run docker-compose up -d
5. attach the shaarli container to a network I have set up so that my reverse proxy can see everything
6. I am trying to run shaarli as a sub-directory (www.MyDomain.com/shaarli ).  I'll put my nginx reverse proxy config below too

My docker-compose.yml file
`
version: '3'

services:
  shaarli:
    image: shaarli/shaarli:latest
    build: ./
    volumes:
      - ./TheDockerData/shaarli-cache:/var/www/shaarli/cache
      - ./TheDockerData/shaarli-data:/var/www/shaarli/data
`
My reverse proxy conf file
`
location ^~ /shaarli/ {
        proxy_pass http://DockerImageName/;

 #       proxy_pass             http://localhost:10080/;
        proxy_set_header Host  $host;
        proxy_connect_timeout  30s;
        proxy_read_timeout     120s;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $remote_addr;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

`

**Comment by TheOtterslider** [comment]
I've sorted out how to get the nginx server on the shaarli image to show me the error log.  Here's what's going on there.  It looks like a permissions error; however, I can't find the file Logger.php in my [LOCALDIR] director anywhere (this is the one where I did the git cloneinto).

2022/01/29 20:44:28 [error] 11#11: *1 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught RuntimeException: The file could not be opened. Check permissions. in /var/www/shaarli/vendor/katzgrau/klogger/src/Logger.php:134
REVERSE_PROXY_IP - - [29/Jan/2022:20:44:28 +0000] "GET / HTTP/1.0" 500 0 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:96.0) Gecko/20100101 Firefox/96.0"
      
Stack trace:
#0 /var/www/shaarli/index.php(59): Katzgrau\KLogger\Logger->__construct()
      
}
  thrown in /var/www/shaarli/vendor/katzgrau/klogger/src/Logger.php on line 134" while reading response header from upstream, client: REVERSE_PROXY_IP, server: , request: "GET / HTTP/1.0", upstream: "fastcgi://unix:/var/run/php-fpm.sock:", host: "www.MYDOMAIN.com"
2022/01/29 20:44:33 [error] 11#11: *3 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught RuntimeException: The file could not be opened. Check permissions. in /var/www/shaarli/vendor/katzgrau/klogger/src/Logger.php:134
      
Stack trace:
#0 /var/www/shaarli/index.php(59): Katzgrau\KLogger\Logger->__construct()
      
}
  thrown in /var/www/shaarli/vendor/katzgrau/klogger/src/Logger.php on line 134" while reading response header from upstream, client: REVERSE_PROXY_IP, server: , request: "GET / HTTP/1.0", upstream: "fastcgi://unix:/var/run/php-fpm.sock:", host: "www.MYDOMAIN.com"
REVERSE_PROXY_IP - - [29/Jan/2022:20:44:33 +0000] "GET / HTTP/1.0" 500 0 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:96.0) Gecko/20100101 Firefox/96.0"
2022/01/29 20:45:10 [error] 11#11: *5 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught RuntimeException: The file could not be opened. Check permissions. in /var/www/shaarli/vendor/katzgrau/klogger/src/Logger.php:134
      
Stack trace:
#0 /var/www/shaarli/index.php(59): Katzgrau\KLogger\Logger->__construct()
      
}
  thrown in /var/www/shaarli/vendor/katzgrau/klogger/src/Logger.php on line 134" while reading response header from upstream, client: REVERSE_PROXY_IP, server: , request: "GET /index.php HTTP/1.0", upstream: "fastcgi://unix:/var/run/php-fpm.sock:", host: "www.MYDOMAIN.com"
REVERSE_PROXY_IP - - [29/Jan/2022:20:45:10 +0000] "GET /index.php HTTP/1.0" 500 0 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:96.0) Gecko/20100101 Firefox/96.0"
2022/01/29 20:51:09 [error] 11#11: *7 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught RuntimeException: The file could not be opened. Check permissions. in /var/www/shaarli/vendor/katzgrau/klogger/src/Logger.php:134
      
Stack trace:
#0 /var/www/shaarli/index.php(59): Katzgrau\KLogger\Logger->__construct()
      
}
  thrown in /var/www/shaarli/vendor/katzgrau/klogger/src/Logger.php on line 134" while reading response header from upstream, client: REVERSE_PROXY_IP, server: , request: "GET /index.php HTTP/1.0", upstream: "fastcgi://unix:/var/run/php-fpm.sock:", host: "www.MYDOMAIN.com"
REVERSE_PROXY_IP - - [29/Jan/2022:20:51:09 +0000] "GET /index.php HTTP/1.0" 500 0 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:96.0) Gecko/20100101 Firefox/96.0"
2022/01/29 20:51:11 [error] 11#11: *9 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught RuntimeException: The file could not be opened. Check permissions. in /var/www/shaarli/vendor/katzgrau/klogger/src/Logger.php:134
      
Stack trace:
#0 /var/www/shaarli/index.php(59): Katzgrau\KLogger\Logger->__construct()
      
}
  thrown in /var/www/shaarli/vendor/katzgrau/klogger/src/Logger.php on line 134" while reading response header from upstream, client: REVERSE_PROXY_IP, server: , request: "GET /index.php HTTP/1.0", upstream: "fastcgi://unix:/var/run/php-fpm.sock:", host: "www.MYDOMAIN.com"
REVERSE_PROXY_IP - - [29/Jan/2022:20:51:11 +0000] "GET /index.php HTTP/1.0" 500 0 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:96.0) Gecko/20100101 Firefox/96.0"

**Comment by Rodelanuit** [comment]
Hello,

From my understanding, it's a permission issue with data and cache folder : https://github.com/shaarli/Shaarli/issues/1349

Two possibilities seems possible : create volume or change owner of data/cache (id 100/101 as image nginx user is 100:101).

Not a docker expert here, so feel free to correct me if i'm wrong.

Regards.

**Comment by avks** [comment]
@Rodelanuit yes, that actually was the problem. Solved it with `chown`
