### ISSUE TITLE
Archive Websites

### ISSUE THREAD

**Issue by djusHa** [shaarli/Shaarli#1834]
Good morning,

is there an ability to Archive Websites like Shiori does?
Would be a nice Feature.

**Comment by nodiscc** [comment]
Hi @djusHa 

> is there an ability to Archive Websites like Shiori does?

There is not. Check https://github.com/shaarli/Shaarli/issues/318 which lists a few possible workarounds. I was planning a full refactoring of [shaarchiver](https://github.com/nodiscc/shaarchiver/) (currently broken) but don't have time to work on it at the moment.
