### ISSUE TITLE
really can't get thumbs with shaarli 0.12.1 (shared hosting)

### ISSUE THREAD

**Issue by lmjst** [shaarli/Shaarli#1838]
Since I upgraded to shaarli 0.12.1 from shaarli 0.11.1 months ago I can't get the thumbnails working. 

What I see:
# on page admin/server:
Version Current version v0.12.1
Latest release v (link is dead by the way)
Thumbnails Thumbnails status All

 Click on "Synchronize thumbnails "

# on page admin/thumbnails:
Thumbnails update 0 / 519

# on page picture-wall?
"Picture Wall - 275 pics"
But no thumb is displayed

When hover on the blank screen, darker squares are visible where thumbs should be displayed with title of the links in white color (with link to url).

# Inspecting this link in firefox gives : 
`<img data-src="/cache/thumb/1ed7a5dc34bc8c93fe268aac750fe0cd/2b25e3c7578cc9bf1ac68e9a5a9d3398ee8f6b2a125901.jpg" class="b-lazy b-error" src="" alt="" width="125" height="90">`

and of course console error
404
Not Found
VersionHTTP/2
for file cache/thumb/1ed7a5dc34bc8c93fe268aac750fe0cd/2b25e3c7578cc9bf1ac68e9a5a9d3398ee8f6b2a125901.jpg

There is nothing in the /cache folder on the server. How should this /cache/thumb/ be populated ?

I believe I'll finally revert to shaarli 0.11.1 since the "Daily Weekly Monthly" view is a nice engaging view and want to use it in a kind of newsletter, but without any pic it's not really an option.

thanks
dd

**Comment by nodiscc** [comment]
Hi @lmjst,
- which [installation method](https://shaarli.readthedocs.io/en/master/Installation/) are you using?
- do you have any errors in your webserver logs when the problem happens (copy paste web/php server logs here)?
- do you have any errors in your browser console when the problem happens (copy-paste full console messages here)?

you can paste log contents between triple backticks for better formatting:

````
```
like this
```
````

Make sure the following directories are writable by your webserver user (typically `www-data`):
 - data/
 - tmp/
 - cache/
 - pagecache/

**Comment by lmjst** [comment]
Thanks for your help.
I guess it has to do with the remote server since I transfer my local shaarli to the server and it still doesn't want to show the thumbnails on the server but it's working perfectly locally.
The only difference is the URL : locally it's 127.0.0.1/shaarli and on the server it's https://shaarli.site.net

The only error I see is: 
`<img data-src="/cache/thumb/3855f10929da66abcacdbf463558f3da/02db2f5ab9043edb1081e0bad36e2b7670fa6bcb125901.jpg" class="b-lazy **b-error**" src="" alt="" width="125" height="90">`

whereas locally there is no **b-error**": 
`<img class="b-lazy b-loaded" src="/links/cache/thumb/3855f10929da66abcacdbf463558f3da/02db2f5ab9043edb1081e0bad36e2b7670fa6bcb125901.jpg" alt="" width="125" height="90">`

Don't know why on one side it is:
`<img data-src="...`
and on the other side:
`<img class="b-lazy b-loaded" src="....`

**Comment by nodiscc** [comment]
do you have any errors in your webserver logs when the problem happens (copy paste web/php server logs here)?

**Comment by nodiscc** [comment]
ping @lmjst

**Comment by lmjst** [comment]
Trying again...
There is nothing in the error log of the browser console, nothing in the log of the server.
I just found this in a stat report:

```
site URLs not found (Code HTTP 404) 	 
URL (152)	Hits missed	Origine/Referer
/cache/thumb/c2e3c74586909292fd235ef7e590d9ee/795bfdcf68179008affd589a857604fbb0a8e66b125901.jpg	10	https://links.mysite.fr/picture-wall

```

**Comment by nodiscc** [comment]
Since you are using shared hosting, this is likely caused by a security setting on your hosting provider's side (see for example https://shaarli.readthedocs.io/en/master/Troubleshooting/ -> `Error 406 "Not acceptable"`, since you don't have this error at all, I guess your provider may simply be blocking all outbound HTTP requests?)

Shaarli needs to be able to contact the remote server over HTTP to parse the page and extract/download the thumbnail. Failure to do this will result in the thumbnail not being cached/downloaded (hence errors 404/no thumbnails).

You should check your hosting provider's security restrictions and/or contact their support line to ask for more information/the restriction to be removed (allow the server to contact any host over HTTP/HTTPS).

**Comment by lmjst** [comment]
OK thanks for your  response and explanation. I'll see with the hosting provider
