### ISSUE TITLE
Autolocate doesn't work anymore?

### ISSUE THREAD

**Issue by alexisju** [shaarli/Shaarli#184]
I don't find this commit https://github.com/shaarli/Shaarli/commit/880cbf92ca0ee87a4b10a0621e44aa70d019aff7 in latest version of index.php

Autolocate doesn't work anymore for me.

**Comment by nodiscc** [comment]
Thanks for reporting it. This code was also nuked in the bogus merge commit https://github.com/shaarli/Shaarli/commit/d3b2b456e174a7a4de67bf39460749cc35a6e382. Sorry for the inconvenience, I don't know what went wrong. I'll fix this soon, patches are also welcome.

**Comment by nodiscc** [comment]
It should be fixed.
