### ISSUE TITLE
Pi

### ISSUE THREAD

**Issue by aashish108** [shaarli/Shaarli#1841]
Hey there, just realised Shaarli does not support ARMv7 platform, is it easy to implement or you are not interested in doing that?

**Comment by virtadpt** [comment]
You should be able to install Apache and PHP normally on the RasPi (guessing Raspbian) and then use the regular installation process for Shaarli.  What are you trying to do?

**Comment by nodiscc** [comment]
related to https://github.com/shaarli/Shaarli/issues/1048 and more generally build tools improvements planned for 1.0.0

**Comment by nodiscc** [comment]
In fact a duplicate of https://github.com/shaarli/Shaarli/issues/1048, Shaarli does not provide ARM Docker images.

@aashish108 in the mean time you should be able to use another [installation](https://shaarli.readthedocs.io/en/master/Installation/) method, or build the images yourself.
