### ISSUE TITLE
Not display month=202202

### ISSUE THREAD

**Issue by einheft** [shaarli/Shaarli#1844]
Sorry my poor English.

My Shaarli site do not display Monthly page, "February 2022". 

I researched other Shaarli sites, found same phenomenon. For example, the following sites.
- [Monthly \- March, 2022 \- kalvn's links](https://links.kalvn.net/daily?month)
- [Monthly \- March, 2022 \- Slobberbone's links](https://shaarli.slobberbone.net/daily?month)
- [Monthly \- March, 2022 \- CAILAB Home](http://video.cailab.net/bookmarks/daily?month)
- [Monthly \- March, 2022 \- Sécurité & informatique](https://nuage.lolifant.net/samuel-shaarli/daily?month)

In all sites, I clicked link "Previous month" (daily?month=202202) , not display page 202202.

Maybe this is a bug? Please any ideas to solve this problem.

**Comment by kcaran** [comment]
https://stackoverflow.com/questions/21473817/wrong-month-february-datetimecreatefromformat

This will happen at the end of the month where the day is greater than the last day of February (29th, 30th, 31st). I bet it will happen for more months tomorrow on the 31st, but it will resolve itself on Friday, April 1st.

**Comment by kcaran** [comment]
Hi einheft. It most certainly is a bug, just one that doesn't always appear. Would you open the issue back up? I'm working on a pull request for it.****

**Comment by einheft** [comment]
OK. I opened this issue again.

**Comment by nodiscc** [comment]
I can reproduce this on v0.12.1 installed from release zip
