### ISSUE TITLE
Tag links in listings don't contain the tags

### ISSUE THREAD

**Issue by BeecherNetworks** [shaarli/Shaarli#1846]
If I click a tag on a save in the Shaarli demo, that is one of "shaarli" or "help", the link is "?/add-tag/shaarli" or "/add-tag/help". However on my install, the link on ALL tags is just "/add-tag/", the tag isn't appended. I've disabled all plugins and reverted the theme just in case. My install is completely private but I can give access if necessary.

**Comment by nodiscc** [comment]
Please post your full webserver/virtualhost configuration, the [installation](https://shaarli.readthedocs.io/en/master/Installation/) method used/Shaarli version, webserver/PHP error logs

**Comment by BeecherNetworks** [comment]
Apologies, I should have mentioned that it's a bog-standard docker install.

**Comment by BeecherNetworks** [comment]
I recreated Shaarli and copied my data folder in and the problem resolved itself.
