### ISSUE TITLE
Atom not displayed if Shaarli in subdir

### ISSUE THREAD

**Issue by Draky50110** [shaarli/Shaarli#1847]
Hello.

I don't know why my atom feed gives a 404 : https://parigotmanchot.fr/liens/feed/atom?

Maybe an explanation : Shaarli is installed in a WordPress install subdir.
This WP instance has a .htaccess, don't know if it is a problem...

**Comment by nodiscc** [comment]
>  This WP instance has a .htaccess, don't know if it is a problem...

Maybe.

Please post your full webserver/virtualhost configuration, [installation](https://shaarli.readthedocs.io/en/master/Installation/) method, relevant webserver error logs...

**Comment by Draky50110** [comment]
Shared hosting.

Installed fro thr ZIP file from GitHub, uncompressed and that's all.

**Comment by nodiscc** [comment]
> webserver error logs

**Comment by Draky50110** [comment]
Have finally tested a fresh new install + import of "data" dir and RSS feed is back.
If I find what was the problem, will post here...

**Comment by Riduidel** [comment]
Weirdly enough, I currently have this issue on https://nicolas-delsaux.hd.free.fr/Shaarli/ (freshly reinstalled with version 0.12.1).
The atom field can't be accessed from https://nicolas-delsaux.hd.free.fr/Shaarli/feed/atom?, but works ok from https://nicolas-delsaux.hd.free.fr/Shaarli/index.php/feed/atom?
It reminds me an issue with newest version of Shaarli requiring the install of a `.htaccess` file, no?
