### ISSUE TITLE
Fail2Ban not seeing fails

### ISSUE THREAD

**Issue by presence06** [shaarli/Shaarli#1851]
running Unraid with SWAG. I passed the  log.txt from within /data/ to SWAG. I can see the fails in the log.txt for shaarli but Fail2ban isn't seeing the fails. I also see dockerIP/Swag_remoteIP in the log. Using master.

**Comment by nodiscc** [comment]
Hi  @presence06 ,
please post your full configuration/installation/configuration steps and relevant error logs.

Fail2ban jail/filter is working fine for me on a standard apache/php-fpm install:

```bash
deploy@demo1:~$ sudo cat /etc/fail2ban/filter.d/shaarli-auth.conf
# fail2ban filter for Shaarli authentication
[INCLUDES]
before = common.conf
[Definition]
failregex = \s-\s<HOST>\s-\sLogin failed for user.*$
ignoreregex =

deploy@demo1:~$ sudo cat /etc/fail2ban/jail.d/shaarli.conf
# Fail2ban shaarli jails
[shaarli-auth]
# Shaarli login failures
enabled  = true
filter   = shaarli-auth
port     = https,http
logpath  = /var/www/links.example.orgdata/log.txt


# attempt to login with wrong password
deploy@demo1:~$ sudo tail -n1 /var/log/fail2ban.log 
2022-04-18 21:00:06,180 fail2ban.filter         [557]: INFO    [shaarli-auth] Ignore 10.x.x.x by ip
```

**Comment by presence06** [comment]
regex:
```
[INCLUDES]
before = common.conf

[Definition]

failregex = \s-\s<HOST>\s-\s Login failed for user.*$
ignoreregex =
```
My Jail:

```
[shaarli-auth]

enabled  = true
port     = https,http
filter   = shaarli-auth
logpath  = /shaarli/log.txt
action = gotify
		 cloudflare
maxretry = 3
# permanently ban the IP address after reaching the limit
bantime = 600

```

and from my log.txt file for Shaarli:
[2022-04-18 10:59:06.342138] [info] - 172.19.0.9_*remoteIPedited* , *remoteIPedited* - Login failed for user bob
[2022-04-18 12:24:54.935246] [info] - 172.19.0.9_*remoteIPedited* , *remoteIPedited*  - Login failed for user bob
[2022-04-18 12:47:02.419877] [info] - 172.19.0.9_*remoteIPedited* , *remoteIPedited*  - Login failed for user bob
[2022-04-18 12:51:34.788862] [info] - 172.19.0.9_*remoteIPedited* , *remoteIPedited* - Login failed for user bob
[2022-04-18 12:51:34.788988] [info] - 172.19.0.9 - IP address banned from login: 172.19.0.9 <<<< docker network IP

My ngnix/Swag proxy config file:

```
server {
    listen 443 ssl;
    listen [::]:443 ssl;

    server_name share.*;

    include /config/nginx/ssl.conf;

    client_max_body_size 0;

    # enable for ldap auth, fill in ldap details in ldap.conf
    #include /config/nginx/ldap.conf;

    # enable for Authelia
    #include /config/nginx/authelia-server.conf;

    location / {
        # enable the next two lines for http auth
        #auth_basic "Restricted";
        #auth_basic_user_file /config/nginx/.htpasswd;

        # enable the next two lines for ldap auth
        #auth_request /auth;
        #error_page 401 =200 /ldaplogin;

        # enable for Authelia
        #include /config/nginx/authelia-location.conf;
        proxy_set_header  X-Real-IP         $remote_addr;
        proxy_set_header  X-Forwarded-For   $proxy_add_x_forwarded_for;
        proxy_set_header  X-Forwarded-Proto $scheme;
        proxy_set_header  X-Forwarded-Host  $host;
        
        include /config/nginx/proxy.conf;
        include /config/nginx/resolver.conf;
        set $upstream_app shaarli;
        set $upstream_port 80;
        set $upstream_proto http;
        proxy_pass $upstream_proto://$upstream_app:$upstream_port;

    }

}
```

**Comment by nodiscc** [comment]
> ` [2022-04-18 12:51:34.788862] [info] - 172.19.0.9_remoteIPedited , remoteIPedited - Login failed for user bob`

This doesn't match what I am getting for failed logins with Shaarli installed [from release zip](https://shaarli.readthedocs.io/en/master/Installation/#from-release-zip):

> `[2022-04-23 13:56:11.318789] [info] - 10.0.X.X - Login failed for user bob`

(you are getting the remote IP twice in your logs?) Can you post your failed login logs again, in a `code` block, just replacing the remote IP with `10.0.X.X` as I just did? `failregex = \s-\s<HOST>\s-\s Login failed for user.*$` will **not** match log messages that are **not** exactly of this form.

**Comment by presence06** [comment]
`[2022-04-21 15:22:38.028446] [info] - 172.19.0.10_10.x.x.x, 10.x.x.x - Login successful
[2022-04-21 21:47:14.529237] [info] - 172.19.0.10_10.x.x.x, 10.x.x.x - Login successful
[2022-04-25 13:15:55.974534] [info] - 172.19.0.10_10.x.x.x, 10.x.x.x - Login failed for user test`

**Comment by nodiscc** [comment]
> 172.19.0.10_10.x.x.x, 10.x.x.x

something in your reverse proxy configuration is messing up the IP address Shaarli sees.

As I said, failed login messages must be of the form `[2022-04-23 13:56:11.318789] [info] - 10.0.X.X - Login failed for user bob`, else you will have to adapt your fail2ban filter.
