### ISSUE TITLE
stable docker shaarli version is based on obsolete alpine 3.12

### ISSUE THREAD

**Issue by hydrargyrum** [shaarli/Shaarli#1855]
The stable dockerized shaarli version is [based on alpine 3.12](https://github.com/shaarli/Shaarli/blob/stable/Dockerfile#L29=) which will be [unsupported on 2022-05-01](https://www.alpinelinux.org/releases/).

Maybe a new stable docker shaarli version should be released? Or stable version should be patched not to point anymore to an obsolete alpine?

**Comment by nodiscc** [comment]
@hydrargyrum can you send a Pull Request to update the base Alpine image? Thanks

**Comment by nodiscc** [comment]
Updated alpine base images to v3.16 on `master` in https://github.com/shaarli/Shaarli/pull/1867. The `stable` docker tag will be removed in the next release (replaced with `release`).

Now we just need to do a new release, I will check https://github.com/shaarli/Shaarli/milestone/34 in the coming days.
