### ISSUE TITLE
HTML entity

### ISSUE THREAD

**Issue by RolandTi** [shaarli/Shaarli#1856]
Hello ! 
Is it just me or html entities aren’t converted when shaarli retrieve metadata’s ?
For exemple, Clémence is retrieved as Cl&eacute;mence. 

is there any fix out there ? Thanks 😊

**Comment by nodiscc** [comment]
Hi @RolandTi 

Can you detail all steps allowing to reproduce the problem? (actions, URL, expected result, observed result)

**Comment by RolandTi** [comment]
Hello @nodiscc ,
I'm sorry, but I tested again with shaarli default template with this url : https://css-tricks.com/accessible-svg-icons/, 
and it's working.

Html entities are only displayed with "material"  (https://github.com/kalvn/Shaarli-Material) template. So I think it's not related to shaarli dev.  I should have tested more before posting.

![image](https://user-images.githubusercontent.com/28786873/174570114-8e8973fe-0c5c-4cdc-a8c4-ccfd7144eca7.png)

**Comment by ArthurHoaro** [comment]
Thanks for the clarification. I suggest that you report this issue on the Kalvn theme repo then, as it's probably related to frontend display.
