### ISSUE TITLE
Error 300 or 400 when updating Thumbnails in Shaarli 11

### ISSUE THREAD

**Issue by MagicFab** [shaarli/Shaarli#1860]
When launching Thumbnails Update everything seems OK until it reaches ~200 thumbnails (not always the same #):

![image](https://user-images.githubusercontent.com/317514/175550423-6c14c0c2-6782-4328-809c-5d09e2fb5008.png)

Then I get a popup with "An error occurred. Return code: 400" sometimes error 300.

My Shaarli instance is hosted at Dreamhost (shared hosting).

**Comment by ArthurHoaro** [comment]
It's fairly possible that you hit some kind of limit rate set up by your provider. If you refresh the page immediately after the first few errors, do you get 400/300 errors as well?

**Comment by nodiscc** [comment]
@MagicFab Some shared hosting providers place restrictions on the number/contents of requests made by the server (see https://shaarli.readthedocs.io/en/master/Troubleshooting/#error-406-not-acceptable for another example). If that's the case, you should get in touch with your provider's support (or it might be mentioned in their documentation) to ask if the restriction can be lifted.

**Comment by MagicFab** [comment]
No idea. I am not chasing this anymore. Please don't assign to me something I can't fix/improve in Shaarli.
