### ISSUE TITLE
Plugins to add stars (marks to a bookmark)

### ISSUE THREAD

**Issue by Romuald23** [shaarli/Shaarli#1862]
Hello,

I read the list of plugins but I didn't find a plugin to add a list of starsfrom 1 to 5 for example to an item in order to rank them.

Do you know if it exists ?

Thank you

**Comment by ArthurHoaro** [comment]
Hi! I'm pretty it doesn't exist, and we don't plan to create one in the core, but if you happen to build one, feel free to list it as a 3rd party on this repo docs.
