### ISSUE TITLE
ban: HTTP 429?

### ISSUE THREAD

**Issue by mro** [shaarli/Shaarli#1863]
Hi  @ArthurHoaro,

when banned, shaarli returns a 401. Wouldn't a https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/429 plus `Retry-After:` be more appropriate?

**Comment by mro** [comment]
@ArthurHoaro hello?

**Comment by nodiscc** [comment]
Hi @mro, I think HTTP 429 is not appropriate

> The HTTP 429 Too Many Requests response status code indicates the user has sent too many requests in a given amount of time ("rate limiting").

The login bruteforce prevention feature is not a rate-limiting mechanism, but an intrusion prevention mechanism. Client is no longer authorized to access the service once they trigger the mechanism. So HTTP 403 is correct. Additionally we don't want to tell offenders about the duration of the ban.

For example, fail2ban has a similar role, and simply drops TCP connections once the login failure threshold is reached.

**Comment by mro** [comment]
@nodiscc with due respect I have to disagree: Since the decision to deny the request is not made after checking the password but instead, it is not an honest 403.

Namely https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/403 says "… The access is permanently forbidden  …" which is not the case.

Beyond that is the decision finally based on an exceeding rate (of retries), the failed login is necessary but not sufficient a condition. A single failed login does not trigger a ban.

Lastly not telling about the expiry is the fallacy of security by obscurity and even encourages retries meanwhile. Which is useless load.

**Comment by nodiscc** [comment]
You make a point and I have no strong feelings about this. Do you have a specific use case in mind? It should be very easy to [patch](https://github.com/shaarli/Shaarli/blob/820cae27cfcc94af552818f3f1e5342e00478f6c/application/front/exceptions/LoginBannedException.php#L13)

**Comment by mro** [comment]
the use case is to make more meaningful error messages related to https://github.com/mro/ShaarliOS/issues/46.

If one misspells the uid/pwd and runs into a ban, a date time when a retry makes sense would be nice. Thus a 429+`Retry-After`.

**Comment by ArthurHoaro** [comment]
It's true that in the web UI, when a user is banned the login form is hidden and a message saying so is displayed. It would be nice to have something similar for the API, especially for legitimate failed attempts. `429` could probably fit this use case. 
:+1:
