### ISSUE TITLE
GET /api/v1/links?limit=all does not return all links

### ISSUE THREAD

**Issue by jsrolon** [shaarli/Shaarli#1865]
I have a k8s pod running the `shaarli/shaarli:v0.12.1` image. As reported by the Web interface, this instance contains 196 shaares. I am calling `/api/v1/links?limit=all`, which I expect would return all of the shaares, but it doesn't. Nor does `/api/v1/links?limit=196`.

The most items I am getting per response are 31, when calling `/api/v1/links?limit=50`. There doesn't seem to be any rhyme or reason to the response size, sometimes I get 30 as well. Is this expected behavior?

EDIT: Attaching the response body for `limit=196`, you'll see the list skips from id 12 to 192.
[shaarli.txt](https://github.com/shaarli/Shaarli/files/9172207/shaarli.txt)

**Comment by jsrolon** [comment]
I reverted to `shaarli/shaarli:v0.12.0` and the API responds with the appropriate amount of links. Definitely seems to be a regression in `0.12.1`.

**Comment by nodiscc** [comment]
I can't reproduce this on shaarli v0.12.1 installed from release zip + apache/php-fpm, using [python-shaarli-client](https://github.com/shaarli/python-shaarli-client/) to query shaarli:

```bash
$ shaarli -u https://links.EXAMPLE.network get-links |jq '.[]["title"]'|wc -l
20
$ shaarli -u https://links.EXAMPLE.network get-links --limit=all |jq '.[]["title"]'|wc -l
6052
$ shaarli -u https://links.EXAMPLE.network get-links --limit=9 |jq '.[]["title"]'|wc -l
9
```

Maybe there is something specific to your setup that causes this issue?

- Is the reverse proxy stripping URL parameters from queries? Please post your reverseproxy configuration.
- Does setting `limit=` to **less** than 10 affect the number of shaares returned? or is the URL parameter completely ignored?
- Can you see URL parameters in your webserver/reverse proxy logs?

> I am calling /api/v1/links?limit=all

How/through what script are you querying it?

That doesn't explain why it would work on v0.12.0 and not on v0.12.1 though.

**Comment by nodiscc** [comment]
@jsrolon ping

**Comment by jsrolon** [comment]
I don't have access to the environment where this was happening anymore. Will close since I can't provide additional information.
