### ISSUE TITLE
set search/tags fields tabindex to 1/2

### ISSUE THREAD

**Issue by nodiscc** [shaarli/Shaarli#187]
http://stackoverflow.com/a/1484978

**Comment by nicolasdanelon** [comment]
Q: what if we add [modernizr](http://modernizr.com/docs/) for HTML5 better support?
We can use autofocus without the javascript code in that stackoverflow link and use modernizr will help us with SVG detecting if browser supports or not SVG images ;)

**Comment by nodiscc** [comment]
There's no javascript required http://www.w3schools.com/tags/att_input_autofocus.asp `<input type="text" id="searchform_value" name="searchterm" placeholder="Search text" value="" autofocus>`

**Comment by nicolasdanelon** [comment]
Yes... I know but I'm talking about old browsers :)

**Comment by pikzen** [comment]
Modernizr doesn't implement autofocus though. It merely declares it, but nothing is done with it. Last mention I've seen of it is a 2009 issue.

**Comment by nodiscc** [comment]
I've added autofocus to my `autofocus` branch. https://github.com/nodiscc/Shaarli/commit/82d7a405b00b1b30f40f2cc7018362419ae8dda6. It works, except when you want to reach an URL like `/?#34czEf`, which should scroll the link list view to a particular link (anchor), but instead places the view on the search field.

**Comment by alexisju** [comment]
I've removed autofocus (html5) from albinomouse because it is not compliant for smartphones (autofocus opens the keyboard automatically, what is a bit boring on small screens).

On desktop, page up/down keys are not usable before unfocus search fields.

Finally, i prefer using tab key (or use my mouse) when i want to focus make a search ;)

**Comment by nodiscc** [comment]
Very good points. Maybe we should use `tabindex=1` instead (just hit Tab once?)

**Comment by nodiscc** [comment]
Fixed in https://github.com/shaarli/Shaarli/commit/0923a2bc1b097bf1def882722db489d83d95c423
