### ISSUE TITLE
Broken link to documentation 404

### ISSUE THREAD

**Issue by mike2003** [shaarli/Shaarli#1873]
This link takes me to my local server. (docker version)

Plugin administration -> More plugins available **in the documentation**
=
404 Not Found
http://192.168.1.33:8000/doc/html/Community-&-Related-software/#third-party-plugins

**Comment by ArthurHoaro** [comment]
Hi, it looks like Shaarli can not properly find your instance URL. We would need more info regarding your server setup to help you.

Take a look at the [Reverse proxy documentation](https://shaarli.readthedocs.io/en/master/Reverse-proxy/), you are probably missing `X-Forwarded` headers.

**Comment by mike2003** [comment]
I didn't make any settings. Where should this link go? Is there a DOC folder on my computer? It looks more like an installation without the necessary files.

**Comment by nodiscc** [comment]
@mike2003 which [installation](https://shaarli.readthedocs.io/en/master/Installation/) method did you use?

If you installed from .zip make sure you sure you grab the `-full` zip/tarball from https://github.com/shaarli/Shaarli/releases/tag/v0.12.1

**Comment by svemoe** [comment]
The link is actually wrong and should point to 
instance/doc/html/Community-**and**-**r**elated-software/#third-party-plugins
instead of
instance/doc/html/Community-**&**-**R**elated-software/#third-party-plugins

**Comment by ArthurHoaro** [comment]
Oh good catch!
