### ISSUE TITLE
Docker image tag 'release' is missing

### ISSUE THREAD

**Issue by Tronde** [shaarli/Shaarli#1875]
The docs for [Docer](doc/md/Docker.md) say:

> Shaarli images are available on [DockerHub](https://hub.docker.com/r/shaarli/shaarli/) `shaarli/shaarli`:
> 
> - `latest`: master (development) branch
> - `vX.Y.Z`: shaarli [releases](https://github.com/shaarli/Shaarli/releases)
> - `release`: always points to the last release
> - `stable` and `master`: **deprecated**. These tags are no longer maintained and may be removed without notice

But the image doesn't seem to contain a `release` tag:

```bash
$ skopeo inspect docker://docker.io/shaarli/shaarli
{
    "Name": "docker.io/shaarli/shaarli",
    "Digest": "sha256:4f681d7c6740526c27cefa21ffbfbf0cfa704c23a23b54bced791d64fa2902d3",
    "RepoTags": [
        "latest",
        "master",
        "stable",
        "v0.10.0",
        "v0.10.2",
        "v0.10.3",
        "v0.10.4",
        "v0.11.1",
        "v0.12.0",
        "v0.12.1"
    ],
    "Created": "2022-07-26T13:20:17.31756566Z",
    "DockerVersion": "",
    "Labels": {
        "maintainer": "Shaarli Community"
    },
    "Architecture": "amd64",
    "Os": "linux",
    "Layers": [
        "sha256:ab6db1bc80d0a6df92d04c3fad44b9443642fbc85878023bc8c011763fe44524",
        "sha256:35dd2d03754f80fce2334e3e30761a95523a4320406924b70c6d6c53635b614d",
        "sha256:61a0fb6546c97bd363d63f1e23c345697c48c33ab8014665e620d226dffe7ec0",
        "sha256:1058bd809be0ad9eaf3ea59a71348874bf966722e6857115fa1f6630cd509bb8",
        "sha256:930db93fd42065c00ae4e48efc1f09aa50e2c1d251488b1336ab8afd5ed4d30d",
        "sha256:d0aa216f85e4d09d311d3e91ae4cd42157f9748ba2298d627d34f2d449e1953e",
        "sha256:4f4fb700ef54461cfa02571ae0db9a0dc1e0cdb5577484a6d75e68dc38e8acc1",
        "sha256:f663f1537a17b8b1d1c77ad9a98713d789a8f314065f0c6135b93b2bffc67719",
        "sha256:4876795739b6d5c3cf9862ab8ceda054411e330034691c6661f6c0df2b3e0522"
    ],
    "Env": [
        "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
    ]
}
```

- Is there a bug in the image or in the documentation?
- Is it possible to add a tag `release` to the docker image that points to the latest stable release?
- Could you give an estimate when this could be fixed?

**Comment by nodiscc** [comment]
> Is there a bug in the image or in the documentation?
> Is it possible to add a tag release to the docker image that points to the latest stable release?
> Could you give an estimate when this could be fixed?

It's been introduced after v0.12.1, but there has been no new release since, hence there is no image tagged `release` yet. It will be fixed when v0.12.2 is released ([remaining work](https://github.com/shaarli/Shaarli/milestone/34)), there is no release date set.

In the mean time you can use the `stable` tag but it will be dropped (and replaced with `release`) when v0.12.2 is released.

**Comment by Tronde** [comment]
Currently I use the `stable` tag. I'm watching this project to switch to the `release` tag once it's there. I guess this issue will be closed by v0.12.2 release, right?

**Comment by nodiscc** [comment]
Correct.

For the next release we will also delete `stable` images, so that users trying to pull them receive an error and consult the updated documentation.

**Comment by nodiscc** [comment]
I think it's not necessary to wait for the next release. We should tag the current `stable` image with `release` right now (this way documentation will be correct).

**Comment by nodiscc** [comment]
Done.

```bash
$ sudo docker pull shaarli/shaarli:stable
stable: Pulling from shaarli/shaarli
339de151aab4: Pull complete 
014a37916ac2: Pull complete 
747e219c257d: Pull complete 
940bf69b4cba: Pull complete 
9e0b588979b0: Pull complete 
3d08f6500d50: Pull complete 
cef6951c288e: Pull complete 
94d33678c1b1: Pull complete 
Digest: sha256:441d93a5c98169ce2973583712e1bee85790014452dcf252acf6bf85a9e6885a
Status: Downloaded newer image for shaarli/shaarli:stable
docker.io/shaarli/shaarli:stable
$ sudo docker tag shaarli/shaarli:stable shaarli/shaarli:release
$ sudo docker login
...
Login Succeeded
$  sudo docker push  shaarli/shaarli:release
The push refers to repository [docker.io/shaarli/shaarli]
4197ebb5c4c8: Layer already exists 
cbdfc3bc4cba: Layer already exists 
4624195c4450: Layer already exists 
251d82b0938d: Layer already exists 
1c623c8eb0b6: Layer already exists 
d91d8c5560b9: Layer already exists 
177c86a40748: Layer already exists 
32f366d666a5: Layer already exists 
release: digest: sha256:441d93a5c98169ce2973583712e1bee85790014452dcf252acf6bf85a9e6885a size: 1992
$ sudo docker logout 
Removing login credentials for https://index.docker.io/v1/
```
