### ISSUE TITLE
Option to hide **all** links to non-logged in users

### ISSUE THREAD

**Issue by nodiscc** [shaarli/Shaarli#188]
In config, add an option to make the Shaarli private: The Shaarli will not show any link, except if you are logged in. (This can also be used to temporarly “close” a shaarli).

From https://github.com/shaarli/Shaarli/issues/106

**Comment by dimtion** [comment]
Would it discard the effect of "private" check box or just force to post private posts only ? Both implementations have pros and cons but the first one seems more secure.

**Comment by nodiscc** [comment]
It discards the effect of the private/public status of links. While this option is enabled and the user is logged out, all links are hidden, disregarding if they are public or private.

**Comment by NerosTie** [comment]
I agree with @nodiscc, this is a needed feature.

**Comment by pikzen** [comment]
See #197
