### ISSUE TITLE
RFE: Support file:// for URL

### ISSUE THREAD

**Issue by Tronde** [shaarli/Shaarli#1880]
Hi everyone,  
I would like to store links to local resources in Shaarli that have to for of _file:////example.com/sharename/filename.html_.

Currently it's not possible to store those in Shaarli as 'file://' is being replaced by 'http://'.

IMHO this would be a nice feature for Shaarli. What do you think about it?

Regards,  
Tronde

**Comment by ArthurHoaro** [comment]
Hi,

It should probably work if you add `file` in the list of allowed protocols in your configuration file, under the security key.
See https://shaarli.readthedocs.io/en/master/Shaarli-configuration/

**Comment by Tronde** [comment]
> It should probably work if you add `file` in the list of allowed protocols in your configuration file, under the security key. See https://shaarli.readthedocs.io/en/master/Shaarli-configuration/

It works as I can use `file://` URLs now.

I guess this was a classic RTFM. Appreciate your quick response on this.
