### ISSUE TITLE
Feature request: Include or exclude private links?

### ISSUE THREAD

**Issue by virtadpt** [shaarli/Shaarli#1886]
When searching a Shaarli install's stored bookmarks, would it be possible to add a flag that would either limit searches to private links or exclude them specifically?  When logged in, it's nice to search on both categories at the same time, but sometimes it would be more efficient to target specifically private or not-private entries.

Does this seem like a reasonable kind of search option to the community?

**Comment by aledeg** [comment]
You have the filters available at the top of the link list. See screenshot
![Screen Shot 2022-09-13 at 15 32 11](https://user-images.githubusercontent.com/3056148/189992995-c9aaad9d-c4a3-4c63-be12-676b8d7e3045.png)

**Comment by virtadpt** [comment]
Oh, crap - I never noticed that before.  Thank you, and sorry to bother you.
