### ISSUE TITLE
Atom seems broken

### ISSUE THREAD

**Issue by mrtpcet** [shaarli/Shaarli#1888]
### Describe the bug

Atom seems broken since last update with all my Shaarli instances. For all my instances, I have two error messages : 
![image](https://user-images.githubusercontent.com/60814449/191708243-903a377d-d38d-446a-8577-dc98276cec41.png)
(https://www.rssboard.org/rss-validator/)

### Context
- Shaarli v0.12.1
- Hardware: VPS bought online 
- Debian: 11

**Comment by nodiscc** [comment]
Hi,
- Are there any errors in your server logs?
- How did you install Shaarli? (from [release zip](https://shaarli.readthedocs.io/en/master/Installation/#from-release-zip)? other method?)
- Did you install all [required php extensions](https://shaarli.readthedocs.io/en/master/Server-configuration/#php) ?

**Comment by mrtpcet** [comment]
> 



> * Are there any errors in your server logs?
There is no log file in /var/log/shaarli

>     * How did you install Shaarli? (from [release zip](https://shaarli.readthedocs.io/en/master/Installation/#from-release-zip)? other method?)
From this script : https://github.com/YunoHost-Apps/shaarli_ynh who download https://github.com/shaarli/Shaarli/releases/download/v0.12.1/shaarli-v0.12.1-full.tar.gz
>     * Did you install all [required php extensions](https://shaarli.readthedocs.io/en/master/Server-configuration/#php) ?
I don't know but i think the script do that !

**Comment by nodiscc** [comment]
You should probably ask on the Yunohost support/bug tracker/forum then. The yunohost packaging is not supported here - the only supported methods are those described in https://shaarli.readthedocs.io/en/master/Installation/. I see you did that already in https://github.com/YunoHost-Apps/shaarli_ynh/issues.

Errors are usually logged in `/var/log/apache2/error.log` or /var/log/nginx/error.log` or `/var/log/php*` depending on your setup.

Closing.
