### ISSUE TITLE
Installing from scratch -> no template used -> page without assets

### ISSUE THREAD

**Issue by ZacAzko** [shaarli/Shaarli#1889]
Hi,

I've an old version of  Shaarli... Due to the upgrade of Php (5.x -> 8.x) old Shaarli don't work anymore 😅

So i decided to restart from scratch with new version (v0.12.1)...

No css/images are used, i've bad look :3

![image](https://user-images.githubusercontent.com/106684856/191924351-a369051b-4180-44e1-bdd9-5aa1834cb521.png)
 if I read the html source, it seem's that the assets path is not correct... Why ?! 😅

![image](https://user-images.githubusercontent.com/106684856/191924674-587e7a12-e239-49f2-8004-88c66fd30e63.png)

Thanks for your help 😜

**Comment by nodiscc** [comment]
Hi,
- How did you install Shaarli (from [release zip](https://shaarli.readthedocs.io/en/master/Installation/#from-release-zip)? other method?)
- Are there any errors in the browser console or server logs?
- Is Shaarli accessed at the root of the domain (https://links.example.org/) or in a subdirectory (https://example.org/shaarli/) ?
- Any other information on your environment (dedicated server? shared hosting? reverse proxy used and configuration?)

**Comment by ZacAzko** [comment]
Thanks for your response.
Nothing special, just a simple Wamp installed on my computer and just the zip version of Shaarli in the folder...

![image](https://user-images.githubusercontent.com/106684856/193516486-e258ca7a-a7b3-482d-8115-0d4456098207.png)

(there is 2xi at the end, it's normal :p)

**Comment by nodiscc** [comment]
> -Are there any errors in the browser console or server logs?

**Comment by ZacAzko** [comment]
full... because path are not correct... :3

![image](https://user-images.githubusercontent.com/106684856/193790436-aecef42d-d333-4729-9e2a-24051b0d8ce9.png)

**Comment by ZacAzko** [comment]
Assets folder is in shaarli root folder...
But Templates search Assets in tpl folder... It's the trouble i think... But I change nothing after dezip, so why it's not working well by default 😅

**Comment by nodiscc** [comment]
> why it's not working well by default

WAMP is not tested/supported. `localhost` is also not a valid FQDN and browsers will behave strangely with domain names that don't contain a dot (see [[1]](https://shaarli.readthedocs.io/en/master/Troubleshooting/#firefox-localhost-and-redirections), [[2]](https://shaarli.readthedocs.io/en/master/Troubleshooting/#sessions-do-not-seem-to-work-correctly-on-your-server))

But I would guess automatic detection of the root URL simply does not work on your setup. Have you tried settting [`general.root_url`](https://shaarli.readthedocs.io/en/master/Shaarli-configuration/#general) to `http://localhost/shaarlii/` in your `config.json.php`?

**Comment by ZacAzko** [comment]
Haaaaaa...
I go to test...
Thanks 😁

**Comment by ZacAzko** [comment]
I've tried with a dot in the url, but no more results...

![image](https://user-images.githubusercontent.com/106684856/193830369-76143083-8f3c-4d43-9c28-5a278c99c955.png)

I try to directly upload the solution on my website to see if it's work better or not 😜
Thanks for your Patience ❤

**Comment by nodiscc** [comment]
> But I would guess automatic detection of the root URL simply does not work on your setup. Have you tried settting [general.root_url](https://shaarli.readthedocs.io/en/master/Shaarli-configuration/#general) to http://localhost/shaarlii/ in your config.json.php?

**Comment by ZacAzko** [comment]
Website upgraded...
No more results...

i change the section in config :

    "general": {
        "root_url": "http://links.zacland.net/",
        "header_link": "\/shaarlii\/",
        "links_per_page": 20,
        "enabled_plugins": [
            "qrcode"
        ],
        "default_note_title": "Note: ",
        "retrieve_description": true,
        "enable_async_metadata": true,
        "tags_separator": " ",
        "timezone": "Europe\/Paris",
        "title": "Zaaac Liiiinks"
    },

The access time is longer with root_url -> but no css with or without the option...

See the result here : http://links.zacland.net/

**Comment by nodiscc** [comment]
> just the zip version of Shaarli

Where did you download it from? You need ` shaarli-v0.12.1-full.tar.gz ` from https://github.com/shaarli/Shaarli/releases

**Comment by ZacAzko** [comment]
AAAAAAaaaah !

It's working really better !!! (in Wamp too)

I think i download the zip from github here : (and i think that's teh cause of the trouble... :3)

![image](https://user-images.githubusercontent.com/106684856/194265933-ef1b7036-4f3b-4c35-911e-d4e96daec937.png)

Lots of THANKS 😘

**Comment by nodiscc** [comment]
No problem.
Remember to read the documentation https://shaarli.readthedocs.io/en/master/Installation/ thoroughly.
