### ISSUE TITLE
Locked out of Shaarli

### ISSUE THREAD

**Issue by gingersnapglitch** [shaarli/Shaarli#1894]
I am locked out of my Shaarli instance. I took a look at the documentation and saw that deleting the config.json.php would prompt for a new login. I have a question:

 If I delete this file, does it delete my existing Shaarli content on the user I'm locked out of? Or does it just allow me to reset the password for my existing account?

Thanks for your help!

**Comment by nodiscc** [comment]
If it's a simple "locked out after trying too many bad passwords" issue, deleting `data/ipbans.php` should be enough. Check https://shaarli.readthedocs.io/en/master/Troubleshooting/#im-locked-out-login-bruteforce-protection

> If I delete config.json.php does it delete my existing Shaarli content on the user I'm locked out of? Or does it just allow me to reset the password for my existing account?

It resets all settings, including username/password. Your bookmarks are untouched (they are stored in `datastore.php`). You should still do a full backup of your `data/` directory before touching these files.

**Comment by gingersnapglitch** [comment]
Thank you for the response. I didn't delete ipbans.php because no matter what I try, I can't seem to remember my password. If I delete config.json.php and that resets username/password, how do I gain access to the bookmarks in datastore.php after that?

**Comment by gingersnapglitch** [comment]
This worked great and I am back in. I'm very new to this, so I greatly appreciate the help - thank you!
