### ISSUE TITLE
Wrong date format when language setting is set to `Automatic`

### ISSUE THREAD

**Issue by jlkDE** [shaarli/Shaarli#1900]
Hey, I am glad that Shaarli is still actively maintained and I am happy with the overall quality.

My setup consists of several small Docker containers that I built myself for the ARM64 arch.
As mentioned in https://github.com/shaarli/Shaarli/issues/1869#issuecomment-1256999136 moments before I got merged the switch to PHP 8 works flawlessly, there is only one small issue I got that I could not resolve until now:
The date format of entries changed from `30. Januar 2022 um 12:44:20 UTC *` in my case to simply `2022 M01 30 12:44:20 UTC *`.

Regarding my locale configuration: I am a German speaker, but my systems locale and therefore Firefox and it's settings is set to English. Shaarlis language is set to `Automatic`. After installation the timezone was `UTC/UTC`, I changed it to `Europe/Berlin` without effect.
Firefox reports the following:
```
locale 					en-US
intl.requestedLocales 			[en-US]
intl.availableLocales 			[fr, zh-TW, es-ES, pt-BR, el, it, ca, en-US, ar, es-CL, pl, de, sv-SE, fi, cs, da, en-GB, hu, ko, ja, ru, nb-NO, nl, pt-PT, zh-CN, es-AR]
intl.appLocales 			[en-US, en-GB]
intl.systemLocales 			[en-US]
intl.regionalPrefsLocales 		[en-US]
intl.acceptLanguages 			[de-de, en-us, en]
userPrefs.browser.search.region 	DE
```
Therefore I am not completely sure why the format with my PHP 7 build was German localized, maybe it was the region?

**Comment by ArthurHoaro** [comment]
Hi, I'm not really able to reproduce your issue, but I can only easily use the AMD64 Docker build and not the ARM, so my guess would be to check in that direction.

> Regarding my locale configuration: I am a German speaker, but my systems locale and therefore Firefox and it's settings is set to English. Shaarlis language is set to Automatic. 

If you had the date in German, it means that Firefox is sending the `de` locale in the `Accepted Languages` header. You can play with it by changing the header or using a simple browser extension such as [this one](https://addons.mozilla.org/en-US/firefox/addon/locale-switcher/).

![image](https://user-images.githubusercontent.com/1962678/203859492-19eeb1e4-3aa4-4475-b7e2-03792212023b.png)

 > After installation the timezone was UTC/UTC, I changed it to Europe/Berlin without effect.

It should affect the new links you save.

![image](https://user-images.githubusercontent.com/1962678/203859609-634a8e41-aca2-4170-8dfa-7df8af542023.png)

---

So first, can you try a few other locales from the client browser to see what happens?

**Comment by jlkDE** [comment]
Thanks for checking back with me! Unfortunately I was busy moving in this time of the year, but now I could look into your suggestions.

It seems that this has indeed to do with the `Accepted Languages` header - After switching my locale to English (`en`) the date appeared as `January 30, 2022 at 12:44:20 UTC` but I was unable to use any locale apart from the English ones.
These seem to be evaluated differently as `en-US` or `en-HK` leads to `January 30, 2022 at 12:44:20 PM UTC` with an additional `PM` while `en-GB` omits this.

I will try to build the image on for different architectures to look into this further, but so far I have no clue what may be causing this.

**Comment by nodiscc** [comment]
@jlkDE is this issue still present?

**Comment by jlkDE** [comment]
Yes, I just tested it and the problem persists. However I have noticed that this only seems to happen when the _Languages_ setting of Shaarli is set to `Automatic` - Here is a comparison:

| Languages setting | `Accept-Language` headers | Date format |
| -- | -- | -- |
| Automatic | `en-US,en;q=0.7,de-DE;q=0.3` | `June 14, 2020 at 11:02:38 PM GMT+2` |
| Automatic | `de-DE,en-US;q=0.7,en;q=0.3` | `2020 M06 14 23:02:38 GMT+2` |
| Deutsch | `en-US,en;q=0.7,de-DE;q=0.3` | `June 14, 2020 at 11:02:38 PM GMT+2` |
| Deutsch | `de-DE,en-US;q=0.7,en;q=0.3` | `June 14, 2020 at 23:02:38 GMT+2` |

My systems and browsers locale was `en-US` the whole time, changing the UI language of Firefox changed nothing. I could reproduce the same behavior with the Brave browser too.

**Comment by nodiscc** [comment]
So a possible workaround is to set the language manually in `/admin/configure`, good to know.

There must be something strange at play in [`autoLocale()`](https://github.com/shaarli/Shaarli/blob/master/application/Utils.php#L198).

I am still running PHP 7.4 (upgrade planned soon), and I can't reproduce the problem you describe, **but** for me the date format stays at `August 1, 2023 at 2:38:17 PM GMT+2` regardless of Shaarli's language setting, or my Accept-Language headers (I would expect it to be `1 Août 2023, à 14:38:17 GMT+2` if I force everything to french - the rest of the UI is correctly translated, but dates are not).

I will try to reproduce the bug on a PHP8 system.

**Comment by henschi** [comment]
The problem is not in shaarli code, but is caused by the alpine update and the splitting of the icu package.
See here:
https://github.com/php/php-src/issues/8656#issuecomment-1141100253
https://wiki.alpinelinux.org/wiki/Release_Notes_for_Alpine_3.16.0#ICU_data_split

Please add "apk del icu-data-en && apk add icu-data-full" in Dockerfile to support more than english. ;-)

**Comment by nodiscc** [comment]
Thanks @henschi 
So this is probably the commit that broke it https://github.com/shaarli/Shaarli/commit/0abe2f0dcc8415515e37ab8a67c9bca96a72be00 :smiling_face_with_tear: 
@jlkDE could you please confirm the `:latest` Docker image fixes it for you (after it's finished building https://github.com/shaarli/Shaarli/actions/runs/11581312294)?

**Comment by jlkDE** [comment]
Indeed, with including the package this issue is resolved for me. Thanks to everyone involved! 🎉
