### ISSUE TITLE
feature request: be able to add a tag to multiple shaares with one user operation

### ISSUE THREAD

**Issue by znoteer** [shaarli/Shaarli#1901]
The title pretty much says it all.

When you tick the check box of any shaare a menu bar appears offering the opportunity to change the public/private status of all ticked shaares or to delete all ticked shaares. It would  be nice if there were also an "Add tag" option so that multiple shaares could be labelled with the same tag all at once.

Would this be even possible? Not being a programmer, I can't answer myself.

**Comment by ArthurHoaro** [comment]
Feature related to #1160.
It should be fixed by the PR opened in #1898
