### ISSUE TITLE
504 Gateway Timeout when importing bookmarks

### ISSUE THREAD

**Issue by JuanRodenas** [shaarli/Shaarli#1910]
Hello,

I have detected a lack of configuration in nginx.
When loading a lot of bookmarks, nginx stops responding and plays error: `504 Gateway Timeout`.

I have solved it by adding inside the `server` in the file `/etc/nginx/nginx.conf`:

```
server {
    # Buffer configuration
    client_header_buffer_size 8k;
    large_client_header_buffers 4 32k;
    client_body_buffer_size 32K;
    keepalive_timeout 60;
    send_timeout 60;

    # timeout for reading a response
    proxy_read_timeout 600;
    proxy_connect_timeout 600;
    proxy_send_timeout 600; 
}
```

Best regards, Juan

**Comment by nodiscc** [comment]
> loading a lot of bookmarks

- How many bookmarks?
- Do you mean importing bookmarks from a bookmarks.html file? Or just displaying them in Shaarli?

(This may be similar to https://github.com/shaarli/Shaarli/issues/1854, optional timeout settings should probably be documented in https://shaarli.readthedocs.io/en/master/Reverse-proxy/)

**Comment by JuanRodenas** [comment]
Hi!
- I have loaded about 200 or so.
- I import the bookmarks from a bookmarks.html file.
Best regards.

**Comment by nodiscc** [comment]
Thanks for letting us know. I've added a hint that reverse proxy timeout settings might need to be adjusted for long-lasting operations (like importing a lot of bookmarks) in https://github.com/shaarli/Shaarli/pull/1938/files. Feel free to send a patch to improve the nginx-specific documentation in https://github.com/shaarli/Shaarli/blob/master/doc/md/Reverse-proxy.md#nginx.

By the way 200 bookmarks is not that many. By chance, is this on low-powered hardware/ARM board? That would explain why you're hitting the timeout.
