### ISSUE TITLE
New Install, Features Not Working on WAMP

### ISSUE THREAD

**Issue by ElCapitannn** [shaarli/Shaarli#1929]
Hi,

I have a fresh install of version 0.12.1 , PHP version 7.4.26
When I first installed it, there was a webpage that showed the checks and that everything passed (How do I get back to this page ??)

But features are not working and I see errors in the logs.

When adding a new shaare , title and description are not retrieved. Thumbnail update does not function. Version update check is failing.
I supposed that this is all related to curl in some way.

php_error.log
`Failed to retrieve https://raw.githubusercontent.com/shaarli/Shaarli/latest/shaarli_version.php`

`TypeError: Argument 1 passed to WebThumbnailer\Utils\ImageUtils::isImageString() must be of the type string, bool given, called in C:\wamp64\www\Shaarli\vendor\arthurhoaro\web-thumbnailer\src\WebThumbnailer\Finder\DefaultFinder.php on line 59`

thanks

**Comment by ArthurHoaro** [comment]
Hi, 

> When I first installed it, there was a webpage that showed the checks and that everything passed (How do I get back to this page ??)

This table is also available in Tools > Server Administration.
The installation page is displayed if there is no config, so you could delete or rename `data/config.json.php` to do so.

But yes, it does look like some issue with curl or your server external requests.

**Comment by ElCapitannn** [comment]
Does the TypeError reveal any information? Or is there some verbose logging mode that can give me more insight?

From the server administration webpage, everything appears OK.

**Comment by ElCapitannn** [comment]
I have mostly resolved this now. It was related to SSL certificates https://stackoverflow.com/questions/24611640/curl-60-ssl-certificate-problem-unable-to-get-local-issuer-certificate

However, the Shaarli version check is still failing. Title, description, and thumbnails are good.
