### ISSUE TITLE
Bad  special characters are displayed into date in french

### ISSUE THREAD

**Issue by alexisju** [shaarli/Shaarli#193]
With autolocate fixed by https://github.com/shaarli/Shaarli/commit/8438a2e5d0cb90a869d67516c6e6cf756f77a588 special caracters seems encoded in bad format.

In french i get : d�cembre / f�vrier

Check this monthes (february/december) on https://liens.effingo.be/?page=8

**Comment by nodiscc** [comment]
I can't test this. dates are always displayed in english on my browsers, and setting `Accept-Language` to `fr` doesn't change it. @ArthurHoaro, ping. Do you have this problem?

**Comment by alexisju** [comment]
You can browse my shaarli and loof after links posted in december or february ;-)

**Comment by nodiscc** [comment]
@alexisju dates are always displayed in english for me, even on your Shaarli.

**Comment by alexisju** [comment]
Its possible to change easily prefered content languages into browsers if you want...
(with firefox : preference > content > languages : choose )

**Comment by ArthurHoaro** [comment]
Confirmed.

**Comment by nodiscc** [comment]
> Its possible to change easily prefered content languages into browsers if you want...
(with firefox : preference > content > languages : choose )

This has no effect for me.

> Confirmed

Thanks, looking at your patch soon

**Comment by nodiscc** [comment]
Should be fixed by https://github.com/shaarli/Shaarli/pull/195
