### ISSUE TITLE
Return to search results after editing

### ISSUE THREAD

**Issue by chadberg** [shaarli/Shaarli#1940]
There seems to be a bug currently when doing a search (text or tags), and then editing a bookmark. After saving out from editing, it looks like it attempts to return you to the search results, but the URL does not get 'reencoded' properly.

e.g., if I search for the tag 'work' I go to "fqdn/?searchterm=&searchtags=work+". If I then edit one of the results and Apply Changes, I am brought back to "fqdn/?searchterm=&amp%3Bsearchtags=work+#anchortoselectedentry"

Because the "&" comes back as "&amp%3B", Shaarli doesn't undertstand what to do and goes back to the default unfiltered page.

**Comment by nodiscc** [comment]
I cannot reproduce this on https://demo.shaarli.org/ (master) and on my own instance (v1.12.1 installed from zip). Please post the [installation method](https://shaarli.readthedocs.io/en/master/Installation/) used, full installation steps you followed, Shaarli version, reverse proxy configuration, browser and browser version.

**Comment by chadberg** [comment]
Issue was resolved with an upgrade from 0.12.0 to 0.12.1
