### ISSUE TITLE
Share link for FreshRss

### ISSUE THREAD

**Issue by sebastienserre** [shaarli/Shaarli#1941]
Hello,

Which link structure do you recommend sharing a link from FreshRss ?
![2023-02-02_10-25](https://user-images.githubusercontent.com/3902621/216284839-a95a18b2-33b9-4b07-8d6e-d656abfca970.jpg)
I'm using https://shaarli.example.com/admin/add-shaare but it doesn't fill the Shaarli fields

Thank for your help

**Comment by nodiscc** [comment]
> Which link structure

What do you mean?

If you want to post a link by passing the URL/title as URL parameters, the format is `https://[SHAARLI URL]/admin/shaare?post=[PECRENT-ENCODED URL]&title=[POST TITLE]`. For example:

https://demo.shaarli.org/admin/shaare?post=https%3A%2F%2Fgithub.com%2Fshaarli%2FShaarli%2Fissues&title=Issues+%C2%B7+shaarli%2FShaarli

**Comment by sebastienserre** [comment]
By link structure I mean, how to setup the share menu in Fresh RSS to automatically fill `[PECRENT-ENCODED URL]&title=[POST TITLE]`

**Comment by nodiscc** [comment]
Wrong repo? I cannot tell you that, this is the issue tracker for Shaarli, not FreshRSS. You should consult their documentation or ask the FreshRSS maintainers/community in their issue tracker. As far as I can see in https://github.com/danc/FreshRSS/blob/beta/data/shares.php#L20, sharing to Shaarli should work out of the box, I think you just have to enter the base URL for the Shaarli instance (https://shaarli.example.com)
