### ISSUE TITLE
Feature Request: Import from pinboard / delicious

### ISSUE THREAD

**Issue by miquelbotanch** [shaarli/Shaarli#1942]
It would be super nice to be able to import our actual bookmarks stored in delicious / pinboard app. They share file format, and save it to shaarli

**Comment by nodiscc** [comment]
Please provide an example export from Delicious/Pinboard.

As far as I know, Delicious uses the same Netscape HTML import/export format as Shaarli, so importing it should work without problems. Please report back if that's not the case.

**Comment by dsalo** [comment]
I just imported a Pinboard export into Shaarli without difficulty. I think you can close this, though a look at the documentation for the process might be in order.

**Comment by nodiscc** [comment]
@dsalo thanks for the confirmation. @miquelbotanch feel free to provide more information if [importing from Delicious/Pinboard](https://shaarli.readthedocs.io/en/master/Usage/#importexport) does not work as expected.
