### ISSUE TITLE
Typo in visibility link

### ISSUE THREAD

**Issue by williamdes** [shaarli/Shaarli#1946]
https://github.com/shaarli/Shaarli/blob/0d70e5e44f7a52a7f905e807e387f7ec40009efe/tpl/vintage/linklist.paging.html#L4

Should be **`v`** isibility

**Comment by williamdes** [comment]
@jvalleroy should we patch it into Debian or leave the link do a 404 until it's fixed here ?
Not sure if I should open a Debian bug

**Comment by nodiscc** [comment]
Thanks for the heads up, the vintage template probably receives less testing/users and this has gone unnoticed until now. I will patch it now.
