### ISSUE TITLE
Latest release version is not displayed in `/admin/server` since v0.12.2 release

### ISSUE THREAD

**Issue by nodiscc** [shaarli/Shaarli#1961]
![image](https://user-images.githubusercontent.com/3950390/226415798-2f1da65a-3a6f-41d3-b03b-ac4ce81025f9.png)

The latest release version number was still detected as `v0.12.1` since the `latest` branch was not yet updated. I removed the `latest` branch (see https://github.com/shaarli/Shaarli/pull/1959), for consistency we will now use a branch named `release` to check for the latest release version number.

Updated documentation/release procedure/version check branch in https://github.com/shaarli/Shaarli/pull/1960

**Comment by nodiscc** [comment]
![image](https://user-images.githubusercontent.com/3950390/226419143-5882ff5e-cf49-43b8-b7b6-6d78e508be63.png)

**Comment by agentcobra** [comment]
nice job ;)
