### ISSUE TITLE
Call to undefined function Shaarli\Bookmark\disk_free_space()

### ISSUE THREAD

**Issue by foxbille** [shaarli/Shaarli#1968]
I got
Call to undefined function Shaarli\Bookmark\disk_free_space()
[...]/Shaarli/application/bookmark/BookmarkIO.php171
after update 0.12.2
PHP version :  8.1
Does it mean my web hosting has disabled the “disk_free_space” ? If yes, what can i do ?
Thanks 
Eric

**Comment by ArthurHoaro** [comment]
[disk_free_space](https://www.php.net/manual/en/function.disk-free-space.php) function is part of the standard file system library, which you had installed if you just upgraded.
So yes, it's fair to assume that your host provider disabled that function. I would suggest that you contact their support first.
We could also check if the function exists before calling it in the code if they can't do anything.

**Comment by foxbille** [comment]
Thanks for replay
Provider is a french one : ouvaton
Support has replied that function is disabled.
I replaced code with "return true;"
Eric

**Comment by ArthurHoaro** [comment]
I applied this change as well if the function is not available.
