### ISSUE TITLE
Setup a public demo instance

### ISSUE THREAD

**Issue by nodiscc** [shaarli/Shaarli#198]
We could host a public Shaarli instance on https://aws.amazon.com/free/ for demo purposes. It would always be synced on master and would reset (cron job) every hour or so. What do you think?

**Comment by alexisju** [comment]
Why not :)  (but not on amazon!)

**Comment by pikzen** [comment]
>(but not on amazon!)

Why ? Legal and personal reasons aside (i.e. Amazon is in US), an EC2 instance offers great availability and SSH access. a t2.micro instance is more than enough to host Shaarli. Unless you know of hosts that offer SSH access AND a free tier, Amazon is the safest bet there is.

A nice side effect of that is that exposing a Shaarli instance to the world is one of the best way to detect bugs and potential attacks.

**Comment by Marsup** [comment]
For automated post-CI deployment I use heroku (which is hosted on AWS), no complains so far, great API. Why would you **need** SSH access anyway ?

**Comment by nodiscc** [comment]
we just need a free, up to date web server with PHP. I'm ok with suggestions other than amazon.

**Comment by alexisju** [comment]
When it's possible, in particulary for FLOSS project, i think is good to use hosting who promote also  freedom and respect users and datas about privacy etc... 

http://www.tuxfamily.org/ 
http://www.toile-libre.org/
http://www.domainepublic.net/
http://www.web4all.fr (usualy not free but sometimes support for free some project)

**Comment by nodiscc** [comment]
@alexisju I'm very ok with avoiding amazon, and using a freedom respecting service. toile-libre.org has been around for a long time and provides quality services, do you have some time to set up an account there? We just need a web server, and a cron job to delete and re-clone the repo at a decent interval.

**Comment by alexisju** [comment]
@nodiscc toile-libre is not free but "à prix libre". They don't mention cron in their services. Maybe are you talking about tuxfamily ? I'm ok to set it up.

**Comment by nodiscc** [comment]
Both are fine, but yes, I didn't check the pricing. I think we should go with tuxfamily, can you contact them? (just remember we need something like cron jobs to reset the demo). merci!

**Comment by alexisju** [comment]
Its working here : http://shaarlidemo.tuxfamily.org/  
or directly http://shaarlidemo.tuxfamily.org/Shaarli/
user/password = demo

**Comment by alexisju** [comment]
Feel free to mention the demo into the readme. Maybe using the same structure i've done on http://shaarlidemo.tuxfamily.org/
