### ISSUE TITLE
Cant catch qrcode or thumbails with a apache proxy made

### ISSUE THREAD

**Issue by Lurius-Kitsune** [shaarli/Shaarli#1990]
``Hello !

I have a proxy apache that redirect my shaarli in my local netwwork to -> ip/shaarli instead of ip:port

but the issue is with the script i got error 404 and file are searche here : 
- wanted : ip/shaarli/qrcode/qr-1.1.3.min.js net
- get : ip/qrcode/qr-1.1.3.min.js net

and 

- wanted : ip/shaarli/path/to/thumbail.jpg
- get : ip/path/to/thumbail.jpg
--------------------
- My apache setting for shaarli
```
ProxyPass /shaarli http://192.168.1.150:8000/
      	#ProxyPassReverse /shaarli http://192.168.1.150:8000/

      	ProxyHTMLURLMap http://192.168.1.150:8000 /shaarli
      
      	<Location /shaarli/>
      		ProxyPassReverse /
          Redirect /plugins http://rasp.fur/shaarli/plugins/	
      		SetOutputFilter  proxy-html
      		ProxyHTMLURLMap http://192.168.1.150:8000/ /shaarli/
      		ProxyHTMLURLMap / /shaarli/
      		ProxyHTMLURLMap /shaarli/ /shaarli/
      	</Location>
      	
```

**Comment by nodiscc** [comment]
Did you set `root_url` to `https://my.domain.tld/shaarli/` as described here https://shaarli.readthedocs.io/en/master/Shaarli-configuration/#general?

**Comment by Lurius-Kitsune** [comment]
> Did you set `root_url` to `https://my.domain.tld/shaarli/` as described here https://shaarli.readthedocs.io/en/master/Shaarli-configuration/#general?

I did it, but the result is still the same

**Comment by Lurius-Kitsune** [comment]
by taking a look seems that for the qrcode it's : `<input type="hidden" name="js_base_path" value="">` and the value seems to be the start of url so when I put "/shaarli" my qrcode work

but for the thumbail :/

**Comment by nodiscc** [comment]
>     My apache setting for shaarli

Is there a reason why you're not using the [recommended apache configuration](https://shaarli.readthedocs.io/en/master/Server-configuration/#apache)? Please try with the recommended configuration and update this issue why any errors that arise.
