### ISSUE TITLE
Update default links

### ISSUE THREAD

**Issue by alexisju** [shaarli/Shaarli#200]
When a user install the community version of Shaarli, default/demo links could also directly mention the community wiki / repository...

**Comment by alexisju** [comment]
It is not about documentation but into index.php directly (look for *Create a dummy database for example*) https://github.com/shaarli/Shaarli/blob/master/index.php#L780

**Comment by nodiscc** [comment]
Yes, I was thinking about also adding basic usage explanations/examples in the default links. (Basic tags, private links, RSS, Picture wall, search and filtering)

**Comment by alexisju** [comment]
URL : https://github.com/shaarli/Shaarli/wiki
Title :  Shaarli, the personal, minimalist, super-fast, no-database delicious clone
Description : 
Welcome to Shaarli ! This is a bookmark. To edit or delete me, you must first login.

To know more about how to use Shaarli, check the link "Help/documentation" on the bottom of this page.

You use the community fork of the original Shaarli project by sebsauvage.
---

I think i good to be very short and refer to wiki (who can be improved).
I think also is better to avoid to put links into description of this default links (by default, the concept of shaali, is to have one link by entry into the url field, not into description)...
About private link, there is also a private default link : users learn "naturally" the difference between private and public links links.

About the "branding" of this fork, maybe it is time to  be more clear to make the difference between this fork and the "legacy" version of Sebsauvage? We could try to find another name something  about "Community Shaarli" Or Shaarli2 (shaarli too/two)? ... or not if Sebsauvage migrate or merge his github project to this fork (who know?)  :)

**Comment by nodiscc** [comment]
I agree with everything

> About the "branding" of this fork, maybe it is time to be more clear to make the difference between this fork and the "legacy" version of Sebsauvage? 

Yes we could do this... it will be a breaking change (repo name change will break update URLs...) so I suggest we wait for the next batch of large changes (plugin system), but definitely before 1.0 if we go this way. Please open a separate issue.

**Comment by nodiscc** [comment]
We should have more than 1 public link visble by default, else the page title gets changed to the only default link's title (see http://shaarlidemo.tuxfamily.org/Shaarli/) which is weird.

**Comment by ArthurHoaro** [comment]
Having more than 1 public link isn't really useful. 

I've submitted PR #233  to fix the issue you're talking about (reported in #232).
