### ISSUE TITLE
It's really frustrating.

### ISSUE THREAD

**Issue by mkaaamk** [shaarli/Shaarli#2001]
It's really frustrating. Why can't software be developed and offered that is easy to install and set up, similar to WordPress? I have a Raspberry Pi 4 that is already configured. It has Apache, PHP 7.4, MySQL, PHPMyAdmin, and Let's Encrypt installed. The website is already up and running. Now I've been trying to install Shaarli for 5 hours. I've installed all the dependencies but I can't make any progress. I'm really annoyed because I previously tried to set up and install Shaark, but it didn't work at all. Now I'm trying to set up and install Shaarli, but I can't get it to install. Developers, what's the deal? Why do you create systems that are so difficult to install? Not everyone is an expert. You sit in front of the computer for hours and nothing happens. Excuse my language, but it's really frustrating. Why aren't there concrete, fully explained step-by-step instructions with pictures? Why is it not possible to create an application that is actually easy to install? How can I install Shaarli now? I'm really frustrated. I want to make progress. I have other things to do. I'd rather take my dog for a walk than deal with unnecessary hassle. So, how the hell can I get this Shaarli application up and running?

**Comment by nodiscc** [comment]
- Follow the documentation https://shaarli.readthedocs.io/en/master/Installation/
- Provide clear explanations of what your problem is, detailed steps to reproduces the issue, etc. Read http://www.catb.org/~esr/faqs/smart-questions.html twice.
- There is a full screencast of the installation process on https://shaarli.readthedocs.io/en/master/Server-configuration/

**Comment by mkaaamk** [comment]
These explanations and answers are not sufficient for an amateur. You're not helping me!
