### ISSUE TITLE
Option "sticky" is undocumented

### ISSUE THREAD

**Issue by Gnlfz007** [shaarli/Shaarli#2048]
The term "sticky" does not appear in any documentation and its intention is not self-explanatory. The entry disappears if it is sticky and filters are turned on which exclude the entry. So where is the entry actually sticked to?

**Comment by nodiscc** [comment]
It is "stickied" as the first item in the link list, bypassing the normal sort order (most recent first)

Sticky-ing a bookmark does not bypass active filters/search terms.
