### ISSUE TITLE
Missing timezone in docker image

### ISSUE THREAD

**Issue by ufm** [shaarli/Shaarli#2049]
datefmt_create: No such time zone: 'Europe/Kyiv': U_ILLEGAL_ARGUMENT_ERROR
/var/www/shaarli/application/Utils.php327

**Comment by nodiscc** [comment]
Hi, see https://github.com/shaarli/Shaarli/issues/1892.
Docker Image version?

**Comment by ufm** [comment]
> Hi, see #1892. Docker image version?
ghcr.io/shaarli/shaarli:latest

**Comment by nodiscc** [comment]
@ufm this should now be fixed (https://github.com/shaarli/Shaarli/pull/2054)

Can you please check?

**Comment by ufm** [comment]
> @ufm this should now be fixed (#2054)
> 
> Can you please check?

Yes, looks like fixed.
