### ISSUE TITLE
Highlight search results

### ISSUE THREAD

**Issue by nodiscc** [shaarli/Shaarli#205]
When doing a full text search, return the results with matching text highlighted.

Implemented in the https://github.com/broncowdd/Shinterest fork

**Comment by alexisju** [comment]
Great idea!

**Comment by ArthurHoaro** [comment]
+1

**Comment by alexisju** [comment]
function highLightSearchTerms($string,$searchterm){
    if (is_array($searchterm)){$searchterm=implode('', $searchterm); }
    $repl='<em class="highlight_term">'.$searchterm.'</em>';
    $replreg='\\1<em class="highlight_term">\\2</em>';
    $rule='(?<!href="|src=")(.+)('.$searchterm.')';
    return mb_eregi_replace($rule,$replreg,parse($string));
}

https://github.com/broncowdd/Shinterest/blob/master/inc/functions.php

**Comment by ArthurHoaro** [comment]
I have something more or less working: [ArthurHoaro/Shaarli:search-highlight](https://github.com/ArthurHoaro/Shaarli/tree/search-highlight)
Except this is not doable with the current Markdown plugin. I started to work toward a modulable formatter for links, but data link fields and displayable link fields got mixed up and the result isn't really satisfying.

I think this should be put on hold for now. #445 could help.
