### ISSUE TITLE
Add rename/delete buttons on tags in tag cloud

### ISSUE THREAD

**Issue by nodiscc** [shaarli/Shaarli#207]
Allows to edit or delete tags directly from the tag cloud.
Implemented in this fork https://github.com/broncowdd/Shinterest

**Comment by alexisju** [comment]
In daily use i dont think it is the best think to do. 
But in a "edit mode" it could be usefull to manage tags.

**Comment by nodiscc** [comment]
Yes it should be toggle-able with a switch `Edit mode ON [OFF]` to prevent clutter and misclicks in the tag cloud.

**Comment by alexisju** [comment]
in this case, it's nice :)

**Comment by n00b12345** [comment]
Just a small shoutout to this. I've just switched from Pinboard to Shaarli and I would _love_ to see this feature in the future.
