### ISSUE TITLE
Create a new tab instead of replacing current one

### ISSUE THREAD

**Issue by caxjm** [shaarli/Shaarli#2076]
Is there any switch that allow to create a new tab instead of replacing the current one when clicking on a bookmark at shaarli's web page on browsers? Thanks a lot!

**Comment by nodiscc** [comment]
Hi,
you can use this [third-party plugin](https://shaarli.readthedocs.io/en/master/Community-and-related-software.html#third-party-plugins): https://github.com/waschinski/shaarli-targetblank
