### ISSUE TITLE
My shaarli instance only shows the first link of page with "An unexpected error occurred."

### ISSUE THREAD

**Issue by Riduidel** [shaarli/Shaarli#2085]
Starting this week end, it seems like my Shaarli instance now only shows the first link on each page with "An unexpected error occurred." displayed on page upper side.
See this snapshot

![shaarli](https://github.com/shaarli/Shaarli/assets/171018/829885bc-338a-46e6-be5b-62e8d188c042)

My shaarli is available at https://nicolas-delsaux.hd.free.fr/Shaarli/index.php

**Comment by Riduidel** [comment]
Seems like I got a reproduction of #2065

**Comment by Riduidel** [comment]
My php 8.1 comes from

```
pi@raspberrypi:~ $ apt policy php8.1
php8.1:
  Installed: 8.1.28-1+0~20240424.64+debian11~1.gbpd7b516
  Candidate: 8.1.28-1+0~20240424.64+debian11~1.gbpd7b516
  Version table:
 *** 8.1.28-1+0~20240424.64+debian11~1.gbpd7b516 500
        500 https://packages.sury.org/php bullseye/main armhf Packages
        100 /var/lib/dpkg/status
```

**Comment by kcaran** [comment]
I commented on #2065 as well:

I'm using Centos 8, but I had the same issue and made this note to myself:

(2022-03-31 Added php-intl to install - didn't automatically add the module)
http://tutorialspots.com/php-how-to-install-intl-module-on-centos-4357.html

It looks like there is a php-intl package on Debian as well.

**Comment by Riduidel** [comment]
Looks like the same problem, but is not : php-intl is installed on my raspberry

**Comment by ArthurHoaro** [comment]
If you login, you should have stack trace. Is it the same error as the one you linked?

**Comment by Riduidel** [comment]
Yes, I have the error when logged in (and can't log out)

**Comment by ArthurHoaro** [comment]
This error could potentially come from a bug fixed by #2044 (not released). You could try to make sure that your locale is properly defined in your PHP config.

**Comment by Riduidel** [comment]
I've set the locale to fr-FR using `intl.default-locale`, but it changed nothing

**Comment by Riduidel** [comment]
Wait, after setting the `intl.default-locale`, re-running the `sudo dpkg-reconfigure locales`, restarting both php-fpm and apache2, it worked again !
