### ISSUE TITLE
Invalid documentation link in admin/tools page?

### ISSUE THREAD

**Issue by SansGuidon** [shaarli/Shaarli#2104]
Hi,
While opening my instance `/admin/tools` page, whenever I click on `Community and related software` it opens a broken link at https://shaarli.readthedocs.io/en/master/Community-and-related-software/

**Comment by SansGuidon** [comment]
Should, but is it a technical requirement? It's really up to the CI/CD strategy you define but the general trend and expectation imho for such productivity tools is to continuously ship features and fixes through continuous intermediate/minor version bumps. So unless there is an obvious reason (breaking changes? coupling?) to not ship, it's also good to release whatever can already improve users experience? blocking some improvements which are as old as the one you linked (11 months old) seems a bit counter productive?

**Comment by nodiscc** [comment]
You are right -> https://github.com/shaarli/Shaarli/issues/2105
