### ISSUE TITLE
"Hide all public links" is broken/does not work as expected

### ISSUE THREAD

**Issue by nodiscc** [shaarli/Shaarli#212]
In addition to https://github.com/shaarli/Shaarli/issues/202 and https://github.com/shaarli/Shaarli/issues/199; hiding public links does not work when:

 * you access the tag cloud
 * you access the picture wall
 * you access a search URL (`?searchterm=test` or `?searchtags=test`)

In these cases, public links are still displayed. The switch on the settings page lets the user think that all links are hidden, when in fact they are not. I suggest we fix this as soon as possible or remove the broken "Hide all public links" feature from master (move it to a branch)

**Comment by pikzen** [comment]
It's not a bug, it's a feature :trollface:

Fixed in #214
