### ISSUE TITLE
Provide an optional (opt-out) link to shaarli.fr in the menu bar

### ISSUE THREAD

**Issue by jeekajoo** [shaarli/Shaarli#217]
Hey,

shaarli.fr is a nice tool, it became very popular, you can now choose who you want to follow (Thanks @DMeloni)

I think that people that have no clue about what shaarli is/became should know we can use it like twitter and discover new stuff with new people.

I suggest it to be opt-out (and not opt-in, but it's up to you then), because well.. we need to spread the world and decentralize the Internet.

What do you think?

Thanks
J.

**Comment by DMeloni** [comment]
[French]

Salut ! 

Juste pour donner mon avis sur les pour et les contre : 
Les pour:
- plus de visites sur le site shaarli.fr ? les utilisateurs de l'outil en ont vite connaissance
- plus de sensibilité à la décentralisation ? honnêtement je ne sais pas car si le lien est vraiment dans l'outil, l'utilisateur l'aura quand même installé quelque part (donc il fera surement déjà du décentralisé)

Les contre : 
- si j'installe un outil, je veux qu'il soit le plus indépendant possible et au possible de pas avoir de liens vers des sites tierces, surtout quand ses mêmes sites n'ont pas de rapport direct avec le développement du logiciel. En bref, il n'est pas du tout légitime que le site shaarli.fr soit considéré comme officiel alors qu'il n'en a que le nom de domaine en .fr
- découlant de ça, si le site ferme un jour pour x ou y raison, on se retrouve avec x utilisateurs de l'outil qui se retrouvent avec un lien par défaut qui ne marche plus.
- en bref si tu veux proner la décentralisation, il faut (à mon avis toujours) justement éviter de mettre en avant tel ou tel site puisque justement !

Par contre, 
dans l'idée où on pourrait laisser l'utilisateur afficher un lien supplémentaire/personnalisable sur son shaarli, c'est plutot intéressant :-)

Voilà...je pense de plus que le site est assez vite connu par les utilisateurs de shaarli donc il n'y a pas vraiment de valeur ajoutée à ce lien.


Qu'en penses tu jeekajoo ?

**Comment by jeekajoo** [comment]
yes, that might not be a good idea
especially if we aim to make this tool (shaarli) more popular outside france.
and shaarli.fr is very french focused.

but your idea with a custom additional link is interesting.

**Comment by jeekajoo** [comment]
Let's close this.

**Comment by nodiscc** [comment]
@jeekajoo Yep I don't think linking to a particular instance of a particular tool would help. However, feel free to edit the wiki and link to the shaarli.fr **self-hostable tool source code**, and give shaarli.fr as an example. (Related projects section)

> your idea about a custom additional link is interesting.

Yes and this is something I started drafting as a plugin. Sorry for the lack of updates. I think you could report this a separate request.

**Comment by DMeloni** [comment]
I will write some codes for english support :)
