### ISSUE TITLE
Add themes management

### ISSUE THREAD

**Issue by qwertygc** [shaarli/Shaarli#22]
Hello !
It's possible to add a themes managment e.g a folder by theme ? And a variable show the theme.
A other suggestion it's the possibility to translate shaarli.
Regards

**Comment by alexisju** [comment]
Why do you consider that a "theme" is just another CSS ? To make AlbinoMouse (http://liens.effingo.be) i had to change many tpl to design really a something different. 

It's why i need to maintain another full repository (what is not very convenient).

**Comment by nodiscc** [comment]
@alexisju Yep! This is why we differentiate between themes and templates (btw albinomouse is very nice)

 * There is a *templates* repository at https://github.com/shaarli/templates
   * You could add albinomouse to it like we did for hoa.ro
 * There is a *themes* repository at https://github.com/shaarli/shaarli-themes
  * These are themes for the default template

There is still much work to do about this but in the future, users could:

 * clone the *templates* repository to eg. `templates/` in their Shaarli install
 * set their config variable `$GLOBALS['config']['RAINTPL_TPL'] = 'templates/albinomouse/` to use your template + theme

There **could** be a config variable `$GLOBALS['config']['CSS_THEME']`. This would allow selecting the CSS file in use for the current theme; but we need to standardize that (eg. Shaarli's default is `shaarli.css`, yours is `albinomouse.css` and in the hoaro theme it's `css/style.css`)

But in the long run, I'm not sure we should add theme management. Collecting themes and templates is a good idea, but simply replacing `user.css` is already nice and doesn't interefer with the update process.

**Comment by alexisju** [comment]
ok, I'll consider this to try to make my templates a bit more compliant to follow future updates from the community forks of shaarli :)
