### ISSUE TITLE
Firefox tag entry fails

### ISSUE THREAD

**Issue by seigler** [shaarli/Shaarli#220]
In Firefox the tags field is not populated or saved when editing a bookmark.

**Comment by nodiscc** [comment]
Hi, I can't reproduce this. Please provide any relevant message you can find in Firefox's error console or in your webserver logs.

You can also try [resetting Firefox](https://support.mozilla.org/en-US/kb/reset-preferences-fix-problems), disabling your addons, or [create a blank Firefox profile](https://support.mozilla.org/en-US/kb/profile-manager-create-and-remove-firefox-profiles) and test again.

Does this solve your problem?

**Comment by seigler** [comment]
In Firefox's console I see "15:14:02.152 NS_ERROR_FAILURE: 1 awesomplete.min.js:2:0" which seems to be a cross-domain request failure.

**Comment by nodiscc** [comment]
Plesae try from a blank Firefox profile.

**Comment by seigler** [comment]
Same issue from a blank Firefox profile. One difference might be that I am hosting Shaarli under https instead of http.

**Comment by seigler** [comment]
Figured it out. One of my imported tags was "Mark Twain" which ended up parsed as ("Mark) and (Twain"). Chrome was able to handle the unescaped quotes somehow and fix the DOM, but in Firefox it was just an invalid input field.
