### ISSUE TITLE
Character escaping and potential XSS

### ISSUE THREAD

**Issue by ArthurHoaro** [shaarli/Shaarli#224]
As I said on Gitter, there is a problem with tags escaping. Since we use awesomplete, all tags are now present in HTML structure and they're not escaped when there is a field which can be autocompleted (my bad!).

It only concerns logged in users, so it's not a critical security issue but it has to be fixed. Also any `"` breaks autocompletion.

I took a look, and character escaping seems to be a bit of a mess:

  * Nothing is escaped while saving user input in datastore. Everything is base64 encoded, but I'm not sure that's really safe.
  * Some fields are escaped with `htmlspecialchars` while rendering the page. eg: description in linklist.
  * Some other are escaped in templates. eg: tags in linklist.

We should keep the same rule for every user input, and IMO, not escape them in templates. 

What's your opinion on this? Also should we escape data before saving it?

EDIT: in anyway, I think this issue should be in the soonest milestone.

**Comment by ArthurHoaro** [comment]
About the XSS on tags, create a link with this tag:

    "><script>alert("test");</script><

and edit it.

**Comment by nodiscc** [comment]
Well spotted. My 2 cents: everything that contains user input should be escaped with `htmlspecialchars` during rendering.

> Also should we escape data before saving it?

I don't think this is needed. Or is it? The datastore is in a php comment block anyway so we should be reasonably safe against arbitrary code execution

Thanks a lot for reporting this @ArthurHoaro and @seigler for pointing it out..

**Comment by nicolasdanelon** [comment]
I use this functions for clean inputs... maybe it can help
https://gist.github.com/nicolasdanelon/26bca38391e43a771243

**Comment by nodiscc** [comment]
This seems to be fixed at first glance. If you find a way to reproduce the XSS again, please add your comment/steps to reproduce.

**Comment by ArthurHoaro** [comment]
I think it's OK to close this issue. It can be reopened later if a related issue is found.
