### ISSUE TITLE
Add media enclosures to RSS feeds

### ISSUE THREAD

**Issue by nodiscc** [shaarli/Shaarli#226]
https://en.wikipedia.org/wiki/RSS_enclosure

> RSS enclosures are a way of attaching multimedia content to RSS feeds by providing the URL of a file associated with an entry, such as an MP3 file to a music recommendation or a photo to a diary entry. Unlike e-mail attachments, enclosures are merely hyperlinks to files, the actual file data is not embedded into the feed (unless a data URL is used). 

The link's thumbnail (if it exists) could be used as enclosure

**Comment by ArthurHoaro** [comment]
Media enclosures are usually used for downloadable files (I'm thinking stuff like podcasts) which are not the case of thumbnails. They're here to add an illustration, in the content. I suggest that we close this as 'wontfix'.

**Comment by ArthurHoaro** [comment]
:point_up_2:

**Comment by ArthurHoaro** [comment]
Closing. Feel free to reopen if you think that feature is still needed.
