### ISSUE TITLE
Tag entry field is too small

### ISSUE THREAD

**Issue by nodiscc** [shaarli/Shaarli#235]
![shaarli](https://cloud.githubusercontent.com/assets/3950390/8314539/5bc5adbe-19ea-11e5-9850-6ec63b4baf8e.png)

This happens since https://github.com/shaarli/Shaarli/commit/4c68c20cdd2baec36c03aa6237d2d932605b6252

**Comment by nicolasdanelon** [comment]
Yes, my fault. Sorry for small pulls with poor testing. I'm with this now. But we need to move the CSS to [OOCSS](https://www.google.com.ar/search?q=object+oriented+css) Just because this can not happen again. I'll work on OOCSS ASAP too.
OOCSS = one "class" for structure, one "class" for styling.

**Comment by ArthurHoaro** [comment]
I didn't know OOCSS, that's an interesting concept. However, it's probably a lot of work with this 1K lines CSS file.

**Comment by nicolasdanelon** [comment]
No no, is not about that, it's about avoid a big CSS file!
but we need to rewrite some html structures.. and the whole CSS.
OOCSS was born in 2008 when people write big stylesheets and was hard to edit and add new styles. If we turn shaarli CSS code into this technique we won't have this issues again

**Comment by nodiscc** [comment]
As discussed with @mrjovanovic in https://github.com/shaarli/Shaarli/issues/174, proposing a new default template would be welcome, I think. A simple responsive grid system (https://thisisdallas.github.io/Simple-Grid/ or other) could be used, along with best webdev practices.

We should still fix the current stylesheet for now.

**Comment by nodiscc** [comment]
Not fixed http://shaarlidemo.tuxfamily.org/Shaarli/?post=
