### ISSUE TITLE
Statistics : number private links, database and cache size

### ISSUE THREAD

**Issue by ArthurHoaro** [shaarli/Shaarli#247]
Discussed in #106:

  * Add counters for number of public and private links to the tools page.
  * Add counters for datastore and cache directories to the tools page.

Maybe highlight cache size if it's anormaly big.

**Comment by nodiscc** [comment]
My vote goes to only separate number of public/private links counters. db and cache size can be checked with a simple file manager/sftp/ftp client, and they should not be that large

For me:

```
$ du -hc data/datastore.php cache/ tmp/
292K	data/datastore.php
18M	cache/
120K	tmp/
19M	total
```

Other numbers are welcome.

Related to https://github.com/shaarli/Shaarli/issues/185
