### ISSUE TITLE
LinkDB test inconsistencies (filesize)

### ISSUE THREAD

**Issue by virtualtam** [shaarli/Shaarli#252]
When having PRs tested by Travis, there are seemingly random failures on the following tests:
* testCheckDBNew
* testCheckDBLoad

As an example, builds [15](https://travis-ci.org/shaarli/Shaarli/builds/68601602) (failure) and [16](https://travis-ci.org/shaarli/Shaarli/builds/68602640) (success) were tested against the same commit content (just amended to trigger a new build).

Moreover, my fork's build [21](https://travis-ci.org/virtualtam/Shaarli/builds/68602639) (failure) was started by the same commit as 16 (success).

Does anyone have any idea why the datastore size varies from time to time? And how to tackle this in tests?

**Comment by virtualtam** [comment]
This seems to happen due to the serialization of dynamic dummy link dates (see #238).

Should the tests be more permissive, i.e. check if the datastore's filesize is comprised within a given range, instead of a fixed one?

**Comment by nodiscc** [comment]
What does this test do? Check the filesize to see if the dummy link has been stored? If yes, just checking for a filesize > 0 should do it. Right?

**Comment by virtualtam** [comment]
Good idea! The following should suffice:
* check a new datastore file is non-empty (filled with dummy links)
* check an existing datastore is left unchanged by `LinkDB::checkDB()`

PR upcoming :)
