### ISSUE TITLE
'javascript:' links escaping problem when pasted in a description

### ISSUE THREAD

**Issue by nodiscc** [shaarli/Shaarli#253]
**How to reproduce:**
create a new link and paste this in the description field, then save:

    javascript:location.href='http://www.reddit.com/submit?url='+encodeURIComponent(location.href)+'&title='+encodeURIComponent(document.title) example bookmarklet

**Expected results:**
The description text should display fully in the linklist.

**Actual results:**
The displayed description is somehow trimmed to `javascript:location.href=') example bookmarklet`.

**Comment by ArthurHoaro** [comment]
I can't reproduce your issue. But the part that seems to disapear in your test is the one is the one transformed in link here:

![screen](http://i.imgur.com/abHOYlP.png)

**Comment by nodiscc** [comment]
I will check with a different Firefox profile. I suspect my ad blocker to interfere...

**Comment by ArthurHoaro** [comment]
I just tried and it's also working...

Can you also check the HTML result?

**Comment by virtualtam** [comment]
Working here as well on Firefox (µBlock, Ghostery), Chromium (µBlock) and Midori (built-in ad-block)

**Comment by nodiscc** [comment]
Can confirm it was altered by my ad blocker, following event appears in the requests log:

``14:02:38		##[href^="http://www.reddit.com/submit"]	--	dom	http://shaarlidemo.tuxfamily.org/Shaarli/?#PGQM2g``
