### ISSUE TITLE
The page isn't redirecting properly

### ISSUE THREAD

**Issue by fturco** [shaarli/Shaarli#256]
I'm running an instance of Shaarli 0.0.45-beta on my local desktop computer. If I click on a tag in the main view I get the following error from Iceweasel/Firefox 38.0.1:

> The page isn't redirecting properly. Iceweasel has detected that the server is redirecting the request for this address in a way that will never complete. This problem can sometimes be caused by disabling or refusing to accept cookies.

I also tried with a clean, new Iceweasel profile.

If I move the mouse over the "linux" tag I see the "http://127.0.0.1/shaarli/?addtag=linux" link. But if I click on it I'm redirected to the http://127.0.0.1/shaarli/?addtag=linux&searchtags=linux, which doesn't work.

**Comment by ArthurHoaro** [comment]
I can't reproduce this issue on master or latest release. Could you try on latest commit?

However [this part](https://github.com/shaarli/Shaarli/blob/master/index.php#L1090) rely on HTTP_REFERER, which I believe unreliable. So there might be an issue.

If you confirm this issue, i suggest you show us what's giving:

  * `var_dump($_SERVER['HTTP_REFERER']))` after L1091
  * `var_dump($params)` after L1094

**Comment by fturco** [comment]
I tried the latest git version, and I can still reproduce the problem.

I don't know PHP programming. I tried anyway adding those instructions in `index.php` and placing a semicolon at the end of each one. But I just see the Iceweasel error message again, and nothing else. Am I supposed to do something differently?

**Comment by ArthurHoaro** [comment]
Alright, my bad.

Could you retrieve [my branch](https://github.com/ArthurHoaro/shaarli/tree/shaarli-256) with the following:

    git remote add arthur https://github.com/ArthurHoaro/Shaarli.git
    git fetch arthur
    git checkout shaarli-256

Then can you give us the result when you click on this link:

![screenshot](http://i.imgur.com/v14K0ce.png)

**Comment by fturco** [comment]
string(43) "http://127.0.0.1/shaarli/?addtag=opensource" array(1) { ["addtag"]=> string(10) "opensource" } string(39) "addtag=opensource&searchtags=opensource"

**Comment by ArthurHoaro** [comment]
Thank you. Your browser is sending the current URL as [HTTP referer](https://en.wikipedia.org/wiki/HTTP_referrer) instead of the previous one, probably for privacy matters, which causes this bug. I'll submit a PR to fix it.

**Comment by fturco** [comment]
I haven't modified my browser behaviour directly. I think it may be due to the fact that I use HTTPS Everywhere and uBlock extensions, but I'm not sure.

**Comment by ArthurHoaro** [comment]
I don't really know either... Please checkout `tag-http-referer` and let us know if this fix your issue.

**Comment by fturco** [comment]
It works now. Thank you!

**Comment by fturco** [comment]
Reopening because I noticed that I get "The page isn't redirecting properly" error also when removing a tag: http://127.0.0.1/shaarli/?removetag=opensource

**Comment by fturco** [comment]
It seems applying a similar modification to `index.php` after line 1129 makes it work:
```
// Prevent redirection loop
if(isset($params['removetag'])) {
    unset($params['removetag']);
}
```

**Comment by ArthurHoaro** [comment]
You're right. Can you also check the behaviour of those links:

  * `/?privateonly`
  * `/?linksperpage=100`

`HTTP_REFERER` is also used in other function, I'll do further tests.

**Comment by fturco** [comment]
Yeah, my browser returns the same error with those two links too.

**Comment by ArthurHoaro** [comment]
Can you also provide your settings in `about:config` searching `referer`:

![img](http://i.imgur.com/lbuQ8qB.png)

**Comment by fturco** [comment]
My settings are identical to yours except for `network.http.referer.spoofSource` which is set to `true`.

**Comment by ArthurHoaro** [comment]
That's it. Spoofing the referer means using target URI as referer (is there any up to date documentation?!).

**Comment by virtualtam** [comment]
[Browser](https://github.com/shaarli/Shaarli/wiki/Troubleshooting#browser) section added to the Troubleshooting page.

The following links may prove useful:
- [HTTP referer](https://en.wikipedia.org/wiki/HTTP_referer) (Wikipedia)
- [Improve online privacy by controlling referrer information](http://www.ghacks.net/2015/01/22/improve-online-privacy-by-controlling-referrer-information/)
- [Better security, privacy and anonymity in Firefox](http://b.agilob.net/better-security-privacy-and-anonymity-in-firefox/)
