### ISSUE TITLE
Add OpenGraph metadata

### ISSUE THREAD

**Issue by qwertygc** [shaarli/Shaarli#258]
it's possible to implante h-entry on shaarli ?

**Comment by nodiscc** [comment]
What does this do?

**Comment by qwertygc** [comment]
http://microformats.org/wiki/h-card

**Comment by nodiscc** [comment]
I suggest enabling more [Opengraph](http://ogp.me/) metadata on Shaarlis instead. Opengraph is a well known and widely used standard, and as far as I can see, the opengraph metadata properties supersede the h-card [properties](http://microformats.org/wiki/h-card#Properties).

Or does h-card do something that opengraph does not?

There is no commit messages on https://github.com/shaarli/Shaarli/pull/259 which doesn't help knowing what your edits actually do.

Explaining in french is also fine.

**Comment by virtualtam** [comment]
Hello @qwertygc,

Could you elaborate a bit what h-cards are, and in which way(s) they could benefit to Shaarli?

* h-cards seem to have a purpose very similar to vCards, that is, holding an individual's information (address, contact, websites, etc.)
* OpenGraphs look like inserting Semantic Web elements (namely, RDF schemas) into a web page, using `<meta>` tags

Could you squash the commits from #259 and provide a more explanatory commit message?

Here's an example:
```
semantics: implement h-card support

Adds <some feature> because of <some reason/user need>

Reference:
 - http://microformats.org/wiki/h-card
 - <any useful link>

Modifications:
 - <Shaarli features impacted by the commit>
```

**Comment by qwertygc** [comment]
sorry, it's more easy for me to speak in french.

En gros les h-card permettent de rajouter de la sémantique. Les h-card sont un truc standardisés.  Il est utilisé par indewebcamp (http://indiewebify.me/) pour faire un réseau social décentralisé, dans le même objectif que shaarli. À terme, je compte rendre totalement compatible avec ce qui est décrit (avec POSS rt webmentions et autres, cf leur wiki).

Opengraph est quand a lui spécifique à Facebook et ne sert que ce dernier. 

Au final, voulez-vous etre asservi à facebook en utilisant un protocole quasiment propriétaire ou être libre en faisant quelque chose de décentralisé ?

**Comment by qwertygc** [comment]
Opengraph n'est pas reconnu par le w3c hcard si.

**Comment by virtualtam** [comment]
If you don't mind, I'll translate questions / remarks and answer to them in English :)

> h-cards allow to add semantics

[hCard](https://en.wikipedia.org/wiki/HCard) is a [microformat](https://en.wikipedia.org/wiki/Microformat), that allows using HTML classes to add personal information semantics (see Wikipedia links for examples)

> h-cards are a standard

As far as the W3C is concerned, hCard is currently an experimental profile specification, derived from the vCard RFC:
* http://www.w3.org/2006/03/hcard
* http://semanticweb.org/wiki/HCard
* http://microformats.org/wiki/hcard
* http://microformats.org/wiki/rfc-2426, http://www.ietf.org/rfc/rfc2426.txt

> [h-card] is used by IndieWebCamp to provide a decentralized social network, serving the same purpose as Shaarli

Though it encourages self-hosting, and keeping an eye on your personal data, Shaarli has no decentralized nor social role by itself.

RSS/Atom agregators, as well as Shaarli River, on the other hand, bring a decentralized, social (yet limited) dimension to Shaarli.

> eventually, I want to be fully compatible with the [IndieWeb] specifications ([POSSE](http://indiewebcamp.com/POSSE), [Webmention](http://indiewebcamp.com/Webmention))

For Shaarli to be IndieWeb-ready, you'll need at least to:
* add semantics to all published content
  * store additional information
  * modify RainTPL templates to support semantics
* implement a Pingback / Webmention feature, to notify websites when publishing a link on your Shaarli

> OpenGraph is specific to Facebook, which it only serves

There are plenty of examples of cool OpenSource projects delivered by corporate entities, that can be used for self-hosting:
* Twitter's [Bootstrap](http://getbootstrap.com/)
* Facebook's OpenSource [projects](https://code.facebook.com/projects), and contribution to multiple community projects, such as [Mercurial](https://code.facebook.com/posts/218678814984400/scaling-mercurial-at-facebook/)
* Google's [CoreOS](https://coreos.com/), [Chromium](http://www.chromium.org/)...

> do you want to be enslaved to Facebook by using an almost proprietary protocol

By the very moment a piece of software has been declared Open Source, it tends to be assimilated by its community, which will fork it in case of a disagreement. The best examples that come to mind are most projects that were developed by Sun, and that have been forked when the company was bought by Oracle:
* OpenOffice => LibreOffice
* Hudson => Jenkins
* MySQL => MariaDB
* ... hey, why is there no VirtualBox fork yet‽

From an ethical point of view, I agree that it seems uncomfortable to use libraries developed by companies turning your personal data into profit, to design self-hosting solutions.

The thing is, they may be more robust, more actively developed, and better documented, than many community-driven projects...

**Comment by ArthurHoaro** [comment]
While Shaarli doesn't have any social role by itself, I don't see any problem complying with a decentralized standard. If Shaarli's content can be understand through these standards, why not. Especially if it's only a matter of CSS classes and/or meta tags.

However, h-card standard doesn't seem to be much known and used. There is no point complying with a standard if we're the only one to do so.

I'll review your PR later if we decide to go with hcards.

**Comment by qwertygc** [comment]
Je comprends les arguments et je les entends. Néanmoins, shaarli est bien décentralisé. mise a part le my de shaarli.fr, on est obliger de l'installer sur son serveur.

Si on met pas les hcards, puis-je au moins améliorer shaarli à coup de <article> et de <time> ?

**Comment by qwertygc** [comment]
Rhaa. De balise time et article

**Comment by nodiscc** [comment]
OpenGraph has the advantage of being widely used already - a lot of services and applications, bot Free and proprietary - do publish and/or parse og metadata (by the way, the generic thumbnailer patch uses `og:image` to find thumbnails).

You could also use `og:article:published_time` (check http://ogp.me/#no_vertical) to publish article dates.

Minor point, Shaarli is not decentralized/distributed (just self-hostable), but using metadata as provided by OpenGraph or hCard could allow [federation](https://en.wikipedia.org/wiki/Federation_%28information_technology%29) of Shaarlis.

**Comment by qwertygc** [comment]
Ok for the minor point, you have understand my thought.
I have ask the question on forum's alsacreations (http://forum.alsacreations.com/topic-2-76328-1-Opengraphouh-entry.html), a french website for web standards.

The implantation is easy, because just template change.

**Comment by mro** [comment]
@qwertygc what do you want to achieve with hCard? Machine readability comes already with the atom feed.

**Comment by Lucas-C** [comment]
I do not want to re-open a similar issue, but I would also be interested in adding [microformats](https://indieweb.org/microformats) semantic attributes/metadata on Shaarli...

As this been totally dismissed ? Should I open another issue ?
