### ISSUE TITLE
Ajouter deux liens au wiki

### ISSUE THREAD

**Issue by qwertygc** [shaarli/Shaarli#263]
Hello !

J'ai codé deux outils (enfin, un est une variation de l'autre), permettant de détecter les liens morts sur les instances shaarlis. Si ça intéressent du monde, pourquoi pas le rajouter au wiki ?

https://github.com/qwertygc/shaarli-dev-code/blob/master/self-dead-link.php
https://github.com/qwertygc/shaarli-dev-code/blob/master/dead-link.php

**Comment by virtualtam** [comment]
This feature could even be added to Shaarli's administration panel :)

**Comment by ArthurHoaro** [comment]
Yep. In the meantime, @qwertygc you can edit the wiki and add your tools under "Related software".

**Comment by qwertygc** [comment]
OK, je modifie le wiki. Je demandais juste l'autorisation pour éviter que "ça fasse de la pub".

**Comment by nodiscc** [comment]
Thank you. All future changes like this one are welcome.
