### ISSUE TITLE
Tags: input matches are colored only for the first suggestion

### ISSUE THREAD

**Issue by virtualtam** [shaarli/Shaarli#265]
When adding tags to a link, the part matching what has been typed in the input field is only colored for the first suggestion:

![tag1](https://cloud.githubusercontent.com/assets/1615162/8584702/b3373180-25d9-11e5-9c09-8672fe38d555.jpg)
![tag2](https://cloud.githubusercontent.com/assets/1615162/8584701/b3343700-25d9-11e5-920f-885bdb49003e.jpg)

**Comment by alexisju** [comment]
You can add another (linked?) bug : suggestions dont appear colored either if you add tags from an existing link (edit).

**Comment by ArthurHoaro** [comment]
I've already reported this issue here leaverou/awesomplete#16749.

**Comment by ArthurHoaro** [comment]
Moved to LeaVerou/awesomplete#16814

**Comment by virtualtam** [comment]
@ArthurHoaro should we close this issue? Completion works for multiple tags on the current `master`

**Comment by ArthurHoaro** [comment]
Sure!
