### ISSUE TITLE
Use DateTime to format dates and timestamps

### ISSUE THREAD

**Issue by virtualtam** [shaarli/Shaarli#270]
It would be more robust and flexible to use the built-in [DateTime](http://php.net/manual/en/class.datetime.php) object, and pass is to RainTPL templates, than relying on tedious string processing in `index.php`:

```php
/*  Converts a linkdate time (YYYYMMDD_HHMMSS) of an article to a timestamp (Unix epoch)                
    (used to build the ADD_DATE attribute in Netscape-bookmarks file)                                   
    PS: I could have used strptime(), but it does not exist on Windows. I'm too kind. */
function linkdate2timestamp($linkdate)
{
    if(strcmp($linkdate, '_000000') !== 0 || !$linkdate){
        $Y=$M=$D=$h=$m=$s=0;
        $r = sscanf($linkdate,'%4d%2d%2d_%2d%2d%2d',$Y,$M,$D,$h,$m,$s);
        return mktime($h,$m,$s,$M,$D,$Y);
    }
    return time();
}

/*  Converts a linkdate time (YYYYMMDD_HHMMSS) of an article to a RFC822 date.                          
    (used to build the pubDate attribute in RSS feed.)  */
function linkdate2rfc822($linkdate)
{
    return date('r',linkdate2timestamp($linkdate)); // 'r' is for RFC822 date format.
}

/*  Converts a linkdate time (YYYYMMDD_HHMMSS) of an article to a ISO 8601 date.                        
    (used to build the updated tags in ATOM feed.)  */
function linkdate2iso8601($linkdate)
{
    return date('c',linkdate2timestamp($linkdate)); // 'c' is for ISO 8601 date format.
}
```

**Comment by ArthurHoaro** [comment]
I've no idea how to call an object method from a RainTPL template. I'm not sure that's possible.

**Comment by virtualtam** [comment]
It requires to enable PHP evaluation (or rather, by looking at the code, prevent PHP tags from being escaped) for RainTPL template rendering, see [l. 93](https://github.com/rainphp/raintpl/blob/3bd60d3843f2048b57875de68bd118eddca1eeb5/inc/rain.tpl.class.php#L93) and [l. 318](https://github.com/rainphp/raintpl/blob/3bd60d3843f2048b57875de68bd118eddca1eeb5/inc/rain.tpl.class.php#L318) in `rain.tpl.class.php`:

Code:
```php
raintpl::configure( "php_enabled", true );
```

Template:
```php
<?php $myObject->doSomeStuff() ?>
```

(Seems a bit simpler, and better documented, [in Smarty](http://www.smarty.net/docs/en/advanced.features.objects.tpl))

**Comment by ArthurHoaro** [comment]
Not a big fan of using PHP in templates. I'd prefer if we don't, until an eventual replacement of RainTPL (also easy [in Twig](http://stackoverflow.com/questions/15277736/access-an-object-method-with-twig)).

However, we can use DateTime for date manipulation in `index.php` and pass timestamps to templates, for now.

**Comment by virtualtam** [comment]
Yep, sounds good!
