### ISSUE TITLE
Filter by tag input field is way too long

### ISSUE THREAD

**Issue by fturco** [shaarli/Shaarli#272]
I tried latest Git version and I noticed a problem with the filter by tag input field in the up-right part of the screen. It's simply too long, and I need to scroll the page horizontally to see the corresponding Search button.

![shaari-full](https://cloud.githubusercontent.com/assets/5459866/8633410/55236aec-27c7-11e5-8f74-bdabca3a6abc.png)

**Comment by ArthurHoaro** [comment]
Do you have javascript enabled?

**Comment by fturco** [comment]
Option `javascript.enabled` in about:config is set to true.

**Comment by ArthurHoaro** [comment]
Ok. I've no idea what's going on, so let's gather info:

  * what's your browser and version?
  * did you try to clear your cache?
  * did you try another browser?
  * does tag autocompletion in the search field work?
  * is there anything in the Javascript console?
  * does you HTML generated structure look like that:

![img](http://i.imgur.com/hKLmm16.png)

**Comment by nodiscc** [comment]
@fturco in addition to @ArthurHoaro's points, can you also reproduce this bug on http://shaarlidemo.tuxfamily.org/Shaarli/? (demo/demo)

**Comment by fturco** [comment]
@nodiscc No, I can't reproduce the problem at your website.
@ArthurHoaro I will now test Shaarli in order to gather the info you required.

**Comment by fturco** [comment]
I cleared my browser's cache and now I can't reproduce the problem anymore.

**Comment by ArthurHoaro** [comment]
Glad to hear that. :)
