### ISSUE TITLE
RSS and ATOM feed: rely on templates

### ISSUE THREAD

**Issue by ArthurHoaro** [shaarli/Shaarli#273]
Feeds are currently generated in `index.php` (`showRSS()`, `showATOM()`). It would be better if their items were generated through template, like it's done with dailyRSS.

**Comment by alexisju** [comment]
Maybe this still usefull (or necessary?) for shaarlo (or "rivers") to have "standard" rss feed shaarlis ?

**Comment by ArthurHoaro** [comment]
RSS and ATOM are both standardized formats. As long as its XML is valid, its content shouldn't be an issue.

Also having RSS *and* ATOM is pointless IMHO.

**Comment by DMeloni** [comment]
No prob for shaarlo.

**Comment by alexisju** [comment]
Great :-)

**Comment by virtualtam** [comment]
+1, a bit of refactoring and standardization would do no harm to feed generation methods (`?do=rss`, `?do=atom`, `?do=dailyrss`) :)
