### ISSUE TITLE
Installation: timezone can't be selected without JS

### ISSUE THREAD

**Issue by ArthurHoaro** [shaarli/Shaarli#274]
Except you're in Africa.

Cities don't update without JS. Maybe we should add a noscript failover or something.

**Comment by virtualtam** [comment]
Maybe we could use server information to preselect a suitable timezone?
Despite not fixing the issue, this would make it less noticeable provided the right continent is preselected

**Comment by ArthurHoaro** [comment]
Sounds good.

**Comment by virtualtam** [comment]
Related info: [date_default_timezone_get](http://php.net/manual/en/function.date-default-timezone-get.php)

>  In order of preference, this function returns the default timezone by:
- Reading the timezone set using the date_default_timezone_set() function (if any)
- Prior to PHP 5.4.0 only: Reading the TZ environment variable (if non empty)
- Reading the value of the date.timezone ini option (if set)
- Prior to PHP 5.4.0 only: Querying the host operating system (if supported and allowed by the OS). This uses an algorithm that has to guess the timezone. This is by no means going to work correctly for every situation. A warning is shown when this stage is reached. Do not rely on it to be guessed correctly, and set date.timezone to the correct timezone instead.
- If none of the above succeed, date_default_timezone_get() will return a default timezone of UTC.

In application, it's working fine if the timezone is set in `php.ini`, which _should_ be the case on production servers (else, PHP will complain):

```bash
$ php --ini
Configuration File (php.ini) Path: /etc/php
Loaded Configuration File:         /etc/php/php.ini
Scan for additional .ini files in: /etc/php/conf.d
Additional .ini files parsed:      /etc/php/conf.d/xdebug.ini

$ grep timezone /etc/php/php.ini
; Defines the default timezone used by the date functions
; http://php.net/date.timezone
date.timezone = Europe/Paris

$ php -a
php > echo ini_get('date.timezone');
Europe/Paris
php > echo date_default_timezone_get();
Europe/Paris
```

Notes:
- there are 2 `php.ini` on Debian hosts: `/etc/php5/cli/php.ini` and `/etc/php5/apache2/php.ini`
- if the TZ is not set, then `date_default_timezone_get();` may guess it from system info and return the first TZ  in the same range, e.g. `Europe/Berlin`
- old configs may feature deprecated & exotic TZ values, see [Other timezones](http://php.net/manual/en/timezones.others.php)
