### ISSUE TITLE
Hashtag system

### ISSUE THREAD

**Issue by alexisju** [shaarli/Shaarli#278]
A hashtag system into Shaarli would be interesting in addition to links associated tags. 
The idea is that, in the description, any word ahead of # is linked to ?searchtags=[theword]

(Suggestion started here : https://github.com/shaarli/Shaarli/issues/44#issuecomment-120838806)

**Comment by ArthurHoaro** [comment]
Hashtags should create a tag automatically at link creation/edition.

**Comment by nodiscc** [comment]
> Hashtags should create a tag automatically at link creation/edition

I disagree. People may want to use hashtags in the description without messing up their tag list #pasdaccord (<- see what I just did?)

Automatically linking to `?searchtags=[theword]` is a good idea

**Comment by ArthurHoaro** [comment]
You're right.

I'm working on it. It's working pretty fine so far, except if I want to display code containing 'hashtags', such as CSS. I don't really see any good option here, except adding the link only if the tag exists...
