### ISSUE TITLE
Digest Auth?

### ISSUE THREAD

**Issue by mro** [shaarli/Shaarli#287]
Hi guys, what do you think about allowing (webserver) Digest Auth to avoid cleartext passwords over the wire?

Incentive is to avoid cleartext passwords over the wire with plain HTTP (no TLS).

**Comment by ArthurHoaro** [comment]
Yes, we should do that.

**Comment by mro** [comment]
well, the security won't become military grade, because of [digest auth](https://tools.ietf.org/html/rfc2617) relying on md5 (in theory: *An optional header allows the server to specify the algorithm used to create the checksum or digest.*) . 

But digest auth may be simple to integrate:

We may check for the presence of a `(REDIRECT_)*REMOTE_USER` header variable and use it in case (if it can't be forged). It may be a bit hairy that the php script has to tamper with both `.htaccess` and the password file.

I'm not sure myself if it's a good idea anyway. Key question may be: does it reduce overall complexity yes/no?

**Comment by mro** [comment]
I guess this won't happen as digest is quite a niche and tls seems to be the one answer to all privacy and security issues.

**Comment by mro** [comment]
https://github.com/shaarli/api-documentation/pull/13
