### ISSUE TITLE
Clean goal and developpement

### ISSUE THREAD

**Issue by ArthurHoaro** [shaarli/Shaarli#288]
> It is necessary there, not to index temporary/ backup files.

    $ make test
    Suppression de tests/PluginTest.php
    Suppression de tests/plugins/

Not cool.

Maybe we could add a specific goal for Travis with cleaning, and keep our files in dev environment?

**Comment by virtualtam** [comment]
Yup, the `clean` target is mostly useful before:
- generating documentation
- running static analysis tools

If you often find yourself losing unstaged changes, you can safely remove the dependency to `clean` from dev targets, and add it to Travis' config :)
