### ISSUE TITLE
Improve Wiki structure & navigation

### ISSUE THREAD

**Issue by virtualtam** [shaarli/Shaarli#291]
The wiki is currently quite dense, making finding and adding information a bit tough...

I'd like to restructurate pages & content, and add a custom [sidebar](https://help.github.com/articles/creating-a-sidebar/) to group pages by category; here is a proposition:

- Home
- Installation
 - Server requirements
 - Server configuration
 - Shaarli configuration
- Usage
 - Sharing button (bookmarklet)
 - Firefox share
 - Shaarli as a blog, notepad, pastebin
 - RSS feeds
- How To
 - Backup your links
 - Import and export links
 - Copy an existing installation over SSH, serve it locally
 - Download CSS styles from an OPML list
 - Report an issue
- Troubleshooting
- Development
 - Coding guidelines
 - Directory structure
 - 3rd party libraries
 - Plugin system
 - Static analysis
 - Theming
 - Unit tests
- About
 - FAQ
 - Other links
 - Related software
 - TODO

What do you think of it?

**Comment by nicolasdanelon** [comment]
+1
What do you need?

**Comment by virtualtam** [comment]
Maintainers to agree with the suggested changes, and contributors / users to be aware of them, before moving or making major edits to anything :)

Proof-check is much appreciated, too, in case I forgot anything, or there is a more elegant way to shape the documentation (e.g., look for broken links, check the makefile target to generate HTML documentation from Markdown pages, etc.)
