### ISSUE TITLE
Black thumbnails on picture wall after upgrade

### ISSUE THREAD

**Issue by ChuckMoh** [shaarli/Shaarli#293]
Hi !
After upgrade from the original seb sauvage's Shaarli, the picture wall is empty. I only have the titles when focus on. I have the correct thumbnails in Home page. To upgrade, I just follow your recommandations : suppression of all directories (except data) and extraction

My shaarli page : 
http://phileom.alwaysdata.net/shaarli/

**Comment by Knah-Tsaeb** [comment]
Your picture wall work fine.
http://img.knah-tsaeb.org/photos/shaarli/phils_picture_wall.png

I use Firefox 39 under Linux.

**Comment by ChuckMoh** [comment]
I am with chromium 43 and I can confirm I don' have the problem with opera

**Comment by nodiscc** [comment]
@ChuckMoh are there any errors in your browser console or in your webserver logs?

**Comment by Knah-Tsaeb** [comment]
I can confirm, this bug is only with Chromium.

**Comment by ChuckMoh** [comment]
[error] [client _ip number_] File does not exist: /home/phileom/www/shaarli/do=picwall

**Comment by Knah-Tsaeb** [comment]
Same with Shaarli demo (http://shaarlidemo.tuxfamily.org/Shaarli/?do=picwall). Maybe a problem with Blazy-js. I am no problem with jQuery and Lazy load under Chromium.

**Comment by ChuckMoh** [comment]
Ok thanks for the reply

**Comment by virtualtam** [comment]
Hello @ChuckMoh and @Knah-Tsaeb !

Could you check that your `cache` directory is writeable by Shaarli?

I've tested on `master` in the following conditions:
- `cache` is writeable
 - thumbnails are correctly created and used
 - works fine on Linux with Firefox 39.0 and Chromium 43.0
- `cache` is not writeable / does not exist
 - no (local) thumbnails
 - Firefox lazy-loads the thumbnails from the websites (Youtube, etc.)
 - Chromium does not load anything

**Comment by ChuckMoh** [comment]
Weird, my cache is writeable and I can' t see my picwall (only with chromium of course)

**Comment by Knah-Tsaeb** [comment]
Look the source in Chromium
```html
<img class="b-lazy" src="#" data-src="https://img.youtube.com/vi/4vWJ3lmnVl8/default.jpg" width="120" height="90" alt="YouTube thumbnail">
```
I think javascript not load.

@ChuckMoh  Can you edit ```tpl/picwall.html``` and replace : 
```javascript
var bLazy = new Blazy();
```
by
```javascript
window.onload = function() {
  var bLazy = new Blazy();
}
```
And report the result.

**Comment by ChuckMoh** [comment]
Problem solved Thanks !

**Comment by Knah-Tsaeb** [comment]
@ChuckMoh have a nice day.

**Comment by ChuckMoh** [comment]
You too!

**Comment by ArthurHoaro** [comment]
Good catch @Knah-Tsaeb. Could you provide a PR to fix this?

I'm switching milestone 1.0 to 0.9 since it's an important bug (broken feature).

**Comment by Knah-Tsaeb** [comment]
I can try.
