### ISSUE TITLE
README: php-mbstring is required

### ISSUE THREAD

**Issue by ArthurHoaro** [shaarli/Shaarli#297]
Used in LinkDb.

**Comment by virtualtam** [comment]
Spotted in the [Troubleshooting](https://github.com/shaarli/Shaarli/wiki/Troubleshooting) > CentOS section ;-)

It seems to be a RHEL/CentOS-specific requirement; from http://php.net/manual/en/mbstring.installation.php :

> mbstring is a non-default extension. This means it is not enabled by default.
> You must explicitly enable the module with the configure option. See the Install section for details.

**Comment by ArthurHoaro** [comment]
Oh. Good to know. I actually spotted this in a random Windows PHP install. Also, RHEL/CentOS + Fedora.

**Comment by virtualtam** [comment]
Added to [Server requirements](https://github.com/shaarli/Shaarli/wiki/Server-requirements) :)

**Comment by ArthurHoaro** [comment]
Perfect! :)
