### ISSUE TITLE
Use ATOM feed as default

### ISSUE THREAD

**Issue by qwertygc** [shaarli/Shaarli#304]
Hello!
Why RSS is the default syndication that is prupose whereas Atom is a standard?

**Comment by ArthurHoaro** [comment]
We have both: `?do=atom` and `?do=rss`. As I said in another issue, I believe it's useless and RSS should be removed (and redirect `do=rss` to Atom).

Why is RSS the default format... probably legacy.

**Comment by nicolasdanelon** [comment]
Remove RSS support? WTF seriously ? RSS2 is the modernized version of the legacy format, don't kill him!

**Comment by ArthurHoaro** [comment]
Well, I don't have a strong opinion on this. I just don't really see the point of providing both, and I've read the Atom specification is a bit better. That might be wrong.

If you guys think that we should keep both for some reason, no problem!

**Comment by nicolasdanelon** [comment]
what about this: create two plugins. one for RSS and other for ATOM. So the final user can chose which one will use :P
