### ISSUE TITLE
Firefox social broken

### ISSUE THREAD

**Issue by alexisju** [shaarli/Shaarli#310]
- `✚Add to Firefox social` from tool's page doesn't add service to Firefox anymore.
- tags autocompletion from configured services into Firefox doesn't work anymore.

**Comment by qwertygc** [comment]
:+1:  for Firefox Social

**Comment by Marsup** [comment]
Both works on my server and I'm on latest master.

**Comment by qwertygc** [comment]
I thought : you url scheme is : example.org/links or links.example.org ?

**Comment by alexisju** [comment]
- I got the same issue on different domains or subdomains (like domain.com/shaarli or shaarli.domain.com)
- I cant' add `✚Add to Firefox social` neither from  http://shaarlidemo.tuxfamily.org/Shaarli/

**Comment by jeekajoo** [comment]
just FYI
it works for me: https://fralef.me/links/
it doesn't work for @kalvn: http://exystenz.com/links/ (ref: https://github.com/kalvn/Shaarli-Material/issues/12)

**Comment by qwertygc** [comment]
Et que dit ton about:support ?

**Comment by jeekajoo** [comment]
I don't think this is related to the browser, as clicking on `✚Add to Firefox social` in http://shaarlidemo.tuxfamily.org/Shaarli/ doesn't work for me either.

**Comment by Marsup** [comment]
https://developer.mozilla.org/en-US/docs/Mozilla/Projects/Social_API/Manifest => All URLs in the manifest should be HTTPS URLs

That's why. Maybe the button should be grayed (explaining why) when it's not on an HTTPS server.

**Comment by alexisju** [comment]
The explanation of @Marsup make sense for me.

With https all works fine also  with shaarlidemo (from https://shaarlidemo.tuxfamily.org/Shaarli/ ).

Sorry for the inconvenience, thanks for your answers.

**Comment by nodiscc** [comment]
Maybe this should be added to the doc
