### ISSUE TITLE
Stop returning to the first page after editing a bookmark from another page

### ISSUE THREAD

**Issue by fturco** [shaarli/Shaarli#311]
If I go to a page other that the first one and then I edit a bookmark, Shaarli will bring me back to the first page upon clicking on Save. This is quite annoying. Shaarli should remain on the same page of the modified bookmark.

**Comment by virtualtam** [comment]
This is the behavior I have on the latest version:

URL | action
---|---
http://shaar.li/ | start from the main page (link list)
http://shaar.li/?page=4 | go further some pages, say to the fourth one
http://shaar.li/?edit_link=20150531_185648 | edit a link on the fourth page
- | save the link
http://shaar.li/?page=4#DulVxA | back to the fourth page, with an anchor to the edited link

When editing a link from the main page, there is a hidden form value:
```html
<input type="hidden" name="returnurl" value="https://shaar.li/?page=4">
```

Is there a corner case where this fails?

**Comment by fturco** [comment]
This is what happens to me:

URL | Action
----------------
http://127.0.0.1/shaarli/?page=4 | go to page four
http://127.0.0.1/shaarli/?edit_link=20150307_163635&x=7&y=5 | Edit the first link on page 4
http://127.0.0.1/shaarli/? | back to the first page, not the fourth

This is my input tag when editing the link on page four:

    <input type="hidden" name="returnurl" value="http://127.0.0.1/shaarli/?edit_link=20150307_163635&amp;x=7&amp;y=5">

**Comment by ArthurHoaro** [comment]
Related to #256.

You're obfuscating your HTTP referer, which prevent Shaarli to redirect you properly.

If you're concerned about privacy, and wan't Shaarli to work properly, I can suggest you this configuration:

  * `network.http.referer.spoofSource`: false - send the referrer.
  * `network.http.referer.XOriginPolicy`: 1 - only send if base domains match.

[More info](http://www.ghacks.net/2015/01/22/improve-online-privacy-by-controlling-referrer-information/).

**Comment by virtualtam** [comment]
[Browser](https://github.com/shaarli/Shaarli/wiki/Troubleshooting#browser) section added to the Troubleshooting page.

The following links may prove useful:
- [HTTP referer](https://en.wikipedia.org/wiki/HTTP_referer) (Wikipedia)
- [Improve online privacy by controlling referrer information](http://www.ghacks.net/2015/01/22/improve-online-privacy-by-controlling-referrer-information/)
- [Better security, privacy and anonymity in Firefox](http://b.agilob.net/better-security-privacy-and-anonymity-in-firefox/)

**Comment by fturco** [comment]
My original settings were:

- network.http.referer.spoofSource: true
- network.http.referer.XOriginPolicy: 0

So I set them to "false" and "1", respectively, as suggested. But Shaarli still exhibits the same behaviour. I also tried installing the Smart Referer plugin, to no avail.

**Comment by fturco** [comment]
Tried editing about:config with a fresh new Iceweasel profile but I experience the same problem.

**Comment by ArthurHoaro** [comment]
I just tried on the [demo instance](http://shaarlidemo.tuxfamily.org/Shaarli/) (demo - demo), and the only way I can reproduce your issue is setting `spoofSource` to `true`. :(

I suppose with a fresh profile you have no extension?

Can you reproduce those steps:

  * Open Firefox dev tools and go to the network tab.
  * While logged in go to tag search : http://shaarlidemo.tuxfamily.org/Shaarli/?searchtags=sandwich
  * Click on the edit button.
  * Watch request headers, especially `Referer`.

![referershaarli](https://cloud.githubusercontent.com/assets/1962678/9135475/07323ae6-3d0e-11e5-8c5d-e352790fe239.png)

  * The saving button should redirect you to your tagsearch, but that's the issue.

**Comment by ArthurHoaro** [comment]
Oh! I think I just found the issue. Are you testing on localhost? 

`XOriginPolicy` set to 1 doesn't seem to work because it's not a valid base domain. It's working on localhost.localdomain though (or whatever is in your hosts file).

**Comment by fturco** [comment]
I'm testing on http://127.0.0.1/shaarli/.

My `/etc/hosts` file is:

```
127.0.0.1 localhost desktop
::1       localhost desktop
```

**Comment by ArthurHoaro** [comment]
Can you test on the demo instance?

You can also edit your hosts file this way:

```
127.0.0.1 localhost desktop localhost.lan
::1       localhost desktop localhost.lan
```

And test on http://localhost.lan.

**Comment by fturco** [comment]
I modified `/etc/hosts` and about:config as you described and tested http://localhost.lan/shaarli/: it works now! It stays on the same page. But I have no idea why the former works while http://127.0.0.1/shaarli doesn't. I'm also going to test the demo instance now.

**Comment by ArthurHoaro** [comment]
Good to know! `XOriginPolicy` is supposed to send the referer only between pages of the same domain. I guess an IP is not really a domain, and localhost isn't valid either (`hostname.tld` required).

**Comment by fturco** [comment]
I tried the demo instance, but I'm not sure I tested it correctly (no experience with debugging web applications).

URL | Method | Referer
---|------|-------
http://shaarlidemo.tuxfamily.org/Shaarli/?edit_link=20150809_135302&x=9&y=4 | 302 POST | http://shaarlidemo.tuxfamily.org/Shaarli/?edit_link=20150809_135302&x=9&y=4 |
http://shaarlidemo.tuxfamily.org/Shaarli/?searchtags=sandwich#qpvdtw | 200 GET | http://shaarlidemo.tuxfamily.org/Shaarli/?edit_link=20150809_135302&x=9&y=4

I also had no problem at going back to previous pages on the demo instance and editing a bookmark: it remains on the same page after saving, as with my local instance of Shaarli.

**Comment by virtualtam** [comment]
Here's an interesting thread on the Arch ML: [what is localhost.localdomain for?](https://bbs.archlinux.org/viewtopic.php?id=156064), which in turn references configuration-related discussions on the Debian ML:
- https://lists.debian.org/debian-devel/2005/10/msg00559.html
- https://lists.debian.org/debian-devel/2009/12/msg00778.html
- https://lists.debian.org/debian-devel/2005/10/msg00572.html

The [manpage](http://linux.die.net/man/5/hosts) for `/etc/hosts` is quite vague about this, though.

Looking at some database/service-related threads on StackOverflow/StackExchange, it seems that:
- `localhost` is considered as a host name, and does not form a valid FQDN
- `localhost.localdomain` forms a valid FQDN
- whether `localhost` is properly resolved is implementation/application-dependent

**Comment by virtualtam** [comment]
- [ ] TODO: improve the troubleshooting documentation for browser specificities

**Comment by virtualtam** [comment]
On Troubleshooting:
- [Firefox HTTP Referer options](https://github.com/shaarli/Shaarli/wiki/Troubleshooting#firefox-http-referer-options)
- [Firefox, localhost and redirections](https://github.com/shaarli/Shaarli/wiki/Troubleshooting#firefox-localhost-and-redirections)
