### ISSUE TITLE
Feature request: hidden tags

### ISSUE THREAD

**Issue by seigler** [shaarli/Shaarli#315]
pinboard.in has a feature where tags beginning with a period are only searchable or shown when the user is logged in. This way you can, for instance, tag something with .friendsname to privately catalog resources for them.

**Comment by ArthurHoaro** [comment]
I think that's a very good idea.

**Comment by nodiscc** [comment]
Whether it is tags stating with a dot/period, or a user-definable hidden tags list, I think this is a good idea.

**Comment by virtualtam** [comment]
+1

a leading dot feels more natural (cf. Unix hidden files)

**Comment by mro** [comment]
+1 `.`
