### ISSUE TITLE
Import / Export database - documentation of Shaarli-Fileformat wanted

### ISSUE THREAD

**Issue by klartext** [shaarli/Shaarli#316]
Hello,
I want to import Links from Shaarli into my SQL-database, and maybe also do it the other way around.
In what format are Shaarli-Files saved?
How can I read / import them (from any other language... I may not have the same libraries available,
so would need to know what's going on there).
Is it compressed stuff? I have a small example-file, and it looks weird for human eyes.

**Comment by klartext** [comment]
Hello, in LinkDB.php I found function savedb().
It uses
---
self::$phpPrefix.base64_encode(gzdeflate(serialize($this->_links))).self::$phpSuffix
---
and function _readDB() uses
---
if (file_exists($this->_datastore)) {
            $this->_links = unserialize(gzinflate(base64_decode(
                substr(file_get_contents($this->_datastore),
                       strlen(self::$phpPrefix), -strlen(self::$phpSuffix)))));
---
so, gzip and base64 are involved, which is part of the answer.
What about serialize()?
Seems to be PHP-specific and not easy to make compatible with non-PHP access?

I found articles/discussions about serialize, that it's problematic in respct to compatibility, and also is much slower tha serialization with json-output. So it might make sense to switch to json-based serialization? It also would make compatibility issues easy to solve...

**Comment by ArthurHoaro** [comment]
Shaarli doesn't support databases by design. It saves its data into files (base64 + gzip as you saw) which is fine for its usage.

If you really need to use a DB, I believe you'll need to create an export/import script with the functions you've seen:

    unserialize(gzinflate(base64_decode(

You can also see [Export links as...](https://github.com/shaarli/Shaarli/wiki/Backup%2C-restore%2C-import-and-export#export-links-as) in the documentation.

About `serialize()`, it is PHP specific, and it takes slightly longer (few ms) than `json_enconde()`, after my own performance tests. Maybe it's something we can discuss.

**Comment by virtualtam** [comment]
Hi @klartext !

There's a bit of documentation on the [Datastore hacks](https://github.com/shaarli/Shaarli/wiki/Datastore-hacks) page (which was missing from the wiki's side-menu -fixed)

If you want to access/modify Shaarli's link DB from an external program, the best way would be to use a small PHP script, as data serialization is (for now) quite tied to PHP's internals.

An other option you may want to consider is using the HTML import-export feature (which may or not be convenient).

Switching to JSON would be feasible in the long-term, as well as providing a RESTful API but it's _low-low priority_ for now ;-)

**Comment by mro** [comment]
do you know that `?do=atom&nb=all` exports **ALL** content in [Atom](http://atomenabled.org/) format?

So it's IMO all there already when it comes to exporting.

**Comment by virtualtam** [comment]
Which format to use greatly depends on the intended usage.

For example, to export an array of links from PHP to a Python or Java external tool, I'd find it much easier to process JSON or YAML data, as it is both lightweight and very easy to parse (provided the language supports it).

In this case, writing and parsing XML, especially formatted as a syndication feed, is not an optimal solution.

On the other hand, you may want to use HTTP to query information from a remote Shaarli instance, in which case a standard format such as Atom is perfectly suitable (unless you want/need _dat RESTful hype touch_).

**Comment by klartext** [comment]
For newsbeuter I have written an import-functionality, so I can read newsbeuter's database (it's sqlite).
I thought there would be a similar possibility for Shaarli.
I personally don't use Shaarli, but was hinted to maybe write an importer-function, so that the link-database makes more sense / is more general.
Thats, what it is about.

Importing RSS or Atom or JSON could also be possible.
Direct database-read is not possible because of PHP-specific serialize-function,
even though it might be a nice solution, because no export-step is needed.
If first export to Atom-or-something-else and then importing this exported stuff to my database would be necessary, thats two steps, instead of one.
(But the advantage is, that it is less depending on the structure of the database.)
If easy-usage is an item, read-access to the database would be nice.
Just pass around the Shaarli-files and import those, that are of interest....

**Comment by mro** [comment]
@virtualtam question is if shaarli should increase it's complexity for something that's neither it's goal (*The personal, minimalist, super-fast, no-database delicious clone*) nor necessary because it can already be achieved. Convenience of 3rd party data imports doesn't justify any increase of complexity IMHO. Everybody is free to add a Atom2Foo converter - independant of shaarli. Shaarli may advertise it, it shuldn't maintain it.

**Comment by nodiscc** [comment]
Links to a third party conversion tool could be added to the documentation if such a thing exists. We already have 4 data export methods available (deserialize datastore.php, export as HTML, RSS or ATOM). As mro said, writing a third-party converter from any of these formats to a sqlite database would be trivial. I suggest closing this issue if it answers your question @klartext

**Comment by klartext** [comment]
OK. Question solved.
Thanks.
