### ISSUE TITLE
Suggestion: better tag renaming

### ISSUE THREAD

**Issue by urza** [shaarli/Shaarli#317]
Hi, I was very happy to discover that Shaarli is maintained by this amazing community. I was running the original for few years and didnt know about this one. Thanks everybody.

I have a feature suggestion: make it easier to rename misspelled tags. Over the years I accumulated quite a lot of misspelled tags, or "synonym" tags - tags having the same meaning as other tags, but using different word, because I forgot I was using that tag already.

What I would welcome to fix my tags:
1. See list of tags ordered by number of items with this tag, so I can see tags with 1 or small number of items first..  this would help me to discover misspelled tags or the most suspicions tags quickly.
2. See tags that are similar to other tags.. I have good experience with this string distance algorithm: http://siderite.blogspot.com/2014/11/super-fast-and-accurate-string-distance.html
   it could suggest which tags are most similar and I could decide whether it is intentional, or whether to merge them
3. When renaming tag, the first textbox (to locate tag to rename) has auto-completion, the second textbox (with new name) doesn't have auto-completion... if I am renaming tag to something completely new, it is OK, but when I am fixing tag, it would help to have auto-completion even in the second textbox.

This is nothing that one couldnt live without, but if it does inspire someone, to implement any of this, it would be great. Thanks.

**Comment by ArthurHoaro** [comment]
Thanks for your feedback.

IMHO:

  1. It can only be another display of tagcloud: +1.
  2. Interesting. I didn't go through your whole blog post, but that looks a bit complex... I need to think a bit more about it.
  3. I understand the use case, it's easy, I say let's do this.

**Comment by virtualtam** [comment]
Thanks @urza for your feedback!

Additionally, we could check tag spelling, either in JS when typing, or as an admin tool through aspell/hunspell bindings

**Comment by nodiscc** [comment]
different sorting modes for the tag cloud/list would be nice (cloud, alphabetical order, order by frequency of tags)

**Comment by virtualtam** [comment]
filtering / not showing all tags could help readability as well (with nearly 2500 tags, my cloud looks a bit overcrowded)

**Comment by mro** [comment]
when it comes to tags I'd like to throw in http://www.w3.org/2004/02/skos/ for relations between tags.

**Comment by ArthurHoaro** [comment]
This issue is quite old and hasn't been active since 2015, so I will close this issue. 

We now support tag list by usage and alphabetical order, with renaming/deletion. Also in rename/delete tag page, the second input now support auto-completion.

Regarding spelling, I think this should be handled by the browser, and definitely not by Shaarli. Especially because it would mean to embed dictionaries depending on the locale.

Similar tags also seems a bit complicated for its use case in Shaarli. But if you think it could be a good feature for Shaarli, please open a new issue.
