### ISSUE TITLE
Blank page after clicking the “key” icon

### ISSUE THREAD

**Issue by pierreporte** [shaarli/Shaarli#320]
After updating to the version 0.5, I clicked on the icon ![/images/private_16x16.png](https://raw.githubusercontent.com/shaarli/Shaarli/master/images/private_16x16.png) to see what it does. Right after, I got a blank page with an empty source code. After re-uploading the files (except the data folder), the issue persists. I can’t access to anything except static files.

The content and permissions of the files doesn’t seem to have changed.

You can check [my shaarli](http://thomasd.eu/shaarli).

**Comment by ArthurHoaro** [comment]
Looks like a PHP error. Can you check your error log?

**Comment by pierreporte** [comment]
Where can I find it ?

In the meantime, I made a backup of the data folder and uploaded the blank one from the zip archive provided here and I am redirected to the installation wizard. After completing it and re-uploading the HTML backup, I got everything working.

**Comment by pierreporte** [comment]
I found the error log:

    [Thu Aug 13 14:01:21 2015] [error] [client 213.251.182.115] [host thomasd.eu] client denied by server configuration: /homez.239/thomasdeyi/www/shaarli/data/
    [Thu Aug 13 14:01:22 2015] [error] [client 46.105.120.211] [host thomasd.eu] client denied by server configuration: /homez.239/thomasdeyi/www/shaarli/data/
    [Thu Aug 13 14:21:40 2015] [error] [client 109.220.26.237] [host thomasd.eu] client denied by server configuration: /homez.239/thomasdeyi/www/shaarli/application
    [Thu Aug 13 14:21:47 2015] [error] [client 109.220.26.237] [host thomasd.eu] client denied by server configuration: /homez.239/thomasdeyi/www/shaarli/tmp
    [Thu Aug 13 14:21:50 2015] [error] [client 109.220.26.237] [host thomasd.eu] client denied by server configuration: /homez.239/thomasdeyi/www/shaarli/tests
    [Thu Aug 13 14:21:55 2015] [error] [client 109.220.26.237] [host thomasd.eu] client denied by server configuration: /homez.239/thomasdeyi/www/shaarli/data

**Comment by ArthurHoaro** [comment]
It looks like you didn't had permissions on your files/folder for a while. Maybe a bug from your host?

Everything seems fine now. Should we close this?

**Comment by ArthurHoaro** [comment]
I'm closing this. Please reopen if you're still facing your issue.
