### ISSUE TITLE
Automatic description in the bookmark

### ISSUE THREAD

**Issue by NerosTie** [shaarli/Shaarli#322]
Is it possible to add in the bookmark something wich can read the meta "description" of a link and add it automatically in the shaarlink?  
And same question for tags.

Thanks!

**Comment by virtualtam** [comment]
Looking at the corresponding [code section](https://github.com/shaarli/Shaarli/blob/master/index.php#L1493):
- title and description should be set when sharing a link via the bookmarklet
- title is extracted from the page's `<head>` _if the scheme is HTTP_

It'd be quite easy to extend [`html_extract_title`](https://github.com/shaarli/Shaarli/blob/master/index.php#L570)'s inline parsing to other HTML elements, yet this won't work for multi-line HTML elements (unless parsing the `<head>` with SAX/DOM).

Functionally, I'm not sure it would be worth doing:
- I tend to add stuff to the title, and either leave links with no description, or write more personal comments and clues, or link to related resources
- web pages that have keywords usually have a lot of them, not always worth adding, and their formatting may vary

Here's an example of what I would consider as not being very informative to add:
```html
<head>
    <title>reddit: the front page of the internet</title>
    <meta name="keywords" content=" reddit, reddit.com, vote, comment, submit " />
    <meta name="description" content="reddit: the front page of the internet" />
    <meta name="referrer" content="always">
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    [...]
</head>
```

**Comment by nodiscc** [comment]
I am pretty certain this feature would annoy me, as explained above (metatags are mainly used for SEO and often not very informative).

However @NerosTie extracting the page description using a bookmarklet doesn't seem too hard: https://stackoverflow.com/questions/1268180/javascript-quickest-way-to-extract-document-meta-fields

    var desc = document.getElementsByName('description')[0].getAttribute('content');

Feel free to share your extended bookmarklet if you think it's useful.

**Comment by NerosTie** [comment]
Thanks to @nodiscc, this is the code for my bookmark:

```
javascript:javascript:  
(function() {
    var url = location.href;
    var title = document.title ||url;
    var desc = document.getElementsByName('description')[0].getAttribute('content');
    var selected_text = window.getSelection() || document.getSelection() || document.selection.createRange().text;

    window.open('http://domain.tld/shaarli/?post=' + encodeURIComponent(url)+'&title=' + 
                                                     encodeURIComponent(title)+'&description=' + (selected_text != "" ? '%3E ' : '> ' + encodeURIComponent(desc)) + 
                                                     encodeURIComponent(selected_text) + 
                                                     '&source=bookmarklet','_blank','menubar=no,height=650,width=600,toolbar=no,scrollbars=no,status=no,dialog=1');
})();
```

It works well! If nothing is selected, it takes the meta description and if you select text, it will take what you have selected (plus it adds a `>` in both cases).

I didn't test with tags but I guess it's similar.

**Comment by virtualtam** [comment]
Neat!

Don't hesitate to drop a line in the Wiki on how to write custom bookmarklets, this could prove useful to other users ;-)

**Comment by NerosTie** [comment]
Hm, it doesn't work if there is no meta description... (nothing happen when you click on the bookmark)

**Comment by mro** [comment]
I would guess the more hip [`og:description`](http://ogp.me/) is maintained better because it's the facebook-marketing-evangelists that advocate it. It's the text pre-filled when sharing a page with fb, isn't it?

So maybe prefer it if present over the old-school `description` tag.

**Comment by Eragos** [comment]
Thanks to @NerosTie for the bookmarklet code. 

> Hm, it doesn't work if there is no meta description... (nothing happen when you click on the bookmark).

I have a small fix to prevent an javascript exception, when 'description' does not exists in DOM:

    var url = location.href;
    var title = document.title ||url;
    try {
       var desc = document.getElementsByName('description')[0].getAttribute('content');
    } catch(err) {
        var desc ='';
    }
    var selected_text = window.getSelection() || document.getSelection() || document.selection.createRange().text;

    window.open('http://domain.tld/shaarli/?post=' + encodeURIComponent(url)+'&title=' + 
                                                     encodeURIComponent(title)+'&description=' + (selected_text != "" ? '%3E ' : '> ' + encodeURIComponent(desc)) +
                                                     encodeURIComponent(selected_text) + 
                                                     '&source=bookmarklet','_blank','menubar=no,height=610,width=500,toolbar=no,scrollbars=no,status=no,dialog=1');

**Comment by nodiscc** [comment]
If someone has a one-liner bookmarklet for the tool above (thanks @Eragos) it could be added to the wiki.

**Comment by Eragos** [comment]
> If someone has a one-liner bookmarklet for the tool above (thanks @Eragos) it could be added to the wiki.

A on-liner ist not so easy because of the {$pageabsaddr}. Here is my code from tpl/tools.html

     <a class="smallbutton" onclick="alert('Drag this link to your bookmarks toolbar, or right-click it and choose Bookmark This Link...');return false;" href="javascript:(function()%7Bvar%20url%20%3D%20location.href%3Bvar%20title%20%3D%20document.title%20%7C%7Curl%3Bvar%20desc%3Btry%20%7Bdesc%20%3D%20document.getElementsByName('description')%5B0%5D.getAttribute('content')%3B%7D%20catch(err)%20%7B%7Dvar%20paras%20%3D%20document.getElementsByTagName('meta')%3Bfor%20(i%20%3D%200%3B%20i%20%3C%20paras.length%3B%20i%2B%2B)%20%7Bvar%20test%20%3D%20paras%5Bi%5D.getAttribute('property')%3Bif(test%20%3D%3D%20%22og%3Adescription%22)%20%7Bdesc%20%3D%20paras%5Bi%5D.getAttribute('content')%3B%3B%7D%7Dvar%20selected_text%20%3D%20window.getSelection()%20%7C%7C%20document.getSelection()%20%7C%7C%20document.selection.createRange().text%3Bwindow.open('{$pageabsaddr}%2F%3Fpost%3D'%20%2B%20encodeURIComponent(url)%2B'%26title%3D'%20%2BencodeURIComponent(title)%2B'%26description%3D'%20%2B%20(selected_text%20!%3D%20%22%22%20%3F%20'%253E%20'%20%3A%20encodeURIComponent(desc))%20%2BencodeURIComponent(selected_text)%20%2B'%26source%3Dbookmarklet'%2C'_blank'%2C'menubar%3Dno%2Cheight%3D610%2Cwidth%3D500%2Ctoolbar%3Dno%2Cscrollbars%3Dno%2Cstatus%3Dno%2Cdialog%3D1')%7D)()"><b>✚Shaare link (with description)</b></a> <a href="#" style="clear:none;"><span>&#x21D0; Drag this link to your bookmarks toolbar (or right-click it and choose Bookmark This Link....).<br>&nbsp;&nbsp;&nbsp;&nbsp;Then click "✚Shaare link" button in any page you want to share.</span></a><br><br>

You can quick'n easy create your own bookmarklet with copy & past to http://mrcoles.com/bookmarklet/. You not need to check the two checkboxes. But you have to change the URL for your own installation.

**Comment by ArthurHoaro** [comment]
Closing. It won't be added in Shaarli core, but could be done with bookmarklets.
