### ISSUE TITLE
Invitation: iOS share extension

### ISSUE THREAD

**Issue by mro** [shaarli/Shaarli#323]
Hi all,
a few days ago, I published [https://github.com/mro/ShaarliOS](https://github.com/mro/ShaarliOS#the-missing-ios-8-share-extension-to-shaarli) on the Apple App Store.

Here are a few codes to get free copies from Apple, please write in a comment which one you used.

    XP73J6J7W4PP
    A6TNRTAKR4AP
    F6NTRJLLT64N
    396FFEFK4J7F
    WNEJTK9TYK7F
    4RK3F4KH7LWH
    XHJJ7AXWA49H
    K7WTHFTLF3F3
    ERXFTYWT93FK
    L349HLFNJT6H

They do expire in 4 weeks.

P.S.: I hope posting the codes here is compliant to the contribution guidelines.

**Comment by nodiscc** [comment]
@mro you could also edit https://github.com/shaarli/Shaarli/wiki/Community-%26-Related-software, rename `Android Apps` to `Mobile Apps` and add ShaarliOS there. You can also do announces like this in the general discussion thread: https://github.com/shaarli/Shaarli/issues/308

Closing to keep issues tracker in good order.

**Comment by mro** [comment]
Follow up at https://github.com/shaarli/Shaarli/issues/308#issuecomment-132303709

@nodiscc thanks you, feel free to pass the codes on if you know iOS shaarliers.
