### ISSUE TITLE
Use Shaarli like a url shortener?!

### ISSUE THREAD

**Issue by Eragos** [shaarli/Shaarli#329]
It would be nice to use Shaarli like a url shortener (like tinyurl, bitly, ...)

Actually all my shaarli bookmarks are private. But sometime I want to share it to the social world.

If you know the short url http://l.domain.tld/?iePvsw Shaarli should redirect to the original URL and optionally count the requests.

What do you think about that?

**Comment by nodiscc** [comment]
- There are already a few FOSS self-hostable URL shorteners https://github.com/Kickball/awesome-selfhosted#url-shorteners (if you need stats I recommend YOURLS)
 - Private links are private. Letting unauthenticated users access private shortlinks allows an attacker to enumerate private links.

> If you know the short url http://l.domain.tld/?iePvsw Shaarli should redirect to the original URL and optionally count the requests.

I thought we had an option for that. Do we? Or maybe it has been reported elsewhere. Anyway having the possibility to automatically redirect shortlinks to the original URL would be nice.

**Comment by Eragos** [comment]
Done & thanks for your quick reply!

**Comment by ArthurHoaro** [comment]
> I thought we had an option for that. Do we?

This option is used for RSS / Atom feeds (direct link or shaare link).

That's not a bad idea, and it could be done with a plugin.
