### ISSUE TITLE
Refactor HTTP / Url functions

### ISSUE THREAD

**Issue by virtualtam** [shaarli/Shaarli#333]
Relates to #332

### Todolist
- move to `application/HttpUtils.php` (#334, #346):
    - [x] ~~`http_parse_headers_shaarli()`~~ => use [`get_headers()`](http://php.net/manual/en/function.get-headers.php)
    - [x] `getHTTP ()` => `get_http_url()`
    - [x] `serverUrl()`
    - [x] `indexUrl()`
    - [x] `pageUrl()`
- add test coverage
- apply coding conventions

[EDIT 2015-11-09] Moved to _#372 -Introduce a Shaarli class_:
> - move to ?
>     - [ ] `checkUpdate()` => `shaarli_check_update()`
>     - possibly `application/ShaarliUtils.php`:
>     - other option: introduce a `Shaarli` class to hold config / version management

**Comment by nicolasdanelon** [comment]
Awesome work!
