### ISSUE TITLE
Make update check optional

### ISSUE THREAD

**Issue by nodiscc** [shaarli/Shaarli#34]
https://github.com/shaarli/Shaarli/issues/5#issuecomment-50355925:

> About the update check, imho it should follow such guidelines:
>    The user is fully aware of it existence.
>    The user must enable it himself
>    The user must be aware of the privacy concern (privacy vs. function)

>Totally agree. Maybe a checkbox at setup and in the configure dialog:
>  [ ]  Automatically check for updates. This will periodically check the author's code repository for new versions. Your current version is $shaarli_version. You can also stay informed of latest updates by subscribing to the releases feed

We can already add a  `ENABLE_UPDATECHECK` config option and [`checkUpdate()`](https://github.com/shaarli/Shaarli/blob/master/index.php#L128) should only run if set to 1. What should be the default value?

Is this ok?

**Comment by e2jk** [comment]
Fixed in #120.
