### ISSUE TITLE
Suggestion : support yubikey (OTP)

### ISSUE THREAD

**Issue by OniriCorpe** [shaarli/Shaarli#341]
Bonjour,
J'ai pensé qu'ajouter un troisième facteur d'authentification en option serait sympathique.
Je possède une clef yubikey, la documentation est assez précise et simple.

Mais elles sont assez onéreuses, donc au final peu de personnes en possèdent, c'est pourquoi il serait intéressant de discuter des autres moyens de sécurisation à base d'OTP (one time password) qu'il serait bien d'inclure.

En plus de cela, peut être ajouter un support LDAP facilité ?

Aussi, pouvoir choisir juste en modifiant les paramètres : 
- le serveur à interroger (pour le cas yubikey, du moins), pour ceux qui ont leur propre serveur de vérification)
- le choix entre login + password + OTP ou juste OTP

(Je rédige en français car je n'ai pas la motivation de faire aussi une version anglaise pour l'instant, mais si ça dérange je le ferai un peu plus tard ;) )

**Comment by mro** [comment]
Wie bitte?

**Comment by virtualtam** [comment]
@mro :D

@OniriCorpe, ![do not unleash the Troll!](https://img.shields.io/badge/i'm%20feeling-trollish-red.svg)

... but I'll point you to these excerpts of [How to ask questions the smart way?](http://catb.org/~esr/faqs/smart-questions.html) instead:

> [...] expressing your question clearly and well is important. If you can't be bothered to do that, we can't be bothered to pay attention.
>
> [...] unless you know what your respondent's languages are, write in English. Busy hackers tend to simply flush questions in languages they don't understand, and English is the working language of the Internet. By writing in English you minimize your chances that your question will be discarded unread.
