### ISSUE TITLE
login/session issue with php 7

### ISSUE THREAD

**Issue by mro** [shaarli/Shaarli#349]
when running integration tests, I hit https://travis-ci.org/mro/Shaarli-API-test/jobs/79110616#L179.

Watch out for `exit 8` in [`test-post.sh`](https://github.com/mro/Shaarli-API-test/blob/314fb2faceec66b39c182078df20ee90ec380b31/scripts/test-post.sh#L69) for the precise location.

I would fully understand if you close this issue as a `won fix`, as php 7 isn't shipped yet. I just wanted to bring it to your attention in case you care.

**Comment by virtualtam** [comment]
PHP 7 is not to be expected before November / December - the Beta / RC announcements are tracked in the [Server requirements](https://github.com/shaarli/Shaarli/wiki/Server-requirements) page

It'd be a good idea to keep this open, yet not flag it as a bug for now, until proper integration tests are run with PHP7 + Apache/Nginx.

**Comment by mro** [comment]
looks good nowadays.
