### ISSUE TITLE
Risk of bookmarking duplicates

### ISSUE THREAD

**Issue by kalvn** [shaarli/Shaarli#350]
I noticed that since the 0.5.X version, when I want to bookmark a URL I already bookmarked before, instead of the EDIT popup, I see the ADD popup as if I never bookmarked this URL. This is problematic because it could lead to duplicate entries.

**Comment by virtualtam** [comment]
Hello @kalvn!

Which Shaarli version are you using?

This issue was reported in #325 & fixed in #326, which have been included in Shaarli [v0.5.2](https://github.com/shaarli/Shaarli/releases/tag/v0.5.2)

**Comment by kalvn** [comment]
You are perfectly right, I was running Shaarli 0.5.1. I upgraded to the last version and it works again. Sorry for the duplicate issue and thanks for the help.

**Comment by virtualtam** [comment]
No problem :)
