### ISSUE TITLE
html encoding issue

### ISSUE THREAD

**Issue by jeekajoo** [shaarli/Shaarli#352]
Hi,
Try to shaarlink this: https://budgetparticipatif.paris.fr/bp/jsp/site/Portal.jsp?document_id=1959&portlet_id=123

Shaarli will save this: https://budgetparticipatif.paris.fr/bp/jsp/site/Portal.jsp?document_id=1959&amp;portlet_id=123 .. and thus making the link invalid.

Thanks

**Comment by ArthurHoaro** [comment]
Few questions:

  * Are you using a redirector? If so, probably #328 duplicate.
  * Which version of Shaarli are you using? 
  * Which way did you used to save the link?

**Comment by ArthurHoaro** [comment]
Few questions:

  * Are you using a redirector? If so, probably #328 duplicate.
  * Which version of Shaarli are you using? 
  * Which way did you used to save the link?

**Comment by jeekajoo** [comment]
i'm using last version (master)

bookmarklet
```javascript
javascript:javascript:(function(){var%20url%20=%20location.href;var%20title%20=%20document.title%20||%20url;window.open('https://fralef.me/links/?post='%20+%20encodeURIComponent(url)+'&title='%20+%20encodeURIComponent(title)+'&description='%20+%20encodeURIComponent(document.getSelection())+'&source=bookmarklet','_blank','menubar=no,height=650,width=600,toolbar=no,scrollbars=no,status=no,dialog=1');})();
```

Actually when I'm editing a link, shaarli is showing the html encoding code:
![screenshot - 15092015 - 12 40 19](https://cloud.githubusercontent.com/assets/1882534/9874569/1eb13cd2-5ba7-11e5-9b90-3cd80bb9da3b.png)

**Comment by jeekajoo** [comment]
guess what. problems comes from the template I'm using. ping @kalvn

**Comment by kalvn** [comment]
Damn, all the `htmlspecialchars` have been removed from template and I didn't see it!
I believe the escapement is now done in php files directly. Sorry for this, the last commit fixes this (https://github.com/kalvn/Shaarli-Material/commit/10f77f3df928a1977a138a3bf2a1cac267351077).

By the way, that would be great to have a sort of "changelog-for-theme-developers" file for themes developer to be notified of important changes in php which may impact custom themes at each major update.

**Comment by jeekajoo** [comment]
nice. it looks like you fixed it.
I was just reporting the bug on your theme :) https://github.com/kalvn/Shaarli-Material/issues/17

**Comment by kalvn** [comment]
Yep I just saw it, thanks a lot for your feedback on this!

**Comment by ArthurHoaro** [comment]
Yes, this behaviour has been changed in #224.

I agree with your *changelog-for-theme-developers* idea, especially with the plugin system coming. I'm not sure which support should be used though. We were talking about a release related locked thread with @virtualtam and @nodiscc.

Do you think this should be enough?

**Comment by kalvn** [comment]
Yep, it seems perfect, as long as this thread is easily findable for themers.

**Comment by virtualtam** [comment]
Hi all!

I've created [#353 - Releases / Roadmap](https://github.com/shaarli/Shaarli/issues/353) to track the upcoming key changes that will be brought to Shaarli.

Template designers should not be impacted by background tasks (refactoring, code compliance, documentation...).

Major changes are to be expected in the following releases:
- [v0.6.0](https://github.com/shaarli/Shaarli/milestones/0.6.0) - Plugin system
- [v0.8.0](https://github.com/shaarli/Shaarli/milestones/0.8.0) - Page template rewrite
