### ISSUE TITLE
'-' operator for search/tags

### ISSUE THREAD

**Issue by nodiscc** [shaarli/Shaarli#358]
This is a feature that I have been found missing for some time in Shaarli: negative filtering of search results.

This has multiple use cases, mostly I have some tags that are for things that I have an interest in (personal bookmarks, documentation, technical topics) and I wish friends and visitors that have no interest in this could filter them out (eg send them a mail _check what cool links I have found this week https://my.shaarli.url/?searchtags=-doc-tech-poney_). Right now the `-` operator is treated like any other character.

note that I still would like these links publicly visible, private links have a different purpose

UI for this is a separate issue; but URL params for this would be nice.

What do you think?

**Comment by ArthurHoaro** [comment]
Good idea. Kinda related to #315.

Note that you can currently create a tag starting with a `-`. So this feature might need some retro compatibility work.

**Comment by mro** [comment]
interesting. I would recommend - for compatibility reasons - to introduce a new GET parameter `q` with semantics like

  <https://startpage.com/do/search?q=foo+%2Bbar+-term>

where `foo`, `bar`and `term`are full text phrases. To search tags I would recommend parameters like

  <https://startpage.com/do/search?q=tag:foo+%2Btag:bar+-tag:term>

This may be a powerful search with clear and well-defined (API) interface, full backward compatibility and even extensible semantics.

What do you guys think?
