### ISSUE TITLE
Thumbnail fails when it's a gallery from Imgur

### ISSUE THREAD

**Issue by NerosTie** [shaarli/Shaarli#364]
If a link comes from a gallery on Imgur (not a single picture), the thumbnail fails.

**Comment by nodiscc** [comment]
Thumbnails for albums are not available: https://github.com/sebsauvage/Shaarli/blob/c2be107852ade1150402747e166b62fc041f8df9/index.php#L1916

See the generic thumbnailer patch to allow thumbs for albums. https://github.com/shaarli/Shaarli/pull/153
