### ISSUE TITLE
Re-implement thumbnailing as a plugin

### ISSUE THREAD

**Issue by nodiscc** [shaarli/Shaarli#365]
Related to https://github.com/shaarli/Shaarli/issues/345 and https://github.com/shaarli/Shaarli/issues/127

Mutually exclusive with patches https://github.com/shaarli/Shaarli/pull/153 and https://github.com/shaarli/Shaarli/pull/361 so a choice needs to be made

> Regarding custom thumbnails and the discussion on gitter (which plugins do we enable by default):
> 
> Is it possible to move thumbnailing to a plugin? This would allow several options, just by enabling one plugin:
> - Use the default, legacy thumbnailer (need to port current thumbnailer to a plugin)
> - Use an improved [generic thumbnailer](https://github.com/shaarli/Shaarli/pull/153) (need to adapt this patch to work as a plugin)
> - Use custom thumbnails (proposed here)
> - Use favicons (Based on you favicon extractor?)
> - Disable thumbnails (no thumb. plugin enabled)
> - Others (website screenshots...)
> 
> The legacy thumbnailer plugin would be enabled by default.
> 
> I don't really like the idea of a plugin affecting the core code
> 
> Me neither, that's why I suggest making thumbnailers independent from the core.

**Comment by rubykat** [comment]
I want custom thumbnails very much. The main problem that I can see is that custom thumbnails require storing the thumbnail URL as well as the bookmark URL, and that requires altering the database.
On the other hand, would it hurt so much to store a thumbnail URL? For the original thumbnailing stuff, it deduces a thumbnail URL from the bookmark URL (e.g with youtube) at the time of thumbnail construction. It would make just as much sense to deduce a thumbnail URL at the time of saving the bookmark, save that thumbnail URL, and then the thumbnailing code could be simpler, just checking whether there's a thumbnail URL saved or not.

**Comment by mro** [comment]
indeed, editable thumbnail urls would be nice. I thought about it here https://github.com/shaarli/Shaarli/pull/153#issuecomment-85734678 

However shaarli is about links in the first place, images are 2nd prio. And I have no idea how well the storage scales. URLs tend to be heavy.

How would plugins access storage?

**Comment by rubykat** [comment]
Storage tends to be cheap, though. I was thinking that a simpler, more consistent interface would be desireable, but sure, it isn't *necessary* to store thumbnail URLs for every single bookmark, one could keep the thumbnail-guessing code just as it is.

I don't know how plugins would access storage, I haven't (yet) looked at the plugin interface.

When I hacked the older code to put my own version of this in, I saw that there are two points at which the database stuff needed changing: first, when it is read, and second, when it is written. When it is read, it reads each bookmark record into a hash, and basically ignores the stuff it doesn't care about. At that point, I checked if a thumbnail field existed, and if it didn't, set the record hash thumbnail field to an empty string, which the thumbnailing code could check and act appropriately. When saving, one would save the thumbnail field along with everything else. (Mind you, I haven't looked at the code recently, so I could be misremembering).

As for images being second priority, I can't see how having more flexible thumbnails would be *harmful* to bookmarking. I mean, using Shaarli as a micro-blogging platform isn't about bookmarks either, and yet that is one of its touted uses.

**Comment by mro** [comment]
yes, interesting. How dow you think the storage r/w access would scale, say into 1e5 thumbnails of 1k size?

**Comment by rubykat** [comment]
Well, I only have the example of my hacked version (running here: http://www.katspace.org/links/craftmarks/) which has 683 bookmarks and the database is 132K. My non-thumbnail bookmarks (using a normal Shaarli) only has 389 bookmarks, and the database is 43K. That's an average of 0.19K per bookmark for the first, and 0.11K per bookmark for the second.

I don't understand what you mean by "thumbnails of 1k size", since it's clear that the thumbnail URLs don't take up 1K -- unless you are talking about the thumbnail images themselves? That's a different matter; the caching of thumbnail images is done the same way, whether the URL of the thumbnail is deduced from the bookmark, or whether it is provided as a URL by the user.

**Comment by mro** [comment]
1k is maybe a bit too large, but I mean the textual urls itself.

**Comment by rubykat** [comment]
IMHO, I think the notes about a bookmark are likely to be bigger than the URLs. Well, depending on the person, I suppose.

**Comment by mro** [comment]
so, after all, the additional image url isn't likely to blow the storage, right?

**Comment by rubykat** [comment]
I don't think it would blow the storage, no.

**Comment by ArthurHoaro** [comment]
I think thumbnails should stay a core feature. Illustrating shaared link is really related the core feature of Shaarli. Most importantly, doing it with a plugin would probably be too much 'hacky'. However, they need to be refactored (#153 and #345 - I didn't really dig in the code) in a smart way. For exemple, having a plugin for custom thumbnails, as @rubykat mentionned.

Thumbnails URL storage size is a non issue. We're talking about a few kb, even for a large database. Thumbnails cache can be though.

Maybe 0.7 milestone is a good time for it?

**Comment by mro** [comment]
+1. As to image urls – im speculating a bit in direction of data urls…

**Comment by ArthurHoaro** [comment]
I should have read my own comment.

There is a big issue I didn't think of with thumbnails as a plugin: the picwall. It's actually a main core feature of Shaarli which rely on thumbnails. Creating an entire page with the plugin system is not possible (well, it is, but it requires a bunch of terrible hacks).

I'd rather go for a core feature which can be disabled. Closing this for now, feel free to comment/re-open if you disagree.
