### ISSUE TITLE
Problem when shaaring a link in Reader View of Firefox

### ISSUE THREAD

**Issue by StyMaar** [shaarli/Shaarli#366]
When in Firefox Reader View, if you try to post the current page on shaarli with the bookmarklet, the url that is being posted is “URL-encoded” (special characters being escaped) and prefixed with `about://reader?url=`.

The link posted on shaarli is then non-followable.

**Comment by ArthurHoaro** [comment]
Confirmed:

  * [Firefox Reader View](https://support.mozilla.org/en-US/kb/firefox-reader-view-clutter-free-web-pages).
  * [Usable here for example](http://www.theatlantic.com/international/archive/2015/10/europeans-comfort-touch-social-bonds/412861/).

**Comment by StyMaar** [comment]
I'm currently working on a pull request for that. It should land in a few minutes.

**Comment by StyMaar** [comment]
landed here : https://github.com/shaarli/Shaarli/pull/367

**Comment by alexisju** [comment]
Juste au passage, Firefox désactive le bouton de partage social quand le mode lecture est activé...

Cela oblige normalement à quitter le mode de lecture pour enregistrer/partager l'url.

**Comment by ArthurHoaro** [comment]
That looks like a lazy move. :)
