### ISSUE TITLE
Add unit tests for each plugin

### ISSUE THREAD

**Issue by ArthurHoaro** [shaarli/Shaarli#371]
I only wrote unit tests for the plugin manager, covering each plugin individually would be a good improvement.

  - [x] addlink_toolbar
  - [x] archiveorg
  - <s>demo_plugin</s>
  - [x] playvideos
  - [x] qrcode
  - [x] readityourself
  - [x] wallabag

Edit: won't test demo_plugin - it will be long and useless.

**Comment by mro** [comment]
refs #71
