### ISSUE TITLE
Bookmarklet can not retrieve title when there is a quotation mark in it

### ISSUE THREAD

**Issue by alexisju** [shaarli/Shaarli#382]
When there is a quotation mark (") , bookmarklet (as well with Firefox Social Api) can not retrieve the title correctly to prefill informations about a new link to save. 

The problem happens only with the straight US quotes ("), not with other typographical forms ( « “ )

Example : 
 - http://www.techno-science.net/?onglet=news&news=14547
 - https://www.rtbf.be/info/monde/detail_crise-des-migrants-le-president-obama-denonce-l-hysterie-regnant-aux-etats-unis?id=9139841
 - http://www.treehugger.com/corporate-responsibility/vw-discovers-more-gasoline-models-implausible-co2-figures.html
 - Ok with « : https://lejournal.cnrs.fr/articles/de-tout-temps-lhomme-sest-deplace
 - Ok with “ : http://www.ecf.com/news/success-for-the-zero-star-for-eurostar-campaign/

**Comment by ArthurHoaro** [comment]
Confirmed. The title is probably not escaped correctly.
