### ISSUE TITLE
Question: Change versioning schema?

### ISSUE THREAD

**Issue by e2jk** [shaarli/Shaarli#4]
The current versioning scheme is:
- an increasing integer (at the moment 41)
- prepended by "0.0"
- appended by "beta" (lower case, with space when displayed, without space in the release zipfiles' filenames)

The latest version is currently "0.0.41 beta".

In an email discussion with @sebsauvage in 2011 (actual version then was 0.0.30beta), when I asked if the version number might get changed in the future Seb's answer was:
> Sinon pour le numéro de version, je n'ai aucune stratégie marketting :-)
> Je garde le beta pour bien signaler que ça peut casser... 

That things might break, I think 3 years further down the line we see it's reasonably stable, and we could drop the "beta" part.

The double 0 in the beginning doesn't have much sense either, to my opinion.

I would suggest we move to something a bit more conventional, either 0.43 (with the idea we would go to v 1.0 some time, and then rediscuss a new versioning scheme from there on), or just keep it simple and call the next version v43.

I would like to have @sebsauvage's input before we change anything, hence my proposition to release 0.0.42beta in #3. Let's wait for him to be back from vacation to weigh-in on this question.

**Comment by nodiscc** [comment]
Should we release v0.0.43beta now? There have been many improvements since the last release, and I think the current code is stable. The v0.9beta milestone still holds.

**Comment by e2jk** [comment]
Fine by me

**Comment by nodiscc** [comment]
[v0.0.43beta released!](https://github.com/shaarli/Shaarli/releases/tag/v0.0.43beta) Thanks to everyone involved.

**Comment by nodiscc** [comment]
Closing this as the planned versioning is now detailed in [milestones](https://github.com/shaarli/Shaarli/milestones)
