### ISSUE TITLE
Require write permissions only for relevant directories

### ISSUE THREAD

**Issue by nodiscc** [shaarli/Shaarli#40]
It is recommended to not give write access to all files to the webserver process (see https://wiki.debian.org/Apache/Hardening#File_permissions). The dirs for which write permissions are required are `cache`, `data`, `pagecache` and `tmp`, so we should only check these.

This allows to install shaarli with user/group `someuser:www-data` and permissions `640` (`750` for dirs), except for these read/write dirs. The permissions can be stored in the git repository (so no extra chmod/chown commands required at install)

This was requested at https://github.com/sebsauvage/Shaarli/issues/181, and discussed at https://github.com/shaarli/Shaarli/pull/11#issuecomment-50869986

**Comment by nodiscc** [comment]
Bumping this issue

https://github.com/shaarli/Shaarli/blob/master/index.php#L110

Can we check only ifrequired directories exist/are writable instead?
We can then remove the `mkdir()` calls.

**Comment by ArthurHoaro** [comment]
Yes, we can check every directories individually. If it doesn't exist, we can create is though. The only issue is if it's not writable.

**Comment by virtualtam** [comment]
Hi all!
As nobody's currently assigned, I'd like to start working on this as part of #372 :)

Suggestion:
- check whether file/folder permissions match the wiki's [Shaarli configuration](https://github.com/shaarli/Shaarli/wiki/Shaarli-configuration)
- display a warning message with all information, so the user doesn't have to play hide & seek with permissions to get Shaarli working

**Comment by ArthurHoaro** [comment]
Is this issue still open for directories autocreation?

**Comment by virtualtam** [comment]
Still open as the resource check is only done during the first install, and it'd be nice to allow users to run checks from the tools, as well as when there's a failed attempt at writing the datastore.
