### ISSUE TITLE
Plugin is not displayed  on all pages

### ISSUE THREAD

**Issue by alexisju** [shaarli/Shaarli#402]
A plugin supposed to add items on all pages at buttons_toolbar location doesn't work as expected using a specific template.

The call on my page.header.html seems correct :

``
    {loop="$plugins_header.buttons_toolbar"}
        {$value}
    {/loop}
``

code : https://github.com/alexisju/albinomouse-template/blob/master/page.header.html

The function into my plugin is :
```
function hook_effingo_menu_render_header($data)
{
    $data['buttons_toolbar'][] = file_get_contents(PluginManager::$PLUGINS_PATH . '/effingo_menu/effingo_menu.html');
    
    return $data;
}
```
code : https://github.com/alexisju/menu/blob/master/effingo_menu.php

The plugin displays correctly everywhere except on the daily.html, why i opened this issue.

You can try at this url : https://liens.effingo.be/

**Comment by alexisju** [comment]
You can also try with this plugin : https://github.com/alexisju/gototop

Same issue, it doesnt work on daily page.

**Comment by ArthurHoaro** [comment]
Yep that's a bug. The daily page isn't processed through the `Router`, so the default hooks (footer/header/etc) aren't triggered.
