### ISSUE TITLE
css : footer doesn't need to have a max-width

### ISSUE THREAD

**Issue by alexisju** [shaarli/Shaarli#404]
Max-with on #footer of the default template limits too much plugins possibilities (like floating in css).

More exactly, the limitation impacts the plugin_footer loop and not the footer itself.
```
{loop="$plugins_footer.text"}
        {$value}
{/loop}
```

**Comment by nicolasdanelon** [comment]
Agree. If I write a plugin and this plugin is not adding a CSS file my functionality will be limited. +1

**Comment by ArthurHoaro** [comment]
Can you provide a use case of what you would like to do?

**Comment by alexisju** [comment]
Try with this plugin : https://github.com/alexisju/gototop

**Comment by alexisju** [comment]
If you prefer dont modify #footer, maybe we could add a specific class to the `plugins_footer` loop

**Comment by ArthurHoaro** [comment]
Adding another loop is probably cleaner, yes.

**Comment by ArthurHoaro** [comment]
Reopened to don't forget to update the documentation.

**Comment by ArthurHoaro** [comment]
done
