### ISSUE TITLE
Reverse proxy: ban the client IP instead of the proxy IP

### ISSUE THREAD

**Issue by nbedou** [shaarli/Shaarli#409]
My shaarli is behind a reverse proxy. Then whenever someone try to brute force it, the proxy IP is banned (``$_SERVER['REMOTE_ADDR']``), which prevents anyone (including me) to login. Indeed it would be preferable to ban the real client IP (``$_SERVER['HTTP_CLIENT_IP']``).

Cf functions ``ban_loginOk``, ``ban_loginFailed``.

To avoid spoofing, it would be great to define in ``config.php`` an array of trusted proxies (like for [owncloud](https://doc.owncloud.org/server/8.2/admin_manual/configuration_server/reverse_proxy_configuration.html)).

Thanks!

**Comment by ArthurHoaro** [comment]
We could use [this](https://github.com/zendframework/zend-http/blob/master/src/PhpEnvironment/RemoteAddress.php) to retrieve IP address and handling reverse proxy.

**Comment by virtualtam** [comment]
@nbedou: I like the idea of keeping a list of trusted IPs, thanks for the suggestion :)

@ArthurHoaro: let's keep processing as simple as possible until refactoring provides us with a good visibility on the code; introducing a lightweight PHP framework could then prove useful to handle common operations (session handling, security, etc.)

**Comment by ArthurHoaro** [comment]
Well, even if we don't take the whole class which is a bit overkill, the algorithm is good. We need to do something like this:

```
if REMOTE_ADDR is in trusted_proxy
  Try to retrieve IP from other headers... or not and do nothing.
else
  Use REMOTE_ADDR (which can't be spoofed).
```
