### ISSUE TITLE
Move all configuration settings to data/config.php

### ISSUE THREAD

**Issue by nodiscc** [shaarli/Shaarli#41]
~~Once https://github.com/shaarli/Shaarli/issues/40 is solved we can think about moving options.php out of data/. It is _not_ program data and should not be writeable by the server.~~

~~We can also provide a options.example.php presenting all switches from https://github.com/shaarli/Shaarli/blob/master/index.php and https://github.com/shaarli/Shaarli/wiki#configuration and have evrything in one place.~~

See below

**Comment by nodiscc** [comment]
Pull request https://github.com/shaarli/Shaarli/pull/108 solves this

**Comment by ArthurHoaro** [comment]
It can be done easily by iterating over `$GLOBALS['config']`. However, I'd prefer to keep `config.php` instead of using `options.php`.
