### ISSUE TITLE
Title do not show if space at the end of the URL

### ISSUE THREAD

**Issue by tmos** [shaarli/Shaarli#410]
Hi,

If I paste the URL in the "add link" form with some extra spaces at the end of the url (when copied manually for example), the title doesn't auto fill. It seems to be a simple trim I guess.

Regards,
Tom

**Comment by alexisju** [comment]
Indeed, it is not only when there is a space, it is also when there is not extension (.php, .html,...) or no slash at the end of the url. May differt if https is used. Only by the "add link" form.

**Comment by ArthurHoaro** [comment]
There is a `trim()` missing [here](https://github.com/shaarli/Shaarli/blob/master/application/Url.php#L109).

It also doesn't work if you're putting a link with an invalid certificate (like mine which is *very* outdated). 

@alexisju I couldn't reproduce the issue with or without an extension or a slash.

**Comment by alexisju** [comment]
Without space at the end, try these : 

naked domain ie : 
 - `http://github.com` or `http://effingo.be`-> no title

Some https issues ?
`https://motherboard.vice.com/read/pirate-bay-founder-peter-sunde-i-have-given-up`
`https://github.com/pulls` but `http://github.com/pulls` ok

Some other issues seems caused by redirects who are not managed by shaarli.
http://lemonde.fr (no title) -> http://www.lemonde.fr (title)

**Comment by nicolasdanelon** [comment]
Hi ! 
I've try with lemonde.fr and I saw this in my bash terminal
```
wget http://lemonde.fr
--2015-12-14 13:28:45--  http://lemonde.fr/
Resolving lemonde.fr (lemonde.fr)... 93.184.220.20
Connecting to lemonde.fr (lemonde.fr)|93.184.220.20|:80... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: http://www.lemonde.fr/ [following]
--2015-12-14 13:28:46--  http://www.lemonde.fr/
Resolving www.lemonde.fr (www.lemonde.fr)... 72.21.91.8
Connecting to www.lemonde.fr (www.lemonde.fr)|72.21.91.8|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 443680 (433K) [text/html]
Saving to: ‘index.html’

index.html                                  100%[=============================================================================================>] 433.28K   497KB/s   in 0.9s   

2015-12-14 13:28:47 (497 KB/s) - ‘index.html’ saved [443680/443680]
```

as you can lemonde.fr has a 301 redirect to www.lemonde.fr. this is why you don't have a title without the www.

same thing with github.com

```
wget github.com
--2015-12-14 13:31:35--  http://github.com/
Resolving github.com (github.com)... 192.30.252.131
Connecting to github.com (github.com)|192.30.252.131|:80... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://github.com/ [following]
--2015-12-14 13:31:36--  https://github.com/
Connecting to github.com (github.com)|192.30.252.131|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [text/html]
Saving to: ‘index.html.1’

index.html.1                                    [ <=>                                                                                          ]  16.32K  83.5KB/s   in 0.2s   

2015-12-14 13:31:37 (83.5 KB/s) - ‘index.html.1’ saved [16713]

wget http://github.com
--2015-12-14 13:31:52--  http://github.com/
Resolving github.com (github.com)... 192.30.252.131
Connecting to github.com (github.com)|192.30.252.131|:80... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://github.com/ [following]
--2015-12-14 13:31:53--  https://github.com/
Connecting to github.com (github.com)|192.30.252.131|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [text/html]
Saving to: ‘index.html.2’

index.html.2                                    [ <=>                                                                                          ]  16.32K  83.1KB/s   in 0.2s   

2015-12-14 13:31:54 (83.1 KB/s) - ‘index.html.2’ saved [16712]
```

but with effingo.be the thing is totally different:

```
wget http://effingo.be
--2015-12-14 13:32:01--  http://effingo.be/
Resolving effingo.be (effingo.be)... 185.49.20.101
Connecting to effingo.be (effingo.be)|185.49.20.101|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [text/html]
Saving to: ‘index.html.3’

index.html.3                                    [  <=>                                                                                         ]  25.56K  94.4KB/s   in 0.3s   

2015-12-14 13:32:03 (94.4 KB/s) - ‘index.html.3’ saved [26175]
```

just in case : 
```bash
$ wget --version
GNU Wget 1.16.3 built on linux-gnu.
```

any ideas?

**Comment by ArthurHoaro** [comment]
About `301` and `302` HTTP codes (redirection), we could try to reach the first redirection to retrieve the title (follow first response HTTP header `Location`).

About effingo.be, that's *very* weird. @alexisju, your webserver rejects Shaarli's user-agent.

On both http://effingo.be and http://effingo.be, `file_get_contents()` returns `false` with:

  * Shaarli's User-Agent: `Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:23.0) Gecko/20100101 Firefox/23.0`
  * My own User-Agent: `User-Agent: Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:42.0) Gecko/20100101 Firefox/42.0`
  * Just User-Agent: `mozilla`

BUT there is no problem with those UA using my browser (and editing request HTTP headers).
AND those are working:

  * UA: `shaarli`
  * UA: `mozill`
  * Don't start with full Mozilla, UA: `Mozill/5.0 (X11; Ubuntu; Linux x86_64; rv:23.0) Gecko/20100101 Firefox/23.0`

No issue on liens.effingo.be. And they're both responding through `http01.web4all.fr`.

I've honestly no idea what's could cause that. Do you have specific settings, like a `.htaccess`?

**Comment by virtualtam** [comment]
It'd be OK to follow HTTP redirections, as far as these cases are handled:
- (optional) allow adjusting the request timeout;
- (optional) add a config entry to toggle redirection support;
- limit the number of redirections ( < 5 should be more than sufficient);
- the redirection may lead to an entirely different website for a number of reasons:
    - new hosting service;
    - new website version;
    - temporary (site down for maintenance);
    - hacked / defaced site;
- in the aforementioned situation, the user should be warned so he can choose whether:
    - not to archive the URL at all;
    - archive the final resolved URL;
    - archive the initially filled URL and use metadata from the page obtained after following redirections.

**Comment by ArthurHoaro** [comment]
And I forgot about `vice.com`.

`get_headers()` isn't using the stream_context created for `file_get_contents()`, and returns a 504 HTTP code even though we downloaded the page without error. It can be fixed with `stream_context_set_default()`.

**Comment by ArthurHoaro** [comment]
@virtualtam: I was only talking following the redirection to attempt retrieving the title. We should keep the URL as the user typed in. So we don't really care why the URL is redirected (and the field is protected against XSS attacks in the worst scenario).

**Comment by nicolasdanelon** [comment]
which will be the URLs for testing this issue ? the following ?
``` 
( fail ) vice.com
(status) http://effingo.be
(status) https://motherboard.vice.com/read/pirate-bay-founder-peter-sunde-i-have-given-up
( fail ) https://github.com/pulls 
( fail ) http://github.com
(  ok  ) http://github.com/pulls
( fail ) http://lemonde.fr
(  ok  ) http://www.lemonde.fr
```

**Comment by ArthurHoaro** [comment]
And `http://www.lemonde.fr    ` since it's the original issue.

Except if we find other failing use cases in the meantime, that seems fine.

**Comment by ArthurHoaro** [comment]
Update:

```
( fail ) https://github.com/pulls 
( fail ) http://github.com
```

Won't work because they're 404 URL while logged out. I tried `github.com/shaarli/Shaarli/pulls` instead.

```
(status) http://effingo.be
```
Also doesn't work, see my previous [comment](https://github.com/shaarli/Shaarli/issues/410#issuecomment-164520489). I'm now on a different computer and I get a `HTTP/1.1 403 Bad Behavior` from response header. @alexisju should see something in his log files.
