### ISSUE TITLE
master installation - search breaks after import

### ISSUE THREAD

**Issue by Kulak** [shaarli/Shaarli#415]
My installation was clean, without default links and a couple test lings and a couple or so tags.

I have imported my chrome bookmarks (I think the amount is about 1700) from Chrome browser and I observed:

* import page never displayed anything
* some large number of links made it, but it is not clear if all made it
* I can browse site as usual

* BUT search is broken with "Server error 500"

Any pointers on where to collect more error related information?

The installation is from git hub master branch.
I used defaults, so there is no mysql installation in use.

thanks

**Comment by nodiscc** [comment]
Hi @Kulak is there something relevant in your webserver error logs (both during import and when the error 500 happens)? For apache/debian the error log is at `/var/log/apache2/error.log`

**Comment by Kulak** [comment]
I am sorry for not including the error in initial post.  I had no access to the server log.
Here it the relevant error (I removed parts of identity):

PHP message: PHP Fatal error:  Call to undefined function mb_convert_case() in /usr/local/----/shaarli/application/LinkDB.php on line 353" while reading response header from upstream, client: 198.182.x.x, server: pin.xx.com, request: "GET /?searchterm=Linux HTTP/1.1", upstream: "fastcgi://192.168.x.x:9000", host: "pin.xx.com", referrer: "http://pin.xx.com/"

I am also getting time zone warnings UTC/UTC, but these are not as important:

PHP message: PHP Notice:  date_default_timezone_set(): Timezone ID 'UTC/UTC' is invalid in /usr/local/----/shaarli/data/config.php on line 6

2015/12/18 23:57:45 [error] 79220#0: *1057 FastCGI sent in stderr: "PHP message: PHP Warning:  date_default_timezone_get(): It is not safe to rely on the system's timezone settings. You are *required* to use the date.timezone setting or the date_default_timezone_set() function. In case you used any of those methods and you are still getting this warning, you most likely misspelled the timezone identifier. We selected the timezone 'UTC' for now, but please set date.timezone to select your timezone. in /usr/local/----/shaarli/index.php on line 21

**Comment by Kulak** [comment]
It appears that my issue is installation dependent.  I am using PHP on FreeBSD and it seems to have been compiled without mbstring support.

The resolution is to recompile PHP with the --enable-mbstring flag.

**Comment by ArthurHoaro** [comment]
You also need php-gd for thumbnails.

**Comment by Kulak** [comment]
I installed php56-mbstring package and that resolved my issue.
