### ISSUE TITLE
Markdown conversion from wiki to documentation break links

### ISSUE THREAD

**Issue by ErwanLeroux** [shaarli/Shaarli#416]
Hello,

I think there is something wrong in the html version of doc/Home.md

First link
Welcome to the `<a href="https://github.com/shaarli/Shaarli/">Shaarli</a> wiki<embed src=".html" />`
Notice the `<embed>` part

Second link
For general info, read the `<a href="https://github.com/shaarli/Shaarli/blob/master/README.md">README</a>.<a href=".html"></a>`
Notice the second `<a>`

There is more wrong links in the page, I will not list all of them because I think they all have the same cause.
In doc/Home.md, I see this "`[](.html)`", which look like a typo.

Edit to show the link using proper Markdown syntax

**Comment by alexisju** [comment]
Wich version of shaarli is concerned / do you use?

The demo instance doesn't have this issue : http://shaarlidemo.tuxfamily.org/Shaarli/doc/Home.html

**Comment by ErwanLeroux** [comment]
I use the stable version.

**Comment by alexisju** [comment]
Do you have a link to you doc?

**Comment by ErwanLeroux** [comment]
Here you go : http://shaarli.elendar.fr/doc/Home.html

**Comment by alexisju** [comment]
Indeed. I guess it is a little bug of the compiler from wiki to html...

**Comment by ErwanLeroux** [comment]
Not sure, I think there is something wrong directly in the .md.

What is the purpose of `[](.html)` ? It look like a incomplete link.

**Comment by alexisju** [comment]
I think the md is generated directly from the wiki https://github.com/shaarli/Shaarli/wiki 
This .md is not supposed to be edited manually.

**Comment by ErwanLeroux** [comment]
Okay I was thinking the other way around, ie that the .md was the source of the wiki ^^

**Comment by ErwanLeroux** [comment]
I clone the wiki and checked, no trace of `[](.html)` inside, so something happens when the wiki is duplicated in doc/

**Comment by ErwanLeroux** [comment]
I found other wrong links : `<a href="(https://api.travis-ci.org/shaarli/Shaarli.svg)](https://travis-ci.org/shaarli/Shaarli).html"><img src="https://travis-ci.org/shaarli/Shaarli" alt="(https://api.travis-ci.org/shaarli/Shaarli.svg)" /></a>`

**Comment by virtualtam** [comment]
Hi @ErwanLeroux!

Please keep in mind that the current format for the local documentation is more of a _convenience hack_ than a proper support:
- there are some (known) shortcomings when converting GitHub-flavoured Markdown to HTML:
    - relative links;
    - static resource links (images);
- #312 has been raised to switch to a proper, more flexible documentation system (Sphinx), and either host it on ReadTheDocs, or as a github.io website.

Feel free to submit a PR if you find a simple fix for the documentation `make` [targets](https://github.com/shaarli/Shaarli/blob/master/Makefile#L156) though :)

**Comment by ErwanLeroux** [comment]
Thanks @virtualtam, I saw that part of the makefile earlier, but I did not understand all of it.
The generation of the doc is `make htmldoc` right ? I'm going to poke around to see what I can do.

**Comment by virtualtam** [comment]
To elaborate a bit: we use [Pandoc](http://pandoc.org/) to generate HTML documentation from the GitHub wiki pages.

Here's what is done by each Makefile target:
- `doc` clones the Shaarli wiki repository
- `htmlsidebar` parse the GitHub [_Sidebar](https://github.com/shaarli/Shaarli/wiki/_Sidebar/_edit) to generate a standard Markdown-formatted sidebar, then generates the actual HTML sidebar with Pandoc
- `htmlpages` parses all wiki pages, removes Markdown pages titles, applies some regexes with `awk` to fix _most_ links, then generates the final HTML pages, each with a custom title and the previously generated sidebar

The whole process is quite a succession of hacks, resulting in a local documentation that is browsable enough...

Broken links mostly come from the GitHub-flavoured Markdown syntax (especially handy shortcuts for relative links) not being fully supported by Pandoc. So there is a risk that when fixing parsing for some links, other will end up being broken :(

**Comment by ErwanLeroux** [comment]
Thanks for the details, I figured as much, altough I can't claim I understand all of the command used :)
I'm currently testing a [php script](https://gist.github.com/ErwanLeroux/ae7a7083e16f31995b69) to use the github api to convert from GFM to html.

**Comment by ErwanLeroux** [comment]
All wrongs come from the use of `[[Unit tests]]` syntax on the wiki. I'm trying more regex to take account of this syntax

**Comment by ArthurHoaro** [comment]
Maybe we can just don't use this syntax?

**Comment by ErwanLeroux** [comment]
It's a possibility. At least I would recommend to not use it on image.
`[[images/firefoxshare.png]]` should be `![](/shaarli/Shaarli/wiki/images/images/firefoxshare.png)`

Note for later:
On the sidebar, `[[Home]]` should be translated to `[Home](../Home)`
Reference : https://help.github.com/articles/adding-links-to-wikis/

**Comment by ArthurHoaro** [comment]
Didn't make any test, but [also relevant](https://github.com/blog/1395-relative-links-in-markup-files).

**Comment by ErwanLeroux** [comment]
I just tested it a bit
sidebar : `[Home](../Home)` is not equivalent to `[Home](../Home.md)`
wiki : [plugins](Plugin-System) is not equivalent to `[plugins](Plugin-System.md)`

I think relative links in wiki doesn't like .md extension

**Comment by virtualtam** [comment]
Closed per #772, see also #312
