### ISSUE TITLE
Move Dockerfiles to the main repository

### ISSUE THREAD

**Issue by virtualtam** [shaarli/Shaarli#420]
Pros:
- prod & dev DockerHub images are built after each commit, for both `master` and `stable` branches
- [Travis supports](https://docs.travis-ci.com/user/docker/) using/building custom Docker images to run tests

Cons:
- more CI metadata in the main repo (can be filtered from release archives though, see #419)

**Comment by virtualtam** [comment]
TODO:
- [ ] add Dockerfiles to the main repo
- [ ] re-create a Git automated build on Docker Hub
- [ ] remove Docker content from `docker-shaarli`
    - [ ] leave a notice with the new location
- [ ] move & update Docker doc from the repo to the wiki

**Comment by nicolasdanelon** [comment]
+1
