### ISSUE TITLE
Request for Help: shaarli behind ngrok tunnel

### ISSUE THREAD

**Issue by mro** [shaarli/Shaarli#421]
who can help to tunnel to the public shaarli from https://github.com/shaarli/Shaarli/issues/198#issuecomment-93697667 via [ngrok](https://ngrok.com)?

    $ ngrok http -host-header=rewrite shaarlidemo.tuxfamily.org:80

and logging in at

    http://<random subdomain>.ngrok.io/Shaarli/

which fails for me with "Wrong login/password."

(When debugging https://github.com/mro/ShaarliOS/issues/6 I'd like to use a public instance as a reference and not install php on my tls servers and vice versa).

Update: looks like the session gets lost.

**Comment by ArthurHoaro** [comment]
Check out #319 and [this](https://github.com/shaarli/Shaarli/wiki/Server-configuration#proxies).

**Comment by mro** [comment]
@ArthurHoaro thank you https://github.com/shaarli/Shaarli/issues/319#issuecomment-137012866 and https://github.com/shaarli/Shaarli/issues/319#issuecomment-158808012 look promising.

**Comment by mro** [comment]
ngrok doesn't seem to support http-header changes as required to get the session cookie properly assigned.

So this seems a dead end.

**Comment by nodiscc** [comment]
You might want to try pagekite (if you don't need ngrok's traffic sniffing and just want a tunnel to localhost)
