### ISSUE TITLE
Option to open shaare links in new window/tab

### ISSUE THREAD

**Issue by wouaibe** [shaarli/Shaarli#422]
Ask of Enhancement
Add a 'target="_blank"' option for link list on Tools/configuration of shaarli
So that on linklist page, each link opens in new tab.

**Comment by virtualtam** [comment]
[w3schools page](http://www.w3schools.com/tags/att_a_target.asp) for the `<a>` `target` attribute

**Comment by ArthurHoaro** [comment]
I'm not really in favor of an additional setting for this, because it's minor and I'd like to keep the settings page simple. Let aside that I personally hate this browser feature, as a user.

Eventually, we can add a plugin which triggers this in JS.
I suppose we can do something like this:

```javascript
document.getElementsByClassName('linktitle')
    .getElementsElementByTagName('a')[0].target = '_blank';
```

**Comment by nicolasdanelon** [comment]
+1 for plugin :)

**Comment by ArthurHoaro** [comment]
Closing, old issue which can be fixed using a 3rd party plugin. Feel free to reopen if you think Shaarli should support it officially.

**Comment by fsch0203** [comment]
Has anyone made a plugin for this feature?

**Comment by ArthurHoaro** [comment]
Not that I'm aware of.
Le 29/07/2019 à 16:58, fsch0203 a écrit :
> Has anyone made a plugin for this feature?
>

**Comment by demure** [comment]
> Has anyone made a plugin for this feature?

I found this listed on the [Community & Related software](https://shaarli.readthedocs.io/en/master/Community-&-Related-software/) page:

https://github.com/trailjeep/shaarli-urlextern

**Comment by virtadpt** [comment]
Does it work with the v0.11.x series?

**Comment by fsch0203** [comment]
Yes, I just tried it!
