### ISSUE TITLE
Open Graph support for thumbnails

### ISSUE THREAD

**Issue by nlegaillart** [shaarli/Shaarli#425]
Hi,

Here is a small patch to make use of the Open Graph tags present in many pages to generate thumbnails. I've been using it for quite a long time now and it works well. Maybe it's not very clean, I know there is a discussion about moving thumbnail processing to a plugin but I don't know its status. 

Anyway, you get the idea, just by using these tags we can get a lot more thumbnails.

Best regards,

[shaarli_oleg.txt](https://github.com/shaarli/Shaarli/files/72813/shaarli_oleg.txt)

**Comment by nodiscc** [comment]
Hi @nlegaillart there is a patch to replace legacy thumbnailers with a generic one (using opengraph) at https://github.com/shaarli/Shaarli/pull/153/files, but it needs some work (review, rebase, bugfixes). If you're interested in improving it with your own changes.

**Comment by nlegaillart** [comment]
Hi,

It's me again with my small OpenGraph patch.
I've updated it to work with latest version (0.8.3). I know there's a more proper way to do it, using web-thumbnailer, so I'll just put it there if people want to patch their installation while they wait, like me, for 0.10.0 release :-)
And if you agree, I think we can close this issue.

PS: @nodiscc , I didn't use your code at the end. Sorry about that!

[shaarli_OleG.0.8.3.patch.txt](https://github.com/shaarli/Shaarli/files/772082/shaarli_OleG.0.8.3.patch.txt)

**Comment by ArthurHoaro** [comment]
Fixed by #687
