### ISSUE TITLE
Blank tag when filtering by tag from the input field via autocomplete

### ISSUE THREAD

**Issue by kalvn** [shaarli/Shaarli#426]
When filtering by tag using the filter input from the link list with the autocomplete plugin, it adds a space at the end of the selected text. Consequently, when I click on the filter button, the trailing space is interpreted as a separator between the first tag and an empty tag (as we can see in the URL, for example `...?searchtags=opensource+`).

Once the filtered page appears, it's fine because only the first tag is displayed. But if I delete this tag via the little cross on the right, rather than getting back on the home page, I arrive on a page which displays only links with a blank tag (so usually none).

To avoid this, a trim should be done either in Javascript when submitting the "filter by tag" form or in PHP. The PHP solution seems more logical.

I hope my explanation is clear enough. Feel free to ask for more information if it's not.

**Comment by alexisju** [comment]
I cannot reproduce that from the input field (i don't get space after tag with autocompletion).
(Alson on your shaarli with material template).

But if i add volontary a space, you're right, there is a little bug when we remove the tag (clicking on X).

**Comment by kalvn** [comment]
I made a small screencast using the release 0.6.2 of Shaarli with the default theme:

![The animation](http://i.imgur.com/YnyPIo5.gif)

**Comment by alexisju** [comment]
You're right. But if you type the first letters, then use down arrow, then enter, you don't have this issue (this is how i tested it before to answer you).

**Comment by kalvn** [comment]
I agree but still, there's a problem with the way I did on the screencast :)
And as you said before, the problem is the same if I add a space by mistake in the input by myself. That's why the trim should be done in any case.

**Comment by alexisju** [comment]
Indeed :-)
