### ISSUE TITLE
https -> Disable session hijacking

### ISSUE THREAD

**Issue by foomep** [shaarli/Shaarli#427]
My Shaarli installation runs on a uberspace server. If i use http it works fine. But when i use https and i want to log in, the side reload an i'm not loged in.
When i set $GLOBALS['disablesessionprotection'] = true; it works fine.
I'm not on a Uni-network or over mobile network. 
Why i have to disabled Session Protection? It's a bug or a fault server configuration?

**Comment by ArthurHoaro** [comment]
Which Shaarli version are you using? Do you have an error message when you try to login using HTTPS?

Shaarli's session is stored in a cookie. You should be able to monitor what's going on using Firebug or Chrome debugger.

**Comment by foomep** [comment]
now it works with $GLOBALS['disablesessionprotection'] = false.
sorry
