### ISSUE TITLE
PHP isset instead of php !empty on submit buttons values

### ISSUE THREAD

**Issue by kalvn** [shaarli/Shaarli#428]
I noticed something strange when submitting a form (for example the one to rename tag).
Here is an excerpt of the code from `index.php`:

```php
// Rename a tag:
if (!empty($_POST['renametag']) && !empty($_POST['fromtag']) && !empty($_POST['totag']))
```

It is checked whether the expected fields `fromtag` and `totag` are empty or not, which makes sense. But concerning `renametag` which is the name of the submit button, shouldn't we use `isset` instead of `!empty`? Because what matters is which button was used to submit the form, not its value.

I raise this point because in my theme, I changed submit `<input>` by submit `<button>` for design purpose, and therefore I removed the value attribute to put the label of the button between the opening and closing `<button>` tags.
Of course I can set a value for button and that's what I'm going to do as a quick fix but I think it would be preferable not to have to.

**Comment by kalvn** [comment]
By the way, I just noticed that what I suggest is already done for example when deleting a link or canceling the edition (still in `index.php`, around lines `1510`, `1543` and `1555`:

```php
if (isset($_POST['save_edit']))
//...
if (isset($_POST['cancel_edit']))
//...
if (isset($_POST['delete_link']))
```

**Comment by ArthurHoaro** [comment]
Thank you, I've submitted a patch for this.
