### ISSUE TITLE
If already saved, display timestamp

### ISSUE THREAD

**Issue by alexisju** [shaarli/Shaarli#431]
When you try to save a already-saved link, you know it is already saved (only) if you have already filled the description and tags.  

However, even with this informations, you don't know _when_ you saved it.
Sometime it could be interesting to know it directly in the popup (from social api or bookmarklet) without need to go into Shaarli and make a research.

Is it possible to display it in the `editlink.html` template?

**Comment by ArthurHoaro** [comment]
I suppose you can use `{$link.linkdate}` in your template (`editlink.html`, not `addlink`).
