### ISSUE TITLE
Multi-word search is broken

### ISSUE THREAD

**Issue by joedemo42** [shaarli/Shaarli#435]
Searching for multiple words occurring in the description does not always find the relevant note/link.

Example:
Create Link/Note containing the description: "this search is broken" with the title "demo"

Try: search for "search broken" Result: newly created Link/Note is not found
Try: search for "demo broken" Result: newly created Link/Note is not found

Try: search for "search is broken" Result: newly created Link/Note _is_ found

This behavior occurs in the latest commit of Shaarli.

**Comment by ArthurHoaro** [comment]
I might be wrong, but I'm pretty sure it's not broken, just not implemented yet. I'm working on it, along other things dealing with filtering.

**Comment by ArthurHoaro** [comment]
Actually, I'm not so sure it's a good idea.
With this feature, searching `search is broken` would return all shaares containing the word `is`. There is probably good search algorithm out there, but it would probably too complex for Shaarli.

Any opinion on this is welcome.

I quote @mro from #358, which hasn't been discussed:

> interesting. I would recommend - for compatibility reasons - to introduce a new GET parameter `q` with semantics like
>
>  <https://startpage.com/do/search?q=foo+%2Bbar+-term>
>
> where `foo`, `bar`and `term`are full text phrases. To search tags I would recommend parameters like
>
>  <https://startpage.com/do/search?q=tag:foo+%2Btag:bar+-tag:term>
>
> This may be a powerful search with clear and well-defined (API) interface, full backward compatibility and even extensible semantics.

But IMHO that's only a response to *how* to do it, not really why.

**Comment by mro** [comment]
@ArthurHoaro I think large result sets are ok – the ranking becomes super important then. I once [did such for sqlite stored data](http://blog.mro.name/2011/08/rank-sqlite-text-search-results/) – the same principles might be useful here.

**Comment by mro** [comment]
however, a sophsticated search may collide with the deisgn goal "minimalist", which I personally consider the most important 'feature'. So I'd rather leave the nifty search to a separate, parallel service – updated e.g. via pubsubhubbub.

**Comment by joedemo42** [comment]
I think @ArthurHoaro misunderstood me.
>With this feature, searching search is broken would return all shaares containing the word is. There is probably good search algorithm out there, but it would probably too complex for Shaarli.

This is not what I meant. When I input the search term `search is broken`, I expected Shaarli to search for all words like `search AND is AND broken` and return all items containing all three words - not like `search OR is OR broken`.

I wouldn't call that a sophisticated search - rather basic I think. When I use google to find something, I throw a few keywords at it and expect it to turn up something useful containing all my keywords. Searching for the exact phrase is rather the exception than the norm - well, at least for me.

Ranking on the other hand is pretty much irrelevant to me. It'd be fine to me if the results turn up in the order the links were originally added.

**Comment by joedemo42** [comment]
>however, a sophisticated search may collide with the deisgn goal "minimalist", which I personally consider the most important 'feature'.

What's the point of storing information if you've got no proper way of finding it again?

**Comment by mro** [comment]
> What's the point of storing information if you've got no proper way of finding it again?

First of all, information stored has to be able to be retrieved again. Search is a later step.

Second, I find almost everything I want with v0.48, so I can't agree that there's no proper way of finding (for me) for what I expect from a minimalistic tool. While there's always things to improve, I would be very careful in terms of effort and codebase growth.

And for search, the sky is the limit – imagine soundex, thesauri, logical operators etc. As said, I'd put a sophisticated search separate. That shouldn't be too hard.

**Comment by ArthurHoaro** [comment]
> This is not what I meant. When I input the search term search is broken, I expected Shaarli to search for all words like search AND is AND broken.

Ugh, I guess I was tired.

>  I once did such for sqlite stored data – the same principles might be useful here.

That's simple and clever. I'll try something.

**Comment by joedemo42** [comment]
>First of all, information stored has to be able to be retrieved again. Search is a later step.
Well, before I retrieve information, I must know what I want to retrieve. That's where search comes into play.

>Second, I find almost everything [...]
And that's the point. "almost everything". I hate the feeling that I might miss some result because search works the way it does now.

>And for search, the sky is the limit – imagine soundex, thesauri, logical operators etc.
Yes, that's what other tools usually call "advanced search". I did not suggest Shaarli implements any of those. I just thought it would be nice, to be able to search for items that contain all of the words in the search string. Nothing fancy, pretty basic I'd say, but I see that I seem to be the only one who thinks so.

**Comment by mro** [comment]
@joedemo42 no, I don't think you're the only one. But search semantics is really hard. That's why I referred to startpage (https://github.com/shaarli/Shaarli/issues/435#issuecomment-173690220), to have a baseline to talk about.

Their semantic is `OR` unless `+term` turns it into `AND`. When searching `OR` you get a lot of results – the ranking then determines what you see at the top. If the ranking is good (i.e. ranks like you expect), you won't bother to see all the irrelevant search results further down that `OR` brings up.

**Comment by joedemo42** [comment]
I don't see what use it would be to have `OR` as a default. I'd say `AND` is much more common. Wouldn't it be easier to use `AND` as a default and then skip ranking the results but output them in the order they were added?

Again: my goal was to find all items that contain ALL (not some) words of my search string.

**Comment by nodiscc** [comment]
I have no strong opinion on `OR` vs `AND`.
About ranking, I think search results should be ordered by date, as they are now (no complex ranking please).

**Comment by nodiscc** [comment]
But yeah, the current multiword search is somehow broken. Example: searching for `bowie deranged` does not return a link named `David Bowie - I'm Deranged (With Lyrics) - YouTube` in the search results. This is obviously wrong.

**Comment by joedemo42** [comment]
Since I don't want to be someone who just complains, I patched things myself. Right now I'm able to search for items containing the full phrase (like it is now) and for items containing all words in any order in any place. I just need a little more time to get everything ready, then I'll create a pull request.

**Comment by joedemo42** [comment]
Also, I no longer think it's correct to say it's broken - it is not. I just doesn't work like I expected.
Searching for a phrase consisting of multiple words works just fine.

**Comment by ArthurHoaro** [comment]
Alright, I'll wait for your PR then.

@nodiscc that looks like a bug though. Is it a case-sensitive issue?

**Comment by nodiscc** [comment]
It is not case-sensitive. You can try searching for `personal super-fast` on http://shaarlidemo.tuxfamily.org/Shaarli/. Shaarli always searches for the exact expression.
