### ISSUE TITLE
Change date format in log file to match native fail2ban date templates

### ISSUE THREAD

**Issue by Arno0x** [shaarli/Shaarli#436]
Hello,

I know Shaarli has its own ban mechanism, but I prefer using fail2ban for being lower level and also because if someone is trying to bruteforce my Shaarli, he might also want to hack the rest of my website, so I prefer to ban the IP globally. Also, I'm using permanent and persistent bans (accross reboot or restart) which is not possible with Shaarli (not a problem, just let fail2ban do it, being its core business).

The only little thing that prevents users from using fail2ban with Shaarli log files out-of-the-box is simply the date format used in Shaarli log files.

The change is simple. In index.php file, in the logm function, change the line:
```
$t = strval(date('Y/m/d_H:i:s')).' - '.$_SERVER["REMOTE_ADDR"].' - '.strval($message)."\n";
```
to
```
$t = strval(date('Y/m/d H:i:s')).' - '.$_SERVER["REMOTE_ADDR"].' - '.strval($message)."\n";
```

That is simply removing the underscore between the Y/m/d and the H:i:s
With this slight change, fail2ban users will be happy to develop their own fail2ban regex while not having to adapt the fail2ban code to match yet another date template.

Keep up with the excellent work ! I love Shaarli :-)
Cheers,
Arno

**Comment by nicolasdanelon** [comment]
+1 to modify date. @Arno0x share your fail2ban regex !!

**Comment by Arno0x** [comment]
Sure, I should have added it in the first place :-)

Here is the whole shaarli-auth.conf filter to be created in the fail2ban/filter.d directory

$ cat /etc/fail2ban/filter.d/shaarli-auth.conf 
# Fail2Ban configuration file for shaarli application authentication
[INCLUDES]
before = common.conf
[Definition]
failregex = \s-\s<HOST>\s-\sLogin failed for user.*$
ignoreregex =

**Comment by ArthurHoaro** [comment]
No problem. You can submit a PR if you want, otherwise we'll do it later.

Thanks for the conf file. This belongs in the wiki. ;)

**Comment by Arno0x** [comment]
I'm not too much used to GitHub to do a 'PR' (no matter what it means :-) ) so I guess it can wait until you guys do it later.

Beware the fail2ban config file I submitted only works once the date format has been changed as I mentioned.

Cheers.
Arno

**Comment by virtualtam** [comment]
Thanks @Arno0x for opening this issue & sharing your fail2ban filter ;-)

I've added a `fail2ban` section to the [server configuration](https://github.com/shaarli/Shaarli/wiki/Server-configuration#fail2ban) page, feel free to add any relevant information!

**Comment by Arno0x** [comment]
The fail2ban filter alone is not sufficient. Might be worth adding a fail2ban **jail** example:
For instance, to permanently ban (*bantime = -1*) an IP after 3 failed attempt to login (*maxretry = 3*), edit the /etc/fail2ban/jail.conf file and add the following section:
```
[shaarli-auth]
enabled  = true
port     = https,http
filter   = shaarli-auth
logpath  = /var/www/path/to/shaarli/data/log.txt
maxretry = 3
bantime = -1
```
Please note that the *failregex* I mentioned in a previous post only works if the Shaarli date template matches one of the various ones fail2ban knows (which needs to be changed as explained in my first comment).

Thanks to the Shaarli community for providing and maintaining such a nice and nifty little tool. Really love it ! :-)

**Comment by virtualtam** [comment]
Thanks for the feedback; I've submitted a patch (aka PR - [Pull Request](https://help.github.com/articles/using-pull-requests/)) @ #438 and moved the fail2ban configuration examples to a page dedicated to [server security](https://github.com/shaarli/Shaarli/wiki/Server-security).

**Comment by ArthurHoaro** [comment]
Reopened regarding my comment in the PR.

**Comment by virtualtam** [comment]
Fixed, thanks for the post-review ;-)
