### ISSUE TITLE
Highlight quick notes/articles

### ISSUE THREAD

**Issue by Ginko-Aloe** [shaarli/Shaarli#439]
I think this issue is midway between #208 and #266 : 

The quick notes/article (linkless shaares) functionnality is a really nice feature of Shaarli (thx to our Godfather Sebsauvage) but how many times have you clicked on the title of a quick note only to find out there's no linked resource, just a nice full page of the note you've already read ?

So I think it could be enjoyable to highlight those lovely quick notes so we don't foolishly end up  wasting clicks.

This could be done by using a different background color on some element of the note somewhere in the CSS (maybe along with a js tweak to detect the linkless notes).

What do you think of this proposition ?

**Comment by nodiscc** [comment]
I think slightly changing the appearance of self-notes makes sense. A similar change has been proposed for `pricate` links in https://github.com/shaarli/Shaarli/issues/433. Yes it is something to consider for https://github.com/shaarli/Shaarli/issues/266

**Comment by ArthurHoaro** [comment]
I agree that self post should be recognizable. We'll see how if we wait #266 for this.

**Comment by ArthurHoaro** [comment]
Fixed by the new default template (different icon before the title).
