### ISSUE TITLE
404 error after editing a link

### ISSUE THREAD

**Issue by nodiscc** [shaarli/Shaarli#440]
How to reproduce:

 * Perform a tag search that returns results over multiple page (`?searchtags=mytag`)
 * **Navigate to page 2** (`?page=2&searchtags=mytag`)
 * Edit a link (`?edit_link=20140724_145616&x=9&y=8` <- btw I think there are useless xy params here)
 * Edit link info (in my test case I was changing the Private status)
 * Save
 * You are directed to `?page=2&amp;searchtags=mytag#O-71EA` and that url returns a 404 error

**Comment by nicolasdanelon** [comment]
Confirm.. bad HTMLentities or url encode somewhere
?page=2**&amp;amp;**searchterm=laravel#3tx57Q

**Comment by ArthurHoaro** [comment]
`escape()` [L1540](https://github.com/shaarli/Shaarli/blob/master/index.php#L1540). We probably can just remove the escape.

**Comment by ArthurHoaro** [comment]
About `x` and `y` GET params, it's actually an HTML feature: http://stackoverflow.com/a/745476/1484919.
