### ISSUE TITLE
Filtering search results by tags does not work

### ISSUE THREAD

**Issue by nodiscc** [shaarli/Shaarli#449]
How to reproduce:

 * Enter a plain text search term (eg. `tron`).
   * Search returns links containing the keyword as expected. (`/?searchterm=tron` returns 350 results. )
 * Click on a tag in the list (eg. `linux`).
   * You are directed to `?searchterm=tron&searchtags=linux` but the search results are the same as the previous search (350 results). Only the `searchterm` query is considered.
   * Search should return _only_ links matching `tron` _that are tagged `linux`_

**Comment by ArthurHoaro** [comment]
I'm guessing that's a regression introduced by link filter refactoring. I'll look into it.

**Comment by ArthurHoaro** [comment]
Now the question is, should we really do this:

> Search should return only links matching tron that are tagged linux

Or create a new tag search, filtering only the clicked tag. Note that if we do this, it can't be done the other way around (tag search then text) because if you enter a new search in one of the search field, it creates a new search (which make sense IMHO).

**Comment by kalvn** [comment]
I guess the behavior could be the one described by nodiscc but we should find a way to show precisely what filters are currently active. For tags it's fine, there's already those little blocks, but for search text there's nothing (except the fact that the text is displayed in the search field but it's not visible enough). So we could imagine a way of adding another block for the search term that we can easily remove (like tags and the little cross) to fall back on a tag-only research.

Don't hesitate to tell me if that isn't clear enough.

**Comment by ArthurHoaro** [comment]
>  but for search text there's nothing (except the fact that the text is displayed in the search field but it's not visible enough)

That's not true. 
![2016-01-29 11_59_33-shaarli_ the personal minimalist super-fast no-database delicious clone - dem](https://cloud.githubusercontent.com/assets/1962678/12673948/592a2ae2-c680-11e5-8e91-14d741aa9a42.png)

> that we can easily remove (like tags and the little cross) to fall back on a tag-only research.

Why not.

Anyway we can add a double search feature and see how it can be used in the UI.

**Comment by nodiscc** [comment]
Ah I forgot about the visual feedback for the current search. Yes, the current search indicator should display something like

x results for _tron_, tagged `[linux]`

**Comment by ArthurHoaro** [comment]
Crossed search is done. However it could be improved regarding the UI:

  * remove terms like we can do with tags.
  * search fields contains current search, but will reset the search if you add a term/tag. It feels awkward. No idea on this yet.

**Comment by nodiscc** [comment]
I think this can be closed and remaining points brought up in other issues, if needed. This particular bug is fixed as far as I'm concerned. Merci @ArthurHoaro
