### ISSUE TITLE
Tag cloud does not sort tags (fully) alphabetically

### ISSUE THREAD

**Issue by 8139david** [shaarli/Shaarli#456]
Well, mostly, tags seem to be sorted alphabetically.
BUT some randomness seems to be added here and there.
I would like to have at least the option that the tags be displayed (completely) alphabetically.
That's more logical when you're going through tags, wondering if one has been used.

![2016-02-02-red beard](https://cloud.githubusercontent.com/assets/11293408/12762748/fa1d0d2a-c9f0-11e5-9021-0eca371ef46c.jpg)

**Comment by alexisju** [comment]
Indeed, accented characters are not alphabetically sorted (é is after z)

**Comment by ArthurHoaro** [comment]
Also, uppercase tags are sorted before lowercase.tags.
