### ISSUE TITLE
PubSubHubbub support is currently dead code

### ISSUE THREAD

**Issue by ArthurHoaro** [shaarli/Shaarli#459]
It relies on a `publisher.php` file which isn't included with Shaarli's code. It is also marked as `[UNTESTED]` in the comments. We should either support it, or remove the dead code.
- [More info.](https://aldarone.fr/les-flux-rss-shaarli-et-pubsubhubbub/)
- [php-publisher](https://github.com/pubsubhubbub/php-publisher).

**Comment by nodiscc** [comment]
I'm in favor or removing it entirely, unless it is widely used on Shaarli instances. If someone is actively using PubSubHubbub with Shaarli please chime in.

**Comment by virtualtam** [comment]
+1 for removal

**Comment by Aldarone** [comment]
I was the one who asked for it and as far as I know I'm the only one using it.

I'd be ok if it were moved to a plugin (I could maintain it) but it would need two hooks : 

- After a link has been saved to notify the hub.
- In the header of atom/rss feed to insert pubsub discovery data.

I'm not familiar with the plugin system so I don't know if those hooks already exists.

**Comment by ArthurHoaro** [comment]
I'm fine with moving it to a plugin. Plugins doesn't support RSS feeds yet.

Depending on #273.
