### ISSUE TITLE
Handle storage of javascript: URIs

### ISSUE THREAD

**Issue by nodiscc** [shaarli/Shaarli#46]
Copied from https://github.com/sebsauvage/Shaarli/issues/174

At https://github.com/shaarli/Shaarli/blob/master/index.php#L1479, add `&& !startsWith($url,'javascript:')`

> This allows to pervent bookmarklets' URL to be prepended with http:// prefix.
That keeps the bookmarklet link functional and dragable "as is" to the browser's bookmarks bar.

**Comment by nodiscc** [comment]
Bookmarklets always open a small way for XSS, like the one presented at http://www.stealmylogin.com/ (scroll down for the bookmarklet). However running a bookmarklet from your Shaarli links _is no different_ than running it from your browser toolbar.

Basically when you're running "links" that run javascript code from your Shaarli OR your browser toolbar, you have to trust the code.

This is also easily mitigated by the [`X-Content-Security-Policy`](http://content-security-policy.com/) header, (eg. the _Steal my Login_ attack doesn't work on my server) which most browsers respect.

I think we should allow users to store bookmarklets as Shaarli links. The risk is more for visitors clicking on an untrusted link, or adding it to their bookmarks bar. Anyway this is a risk even from a simple HTML page.

<sub>[RequestPolicy](https://requestpolicycontinued.github.io/) is also a good way to prevent XSS/CSRF on sites that are improperly secured</sub>

**Comment by nodiscc** [comment]
Ongoing work in pull request https://github.com/shaarli/Shaarli/pull/119

**Comment by nicolasdanelon** [comment]
-1 to add javascript:**something**

**Comment by nodiscc** [comment]
@nicolasdanelon +1s an -1s without technical argumentation spams everyone subscribed to this issue (mail notification, RSS notification and Github notification). Please refrain in the future, thanks.

**Comment by nicolasdanelon** [comment]
ok, sorry.
is not a good practice for coding. developers shouldn't code like that and we shouldn't be agree with this kind of practices. -1

**Comment by e2jk** [comment]
@nicolasdanelon It's not Shaarli's job to influence "coding practices".
With HTML5 "apps", Firefox mobile and all, if you just take a "all JavaScript is bad" approach you haven't got a bright future in front of you.
Plus, this doesn't have anything to do with the developers of the websites, since this would be used primarily to store bookmarklets.
Sorry, not a convincing argument to me.

**Comment by nodiscc** [comment]
Copied from #119 

> I've just re-read a [bug report on the RequestPolicyContinued](https://github.com/RequestPolicyContinued/requestpolicy/issues/447) bug tracker. There are _a lot_ of existing URI schemes aside from `http: https: ftp: magnet:` (the linked bug report references `feed: mailto: magnet: mediasource: about: jar: gopher: UT2004: spotify: chrome-extension: floatnotes: greasemonkey: bank-id:` and mooore) and I think we should allow users to bookmark them.

> @e2jk has concerns about the security of this, and the workaround (popup) is IMHO not so good. 

> I propose allowing users to configure extra URI schemes they want to be able to store. Eg. a config array `$GLOBALS['config']['EXTRA_ALLOWED_URIS'] = array('javascript:', 'mailto:', mediasource');` and loop over this for `if (!startsWith($url,$allowed_uri)`.

> Would that that be ok?

**Comment by nodiscc** [comment]
Another solution is to have have an option/checkbox (heh) in the tools dialog, checked by default:

`[x] Only allow bookmarking http://, https:// and magnet: URIs`
