### ISSUE TITLE
Feature request: Add tags to RSS feed

### ISSUE THREAD

**Issue by nasser-torabzade** [shaarli/Shaarli#462]
Hi,
Is it possible to enable link tags in RSS output? I think it's quite useful to have them, because many feed reader/parsers can process tags and organize imported items accordingly.

thanks.

**Comment by nodiscc** [comment]
Tags are already present in the RSS feed. Example RSS entry:

```html
<item><title>COSTA RICA IN 4K 60fps (ULTRA HD) w/ Freefly Movi - YouTube</title><guid isPermaLink="false">https://my.domain.org/links/?riF_Sw</guid><link>https://www.youtube.com/watch?v=iNJdPyoqt8U</link><category domain="https://my.domain.org/links/">video</category>
<category domain="https://my.domain.org/links/">nature</category>
<category domain="https://my.domain.org/links/">photography</category>
<description><![CDATA[(<a href="https://my.domain.org/links/?riF_Sw">Permalink</a>)]]></description>
</item>
```

My RSS reader parses them just fine. Or is your problem unrelated?

**Comment by nasser-torabzade** [comment]
@nodiscc Yes you are right. My problem was not related to shaarli output, apparently my parser is not correctly processing them.

**Comment by nodiscc** [comment]
Nice you figured out. I can recommend [Tiny Tiny RSS](https://tt-rss.org/gitlab/fox/tt-rss/wikis/home) (web based) or [Liferea](https://lzone.de/liferea/) which are both excellent feed readers.
