### ISSUE TITLE
Blockquotes should be in italic

### ISSUE THREAD

**Issue by NerosTie** [shaarli/Shaarli#465]
With the markdown plugin activated, blockquotes should be displayed in italic.

(also, thank you for this plugin!)

**Comment by ArthurHoaro** [comment]
> With the markdown plugin activated, blockquotes should be displayed in italic.

Why?

**Comment by nodiscc** [comment]
Italic should be reserved to text actually using the markdown `_italic_` syntax. However I agree that text in blockquotes is currently not very well recognizable. Maybe adding `border-left-style: solid` to blockquotes (this is what Github does) would do the trick?

**Comment by ArthurHoaro** [comment]
I'm not sure to understand the problem here...

![2016-02-09 15_51_00-test title](https://cloud.githubusercontent.com/assets/1962678/12919598/2b0d9a90-cf45-11e5-84af-afba84fd3aaa.png)

**Comment by nodiscc** [comment]
Oops; for some reason I did not see this. I've restored proper brightness/contrast settings on my monitor and now everything is fine. I suggest closing this. @NerosTie is this ok?

**Comment by NerosTie** [comment]
In fact, quotes in italics are not as common as I thought. It's because I see a lot of blogs (mostly Wordpress, Ghost and Blogger) where quotes are in italics but in markdown syntax, they are not by default.

Sorry, my bad.
