### ISSUE TITLE
markdown: html encoding issue

### ISSUE THREAD

**Issue by jeekajoo** [shaarli/Shaarli#466]
Hi,
When using markdown plugin, I can see that for example `> | < "` is not well encoded.
```
\```bash
JENKINS_HOME=/mnt/jenkins/data
sed -i "s|^JENKINS_HOME=.*|JENKINS_HOME=$JENKINS_HOME|" /etc/default/jenkins
\```
```
(without `\`)
produces this:
```
JENKINS_HOME=/mnt/jenkins/data
sed -i &quot;s|^JENKINS_HOME=.*|JENKINS_HOME=$JENKINS_HOME|&quot; /etc/default/jenkins
```
Using shaarli master (`5369f04521c8ed5bf332b75311ca73b604df1097`).
I also tried the default raintpl template, no effect.

Thanks

**Comment by alexisju** [comment]
Indeed. And 4 spaces don't create code blocks (was working before with this md plugin)

**Comment by ArthurHoaro** [comment]
Thanks I'll look into it.

@alexisju it looks like a different issue.

**Comment by ArthurHoaro** [comment]
The problem here is that shaares descriptions are escaped for security matters, and the `<code>` HTML render the description as it is. I need to 'unescape' the HTML inside <code> blocks.

It looks like it's what is done in Github and Reddit.

**Comment by jeekajoo** [comment]
I confirm this is fixed.
Thanks much @ArthurHoaro !
