### ISSUE TITLE
Undefined index: plugins

### ISSUE THREAD

**Issue by nibreh** [shaarli/Shaarli#467]
When I am in plugin administration, `?do=pluginadmin` I've got this error:

> Undefined index: plugins in /var/www/legtux.org/users/nibreh/www/shaarli/index.php on line 1780

Working fine by the way

**Comment by ArthurHoaro** [comment]
This issue has been fixed in 091e2d139dfd35e1a0fbfef5c561b26af633dbd9 and will be shipped with Shaarli 0.6.4. Thanks for reporting it anyway. :)
