### ISSUE TITLE
Markdown: code blocks aren't created with spaces

### ISSUE THREAD

**Issue by ArthurHoaro** [shaarli/Shaarli#468]
@alexisju, about Markdown

> 4 spaces don't create code blocks (was working before with this md plugin)

Actually, only if it's at the start of the shaare, because spaces are deleted (for me at least, please confirm). I suspect a `trim()` somewhere.

**Comment by kalvn** [comment]
Also, just in case, you need to add an new line before and after the code line (or lines), otherwise it's not taken into account.

This won't work:

Dummy text
    $ cd /etc
    $ mkdir dummy
Other dummy text

But this will:

Dummy text

    $ cd /etc
    $ mkdir dummy

Other dummy text
