### ISSUE TITLE
Trouble on RSS link with HAProxy

### ISSUE THREAD

**Issue by theonlydoo** [shaarli/Shaarli#477]
https://dooby.fr/links/?

Hi, I don't know how Shaarli generates its RSS link but if you check on mine
![sans titre](https://cloud.githubusercontent.com/assets/1903124/13048862/216d2ff2-d3e9-11e5-8a6a-0decb4f2e6e8.png) it doesn't seem normal :)

**Comment by ArthurHoaro** [comment]
This relies on [server_url](https://github.com/shaarli/Shaarli/blob/master/application/HttpUtils.php#L101). I suspect a specific server configuration.

Can you `<?php var_dump($_SERVER);` in a temporary PHP file and display it in your browser. Give us at least:
  * SERVER_NAME
  * SERVER_PORT
  * SCRIPT_NAME
  * HTTP_X_FORWARDED_*

**Comment by theonlydoo** [comment]
Yep, here it is : 
```php
array(29) { ["HTTP_HOST"]=> string(8) "dooby.fr" ["HTTP_USER_AGENT"]=> string(76) "Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:44.0) Gecko/20100101 Firefox/44.0" ["HTTP_ACCEPT"]=> string(63) "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8" ["HTTP_ACCEPT_LANGUAGE"]=> string(14) "en-US,en;q=0.5" ["HTTP_ACCEPT_ENCODING"]=> string(17) "gzip, deflate, br" ["HTTP_DNT"]=> string(1) "1" ["HTTP_X_FORWARDED_PROTO"]=> string(12) "https, https" ["HTTP_X_FORWARDED_FOR"]=> string(15) "109.190.120.166" ["HTTP_CONNECTION"]=> string(5) "close" ["PATH"]=> string(28) "/usr/local/bin:/usr/bin:/bin" ["SERVER_SIGNATURE"]=> string(0) "" ["SERVER_SOFTWARE"]=> string(6) "Apache" ["SERVER_NAME"]=> string(8) "dooby.fr" ["SERVER_ADDR"]=> string(9) "127.0.0.1" ["SERVER_PORT"]=> string(2) "80" ["REMOTE_ADDR"]=> string(15) "109.190.120.166" ["DOCUMENT_ROOT"]=> string(15) "/var/www/temp" ["SERVER_ADMIN"]=> string(12) "doo@dooby.fr" ["SCRIPT_FILENAME"]=> string(30) "/var/www/temp/temp/index.php" ["REMOTE_PORT"]=> string(5) "34389" ["GATEWAY_INTERFACE"]=> string(7) "CGI/1.1" ["SERVER_PROTOCOL"]=> string(8) "HTTP/1.1" ["REQUEST_METHOD"]=> string(3) "GET" ["QUERY_STRING"]=> string(0) "" ["REQUEST_URI"]=> string(15) "/temp/index.php" ["SCRIPT_NAME"]=> string(15) "/temp/index.php" ["PHP_SELF"]=> string(15) "/temp/index.php" ["REQUEST_TIME_FLOAT"]=> float(1455549434.349) ["REQUEST_TIME"]=> int(1455549434) } 
```

**Comment by ArthurHoaro** [comment]
Thanks. That's it, the forwarded protocol is separated by a comma:

> HTTP_X_FORWARDED_PROTO: "https, https"

[Apparently](https://en.wikipedia.org/wiki/X-Forwarded-For#Format) it happens if you go through multiple reverse proxies. We need to handle those cases.

**Comment by theonlydoo** [comment]
Fun fact : i only go through one and only reverse !

it's HAProxy, and I have the directive `http-request set-header X-Forwarded-Proto https if  { ssl_fc }` enabled.

But it was inserting the header twice ...
```X-Forwarded-Proto: https.
X-Forwarded-Proto: https.
```

so I removed the potential duplicate directive and it fixed the issue :-) THX!

**Comment by ArthurHoaro** [comment]
Reopening since the syntax is valid.
