### ISSUE TITLE
PHP Fatal Error in Tag Cloud

### ISSUE THREAD

**Issue by Nh3xus** [shaarli/Shaarli#481]
Hi guys,

With the latest master.zip archive of Shaarli, the tag cloud page is completely blank.

Here's the output of the log "error_log" of Apache :
PHP Fatal error:  Call to a member function compare() on a non-object in /var/www/shaarli/index.php on line 1242

Server configuration :
Apache 2.4.16
PHP 5.4.45
Shaarli's folder is owned by apache:apache

Thanks.

**Comment by alexisju** [comment]
I can confirm that. Just look at : http://shaarlidemo.tuxfamily.org/Shaarli/?do=tagcloud

**Comment by ArthurHoaro** [comment]
That's weird. I don't [reproduce (`ae`/`aé`)](https://links.hoa.ro/?do=tagcloud) and it shouldn't be possible according [the doc](http://php.net/manual/en/collator.construct.php):

> ### Errors/Exceptions
> 
> Returns an "empty" object on error.

I'll give you a few tests to run later.

**Comment by alexisju** [comment]
However i dont have this issue on another instance...

**Comment by ArthurHoaro** [comment]
OK, I found the issue (thanks to @alexisju instance access):

> Locale string too long, should be no longer than 80 characters: U_ILLEGAL_ARGUMENT_ERROR

> string(170) "LC_CTYPE=C;LC_NUMERIC=C;LC_TIME=fr_FR.UTF-8;LC_COLLATE=C;LC_MONETARY=C;LC_MESSAGES=C;LC_PAPER=C;LC_NAME=C;LC_ADDRESS=C;LC_TELEPHONE=C;LC_MEASUREMENT=C;LC_IDENTIFICATION=C"

So the doc is apparently lying because that's not an empty object, but `NULL`. I'll run a few tests, but passing only `LC_COLLATE` might be enough.

**Comment by jeekajoo** [comment]
Hi,
As I'm using master, I reverted f1e96a0 to get around it.
Thanks

**Comment by ArthurHoaro** [comment]
It should be fixed now.

**Comment by jeekajoo** [comment]
Yes, indeed. Thanks @ArthurHoaro

**Comment by Nh3xus** [comment]
Works fine after updating from master.

Thanks @ArthurHoaro
