### ISSUE TITLE
Sortable tags list on tag cloud page

### ISSUE THREAD

**Issue by arnaudmm** [shaarli/Shaarli#483]
I did some custom dev to improve the tag view.

Basically you can display tags with two layout:
- the original tag cloud
- a simple list

Then you can also sort alpha or by number of tag occurence.

It looks like that, here with simple list layout and sorted by occurence:

http://screen.infomee.fr/80b8f48726c879253a77dc37678f5a90.png

If interested I could work on it to do a pull request!

**Comment by nodiscc** [comment]
Thanks, this is an idea to consider for the upcoming template rewrite: https://github.com/shaarli/Shaarli/issues/266. The current template will soon be EOL so I don't think your current patch will be merged, but keep watching #266.

Sorting tags (alpha/count) would be nice. Making the list filterable with a `Filter...` field at the top + live filtering displayed results would also be nice.

**Comment by virtualtam** [comment]
Additionally, it would be nice to be able to limit the cloud to `n` tags to improve readability by having a quick overview of the main tags.

**Comment by nodiscc** [comment]
Issue recap: Tag cloud page

 - [x] Display as tags cloud
    - [ ] Ability to limit display to `n` tags
 - [ ] Display as tags list
   - [ ] Ability to sort alphabetically
   - [ ] Ability to sort by number of tag occurences

**Comment by ArthurHoaro** [comment]
> Additionally, it would be nice to be able to limit the cloud to n tags to improve readability by having a quick overview of the main tags.

I'm not in favor of this. It would add another setting in the UI without any real benefit.
