### ISSUE TITLE
Tags on private links should be also private

### ISSUE THREAD

**Issue by arnaudmm** [shaarli/Shaarli#484]
Try to share a link in private and add some new tags...

The tag are listed in autocompletion and tag cloud and it could be a privacy issue don't you think?

Expected: tags only in private links does not appear in public tag list/auto completion tag list

**Comment by nodiscc** [comment]
Yes they should! Tag counters (numbers next to each tag) also allow deducing the number of private links for any tag.

Nice find, thanks.

**Comment by ArthurHoaro** [comment]
Which version are you using? I just tried and tags only present in private links aren't seeable when logged out ; either completion and tag cloud.

**Comment by nodiscc** [comment]
I don't have this issue anymore (maybe I was still logged in?). @arnaudmm can you re-test, while making sure you are logged out?

**Comment by arnaudmm** [comment]
You are right, my mistake, it's working great.

Sorry bad check from me guys
