### ISSUE TITLE
Are tags with different case considered the same?

### ISSUE THREAD

**Issue by kalvn** [shaarli/Shaarli#497]
I noticed a small inconsistency in the way tags are handled.

For example, in the search form, if I type "vpn", the autocompletion propose me two options: VPN and vpn (because for some links I put vpn, for some others I put VPN). But no matter which one I select, I'll get the same results (meaning that the search algorithm is case insensitive, which is perfect).

In that case, wouldn't it make sense to apply the same logic to the autocompletion, proposing only one option (the first found for example)?

**Comment by ArthurHoaro** [comment]
Yes. "Case duplicate" tags should be selected as one when retrieved from LinkDB. Note that it doesn't mean that tags should be saved or displayed in lowercase.

**Comment by kalvn** [comment]
I absolutely agree on the last point.
