### ISSUE TITLE
Firefox Social Api broken

### ISSUE THREAD

**Issue by alexisju** [shaarli/Shaarli#498]
Firefox Social Api seems broken. Unable to add the service to Firefox clicking the button on Shaarli's Tools page.

Maybe this issue is linked how SSL is managed, or something else...

**Comment by ArthurHoaro** [comment]
On the [demo instance](https://shaarlidemo.tuxfamily.org/Shaarli/), in only works in HTTPS. Do you experience the same thing?
Also, which Firefox version are you sing? 44.0.2 here.

**Comment by alexisju** [comment]
Same : it works on https ; also Firefox 44.0.2

**Comment by ArthurHoaro** [comment]
HTTPS for FirefoxSocial activation is actually mandatory since Firefox 39. See https://bugzilla.mozilla.org/show_bug.cgi?id=1137900

**Comment by alexisju** [comment]
In fact, with my (outdated) SSL certificate, when i'm not logged to shaarli, i cannot use the Firefox API anymore to login before sharing a link.
The sharing popup doesn't open the login page (i just have the message : Firefox ne peut actuellement pas se connecter à -mon shaarli-). 
But if i'm logged before, the api works correctly.

I guess the issue is because my certificate is outdated (no issue with valid certificat even if it is selfsigned ie https://shaarlidemo.tuxfamily.org/Shaarli/ )
