### ISSUE TITLE
Change templates set through administration UI

### ISSUE THREAD

**Issue by ArthurHoaro** [shaarli/Shaarli#502]
The objective for 0.8.x is to have:

```
tpl/
  -- default/
  -- custom1/
  -- custom2/
```

Adding a field to choose between one of these in the administration would be nice.

**Comment by alexisju** [comment]
Great :-)

**Comment by kalvn** [comment]
Yep, we just have to ensure that all the themes do implement this field in order to avoid for a user to be blocked on a theme and to be forced to modify the config file directly.

**Comment by nicolasdanelon** [comment]
:+1:

**Comment by virtualtam** [comment]
:+1:

**Comment by ArthurHoaro** [comment]
related to #22
