### ISSUE TITLE
Undefined index: HTTP_ACCEPT_LANGUAGE

### ISSUE THREAD

**Issue by mitsukarenai** [shaarli/Shaarli#503]
RSS/ATOM feed invalidation due to PHP notice before XML code:
`
<br />
<b>Notice</b>:  Undefined index: HTTP_ACCEPT_LANGUAGE in <b>../htdocs/links/index.php</b> on line <b>271</b><br />
`

Culprit line:
`autoLocale($_SERVER['HTTP_ACCEPT_LANGUAGE']); // Sniff browser language and set date format accordingly.`

→ never trust user input ! `$_SERVER['HTTP_ACCEPT_LANGUAGE']` can be nonset, for example to preserve browser privacy. I recommend using:

`if (isset($_SERVER['HTTP_ACCEPT_LANGUAGE'])) autoLocale($_SERVER['HTTP_ACCEPT_LANGUAGE']); // Sniff browser language and set date format accordingly.`

**Comment by ArthurHoaro** [comment]
Crap.

**Comment by ArthurHoaro** [comment]
Thanks for the report. I've submitted a PR to fix this. I'll wait a few day, just in case there are other bugs, and release a v0.6.5.

**Comment by ZatsuneNoMokou** [comment]
"Never trust user" basic dev rule xD
