### ISSUE TITLE
Regression: Atom Feed starts with html (error message).

### ISSUE THREAD

**Issue by mro** [shaarli/Shaarli#507]
related to #503 . Tested version 8710d4d (current master)

**Observed behaviour**: Atom feed isn't valid Atom xml, not even well-formed xml. (dependant on the webserver configuration):

See `test-atom-empty.sh`result at https://travis-ci.org/mro/Shaarli-API-test/jobs/112820514#L166:

```
<br />
<font size='1'><table class='xdebug-error xe-notice' dir='ltr' border='1' cellspacing='0' cellpadding='1'>
<tr><th align='left' bgcolor='#f57900' colspan="5"><span style='background-color: #cc0000; color: #fce94f; font-size: x-large;'>( ! )</span> Notice: Undefined index: HTTP_ACCEPT_LANGUAGE in /home/travis/build/mro/Shaarli-API-test/tmp/WebAppRoot/index.php on line <i>271</i></th></tr>
<tr><th align='left' bgcolor='#e9b96e' colspan='5'>Call Stack</th></tr>
<tr><th align='center' bgcolor='#eeeeec'>#</th><th align='left' bgcolor='#eeeeec'>Time</th><th align='left' bgcolor='#eeeeec'>Memory</th><th align='left' bgcolor='#eeeeec'>Function</th><th align='left' bgcolor='#eeeeec'>Location</th></tr>
<tr><td bgcolor='#eeeeec' align='center'>1</td><td bgcolor='#eeeeec' align='center'>0.0051</td><td bgcolor='#eeeeec' align='right'>1028736</td><td bgcolor='#eeeeec'>{main}(  )</td><td title='/home/travis/build/mro/Shaarli-API-test/tmp/WebAppRoot/index.php' bgcolor='#eeeeec'>../index.php<b>:</b>0</td></tr>
</table></font>
<?xml version="1.0" encoding="UTF-8"?><feed xmlns="http://www.w3.org/2005/Atom"><title>Review Shaarli</title><updated>2016-03-01T09:21:43+0100</updated><link rel="self" href="http://127.0.0.1:8000/?do=atom" /><author><name>http://127.0.0.1:8000/</name><uri>http://127.0.0.1:8000/</uri></author><id>http://127.0.0.1:8000/</id>
<entry><title> Shaarli: the personal, minimalist, super-fast, no-database delicious clone</title><link href="https://github.com/shaarli/Shaarli/wiki" /><id>http://127.0.0.1:8000/?e7W2bw</id><updated>2016-03-01T09:21:43+0100</updated><content type="html"><![CDATA[Welcome to Shaarli! This is your first public bookmark. To edit or delete me, you must first login.<br />
<br />
To learn how to use Shaarli, consult the link &quot;Help/documentation&quot; at the bottom of this page.<br />
<br />
You use the community supported version of the original Shaarli project, by Sebastien Sauvage.<br>(<a href="http://127.0.0.1:8000/?e7W2bw">Permalink</a>)]]></content>
<category scheme="http://127.0.0.1:8000/" term="opensource" />
<category scheme="http://127.0.0.1:8000/" term="software" />
</entry>
</feed><!-- Cached version of http://127.0.0.1:8000/?do=atom -->
```

**Expected behaviour**: Atom feed is valid atom xml.

**Comment by mro** [comment]
observed already in v0.6.4: https://travis-ci.org/mro/Shaarli-API-test/jobs/112802991#L166

**Comment by ArthurHoaro** [comment]
Yes this is the same issue as #503. I'll merge #504 soon to fix that.

**Comment by mro** [comment]
#504 doesn't fix it, I tested it: https://travis-ci.org/mro/Shaarli-API-test/jobs/112805214.

The issue isn't that there's a message telling about an error, but that there's debug (html) output at all – even without error message.

**Comment by mro** [comment]
what confirmatioon do you need?

**Comment by ArthurHoaro** [comment]
There shouldn't be any x-debug output if there is no error/warning. Could you get the content of the ATOM feed with this test?

Also, the Travis build failed on `tar` and `test-atom-empty.sh` doesn't contain any tar command. I don't know how your tests work, but are you sure this is related with our issue?

**Comment by mro** [comment]
yes. I'm sure it is related, yes, I get the atom result (see https://github.com/shaarli/Shaarli/issues/507#issue-137511419 and https://travis-ci.org/mro/Shaarli-API-test/jobs/112820513#L166 and https://travis-ci.org/mro/Shaarli-API-test/jobs/112820514#L166).

Why do you think the travis build failed on a `tar` command?  The word `tar` doesn't even appear on https://travis-ci.org/mro/Shaarli-API-test/jobs/112820514#L166

**Comment by ArthurHoaro** [comment]
I was answering to this message:

> #504 doesn't fix it, I tested it: https://travis-ci.org/mro/Shaarli-API-test/jobs/112805214.

So, in the Travis build:
```
Running test-atom-empty.sh 
gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now
ouch

The command "sh scripts/run-tests.sh" exited with 1.
```

The error message in your first comment is:

> Notice: Undefined index: HTTP_ACCEPT_LANGUAGE

This warning is fixed by #504 (or should be). I've merged it, maybe you can rerun your test suite on `master`?

**Comment by mro** [comment]
just triggered a fresh build: https://travis-ci.org/mro/Shaarli-API-test/builds/112820479

**Comment by mro** [comment]
thx, look fine now! https://travis-ci.org/mro/Shaarli-API-test/jobs/112820514

I'm confused as https://travis-ci.org/mro/Shaarli-API-test/builds/112805158 failed on 408def1a07 which was supposed to be #504, right?

**Comment by ArthurHoaro** [comment]
Great! Yes, but looking at your other build, you probably forgot the `archive` keyword in your parameter.

**Comment by mro** [comment]
ah! so comes tar into play! Thx!
