### ISSUE TITLE
Bookmarklet doesn't work for github URLs

### ISSUE THREAD

**Issue by bdillahu** [shaarli/Shaarli#510]
Seems like the bookmarklet works great, unless you are on a github page, then nothing happens. I can go to "add link" and paste in the link and it's fine.

**Comment by ArthurHoaro** [comment]
Github and some other websites use Content Security Policy HTTP header which prevents bookmarklets to run.

https://github.com/blog/1477-content-security-policy#bookmarklets

If you want it to work everywhere, you can use the Firefox Social button, or third party Firefox/Chrome browser extension.

**Comment by Marsup** [comment]
It's also documented on https://github.com/shaarli/Shaarli/wiki/Sharing-button if you want to track browsers' issues.

**Comment by bdillahu** [comment]
Sorry, searched the Issues but not the Wiki... thanks for the info!
