### ISSUE TITLE
In Markdown syntax, it's hard to see an in-line code

### ISSUE THREAD

**Issue by NerosTie** [shaarli/Shaarli#511]
Here an example:

![shaarli_md](https://cloud.githubusercontent.com/assets/4572452/13532481/0896d234-e22c-11e5-853b-7d910d95b586.png)

"test" is an in-line code, but it's hard to see it.
With a grey background, like here on Github, it should be better, I think.

Ceci est un autre `test`. Voilà

**Comment by ArthurHoaro** [comment]
:+1:
