### ISSUE TITLE
FlickR links break the UI

### ISSUE THREAD

**Issue by ArthurHoaro** [shaarli/Shaarli#512]
Title discovery fails with flickr.com, breaking the UI.

Example: https://www.flickr.com/photos/westendfoto/25448713131/in/explore-2016-03-06/
Result on my instance:
![](http://i.imgur.com/qcbsTKk.png)
Demo instance:
![](http://i.imgur.com/P4pmngT.png)

**Comment by mro** [comment]
must be a regression, works fine over at https://github.com/mro/Shaarli/commit/b9c0e1632b8c2e41dd89d0a21c1ae708835f91d0, see https://links.mro.name/?n1lCVg

**Comment by ArthurHoaro** [comment]
Oh. Then the regression might come from 1557cefbd76257ceb830f65806831b490faf0acc.

**Comment by mro** [comment]
you are not a fan of fine-grained commit, are you?

**Comment by mro** [comment]
IMO would be a great candidate for a unit test.

**Comment by mro** [comment]
chapeau, très élégant!

**Comment by ArthurHoaro** [comment]
It would even have been better if I didn't break the regex in the first place, but thanks.
