### ISSUE TITLE
Add an option to show/hide RSS link

### ISSUE THREAD

**Issue by aurmil** [shaarli/Shaarli#517]
hello

I personnaly don't need the RSS feed so I would like to hide the RSS link in page.header.html
you could add an option as for SHOW_ATOM

thanks
regards

**Comment by ArthurHoaro** [comment]
Hi. This behavior will probably change with template rewriting in v0.8:

  * ATOM feed button as default.
  * An option to display to display the RSS feed instead,

**Comment by aurmil** [comment]
OK thanks for answering

so, + an option to display no button ;)

**Comment by nodiscc** [comment]
Uh ATOMS/RSS feeds are a core fetaure of Shaarli and I don't think there should be an option to hide them. This looks more like a job for a trimmed-down template. Else we would end up adding a hide/show option for every single button/item.

**Comment by aurmil** [comment]
OK, I personnaly don't need RSS or ATOM feeds (links are just for my own use) but I understand your point

**Comment by nodiscc** [comment]
Thank you for understanding; note that it might be a good idea to make each button easily hideable via CSS when rewriting the template (https://github.com/shaarli/Shaarli/issues/266) (eg. `<div id=rssbutton>` in template, let users add `#rssbutton { display: none }` to custom CSS)
