### ISSUE TITLE
wrong password

### ISSUE THREAD

**Issue by lolop-lj** [shaarli/Shaarli#519]
hi,

I just present my problem I find under official Shaarli too.
My last installation and comunity Shaarli and material theme.

I defined with a user password and the first connection works well.

But now I have a wrong login / password when I try to connect.
I tried different browser and different from machine to eliminate the problem of cookies.

I use php-fpm with nginx 7.0.4.

Nginx log me in:
```
192.168.1.18 - - [20 / Mar / 2016: 21: 13: 46 +0100] "POST / links / do = login HTTP / 1.1?" 200 89 "http://192.168.1.15/links/?do=login "" Mozilla / 5.0 (X11; Linux x86_64; rv: 45.0) Gecko / 20100101 Firefox / 45.0 "
192.168.1.18 - - [20 / Mar / 2016: 21: 13: 48 +0100] "GET / links / do = login HTTP / 1.1?" 200 8835 "http://192.168.1.15/links/?do=login "" Mozilla / 5.0 (X11; Linux x86_64; rv: 45.0) Gecko / 20100101 Firefox / 45.0 "
```

If you see an issue, thank you

**Comment by ArthurHoaro** [comment]
Hi,

  * Please take a look at https://github.com/shaarli/Shaarli/wiki/Troubleshooting#login
  * Are you behind a reverse proxy?
  * You can observe the cookies behavior through Chrome/Firefox debugger tool (Firefox needs to be [enabled](https://developer.mozilla.org/en-US/docs/Tools/Storage_Inspector)). Can you tell us what's going on here?

**Comment by lolop-lj** [comment]
Thank you for your help.

After passing under chromium and proper login, I searched some more.
And, it is about going through my domain login is correct.
I could also check with the android application.

So through the IP address that problem.
See for a new release?

**Comment by mro** [comment]
> my domain login

what's that – a *domain login*?

**Comment by ArthurHoaro** [comment]
I'm sorry but I don't understand you answer.

**Comment by lolop-lj** [comment]
Sorry I use google translation, I mean name of domain.
The query happens when I use lolop.no-ip.org/links but not 192.168.1.15/links.

**Comment by mro** [comment]
so you successfully can login to <http://lolop.no-ip.org/links> while failing to <http://192.168.1.15/links>? Sounds like different servers to me.

**Comment by ArthurHoaro** [comment]
Yes, that's because cookies are attached to a specific domain.
