### ISSUE TITLE
Bad font size format for tagcloud elements

### ISSUE THREAD

**Issue by alexisju** [shaarli/Shaarli#526]
The font size format generated by Shaarli seems to be invalid in most situations.

In most case, it is the default link/body's font size which is used instead a specific size proportional to the number of shares using the tag.

**Comment by ArthurHoaro** [comment]
I took a look at the demo, the font size is set with a comma separator (French number formatting). It's due to the fact that I've extended `autoLocale()` to all locale categories, and CSS seems to require a dot separator.
