### ISSUE TITLE
changed behaviour of non-logged-in GET /?do=configure

### ISSUE THREAD

**Issue by mro** [shaarli/Shaarli#533]
once it was a HTTP 404, now it is HTTP 200.

I found it when putting the (informal) API under test (https://github.com/mro/Shaarli-API-test/issues/5). The response code once was a theme independant indicator if the session is logged in or not.

I've got 3 questions which I would be grateful to get answered:

- is this changed behaviour intentional or a regression?
- of what benefit is the change?
- is there a corresponding issue/feature or was it ad-hoc?

Thanks in advance.

**Comment by mro** [comment]
working as expected: 890afc32 (stable) and 
broken: 11609d9f (current master)

**Comment by mro** [comment]
@ArthurHoaro Travis [build 121625186](https://travis-ci.org/mro/Shaarli-API-test/builds/121625186) suggests that 69c474b96612 is the breaking commit.

**Comment by ArthurHoaro** [comment]
Well... It's actually a bugfix I did along that big #515.

`do=configure` was long enough to be considered as a shaare smallhash, and then not found, which led to a 404. This trick didn't work with `do=tools` for example. I improved the regex a bit to avoid that behavior.

The current behavior is to display the link list. Although, I think it would be a better idea to display the login page in those cases.

**Comment by mro** [comment]
It was a 404 ever since, why should it become a 200 now? You mean you fixed a bug that was there from the first versions and didn't bother anybody, or did it? Was there an issue or other complaint about it? I'd call that a feature, by the time.

Is there an other theme independant indicator for `session isn't logged in` you would recommend (and was there in every shaarli version since and can remain)?

**Comment by mro** [comment]
> avoid that behavior.

why?

> display the login page in those cases

What usecases do you have in mind?

P.S.: I'm asking because changed semantics of the HTTP requests make it very hard for 3rd party tools like e.g. the ones mentioned at https://github.com/shaarli/Shaarli/wiki/Community-%26-Related-software#mobile-apps to reliably interact with a broad range of shaarlies out there.

So please let `?do=configure`, `?do=changepasswd` etc. return a `4**` again – be it 404 or 401.

**Comment by nodiscc** [comment]
> The current behavior is to display the link list. Although, I think it would be a better idea to display the login page in those cases.

Agreed

> So please let ?do=configure, ?do=changepasswd etc. return a 4** again – be it 404 or 401.

Would a 301/302 response (redirect to `/?`)do the trick?

**Comment by ArthurHoaro** [comment]
> I'd call that a feature

A minor bug that no one noticed or bother reporting isn't a feature, it's just a minor bug.

> What usecases do you have in mind?

Same use case as trying to access https://github.com/settings/profile while logged out.

So, if I understand you test if the user is logged in by checking `do=configure` HTTP status. I understand why this is annoying then.

> Is there an other theme independant indicator for session isn't logged in you would recommend (and was there in every shaarli version since and can remain)?

Reaching http://shaarli.tld/?post will return a HTTP 302 and always have been.

**Comment by mro** [comment]
> Reaching http://shaarli.tld/?post will return a HTTP 302 and always have been.

that'll be great. I'll check if it does so with a single request, i.e. without a token.

**Comment by mro** [comment]
> Reaching http://shaarli.tld/?post will return a HTTP 302 and always have been.

👎  returns a 200 and all versions ever did: https://travis-ci.org/mro/Shaarli-API-test/jobs/121894713#L234 as far as I can tell.

The test: https://github.com/mro/Shaarli-API-test/blob/f9253ea025b7b7bca4491aa66f506b7bac419352/tests/test-login-ok.sh#L29

**Comment by ArthurHoaro** [comment]
`--location` makes cURL follow redirections.

**Comment by mro** [comment]
indeed, my bad, `do=addlink` works like a charm, I'll re-test with `?post`. https://travis-ci.org/mro/Shaarli-API-test/builds/121897311

**Comment by mro** [comment]
thx! https://travis-ci.org/mro/Shaarli-API-test/builds/121898355
