### ISSUE TITLE
Missing thumbnails with Dailymotion

### ISSUE THREAD

**Issue by alexisju** [shaarli/Shaarli#543]
I know the plan is to generate thumbnails from a plugin (https://github.com/shaarli/Shaarli/issues/365) but for now, thumbnails from Dailymotion's videos seem broken.

**Comment by alexisju** [comment]
Same with TED talks videos. ie : https://www.ted.com/talks/larry_lessig_says_the_law_is_strangling_creativity?language=fr

**Comment by ArthurHoaro** [comment]
Fixed by #687
