### ISSUE TITLE
Private link icon overlaps with edit/delete ones

### ISSUE THREAD

**Issue by julienCXX** [shaarli/Shaarli#544]
Hello, I noticed that (at least with Firefox and Chromium on v0.6.5) the “key” icon appearing on the left of a private link overlaps with the icons for editing or deleting a link (when logged-in). The bug seems to appear when the link does not take enough height on the page, as illustrated here:

![shaarli-private-bug](https://cloud.githubusercontent.com/assets/6797542/14691332/ecb5d160-0750-11e6-8cec-c7b265396c2f.png)

**Comment by virtualtam** [comment]
Hi @julienCXX !

This is due to the `.linkeditbuttons` div using absolute positioning (see [inc/shaarli.css l.89](https://github.com/shaarli/Shaarli/blob/master/inc/shaarli.css#L89)), and could be fixed by constraining a minimum height on `.linkcontainer`.

**Comment by ArthurHoaro** [comment]
This will be fixed with templates rewriting or before if someone wants to provide a PR for this.

**Comment by ArthurHoaro** [comment]
Fixed by the new template.
