### ISSUE TITLE
[need help] I'm trying to add support for emojione but it fails

### ISSUE THREAD

**Issue by NerosTie** [shaarli/Shaarli#545]
Just like I did on my blog, I'm trying to add support for emojis on shaarli but the installation process seems to be different.

On the repo (https://github.com/Ranks/emojione) they say to do add this in the head:
```
<script src="https://cdn.jsdelivr.net/emojione/2.1.4/lib/js/emojione.min.js"></script>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/emojione/2.1.4/assets/css/emojione.min.css"/>
```

I added this in `includes.html` but it has no effect.

But if I use the same process than my blog, it doesn't work either.

In `includes.html`: 

```
<link rel="stylesheet" href="emojione.css" />
```

In `page.footer.html` (at the end):

```
<script src="https://cdn.jsdelivr.net/emojione/2.1.4/lib/js/emojione.min.js"></script>
<script type="text/javascript"> emojione.imageType = 'svg'; </script>
<script src="emojione.js"></script>
```

emojione.css:
```
img.emojione {  
  margin: 0px !important;
  display: inline !important;
  padding: 0px;
  position: static;
  -webkit-transform: none;
  -moz-transform: none;
  -ms-transform: none;
  tranform: none;
  height: 1em;
  width: 1em;
  vertical-align: -0.15em;
}
```

emojione.js:
```
var posts = document.querySelectorAll('.post-content, .post-title, h2, h1');
emojione.imagePathPNG = "https://cdn.jsdelivr.net/emojione/assets/png/";
Array.prototype.forEach.call(posts, function(el, i){
  var parsed = emojione.toImage(el.innerHTML);
  el.innerHTML = parsed;
});
```

Do you have an idea?
(also, it could be a good idea to have an add-on for code-injections in the head and the footer!)

**Comment by ArthurHoaro** [comment]
> (also, it could be a good idea to have an add-on for code-injections in the head and the footer!)

That's exactly what plugins are for: CSS [header](https://github.com/shaarli/Shaarli/blob/master/plugins/demo_plugin/demo_plugin.php#L64), JS [footer](https://github.com/shaarli/Shaarli/blob/master/plugins/demo_plugin/demo_plugin.php#L100).

Regarding your issue, I can't really help you, but it targets these elements : `.post-content, .post-title, h2, h1` ; which aren't used in Shaarli's default templates.

If you need help regarding plugins, feel free to ask.

**Comment by NerosTie** [comment]
Thank you @ArthurHoaro! I have something that works!

emojione.ccs:
```
img.emojione {  
  display: inline-block;
  line-height: normal;
  font-size: inherit;
  vertical-align: middle;
  position: relative;
  width: 1.1em;
  height: 1.1em;
  top: -0.1em;
}
```
emojione.js:
```
var posts = document.querySelectorAll('.link-tag, .link-description, a.link-title');
emojione.imagePathPNG = "https://cdn.jsdelivr.net/emojione/assets/png/";
Array.prototype.forEach.call(posts, function(el, i){
  var parsed = emojione.toImage(el.innerHTML);
  el.innerHTML = parsed;
});
```

Now i'm trying to make a plugin from this...

**Comment by NerosTie** [comment]
How to translate this:
`<script type="text/javascript"> emojione.imageType = 'svg'; </script>
`
for the plugin manager?

**Comment by alexisju** [comment]
Feel free to share it with us here : https://github.com/shaarli/Shaarli/wiki/Plugin-list ;-)

**Comment by NerosTie** [comment]
@alexisju Is it ok with the external calls?

**Comment by alexisju** [comment]
I guess, but the easiest way is to link a dedicated git repository (easier to maintain and update for yourself and potential users).

**Comment by NerosTie** [comment]
@alexisju https://github.com/NerosTie/shaarli-plugin-emojione

Is it good? It's my first one :)

**Comment by alexisju** [comment]
I think it is better when the files are in the root of the folder, it is more easy to clone your repository. If you use subfolder we need to move the files before to be able to use your plugin.

**Comment by NerosTie** [comment]
Hm, I think you are right. My issue is that the plugin is named from the folder...

**Comment by alexisju** [comment]
Choose the right name (and/or change the pathes)

**Comment by NerosTie** [comment]
Let's call it `emojione` then! I will change that.

**Comment by alexisju** [comment]
Nice, works very well :-)

**Comment by alexisju** [comment]
Maybe you need to add some CSS (to the object class `.emojione`). No problem to have unicode emoji (ie 🌴) converted into image, but if you use shortname (ie `:beer:`), the emoji converted is very big.

Do you plan already some enhancements, like : 
 - ascii smilies conversion  (http://git.emojione.com/demos/2.1.4/ascii-smileys.html)
 - shortcode autocomplete  (http://git.emojione.com/demos/2.1.4/autocomplete.html) (without that we need to copy/paste unicode emojis from other websites or memorise shortcodes, what is not very convenient).

**Comment by NerosTie** [comment]
Ho I didn't know about all of that!

* unicode emoji, I will fix that ASAP, it's the most important.
* ascii smilies: I don't know, thing like that `:)` could be dangerous. So maybe in option (commented)
* shortcode autocomplete: this is cool! I will add this for sure. 

Also, if you are a Chrome/ium user, you have this addon: https://chrome.google.com/webstore/detail/emoji-keyboard-2016-by-em/ipdjnhgkpapgippgcgkfcbpdpcgifncb?utm_source=chrome-app-launcher-info-dialog

If you are fastest than me, feel free to send a PR :rabbit:

**Comment by ArthurHoaro** [comment]
Thanks @NerosTie, it's always good to see a new plugin coming out! 

However, you guys might want to discuss details at https://github.com/NerosTie/emojione to avoid sending too much unrelated notifications here.
