### ISSUE TITLE
Tags with ASCII characters are not in tagcloud

### ISSUE THREAD

**Issue by NerosTie** [shaarli/Shaarli#546]
If I have a tag like this: `:)` or `:dog:` we can't find it in tagcloud.

It could be interesting to support it and it would bring a better compatibility with the plugin https://github.com/NerosTie/emojione

**Comment by ArthurHoaro** [comment]
I'm not sure what you're talking about. `:dog:` is displayed in the tagcloud using the demo:

![snapshot8](https://cloud.githubusercontent.com/assets/1962678/14860987/8870927a-0cab-11e6-9b31-ebbc13b01db3.png)

And you have emojis in [your tagcloud](http://links.neros.fr/?do=tagcloud).

**Comment by NerosTie** [comment]
Ho, you are right! What I wanted was lost in my ocean of tags.
Sorry, false alert!

**Comment by virtualtam** [comment]
@NerosTie better keep your :dog:s safe in the future :D
