### ISSUE TITLE
Timezone ID 'UTC/UTC' is invalid after fresh install

### ISSUE THREAD

**Issue by kalumkalac** [shaarli/Shaarli#547]
Hi,

I installed shaarli with Notice print on my web server (nginx / php-fpm)

The homepage is giving me : 
```
Notice: date_default_timezone_set(): Timezone ID 'UTC/UTC' is invalid in /usr/share/nginx/shaarli/data/config.php on line 6
```

This happen when I let timezone info to default UTC/UTC. When I choose another timezone, no errors are displayed.

**Comment by ArthurHoaro** [comment]
[UTC is a valid timezone](http://stackoverflow.com/questions/7587435/setting-timezone-to-utc-0-in-php). Someone in this thread mentioned a problem with Mac though. Anyway, the default configuration i just an attempt to prevent bad configured server to throw warnings, but:

   * you must define your timezone in your `php.ini`.
   * if you're using Shaarli in production, you should not display errors.

**Comment by kalumkalac** [comment]
Well, **'UTC'** is a valid timezone, while **'UTC/UTC'** is not.

```php
date_default_timezone_set('UTC'); # Correct
```
```php
date_default_timezone_set('UTC/UTC'); # Throws a notice
```

> if you're using Shaarli in production, you should not display errors.

I agree, but hiding an error don't make it disappear. It's not harmfull, yes, but still present.

**Comment by virtualtam** [comment]
The installer proposes two lists (Continent, City) to pick a timezone from. `UTC/UTC` is an internal workaround so we can span a single value (`UTC`) over those two lists, see https://github.com/shaarli/Shaarli/blob/master/application/TimeZone.php

Yet, there may be an actual issue with how this value is dealt with when saving user configuration after running the installer, so it's worth double-checking and reopening this issue if needed :)

**Comment by ArthurHoaro** [comment]
Oh I forgot about the installer. I thought you're timezone was set by [this](https://github.com/shaarli/Shaarli/blob/master/index.php#L19). We should probably investigate why you have `UTC/UTC` then.

**Comment by daks** [comment]
Hello,

I installed Shaarli for the first time today and I got the same problem, on Debian Jessie 64 (Vagrant), with Apache 2.4.10-10+deb8u4 and PHP 5.6.20+dfsg-0+deb8u1.
Reading this issue, I first edited /etc/php5/apache2/php.ini

    date.timezone = 'Europe/Paris'

reloaded Apache, but still the same error on Apache log. And browsing the app I see

    /** * Rename tags starting with a '-' to work with tag exclusion search. */ Method [ public method
    updateMethodRenameDashTags ] { @@ /var/www/shaarli/application/Updater.php 138 - 148 } An error 
    occurred while running the update exception 'IOException' with message 'Error accessing 
    data/datastore.php' in /var/www/shaarli/application/LinkDB.php:298 Stack trace: #0 /var/www/shaarli
    /application/LinkDB.php(323): LinkDB->writeDB() #1 /var/www/shaarli/application/Updater.php(146): 
    LinkDB->savedb('pagecache') #2 [internal function]: Updater->updateMethodRenameDashTags() #3 
    /var/www/shaarli/application/Updater.php(86): ReflectionMethod->invoke(Object(Updater)) #4 /var/www
    /shaarli/index.php(1107): Updater->update() #5 /var/www/shaarli/index.php(2591): renderPage() #6 
    {main} 

I then edited shaarli/data/config.php

    $GLOBALS['timezone'] = 'Europe/Paris';
    date_default_timezone_set('Europe/Paris');

Changing only the first line did not solve the problem, but both yes. The error disappears from log.
But not the error on the website. It appears when I log in. I'll look on the issues.

**Comment by ArthurHoaro** [comment]
Yes, the timezone is always force according to the settings. We should probably do it only if the default one is empty.
