### ISSUE TITLE
After first login: error about Updater.php

### ISSUE THREAD

**Issue by daks** [shaarli/Shaarli#548]
Hello,

I installed Shaarli for the first time today and I got a problem after login on the application.
Debian Jessie 64 on Vagrant, with Apache 2.4.10-10+deb8u4 and PHP 5.6.20+dfsg-0+deb8u1.

After installation, I browse the website and did the first configuration (creating a user). I can then browse the 'public' part of the application but when I log in I get this error

    /** * Rename tags starting with a '-' to work with tag exclusion search. */ Method [ public method
    updateMethodRenameDashTags ] { @@ /var/www/shaarli/application/Updater.php 138 - 148 } An error 
    occurred while running the update exception 'IOException' with message 'Error accessing 
    data/datastore.php' in /var/www/shaarli/application/LinkDB.php:298 Stack trace: #0 /var/www/shaarli
    /application/LinkDB.php(323): LinkDB->writeDB() #1 /var/www/shaarli/application/Updater.php(146): 
    LinkDB->savedb('pagecache') #2 [internal function]: Updater->updateMethodRenameDashTags() #3 
    /var/www/shaarli/application/Updater.php(86): ReflectionMethod->invoke(Object(Updater)) #4 /var/www
    /shaarli/index.php(1107): Updater->update() #5 /var/www/shaarli/index.php(2591): renderPage() #6 
    {main} 

Any idea about this problem?

Thanks.

**Comment by ArthurHoaro** [comment]
Hi,

It looks the file `data/datastore.php` isn't writable. Can you make sure that your web server has write permissions on this file?

**Comment by daks** [comment]
Okay the problem comes from permissions. I got 'fooled' by Vagrant which has its own way of handling user/group.
Thanks.
