### ISSUE TITLE
Make RSS "permalink" mode available through an option

### ISSUE THREAD

**Issue by nodiscc** [shaarli/Shaarli#55]
I just discovered adding the `permalink` parameter to the RSS feed URL switches the main URL for feed items between full URL (the address the link points to) and permalink (short URL that points to the shaarli item.

index.html, line 891:
```
    // $usepermalink : If true, use permalink instead of final link.
    // User just has to add 'permalink' in URL parameters. e.g. http://mysite.com/shaarli/?do=rss&permalinks
    $usepermalinks = isset($_GET['permalinks']);
```

Check the difference between https://telecom.dmz.se/links/?do=rss and https://telecom.dmz.se/links/?do=rss&permalinks

I think this should be toggleable via a config option (some people will prefer just sharing links, whereas other use Shaarli in a blog-like mode and will want the RSS links to point to their article). It should also be documented like other options.

**Comment by ArthurHoaro** [comment]
The PR is merged, and it's working so I suppose we can close this issue.
