### ISSUE TITLE
Cannot add link: Get error 412, probably mod_security issue

### ISSUE THREAD

**Issue by Tighbu** [shaarli/Shaarli#555]
Hi. Thanks to the devs for this. It looks really good!
I have installed Shaarli on Freehostia.com (shared hosting service) and imported links from Delicious. That's all okay, but when I try and add a new link - Either from the "+Shaar link" bookmarklet or from the "Add link" button on my Shaari web page I get this:
> 412 Error
> Your request got filtered out due to possible security issues.
> One or more things in your request were suspicious (defective request header, invalid cookies, bad parameters)
> If you think you did nothing wrong:
>     try again with a different browser
>     avoid any evil characters inside the request url
> If you are the owner of the website, you can consider revising the rules of the mod_security module or turning it off from your Web Hosting Control Panel.

I assume it's a mod_security problem and that I need to ask my hosting support to fix it. What exactly must I ask them to do?

**Comment by ArthurHoaro** [comment]
Wild guess: they're blocking GET parameters containing a URL.

  * Does it happen with all website? 
  * Do you have any more information in your log files? 
  * Can you add a link manually within Shaarli? 
-- 
Arthur Hoaro
http://hoa.ro
- Envoi mobile -

**Comment by Tighbu** [comment]
> Does it happen with all website?

The only pages I have found that I can add successully are those that are within the domain in which I'm hosting Shaarly. I.e. I've installed Shaarli in www.mydomain.com/shaarli. I can successfully add that page into Shaarli, and can also add www.mydomain.com and www.mydomain.com/anotherpage.html.

> Do you have any more information in your log files?

data/log.txt just shows that I logged in successfully

> Can you add a link manually within Shaarli?

What do you mean "manually"? Clicking the "+Shaar link" bookmarklet or the "Add link" button on my Shaari web page (and then entering an url) gives the error.

**Comment by ArthurHoaro** [comment]
It kinda confirm what I thought. They're apparently enforcing some sort of security policy to GET parameters. You should get in touch with them. There is not much we can do about it.

> What do you mean "manually"? 

Sorry I misread your first post.

**Comment by kalvn** [comment]
Apparently you can still turn off mod_security from your control panel. I don't know exactly what it implies though.

**Comment by Tighbu** [comment]
Thanks for the replies. 

Freehostia support tells me that mod_security can't be changed for free sites (like mine). Anybody know another free host where Shaarli will work or a public installation of Shaarli?

**Comment by ArthurHoaro** [comment]
Sorry that no one could provide an answer to your last question, but closing because this is unrelated to Shaarli.
