### ISSUE TITLE
Incorrect page redirection after session timeout relogin

### ISSUE THREAD

**Issue by julienCXX** [shaarli/Shaarli#561]
Hello,
I noticed that page redirection was not correct when adding a new link, if I have to log in again after a session timeout, and before entering the URL. To reproduce that bug:
- log in to your Shaarli instance
- invalidate your session (e.g. by deleting the associated cookie)
- click on the “Add link” button
- as your session has expired, you will be asked to log in again, do it
- you are redirected on the page used to edit a link’s contents (URL, title, description and tags), as if you were creating a note (i.e. adding a link with an empty URL), instead of the usual URL input field.

**Comment by ArthurHoaro** [comment]
I can't reproduce:
 
  * Go to `?do=addlink`
  * Enter `http://stuff.com`
  * Open logout in a new tab.
  * Click on "Add link"
  * Login

Result: I'm in `?post=http%3A%2F%2Fstuff.com` and the title is retrieved.

**Comment by julienCXX** [comment]
Actually, you have to go to `?do=addlink` *after* logging out. It evens happens if you did not log in first.

**Comment by ArthurHoaro** [comment]
Oh right! Confirmed. That's weird.
