### ISSUE TITLE
Redirection problem

### ISSUE THREAD

**Issue by emporeso2** [shaarli/Shaarli#564]
Hi all,
i have put a redirector (https://sourceforge.net/projects/noreferplz/) but all the links sent by shaarli are like this :
http://mysite.com/https%3A%2F%2Fgithub.com%2Fshaarli%2FShaarli

I don't know if the problem is made by shaarli or my rediector ?

Thanks for your help.

**Comment by ArthurHoaro** [comment]
I'm not sure to understand your problem, but I suppose you want to add 
```php
$GLOBALS['config']['REDIRECTOR_URLENCODE'] = false;
``` 

in `data/config.php`.

**Comment by emporeso2** [comment]
@ArthurHoaro , i tried but don't work ,even "true".

Iit work well in https://github.com/tontof/kriss_blog

I think that the problem come from shaarli ?

**Comment by ArthurHoaro** [comment]
Can you give more details on your problem: What are you trying to achieve? What's not working?

The redirector setting lets you prepend any URL before actual external links. For example, if you shaare `http://github.com`, and set the redirector to `http://anonym.to/?`, your link will be:

  * With URL encode: `http://anonym.to/?https%3A%2F%2Fgithub.com`
  * Without URL encode: `http://anonym.to/?https://github.com`

**Comment by emporeso2** [comment]
I'am ok with you this exactly what the redirector do , 
when i use it in another (kiss) script like  https://github.com/tontof/kriss_blog the redirection work good 
but in shaarli it does not work !

i tried $GLOBALS['config']['REDIRECTOR_URLENCODE'] = false; 
and 
$GLOBALS['config']['REDIRECTOR_URLENCODE'] = true;

**Comment by ArthurHoaro** [comment]
Again, can you explain what you mean by: *"it does not work"*?

**Comment by emporeso2** [comment]
i have an entry of https://github.com/shaarli/Shaarli then this redirection go the a 404 page :
http://mywebsite/myredirector/https%3A%2F%2Fgithub.com%2Fshaarli%2FShaarli

$GLOBALS['config']['REDIRECTOR_URLENCODE'] = false; 
or
$GLOBALS['config']['REDIRECTOR_URLENCODE'] = true;

send me this url http://mywebsite/myredirector/https%3A%2F%2Fgithub.com%2Fshaarli%2FShaarli

**Comment by ArthurHoaro** [comment]
Oh this option has been added recently, so you won't have it if you're using Shaarli v0.6.5. I've just released v0.7.0, you should update.

Just to make sure, what you want is your link to be `http://mywebsite/myredirector/https://github.com/shaarli/Shaarli`, right?

**Comment by emporeso2** [comment]
I'am trying the new version v0.7.0 ,i get this 


Fatal error: Using $this when not in object context in /mysite/data/config.php on line 2

**Comment by emporeso2** [comment]
Yeeees ArthurOaro it works fine.

ou said that this option was added in the last version but i 'don't find it ? and i put $GLOBALS['config']['REDIRECTOR_URLENCODE'] = false; in /data/config.php

**Comment by nodiscc** [comment]
you can find this option with its description https://github.com/shaarli/Shaarli/wiki/Shaarli-configuration#example-dataconfigphp

**Comment by ArthurHoaro** [comment]
Glad I could help.

**Comment by Draky50110** [comment]
Discovered this, why not link both options ?
If redirector is set, disable url encode ?

Same problem on #480 and thx to GitHub search, found help here :)

**Comment by ArthurHoaro** [comment]
Because some redirectors use URL encoded others don't.
