### ISSUE TITLE
Import/Export possibilities

### ISSUE THREAD

**Issue by daks** [shaarli/Shaarli#565]
Hello,

I'm evaluating Shaarli to use as a personal bookmark manager to replace an old web app I use now. It seems nice but I have some import/export requirements and I don't know if Shaarli can comply with them (as it don't use a database but stores all bookmarks in a cryptic format in datastore.php).

- import option: I have a mysql DB full of old bookmarks with standard data (url, date, tags) which I want to import into shaarli: what possibilities exists for me to do that?
- export option: I saw there is one in 'tools' but it's not complete (no tags), I want to be able to export ALL my data if I want to change the software I use

Thanks.

PS: I know a little dev (Python...) but not PHP and how to script it

**Comment by virtualtam** [comment]
Hi @daks ,

There are a couple solutions to convert a MySQL db to Shaarli bookmarks ;-)

**Solution 1 - using the Netscape bookmark format**
I'm currently working on refactoring import / export using the Netscape "format", more details no the following issues:
- https://github.com/shaarli/netscape-bookmark-parser/issues/5
- https://github.com/shaarli/Shaarli/issues/102
- https://github.com/shaarli/Shaarli/pull/554

This format holds the following metadata:
- URL
- title
- addition date
- tag list
- description
- private flag

So migrating your data from MySQL to Shaarli would require a bit of scripting to dump your existing links to a Netscape bookmark file, which Shaarli should be able to import if it's not too exotic.

**Solution 2 - converting data with a PHP script**
Shaarli handles its data as an associative array that is then serialized, so you could simply write a PHP script to generate such an array from SQL data, and dump it to a serialized PHP file.

Some examples on https://github.com/shaarli/Shaarli/wiki/Datastore-hacks

**Comment by daks** [comment]
Thanks for the pointers, I'll look at converting my DB to a netscape bookmark file. For the export, the snippet works well so it's good for me :)
