### ISSUE TITLE
Bulk operations

### ISSUE THREAD

**Issue by ckuethe** [shaarli/Shaarli#572]
It would be nice to reduce the click count for bulk operations, for example adding a tag to 20 links or deleting a bunch of bookmarks in one shot. I've written some CLI tools to give me that ability now, but having it in the main UI would be handy.

**Comment by virtualtam** [comment]
Hi @ckuethe !

Here are some related (open) issues:
- #317 - Suggestion: better tag renaming
- #137 - batch "add multiple links" feature
- #412 - Suggestion: Tag Groups / Bundles

Such improvements are planned along the tools & UI refactoring (#266) ;-)

**Comment by ArthurHoaro** [comment]
* #644 - Bulk deletion

**Comment by philipp-r** [comment]
This was also suggested here: https://github.com/sebsauvage/Shaarli/issues/61
Would be very cool ;)

**Comment by nodiscc** [comment]
Most suggestions/feature requests listed here are now implemented, only https://github.com/shaarli/Shaarli/issues/412 remains and it's in the backlog/more information is needed.

This is the last issue in the 0.12.2 milestone, should we close it? Then we should be set for a new release.

**Comment by ArthurHoaro** [comment]
Yes I agree, let's close this, and we should release a new version as soon as we have time to do so.
