### ISSUE TITLE
How to upgrade

### ISSUE THREAD

**Issue by urza** [shaarli/Shaarli#575]
Hi,
sorry for stupid question, but I can't find instructions how to upgrade and I dont want to risk loosing data.

Should I just download latest release and overwrite everything in my shaarli folder?

Thanks

**Comment by ArthurHoaro** [comment]
Save your `data/` folder first, but this should work, yes.

**Comment by virtualtam** [comment]
Maybe we could also rename [Upgrade from original sebsauvage Shaarli](https://github.com/shaarli/Shaarli/wiki/Upgrade-from-original-sebsauvage-Shaarli) to _Upgrading Shaarli_, elaborate a bit the upgrade process (e.g. update from Git vs. update from Shaarli release archives) and make it more visible from the README / wiki home page?

**Comment by ArthurHoaro** [comment]
Yes, that's the second time we get this question, so there is probably something to do with the docs.

**Comment by virtualtam** [comment]
I've created the [Update and migration](https://github.com/shaarli/Shaarli/wiki/Upgrade-and-migration) page, please let me know what you think of it ;-)

**Comment by ArthurHoaro** [comment]
Great! 

@urza Please let us know if you were able to upgrade your instance.

**Comment by urza** [comment]
It is excellent.  Thank you very much.

**Comment by virtualtam** [comment]
You're welcome :)
