### ISSUE TITLE
Unable to use firefox bookmarklet to bookmark github repos

### ISSUE THREAD

**Issue by ckuethe** [shaarli/Shaarli#577]
Browser console contains a security error:

    Content Security Policy: The page's settings blocked the loading of a resource at self ("script-src https://assets-cdn.github.com").

It's not clear to me how to make that go away.
Firefox 46.0.1, Shaarli is being served over https

**Comment by ArthurHoaro** [comment]
See https://github.com/shaarli/Shaarli/wiki/Sharing-button#troubleshooting-the-bookmarklet-doesnt-work-with-a-few-website-eg-githubcom

You can try the firefox social button, or the 3rd party firefox plugin.
