### ISSUE TITLE
Ability to include the character "&" within links

### ISSUE THREAD

**Issue by n00b12345** [shaarli/Shaarli#578]
Currently if I were to use a link such as "http://localhost/shaarli/?post=xyz**&**abc.com" to add a link to Shaarli, anything beyond the "&" would be ignored. 

Could there be a workaround for this?

**Comment by nodiscc** [comment]
What would be the part after the `&` character? You mean the _domain name_ would be `xyz&abc.com`? (then it would be [invalid](https://stackoverflow.com/questions/7111881/what-are-the-allowed-characters-in-a-sub-domain)). Do you have an example page where this is broken?

**Comment by n00b12345** [comment]
@nodiscc Eg. This link: http://well.blogs.nytimes.com/2016/05/02/a-shocking-way-really-to-break-bad-habits/?smid=tw-nytimes&smtyp=cur

Only the part before the & gets saved if I were to use http://localhost/shaarli/?post=URL

**Comment by nodiscc** [comment]
It works for me:

![worksforme.png](https://cloud.githubusercontent.com/assets/3950390/15450066/3aae13f2-1f91-11e6-89ba-d8a68785012a.png)

@n00b12345 May be related to your hosting provider filtering out URL parameters? Do you host Shaarli on your home server/shared hosting/...? Does this problem happen when

 * Using the bookmarklet?
 * Using the `Add Link` button?
 * Using the Firefox Share button?

**Comment by n00b12345** [comment]
@nodiscc I use Shaarli on a local host. (Raspberry Pi)

I'm using an app called Workflow (iOS) which will automatically add links from a webpage to Shaarli. The advantage of using it instead of the bookmarklet is that I don't need to be in Safari and I don't need to open links to save them. 

Finally, just one last request so that I know the problem is entirely at my end. 

Could you see if this link gets saved in its entirety? 

http://www.audible.com/cloud-player?ref_=audlib-cp-launch&asin=B003WRG8DQ

**Comment by n00b12345** [comment]
I'm using the localhost/shaarli/?post=URL format. If possible could you try saving the links using this method?

**Comment by ArthurHoaro** [comment]
The URL provided in `?post=` needs to be encoded. Your browser is doing it automatically when you're using the form, but you may need to do it manually with your app.

Example:
`http://localhost.localdomain:8080/?post=http%3A%2F%2Fwww.audible.com%2Fcloud-player%3Fref_%3Daudlib-cp-launch%26asin%3DB003WRG8DQ`

**Comment by n00b12345** [comment]
@ArthurHoaro you sir are awesome! Did I say you're awesome? You're awesome. 

Thank you **so** much. You have no idea how many hours of labour you managed to reduce.
