### ISSUE TITLE
Check the HTTP Content-Type header before fetching remote file contents

### ISSUE THREAD

**Issue by nodiscc** [shaarli/Shaarli#579]
https://github.com/shaarli/Shaarli/blob/master/application/HttpUtils.php#L57

https://gitter.im/shaarli/Shaarli:

> nodiscc: Hi when doing ?do=addlink, entering an URL and pressing the Add link button Shaarli first downloads the document and tries to parse and extract the title from the document. This causes a serious lag when the target URL is a multi-megabyte PDF document, for example (reproducible with https://debian-handbook.info/download/stable/debian-handbook.pdf). 
> Shouldn't we try to 1. first get the HTTP Content-Type header (in this case application/pdf) 2. decide if we should download the whole document for parsing? As far as I know only makes sense to download image/\* (for thumbnail generation) and text/*documents.
> 
> virtualtam: @nodiscc this should be doable by first emitting an HTTP HEAD request (instead of GET), see https://www.w3.org/Protocols/rfc2616/rfc2616-sec9.html (section 9.4)
> the corresponding PHP function is http://php.net/manual/en/function.get-headers.php , to which the HEAD method has to be passed explicilty (as it defaults to... GET O_o)
> 
> ArthurHoaro: We currently only get the header first. Then if Shaarli gets a 200 response we download the page to determine the title and charset. Maybe we can add an option to disable title retrieving to speed up the process.

**Comment by ArthurHoaro** [comment]
We now use cURL to retrieve remote content, and we no longer make an extra request to get metadata. I suggest that we just add a filter function based on URL string (exclude `.pdf`, `.png`, etc.). Simple, but efficient.
