### ISSUE TITLE
'Add Note' bookmarklet should copy selected text to the note description

### ISSUE THREAD

**Issue by nodiscc** [shaarli/Shaarli#580]
- Improves ability to shares quotes, snippets, etc.
- Consistent with 'Add link' bookmarklet behavior.

**Comment by ArthurHoaro** [comment]
@nodiscc Are you still willing to work on this? Do you want to push to the milestone?

**Comment by nodiscc** [comment]
Sorry I totally forgot about this :/ Moving to 0.9.1

**Comment by philipp-r** [comment]
This is the bookmarklet that I'm currently using to add notes:

```
javascript:(
  function(){
    var%20url%20=%20location.href;var%20title%20=%20document.title%20||%20url;window.open(
      'https://example.com/?private=1&post='+
      '&description='%20+%20encodeURIComponent(document.getSelection())+
      '&source=bookmarklet',
      '_blank','menubar=no,height=390,width=600,toolbar=no,scrollbars=no,status=no,dialog=1'
    );
  }
)();
``` 

I will create a pull request and add this code to `tools.html`.
