### ISSUE TITLE
Unable to disable qrcode plugin

### ISSUE THREAD

**Issue by wouaibe** [shaarli/Shaarli#581]
Even if the qrcode plugin is disabled in plugins administration page... it already appear.

**Comment by nodiscc** [comment]
You may need to clear the contents of the `tmp/` directory and/or restart your webserver (if you have php-apc or another PHP cache/accelerator). Does this fix your problem?

**Comment by wouaibe** [comment]
No, it doesn't fix.
I cleared all .rtpl.php files in tmp/ directory but i don't have access to the webserver.

**Comment by ArthurHoaro** [comment]
Which version of Shaarli are you using? Are you using the default theme?

**Comment by wouaibe** [comment]
The last version. Material Theme !
I disable the theme, and it finaly works well !
Sorry, the problem seems to come from the theme, not the app !
Thanks for your questions.
