### ISSUE TITLE
Improve IP ban file format

### ISSUE THREAD

**Issue by ArthurHoaro** [shaarli/Shaarli#587]
Banned IP are store and loaded as `$GLOBALS` in a PHP file. It would be a better practice not to load it as a global variable, and even better to store it in JSON format.

See https://github.com/shaarli/Shaarli/pull/570#discussion-diff-66160082

**Comment by mro** [comment]
for curiosity – why would json be superior to php storage?

**Comment by ArthurHoaro** [comment]
The main improvement here is to get rid of `$GLOBALS`. The following behavior is shows why it shouldn't be used.
```php
$foo = 'bar';
echo $GLOBALS['foo'];
// echoes bar
```

Now about the storing format, it's not that important. But PHP comes out with out of the box functions to store/read an array in JSON. It's a better option than having our own serializing functions.

**Comment by mro** [comment]
ic, thx.

**Comment by ArthurHoaro** [comment]
Fixed by #1273
