### ISSUE TITLE
Textarea shouldn't be static

### ISSUE THREAD

**Issue by NerosTie** [shaarli/Shaarli#589]
![screenshot_20160610_161830](https://cloud.githubusercontent.com/assets/4572452/15967230/19a54590-2f27-11e6-8b00-e5e82e018dc0.png)

As you can see on this screenshot, it's an issue when you have a large text. You have to scroll in a tiny box to see your text. Yes, in Chrome or Firefox, you can enlarge manually this box but I think it could be better if it was automatic.

**Comment by ArthurHoaro** [comment]
This is theme related and you're probably using Material theme. 

But it's a good idea for our theme refactoring #266.

**Comment by NerosTie** [comment]
Yes, I'm using the Material theme but it's the same thing with the default theme.

![screenshot_20160610_164817](https://cloud.githubusercontent.com/assets/4572452/15968181/2d08a100-2f2b-11e6-85fc-80b50693569c.png)

**Comment by ArthurHoaro** [comment]
Yep, but we try not to spend too much time on the current theme, since the new one is coming soon-*ish*.

**Comment by ArthurHoaro** [comment]
Fixed by the new template.
