### ISSUE TITLE
Thumbnails from Flickr can be huge!

### ISSUE THREAD

**Issue by NerosTie** [shaarli/Shaarli#590]
Unlike youtube, thumbnails from flickr are cached and sometime it can be an issue.
I don't know how it works but the thumbnail is a picture from the account and this picture can reach many MBs...

Exemple: 
With: https://www.flickr.com/photos/spacex
Result: http://links.neros.fr/?3oW57Q
(the thumbnail is more than 1MB, which is huge for my self-hosted server behind an ADSL connection)

I think that a better solution would be the avatar as a thumbnail.

**Comment by nodiscc** [comment]
A solution would be resizing the thumbnail to a sensible size (max 200px wide). Otherwise a generic thumbnailer implementation based on OpenGraph tags would also solve this (https://github.com/shaarli/Shaarli/pull/153 needs to be rewritten)

**Comment by ArthurHoaro** [comment]
Fixed by #687
