### ISSUE TITLE
can't login

### ISSUE THREAD

**Issue by dfear** [shaarli/Shaarli#595]
I can't login.

I have read the relevent section on https://github.com/shaarli/Shaarli/wiki/Troubleshooting. I have deleted the data/config.php file and created a new username and password. 

Everytime I try to login I get: wrong user/password

I have deleted and recreated the user account several times now and still can't login.

**Comment by virtualtam** [comment]
How is your Shaarli configured?
- dedicated / shared hosting?
- HTTP server?
    - https://github.com/shaarli/Shaarli/wiki/Server-requirements
    - https://github.com/shaarli/Shaarli/wiki/Server-configuration
- HTTP(s) proxy?
    - https://github.com/shaarli/Shaarli/wiki/Troubleshooting
- has the HTTP user/group been granted appropriate read/write permissions?
    - https://github.com/shaarli/Shaarli/wiki/Shaarli-configuration

**Comment by ArthurHoaro** [comment]
Are you behind a reverse proxy?

Make sure that the domain you're reaching is the same configured in your webserver, so the cookies are properly set:

![](https://i.imgur.com/slsqkAF.png)

Side note: it might be a good idea to just use sessions and get rid of cookie sessions.

**Comment by dfear** [comment]
I am not behind a proxy. I am on shared hosting. Has correct permissions.

**Comment by virtualtam** [comment]
In relation with @ArthurHoaro 's comment regarding the server domain: #519 - Wrong password

Some additional checks:
- which Shaarli version are you running? (e.g. Git + master branch vs stable archive)
- do you have access to the server's PHP logs? or to the HTTP server logs corresponding to your virtualhost (assuming apache2/httpd)?

**Comment by ArthurHoaro** [comment]
Closing due to lack of feedback. Feel free to reopen this issue if necessary.
