### ISSUE TITLE
Improve documentation

### ISSUE THREAD

**Issue by nodiscc** [shaarli/Shaarli#598]
Moving https://github.com/shaarli/Shaarli/wiki/TODO here
- [ ] add more screenshots
- [ ] improve developer documentation: storage architecture, classes and functions, security handling...
- [x] ~~add server configuration examples: lighthttpd~~ _WONTFIX_
- [x] Deduplicate/merge info from https://github.com/shaarli/Shaarli/blob/master/README.md

Other documentation related issues can be found at https://github.com/shaarli/Shaarli/labels/documentation

**Comment by virtualtam** [comment]
> add more screenshots

Could be worth adding a _Shaarli installation 101_ page with concise, step-by-step instructions on how to get Shaarli running under a common configuration (Debian, Apache, PHP 5.6). This guide could then point to the existing pages for further details.

>  improve developer documentation: storage architecture, classes and functions, security handling...

- code: there's a lot of inline (docstrings) documentation for code that has been refactored, i.e. everything under `application`
    - reference documentation can be generated using Doxygen: `make doxygen`
- maintainer/developer: some pages are dedicated to Shaarli dev and maintenance, improvements may happen there

> add server configuration examples: lighthttpd

I'll take care of this one ;-)

**Comment by virtualtam** [comment]
> lighthttpd

I'm not sure whether it's actually used to run Shaarli? Most setups might rely on Apache HTTPD, Nginx, or the Docker image behind a reverse proxy.

> more screenshots

It's actually unclear what Shaarli does by only reading the repository's README and the documentation's landing page. Both should provide information about the core feature(s) at a quick glance:

- concise description of the project (e.g. "Shaarli in a nutshell")
- a couple screenshots to see what the application looks like
- links to other documentation pages: Getting Started, Installation, etc.

**Comment by nodiscc** [comment]
>  a couple screenshots to see what the application looks like

[![](https://i.imgur.com/8wEBRSG.png)](https://i.imgur.com/WWPfSj0.png) [![](https://i.imgur.com/rrsjWYy.png)](https://i.imgur.com/TZzGHMs.png) [![](https://i.imgur.com/uICDOle.png)](https://i.imgur.com/27wYsbC.png) [![](https://i.imgur.com/KNvFGVB.png)](https://i.imgur.com/0f5faqw.png)
[![](https://i.imgur.com/tVvD3gH.png)](https://i.imgur.com/zGF4d6L.jpg) [![](https://i.imgur.com/8iRzHfe.png)](https://i.imgur.com/sfJJ6NT.png) [![](https://i.imgur.com/GjZGvIh.png)](https://i.imgur.com/QsedIuJ.png) [![](https://i.imgur.com/TFZ9PEq.png)](https://i.imgur.com/KdtF8Ll.png)
[![](https://i.imgur.com/IvlqXXK.png)](https://i.imgur.com/boaaibC.png) [![](https://i.imgur.com/nlETouG.png)](https://i.imgur.com/Ib9O7n3.png)

Are these ok?
