### ISSUE TITLE
Drop PHP 5.3/5.4 compatibility

### ISSUE THREAD

**Issue by ArthurHoaro** [shaarli/Shaarli#599]
Proposition: Shaarli 0.8.0 will require PHP 5.5. Old systems will have to run old Shaarli versions.

![](http://i.imgur.com/WxhrvSh.png)
- PHP 5.3 has reached end of life 2 years ago, I think it's time to drop its support in Shaarli.
- PHP 5.4: EOL ~1 year ago
- PHP 5.5 has just reached EOL, so we can probably wait for a while.

Major syntax or feature changes:
- Allow usage of shortened array syntax (`[]` instead of `array()`). :tada: 
- Class member access on instantiation, e.g. (new Foo)->bar(). 
- `empty()` supports arbitrary expressions.
- [Generators](http://php.net/manual/en/language.generators.overview.php).

And a bunch of stuff [5.4](http://php.net/releases/5_4_0.php) - [5.5](http://php.net/releases/5_5_0.php).

Also, I'd like to define a milestone now for using [PHP 5.6](http://php.net/releases/5_6_0.php), which is kinda PHP LTS, as a requirement. 0.10.0 might be a good idea, as it's the last one before 1.0.0 (for now).

**Comment by virtualtam** [comment]
+1
I'd rather plan it for a future release though (e.g. 0.9 or 0.10) so we can warn Shaarli users ahead of this change being effective

**Comment by ArthurHoaro** [comment]
OK. Depending on the time it takes to reach 0.9.0, we'll see if we use PHP 5.5 or 5.6.

**Comment by virtualtam** [comment]
Closed via https://github.com/shaarli/Shaarli/commit/423ab02846286f94276d21e38ca1e296646618bf
