### ISSUE TITLE
shaarli title missing

### ISSUE THREAD

**Issue by mro** [shaarli/Shaarli#600]
shaarli: https://github.com/shaarli/Shaarli/commit/b6e58bab8a7 (which is current master)

Seen via https://travis-ci.org/mro/Shaarli-API-test/builds/131254883 and manual, fresh installation.

    $ fgrep '"title":'  data/config.json.php 

doesn't display top left but rather just "Shaarli".

**Comment by mro** [comment]
thx, tests fine again: https://travis-ci.org/mro/Shaarli-API-test/builds/131254883

P.S.: I'm a bit puzzled by your habit of closing issues. I am used to (in professional work environments) that the reporter finally confirms the fix and closes the issue.

**Comment by ArthurHoaro** [comment]
Well, Github automatically closes the issue when the PR contains "fixes #issueNumber", so discussions generally happens in the PR. However, #601 wasn't linked here... maybe because I put it in the title.
