### ISSUE TITLE
Auto linking code?

### ISSUE THREAD

**Issue by k0nsl** [shaarli/Shaarli#606]
I took a cursory glance on the current code base to find the code which is responsible for turning ordinary text into links, i.e `https://k0nsl.org` would be turned into a link if I published a note on Shaarli.

I'm trying to find that code to see if it would be a better idea to replace it with `linkify`.

Any one who knows and can point me in the right direction?

**Comment by virtualtam** [comment]
The related description formatting functions can be found under [`application/LinkUtils.php`](https://github.com/shaarli/Shaarli/blob/master/application/LinkUtils.php), namely:
- [`text2clickable`](https://github.com/shaarli/Shaarli/blob/master/application/LinkUtils.php#L98)
- [`format_description`](https://github.com/shaarli/Shaarli/blob/master/application/LinkUtils.php#L160)

The rendered text can also be altered by plugin code, e.g. when enabling Markdown descriptions.

The current code is pretty simple, I'm not sure we would benefit from using a full-featured parsing library here.

**Comment by k0nsl** [comment]
Thank you @virtualtam for pointing me to the correct path, much appreciated!

Yeah, I have to agree after seeing the code that it's simple, but it works. I will not replace my forked Shaarli with [Linkify](http://soapbox.github.io/linkifyjs/) because the former is smaller in size and likely a better solution.
The only differences are that Linkify is made in JS and can parse e-mail addresses also, while the solution used by Shaarli is written in PHP.

**Comment by virtualtam** [comment]
There's also a PHP port of Linkify @ https://github.com/misd-service-development/php-linkify ;-)

**Comment by k0nsl** [comment]
Nice! But upon further inspection I think we should keep the current code as it's so lean. All it needs is adding support for e-mail addresses — although it is probably very rare that somebody writes a note which contains an e-mail address. But who knows.
