### ISSUE TITLE
'+Shaare link' button doesn't work for Github URLs

### ISSUE THREAD

**Issue by ossvirt** [shaarli/Shaarli#610]
Click on the +Shaare link button in Firefox on Ubuntu, and nothing happens. Click the button on any other site and the popup window works as expected.

**Comment by alexisju** [comment]
You probably need to log into Shaarli in http**s**.

Can you try?

**Comment by nodiscc** [comment]
Nope, it won't work

https://github.com/shaarli/Shaarli/issues/577
https://github.com/shaarli/Shaarli/issues/510

See See https://github.com/shaarli/Shaarli/wiki/Sharing-button#troubleshooting-the-bookmarklet-doesnt-work-with-a-few-website-eg-githubcom
