### ISSUE TITLE
Search: Http Error 500 when using PHP7

### ISSUE THREAD

**Issue by c0d1ng** [shaarli/Shaarli#614]
When using PHP 7.0.9 I am getting a HTTP ERROR 500 when I try to search for entries (Tag search and normal search).
Switching back to PHP 5.6.24 solved this issue.

**Comment by ArthurHoaro** [comment]
I can't reproduce. Do you have any details in your web server log?

**Comment by c0d1ng** [comment]
I am using tha latest stable version, v0.6.5.
Interestingly it now suddenly seems to work with PHP7, really no idea why.

**Comment by nodiscc** [comment]
Please reopen with server logs and/or PHP debug information if the problem persists.

**Comment by watschi** [comment]
I just set up Shaarli v0.8.4 and get this error using the searchbar or klicking any tag in the tag cloud.

I'm using php 7.0.15 on ubuntu 16.04, following is from the apache error-log

```
[Sat Mar 11 21:45:10.750906 2017] [:error] [pid 1283] [client 84.191.59.210:60467] PHP Fatal error:  Uncaught Error: Call to undefined function mb_convert_case() in /var/www/html/shaarli/application/LinkFilter.php:165\nStack trace:\n#0 /var/www/html/shaarli/application/LinkFilter.php(77): LinkFilter->filterFulltext('dies', false)\n#1 /var/www/html/shaarli/application/LinkDB.php(478): LinkFilter->filter('fulltext', 'dies', false, false)\n#2 /var/www/html/shaarli/index.php(1628): LinkDB->filterSearch(Array, false, false)\n#3 /var/www/html/shaarli/index.php(725): buildLinkList(Object(PageBuilder), Object(LinkDB), Object(ConfigManager), Object(PluginManager))\n#4 /var/www/html/shaarli/index.php(1597): showLinkList(Object(PageBuilder), Object(LinkDB), Object(ConfigManager), Object(PluginManager))\n#5 /var/www/html/shaarli/index.php(2219): renderPage(Object(ConfigManager), Object(PluginManager))\n#6 {main}\n  thrown in /var/www/html/shaarli/application/LinkFilter.php on line 165, referer: https://mydomain.net/shaarli/?
```

**Comment by ArthurHoaro** [comment]
Hi, 

You need php-mbstring extension. See requirements in the wiki. 
-- 
Arthur Hoaro

**Comment by virtualtam** [comment]
Hi @watschi, see:
- https://github.com/shaarli/Shaarli/wiki/Server-requirements
- https://github.com/shaarli/Shaarli/wiki/Server-configuration

Also, please open new issues instead of posting on year-old, closed issues (that we may not pay attention to) :)

**Comment by watschi** [comment]
Thanks installin php-mbstring fixed it. I didn't install it first because the distros mentioned in the requirements were pretty specific and ubuntu wasn't mentioned.

I thought I'd post here since it was exactly the same issue, I will open a new issue next time :)
