### ISSUE TITLE
IPAD Ios session wrong token error

### ISSUE THREAD

**Issue by bikb** [shaarli/Shaarli#615]
Hello,

when I use my Ipad with shaarli newest version I got Wrong token error messages all the time.
I have investigated the problem. When the following code is executed in index.php:

```
// Set default cookie expiration and path.
session_set_cookie_params($cookie['lifetime'], "domain.de".$cookiedir,"ssl.webpack.de");
// Set session parameters on server side.
// If the user does not access any page within this time, his/her session is considered expired.
define('INACTIVITY_TIMEOUT', 3600); // in seconds.
// Use cookies to store session.
ini_set('session.use_cookies', 1);
// Force cookies for session (phpsessionID forbidden in URL).
ini_set('session.use_only_cookies', 1);
// Prevent PHP form using sessionID in URL if cookies are disabled.
ini_set('session.use_trans_sid', false);
```

the session doesn't start correctly. But when I comment out the code all works fine.

You can debug it by inserting this code:

```
if (session_id() == '') {
    session_start();


if (!isset($_SESSION['counter'])) $_SESSION['counter']=0;
echo "Counter ".$_SESSION['counter']++." раз.<br>
<a href=\"https://domain.tld/shaarli/index.php\">reload</a>"; 

}
```

Best regards

**Comment by ArthurHoaro** [comment]
Does it only happens with your iPad?
Can you be more specific with what's happening: when do you get the error? are you able to login ? etc.

Cookies have to be attached to the domain you're visiting. Debugging with iOS might be challenging, this might help: http://apple.stackexchange.com/questions/75178/how-can-you-see-the-value-of-a-cookie-on-an-iphone.

Does your debug code mean that the session is reset?

**Comment by bikb** [comment]
Yes it only happens on my IPAD.
Additional information: I have used "OPENSHAARLI = true".
When I don't use openshaarli then there has to be done more to get it work!

Please can you use crossbrowsertesting.com for testing on a real IPAD?

I don't know exactly whats going wrong, but I think the code prior to session_start(); hinders the right session management.

**Comment by ArthurHoaro** [comment]
I can't reproduce your issue using their iPad node (iPad 2 / 4.3.3 (iOS?) - Safari 5.02). It probably comes from your configuration.

  * Do you reproduce the issue in the demo? 
    * http://shaarlidemo.tuxfamily.org/Shaarli/ 
    * Login: `demo`; Password: `demo`
  * What's your web server + version ?
  * Are you behind a reverse proxy ?

**Comment by bikb** [comment]
There is no error in the demo - it works. 
Yes I am behind a reverse proxy.
Can I email you the link and login data? Do you have a pgp key?

**Comment by ArthurHoaro** [comment]
Check out the [proxy doc part](https://github.com/shaarli/Shaarli/wiki/Server-configuration#proxies) and the related issues.

I can try to see if I see something odd... [GPG](https://0bin.hoa.ro/paste/AYe5mQML#7PxyfD8ryMhRmWTF3dPEdZkRzTyk11aJikB7-1QR6GG)

**Comment by ArthurHoaro** [comment]
Your mail host rejected my email because it uses PTR instead of SPF, and took a week to notify me... Anyway, here is what I said:

Hi @bikb,

So, I ran a few tests, and I was able to reproduce your issue (or at
least something isn't working).

  * index.php: not sure what you did there, it doesn't work anywhere (no cookie).
  * index_2.php: doesn't work on Safari only.

Using Safari the cookie is never set on your Shaarli, while it works on
the demo. I can't debug, but I did notice one difference: the cookie
path has a trailing slash on the demo, and not in your instance. That's
odd because we explicitly set the trailing slash line 82 (master branch).

Did you change anything in index_2.php?
Also, can you try to add « var_dump($_SERVER); » at the beginning of
index.php?

**Comment by bikb** [comment]
Hello,

sorry for the delay. Will help next days.

**Comment by bikb** [comment]
Here is the var_dump:

`["HTTP_HOST"]=> string(20) "domain.de" ["HTTP_X_REAL_IP"]=> string(13) "79.199.x.x" ["HTTP_X_FORWARDED_FOR"]=> string(28) "79.199.x.x, 79.199.x.x" ["HTTP_CONNECTION"]=> string(5) "close" ["HTTP_X_FORWARDED_HOST"]=> string(14) "ssl.webpack.de" ["HTTP_X_FORWARDED_SERVER"]=> string(14) "ssl.webpack.de" ["HTTP_VIA"]=> string(14) "ssl.webpack.de" ["HTTP_USER_AGENT"]=> string(77) "Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:47.0) Gecko/20100101 Firefox/47.0" ["HTTP_ACCEPT"]=> string(63) "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8" ["HTTP_ACCEPT_LANGUAGE"]=> string(23) "de,en-US;q=0.7,en;q=0.3" ["HTTP_ACCEPT_ENCODING"]=> string(17) "gzip, deflate, br" ["HTTP_COOKIE"]=> string(34) "shaarli=d1ldeu9ejounfc2mb4dmv9xxxx" ["HTTP_DNT"]=> string(1) "1" ["PATH"]=> string(46) "/bin:/usr/bin:/usr/ucb:/usr/bsd:/usr/local/bin" ["SERVER_SIGNATURE"]=> string(0) "" ["SERVER_SOFTWARE"]=> string(6) "Apache" ["SERVER_NAME"]=> string(20) "domain.de" ["SERVER_ADDR"]=> string(10) "127.0.0.55" ["SERVER_PORT"]=> string(2) "80" ["REMOTE_ADDR"]=> string(9) "127.0.0.1" ["DOCUMENT_ROOT"]=> string(46) "/is/htdocs/wp/path/" ["REQUEST_SCHEME"]=> string(4) "http" ["CONTEXT_PREFIX"]=> string(0) "" ["CONTEXT_DOCUMENT_ROOT"]=> string(46) "/is/htdocs/wp/path/" ["SERVER_ADMIN"]=> string(25) "email.com" ["SCRIPT_FILENAME"]=> string(70) "/path/index_2.php" ["REMOTE_PORT"]=> string(5) "46844" ["GATEWAY_INTERFACE"]=> string(7) "CGI/1.1" ["SERVER_PROTOCOL"]=> string(8) "HTTP/1.0" ["REQUEST_METHOD"]=> string(3) "GET" ["QUERY_STRING"]=> string(0) "" ["REQUEST_URI"]=> string(25) "/shaarli_open/index_2.php" ["SCRIPT_NAME"]=> string(25) "/shaarli_open/index_2.php" ["PHP_SELF"]=> string(25) "/shaarli_open/index_2.php" ["REQUEST_TIME_FLOAT"]=> float(1471976157.132) ["REQUEST_TIME"]=> int(1471976157) ["argv"]=> array(0) { } ["argc"]=> int(0) }`

index_2 mainly was changed here:

`//define('WEB_PATH', substr($_SERVER["REQUEST_URI"], 0, 1+strrpos($_SERVER["REQUEST_URI"], '/', 0)));
define('WEB_PATH', "https://ssl.webpack.de/domain.de/");`

**Comment by ArthurHoaro** [comment]
While I was able to reproduce, I have no idea what's causing the issue. Any help appreciated, especially with a native Safari access.

**Comment by ArthurHoaro** [comment]
Closing after a year of inactivity. Feel free to reopen with any additional info.
