### ISSUE TITLE
Feeds $self_link is wrong when Shaarli is in a subdirectory

### ISSUE THREAD

**Issue by Aldarone** [shaarli/Shaarli#629]
When Shaarli is not in the webroot, feed validators will give this error : http://validator.w3.org/feed/docs/warning/SelfDoesntMatchLocation.html

My Shaarli feed URL is https://tools.aldarone.fr/share/?do=rss but when looking at the source you can see that `$pageaddr` and `$_SERVER['REQUEST_URI']` contain both the `share/` part.

```
<atom:link rel="self" href="https://tools.aldarone.fr/share/share/?do=rss"  />
```

This is because `index_url($_SERVER)` returns `https://tools.aldarone.fr/share/` and `$_SERVER['REQUEST_URI']` equals `/share/?do=rss` : https://github.com/shaarli/Shaarli/blob/528a6f8a232c060faf024008e4f8a09b4aa8dabc/application/FeedBuilder.php#L127

I use nginx as a webserver (with PHP-fpm 5.6) but I can reproduce the bug with the built-in PHP 7.0 server and a fresh Shaarli install.

**Comment by ArthurHoaro** [comment]
Good catch, thanks!
