### ISSUE TITLE
Latest commits broke Shaarli

### ISSUE THREAD

**Issue by Jucgshu** [shaarli/Shaarli#639]
Hi guys,

Not sure what's going on, but I'm getting a blank page with latest commits.

Resetting to commit 085157c fixes the issue.

-j

---
Nginx 1.10.1
Php-fpm 7.0.9
Sqlite 3.14.0

**Comment by alexisju** [comment]
It is probably the introduction of `composer`, as dependency manager, which broke you install.

I am very perplex about this introduction into Shaarli. I think that just broke what make the succes and the interest of Shaarli :  no sql db and very easy to install on most web hosting (including shared hosting or very light servers).

**Comment by Jucgshu** [comment]
Mmh, I should have thought of that.

Anyway, all is working now, thanks :-)

**Comment by virtualtam** [comment]
cf #607 #613

@Jucgshu using `master` comes with some risks & responsibilities ;-)
- things may break
- the commit log is your best friend

@alexisju I get your point, but we're way past the time where Shaarli was a mere 1500-line PHP hack.

We need to move forwards and adopt proper software management tools to ease our development and release work, and make the codebase modular and easy to dive-in for newcomers, which entails:
- maintaining a proper documentation
- having a decent unitary test coverage
- following coding conventions
- using a _dependency management_ system to pin dependencies and avoid duplicating stuff everywhere (and being ashamed of it...)

Regarding this specific-point: _drag-and-drop Shaarli installs_, I've added a couple extra targets in #608 to the `Makefile`, that will enable us to generate, upload and provide full-featured Shaarli releases, i.e. containing Shaarli + third-party dependencies normally resolved through Composer.

This new release mode will be available and advertised starting with the `v0.8.x` series, so shared hosting users are not (too) impacted by the change.

Again, please check the following before any upgrade:
- the [commit log](https://github.com/shaarli/Shaarli/commits/master)
- the [release notes](https://github.com/shaarli/Shaarli/releases)
- the [roadmap](https://github.com/shaarli/Shaarli/issues/353)

**Comment by Marsup** [comment]
A quick question as I'm no php expert : would it be feasible or desirable to commit the result of composer into git ? Does composer download system-specific binaries ? From what I read it downloads everything into a vendor folder, if there's no roadblock you could commit that and still keep all the advantages you mentioned.

**Comment by virtualtam** [comment]
@Marsup discussion continued @ https://github.com/shaarli/Shaarli/issues/613 -  Use Composer to manage all 3rd-party PHP libraries
