### ISSUE TITLE
Fatal error: require_once(): Failed opening required 'shaarli/vendor/autoload.php' (include_path='.:/opt/sp/php7.0/lib/php') in shaarli/index.php on line 49

### ISSUE THREAD

**Issue by q2apro** [shaarli/Shaarli#640]
Just downloaded shaarli, put it on my server, opened the path, then immediately got: 

    Fatal error: require_once(): Failed opening required 'shaarli/vendor/autoload.php' (include_path='.:/opt/sp/php7.0/lib/php') in shaarli/index.php on line 49

In the [installation docs](https://github.com/shaarli/Shaarli/wiki/Download-and-Installation) there is nothing said about a vendor folder / autoload file.

---

Update: 

Just see that this file would be generated by running composer. Is there no pure-filebased installation? Without the need to SSH and run composer?

**Comment by q2apro** [comment]
I have just FTP-created a folder `vendor` and the file `autoload.php` inside. Now shaarli runs without problem.s

**Comment by nodiscc** [comment]
> Is there no pure-filebased installation? Without the need to SSH and run composer?

https://github.com/shaarli/Shaarli/wiki/Download-and-Installation
