### ISSUE TITLE
Resource: How to export from Scuttle and import to Shaarli 

### ISSUE THREAD

**Issue by q2apro** [shaarli/Shaarli#641]
Hi everyone, great work you have done with Shaarli. 

After years of using Scuttle, I thought it is time for a change. 

Unfortunately, Scuttle has no HTML export. And Shaarli has only an importer for SemanticScuttle. 

So I wrote the "bridge", an exporter/importer: https://github.com/q2apro/scuttle-to-shaarli

Hope that helps.

**Comment by nodiscc** [comment]
Thank you for sharing your program, I added it to the wiki at https://github.com/shaarli/Shaarli/wiki/Backup,-restore,-import-and-export#scuttle :+1:
