### ISSUE TITLE
Readme has broken link

### ISSUE THREAD

**Issue by fnorf** [shaarli/Shaarli#642]
https://github.com/shaarli/Shaarli/commit/ca089c5bad8ee0f85df571ffa0f0beba51fa4efc added a typo:

hhttps://github.com/shaarli/Shaarli/wiki/Download-and-Installation

should be

https://github.com/shaarli/Shaarli/wiki/Download-and-Installation

**Comment by virtualtam** [comment]
Thanks, fixed :)
