### ISSUE TITLE
Ability to set a default search

### ISSUE THREAD

**Issue by nodiscc** [shaarli/Shaarli#643]
For those who use Shaarli both as a personal bookmarking tool *and* as a link sharing tool, it would be nice to be able to set a custom search expression in Shaarli settings
  * eg. exclude links not relevant to most visitors `?searchtags=-software+-doc+-admin+-todo`
  * eg. only list certain tags by default `?searchtags=shared`

This search expression would be used 
 * when clicking the Shaarli logo
 * when accessing Shaarli without parameters (as a default search)

**Comment by ArthurHoaro** [comment]
> when clicking the Shaarli logo

That's already doable using the title link setting.

> when accessing Shaarli without parameters (as a default search)

This needs a bit of work. Also, it would make sense to have the same default homepage for visitor and logged in users, which doesn't cover your use case. 

I use Shaarli as a personal bookmarking and as link sharing tool, and I almost only use private/public to do so. Maybe another way to handle this is custom buttons, as mentioned in #359.

**Comment by nodiscc** [comment]
Alright the title link setting is a partial workaround, I'll try to workaround the default homepage using rewriterules. As you said it's preferable to have the same homepage for visitors and logged in users. Private links are not an option for since I want my technical bookmarks to be available publicly.

Closing for now.
