### ISSUE TITLE
Still a  syntax error with free.fr

### ISSUE THREAD

**Issue by vroc** [shaarli/Shaarli#652]
Hello!

I tried to upgrade from sebsauvage's shaarli to this one on free.fr account, but it shows me this

` Parse error: syntax error, unexpected '{' in /mnt/102/sdb/f/0/wh1tht/shaarli/index.php on line 84`

When I apply changes explained by sebsauvage on his wiki (rename to index.php5 or add .htaccess), but it still doesn't work

` Parse error: syntax error, unexpected T_FUNCTION in /mnt/102/sdb/f/0/wh1tht/shaarli/index.php5 on line 861`
 What can I do ?

**Comment by virtualtam** [comment]
Hi @vroc!

Sebsauvage's Shaarli version hasn't been updated for a while (~2 years?) so I doubt these installation instructions and hacks still apply to Shaarli Community releases ;-)

Here are some relevant wiki pages to guide you through installing/upgrading Shaarli:
- https://github.com/shaarli/Shaarli/wiki/Upgrade-and-migration#migrating-and-upgrading-from-sebsauvages-repository
- https://github.com/shaarli/Shaarli/wiki/Download-and-Installation
- https://github.com/shaarli/Shaarli/wiki/Server-requirements
- https://github.com/shaarli/Shaarli/wiki/Server-configuration

If you're unsure what to do, I'd recommend you:
- start with a fresh Shaarli Community installation, e.g. in another directory on your web server
- get it working
- migrate the data from your existing legacy Shaarli installation

Shaarli works without much trouble on _decent_ PHP configurations, so you shouldn't have to edit PHP scripts nor htaccess configuration...

**Comment by ArthurHoaro** [comment]
Also with a quick search it looks like free.fr has updated to PHP 5.6, so the original hacks aren't probably required anymore.

**Comment by ArthurHoaro** [comment]
Closing due to lack of feedback. Please reopen if you still encounter your issue.
