### ISSUE TITLE
Add a CHANGELOG.md & adopt a formatting convention for release notes

### ISSUE THREAD

**Issue by virtualtam** [shaarli/Shaarli#663]
See http://keepachangelog.com/en/0.3.0/

Proposition:
- adopt a formatting convention for our release notes
- provide a Markdown-formatted CHANGELOG with the full release history

This will help maintainers, users, plugin and template developers to:
- keep track of important changes happening on the Shaarli codebase and documentation
- get this information locally, without need to browse release notes on GitHub

As we're going towards major changes, I think it becomes important to know in a glance which features have been deprecated or removed, and where to find updated configuration/upgrade instructions.

I've already started to refactor pre-`v0.5.0` release notes, and wrote a [Python script](https://gist.github.com/virtualtam/58494bc32a0e76c0dd4db638846a3175) to programmatically generate a Markdown CHANGELOG from GitHub release notes so we have a starting point.

**Comment by ArthurHoaro** [comment]
OK, this format doesn't have too many constraints. :+1:

**Comment by virtualtam** [comment]
Cool, I'll update the remaining release notes and submit a PR with the resulting change log ;-)
