### ISSUE TITLE
Use ATOM instead of RSS

### ISSUE THREAD

**Issue by GreenLunar** [shaarli/Shaarli#675]
Apparently, RSS 2.0 is [copyrighted]; Atom is an open IETF [standard], which means that it is more likely to be subjected to new developments, in future, such as PubSubHubbub.

While RSS requires `description`, `link`, and `title`, ATOM requires `author`, `id`, `link`, `title`, and `updated`,

[copyrighted]: http://wayback.archive.org/web/20141015100359/http://atompub.org/2005/07/11/draft-ietf-atompub-format-10.html
[standard]: https://tools.ietf.org/html/rfc4287

**Comment by virtualtam** [comment]
Hi @GreenLunar !

Atom feeds have been around in Shaarli for a while, see:
- https://github.com/shaarli/Shaarli/wiki/Shaarli-configuration#feed
- https://github.com/shaarli/Shaarli/wiki/RSS-feeds

To enable the `Atom feed` link on the index page, edit `data/config.json.php` as follows:

```json
    "feed": {
        "rss_permalinks": true,
        "show_atom": true
    },
```

While RSS is currently proposed by default, future (likely post-v0.10.0) versions will feature Atom as the default feed.

**Comment by GreenLunar** [comment]
Thank you for the details!
