### ISSUE TITLE
[Apache 2.4 compliance]

### ISSUE THREAD

**Issue by theonlydoo** [shaarli/Shaarli#676]
Les vieilles directives `Allow` et `Deny` n'existent plus sur les distro récentes.

``` bash
# git diff
diff --git a/application/.htaccess b/application/.htaccess
--- a/application/.htaccess
+++ b/application/.htaccess
@@ -1,2 +1 @@
-Allow from none
-Deny from all
+Require all denied
```

**Comment by ArthurHoaro** [comment]
Does the `Require` directive have backward compatibility with previous Apache versions?

**Comment by theonlydoo** [comment]
I don't think so, but I wonder if there is a way to make an `If` statement to detect Apache current version.

**Comment by ArthurHoaro** [comment]
Yep, [using `mod_version`](http://stackoverflow.com/questions/10707186/detect-apache-version-in-apache-config). I've just checked, it's enabled by default on ArchLinux and CentOS packages, but I can't find it on Debian.

I suggest that we do something like that:
```
<IfModule mod_version.c>
  <IfVersion >= 2.4>
     Require all denied
  </IfVersion>
  <IfVersion < 2.4>
     Allow from none
     Deny from all
  </IfVersion>
</IfModule>

# Not sure about the syntax
<IfModule !mod_version.c>
    Require all denied
</IfModule>
```

**Comment by theonlydoo** [comment]
:+1: thank you :)
