### ISSUE TITLE
Errors by importing firefox bookmarks

### ISSUE THREAD

**Issue by hubitor** [shaarli/Shaarli#681]
Hi all,
I'm testing the Shaarli container on docker and I have tried to import my firefox bookmarks into it. The first time Shaarli was complaining about the file size (max 2 MB) - my file is 3.2 MB. I have changed some nginx and PHP settings like suggested here:
https://atulhost.com/fix-nginx-error-413-request-entity-too-large
Now Shaarli is complaining about unknown file format and nothing was imported.
Any ideas?

**Comment by ArthurHoaro** [comment]
Did you export your Firefox bookmarks as HTML? Do you have a more specific error, or server log?

> Shaarli was complaining about the file size (max 2 MB)

It might be a good idea to increase that limit in the nginx docker configuration.

**Comment by hubitor** [comment]
ArthurHoaro thanks for the response! 

> Did you export your Firefox bookmarks as HTML? 
Yes! I have also tried with Chrome bookmarks.

> Do you have a more specific error, or server log?
root@15a2ff871c77:/etc/nginx# cat /var/log/nginx/shaarli.error.log
2016/11/03 17:49:45 [error] 12#0: *4 open() "/var/www/shaarli/shaarli" failed (2: No such file or directory), client: 172.17.0.1, server: , request: "GET /shaarli HTTP/1.1", host: "localhost:8000"
2016/11/03 17:49:45 [error] 12#0: *4 open() "/var/www/shaarli/favicon.ico" failed (2: No such file or directory), client: 172.17.0.1, server: , request: "GET /favicon.ico HTTP/1.1", host: "localhost:8000", referrer: "http://localhost:8000/shaarli"
2016/11/03 18:04:29 [error] 12#0: *86 open() "/var/www/shaarli/favicon.ico" failed (2: No such file or directory), client: 172.17.0.1, server: , request: "GET /favicon.ico HTTP/1.1", host: "localhost:8000"
2016/11/03 18:22:13 [error] 12#0: *175 client intended to send too large body: 3191597 bytes, client: 172.17.0.1, server: , request: "POST /?do=import HTTP/1.1", host: "localhost:8000", referrer: "http://localhost:8000/?do=import"
2016/11/03 18:25:10 [error] 12#0: *182 client intended to send too large body: 3191597 bytes, client: 172.17.0.1, server: , request: "POST /?do=import HTTP/1.1", host: "localhost:8000", referrer: "http://localhost:8000/?do=import"

I have tried to import bookmarks again but there are no other errors in /var/log/nginx/shaarli.error.log. There were also no related errors in /var/log/nginx/error.log.

> It might be a good idea to increase that limit in the nginx docker configuration.
How can I do that?

**Comment by ArthurHoaro** [comment]
Thanks. Can you post the first lines of your import file?

> How can I do that?

I meant in Shaarli's preconfigured docker image, so you wouldn't have to manually change it. ping @virtualtam

**Comment by virtualtam** [comment]
Hi @hubitor !

Which Docker image are you using?
- there may be importing issues in the `stable` image as it points to Shaarli `v0.7.0`, which is anterior to bookmark import refactoring
- the `latest` image should work fine (aside the upload size limit)

I'll double-check the PHP+nginx configuration+docs over the weekend to see if there are other issues lurking :)

**Comment by hubitor** [comment]
@ArthurHoaro: 
> Can you post the first lines of your import file?
Here the first lines of the firefox bookmarks files:
<!DOCTYPE NETSCAPE-Bookmark-file-1>

<META HTTP-EQUIV="Content-Type" CONTENT="text/html; charset=UTF-8">
<TITLE>Bookmarks</TITLE>
<H1>Bookmarks Menu</H1>

<DL><p>
    <HR>    <HR>    <HR>    <HR>    <DT><H3 ADD_DATE="1227676976" LAST_MODIFIED="1478182950" PERSONAL_TOOLBAR_FOLDER="true">Bookmarks Toolbar</H3>
    <DD>Add bookmarks to this folder to see them displayed on the Bookmarks Toolbar
    <DL><p>
        <DT><A HREF="javascript:(function(){var%20a=window,b=document,c=encodeURIComponent,e=c(document.title),d=a.open('http://localhost:8888/index.php/apps/bookmarks/bookmarklet?output=popup&url='+c(b.location)+'&title='+e,'bkmk_popup','left='+((a.screenX||a.screenLeft)+10)+',top='+((a.screenY||a.screenTop)+10)+',height=400px,width=550px,resizable=1,alwaysRaised=1');a.setTimeout(function(){d.focus()},300);})();" ADD_DATE="1478182950" LAST_MODIFIED="1478182950">Add to ownCloud</A>
        <DT><A HREF="http://sourceforge.net/directory/os:linux/freshness:recently-updated/?q=dms" ADD_DATE="1381223821" LAST_MODIFIED="1381223821" ICON_URI="http://icon.xmarks.com/iuv2oz0q-l02" ICON="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAB5ElEQVQ4jZ3T0UuTURzG8fNfyJhjzrURWoRtc0599Z1uMtfeyZgYOlhvIwrMGYNB2+uMZILhLhY4wpUXgShof0B0mTGvKojA7urWu2Jt5br5dhHvC0LY8sDn5jnPj3POxRFCCCFpVdxzi/QnM21xzy0iaVWEPixpVfJ7Byy9eNOW/N4B+pxwKipycYfw+j5jq7v4/2FsdZfw+j5ycQenoiKcSorRlW3klW1Gz3AxdhurHMMeShhdp5JCOCIq0oPnZxrSnlF7/xGA428NI3dEVIQ9nGRoacvgUFJYpCgWKYotcJ3BfJVL1xLUG00j07v2cBLRHUrgy23iy23izW5Qe/cBfR1//Y68vMWPk1+nMr3fHUogbBOzeLMVvNkK44Wn/Gy1cI7HMQ+GuRBJ4c1W8OeeUG80jZ7ONjGL6ArM4MmUDYefvhinvXx9iCdTRr6/Qb3RPNXzZMp0BWYQVn8cV7qEK13i6t1HmH0hTP1B3NE/73alS0jZx9SOPhs9ndUfR1jkGH3za/TNrzFwr0TzpGXc4NXbI2PvbyxyDNE5MsWVO8Vz6RyZQpiHFS7fengu5mEFYfJN0qsW6L25/H/UAibfJELSqjimF+hJ5um5obUnmccxvXD6R3Z4gpgGQm3p8ASN4d+/wj4fIsK2OwAAAABJRU5ErkJggg==">Search Results for “dms”: SourceForge</A>
        <DT><A HREF="http://crosbymichael.com/advanced-docker-volumes.html" ADD_DATE="1477780448" LAST_MODIFIED="1477780448">Advanced Docker Volumes</A>

Here the first lines of the chrome bookmarks files:
<!DOCTYPE NETSCAPE-Bookmark-file-1>

<META HTTP-EQUIV="Content-Type" CONTENT="text/html; charset=UTF-8">
<TITLE>Bookmarks</TITLE>
<H1>Bookmarks</H1>
<DL><p>
    <DT><H3 ADD_DATE="1430738735" LAST_MODIFIED="1478196081" PERSONAL_TOOLBAR_FOLDER="true">Bookmarks bar</H3>
    <DL><p>
        <DT><A HREF="javascript:(function(){var%20url%20=%20location.href;var%20title%20=%20document.title%20||%20url;window.open('http:///?post='%20+%20encodeURIComponent(url)+'&title='%20+%20encodeURIComponent(title)+'&description='%20+%20encodeURIComponent(document.getSelection())+'&source=bookmarklet','_blank','menubar=no,height=390,width=600,toolbar=no,scrollbars=no,status=no,dialog=1');})();" ADD_DATE="1478196064">✚Shaare link</A>
        <DT><A HREF="http://localhost:8000/?private=1&post=" ADD_DATE="1478196081" ICON="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAADUklEQVQ4jX1TbWxTZRh93ve997aXrtvKtlbGbEfSkSEsYkaNyIeGIcIiGko2l0hgSOL+qDEmIiEm1hlRjCEhLiSQGEU3EtsffBjpEjYHdSvgMjdWWIwwkG3duo7etvS7vfd9/EFqIDE7P5/nOSdPTs4BWAT9PWjr70HbYjfk/4aD59FoafR1ZvVXdwpMJCy+6fuVtY4jAIQvJgaISAEAZub+7hzVduFPM4Bn5gBHE+9hKJTaiYgE0UUf59AiEREIIYS31KC8QPraxsNnNZvYntcVGvL31G6eYP43CSHYCi7idrtZUUAAACDk0WvuA7jUsAoa80SpymRFatV/FODQbf4r9eWygqSscx/Gta2EjHmgFZ4QeDAfdUaE628puRMNelm/9IZy0ZjSJJ7V0pE0qsawCiQgn15Z++FC360PLlyvVNefOeeqdHecIgUhHA6/Pcy/+O5G/DREkwtQUB85W292AKalNJASFKEKA8ol/mf0YoVxSVlzQ7mz+YVD7c+5TuEhMjbT29cdf/1lmilVd9u+EUy6GiScJiKRyDUtVH2wpIq3lZUbOuQSOZfFh5Xe6U46/PBX6nzqc6X+3icbBJ1YrghsOZtK3ecTsWEqsQm1TG8W6/gbfaWiHfOGSbsv1WVKRmI5kUksEBulSQRa4JRBDoB9+u7xO0ukiqa0mKoanP0ZL4eGmMTy0hbT/rhXO9JZabKsZUTUTt7+TL4ZHSHPlG+CV6vfUazqxmPuddZfAABgahCr09Hs8aPje/n23ww4HvT7x2Z/H2r2ibi736Iqufnk0PzZRJPXoH01sQeVufTXxSDSFncLs24ks6Ohq8q12BV4tmxrfnXF+pJvJz92RBOER9Q0a/c59HWlDu1F82v8x8lu9ISOtoSu4AoAQOpp9WgnG1EMwz+bp7NBHAmN8QN/vLTaO+cXtpn3FQ7bf5iPY5Zt7V1hvBT0QiIFfEq9b5OtGUsxiaRjhBSeZvUDr1j20Acsqr+ZCdC9de2kydB2YkPU2XzQ1uVzLN9Ck0wTbMuqWa2wJihF5NknyjR9DOWE89b+IL+7WSfoMzZc1Z8/X+Ope5/kYj1oSm6b2udfGNghEamwRny+y2639y5arCJcLvyvPLcBdQOAwuP7fwEQ9YtBVSLeigAAAABJRU5ErkJggg==">✚Add Note</A>
        <DT><A HREF="http://www.mozilla.com/en-US/firefox/central/" ADD_DATE="1432977607">Getting Started</A>
        <DT><A HREF="http://mongoosejs.com/" ADD_DATE="1432977607">Mongoose ODM v4.0.3</A>
        <DT><A HREF="http://sublime-text-unofficial-documentation.readthedocs.org/en/latest/reference/keyboard_shortcuts_win.html" ADD_DATE="1432977609">Keyboard Shortcuts - Windows/Linux — Sublime Text Unofficial Documentation</A>

**Comment by virtualtam** [comment]
PR #684 submitted to fix the favicon error & increase max upload size :)

@hubitor I think the remaining parsing error is due to the dumps containing links from your personal toolbar, among which the bookmarklets are causing parsing issues; could you try importing bookmark dumps that only contain actual links?

**Comment by hubitor** [comment]
Wow. Amazing job both of you! Thanks!

> I think the remaining parsing error is due to the dumps containing links from your personal toolbar, among which the bookmarklets are causing parsing issues; could you try importing bookmark dumps that only contain actual links?

@virtualtam: Understood, it makes sense.  I'll try again asap the latest version is on the docker hub.

**Comment by virtualtam** [comment]
PR merged, let me know if you stumble upon further import issues :)

**Comment by hubitor** [comment]
Thanks for the fix! I have tried to import again and I'm still getting errors about "Unknown token" and "Unknown file format". There was no error about file length. Like it was mentioned before it's probably because of the format of some links in my file. I have tried to remove them but I cannot really locate them. 

BTW. In the description on docker hub is still release v0.8.0.

**Comment by virtualtam** [comment]
> docker hub is still release v0.8.0

The `latest` Docker tag corresponds to our Git `master` branch: https://hub.docker.com/r/shaarli/shaarli/builds/

> still getting errors about "Unknown token"

Looks like an invalid POST form submission or Shaarli configuration issue; are you otherwise able to add links the standard way (Add Link button)?

> "Unknown file format"

If you find entries that prevent parsing/importing bookmarks, feel free to report them at https://github.com/shaarli/netscape-bookmark-parser as new issues, some may be worth investigating to improve the parser's robustness :)

I'll take a look to see whether it'd be easy to add support for dumps containing bookmarklets, e.g. trim anything that looks like a Javascript section and ignore them when parsing the file.

**Comment by hubitor** [comment]
> Looks like an invalid POST form submission or Shaarli configuration issue; are you otherwise able to add links the standard way (Add Link button)?

Add Link Button works fine.

> If you find entries that prevent parsing/importing bookmarks, feel free to report them at https://github.com/shaarli/netscape-bookmark-parser as new issues, some may be worth investigating to improve the parser's robustness :)

Thanks for the tip. Maybe I'll do that.

> I'll take a look to see whether it'd be easy to add support for dumps containing bookmarklets, e.g. trim anything that looks like a Javascript section and ignore them when parsing the file.

Great. Not sure if it's only because of the bookmarklets though. It would be good if we could locate what is causing the  error. Unfortunately I couldn't see something in the error logs.

**Comment by ArthurHoaro** [comment]
@virtualtam Maybe a good idea would be to add a debug log, line by line, in the parser.

**Comment by virtualtam** [comment]
Yup, there's definitely some room for improvement in terms of user feedback ;-)

**Comment by ArthurHoaro** [comment]
Hi @hubitor, we've added an import log to debug imports in the master branch.

You can use it by:

  - getting the master branch
  - running `composer install`
  - add this in `data/config.json.php`
```
"dev": {
  "debug": true
},
```
  - run your import
  - check out `data/import.date.log` file

Or you can wait for the next release if you prefer.

**Comment by nodiscc** [comment]
@hubitor Hi, do you still have this problem? If you are using the latest release, can you set 

```
"dev": {
  "debug": true
},
```

in `data/config.json.php`, run your import, and check `data/import.date.log` for errors?

> It would be good if we could locate what is causing the error.

If for some reason you can't run the new import logger, what I would do is split the HTML bookmarks export in multiple HTML files (depending on your number of bookmarks, ~100 bookmarks per file; don't forget to add the HTML file header in every file), and try to import them one by one, until one fails, then split this HTML file again/check it by hand until you find the entry causing the error.

But certainly using the logger would be faster.

**Comment by hubitor** [comment]
Sorry for the late reponse!
I'm unable to test anything at the moment. My server is down. Sorry...

**Comment by ArthurHoaro** [comment]
Closing for now. Feel free to reopen this issue if you can test it again.
