### ISSUE TITLE
Use rel="noreferrer" attributes on external/bookmark links

### ISSUE THREAD

**Issue by C-Duv** [shaarli/Shaarli#685]
I suggest to add the following HTML attribute to all `<a>` that points somewhere out of the application (typically for the bookmarked links): `rel="noreferrer"`.
It makes the browser not sending any referrer in the GET request of the resource.

This feature is browser dependent but works on some (Firefox and Chromium seems to follow this) and it can't do any harm. It would also mask our Shaarli instance from any referrer cleaner (cf. #209).

**Comment by ArthurHoaro** [comment]
Yes. Also see #331 which unfortunately couldn't get to be mergeable.

**Comment by C-Duv** [comment]
Oh, it seems I forgot to look into PRs before opening my issue :)

Do you want me to create a new PR?

**Comment by ArthurHoaro** [comment]
Yes, go ahead.

**Comment by C-Duv** [comment]
I have opened PR #690, please tell me if anything is missing :)

**Comment by ArthurHoaro** [comment]
Fixed by #692, sorry for your time @C-Duv.
