### ISSUE TITLE
RSS "not found" (Markdown plugin + .nomarkdown tag)

### ISSUE THREAD

**Issue by xrat** [shaarli/Shaarli#689]
http://shaarlidemo.tuxfamily.org/Shaarli/?do=rss errors with "not found" if Markdown plugin is enabled and a bookmark entry has the `.nomarkdown` tag added. Corresponding error message on my installation:
"PHP Fatal error:  Cannot unset string offsets in /var/www/Shaarli/plugins/markdown/markdown.php on line 98"

**Comment by ArthurHoaro** [comment]
Good catch! You actually found 2 different bugs here:

   * while rendering the feed, we use the wrong tag list format (string instead of array) for `stripNoMarkdownTag` parameter.
   * since `noMarkdownTag` uses `strpos()`, if you use `.nomarkdown` instead of the exact `nomarkdown`, the tag is found but can't be stripped (also the readme is outdated).

**Comment by xrat** [comment]
Haven't yet found why but `?do=daily` shows `nomarkdown` as a normal tag instead of hiding it.

**Comment by ArthurHoaro** [comment]
Thanks you for testing.

**Comment by xrat** [comment]
I don't have `git` where I run my Shaarli's. So I tried to get your fixes via https://github.com/ArthurHoaro/Shaarli/archive/master.zip and/or https://github.com/shaarli/Shaarli/archive/master.zip but it seems they are not included. How can I get and test your work? Seems I am completely lost. The commits do not even show up at https://github.com/ArthurHoaro/Shaarli/commits/master !?

**Comment by k0nsl** [comment]
@xrat: here you go https://ragnarok.k0nsl.org/shaarli-k0nsl.tar.gz

**Comment by xrat** [comment]
@k0nsl thanks, however, this does not include @ArthurHoaro fixes!? Anyway, I am looking for a way to access the code myself directly :)

**Comment by xrat** [comment]
@ArthurHoaro Oops, sorry for the noise: I only now saw that your commits are actually PRs. I'll shut up now and will wait patiently.

**Comment by ArthurHoaro** [comment]
Yep, a PR is associated with a branch, in this case [plugins/no-md-feed](https://github.com/ArthurHoaro/Shaarli/tree/plugins/no-md-feed) (also my branches are a total mess). You can download it from there.

**Comment by xrat** [comment]
@ArthurHoaro Thanks for your patience and guidance. Got it, tried it, and it works. Great! Looking forward to seeing these PRs in master.
