### ISSUE TITLE
Firefox Share truncates URLs

### ISSUE THREAD

**Issue by nodiscc** [shaarli/Shaarli#693]
When trying to shaare these URLs (from Firefox Share), 

https://blog.adminrezo.fr/2014/02/migration-virtualbox-kvm-qemu-libvirt/
https://blog.adminrezo.fr/2015/01/reseau-vlan-bridge-nat-kvm/
https://blog.adminrezo.fr/2015/01/kvm-volumes-pools-iscsi-lvm-kvm-snapshots/
https://blog.adminrezo.fr/2015/01/gestion-des-vms-only-kvm-modules-drivers-virtio/

the share link dialog is brought up with only https://blog.adminrezo.fr/ set as URL, the `/2015/01/.../` part is trimmed. The actual title of the page is properly detected though (unless https://blog.adminrezo.fr/ was previously shaared, in this case the Edit link dialog is brought up for this shaare instead).

Adding these links from shaarli's `Add link` feature works as expected (dialog is brought up with the full URL and correct title).

Is anyone able to reproduce this problem?

**Comment by Marsup** [comment]
This is happening, but this is the fault of the site, for misusing the `<link rel="canonical" />`. It's supposed to be a unique identifier to a page, yet all his pages point to the root.

**Comment by ArthurHoaro** [comment]
Confirmed. It somehow makes sense: canonical URL is supposed to be the main/favourite URL to access the content you're currently seeing.
