### ISSUE TITLE
Add title to firefoxsocialapi (Share This Page tool)

### ISSUE THREAD

**Issue by xrat** [shaarli/Shaarli#695]
I have more than one Shaarli installation added to my Firefox "Share this page" feature. They are not easy to distinguish at first glance since favicons and layouts are the same. In order to know where I am going to add the URL I have to hover over the favicon and wait for and read the tooltip.

My workaround is to add `$shaarlititle` to `tpl/editlink.html`, specifically I add
``` php
{else}<div style="color:gray">{$shaarlititle|htmlspecialchars}</div>
```
after the line `{include="page.header"}`

Maybe something along these lines could be considered for Shaarli?

**Comment by ArthurHoaro** [comment]
OK for me, you can submit a PR if you want (without inline CSS and you don't need `htmlspecialchars` here).

**Comment by xrat** [comment]
Sorry, I am not a programmer and have never created a PR so far. Someone else would have to create one, I am afraid. However, it's OK if nobody else needs this. I am happy with my `sed` hacks ;-)

Besides, I am actually not sure `<div` is recommended here.

Thanks for pointing out that htmlspecialchars is not needed. I guess I copied it from somewhere else. In fact, it still shows up in https://github.com/shaarli/Shaarli/blob/master/tpl/includes.html#L15

**Comment by ArthurHoaro** [comment]
No problem, we can keep this open.
