### ISSUE TITLE
What are private tags ?

### ISSUE THREAD

**Issue by sijnak** [shaarli/Shaarli#696]
At lines 293-296 of `LinkDB.php` I found

```php
// Remove private tags if the user is not logged in.
if (! $this->loggedIn) {
    $link['tags'] = preg_replace('/(^|\s+)\.[^($|\s)]+\s*/', ' ', $link['tags']);
}
```

Could someone explain me that private tags are ? I only found a quick reference to it in the markdown plugin's documentation but I would like to hear more about it.

**Comment by ArthurHoaro** [comment]
Hi! Private tags are tags starting a dot that'll show up and be searchable only if you're logged in. See [the wiki](https://github.com/shaarli/Shaarli/wiki/Browsing-and-searching#tags-search) or related issues #315 #447.
