### ISSUE TITLE
[question] Does shaarli support link addition with tags ?

### ISSUE THREAD

**Issue by lapineige** [shaarli/Shaarli#698]
Hi Shaarli team :)

I have a question for you: Is it possible in any way (via url, API, command line) to add a link into shaarli with a bunch of tags linked to it ?
I'm using Wallabag as a read it later, with a lot of automated tagging + some manually added one.
Adding them again in Shaarli after sharing the article is quite... annoying ^^
So I would like to add them automatically. Is it possible right now ?

Thanks in advance for your answers :)

PS: by the way I'm working on a support of Shaarli recent version on Yunohost: https://github.com/YunoHost-Apps/shaarli_ynh
If anyone is interested in helping us, you're welcome :)

**Comment by ArthurHoaro** [comment]
Hi!

Our API is currently being written, and should be available in a few months. Currently, you can pass tags using `?post=[url]&title=[title]&tags=[tags]`, etc. See [corresponding code](https://github.com/shaarli/Shaarli/blob/master/index.php#L1385).

However, from your link, your version of Shaarli is way outdated (last commit 3 years ago), and I have no clue if it applies.

**Comment by lapineige** [comment]
Blazing fast answer ! :)
> Our API is currently being written, and should be available in a few months. Currently, you can pass tags using ?post=[url]&title=[title]&tags=[tags], etc.

Any specific issue/milestone to follow ?

I tried on this version (0.0.41beta) and testing with someurl, sometitle, sometag, give me a good result for url and title, but nothing for the tags.
Anyway, good to know, I don't even need the API now, just to share the link with accurate parameters.
I'll submit this improvement to wallabag's team :)
I guess I can close this issue ?

> However, from your link, your version of Shaarli is way outdated (last commit 3 years ago), and I have no clue if it applies.

Indeed, it's based on a beta version from @sebsauvage, and I'm planning to update it to your community fork (so, jumping from 0.0.41 to 0.8... wow :D).

**Comment by ArthurHoaro** [comment]
I've no idea, but yes, [your code](https://github.com/YunoHost-Apps/shaarli_ynh/blob/master/sources/index.php#L1690) doesn't include tags.

> I'm planning to update it to your community fork (so, jumping from 0.0.41 to 0.8... wow :D).

It shouldn't be so hard. For a third party, I think 3 things can be important: the plugin system, the new configuration manager using JSON and the usage of composer. Good luck!

> I guess I can close this issue ?

You can, and eventually reopen if you have other questions. :-)

**Comment by lapineige** [comment]
> I've no idea, but yes, your code doesn't include tags.

Ok, thanks for the highlight.

> It shouldn't be so hard. For a third party, I think 3 things can be important: the plugin system, the new configuration manager using JSON and the usage of composer. Good luck!

I'll look deeper into the new feature and details later, I'm just starting this project. It might be a bit more complex because of Yunohost's integration (things like SSO) but again I've haven't made a list right now.
Thanks for the list, I'll keep it somewhere in my mind ;)

Ok closing, thanks again for your help ;)
Thanks :)
