### ISSUE TITLE
?searchterm=markdown lists also nomarkdown tagged entries

### ISSUE THREAD

**Issue by xrat** [shaarli/Shaarli#704]
Searching for a substring of "nomarkdown" or the full string "nomarkdown" shows bookmarks that are tagged with "nomarkdown". This might be a regression from when ".nomarkdown" was changed to "nomarkdown"!?
Update: I am still using the 0.8 release.

**Comment by ArthurHoaro** [comment]
Yes, that's because the tag is now public and the plugin strip tag happens after the search is done. Also, the plugin system can't alter the list of all tags for now.

**Comment by xrat** [comment]
For me it's important to be able to search for "markdown". However, since the string "nomarkdown" is simply defined in `plugins/markdown/markdown.php` I am fine with changing it there and renaming all tags.

**Comment by xrat** [comment]
I think this issue can be closed as wontfix or so b/c nomarkdown support has been dropped sometime ago.

**Comment by ArthurHoaro** [comment]
I'm not sure about this specific issue, but `nomarkdown` tag is still supported.

**Comment by xrat** [comment]
Thanks @ArthurHoaro , indeed, I was mistaken. The issue is still present in v0.12. In the meantime all my Shaarli notes are using Markdown, so I do not face the original problem anymore. May I suggest we leave the issue closed b/c it didn't bother others much, apparently?
