### ISSUE TITLE
Add OpenSearch URL in RSS/ATOM feeds

### ISSUE THREAD

**Issue by nythael** [shaarli/Shaarli#709]
Hi,

It would be nice to advertise the OpenSearch URL in shaarli's RSS and ATOM feeds, as it allows discovery and use by feed readers.

The XML output would look like this for RSS :
`<atom:link rel="search" type="application/opensearchdescription+xml" href="?do=opensearch" title="Shaarli search - ..." />`

And this for ATOM :
`<link rel="search" type="application/opensearchdescription+xml" href="?do=opensearch" title="Shaarli search - ..." />`

Thanks !

**Comment by ArthurHoaro** [comment]
Hi, I don't mind adding it, but what kind of application feed readers has with it?

**Comment by nythael** [comment]
It would allow a feed reader to display a search bar next to that Shaarli's feed, that can be used to get a custom feed containing the search results.

I'm not aware of any popular feed reader that currently use this.

I'm writing a new one, that currently use this as follows :
1. The feed reader search for links with rel="search" in subscribed feeds
2. When such a link is found, with type="application/opensearchdescription+xml" : opens the opensearch description file and search for an `<Url>` with type="application/rss+xml" or type="application/atom+xml"
3. Store this URL alongside the feed : we now know this feed is searchable
4. When displaying this feed to the user, show a search bar
5. Redirect user's search to the URL stored in step 3, get back an RSS or ATOM feed containing search results
6. Parse and display this feed to the user.

So we can search a feed (or multiple feeds at the same time) directly from within the feed reader, without having to browse to each website manually.

I know some Wordpress instances already advertise this URL, but it would also be valuable on Shaarli instances, that generally contains a lot more links (think blog vs microblogging).

Another usage I have in mind would be to search all the Shaarli's I'm suscribed to at once, e.g. to ask "what do they all think/share about this subject ?". So, distributed search basically.

**Comment by ArthurHoaro** [comment]
Thanks for the detailed explanation. I'll add these.
