### ISSUE TITLE
Issue with permalinks with v0.8.1

### ISSUE THREAD

**Issue by NerosTie** [shaarli/Shaarli#710]
With the v0.8.1 all my permalinks are now something like `mywebsite.tld/?AAAAAA` . So they have all the same permalink. I can't delete a shaare and if I want to edit, it's always the first link of my Shaarli…

EDIT: permalinks are ok in the rss feed.

**Comment by ArthurHoaro** [comment]
Remember that when you use custom themes, your theme must be compatible with the Shaarli version you use. If I'm not mistaken, you are using Material Theme, and @kalvn hasn't updated it yet (to be fair, the PR was merged 2 days ago 😄).

Feel free to reopen if you encounter the same issue with the default theme or with an up to date theme.

**Comment by NerosTie** [comment]
Ho, it's an issue with the theme. I didn't know. So I'll wait for @kalvn to update his theme. Thanks!

**Comment by kriom** [comment]
Hi !

I have the same issue with version 0.9.3 but I don't use any theme.
All permalinks are `https://links.kriom.net/?AAAAAA`
I will investigate but if you have an idea, I'm interested.

**Comment by virtualtam** [comment]
Hi @kriom,

This is a year-old, closed issue, please open a new issue on GitHub as your problem is likely different from the one addressed here :)
