### ISSUE TITLE
Shaarli does not work with PHP 7.1

### ISSUE THREAD

**Issue by robertharm** [shaarli/Shaarli#711]
I tested PHP 7.1 with Shaarli - front page seems ok, anyway if I try to login I only get a blank page (no related messages in the PHP error log)

**Comment by ArthurHoaro** [comment]
Thanks for the feedback, I'll try to find a 7.1 docker container to test it. However, it's surprising that you get a blank page without any error.

**Comment by ArthurHoaro** [comment]
Confirmed. `function ban_canLogin($conf)` is called without argument in the login template. It's an issue we already have, but PHP 7.1 might be less permissive.

Also potential security issue.

**Comment by robertharm** [comment]
great to hear that you found the issue - I switched back to 7.0 in the meantime

**Comment by ArthurHoaro** [comment]
It's actually OK regarding security: function call in the template is only used to display the form or not, client side. We won't need a v0.8.2.

**Comment by Hund** [comment]
Any news on this issue?

**Comment by ArthurHoaro** [comment]
This issue has been fixed by #711, which was released with Shaarli 0.9.0.

**Comment by Hund** [comment]
Hm. I updated to version 0.9.2 the other day on Ubuntu 14.04 with PHP 7.1.10 and I was greeted with a blank page after loggin in.

**Comment by virtualtam** [comment]
@Hund this issue focuses on supporting PHP 7.1 (in terms of code compatibility) and was closed a year ago.

This seems to be a problem related to data migration following a Shaarli upgrade, I suggest you open a new issue so we can provide adequate support :)
