### ISSUE TITLE
Permalinks change after edits with v0.8.1

### ISSUE THREAD

**Issue by xrat** [shaarli/Shaarli#713]
Since I updated to v0.8.1 (thanks for the many bug fixes!) so far, every time I edit an old entry that was created with an older version of Shaarli the permalink changes. Once edited, I can edit and the permalink does not change. But every edit of an old entry breaks its permalink :-/

**Comment by ArthurHoaro** [comment]
Sorry about this bug. I'll release a v0.8.2 to fix this quickly.

**Comment by xrat** [comment]
I applied your changes/fixes and it works now. Thanks a bUnch!
