### ISSUE TITLE
Cannot purge resource.page_cache

### ISSUE THREAD

**Issue by xrat** [shaarli/Shaarli#718]
Already with 0.8.0 and also with 0.8.1 my error.log shows

> PHP message: Cannot purge resource.page_cache: no directory, referer: https://example.org/Shaarli/?

every time I remove a bookmark entry.

There is a notice immediately before ("Indirect modification of overloaded element of LinkDB") cf. #682 but I assume this is unrelated. `resource.page_cache` refers to the directory `pagecache` which exists.

**Comment by xrat** [comment]
It seems nothing is broken, everything works. Just wanted to report this in case it is important.

**Comment by ArthurHoaro** [comment]
Thanks for your bug spotting! ;)
But this one is also fixed in #682 - see https://github.com/shaarli/Shaarli/pull/682/files#diff-828e0013b8f3bc1bb22b4f57172b019dR1329

**Comment by xrat** [comment]
Bug spotting is the least I can do ;) But I have to apologize again for the noise. Great to see this is already fixed. Thank you very much!
