### ISSUE TITLE
Referrer meta tag not supported by some browsers

### ISSUE THREAD

**Issue by kalvn** [shaarli/Shaarli#720]
On Chrome, I get the following message: 
> Failed to set referrer policy: The value 'same-origin' is not one of 'always', 'default', 'never', 'no-referrer', 'no-referrer-when-downgrade', 'origin', 'origin-when-crossorigin', or 'unsafe-url'. The referrer policy has been left unchanged.

Apparently, the only valid values for this tag are those [described here](https://moz.com/blog/meta-referrer-tag). I suppose that

```html
<meta name="referrer" content="origin-when-crossorigin">
```

would fit the original need.

**Comment by ArthurHoaro** [comment]
Of course there is the standard, then what browsers decide to pick up in it.

`same-origin` and `origin-when-crossorigin` are not the same policy. See the [mozilla page](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Referrer-Policy), there are examples.

There is an [open issue](https://bugs.chromium.org/p/chromium/issues/detail?id=627968) to support `same-origin` on Blink/Chrome, so I'd say wontfix and wait that they do. :)

**Comment by kalvn** [comment]
Alright, thanks for the clarification! The definition I found for `origin-when-cross-origin` was actually different. And clearly the actual definition is not what we want here. I will revert the change I did on Shaarli Material and wait for major browsers to support `same-origin` properly.

**Comment by ArthurHoaro** [comment]
The Chromium bug has been fixed this summer, so I guess the referrer policy used by Shaarli is now supported in Chrome, or will be in the next version.

**Comment by kalvn** [comment]
Thanks for the update.
