### ISSUE TITLE
Invalid serialization data for DateTime object

### ISSUE THREAD

**Issue by floviolleau** [shaarli/Shaarli#721]
Hi all,

Many thanks to maintain this awesome project.

I have an error when I wanted to migrate from sebsauvage/Shaarli to shaarli/Shaarli project.

I did an export from my sebsauvage/Shaarli instance (version 0.0.41) of all of my bookmarks. When I tried to import that .html file into my new shaarli/Shaarli project instance, everything was imported successfully BUT after validating the alert message saying that I had X bookmarks imported successfully, I have a blank page.

In my http server logs, I have: 
PHP Fatal error:  Invalid serialization data for DateTime object in /shaarli/application/LinkDB.php on line 306

Http server: lighttpd in version 1.4.31
Php version: PHP 5.4.45-0+deb7u5

Many thanks

**Comment by virtualtam** [comment]
Hi @floviolleau !

This might be due to the recent refactoring on how links are indexed (by ID instead of date), I'll try to reproduce the issue (this should be covered by tests, though - https://github.com/shaarli/Shaarli/blob/master/tests/NetscapeBookmarkUtils/BookmarkImportTest.php)

Could you see if the following allows you to import your links as HTML?
- switch to a previous Shaarli version, e.g.
    - https://github.com/shaarli/Shaarli/releases/tag/v0.8.0 (either using a release archive or a Git tag)
    - Git revision bea80e43a3714663b0c32879f7bdf4fd19161b2e (precedes the link refactoring)
- import links as HTML
- (optional) update Shaarli to the latest revision

**Comment by virtualtam** [comment]
_(Off-topic)_ Would you mind adding an example `lighttpd` configuration to the [Server configuration](https://github.com/shaarli/Shaarli/wiki/Server-configuration) Wiki page? :D

**Comment by ArthurHoaro** [comment]
Hi, it looks like it's a [PHP bug](https://bugs.php.net/bug.php?id=68889) regarding DateTime serialization in PHP 5.4.35+ (a few reports pointing to this bug: [symfony](https://github.com/symfony/symfony/issues/13000), [debian](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=774975), [SO](http://stackoverflow.com/questions/20124030/php-fatal-error-invalid-serialization-data-for-datetime-object-at-session-start)). In any case, I strongly suggest that you upgrade to PHP 5.6 or PHP 7 since PHP 5.4 has reached end of life in september 2015 and 5.5 in july 2016.

@virtualtam Do you think we should do another minor release to fix this?

**Comment by virtualtam** [comment]
I can't reproduce this issue on 5.6 & 7.0 indeed, and tests are passing on Travis with PHP 5.4.37 - see https://travis-ci.org/shaarli/Shaarli/jobs/184505673#L155

As `LinkDB` datastore manipulation (serialization and un-serialization)  are covered by unitary tests, I would expect them to fail under PHP 5.4.{35-45} (just started a debian wheezy container to check this)

@ArthurHoaro I'd rather not hack Shaarli to fix a PHP bug from a long-stated EoL version, especially as we're about to bump the minimum required version in #599

**Comment by virtualtam** [comment]
Hmm, I got both unit tests and HTML import working using the following configuration:
- Debian 7 Wheezy container (LXC)
- PHP 5.4.45 + required extensions
- Apache HTTPD 2.2
- Shaarli on `master`

OS information:
```bash
eol@deb54:~$ lsb_release -a
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux 7.11 (wheezy)
Release:	7.11
Codename:	wheezy

eol@deb54:~$ uname -a
Linux deb54 4.6.7-rt14-1-rt #1 SMP PREEMPT RT Thu Oct 20 19:55:49 CEST 2016 x86_64 GNU/Linux
```

Package details:
```bash
root@deb54:~# dpkg -l php* | grep ^i
ii  php5                             5.4.45-0+deb7u6            all          server-side, HTML-embedded scripting language (metapackage)
ii  php5-cli                         5.4.45-0+deb7u6            amd64        command-line interpreter for the php5 scripting language
ii  php5-common                      5.4.45-0+deb7u6            amd64        Common files for packages built from the php5 source
ii  php5-curl                        5.4.45-0+deb7u6            amd64        CURL module for php5
ii  php5-gd                          5.4.45-0+deb7u6            amd64        GD module for php5
ii  php5-intl                        5.4.45-0+deb7u6            amd64        internationalisation module for php5

root@deb54:~# dpkg -l apache* | grep ^i
ii  apache2-mpm-prefork              2.2.22-13+deb7u7           amd64        Apache HTTP Server - traditional non-threaded model
ii  apache2-utils                    2.2.22-13+deb7u7           amd64        utility programs for webservers
ii  apache2.2-bin                    2.2.22-13+deb7u7           amd64        Apache HTTP Server common binary files
ii  apache2.2-common                 2.2.22-13+deb7u7           amd64        Apache HTTP Server common files
```

Shaarli Git information:
```bash
eol@deb54:~/shaarli$ git branch -vv
* master e3ffc8f [origin/master] Merge pull request #714 from ArthurHoaro/hotfix/banlogin
```

Test output:
```bash
eol@deb54:~/shaarli$ make test
-------
PHPUNIT
-------
PHPUnit 4.8.31 by Sebastian Bergmann and contributors.
Warning:	The Xdebug extension is not loaded
		No code coverage will be generated.

...............................................................  63 / 282 ( 22%)
............................................................... 126 / 282 ( 44%)
............................................................... 189 / 282 ( 67%)
............................................................... 252 / 282 ( 89%)
..............................

Time: 1 second, Memory: 11.00MB

OK (282 tests, 904 assertions)
```

**Comment by ArthurHoaro** [comment]
> I'd rather not hack Shaarli to fix a PHP bug from a long-stated EoL version, especially as we're about to bump the minimum required version in #599

That's my opinion too. It would also mean manipulating the datastore for one minor version, then changing it back in the next.

I tried to reproduced using the old sebsauvage version, thinking it might be related to the export, but no luck. Your test results are surprising.

@floviolleau In your environment, can you [get composer](https://getcomposer.org/download/) and run:

```
composer install
make test
```
And give us the result?

**Comment by floviolleau** [comment]
I'm sorry, I'm in a business travel in Peru and I do not have time to test it right now. I'll try when I will go back to home.

The thing is that I use it on a Raspberry Pi and the version of Php in the depots is that one:
Php version: PHP 5.4.45-0+deb7u5

To answer to @virtualtam 
>(Off-topic) Would you mind adding an example lighttpd configuration to the Server configuration Wiki page? :D

This is a complete zero configuration :) of lighttpd except create a vhost to map it to a folder

**Comment by virtualtam** [comment]
Looks like the latest Raspbian images are based on Debian Jessie, which comes with PHP 5.6 - https://www.raspberrypi.org/downloads/raspbian/

This might be a good starting point if you have a spare SD card :)

It's not entirely sure that PHP is solely responsible for date serialization issues though, as there are similar threads regarding ARM-based hardware:
- https://www.raspberrypi.org/forums/viewtopic.php?f=33&t=58205
- https://wiki.debian.org/ArmHardFloatPort
- https://raspberrypi.stackexchange.com/questions/4677/how-can-i-tell-if-i-am-using-the-hard-float-or-the-soft-float-version-of-debian

**Comment by floviolleau** [comment]
Hi,

Back to France, I will not upgrade my RPi to Jessie because it's seems to be painfull.

I'm trying to upgrade my Php to 7.1.0 because the latest version of Php is not in Raspbian depots neither in dotdeb.org depots (for armhf).

I'll inform you when I'll try Shaarli with my new php 7.

**Comment by ArthurHoaro** [comment]
Closing due to lack of feedback. Feel free to reopen this issue if you have additional information.
