### ISSUE TITLE
Use of $_SERVER['HTTP_REFERER'] causes PHP notices

### ISSUE THREAD

**Issue by xrat** [shaarli/Shaarli#723]
I pretty frequently see the following notices in error.log:
```
PHP Notice:  Undefined index: HTTP_REFERER in /var/www/Shaarli/index.php on line 1026
```
This is the only notice I get (mostly triggered by search engine visits), however, $_SERVER['HTTP_REFERER'] is used several times in `index.php`without catching the possibility of it being empty.

**Comment by nicolasdanelon** [comment]
what about use the `symfony/http-foundation` ?
more infor:
http://api.symfony.com/3.1/Symfony/Component/HttpFoundation/Request.html
https://github.com/symfony/http-foundation

**Comment by ArthurHoaro** [comment]
@nicolasdanelon We're actually planning to use Slim micro-framework, so we won't need Symfony components.
