### ISSUE TITLE
nomarkdown tag is shown in tagcloud

### ISSUE THREAD

**Issue by xrat** [shaarli/Shaarli#726]
Tested with Shaarli 0.8.1

**Comment by nodiscc** [comment]
Still present in 0.9.0.

But @xrat @ArthurHoaro @virtualtam is that really a bug? Why should the `nomarkdown` tag be hidden? It provides another way to sort/filter bookmarks.

Or should the markdown plugin also handle a `.normarkdown` tag (hidden while logged off) ?

**Comment by ArthurHoaro** [comment]
That's debatable, but `nomarkdown` is a technical tag, not a semantic one.

Note that `nomarkdown` tag isn't a private because for now private tags aren't even loaded for logged off users. That's what I would like to change in the future.

**Comment by xrat** [comment]
I agree with @ArthurHoaro .

I would appreciate if there was a way to hide this tag for users who are not logged in. It simply is of no value to the public visitors of my Shaarli sites.
