### ISSUE TITLE
"Insufficient permissions" error on setup

### ISSUE THREAD

**Issue by Beeblebrox-BSD** [shaarli/Shaarli#729]
Hello, I'm getting this error in the browser

Insufficient permissions:
    "cache" directory is not writable
    "data" directory is not writable
    "pagecache" directory is not writable
    "tmp/" directory is not writable

This is a closed/development environment, shaarli is located in $document_root/shaarli (each project in own subfolder)
Changed folder perm to 777 and removed the .htaccess file => same result.
httpS  server is nginx running inside a FreeBSD jail. shaarli folder is owned by www:www
php-fpm is 5.6 running in same jail, forwarded to unix php-fpm.sock
nginx error log shows no message, Xdebug is installed and running, Composer update completed.
nginx setup for shaarli is minimal, other php-based sites working as expected.
Tracking branch Master

Regards.

**Comment by ArthurHoaro** [comment]
Well, I don't know anything about FreeBSD jails, but the error message is self-explanatory: PHP can't write in listed folders, and Shaarli needs to do so.

Just to be sure, you can add a `tmp.php` and run it through your browser:
```php
<?php
touch('tmp/tmp.test');
```

It'll probably fail to create `tmp.test` file.

**Comment by virtualtam** [comment]
Hi @Beeblebrox-BSD!

> Changed folder perm to 777 and removed the .htaccess file => same result.
> httpS server is nginx running inside a FreeBSD jail. shaarli folder is owned by www:www
> php-fpm is 5.6 running in same jail, forwarded to unix php-fpm.sock

Both `php-fpm` and `nginx` should be run using the same user/group, which should have appropriate read/write access on Shaarli (sub)folders, see corresponding examples on the Wiki:
- https://github.com/shaarli/Shaarli/wiki/Server-configuration#nginx
- https://github.com/shaarli/Shaarli/wiki/Shaarli-configuration

The Docker images use a similar setup, and so does my local development environment which runs in a LXC container :)

> Xdebug is installed and running

This PHP module is only required to generate test coverage reports; using it in production results in significantly longer Composer operations

**Comment by ArthurHoaro** [comment]
Closing due to lack of feedback. Feel free to reopen this issue if you have additional information.
