### ISSUE TITLE
more filters for cleanup_url ?

### ISSUE THREAD

**Issue by nicolasdanelon** [shaarli/Shaarli#735]
I'm trying to save this URL in my shaarli v0.8.1

`http://imgur.com/gallery/23FfW?campaign_name=In_Case_You_Missed_It&campaign_date=20170101&campaign_start=20170101&campaign_item_index=7&utm_source=email&utm_medium=In_Case_You_Missed_It&utm_campaign=20170101_Best_Of`

and the link is saved like this:
`http://imgur.com/gallery/23FfW?campaign_name=In_Case_You_Missed_It&campaign_date=20170101&campaign_start=20170101&campaign_item_index=7`

**Comment by nodiscc** [comment]
`\?campaign_.*` should be removed
