### ISSUE TITLE
pubDate is empty in the RSS feed

### ISSUE THREAD

**Issue by NerosTie** [shaarli/Shaarli#752]
With the last version of Shaarli (v0.8.2), the "pubDate" is empty in the RSS feed. Main consequence: I don't appear anymore on shaarlo.fr and all dates are wrong in a RSS aggregator.

**Comment by ArthurHoaro** [comment]
I can't reproduce. Do you have any error in your web server log file? Can you post the content of your `data/updates.txt`.

**Comment by NerosTie** [comment]
Yes I have a lot of errors about the date in my log:

```
2017/01/09 06:45:42 [error] 26530#26530: *102036 FastCGI sent in stderr: "PHP message: PHP Notice:  Undefined index: iso_date in /var/www/shaarli/tmp/feed.rss.aeadca0864f49f08401fb0f97c162898.rtpl.php on line 33 while reading response header from upstream, client: 163.172.32.175, server: links.neros.fr, request: "GET /?do=rss&searchtags=%F0%9F%8F%A0 HTTP/1.1", upstream: "fastcgi://unix:/var/run/php5-fpm.sock:", host: "links.neros.fr
2017/01/10 06:26:12 [error] 1026#1026: *436 FastCGI sent in stderr: "PHP message: PHP Notice:  Undefined index: iso_date in /var/www/shaarli/tmp/feed.atom.aeadca0864f49f08401fb0f97c162898.rtpl.php on line 40 while reading response header from upstream, client: 163.172.68.122, server: links.neros.fr, request: "GET /?do=atom&searchtags=oiseau HTTP/1.1", upstream: "fastcgi://unix:/var/run/php5-fpm.sock:", host: "links.neros.fr"
```
It's just two of them but they are all something like this.

Content of `data/updates.txt`:
```
updateMethodMergeDeprecatedConfigFile;updateMethodRenameDashTags;updateMethodConfigToJson;updateMethodEscapeUnescapedConfig;updateMethodDatastoreIds%
```

**Comment by ArthurHoaro** [comment]
Your issue is related to your theme. It has been fixed it in https://github.com/kalvn/Shaarli-Material/commit/6c3a255fa493b2e7d607620e5a9c8d0d34265ce0 but it isn't include in the theme latest release. I'm not sure which commit includes what, so you should see with @kalvn or manually edit your `feed.*.html` template files.

**Comment by NerosTie** [comment]
pubDate is still empty after I replace the old `feed.*.html` with the new ones. Even with the default theme, pubDate is empty. Am I missing something?

**Comment by ArthurHoaro** [comment]
I'm not sure. Your error message says `Undefined index: iso_date`, except `iso_date` has been replaced by [`pub_iso_date`](https://github.com/shaarli/Shaarli/blob/v0.8.2/tpl/feed.atom.html#L30) and [`up_iso_date`](https://github.com/shaarli/Shaarli/blob/v0.8.2/tpl/feed.atom.html#L31). Has your error message changed?

Also warning: both `feed_plugins` loops in my links has been added after the

**Comment by NerosTie** [comment]
My previous message was edited. I had to add a new link to trigger something and now it works.

**Comment by ArthurHoaro** [comment]
Oh right, the feeds are cached.

**Comment by kalvn** [comment]
Yes apparently at some point I missed changes to feed templates. That was indeed fixed in the commit you mentioned.
