### ISSUE TITLE
Bad redirections after deleted link, removing and renaming tags.

### ISSUE THREAD

**Issue by alexisju** [shaarli/Shaarli#756]
1. When a user **delete a link**, he is always redirected to home page, even if the link is deleted from a search result list ( `?searchtags=example`) or not on the first page (`?page=2`).

2. When a user **remove a tag** on `?do=changetag`, he is redirected to the home page after. It can be anoying if the user want to remove several tags.

3. Also on `?do=changetag`, when a user **rename a tag**,  he is redirect to the linklist of this tag. 

It would seem more logical to stay on the page where the link is deleted, to stay on changetag page after removing or renaming a tag.

**Comment by ArthurHoaro** [comment]
1. Probably a bug.
2. OK, enhancement.
3. Well, I think that's nice to see the result of the change. We have a few bulk operation open issues to address your use case (planned in this major I think).

**Comment by ArthurHoaro** [comment]
Fixed by #766 and #767
