### ISSUE TITLE
Piwik URL does not support http:// or https://

### ISSUE THREAD

**Issue by robertharm** [shaarli/Shaarli#773]
Thx for adding Piwik as plugin - anyway I wondered why it did not work until I found in the source code that only www.domain.com/piwik is working and not if you provide http:// or https:// as prefix - I think this should be fixed or made clearer. 

Perhaps HTML 5 input type URL could be used for the form field - see more details at http://www.w3schools.com/html/html_form_input_types.asp

**Comment by ArthurHoaro** [comment]
Yes, it's currently protocol relative, which isn't really a good idea since we don't have information about Piwik host.
