### ISSUE TITLE
Missing license

### ISSUE THREAD

**Issue by sogen** [shaarli/Shaarli#774]
FYI it's missing

**Comment by ArthurHoaro** [comment]
https://github.com/shaarli/Shaarli/blob/master/COPYING

**Comment by nodiscc** [comment]
https://github.com/shaarli/Shaarli#license :)

**Comment by sogen** [comment]
Ah, sorry, I meant it's missing in two places: the LICENSE.txt file, and it's also missing the license icon at the top right in the repo.

example:
https://github.com/Microsoft/vscode

![screen shot 2017-01-27 at 10 06 18 am](https://cloud.githubusercontent.com/assets/2784323/22379869/6bd027fc-e478-11e6-8438-81de5f699f8b.png)

**Comment by ArthurHoaro** [comment]
The zlib/libpng license isn't recognized by Github anyway.
