### ISSUE TITLE
Upgrade: You must specify an integer as a key.

### ISSUE THREAD

**Issue by gerroon** [shaarli/Shaarli#775]
HI

I just downloaded and copied the tar file content into the shaarli directory and this is what I am getting when I try to access the url. THe documentation is super vague with update. It does not tell me anything about the actual process. So I checked the git update and did the composer thing, still getting the same issue.

I am on Debian Wheezy Apache. I cant tell what my version is (before the upgrade), there is no any vcersion thing anywhere I can see in the pages. 

loading composer repositories with package information
Updating dependencies

Writing lock file
Generating autoload files

----

Upgrading from release archives

All tagged revisions can be downloaded as tarballs or ZIP archives from the releases page.

We recommend using the releases from the stable branch, which are available as:

    gzipped tarball - https://github.com/shaarli/Shaarli/archive/stable.tar.gz
    ZIP archive - https://github.com/shaarli/Shaarli/archive/stable.zip

Once downloaded, extract the archive locally and update your remote installation (e.g. via FTP) -be sure you keep the contents of the data directory!

After upgrading, access your fresh Shaarli installation from a web browser; the configuration will then be automatically updated, and new settings added to data/config.php (see Shaarli configuration for more details).

**Comment by virtualtam** [comment]
Hi @gerroon!

I'm quite confused by this request, you might want to rewrite it for clarity...

> I cant tell what my version is (before the upgrade), there is no any vcersion thing anywhere I can see in the pages.

What type of installation did you upgrade from?
- Sebsauvage's releases
- Community Shaarli releases (git)
- Community Shaarli releases (tarball)
- ...?

It is highly recommended to backup your configuration / installation before upgrading or migrating a Shaarli installation - https://github.com/shaarli/Shaarli/wiki/Upgrade-and-migration#backup-your-data

> downloaded and copied the tar file
> checked the git update and did the composer thing

There are 3 main ways of installing & updating Shaarli:
- by using a release archive that bundles all third-party dependencies
- by using a git-generated archive, in which case you also need to install and run Composer to manage third-party dependencies
- by cloning the Git repository

>  The documentation is super vague with update

Seriously?
- https://github.com/shaarli/Shaarli/wiki/Download-and-Installation
- https://github.com/shaarli/Shaarli/wiki/Upgrade-and-migration

> I am on Debian Wheezy Apache.

Could you provide us with more details about your installation? At least the Apache HTTPD & PHP versions.
See also https://github.com/shaarli/Shaarli/wiki/Server-requirements for supported PHP versions and required extensions.

**Comment by gerroon** [comment]
@virtualtam 

Thanks for the reply.


When I said the documentation is vague, I meant that it does not clearly tell me what to do with the tarball. Here is the concerning sentence

"Once downloaded, extract the archive locally and update your remote installation (e.g. via FTP) -be sure you keep the contents of the data directory!"

What I understood from this sentence is  this, "copy the content of the tar into the shaarli installation directory and make sure that the data directory contains the files from the previous intallation". When it says "update" it feels abit recursive, to update it you have to update it, so I assume it means just copy the files really. 

So if that is all to do it, then that is all I did and I got the message in the post title when I tried to access the newly upgraded Shaarli. Please bear in mind that my Shaarli installation works normally, before the upgrade it was fine. 


I also did a fresh install from the tar file and then I copied the "data" folder from  my backup to the newly installed Shaarli,but I still got the same error in the browser.


I do not remember where I got the Shaarli instance that is why I said " I cant find a way to tell you the version of the Shaarli" If ypu can tell me a way to get more detail about the installation I will be more than happy to provide it but i cant figure that information by just looking around the Shaarli instance. I tend to think that I got it from this Github page but not sure.

  
PHP 5.6.27-1~dotdeb+7.1 (cli) (built: Oct 15 2016 02:45:48)
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2016, by Zend Technologies


Server version: Apache/2.2.22 (Debian)
Server built:   Aug 18 2015 10:17:37


Like I said, my current Shaarli works but the upgrade process breaks it. As far as I can tell I installed this instance almost 1 year ago.

I hope my reply is helpful regarding this issue.

**Comment by ArthurHoaro** [comment]
Hi! Could you add the two following lines just before the [`die()` instruction in `application/LinkDB.php](https://github.com/shaarli/Shaarli/blob/master/application/LinkDB.php#L148) and give us the result?

```
var_dump($offset);
var_dump($value);
```

Can you also give us the content of `data/updates.txt`.

Also make sure to keep a copy of your database (`data/datastore.php`).

**Comment by virtualtam** [comment]
Definitely clearer, thanks :)

Yep, the upgrade process is mostly about replacing files with a newer version and ensuring file permissions are sufficient, plus running Composer if needed.

You can find which Shaarli version you're using (i.e. which commit it corresponds to) by looking at the `shaarli_version.php` file at the root of the installation.

The error might be due to the configuration updater failing, I'm not sure we have extensively tested it e.g. to upgrade config from a legacy/Sebsauvage setup

Just to check, do you encounter a similar error when serving a new Shaarli installation? That is, without restoring your previous configuration/datastore.

In that case, it might be simpler to setup a fresh installation, and only restore saved links - the `data/datastore.php` file

**Comment by gerroon** [comment]
Hi

it looks like my version before upgrade is 0.6.3

and here is the modified LinkDB.php result

string(15) "20170202_220633" array(10) { ["title"]=> string(49) "Kodi v17 (Krypton) changelog - Official Kodi Wiki" ["url"]=> string(50) "http://kodi.wiki/view/Kodi_v17_(Krypton)_changelog" ["description"]=> string(0) "" ["private"]=> int(1) ["linkdate"]=> string(15) "20170202_220633" ["tags"]=> string(4) "kodi" ["real_url"]=> string(50) "http://kodi.wiki/view/Kodi_v17_(Krypton)_changelog" ["id"]=> string(15) "20170202_220633" ["created"]=> object(DateTime)#1051 (3) { ["date"]=> string(26) "2017-02-02 22:06:33.000000" ["timezone_type"]=> int(3) ["timezone"]=> string(15) "America/Chicago" } ["shorturl"]=> string(6) "EzdCJg" } You must specify an integer as a key.

**Comment by ArthurHoaro** [comment]
I got it. In v0.6.4, an update method was added (`updateMethodRenameDashTags()`) which is accessing `LinkDB`. But since the datastore hasn't been updated at this point, the access fails.

A quick workaround:

  1. Create a file called `data/updates.txt`.
  2. Paste this string in the new file `updateMethodRenameDashTags`
  3. Login to Shaarli.
  4. Delete the update file.

**Comment by gerroon** [comment]
@ArthurHoaro 
Thanks for the follow up. I still get the exact same error. I even restarted apache.

**Comment by ArthurHoaro** [comment]
I'm glad you got it working.
