### ISSUE TITLE
Display current Shaarli version in tools template

### ISSUE THREAD

**Issue by ArthurHoaro** [shaarli/Shaarli#778]

**Comment by alexisju** [comment]
On Albinomouse-template, i put it on footer (displayed only when logged in). Indeed, i think it can be useful to know easily which version is running.

Could it be possible to indicate branch?

**Comment by ArthurHoaro** [comment]
> i put it on footer (displayed only when logged in)

Good idea.

> Could it be possible to indicate branch?

No. Also it doesn't make sense since a release is a signed tag which can come from any branch.

**Comment by alexisju** [comment]
> No. Also it doesn't make sense since a release is a signed tag which can come from any branch.

I don't know. As you know, current Shaarli in `master` is now tagged 0.8.3 (as in v8.0 branch) however the template it this branch doesn't work with latest zip build v0.8.3... 

This is related to the issue #777. But if i choose to use the `master` branch to maintain a 3rd party template or plugins, when i see the same tag as latest release i suppose my dev should work on latest zip build too...
