### ISSUE TITLE
Unable to delete some imported links

### ISSUE THREAD

**Issue by effemmeffe** [shaarli/Shaarli#781]
Delicious doesn't allow to export bookmark anymore.
So I fond a script somewhere that parse somehow the site, extract the links and wrote a delicious.html file as output.
I tried to import that file in Shaali, but I got a 500 error.
I also imported the file in Firefox and as a result I got a lot of new bookmarks, so the file is somehow good.

This is the log I got in my apache logs, don't know if it's really relevant, but it happens when I press import:

`[Wed Feb 15 13:56:15.291192 2017] [:error] [pid 12383] [client $MY_IP:41621] PHP Fatal error:  Uncaught Error: Class 'NetscapeBookmarkParser' not found in /var/www/shaarli/application/NetscapeBookmarkUtils.php:121\nStack trace:\n#0 /var/www/shaarli/index.php(1531): NetscapeBookmarkUtils::import(Array, Array, Object(LinkDB), 'pagecache')\n#1 /var/www/shaarli/index.php(2243): renderPage(Object(ConfigManager), Object(PluginManager), Object(LinkDB))\n#2 {main}\n  thrown in /var/www/shaarli/application/NetscapeBookmarkUtils.php on line 121, referer: http://$MY_SHAARLI_SERVER/shaarli/?do=import`

Shaarli (version 0.8.2)
AlbinoMouse Template

**Comment by virtualtam** [comment]
Hi @effemmeffe, this is a known issue related to the latest changes on https://github.com/shaarli/netscape-bookmark-parser and will be fixed soon.

@ArthurHoaro we should revert these commits and release a fixed `1.x` version, and bump the parser's version code to `2.0` as these are breaking changes

**Comment by effemmeffe** [comment]
Ok, I'll wait.
Thanks.

**Comment by ArthurHoaro** [comment]
@virtualtam OK, I'll do that.

**Comment by virtualtam** [comment]
Thanks @ArthurHoaro !

`1.1.0` should feature in the changelog as an YANKED version, and the tag kept in case someone did clone the repo.

This is to keep consistency with whatever clones are in the wild, i.e. the tag would be re-pushed were someone to release a new version without deleting it from his/her working copy.

**Comment by ArthurHoaro** [comment]
Didn't see your comment @virtualtam, I did remove the tag entirely.

**Comment by ArthurHoaro** [comment]
Hi @effemmeffe, we've added an import log to debug imports in the master branch.

You can use it by:

  - getting the master branch
  - running `composer install`
  - add this in `data/config.json.php`
```
"dev": {
  "debug": true
},
```
  - run your import
  - check out `data/import.date.log` file

Or you can wait for the next release if you prefer.

**Comment by effemmeffe** [comment]
Will try and report

**Comment by effemmeffe** [comment]
I had to run git pull as www-data user and then I had to run `composer update` and not `composer install` because of this message:
```
[RuntimeException]
  The lock file does not contain require-dev information, run install with the --no-dev option or run update to install those packages.
```

But in the end I managed to update my installation and the import went fine.
Problem is that then I realize that some of them were obsolete, but I cannot delete them: I get a messagebox that asks delete comfirmation, but even if I click OK the link it's still there. Reloading the page doesn't change anything.
I had to revert back to saved datastore.php to get rid of all the imported links.

**Comment by ArthurHoaro** [comment]
Oh sorry, I read too fast, your issue wasn't related to the parser issues.

However, the bug you encountered is unexpected, and is more likely related to the ID system which should be stable by now. If you're willing to spend time on debugging this, here are a few step that might help me understand what's going on:

  * did you use the overwrite setting during the import?
  * delete `data/updates.txt` and refresh a page while logged in
  * re-import your file
  * in linklist, please give us the link used for deletion (while hovering the delete icon, right click, copy link location)
  * try to switch between default and vintage themes (in Shaarli's config page) to see if the behaviour is the same
  * take a look at your webserver log to see if there is any error or warning

Also, rememberer to remove the debug setting in your config file.

**Comment by nodiscc** [comment]
@effemmeffe Did you have time to debug this further by any chance?

> But in the end I managed to update my installation and the import went fine.
> Problem is that then I realize that some of them were obsolete, but I cannot delete them

Changing the title of the issue to reflect that

**Comment by virtualtam** [comment]
Closing due to lack of feedback, feel free to reopen should the issue appear again.
