### ISSUE TITLE
Find untagged links

### ISSUE THREAD

**Issue by qwertygc** [shaarli/Shaarli#784]
Hey !
I would like classify my shaarlinks and i would like sharlink without tags. it's possible ?

**Comment by ArthurHoaro** [comment]
Hi! Sorry but I don't understand your question. Could you give more context?

**Comment by qwertygc** [comment]
Je vais le faire en français : 
je souhaite afficher tout mes shaarlinks sans tags, pour pouvoir les étiqueter par la suite.

**Comment by ArthurHoaro** [comment]
OK thanks. I don't think it's possible yet, but it would be a nice feature to go along multiple tags improvements planned in v0.9.x.

**Comment by kalvn** [comment]
I suggest to rename this issue **Find links which have no tags** or **Find untagged links** or something similar to be clearer because I misunderstood the purpose of this issue when first reading it.

**Comment by qwertygc** [comment]
Et je constate quand on renomme avec l'outil, il peut avoir des doublons (un shaarlink taggé deux fois avec le même tag). Comment lutter contre ça ?

**Comment by virtualtam** [comment]
AFAIK removing duplicate tags after renaming has been addressed by #759 / #757 (related: #317)

**Comment by joshingeneral** [comment]
So just wanted to also note that you can use the minus sign to remove tags (even to the point of getting untagged items) so just add -tag1 -tag2 in the search field to remove given tags.

**Comment by qwertygc** [comment]
Good but i have many tags, its not a good solution
