### ISSUE TITLE
serverUrl fails on non-standard port

### ISSUE THREAD

**Issue by Nicals** [shaarli/Shaarli#79]
On non standard port, the server url is 

```
<protocol>://host(:<port>)?
```

Despite the example given, the [actual way](https://github.com/shaarli/Shaarli/blob/master/index.php#L444) can't handle such requests. A request from http://localhost:8000 will return a server url as http://localhost:8000:8000 resulting on a browser error since the *Location* header is incorrect.

**Comment by nodiscc** [comment]
@Nicals Can you recheck agains the latest `master`? https://github.com/shaarli/Shaarli/pull/98 has been merged and should fix this. Thanks

**Comment by nodiscc** [comment]
No reply, closing.
