### ISSUE TITLE
Do not lose POST data when token expires ("Wrong token")

### ISSUE THREAD

**Issue by b4n** [shaarli/Shaarli#80]
*(imported from sebsauvage#215 -- I did not explicitly test this with this fork but I was both told it wasn't fixed and checking the log supports this)*

I just tried to post a link with a lengthy description, and it took me some time to write it, plus I did a few other things in-between.  When I wanted to save the link, I got a "Wrong token" error.  Fair enough, but all my data was lost!

So, please do not lose the POST data (at least not `lf_url`, `lf_title` and `lf_description`).  Ideally the form would be re-shown with only a (big) warning on top, so all it would require would be to re-hit save in such a case.

Alternatively, a relatively simple solution could be to try and submit the form via XHR if available, and embed the error (if any).  While not allowing to re-sumbit right away (and only working for JS-enabled users), it would at least allow the user see the error before losing his data, back it up and retry.

----

If this happens to anyone else in the meantime and you didn't close the page, you can quickly hack to recover your data: just edit shaarli's *index.php* and add `var_dump($_POST);` at the very end, just before `renderPage();`.  Then, force your browser to re-submit the page (e.g. just reload it with Firefox, it will ask whether to resubmit, and you say yes): it will still not save your data but you will be able to back it up (check out the page's source so you also have proper newlines).
Don't forget to remove the added line when you backed up your data!

**Comment by ArthurHoaro** [comment]
Closing this since there is a nice plugin made by @kalvn to do this: https://github.com/kalvn/shaarli-plugin-autosave
