### ISSUE TITLE
Demo out of service

### ISSUE THREAD

**Issue by polyvertex** [shaarli/Shaarli#801]
Hi! I was on my way to try the demo instance but got to face some garbage once [logged-in](http://shaarlidemo.tuxfamily.org/Shaarli/).

```
/** * * `markdown_escape` is a new setting, set to true as default. * * If the
markdown plugin was already enabled, escaping is disabled to avoid * breaking
existing entries. */ Method [ public method updateMethodEscapeMarkdown ] { @@
/data/web/44/11/d5/shaarlidemo.tuxfamily.org/htdocs/Shaarli/application/Updater.php
351 - 365 } An error occurred while running the update exception 'IOException'
with message 'Shaarli could not create the config file. Please make sure Shaarli
has the right to write in the folder is it installed in. data/config.json.php'
in
/data/web/44/11/d5/shaarlidemo.tuxfamily.org/htdocs/Shaarli/application/config/ConfigJson.php:39
Stack trace: #0
/data/web/44/11/d5/shaarlidemo.tuxfamily.org/htdocs/Shaarli/application/config/ConfigManager.php(208):
Shaarli\Config\ConfigJson->write('data/config.jso...', Array) #1
/data/web/44/11/d5/shaarlidemo.tuxfamily.org/htdocs/Shaarli/application/Updater.php(362):
Shaarli\Config\ConfigManager->write(true) #2 [internal function]:
Updater->updateMethodEscapeMarkdown() #3
/data/web/44/11/d5/shaarlidemo.tuxfamily.org/htdocs/Shaarli/application/Updater.php(88):
ReflectionMethod->invoke(Object(Updater)) #4
/data/web/44/11/d5/shaarlidemo.tuxfamily.org/htdocs/Shaarli/index.php(745):
Updater->update() #5
/data/web/44/11/d5/shaarlidemo.tuxfamily.org/htdocs/Shaarli/index.php(2245):
renderPage(Object(Shaarli\Config\ConfigManager), Object(PluginManager),
Object(LinkDB)) #6 {main}
```

**Comment by ArthurHoaro** [comment]
Yes, I'm currently working on it.

**Comment by k0nsl** [comment]
@ArthurHoaro: Which theme were you using before it was fixed? It looked pretty darn nice.

**Comment by ArthurHoaro** [comment]
Thanks! That's the future default theme. It will be released in v0.9.0.
The demo will be moved to https://demo.shaarli.org when the DNS propagation will be done (probably tomorrow night).

**Comment by k0nsl** [comment]
Thanks, @ArthurHoaro !

I must've deleted my comment as you had just typed yours. I figured it out on my own and thought it was a silly question -- because all it took was a minute of looking around on my own :D

**Comment by ArthurHoaro** [comment]
The new demo is apparently running fine at https://demo.shaarli.org - if it doesn't work, wait for a while.

@k0nsl in any case, glad to hear that you like the new theme.

**Comment by polyvertex** [comment]
It does work thanks!
And I second @k0nsl's comment regarding the theme, I didn't mind the previous one but this one does look nicer. Also, it's nice to see such a project being so actively maintained. A gem really. Please keep it up :)

**Comment by warenhaus** [comment]
hi!
public demo now gives 404.

**Comment by ArthurHoaro** [comment]
Thanks, it's fixed. It looks like I had 2 cron services running, which obviously caused some issues. I'll monitor the logs in the next days.
