### ISSUE TITLE
Remove ReadItYourself plugin

### ISSUE THREAD

**Issue by ArthurHoaro** [shaarli/Shaarli#818]
I'm not aware of anyone using it and the [repo](https://github.com/memiks/readityourself) hasn't been updated for almost 3 years.

**Comment by nodiscc** [comment]
Agreed. This was a useful placeholder/example plugin at the time, but keeping has very little interest ,considering the project is abandoned and browser improvements like [Firefox Reader mode](https://support.mozilla.org/t5/Basic-Browsing/Firefox-Reader-View-for-clutter-free-web-pages/ta-p/38466) have made this plugin/web app basically useless.
