### ISSUE TITLE
Fatal error: Uncaught Error: Call to undefined function format_date() 

### ISSUE THREAD

**Issue by ParoTheParrot** [shaarli/Shaarli#820]
I used material theme in `config.json.php`: "raintpl_tpl": "tpl\/material\/" - works fine!
Now I try to change to the _default_ theme from `Shaarli-master`.
Afterwards I get this error on the shaarli startpage: `Fatal error: Uncaught Error: Call to undefined function format_date() `

**Comment by ArthurHoaro** [comment]
Hi! If you want to test the theme from the `master` branch, your Shaarli version must also be from the `master` branch.

**Comment by ParoTheParrot** [comment]
OK, thanks. Is there any chance to use the _default_ theme with Shaarli 0.8.4?
I didn't like the old one and material isn't what I'm looking for. BUT https://demo.shaarli.org/ is very nice!

**Comment by ArthurHoaro** [comment]
Thanks, but no you'll have to wait until v0.9.0 is released, since the theme is still in development stage and is only compatible with the latest dev changes.

**Comment by ParoTheParrot** [comment]
What is the plan for releasing 0.90?

**Comment by virtualtam** [comment]
When it's ready :)
See the [v0.9.0](https://github.com/shaarli/Shaarli/milestone/9) milestone for more details
