### ISSUE TITLE
Theme: font is strange using Windows

### ISSUE THREAD

**Issue by ArthurHoaro** [shaarli/Shaarli#822]
I just checked the demo using Windows 7 and the font used for titles has nothing to do with what's I'm used to on my Linux env or mobile.

Not sure why, needs to be checked before release.

**Comment by ArthurHoaro** [comment]
screenshots

Windows:
![](https://i.imgur.com/98tgyy3.png)
Linux:
![](http://i.imgur.com/0k3tzzR.png)

**Comment by nodiscc** [comment]
Confirming, I have similar font rendering differences between Firefox on Linux (Debian) and Windows 7

**Comment by pikzen** [comment]
This just seems like a font renderer hinting difference to me. Is ClearType activated on your setups?

That, or it's a letter-spacing issue, but it would surprise me.

**Comment by ArthurHoaro** [comment]
Yes, it's enabled. It seems to be how Fire Sans bold is rendered in Firefox Windows (Chromium rendering is similar to the Linux one). Not sure if there is much we can do except trying other fonts.

Also, clean up: the font is set to Roboto Slab while loading Fira Sans.

**Comment by pikzen** [comment]
>Also, clean up: the font is set to Roboto Slab while loading Fira Sans.

Sooooo, having looked at the .css: the "Roboto Slab" font is redefined to load Fira Sans (why.png), through an @font-face directive. My knowledge of font handling is a bit rusty, but I believe that this rule does prevent a font-family: Roboto Slab from loading the actual Roboto Slab. But even if it did, Roboto is not a standard font on Windows, and probably Linux & OSX, so you're going to have the white flash of text when the font goes from default sans serif to Fira Code anyways.

And yes, Chromium's font renderer on Windows has often been wonky, breaking from one release to another, or not respecting system wide font settings.

**Comment by ArthurHoaro** [comment]
> Sooooo, having looked at the .css: the "Roboto Slab" font is redefined to load Fira Sans (why.png)

Yes, that's the first thing I tried, but I'll double check. As for why, I was testing a bunch of fonts and only changing the filename, and apparently forgot to change the font name after that.

**Comment by ArthurHoaro** [comment]
So, I found where the difference comes from, maybe that's what you called font hinting. If I specify the bold variant of Fira Sans, the font is the same on both system. So I suppose the system is trying to create the bold variant based on the regular one if it isn't specified. The thing is, I don't really like the "real" Fira Sans bold for titles here.

I still haven't found a satisfying font yet, nor decided if we should use another one for link titles, and I'll run a few tests later. I'm open to suggestions though.
