### ISSUE TITLE
Latest release is shown as 0.7.1

### ISSUE THREAD

**Issue by jernst** [shaarli/Shaarli#823]
Five days after 0.8.4. That is very confusing. Was that a mistake or intentional?

**Comment by virtualtam** [comment]
Hi @jernst,

If you're referring to  https://github.com/shaarli/Shaarli/releases, Github displays releases in chronological order, which also messes up with the badge shown on our README.

AFAIK there is no way to reorder releases on Github

**Comment by ArthurHoaro** [comment]
0.7.1 contains a security fix for the `stable` branch. They're is not much we can do about how Github displays releases.

**Comment by virtualtam** [comment]
Reopening as there's a valid point: the README should display coherent release information

I suggest we display a badge per release channel, e.g.:
- stable: 0.7.1
- latest: 0.8.4
- master: 0.9.x
