### ISSUE TITLE
Migrate Docker images to Alpine Linux

### ISSUE THREAD

**Issue by virtualtam** [shaarli/Shaarli#843]
### Motivations
Our Docker images are currently based on the `debian:jessie` base image, and weight around 300 MiB.

This is due to several reasons:
- the base Debian image weights around 120 MiB
- it provides APT package management
- it comes with plenty of system dependencies that might not be relevant in a Docker context 

[Alpine Linux](https://alpinelinux.org/) is a lightweight and minimalist distribution tat revolves around:
- [musl-libc](https://www.musl-libc.org/) to provide a C/POSIX environment
- [BusyBox](http://www.busybox.net/) to provide a reduced set of system utilities
- [apk](https://wiki.alpinelinux.org/wiki/Alpine_Linux_package_management) for package management _(Note: it's totally unrelated to Android's apk tool)_

The [base image](https://hub.docker.com/_/alpine/) _weights 4 MiB_ and comes with [usage documentation](http://gliderlabs.viewdocs.io/docker-alpine/usage/) to create lightweight service images.

Related articles/posts:
- https://www.brianchristner.io/docker-is-moving-to-alpine-linux/
    - https://news.ycombinator.com/item?id=11044980
- https://nickjanetakis.com/blog/alpine-based-docker-images-make-a-difference-in-real-world-apps

### Proposed setup for Shaarli images
- Alpine Linux 3.6
- PHP 7.1
- PHP-FPM 7.1
- Nginx
- s6

Note: Supervisor comes with a lot of Python dependencies (with respect to the expected image size) and might be replaced with [runit](http://smarden.org/runit/) to spare a few [MiBs](https://makeuseof.com/wp-content/uploads/2014/10/will-smith-neuralyzer-e1413218351343.jpg?187d39) :)

### Early results
I've started to fiddle with a new image, here are the early results (before attempting Dockerfile voodoo):
```shell
$ docker images

REPOSITORY          TAG             IMAGE ID            CREATED             SIZE
vt-shaarli          latest          b2268683c850        16 minutes ago      116 MB
shaarli/shaarli     latest          c13a3fa1ba4d        35 hours ago        289 MB
debian              jessie          8cedef9d7368        12 days ago         123 MB
alpine              3.5             4a415e366388        4 weeks ago         3.99 MB
```

**Comment by ArthurHoaro** [comment]
If `apk` provides all necessary packages, that's fine with me. 
We're talking about disk usage here, not RAM, right?

**Comment by virtualtam** [comment]
Alpine indeed provides system and PHP packages with good granularity (1 extension => 1 package)

The generated images are more lightweight (I've managed to go down to 75 MiB by replacing supervisor with S6), which means they take less storage space, and by extension use less RAM when running Docker appliances :)
