### ISSUE TITLE
You must specify an integer as a key

### ISSUE THREAD

**Issue by fturco** [shaarli/Shaarli#847]
I'm running Shaarli (latest git version) on my personal VPS. It seems there's a problem when trying to rename tags.

Steps:
* Go to https://shaarli.fturco.net/?do=changetag
* Specify old and new tags
* Click on the Rename tag button

Result: I get the following error message:

> You must specify an integer as a key.

**Comment by ArthurHoaro** [comment]
Hi. Could you add the following lines before the `die()` instruction in `application/LinkDB` line 148:

```
var_dump($offset);
var_dump($value['id']);
```

I don't reproduce but it might be related to c8cb5c282402e3f19497ba9e57ac967a4bdefa1b.

**Comment by fturco** [comment]
I tried renaming tag `c++` into `cpp` and now I obtain the following result:

    string(15) "20160719_201323" string(15) "20160719_201323" You must specify an integer as a key.

**Comment by ArthurHoaro** [comment]
Your datastore hasn't been updated as it should have been since v0.8.1. Did you update recently?

Please **save `data/datastore.php`** and remove `data/update.txt`.

**Comment by fturco** [comment]
Yes, I updated Shaarli recently.

After removing `data/update.txt` tag renaming started working again. Thank you!

Is there any documentation I could have read about the need to remove `data/update.txt` when performing an upgrade? There is no mention of `update.txt` [here](https://github.com/shaarli/Shaarli/wiki/Upgrade-and-migration).

**Comment by ArthurHoaro** [comment]
It shouldn't be needed, but it could be added in a troubleshooting section.

**Comment by ArthurHoaro** [comment]
[Troubleshooting](https://github.com/shaarli/Shaarli/wiki/Upgrade-and-migration#troubleshooting) section added.
