### ISSUE TITLE
[RESOLVED]No available search with tag(?searchtags=)

### ISSUE THREAD

**Issue by Draleg** [shaarli/Shaarli#850]
Hello :-) ,

I was in the group anonym of first users of shaarli, I follow Seb on his blog, and I discover his Shaarli.
Recently, I just check about update of Shaarli, and a found this github, thank a lot for your work.

So I export my data in html, and import it on my new install of your Shaarli.
I have just one problem... The "searchtags"give me a blank page.
My new installation are on a private server so I can't give you a link...
My older installation are in : http://dr4leg.free.fr/shaarli/ .

The old searchtags is ok... and I don't understand why on my new install all "?searchtags=" give me just a blank page with any tags.
My TagCloud is ok, all the tags are here, in the old and the new install of Shaarli.

Thank's

**Comment by ArthurHoaro** [comment]
Hi! If you get a blank page, it probably means that you have a PHP fatal error. Please check your web server logs and give us the error.
Also, which version are you using?

**Comment by Draleg** [comment]
Hi, thank's for your help,
This this the error:

`[Thu Apr 13 14:15:26.009163 2017] [:error] [pid 13330] [client 91.183.231.47:59559] PHP Fatal error:  
Uncaught Error: Call to undefined function mb_convert_case() in /var/www/html/link/application/LinkFilter.php:348\nStack trace:\n#0 
/var/www/html/link/application/LinkFilter.php(250): 
LinkFilter::tagsStrToArray('Linux', false)\n#1 /var/www/html/link/application/LinkFilter.php(79): 
LinkFilter->filterTags('Linux', false, false)\n#2 /var/www/html/link/application/LinkDB.php(478): 
LinkFilter->filter('tags', 'Linux', false, false)\n#3 /var/www/html/link/index.php(1628): 
LinkDB->filterSearch(Array, false, false)\n#4 
/var/www/html/link/index.php(725): buildLinkList(Object(PageBuilder), Object(LinkDB), Object(ConfigManager), Object(PluginManager))\n#5 
/var/www/html/link/index.php(1597): showLinkList(Object(PageBuilder), Object(LinkDB), Object(ConfigManager), Object(PluginManager))\n#6 
/var/www/html/link/index.php(2219): renderPage(Object(ConfigManager), Object(PluginManager))\n#7 {main}\n  thrown in /var/www/html/link/application/LinkFilter.php on line 348`

And I use "shaarli-v0.8.4-full" .

Thanks

**Comment by ArthurHoaro** [comment]
You need php-mbstring extension. See [the requirements](https://github.com/shaarli/Shaarli/wiki/Server-requirements#extensions).

**Comment by Draleg** [comment]
Well I'm on it...
At the same time, I search why this kind of error was generated... And that's the problem effectivly...
(I found the same problem but for other use: https://openclassrooms.com/forum/sujet/symfony2-undefined-function-mbconvertcase-91140)

So I locate all php.ini (I'm beginner in LAMP) and I remove the ";" on all requirement.
I do a "service apache2 force-reload" but nothing always a blank page and the same error...
I have miss something ?

Thank's

**Comment by ArthurHoaro** [comment]
Yes, you actually need to install the package. This depends on your OS, but for example, Ubuntu `sudo apt-get install php-mbstring`.

**Comment by Draleg** [comment]
Oh god... it's exact... I forgot the package... Thank's a lot for your help, it's resolv !

**Comment by ArthurHoaro** [comment]
Glad I could help!
