### ISSUE TITLE
OStatus ?

### ISSUE THREAD

**Issue by qwertygc** [shaarli/Shaarli#851]
Bonjour !
Il semble que le succès de réseaux sociaux décentralisés basé sur OStatus (type Mastodon) fonctionne. Certains utilisent Shaarli comme réseau social (shaarlo.fr, river.hoa.ro…). Pourquoi pas implanter une fonction OStatus, même en plugin, pour interagir avec le reste du monde ?

**Comment by nodiscc** [comment]
Ostatus based software already allows using RSS/Atom for publishing/syndication:

https://en.wikipedia.org/wiki/OStatus:

> OStatus is an open standard for distributed status updates that references a suite of open protocols including Atom, Activity Streams

https://github.com/tootsuite/mastodon/issues/160 (Allow grabbing posts from RSS feed):

> Go into settings > add RSS link > Mastodon auto grabs them for you. No messing around with an API, have a built-in option for it.

Or are you thinking about a specific feature/interaction?

**Comment by qwertygc** [comment]
I think a specific interaction : e.g webmention for comment.

**Comment by opitux** [comment]
Select what shaarli's link to share on Mastodon could be a great feature

**Comment by ArthurHoaro** [comment]
As @nodiscc said, from what I understand, OStatus is a specification regarding a suite of protocols, including ATOM to manage the content. And there is much Shaarli would do since it's only a publisher (we also have a PubSubHub plugin to push changes).

Another solution for Mastodon would be to use their API with a plugin like this one https://github.com/ArthurHoaro/shaarli2twitter.

**Comment by qwertygc** [comment]
@ArthurHoaro oh, amazing ! you have the same for facebook ?

**Comment by ArthurHoaro** [comment]
No I don't because I don't use the service, but I suppose it wouldn't be too hard to adapt the Twitter one to work with Facebook.

**Comment by nodiscc** [comment]
> Select what shaarli's link to share on Mastodon could be a great feature

@opitux You can use a specific tag to choose what you want to share to Mastodon (eg `sharethis`), and point the RSS feed source in mastodon to https://my.shaarli.url/?do=atom&searchtags=sharethis. Only posts tagged `sharethis` will be shared.

> Share RSS feed to facebook

@qwertygc Short from writing a facebook API plugin, I think there are automation tools (commercial/free or selfhosted) that can mirror a RSS/ATOM feed to Facebook (https://github.com/Kickball/awesome-selfhosted#automation https://trigger-happy.eu/ https://www.ifttt.com/ ...)

**Comment by ArthurHoaro** [comment]
I suggest that we close this as I do not wish to add social media API within Shaarli's code base.

**Comment by opitux** [comment]
@nodiscc 
I did not see your answer. Thanks for this tip :)

**Comment by nodiscc** [comment]
> I do not wish to add social media API within Shaarli's code base.

I agree, a combination of RSS/ATOM and proper tagging should fit most use cases related to automatically reposting Shaarli content on social networks. If those don't support ATOM sources the solutions listed at https://github.com/Kickball/awesome-selfhosted#automation should bridge the gap.

**Comment by nodiscc** [comment]
Related https://github.com/shaarli/Shaarli/issues/974
