### ISSUE TITLE
Migration to v0.9.0 failed (from old v0.5.3)

### ISSUE THREAD

**Issue by doc75** [shaarli/Shaarli#865]
Hello,

I just tried to migrate my old Shaarli instance (v0.5.3 according to shaarli_version.php)  to the new v0.9.0.

It failed with the following error message (reformatted to make it readable):
```
/**
 * Move old configuration in PHP to the new config system in JSON format.
 *
 * Will rename 'config.php' into 'config.save.php' and create 'config.json.php'.
 * It will also convert legacy setting keys to the new ones.
 */
 Method [ public method updateMethodConfigToJson ]
 { @@ /home/www-data/private/guillaume/shaarli/application/Updater.php 144 - 183 } An error occurred while running the update exception 'Shaarli\Config\Exception\MissingFieldConfigException' with message 'Configuration value is required for security.session_protection_disabled' in /home/www-data/private/guillaume/shaarli/application/config/ConfigManager.php:208
 Stack trace:
 #0 /home/www-data/private/guillaume/shaarli/application/Updater.php(177): Shaarli\Config\ConfigManager->write(true)
 #1 [internal function]: Updater->updateMethodConfigToJson()
 #2 /home/www-data/private/guillaume/shaarli/application/Updater.php(89): ReflectionMethod->invoke(Object(Updater))
 #3 /home/www-data/private/guillaume/shaarli/index.php(719): Updater->update()
 #4 /home/www-data/private/guillaume/shaarli/index.php(2263): renderPage(Object(Shaarli\Config\ConfigManager), Object(PluginManager), Object(LinkDB), Object(History))
 #5 {main}
```

Is there a list of the mandatory settings to add in my old config that could by-pass the issue ?
Otherwise is there a migration path that could work (by installing some intermediate versions) ?

Thanks.

**Comment by ArthurHoaro** [comment]
Hi!

> Is there a list of the mandatory settings to add in my old config that could by-pass the issue ?

Yes, here is the list of mandatory settings:

```
'credentials.login',
'credentials.hash',
'credentials.salt',
'security.session_protection_disabled',
'general.timezone',
'general.title',
'general.header_link',
'privacy.default_private_links',
'redirector.url', 
```
However, you need to use their legacy label in your PHP config, which you can [find here](https://github.com/shaarli/Shaarli/blob/master/application/config/ConfigPhp.php#L34).

Your issue is a bit surprising since the disable session protection setting has been around forever.

> Otherwise is there a migration path that could work (by installing some intermediate versions) ?

No, you should be able to upgrade from any version.

**Comment by doc75** [comment]
I started with shaarli when it was still maintained by sebsauvage.
I do not know why some parameters are missing.

Here are the one missing, with the line I added in `data/config.php`:
```
$GLOBALS['disablesessionprotection']=false;
$GLOBALS['titleLink']='?';
$GLOBALS['privateLinkByDefault']=false;
```
With those additional lines, the upgrade is done without error.

Thanks for your quick support.

Do you want me to close this incident, or do you plan a fix for supporting the old strange configuration ?

**Comment by ArthurHoaro** [comment]
Well, `disablesessionprotection` was already in Seb's version. I don't know why it wasn't present in your file, but I think that we can close this safely. :)
