### ISSUE TITLE
Theme glitch (default -> vintage) on a fresh install

### ISSUE THREAD

**Issue by virtualtam** [shaarli/Shaarli#866]
## Issue
After setting up a new instance, the theme switches from `default` to `vintage` when accessing the _Tools_ page

Reproduced in the following environments:
- `shaarli/shaarli:latest` Docker image
- development environment (Arch + PHP 7 + Apache HTTPD 2.4)

## Steps to reproduce:
- setup a new Shaarli installation (or just backup/wipe the `data/` dir on an existing one)
- fill the configuration form
- login to the newly configured instance
- go to the _Tools_ page

**Comment by ArthurHoaro** [comment]
Ah yes, I forgot to remove the update method switching to the vintage theme.
