### ISSUE TITLE
Persistent update message

### ISSUE THREAD

**Issue by n00b12345** [shaarli/Shaarli#867]
I've already updated to Shaarli v 0.9.0 but I still get a notification saying

    Shaarli 0.8.2 is available.

If this is a minor glitch, could you please consider taking a look? Thanks. Love the update!

**Comment by ArthurHoaro** [comment]
Thanks for the feedback.

**Comment by ArthurHoaro** [comment]
Hi, I've the version number in the `latest` branch (`v0.9.0` instead of `0.9.0`). Can you make sure that your setting `updates.check_updates_branch` points to `latest` and see if it fixed your issue?

**Comment by n00b12345** [comment]
Yes, that resolves the issue. Thanks for fixing it! I hope this will be integrated in 0.9.1 :)
