### ISSUE TITLE
404 error after deleting a link from it's own page

### ISSUE THREAD

**Issue by e2jk** [shaarli/Shaarli#87]
**How to reproduce:**

* Go to a link's own page (permalink)
* Delete the link
* You are returned to same page, but this time with a 404 error (as the link doesn't exist anymore)

**Suggested fix:**
If the url to be returned to is going to be a permalink, redirect instead to the home page.

**Comment by pikzen** [comment]
The easiest (and most logical) fix would be redirecting to / once the link has been deleted.

However, the current case handles passing around a redirect url to a ?do=<anything> page. Aside from being almost never used (Deleting a link from another page on another website ?), HTTP_REFERER is set differently on each browser and is almost always set to the previous page.
Opinions on removing all this referer parsing nonsense and just ALWAYS returning to / ?

**Comment by e2jk** [comment]
I think it is OK to just redirect to Shaarli's home page.
This would only be an issue when you want to delete multiple links from e.g. a search, but (1) how often does this use case happen and (2) you could click twice on the back button and you would be back to the page from which you clicked the delete button.

**Comment by e2jk** [comment]
I've created pull request #90 that redirects to ? (the default when `returnurl`or `HTTP_REFERER` were empty). Please review, test and merge.

**Comment by nodiscc** [comment]
Fixed in #90

**Comment by nodiscc** [comment]
@e2jk I frequently hit  this bug: 

> This would only be an issue when you want to delete multiple links from e.g. a search, but (1) how often does this use case happen and (2) you could click twice on the back button and you would be back to the page from which you clicked the delete button.

It's very annoying when you are trying to cleanup links with a certain tag. I think if either `$searchtags` or `$searchterm` are defined, we should add these params to the next request (so you would be redirected to the previous serach. Hitting back twice is confusing and annoying.

I'll aopen another issue for this.
