### ISSUE TITLE
Shaarli switches to vintage theme when no items

### ISSUE THREAD

**Issue by disanvparean** [shaarli/Shaarli#874]
Hello,
A strange thing just happened to me. I installed a new version of Shaarli (0.9.0) with an empty database (almost) and then when the two default items Shaarli switched from default theme to vintage theme. So I changed to theme in settings and it's working.
Thank you
/
Bonjour,
Une chose étrange m'est arrivée. J'ai installé une nouvelle version de Shaarli (0.9.0) avec une base vide (quasiment) et quand j'ai supprimé les deux liens par défaut Shaarli est repassé sur le thème vintage. J'ai rechangé dans les options et c'est bon.
Merci

**Comment by ArthurHoaro** [comment]
Hi! Yes, we did have an update method which switches the theme to vintage during the development of the default one. I'll be fixed in the next release.

duplicate of #866
