### ISSUE TITLE
Javascript ES6 syntax breaks functionality on older browsers (with default tpl)

### ISSUE THREAD

**Issue by kramred** [shaarli/Shaarli#875]
Hello there.
I'm still running iOS9.x on my mobile and Safari 9.x on the laptop and noticed that with the current version of Shaarli (dev) some functionality is broken.
Traced it to the [ES6 code](https://github.com/shaarli/Shaarli/blob/master/tpl/default/js/shaarli.js#L220) in shaarli.js of the new/default template.
[Using Babel](http://babeljs.io/repl/#?babili=false&evaluate=true&lineWrap=true&presets=env%2Ces2015&targets=&browsers=ie%20%3E%205%2C%20safari%20%3E%205&builtIns=false&debug=false&code=%20%2F**%0A%20*%20Autofocus%20text%20fields%0A%20*%2F%0A%20%2F%2F%20ES6%20syntax%0A%20let%20autofocusElements%20%3D%20document.querySelectorAll('.autofocus')%3B%0A%20for%20(let%20autofocusElement%20of%20autofocusElements)%20%7B%0A%20if%20(autofocusElement.value%20%3D%3D%20'')%20%7B%0A%20autofocusElement.focus()%3B%0A%20break%3B%0A%20%7D%0A%20%7D) or something similar one could back-port that to support also older (non-ES6) browsers; which I did for my installation and would suggest also in general.
What do you think? 
If you follow the babel link you could just copy the ES5 compatible code, or should I create a pull req.?

**Comment by ArthurHoaro** [comment]
Thanks for the report. This issue will be fixed with #819. As for Babel, there are ongoing discussion in #755 but in any case it'll have to be automated.

**Comment by ArthurHoaro** [comment]
Fixed by #819
