### ISSUE TITLE
What files do I need to backup to have a fully functional Shaarli?

### ISSUE THREAD

**Issue by aledeg** [shaarli/Shaarli#876]
I've read the issue #138 where there are some hints on what to backup. They are only hints and I couldn't find a detailed list of all the files and folders to backup.

Am I missing something?

**Comment by virtualtam** [comment]
Hi @aledeg!

For core functionality, Shaarli relies on the following files:
- `data/datastore.php` that contains all your bookmarked links
- `data/config.json.php` that contains Shaarli configuration

You can either backup/restore these files, or dump the datastore using the Netscape bookmark format, see https://github.com/shaarli/Shaarli/wiki/Backup%2C-restore%2C-import-and-export

Then, depending on your usage, you might have installed custom themes and plugins, or written custom HTTP server rules, which are worth backuping.

For more details, you can take a look at the _Setup_ section of the Wiki:
- https://github.com/shaarli/Shaarli/wiki/Shaarli-configuration
- https://github.com/shaarli/Shaarli/wiki/Server-security
- https://github.com/shaarli/Shaarli/wiki/Server-configuration

**Comment by aledeg** [comment]
Thank you for your answer. I am using a pretty simple configuration so I guess my backup process will be pretty straightforward.
I just need to remember to backup my .htaccess file.
