### ISSUE TITLE
Improvements to the new default template

### ISSUE THREAD

**Issue by nodiscc** [shaarli/Shaarli#877]
Hi, I finally got around to updating Shaarli on my actual personal server (I manage it via ansible, got busy, and was too lazy to update my playbook, now [I've catched up](https://github.com/nodiscc/srv01/tree/master/roles/webapp-shaarli)!)

While I find the new default template better in many regards (overall aesthetics, accessibility/usability, better tagcloud/daily/picwall, ...), there is _one_ thing where I find it's actually less good at, compared to the vintage template, and that is actually browsing/taking a quick glance at posted links.

Sorry for opening such a generic issue, It's hard to precisely tell what I find "wrong". One thing is that the vintage template allowed displaying many more links at once on my display, whereas I need to scroll a lot with the new default. It makes it harder to "pick" a random link to discover. It was also clearer on the old template that tags are actionable items/links. Attached screenshots of a comparison between 2 templates on my Shaarli

![shaarli-new-template](https://cloud.githubusercontent.com/assets/3950390/26211264/7730425e-3bf2-11e7-84c9-b055d65ce9f7.png)

![shaarli-vintage-template](https://cloud.githubusercontent.com/assets/3950390/26211256/7029b4f4-3bf2-11e7-9258-f26a2e9e3d8e.png)

Maybe it's because of my use case (not very microblog/blog-oriented, just dumping links for quick sharing, lazy use of tagging...), maybe the whitespace is actually excessive (I have nothing against whitespace in general), maybe it's just personal taste? Anyway I have set my Shaarli to use the new template and will see if I get accustomed to it/will try to get feedback from visitors.

What do you think? I am no UX expert, I'd like to know if other users noticed that, or something else. We can open separate issues if we find things to improve.

congratz @ArthurHoaro for the new template which I find overall _much_ better.

**Comment by ArthurHoaro** [comment]
Thanks! Yes, there are larger margin and bigger fonts and the UI is overall less overcrowded, which I think is a good thing. Maybe we can play with some of them to display more content, but it won't change a lot.

However, your issue is more related to thumbnails, especially without descriptions, which creates *a lot* of whitespace. I didn't really test this case, since only few links generate thumbnails for now. However, that might change.

I'm not sure how to solve this though. Reducing margin is doable but probably won't be enough. If you have an idea... I'll to play with it anyway.

> It was also clearer on the old template that tags are actionable items/links

Tags were circled first, some people didn't like it, so I removed it. I think it's really a matter of taste, but the icon makes it pretty obvious that they're tags ; which are clickable on almost any tool/website which use tags or category (otherwise what's the point 😄).

**Comment by nodiscc** [comment]
I've tried removing the padding for `.linklist-item-thumbnail` (set it to 0) https://github.com/shaarli/Shaarli/blob/master/tpl/default/css/shaarli.css#L623 and it looks a little bit better. This creates weird alignment with the description when there is one present, setting the margin for `.markdown p` https://github.com/shaarli/Shaarli/blob/master/plugins/markdown/markdown.css#L7 to 0 fixes that.

It's still not enough for my taste (number of links displayed at once is still very low), but definitely better (reduced margin also looks better on text-only - no thumbnails - shaares). I did a quick test edit in Firefox inspector and forgot to take screenshots, let me know if you need them.

`addlink toolbar` plugin also worsens the issue (I have disabled it for now), since the `Add link` field displays below search fields. In the vintage template it was added on the same line as the search fields.

**Comment by nodiscc** [comment]
Another problem I encountered is that there are badly aligned elements when the browser window is resized to certain arbitrary widths, or zoomed in/out. Attaching a screenshot of my Shaarli when zoomed out. This can be reproduced by playing with the browser zoom controls, or resizing the browser window to different widths. It sometimes looks fine, sometimes not.

Let me know if I should open another issue for this.


![zoom](https://user-images.githubusercontent.com/3950390/27088084-02dd795c-5057-11e7-8934-aa21909f5bcf.png)

**Comment by alexisju** [comment]
It could be also useful to add some specific css class and id  (and not only the pure's one) to several contents to make more easy user.css styles (i.e. : shaarli's title, menu bar, menu's item, searchform,...).

**Comment by alexisju** [comment]
I insist on my latest comment about the need to have better classes and id on the current template to allow easiest custom css. I'm tired to maintain a full template, which can be broken to each single Shaarli new version.

**Comment by ArthurHoaro** [comment]
A bunch of improvements has been merged with #978. 

Is there other things that should be improved regarding the theme? Or can we close this issue?

**Comment by alexisju** [comment]
Some more new id/class in the header file (ie: shaarli's title in the menu)?
