### ISSUE TITLE
empty page when clicking on a tag (tag cloud)

### ISSUE THREAD

**Issue by alexxtasi** [shaarli/Shaarli#88]
Hi all
I had shaarli 0.0.41 installed and was everything alright
I upgraded to version 0.0.42, but then I see an empty page whenever I click Tag Cloud > some_tag (and not the list of the links with the specific tag!)

I used both suggested upgrade methods (copy-pasting ```datastore.php``` file and also import-exporting .html file from the older to the newest version of Shaarli)

any suggestions on this ?
regards

> it also happens when viewing the shaarli's list (home page) and clicking on a tag...

**Comment by e2jk** [comment]
Is there anything specific logged in the `log.txt`file, or in the access or error logs of your web server?

**Comment by nodiscc** [comment]
@alexxtasi what page URL is displayed after clicking on `some_tag`?

**Comment by alexxtasi** [comment]
@e2jk nothing spesific... just ```2015/01/02_03:18:50 - ip - successful```

@nodiscc its ```http://server_ip/links/?searchtags=electronics``` for example...
and as far I understand its correct (I have another instance of shaarli version 0.0.41 with the same .html file imported and the link ```http://127.0.0.1/shaarli/?searchtags=electronics``` works fine)

do I miss something ?

**Comment by e2jk** [comment]
Is there actual content on the page (albeit possibly invisible), or is there no content sent back from the webserver? Can you look at the page's source (usually Ctrl + U), or opening the web developer tools (usually pressing F12) and looking at the request and response?

**Comment by alexxtasi** [comment]
Not sure of what it is (newbie here) but in the web dev tools and in Network tab I see ```500 Internal Server Error``` in the GET method.

does this help ?

**Comment by nodiscc** [comment]
@alexxtasi your server sends a `500` error on `http://83.212.100.244/links/?searchtags=tag-name-here`. Details should be logged in your server's `error.log`. Is there something relevant there? Do you have `mod_rewrite` or equivalent enabled or a special server config trick? If there is nothing informative in the error log, you can try to increase PHP `error_reporting` level `in php.ini`

**Comment by alexxtasi** [comment]
apache's access log shows:
```
ip - - [02/Jan/2015:14:59:01 +0200] "GET /links/?addtag=tag-name HTTP/1.1" 302 -
ip - - [02/Jan/2015:14:59:01 +0200] "GET /links/?searchtags=tag-name HTTP/1.1" 500 -
```
while error log shows:
```
[Fri Jan 02 14:59:01 2015] [error] [client ip] PHP Notice:  Undefined index: searchtags in /path/to/shaarli/index.php on line 1275, referer: http:/server_ip/links/
[Fri Jan 02 14:59:01 2015] [error] [client ip] PHP Fatal error:  Call to undefined function mb_convert_case() in /path/to/shaarli/index.php on line 820, referer: http://server_ip/links/
```
I see that ```mb_convert_case()``` is not present in version 0.0.41 am I right ? Is this the problem on my server?

**Comment by alexxtasi** [comment]
well I installed ```php-mbstring```, and restarted apache.
Only the first error
```
PHP Notice:  Undefined index: searchtags in /path/to/shaarli/index.php on line 1275, referer: http:/server_ip/links/
```
remains in the error log.
But the link's list based on tags is displayed nicely... so I think this is ok isn't it ?

**Comment by pikzen** [comment]
Ah, this has been introduced by patch #82, I wasn't aware that PHP had an mbstring module. This should probably be noted in the wiki and README.

As far as the Notice goes, there are probably a hundred of those all around the code if you enable every error_reporting. You'll be fine, it's no problem. Going to do a huge pass with linting, code fixing etc. soon that should remove every notice. Spamming the error log with them isn't exactly a good thing.

**Comment by nodiscc** [comment]
@alexxtasi I see you're running CentOS (by the way you may want to hide some info your server sends, search for the `ServerTokens` apache setting), mind that installing `php-mbstring` seems to be RH/CentOS specific. There is no such package in Debian-based distros (https://packages.debian.org/search?keywords=mbstring) because mbstring support is compiled in the base [libapache2-mod-php5](https://packages.debian.org/wheezy/libapache2-mod-php5).

I'm closing this and adding a not about centos install in the wiki. Thanks for your input.

**Comment by alexxtasi** [comment]
indeed I am using CentOS and I was installed with ```yum install php-mbstring```
thanks for your help!
