### ISSUE TITLE
The search-buttons in linklist.html are mutually exclusive

### ISSUE THREAD

**Issue by Lucas-C** [shaarli/Shaarli#885]
This is a bug report.

When a user clicks on either one of the magnifying glass icons at the top of the main view, in the search form, the other search input is ignored and discarded :

<img width="100%" alt="2017-05-30 16_15_19-liens utiles et a partager" src="https://cloud.githubusercontent.com/assets/925560/26587698/59e9fe00-4553-11e7-889e-da9efe042738.png">

For example, with `foo` in the text input and `bar` in the tags input :
- when clicking on the (left) text button, the tag query term is discarded
- when clicking on the (right) tag button, the text query term is discarded

I can send a PR to fix this.

Do you agree this is a bug ?

**Comment by ArthurHoaro** [comment]
No, I'd say it's a feature request. But the back-end already supports crossed search, so yes I think you can easily provide a PR.

**Comment by Lucas-C** [comment]
I sent a PR

**Comment by Lucas-C** [comment]
Damn, I forgot the header :(

**Comment by Lucas-C** [comment]
PR updated
