### ISSUE TITLE
Weird behavior when removing lable -

### ISSUE THREAD

**Issue by Esak8** [shaarli/Shaarli#886]
Hi,

When one try to remove the label **-**, this remove the first label defined on each links.

Let's take an example :  

![capture1](https://cloud.githubusercontent.com/assets/28948020/26603777/571d4080-4588-11e7-8a80-861fbbb4795d.png)

I try to delete the label **-**.
![capture2](https://cloud.githubusercontent.com/assets/28948020/26603811/76ccd166-4588-11e7-922f-211af99329ae.png)

This shouldn't affect any link because there is no label **-**, except it does...
![capture3](https://cloud.githubusercontent.com/assets/28948020/26603850/953ba730-4588-11e7-82aa-e58770b28dda.png)

Here is the result :  
![capture4](https://cloud.githubusercontent.com/assets/28948020/26603861/9fc4f094-4588-11e7-9f75-15ac8ca0ee0d.png)

If one keep trying to delete the label **-**, it will end up deleting all tags.

**Comment by Esak8** [comment]
PS : Tests were carried out on both the last release (**v0.9.0**) and the last version (**master**)

**Comment by ArthurHoaro** [comment]
Good catch. Tag deletion uses the tag search function, and `-` is a meta character for an exclusion search. So it returns all links not containing an empty tag, i.e. all links. Then it removes `$tags[false]` in the list, which is a PHP equivalent to `$tags[0]`.

Note that it shouldn't be possible to have a tag starting with a `-`. If you do, please remove the string `updateMethodRenameDashTags` from your `data/updates.txt` file.

**Comment by Esak8** [comment]
Hi,

Thanks for the explanation.

Actually, I did originally have a dash tag. It was created after importing bookmarks from safari.

Maybe those character (meta character, etc.) should be filtered out while importing bookmarks into Shaarli.

I'll create another issue if needed.

**Comment by virtualtam** [comment]
Thanks @Esak8 & @ArthurHoaro !

Bookmark import / parsing issues are to be raised on https://github.com/shaarli/netscape-bookmark-parser; Safari exports (with e.g. dummy links and folders) are also welcome there, see existing test input: https://github.com/shaarli/netscape-bookmark-parser/tree/master/tests/input

**Comment by ArthurHoaro** [comment]
Well, while bookmark parsing is handled by the parser, the fact that Shaarli doesn't support tags starting with a `-` should be handled by Shaarli. So yes, you can open another issue.

But as @virtualtam said, if you can provide Safari input data four our tests, it would be nice.

**Comment by Esak8** [comment]
Ok, I opened another issue for that : #892

**Comment by ArthurHoaro** [comment]
Thank you!
