### ISSUE TITLE
Document Docker + HTTP reverse proxy configuration

### ISSUE THREAD

**Issue by virtualtam** [shaarli/Shaarli#888]
https://github.com/shaarli/Shaarli/wiki/Reverse-proxy-configuration

Relates to #879

TODO:
- [x] Apache 2.4 example
- [x] HAProxy example
- [x] Nginx example
- [x] features:
    - HTTP headers / forwarded information
    - SSL termination

**Comment by thewilli** [comment]
> nginx example

@virtualtam  here's a working one (including HTTP forwarding header and SSL termination):

```
server {
	listen 443 ssl http2;
	server_name my-shaarli.tld;
	include /etc/nginx/ssl.conf; # ssl configuration

    location / {
        # forwarding information
        proxy_set_header        X-Real-IP $remote_addr;
        proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header        X-Forwarded-Proto $scheme;
        proxy_set_header        X-Forwarded-Host $host;

        # actual forwarding settings
        proxy_pass http://shaarli.docker/;
        proxy_set_header Host      $host;
        proxy_connect_timeout  30s;
        proxy_read_timeout  120s;

        # logging
        access_log      /var/log/nginx/shaarli.access.log;
        error_log       /var/log/nginx/shaarli.error.log;
    }
}
```

I omitted the caching settings and content of the ssl configuration for the sake of simplicity (nothing special or Shaarli-related about these).

**Comment by bvberkum** [comment]
Example using jwilder/nginx-proxy:
```
docker run 
  --env VIRTUAL_HOST=shaarli.local \
    shaarli/shaarli:latest
```
```
curl -H "Host: sitefile.wtwta.org" http://localhost/
```

I'm not using it for the moment, but I think there's a traefik docker example too.

I can create PR for it to add the docker examples to docker/reverse-proxy-config.
