### ISSUE TITLE
Firefox Share service falls on a 404 error

### ISSUE THREAD

**Issue by Deuchnord** [shaarli/Shaarli#895]
My Shaarli instance is hosted in a sub-folder on my personal website, so that its URL has the `https://www.domain.tld/shaarli/` form.

According to my access logs, it seems that the URL Firefox Share tries to fetch is the following:
```
https://www.domain.tld/shaarli%7bnoparse%7d?post=http://a-url.com&source=firefoxsocialapi%257B%252Fnoparse%257D
```

instead of:
```
https://www.domain.tld/shaarli/%7bnoparse%7d?post=http://a-url.com&source=firefoxsocialapi%257B%252Fnoparse%257D
```
In other word: a `/` is missing after the `/shaarli` at the begining of the URL and this makes the Firefox Share service fall in a 404 error.

**Comment by ArthurHoaro** [comment]
Hi, thanks for the report. You're problem here isn't about the `/`, but that I moved Firefox Social function to a JS file, while `{noparse}` is an instruction for RainTPL. I'll provide a PR to fix it.
