### ISSUE TITLE
Running shaarli 0.9.0, it says:  "Shaarli 0.7.0 */ is available"

### ISSUE THREAD

**Issue by pepa65** [shaarli/Shaarli#898]
I just started Shaarli 0.9.0 from a fresh install, and up pops:  "Shaarli 0.7.0 */ is available"

**Comment by ArthurHoaro** [comment]
Hi, see #873 and more specifically [this commit](https://github.com/shaarli/Shaarli/commit/c318096c7a6fb3f6b00bd8c694ab7acb8fbb7cd0) to fix this issue.

**Comment by pepa65** [comment]
Thank you. I hope you understand I did search through the issues for this but didn't find #873
