### ISSUE TITLE
Merge conflict text in page.footer template

### ISSUE THREAD

**Issue by smuth4** [shaarli/Shaarli#900]
https://github.com/shaarli/Shaarli/blob/master/tpl/default/page.footer.html#L1

![http://i.imgur.com/uwPMXjv.png](http://i.imgur.com/uwPMXjv.png)

I'm kind of sure about what it should be, but don't want to presume.

**Comment by nodiscc** [comment]
Thanks! I missed that when merging https://github.com/shaarli/Shaarli/pull/772

The fix is pending in https://github.com/shaarli/Shaarli/pull/901
