### ISSUE TITLE
How to use/enable the api 

### ISSUE THREAD

**Issue by emixam150** [shaarli/Shaarli#903]
I recently installed shaarli V0.9 on my personal server : https://shaarli.buron.coffee 
And I want to use the api, but it seems that it doesn't works. 

I first tried directly URL for example : https://shaarli.buron.coffee/api/v1/info. And I get a 404 error. 

And I tried the [Python-client](https://github.com/shaarli/python-shaarli-client) and it was the same result.

What I have to do to solve this ?

**Comment by virtualtam** [comment]
Hi @emixam150 !

How is your web server configured?

URL rewriting must be enabled for the REST API to work, see https://shaarli.readthedocs.io/en/master/Server-configuration

More specifically:
- Apache:
    - `mod_rewrite` is enabled, and user-specific `.htaccess` rules are allowed
    - https://shaarli.readthedocs.io/en/master/Server-configuration/#htaccess
- Nginx: 
    - URL rewriting is enabled
    - https://shaarli.readthedocs.io/en/master/Server-configuration/#redirect-http-to-https

**Comment by emixam150** [comment]
Hey, thank you a lot for your response. You was right, I forget to check my apache configuration and I just have to add this in the site conf file: 
```
<Directory /var/www/shaarli/ >
	AllowOverride All
</Directory>
```
By the way, do you know if there is a node.js module to handle with the api ?

**Comment by virtualtam** [comment]
You're welcome @emixam150 ;-)

> By the way, do you know if there is a node.js module to handle with the api ?

Not that I know of, this should be simple to write:
- following the API specification: https://shaarli.github.io/api-documentation/
- using the Python client as an example: https://github.com/shaarli/python-shaarli-client

**Comment by emixam150** [comment]
Thanks, I will try to do something :)
