### ISSUE TITLE
request for API tag methods

### ISSUE THREAD

**Issue by ghost** [shaarli/Shaarli#904]
Hello,
I am just wondering what you are thinking of adding method to the API to handle with tags ? There could be different actions like : 

- **get** all tags
- **delete** a tag
- **rename** a tag

**Comment by Vantablack** [comment]
Hi! Is anyone working on this? I have a rough idea on how to implement this by using https://github.com/shaarli/Shaarli/blob/da95579da7455d3b59723306edc6f41192f531a3/index.php#L842 which will return a list of tags (?) 

And from there I would assume creating a Tags.php Controller under [application/api/controllers](https://github.com/shaarli/Shaarli/tree/master/application/api/controllers)?

**Comment by ArthurHoaro** [comment]
Hi! 

I'm not aware of any ongoing development about this.

> which will return a list of tags (?)

This method will return an associative array with `tag name` => `number of occurrences`. A `LinkDB` instance is injected in API controllers by the middleware.

Note that you will also have to write unit tests for your `Tags` controller.

**Comment by Vantablack** [comment]
@ArthurHoaro Thanks for the prompt reply, I would love to help out in the development, however, may I know which IDE/tools would I use to get started with?

**Comment by virtualtam** [comment]
@Vantablack any text editor with PHP support will do, so you can pick your favorite one: Atom, Sublime Text, Eclipse, PHPStorm, vim, emacs...

If I remember correctly, @ArthurHoaro uses JetBrains' PHPStorm, which is a good option if you're used to JetBrains products (IntelliJ IDEA, PyCharm, Cliion, etc.) and are not that familiar with PHP.

The documentation is a good starting point to get accustomed to the development process:
- https://shaarli.readthedocs.io/en/master/
- https://shaarli.readthedocs.io/en/master/Development-guidelines/
- https://shaarli.readthedocs.io/en/master/Continuous-integration-tools/
- https://shaarli.readthedocs.io/en/master/Directory-structure/
- https://shaarli.readthedocs.io/en/master/Unit-tests/
- etc.

As the docs have been written by -and are mainly used by- Shaarli maintainers/developers, there may be some rough edges here and there, so any feedback to improve them will be much appreciated ;-)

Existing code and tests are also a good reference to delve into the codebase and see how things work and interact.
