### ISSUE TITLE
API always returns 401

### ISSUE THREAD

**Issue by EorlBruder** [shaarli/Shaarli#905]
I am trying to write some code interacting with the API and whatever I do, I get "Not authorized" back. 
In an attempt to troubleshoot this I used the example from the docs https://shaarli.readthedocs.io/en/master/REST-API/#complete-example and this too fails completly. I adjusted $secret to reflect my "API secret", the $apiEndpoint to be "$myshaarli/v1/api/links". 
In Shaarli "Enable REST API" is set. Did I forget something?

**Comment by virtualtam** [comment]
Hi @EorlBruder !

This example looks outdated, as the JWT token is passed using the `Authorization` HTTP header as per #751 , see https://shaarli.github.io/api-documentation/

**Comment by EorlBruder** [comment]
Okay, thanks for clarifying that. 
Aside from the PHP-Example I was actually using the Authorization header and it's still not working. I am suspecting my JWT-Class isn't doing what it should do here. I am using this implementation:  https://java.jsonwebtoken.io/

Following kotlin Code isn't working as expected: 
`        val iat = Date()
        logger.debug((iat.time / 1000).toString())
        val token = Jwts.builder().setHeaderParam("typ", "JWT").setIssuedAt(Date())
                .signWith(SignatureAlgorithm.HS512, "mysecret").compact()
        logger.debug(token)

        val result = get("myshaarliurl/api/v1/links", headers = mapOf("Authorization" to "Bearer $token"))
        logger.debug(result.text)`
IAT returned 1501238004
Token returned eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE1MDEyMzgwMDR9.sgvjkXZiFtk1GprWSeWGKGWvdU7fO6qf0Y9fRBftRIGCS_7hv9HPUyyZvApdaixdBwmEj7cypZd6F241gbm_6Q
(This token was generated with "mysecret" and the above IAT)
With the proper secret I still got a 401.

**Comment by virtualtam** [comment]
You might be interested in this Kotlin/Java example provided by @Braincoke:
- https://github.com/shaarli/api-documentation/issues/33
- https://gitlab.com/snippets/1665808

**Comment by EorlBruder** [comment]
@virtualtam  Thank You! That snippet helped me and now it's working.

**Comment by virtualtam** [comment]
Glad I could help!
