### ISSUE TITLE
A node.js api client

### ISSUE THREAD

**Issue by laBecasse** [shaarli/Shaarli#915]
Hello everyone, 
I made a client for shaarli api in node.js: [shaarli-api](https://github.com/laBecasse/shaarli-api). 
I hope that some of you can test it ;)

**Comment by ArthurHoaro** [comment]
Hi! Thanks for the feedback, that's nice, I'll give a try later.

However, you only implemented 3 out of 7 endpoints, and let out the GET and PUT link methods which are kind of essential. :)

**Comment by laBecasse** [comment]
Yes it is just a begin, but I will add the two endpoints you mention pretty soon.

**Comment by laBecasse** [comment]
Now there are 6 of the 7 endpoints :smile:

**Comment by virtualtam** [comment]
Thanks @laBecasse ;-)

To avoid confusion, I'd suggest renaming:
- the project & node package to `shaarli-client` or `shaarli-api-client`
- the main class to `ShaarliApiClient` or `ShaarliApiV1Client`

**Comment by laBecasse** [comment]
Hep, I understand my mistake, but actually I just can't rename the npm module : https://www.gregjs.com/javascript/2016/how-to-rename-a-published-npm-module/

So I don't know what to do to keep all stuff coherent. Any idea ?

**Comment by virtualtam** [comment]
The linked article provides good advice, but this mostly applies when you're providing a library/project that people start using and rely on; I'm not familiar with NPM's internals, but you should be able to opt for one of the following:
- create a new project, delete the old one
- create a new project, mark the old one as deprecated and add a redirection notice

Deletion might be available from the NPM management interface, or you may have to contact a platform administrator / a mailing list to ask for its removal.

Nevertheless, you can still:
- edit the project's description to highlight it is an API client
- pick suitable class names for API usage

**Comment by laBecasse** [comment]
Ok, I think that the name is corrected in all places, now ;)

**Comment by virtualtam** [comment]
Cool! Thanks @laBecasse for updating the NPM library, I'll add it to the Shaarli documentation ;-)

**Comment by virtualtam** [comment]
Closing as the library has been added to the Shaarli docs :)
