### ISSUE TITLE
● Shaarli 0.7.0 */ is available.

### ISSUE THREAD

**Issue by Sigri44** [shaarli/Shaarli#922]
Salut à tous !

Je viens de dL la version 0.9.0 sur le release de GitHub, et sans arrêt en haut j'ai la notification "● Shaarli 0.7.0 */ is available." alors que j'ai la 0.9.X.

Une idée ??

Merci

**Comment by ArthurHoaro** [comment]
Hi, see #873 and more specifically [this commit](https://github.com/shaarli/Shaarli/commit/c318096c7a6fb3f6b00bd8c694ab7acb8fbb7cd0) to fix this issue.
