### ISSUE TITLE
URL is set to 'http://' when converting a bookmark to a note

### ISSUE THREAD

**Issue by virtualtam** [shaarli/Shaarli#926]
### Use case
- archive some interesting link
- find other related interesting links
- convert the initial bookmark to a note (delete the URL) containing all of this interesting stuff in its description

### Steps to reproduce
- create a bookmark from a link URL
- optional: edit the title and description
- save the bookmark
- edit the bookmark
- delete the bookmark's URL
- save the bookmark

### Expected result
- the URL field contains the note's permalink

### Actual result
- the URL field is set to `http://`

**Comment by ArthurHoaro** [comment]
It also happens if you create a link without URL.
