### ISSUE TITLE
Firefox Social - service title is '{$shaarlititle}'

### ISSUE THREAD

**Issue by 10bass** [shaarli/Shaarli#929]
If I add Shaarli to Firefox Social, it shows up with the name {$shaarlititle}, rather than a defined title.
It looks like this is set in tpl/default/js/shaarli.js, line 631 - I have a title defined in data/config.json.php under general (which works fine for general usage) - should I be setting it somewhere else as well?

I can fix it easily in Firefox's social.manifest preference once it's added, at least.

Using Firefox 55.0.2, Shaarli 0.9.1, though this behavior has also come up with older versions of Shaarli and Firefox.

**Comment by ArthurHoaro** [comment]
Yes, it was a RainTPL variable, and got lost when it was moved to a dedicated JS file.
