### ISSUE TITLE
Tag cloud sorts in reverse alphabetical order

### ISSUE THREAD

**Issue by 10bass** [shaarli/Shaarli#932]
Was this an intended change? In index.php, line 806 calls alphabetical_sort with reverse = true. Easy for me to switch, it was just unexpected since it wasn't mentioned in the changelog. It looks like this changed with commit aa4797ba3679b847adc895e2f817ac058779a171.

**Comment by ArthurHoaro** [comment]
That wasn't intended, I was more focused on the tags list in this PR. Thanks for the report!
