### ISSUE TITLE
'remember me' is enabled by default on default theme's login page (was not in 'vintage')

### ISSUE THREAD

**Issue by thewilli** [shaarli/Shaarli#936]
The vintage theme has the `remember me` checkbox of the login form [disabled by default](https://github.com/shaarli/Shaarli/blob/da95579da7455d3b59723306edc6f41192f531a3/tpl/vintage/loginform.html#L27) while it is [enabled by default](https://github.com/shaarli/Shaarli/blob/da95579da7455d3b59723306edc6f41192f531a3/tpl/default/loginform.html#L32-L33) in the new default theme.

The behavior of the new theme could possible lead to a situation where one forgets to uncheck the box and stays loggedin on an untrusted, public computer (while the other way round you just need to login again).

Would you accept a PR that either

- reverts the default theme to the behavior of the vintage theme (unchecked by default)
- introduces a new setting to set the default state of the checkbox for all themes (all external themes would have to adapt to this)

**Comment by ArthurHoaro** [comment]
I may have changed that thinking users most likely want to stay logged in, but I agree that it could lead to privacy issues. Sure, I would accept such a PR. Note that this setting would have to be manually set in the config file. We try to keep the Configure screen clean.
