### ISSUE TITLE
allow wildcards when searching for tags

### ISSUE THREAD

**Issue by thewilli** [shaarli/Shaarli#937]
I am using prefixed tags (e.g. `customer-A, customer-b, lang-css, lang-js, ...`) and would like to use wildcards when searching for links. So if searched for `lang-*`,  I would find all tags (links with tags) that start with `lang-`.

Would you accept a PR that introduces asterisks as wildcard placeholders when searching for tags? The only implication I can think of is that searching for tags containing asterisks could possibly return more results than expected.

**Comment by ArthurHoaro** [comment]
That's a good idea. 👍 

In the meantime, you can use the full text search with `lang-`, which also search in tags.

**Comment by thewilli** [comment]
@ArthurHoaro I did a [first working implementation draft](https://github.com/thewilli/Shaarli/tree/wildcardsearch).

My approach was to replace the current search algorithm which does a lot of array joining and splitting with something a little bit more *straightforward* by using regular expressions and only one check per search. My current approach linked above builds a single expression out of the search term containing and matches them against the `tags` property of each item. Even the negation (prefixing tags with a minus) can be (is already) realized this way.

While at least from my point of view this looks promising I'm struggling with [this part](https://github.com/shaarli/Shaarli/blob/de901736a663934c1b67f09f1d586da665f0f036/application/LinkFilter.php#L381) where each single provided tag is also matched against the description - prefixed with a '#'. Having those two *tag sources* of course induces an additional overhead.

What do you think about this description search? Is it really required (why not search tags only in the `tags` property)?
