### ISSUE TITLE
Drop support for legacy PHP v5.5

### ISSUE THREAD

**Issue by thewilli** [shaarli/Shaarli#943]
PHP 5.5 is [retired (EOL)](https://secure.php.net/eol.php). 

Please don't [list it as supported](https://shaarli.readthedocs.io/en/master/Server-requirements/#supported-versions) anymore and allow plugin and Shaarli devs to use more modern stuff :wink:

**Comment by ArthurHoaro** [comment]
We'll drop PHP 5.5 compatibility with the next major release (`v0.10`). Note that it might take a while.

**Comment by virtualtam** [comment]
@thewilli note that a PHP version being EoL doesn't mean we won't support it, as a fair amount of Shaarli users are using shared hosting solutions where they may not have access to recent/stable/patched server package versions.
