### ISSUE TITLE
Private share not deleted using bulk delete with new template

### ISSUE THREAD

**Issue by ErwanLeroux** [shaarli/Shaarli#949]
I installed https://github.com/shaarli/Shaarli/releases/tag/v0.9.1 on a new server today and I noticed a problem with the new template : The selected private share checked are not deleted by bulk delete.
I selected one link and clicked on delete :
![image](https://user-images.githubusercontent.com/1643338/29751950-4b071f1a-8b55-11e7-866a-4df2945253d7.png)
Then I click sur ok :
![image](https://user-images.githubusercontent.com/1643338/29751964-6a450af4-8b55-11e7-9f23-6daa6c1a00bc.png)
Nothing happened

It may be connected to these php errors I found in the log
```
[Sun Aug 27 18:29:05.620534 2017] [:error] [pid 12426] [client 127.0.0.1:33272] PHP Notice:  Undefined variable: link in /var/www/shaarli/index.php on line 1340
[Sun Aug 27 18:29:05.621621 2017] [:error] [pid 12426] [client 127.0.0.1:33272] PHP Notice:  Undefined variable: link in /var/www/shaarli/index.php on line 1351
```

**Comment by thewilli** [comment]
@ErwanLeroux I can't reproduce this, neither with the current master nor with v0.9.1 using PHP v5.6 and Apache on Linux.

What browser, web server and PHP version are you using?

**Comment by ErwanLeroux** [comment]
I have php v7.0.19-1 and apache 2.4.5 on debian 9.

I have found something, I can delete all private share but the last. With 2 privates shares and nothing else, when I select the two of them and click ok in the popup, the most recent is deleted, not the other one.

**Comment by thewilli** [comment]
@ErwanLeroux ok, I can reproduce it and found the source of this issue. Expect a PR around tomorrow :wink:

**Comment by ErwanLeroux** [comment]
Thanks !
