### ISSUE TITLE
Fix coding style (static analysis)

### ISSUE THREAD

**Issue by nodiscc** [shaarli/Shaarli#95]
A pass of an automatic coding style fixer may be needed to make shaarli more maintainable.
This will help find and trim down unnecessary complexity/broken code.

**Comment by nodiscc** [comment]
I think this should be the first thing to do once 0.9 beta is released. There are several style fixers available, https://github.com/FriendsOfPHP/PHP-CS-Fixer is one.

**Comment by virtualtam** [comment]
A good start would be to submit the PHP code to a static code analyzer (here's an [article](http://blog.codacy.com/2014/05/06/php-static-analysis-tools/) listing some).

What is likely to be detected:
* code formatting:
 * indentation,
 * lines too long (>80 chars),
 * parenthesis, commas, (trailing) spaces, tabs...
* variables assigned and never used,
* functions/methods:
 * unused arguments,
 * complexity (# variables, # statements).

Benefits of static analysis:
* functionality: almost none;
* development:
 * helps defining a shared coding convention,
 * spot typos, undefined variables and other editing glitches,
 * when the # of detected issues has become low, instant spotting of typos!

How you can encourage devs to use it:
* Makefile with shortcuts to testing tools:
 * static analysis,
 * dynamic analysis,
 * unitary tests,
 * functional tests;
* Travis setup to run tests after a commit is pushed on GH.

A first run of PHP Code Sniffer on `index.php` returns 900+ errors and warnings, most of them being valid:
```
 2601 | ERROR   | [ ] Expected "if (...) {\n"; found "if (...) { "
 2601 | ERROR   | [x] No space found after comma in function call
 2601 | WARNING | [ ] Line exceeds 85 characters; contains 110
      |         |     characters
 2601 | ERROR   | [x] Closing brace must be on a line by itself
 2602 | ERROR   | [ ] Expected "if (...) {\n"; found "if (...) { "
 2602 | ERROR   | [x] No space found after comma in function call
 2602 | ERROR   | [x] Closing brace must be on a line by itself
 2602 | WARNING | [ ] Line exceeds 85 characters; contains 142
      |         |     characters
 2603 | WARNING | [x] Inline control structures are discouraged
 2603 | WARNING | [ ] Line exceeds 85 characters; contains 106
      |         |     characters
```

Regarding code "fixers", I'm not a huge fan of having a tool altering a codebase by itself... sure, doing this by hand is tedious, but browsing your code is also a good way to spot bugs and inconsistencies (and learn things, too) :-)

**Comment by nodiscc** [comment]
I agree that "fixer" changes are not easy to review, we should be wary of automatic linting tools. Thanks for pointing to PHP Code Sniffer, it's something that can definitely be done (it doesn't have to be done all at once, small improvements and patches are welcome). I'll have a look at it.

**Comment by virtualtam** [comment]
A common usage is to fix warnings within / close to commit scopes, e.g.
* I'm working on a feature that requires modifying `function1()` and `function2()`,
* I'll submit a patch that contains:
 * functional changes (what's needed for the feature),
 * code cleanup for the two modified methods.

This, or a "code cleanup rampage" sprint ;-)

I should have some spare time in the upcoming weeks to look at this, plus #71; both being code-quality-related.

**Comment by e2jk** [comment]
Great suggestions. +1 for non-automatic changes (well, I guess I don't care
if it's automatic, as long as if it's not one big commit in git. If you
find a way to have an automatic tool change only one aspect at a time, it
makes it much more easy to review).

Having a Continuous Integration (e.g. TravisCI) would be great. When
submitting pull requests to Ampersand.js, I really like to see the messsage
indicating that the specific change hasn't yet been tested/passed CI
validation.

**Comment by nodiscc** [comment]
I get a lot of these errors using php-cs. What is expected/how to fix this?

` 120 | ERROR   | [ ] You must use "/**" style comments for a function comment`

There is no comment on line 120...

**Comment by nicolasdanelon** [comment]
@nodiscc you just run make ? or something else?

**Comment by nodiscc** [comment]
[`code_sniffer_full`](https://github.com/shaarli/Shaarli/blob/master/Makefile#L41)

**Comment by virtualtam** [comment]
This warning points to the multi-line comment on lines 116-118, which may be associated by CodeSniffer with the function declaration at line 120:
```php
//==================================================================================================
// Checking session state (i.e. is the user still logged in)
//==================================================================================================

function setup_login_state() {
    [...]
}
```

which could be replaced by:
```php
/**
 * Checking session state
 *
 * A bit more comments on what the function performs
 */
function setup_login_state() {
    [...]
}
```

**Comment by nodiscc** [comment]
Thanks @virtualtam, I will take care of these. Start small.

**Comment by virtualtam** [comment]
You're welcome :)

We can safely start with fixing:
* lines too long,
* comment formatting,
* indentation / extra of missing spaces / bracket stuff.

This will remove a lot of noise from the output of code checkers, and help spot more important issues.

_(Bonus section)_
Regarding comments, it could be neat to settle on a [Doxygen](http://www.stack.nl/~dimitri/doxygen/index.html)-like formatting (dunno if there are other tools more suitable for PHP), e.g.
```php
/**
 * Brief description of the function
 *
 * Longer description of the function (optional):
 * - it does this,
 * - and that,
 * - not to mention it's also good at doing this!
 *
 * @param $p1  Param description
 * @param $p2  Param description
 * @return What kind of object does the function return?
 */
function f($p1, $p2) {
    [...]
}
```

**Comment by nodiscc** [comment]
This one has become low priority for me (less time, reprioritizing issues). Anyone is free to work on it and submit a pull request (even small, partial fixes accepted)

**Comment by ArthurHoaro** [comment]
What about variable names? Should we use this: http://programmers.stackexchange.com/questions/149303/naming-classes-methods-functions-and-variables/149321#149321 ?

**Comment by virtualtam** [comment]
This will depend on the coding standard we adopt for Shaarli; I've been toying with the latest PHP Code Sniffer, and there are options to:
- specify a coding standard; PSR-1 and PSR-2 are available through Composer (though I don't get why there is no overall PSR to check both)
- filter which issues are displayed; this would enable removing a lot of noise in PHPCS' output, and make the makefile target more relevant to contributors

I'm a bit perplexed by the syntax suggested for dosctring comments, too, being used to the Doxygen format (which works very good for PHP projects).

**Comment by virtualtam** [comment]
Just ran Code Sniffer using the available (popular) standards: PEAR _(default)_, PSR1, PSR2, Zend (#276 provides a generic makefile rule)

Common warnings:
- line length
- indentation
- access to globals
- forbidden PHP closing tag for included files: `?>`

PEAR-specific warnings
- docstring formatting

PSR-specific warnings
- namespace usage
- side-effects, a file shall either:
 - declare classes / functions
 - include other files and perform actions

Zend-specific warnings
- functions should become members of a static class (Java-style?)

Controversial point
- naming for members: leading underscore? camelCase?

IMHO:
- it is important for the project to stick a coding standard, having an homogenous codebase makes browsing code easier
- unless a documentation generation tool (such as Doxygen) is used, there is no point in constraining docstring formatting (you may have noticed that PHPCS is quite strict on the matter)

**Comment by ArthurHoaro** [comment]
Well, that's good.

> line length

Maybe up to 100 chars?

> naming for members: leading underscore? camelCase?

I don't really care, we just need to chose. My vote goes to camelCase. :)

> there is no point in constraining docstring formatting (you may have noticed that PHPCS is quite strict on the matter)

You're right for useless stuff such as `@return void`, but docstrings are importants for code readability.

**Comment by virtualtam** [comment]
> Maybe up to 100 chars?

I'd go for 80 as a recommendation, and 100-120 as a hard limit. The longest lines in Shaarli are mostly:
- conditional structures that need to be rewritten
- HTML generation that can be moved to templates

+1 for camelCase and docstrings, this would give us:

```php
<?php
// index.php

require_once 'application/MyClass';

mc = new MyClass('param1');
echo mc->someMethod();
?>
```

```php
<?php
// application/MyClass.php

function myFunction1()
{
    // do stuff
}

// what about snake_case for naming functions?
function my_other_function()
{
    // do a different kind of stuff
}

class MyClass extends SomeOtherClass
{
    private $someMember;

    /**
     * Does private stuff. None of your business.
     *
     * @param string $someParam Why are you still here?
     *
     * @throws Exception You broke everything. Again.
     *
     * @return string I'm never coming back!
     */
    private someMethod($someParam)
    {
        $this->someMember = $someParam;

        if ($someParam == 'Snoopy') {
            throw new Exception('Hey!');
        }

        return 'I like trains';
    }
}
// notice the lack of the closing ?> tag
```

**Comment by ArthurHoaro** [comment]
Perfect!

Let's roll with:

    function my_other_function()

**Comment by ArthurHoaro** [comment]
PHPCS asked me to prefix private method with `_`. That feels awkward.

**Comment by virtualtam** [comment]
Yup, that's the reason behind

> Controversial point
> - naming for members: leading underscore? camelCase?

Depending on the chosen standard, the convention differs... It's a pain to have that whole lot of different, contradictory PHP coding conventions :p

There is little interest in adding _variable usage hints_,as we keep improving and documenting the code base: it becomes easier to see the _purpose_ of the different objects, and how they _interact_ (Doxygen, for instance, is able to generate class and sequence diagrams using [Graphviz](http://graphviz.org)).

**Comment by ArthurHoaro** [comment]
Moving milestone as it's something we do as a background task.

**Comment by virtualtam** [comment]
Bumping to `0.10.0` as it'd be nice to settle on a coding standard and:
- enforce it when running tests locally and under Travis
- setup a code quality checking service such as SensioLabs [Insight](https://insight.sensiolabs.com/) or [CodeClimate](https://codeclimate.com/)

I've already setup an Insight account to evaluate it on my dev fork (but am not too fond of it): https://insight.sensiolabs.com/projects/3f368e16-d9df-409c-b186-854cab3036e6

**Comment by ArthurHoaro** [comment]
Good idea. I'm not familiar with these tools, but I also see [Scrutinizer](https://scrutinizer-ci.com/) used quite often.

**Comment by virtualtam** [comment]
Scrutinizer project: https://scrutinizer-ci.com/g/virtualtam/Shaarli/

**Comment by ArthurHoaro** [comment]
Regarding PHP CodeSniffer, I suggest that we only check PSR2 syntax, and use their code beautifier tool to fix thousands of space issues, then manually fix the remaining issues. I use this method in professional projects without any issue so far. Regarding what was said in the beginning of this thread, this method is going to generate a huge diff, bit IMO it doesn't really matter. 

Other standards available with PHPCS checks more things, such as PHPDoc, but they're very strict and sometimes they doesn't match our coding style. Also, PHPCS doesn't allow us to disable single rule like ESLint allow. We can only disable group of rules within a standard, such as PEAR `FileComment` or `ValidFunctionName`.

**Comment by virtualtam** [comment]
Yep, the PHPDoc checker is quite annoying and expects comments all over the place :D

Given how the project has evolved since this issue was raised (3 years already!), I think code beautifiers could be run quite safely on all code that has unitary tests, so we can add PSR-2 checks to the CI pipeline.

**Comment by ArthurHoaro** [comment]
I've starting to work toward this. However note that PSR2 requires us to add a namespace to all classes, which should have be done at some point anyway. But it's a breaking change for 3rd parties. So it should be included in a new major. 

Could we include this in the `v0.10.0` milestone? Because maintaining such a huge diff until `v0.11` will be hard and time consuming.
