### ISSUE TITLE
directly forward users not logged in to the login page if hide_public_links is set?

### ISSUE THREAD

**Issue by thewilli** [shaarli/Shaarli#952]
I'm currently testing usability of different usage scenarios for Shaarli. Something I'd like to change is the behavior if [`hide_public_links`](https://shaarli.readthedocs.io/en/master/Shaarli-configuration/#privacy) is enabled. Currently there's just a `Nothing found` error message.

IMO this setting means that the Shaarli instance is private, and would expect the same behavior as other login-requiring services do: displaying the login page. Would you accept a PR that forwards users to the login page (for each request) if they are not logged in and `hide_public_links` is enabled?

**Comment by virtualtam** [comment]
From a usability / accessibility / ergonomics point of view, there should be a distinction between:
- an instance being private
- an instance being publicly accessible, but holding no content to display

Redirecting users to the login page is a good idea, with some adaptations:
- Atom/RSS feeds should display an empty result list (to ensure we provide valid feeds)
- content-displaying HTML pages should not appear in the main menu unless the user is logged in

This relates to #508 and requires some preliminary work not to waste development/testing efforts, as we plan to fully switch to a proper router to handle HTTP requests (this was introduced with the REST API).

@ArthurHoaro @nodiscc which release do you think we could plan this change for?

**Comment by ArthurHoaro** [comment]
> which release do you think we could plan this change for?

I'm not sure. I'd like to go on with my LinkDB refactoring before that, but I can't find much time to work on Shaarli these days. Probably v0.11?

Anyway, @thewilli suggestion isn't a really major change regarding the code, nor a really important one as I don't think this setting is widely used. I don't have a strong opinion on that matter.
