### ISSUE TITLE
Display the search terms in the HTML page title

### ISSUE THREAD

**Issue by virtualtam** [shaarli/Shaarli#954]
When performing a search (full-text or by tag), the search terms could be displayed in the page title.

This would be useful when juggling between several Shaarli search tabs :)

**Comment by ArthurHoaro** [comment]
A more generic issue would be to customize the title per page. E.g. for `Tools` -> `<Shaarli title> - Tools`.

**Comment by virtualtam** [comment]
Yup, I opened #955 to this effect; this issue is a bit more specific as it involves displaying a context-specific title.

**Comment by kalvn** [comment]
Great idea! But I would actually do the opposite: `Tools - <Shaarli title>` as in the context of the page, it's always better to go from the more specific to the less specific.

**Comment by nodiscc** [comment]
So what would it look like?

 * `My Shaarli Title - Search: searchterms` ?
 * ``My Shaarli Title - Search: more searchterms [and][tags]` ?

**Comment by kalvn** [comment]
What you propose look great. For the last case, I would say `Search: more searchterms [and][tags] - Title of the only listed link - My Shaarli Title`. Or maybe we need to choose between link title and search value.
