### ISSUE TITLE
The encode_url=false setting is ignored in shaare descriptions.

### ISSUE THREAD

**Issue by Draky50110** [shaarli/Shaarli#957]
Salut

J'ai un anonymiseur dans la config et j'ai changé l'option "encode_url" à false.

Quand je clique sur un lien dans le titre d'un shaare, ça marche sans souci.

Mais quand je clique sur un lien qui est dans la description, l'URL est alors encodée avec les % et donc inutilisable.

Il faudrait que "encode_url" soit vérifié sur la description et pas seulement le lien principal, non ?

**Comment by ArthurHoaro** [comment]
For non French speaker: the `encode_url` parameter is ignored in shaare descriptions.

Are you using the markdown plugin?

**Comment by Draky50110** [comment]
No, I don't use Markdown.
---
Pas de markdown.

**Comment by ArthurHoaro** [comment]
Hmm are you sure? Because it works fine for me with markdown disabled:

![](http://i.imgur.com/7QB6Baa.png)

However is doesn't with markdown.

**Comment by Draky50110** [comment]
Just tested : export bookmarks, delete Shaarli, install new Shaarli from scratch, import bookmark, config anonym redirector + encode_url = false : same problem !

**Comment by nodiscc** [comment]
I can reproduce this bug as well:

 * Setup a redirector in Shaarli's configuration (`https://my.redir.service/`)
 * Set `encode_url` to `false` in `config.json.php`
 * Disable the markdown plugin
 * Post a shaare (for example) pointing to `https://my.shaarli.tld/links/?searchterm=vbajkbkjsd&searchtags=foo`, also write this URL in the shaare description.

Expected results:

 * The Shaare now points to `https://my.redir.service/https://my.shaarli.tld/links/?searchterm=vbajkbkjsd&searchtags=foo`
 * The link in the description points to that same URL.

Actual results:

 * The Shaare now points to `https://my.redir.service/https://my.shaarli.tld/links/?searchterm=vbajkbkjsd&searchtags=foo` **OK**
 * The link in the description points to `https://my.redir.service/https%3A%2F%2Fmy.shaarli.tld%2Flinks%2F%3Fsearchterm%3Dvbajkbkjsd%26amp%3Bsearchtags%3Dfoo` (it is still uriencoded)

**Comment by ArthurHoaro** [comment]
Sorry, you're right, I misunderstood the original issue.
