### ISSUE TITLE
Twitter video won't work with bookmarklet

### ISSUE THREAD

**Issue by Nono-m0le** [shaarli/Shaarli#958]
Hi Team,

Not sure if it's a bug or on purpose but I can't share this link using the bookmaklet : https://twitter.com/i/videos/tweet/841902425581719552
Is it the same reason why we can't share github links ?

**Comment by thewilli** [comment]
@Nono-m0le what exactly does not work for you? What web browser and Shaarli version are you using?

I tried the following steps using the current Firefox und Chrome version and the recent Shaarli master branch, and did not encounter any error:

- Open the [link](https://twitter.com/i/videos/tweet/841902425581719552) from you
- Click on bookmarklet, add the bookmark using it
- Open Shaarli in a new tab
- Click on the recently added bookmark
- The original site is loaded again. Everything seem to work :smiley:

**Comment by ArthurHoaro** [comment]
I doesn't for me either due to [CSP](http://shaarli.readthedocs.io/en/master/Bookmarklet/#troubleshooting-the-bookmarklet-doesnt-work-with-a-few-websites-eg-githubcom) (also Firefox reports errors related to CSP).

![](https://i.imgur.com/Q4kOo6C.png)

There is nothing we can do about it though.

@thewilli did you disable CSP settings in your browsers?

**Comment by thewilli** [comment]
> @thewilli did you disable CSP settings in your browsers?

I'm using the [FF dev edition](https://www.mozilla.org/en/firefox/developer/), maybe there is an active setting to disable it. My Chrome is the regular macOS version 60, and passes the [CSP test](https://content-security-policy.com/browser-test/), but the Bookmarklet works, even with Github. Strange 😶

**Comment by ArthurHoaro** [comment]
It does work in Chrome, and not yet in the regular FF version. The issues I linked for both browsers aren't fixed yet, but I guess it's going to the right direction. In any case, that's not related to Shaarli itself.
