### ISSUE TITLE
Libraries in inc/ are not versioned/up-to-date/have no copyright

### ISSUE THREAD

**Issue by nodiscc** [shaarli/Shaarli#96]
Files in https://github.com/shaarli/Shaarli/tree/master/inc have no copyright/author notice in https://github.com/shaarli/Shaarli/blob/master/COPYING.

This violates the GPL for qr.min.js.

They have no version numbers in their filenames, and should be updated. We may provide the unminified source for jquery/qr/jquery-ui/lazyload in the archive.

**Comment by pikzen** [comment]
Fix proposed in #99
