### ISSUE TITLE
Firefox social not available under docker container with SSL reverse proxy

### ISSUE THREAD

**Issue by husimo** [shaarli/Shaarli#960]
Hello,
I have two docker containers : 

- nginx-proxy
- shaarli

I use shaarli via a nginx reverse proxy (using SSL) container. Trouble is shaarli is not aware that the connection is using https, so the Firefox social's button is not displayed.
Is there a way to correct that behavior other than modify the template file to display the Firefox social button ? 
Thank you

**Comment by virtualtam** [comment]
Hi @husimo!

This is a duplicate of #929, a fix is under review at #939

**Comment by husimo** [comment]
Okay, sorry I missed it.
Thank you ! ;)
