### ISSUE TITLE
Plugin: Add PHP script or route to make backoffice action ?

### ISSUE THREAD

**Issue by memiks** [shaarli/Shaarli#964]
Hello,

I would like to develop a plugin but I need to execute some action on the server after form is submitted.
(to retrieve new input and execute actions on it)

How can I do that ? add a route ? add a php file ?
Thanks.

BR,
Memiks.

**Comment by nodiscc** [comment]
Hi, is there anything in the [plugin system documentation](https://shaarli.readthedocs.io/en/master/Plugin-System/) that would help you?

For example the [`save_link` plugin hook](https://shaarli.readthedocs.io/en/master/Plugin-System/#save_link) - this hook will run [after the user clicks the Save button](https://github.com/shaarli/Shaarli/blob/96a1c79456b27892b9221707803f29585565b9dc/index.php#L1283).

If you can detail a bit what you're trying to achieve (purpose  of your plugin, general idea), I'm sure other contributors and plugin maintainers would be glad to help.

**Comment by ArthurHoaro** [comment]
Hi @memiks, did @nodiscc answer your question?

**Comment by memiks** [comment]
Sorry for the late reply

I try to add a plugin to be able to :
- upload by drag / drop a file
- include an image ON shaarli server (retrieve from on URL an made a cache locally)
- add sreencapture

directly from shaarli without have to upload it with an other application before.

could you tell me if I can do that ?
(I think no after read the code)

BR,
Memiks

**Comment by ArthurHoaro** [comment]
I believe it's possible with the current plugin system, using the following [hooks](https://shaarli.readthedocs.io/en/master/Plugin-System/#hooks):

  - render_editlink: add your upload/drag&drop button to the edit form
  - save_link: attach your additional form data to your link
  - render_linklist: display your image in the description, if that's what you want to do.

You can take a look at the code of the demo_plugin to get an idea of how it works.

**Comment by ArthurHoaro** [comment]
Closing as this is quite a general question, and I've tried to answer it. Feel free to re-open it if you have more question, or ask for support on Gitter regarding the plugin system.
