### ISSUE TITLE
Bookmarklet popup window is too small

### ISSUE THREAD

**Issue by nodiscc** [shaarli/Shaarli#967]
Even though the window opened by clicking the `+Shaare` bookmarklet should be 800x600 pixels https://github.com/shaarli/Shaarli/blob/master/tpl/default/tools.html#L84 it is actually smaller, roughly 600x450 px.

This hides most of the add link dialog, as shown in the screenshot:

![cap](https://user-images.githubusercontent.com/3950390/30433049-bcc25a72-9963-11e7-87d9-72e388242277.png)

An appropriate viewport size would be 630x770px

**Comment by ParoTheParrot** [comment]
I changed my bookmarklet to `height=725,width=600`

**Comment by nodiscc** [comment]
My bad, I was using a bookmarklet with `height=390,width=600` parameters (probably from an older Shaarlil install).

After re-dropping the bookmarklet from Shaarli to my bookmarks bar, the window is now large enough to fit the entire `Add link` dialog.

The actual size of the window is _not_ 800x600 though (it's 750x1016 :/). Anyway my problem is solved.
