### ISSUE TITLE
OR search

### ISSUE THREAD

**Issue by mathieucloutier86** [shaarli/Shaarli#968]
Hello,
As an information studies student, I was wondering if Shaarli could (i haven't been able to make it work if so) or intend to allow boolean search. In a very large collection of bookmarks, it seems to be a very good idea to  (at least) rely on the AND, OR and NOT operator.

Also, is there a way to create some sort of reference index that would act as a relay for equivalency terms, either being synonyms (for instance, if input "arms" the search engine would also bring up "weapons") or language translation?

I don't know how much additionnal work this would add on the developper side, since I can't code myself, but i'd tend to believe it would be a major add-on to the software.

Thank you for your work,
Mathieu

**Comment by nodiscc** [comment]
> AND, OR and NOT operator.

Hi @mathieucloutier86, [AND and NOT operators are already implemented](https://shaarli.readthedocs.io/en/master/Browsing-and-searching/). OR search is not yet possible as far as I know.

> is there a way to create some sort of reference index that would act as a relay for equivalency terms

This is not possible and would probably fall outside Shaarli's scope (minimalist/simple bookmark sharing application). I don't know whether there's a knowledge organization app that already does this?

However you could work around this by tagging your shaares and using [tag cloud filtering](https://github.com/shaarli/Shaarli/issues/959#issuecomment-327327945) which will show you all related tags. I think implementing equivalent terms/synonyms search would be a massive undertaking.

**Comment by ArthurHoaro** [comment]
Adding a OR search using the current search system seems rather complicated. Now, it assumes that all search terms are separated by an AND operator. Adding another operator would probably mean to support grouping parentheses and operators priority. 

I understand the use case, and would accept a PR, but it would probably very time consuming to develop without rewriting the whole search system made with a bunch of regexps ; so I think that's low priority.

> is there a way to create some sort of reference index that would act as a relay for equivalency terms

I agree with @nodiscc. However, if someone can provide a well established library, maybe we can work on it as a plugin?

**Comment by thewilli** [comment]
@ArthurHoaro 
> Adding a OR search using the current search system seems rather complicated. Now, it assumes that all search terms are separated by an AND operator. Adding another operator would probably mean to support grouping parentheses and operators priority.

I agree that it would be very time-consuming to add a complex syntax with groups, priorities and escapes for the operators and group elements. A compromise, which could be (quite) easily added to my regex-based wildcard search implementation, would be some kind of *lightweight OR*:
Consider the tilde `~` as an *OR* operator. The search term `foo ~bar ~baz -foobar` would then find all results where

* *foo* is included
* *foobar* is **not** included
* (at least) one of *bar* or *baz* is included

@mathieucloutier86 would this suffice your needs?
