### ISSUE TITLE
Bug: window keeps scrolling up in the addlink / editlink viewswith a long description

### ISSUE THREAD

**Issue by Lucas-C** [shaarli/Shaarli#971]
Hi.

When editing large descriptions of links (filling the screen vertically), the browser window keeps scrolling up each time I press a keystroke.

To reproduce this, copy/paste a long text in the description window.
I faced this bug with this Shaarli link I just created: https://chezsoi.org/shaarli/?OMBz0Q

**Comment by Lucas-C** [comment]
I'm using Chrome under Windows (yeah, shame on me ;) )

**Comment by ArthurHoaro** [comment]
[This function](https://github.com/shaarli/Shaarli/blob/master/tpl/default/js/shaarli.js#L276) automatically resizes the textarea. It shouldn't scroll the page, but I suppose it does for some reason.

**Comment by Lucas-C** [comment]
Thank you !
