### ISSUE TITLE
Bookmarklet (in "tools") does not include non-standard server port

### ISSUE THREAD

**Issue by mrbiber** [shaarli/Shaarli#973]
I am running shaarli on a webserver on a non-standard port (i.e. https://myserver.com:1234/shaarli). The bookmarklet ("Shaare link") that is available under tools does not include the port and thus needs to be manually adapted before it is usable. It would be great if it could automatically include the correct port!

**Comment by ArthurHoaro** [comment]
It should include the port. 

  * Which version of Shaarli are you using?
  * Which theme are you using?
  * Can you provide more information about your web server configuration (are you using a reverse proxy? which web server? etc.)

**Comment by ArthurHoaro** [comment]
Closing due to lack of feedback. Feel free to reopen if you have more information regarding this issue.
