### ISSUE TITLE
Post to Shaarli via IFTTT 

### ISSUE THREAD

**Issue by jochabod** [shaarli/Shaarli#974]
I would like be able to post to Shaarli via IFTTT's [Webhooks](https://ifttt.com/maker_webhooks) to forward to my server to make the signed API request. Can this be implemented easily? Please be kind as I'm new at this.

**Comment by virtualtam** [comment]
Hi @jochabod !

I am not familiar with IFTTT, could you describe what the service does, and in which kind of workflow you would like to integrate Shaarli with it (or the other way around)?

**Comment by ArthurHoaro** [comment]
You can publish links in Shaarli by two ways:

  * a `POST` request while logged in.
  * using the REST API while authenticated using a JWT token (see [the docs](http://shaarli.readthedocs.io/en/master/REST-API/#authentication)).

I'm not familiar but IFTTT either but I don't think it doable without another layer which performs Shaarli's authentication.

**Comment by ArthurHoaro** [comment]
Closing, the question have been answered. Feel free to reopen if it's not the case.
