### ISSUE TITLE
Feature : backup/restore all opened tabs in one click

### ISSUE THREAD

**Issue by s1dh** [shaarli/Shaarli#984]
The idea would be to backup under an appropriate "tag" (e.g. "CurrentMachineA") all opened tabs . Like this when you switch your office/home desktop e.g., you can reopen all current tabs you were working on no matter what browser you use.

We could consider a manual backup or a periodic backup (every 5 minutes e.g.)

What do you think of it ?

Regards,

**Comment by virtualtam** [comment]
Hi @s1dh!

Interacting with the browser is out of Shaarli's scope, especially given there are existing browser-native solutions for data synchronization (either built-in or community-maintained) for all major web browsers:
- https://www.mozilla.org/en-US/firefox/features/sync/
- https://support.google.com/chrome/answer/165139?co=GENIE.Platform%3DDesktop&hl=en
- https://support.microsoft.com/en-us/help/4026735/windows-sync-favorites-and-reading-list-in-microsoft-edge

Closing as "won't fix".

**Comment by nodiscc** [comment]
This feature could be part of a browser addon (https://github.com/shaarli/Shaarli/issues/825), I agree that  browser integration is out of Shaarli's scope.
