### ISSUE TITLE
Security contact

### ISSUE THREAD

**Issue by chb9** [shaarli/Shaarli#986]
Hi,

I've discovered a security issue in Shaarli v0.9.1 (also in master branch).

How can I contact (email) you privately?

**Comment by ArthurHoaro** [comment]
Hi, you can contact @virtualtam, @nodiscc and me using the email on our Github profile.

**Comment by chb9** [comment]
@ArthurHoaro Thank you.

@ArthurHoaro @virtualtam @nodiscc you've got mail.

**Comment by ArthurHoaro** [comment]
Thank you!
