### ISSUE TITLE
Some page titles are not retrieved properly

### ISSUE THREAD

**Issue by ArthurHoaro** [shaarli/Shaarli#989]
The titles aren't retrieved properly if they're not present using the `<title>` HTML tag (e.g. populated in JS, or any other exotic way).

We can extend our ways to retrieve titles. A few examples:

  - `document.title`
  - OpenGraph tag `og:title`
  - etc.
------------------
Original issue:

With the new design (I suppose), the `<title>` tag only contains `YouTube`, the actual title is populated using JS: 

```js
document.title = "Denis Brogniart :  \"AH\" - YouTube";
```

Usually, I would avoid adding specific code for specific websites, however YouTube is a common website to shaare, so maybe we should add something to retrieve the actual title.

**Comment by virtualtam** [comment]
YouTube provides a [REST API](https://developers.google.com/youtube/v3/docs/), but it requires having a Google account to create a Developer API token for authentication.

Corresponding PHP library: [php-youtube-api](https://github.com/madcoda/php-youtube-api)

**Comment by nodiscc** [comment]
> With the new design (I suppose), the <title> tag only contains YouTube, the actual title is populated using JS:

Honestly this sucks. Anyway... Shaarli gets the title correctly when either

 * sharing a youtube page from Firefox Share
 * sharing a youtube page from the bookmarklet

The only case where title fetching fails is when using `+Shaare -> Enter URL`. I don't know how widely used each workflow is. In the mean time, why not rename this issue to something generic like `Some page titles are not retrieved properly`, document it in https://github.com/shaarli/Shaarli/blob/master/doc/md/Troubleshooting.md, and see if/how the problem evolves over time?

I'd like to avoid site-specific code, even more so if we have to import whole libraries for a single website.

**Comment by ArthurHoaro** [comment]
I wasn't talking about using their API, of course, because it requires an account, authentication token management, etc.

Anyway, I agree with your suggestion @nodiscc.
