### ISSUE TITLE
Tagcloud link/page blank after 0.9.0 to 0.9.2 upgrade

### ISSUE THREAD

**Issue by dajare** [shaarli/Shaarli#991]
Title line says it all: I have a small Shaarli installation. The upgrade went fine until step 6 below:

1. Moved 0.9.0 to temp location;
2. Installed fresh 0.9.2 to my shaarli URL;
3. Copied old `/data/*` directory (+ Material template, which is what I use) into "fresh" install;
4. Looked at site in browser: beautiful!
5. Clicked on `http://www.mysite.org/myshaar/?do=tagcloud` link from the top banner/menu, and
6. Got a white screen.

I'm happy to try to help debug if someone is willing to guide me.

**Comment by ArthurHoaro** [comment]
Hi! If you get a white page, you probably have a fatal error. Can you check your web server logs?

**Comment by dajare** [comment]
And I just did what I should have done earlier: checked the Default template, which is working fine. So this is a Material issue -- I log the bug there, and close this one. (VERY fast reply, @ArthurHoaro - thanks!)

**Comment by dajare** [comment]
@kalvn - And it was just a matter of updating Material to the [latest version][1]. Sorry to be a nuisance! All working now. 

[1]: https://github.com/kalvn/Shaarli-Material

**Comment by kalvn** [comment]
No problem @dajare, I'm glad you were able to fix your issue :)
