### ISSUE TITLE
Mobile Favicon

### ISSUE THREAD

**Issue by n00b12345** [shaarli/Shaarli#997]
A logo on the title page would really be helpful. Why? I want to save Shaarli's home page on my server on my mobile devices as an icon which is a shortcut to the URL. Unfortunately because there's no logo, the icon ends up being a screenshot of the home page. Which is less than ideal. 

This shouldn't be too difficult to implement since Shaarli already has a logo.

**Comment by virtualtam** [comment]
Hi @n00b12345 !

The default Shaarli theme provides PNG icons:
- sources can be found at https://github.com/shaarli/Shaarli/tree/master/tpl/default/img
- assets can be accessed by browsing `https://<shaarli_url>/default/img/<asset>`

![shaarli-icon](https://raw.githubusercontent.com/shaarli/Shaarli/master/tpl/default/img/favicon.png)

**Comment by n00b12345** [comment]
Thanks so much @virtualtam 

When I save a webpage (say eg. Rotten tomatoes), I get a default icon as the icon of the shortcut. This doesn't happen with Shaarli. That is what I was asking.

![fullsizerender](https://user-images.githubusercontent.com/17707852/32108790-60a5749a-bb50-11e7-9f63-34603d23cc6b.jpg)

**Comment by virtualtam** [comment]
At a quick glance, it's available on mobiles thanks to:

```html
<link href="https://staticv2-4.rottentomatoes.com/static/images/iphone/apple-touch-icon.png" rel="apple-touch-icon" />
```

- https://stackoverflow.com/questions/19029342/favicons-best-practices
